tools/acrn-manager/acrnctl.h
I am currently using Yocto build and deploy UOS images, it would be
much more convenient to let the VMs to have the same names with when
they are being built. For instance, a typical image name in Yocto is
like: uos-image-weston, but it can not show the name completely with
'acrnctl list', since the length limit is 16.
Increasing the limit to 32 would fix this problem.
Tracked-On: #1837
Signed-off-by: Ming Liu <liu.ming50@gmail.com>
=> tools: acrn-manager: set MAX_NAME_LEN to 32

hypervisor/arch/x86/guest/vm.c, hypervisor/arch/x86/vtd.c, hypervisor/include/arch/x86/vtd.h
This patch series reshuffle VT-d code:
1. typo fix: dmar_uint -> dmar_unit
2. merge lines for a statement if needed.
3. add do_action_for_iommus for actions needed for all active iommus.
4. defer dmar translation enabling until create the first VM.
5. re-init interrupt configuration when resume.
6. refine error code and error handling.
Tracked-On: #1855
=> hv: vtd: code reshuffle

devicemodel/README.rst, hypervisor/README.rst
Clean up of a couple of README.rst files located respectively under hypervisor/
and devicemodel/ to remove obsolete and unmaintained information. Both hold a
basic introduction about the folder content and refer to the official
documentation website for more detailed information.
=> Documentation: clean-up of isolated README.rst files

hypervisor/arch/x86/assign.c, hypervisor/common/ptdev.c, hypervisor/include/common/ptdev.h
handle adding pass-through device entry failure cases,
instead of calling ASSERT, to avoid hypervisor crash.
Tracked-On: #1860
=> HV: handle adding ptdev entry failure cases

devicemodel/include/public/acrn_common.h, hypervisor/arch/x86/Kconfig, hypervisor/arch/x86/guest/vm.c, hypervisor/common/io_request.c, hypervisor/common/schedule.c, hypervisor/include/arch/x86/guest/vm.h, hypervisor/include/arch/x86/ioreq.h, hypervisor/include/public/acrn_common.h
This patch introduce a new mode of IO request completion, polling mode.
Now, the sketch of ioreq process can be,
A. UOS vcpu0 generate PIO/MMIO ->
B. pcpu1(vcpu0 of UOS) trap into HV ->
C. pcpu1 build ioreq, send IPI and enter idle ->
D.1 pcpu0(vcpu0 of SOS) response IPI,
D.2 pcpu0 handle the ioreq in HV, kernel, DM,
D.3 pcpu0 mark ioreq as complete,
D.4 pcpu0 hypercall to enter HV ->
E.1 pcpu0 send IPI to wake pcpu1 up
E.2 UOS vcpu0 continue running
With this change, it skips D.4, E.1 steps. In step C, pcpu1 will enter a
polling ioreq state idle after send out the IPI.
It can save about ~5000 cpu cycles.
In polling mode, we do the polling in idle instead of pause cpu all the
time. It will consume more power. A better way is to use monitor/mwait
instructions which can put cpu into a sleep …
=> hv: Add IO request completion polling feature

devicemodel/core/monitor.c
When thread_cancel() is called to exit pthread, we can't know
when the thread exit done unless pthread_join() is used to
wait for thread exit.
Tracked-On: #1868
=> acrn-dm: wait for monitor thread canceling finish

devicemodel/hw/pci/virtio/virtio_mei.c
Simple atomic add/dec cannot guarantee reference count works well
without lock. Using compare and swap operation instead.
Tracked-On: #1875
=> dm: virtio-mei: Use compare and swap primitive for refcnt

devicemodel/hw/platform/ioc.c
The signal is used to get camera right and left values.
Tracked-On: #1886
=> IOC mediator: Add VehicalSteeringWheelAngle signal to the whitelist

hypervisor/boot/reloc.c
Some data structure are only used under some condition. This patch move data
structure definition under its corresponding contion. Otherwise, it would
violate MISRA-C 413 S "User type declared but not used in code analysed".
=> hv: reloc: define data structure when necessary

hypervisor/arch/x86/assign.c
replace HV_DEBUG with CONFIG_COM_IRQ which is more reasonable
=> hv: assign: clean up HV_DEBUG usage related to vuart pin

hypervisor/arch/x86/guest/vlapic.c, hypervisor/include/arch/x86/guest/vlapic.h
Reduce the count of the "return entries".
Fix the violations which is comply with the cases list below:
1.Function has 2 return entries.
2.The first return entry is used to return the error code of
checking variable whether is valid.
Fix the violations in "if else" format.
=> hv: vlapic: fix "Procedure has more than one exit point"

tools/acrn-manager/acrn_vm_ops.c, tools/acrn-manager/acrnctl.c, tools/acrn-manager/acrnctl.h, tools/acrn-manager/acrnd.c
When UOS is sleeping, 'acrnctl list' command show it is 'paused', not
'suspended'. That is not correct. Because pausing an UOS means to block
its VCPUs immediately, otherwise suspending an UOS means to put it to
sleep.
Tracked-On: #1910 
=> tools: acrn-manager: Fix acrnctl mistake displaying suspended to paused

doc/scripts/kernel-doc
Update the 'kernel-doc' script to the latest version available from
https://github.com/projectacrn/acrn-kernel.
This solves the following error when generating the ACRN documentation:
"Unescaped left brace in regex is deprecated here (and will be fatal in Perl
5.32), passed through in regex; marked by <-- HERE in m/({ <-- HERE .*})/ at
scripts/kernel-doc line 2176."
Tracked-On: #1926
=> Documentation generation: update kernel-doc script to latest

devicemodel/samples/nuc/launch_uos.sh, doc/getting-started/apl-nuc.rst
Update the 'launch_uos.sh' script for UEFI platforms to point at the latest
iot-lts2018 kernel installed by means of the
/usr/lib/kernel/default-default-iot-lts2018 symlink which is set-up by the
kernel-iot-lts2018 bundle.
Update the Getting Started Guide to reflect this minor change.
Tracked-On: #1927
=> Update 'launch_uos.sh' script for UEFI platforms

hypervisor/arch/x86/io.c, hypervisor/arch/x86/trusty.c, hypervisor/common/hypercall.c, hypervisor/debug/profiling.c, hypervisor/lib/crypto/mbedtls/hkdf.c, hypervisor/lib/sprintf.c
v1-v2:
Bypass this case:
When binary arithmetic operators of different precedence (e.g. '+'
and '*') are mixed in an expression, parentheses are added to the
sub-expressions using the operator with a higher precedence.
v1:
The operator precedence rules are complicated and it is easy to make a mistake.
So add brackets to make operator expression more readable.
=> hv: add brackets to make operator expression more readable

hypervisor/arch/x86/guest/instr_emul.c, hypervisor/arch/x86/guest/instr_emul.h, hypervisor/arch/x86/guest/pm.c, hypervisor/arch/x86/guest/vm.c, hypervisor/arch/x86/ioapic.c, hypervisor/arch/x86/irq.c, hypervisor/boot/acpi.c, hypervisor/boot/sbl/multiboot.c, hypervisor/dm/vioapic.c, hypervisor/dm/vpci/msi.c, hypervisor/dm/vpci/sharing_mode.c, hypervisor/dm/vpic.c, hypervisor/include/dm/pci.h, hypervisor/include/dm/vpci.h
hv: vpic: fix "Procedure has more than one exit point"
Reduce the count of the "return entries".
Fix the violations which is comply with the cases list below:
1.Function has 2 return entries.
2.The first return entry is used to return the error code of
checking variable whether is valid.
Fix the violations in "if else" format.
=>  hv: fix "Procedure has more than one exit point"

doc/conf.py, doc/extensions/eager_only.py
The Sphinx .. only:: directive is limited to handling only conditional
text and can't handling conditional use of directives.  For example,
.. only:: test
.. automodule:: west.runners.core
:members:
is not handled.  This PR monkey patches the handling of the existing
.. only:: directive done by Sphinx.
See https://github.com/pfalcon/sphinx_selective_exclude for details.
=> doc: add sphinx extension improving only directive

hypervisor/arch/x86/assign.c, hypervisor/arch/x86/guest/instr_emul.c, hypervisor/arch/x86/guest/vlapic.c, hypervisor/arch/x86/trusty.c, hypervisor/arch/x86/virq.c, hypervisor/arch/x86/vtd.c
MISRA-C requires that if the return value of a function call is
assigned to a local variable, this value shall be used in all paths.
This patch moves the variable assignment right before the moment that
the variable is used.
=> hv: fix 'Function return value potentially unused'

hypervisor/arch/x86/io.c, hypervisor/common/io_request.c, hypervisor/include/public/acrn_common.h
As SOS has already adapted to the new state transition of VHM requests for a
month, the old `valid` field can now be safely obsoleted.
This patch changes the `valid` field as reserved and drops all the code that
reads or modifies this field for backward compatibility. The embedded comments
are updated accordingly, following the doxygen style.
Tracked-On: #875
=> HV: io: obsolete the valid field in vhm requests

hypervisor/dm/vpci/msix.c
The offset calculation should base on the MSI-x BAR address, not MSIX-table address.
Tracked-On: #1946
=> hv: msix: fix bug when check if msix table access

devicemodel/Makefile, devicemodel/hw/pci/virtio/virtio_coreu.c, devicemodel/hw/pci/virtio/virtio_hdcp.c
v4 -> v5
Replace strcpy with strncpy
Refine resource free if error happens
Remove meaningless *in_progress* label for pthread wait/signal
Rename the coreu thread routine name (virtio_coreu_thread)
v3 -> v4
Move setsocketopt to connect_to_daemon
Cleanup coreu file descriptor after close
Reconnect CoreU daemon if the socket descriptor is invalid
v2 -> v3
Move the daemon connection to vdev_init
Diagram the CoreU virtualization architecture
Create a seperate thread for sending and receving the CoreU message
Change the socket name
v1 -> v2
No change
v1
Initial CoreU back-end driver
Tracked-On: #1919 
Signed-off-by: Yu Shiqiang <shiqiang.yu@intel.com>
=> CoreU virtio back-end driver

devicemodel/hw/pci/core.c, devicemodel/hw/pci/virtio/virtio.c, devicemodel/include/dm_string.h, devicemodel/include/pci_core.h, devicemodel/include/virtio.h, hypervisor/arch/x86/guest/guest.c, hypervisor/arch/x86/guest/vlapic.c, hypervisor/arch/x86/io.c, hypervisor/boot/sbl/multiboot.c, hypervisor/common/io_request.c, hypervisor/dm/vioapic.c, hypervisor/dm/vpic.c, hypervisor/include/arch/x86/guest/vcpu.h, hypervisor/include/arch/x86/guest/vioapic.h, hypervisor/include/arch/x86/guest/vlapic.h, hypervisor/include/arch/x86/guest/vpic.h, hypervisor/include/arch/x86/ioreq.h, hypervisor/include/arch/x86/irq.h, hypervisor/include/arch/x86/mmu.h, hypervisor/include/arch/x86/mtrr.h, hypervisor/include/arch/x86/pgtable.h, hypervisor/include/arch/x86/vtd.h, hypervisor/include/common/irq.h
This series fixes the following issues reported by @gvancuts.
1. Absence of return values are stated in inconsistent ways in the doxygen-style comments.
1. Adjacent `@return`s are not joined by breathe, causing multiple `Return` sections in the generated doc.
=> doc: fix inconsistency and format in comments on return values

hypervisor/arch/x86/cpuid.c, hypervisor/arch/x86/guest/vmsr.c, hypervisor/arch/x86/vmx.c, hypervisor/include/arch/x86/cpuid.h
- code clean up
-  throw GP for MSR accesses if they are disabled from guest CPUID
=> hv: vMSR code cleanup

devicemodel/samples/apl-mrb/launch_uos.sh
Based on existence of /dev/vbs_k_audio file
launch AaaG with proper audio virtualization mode
Signed-off-by: Pawel Furtak <pawel.furtak@intel.com>
Tracked-On: #1915
=> Enable audio virtualization for AaaG

hypervisor/arch/x86/guest/vlapic.c, hypervisor/arch/x86/ioapic.c, hypervisor/arch/x86/trusty.c, hypervisor/arch/x86/vmx.c, hypervisor/boot/sbl/sbl_seed_parse.c, hypervisor/dm/hw/pci.c, hypervisor/include/arch/x86/irq.h, hypervisor/include/arch/x86/page.h, hypervisor/include/arch/x86/vtd.h
This patch fixes the following violations:
1. Implicit conversion: actual to formal param
2. Value is not of appropriate type
3. No cast for widening complex int expression
4. Widening cast on complex integer expression
5. Narrower int conversion without cast.
=> hv: fix type conversion violations

hypervisor/Makefile, hypervisor/arch/x86/boot/cpu_primary.S, hypervisor/arch/x86/boot/cpu_save_boot_ctx.S, hypervisor/arch/x86/boot/idt.S, hypervisor/arch/x86/boot/trampoline.S, hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/irq.c, hypervisor/arch/x86/pm.c, hypervisor/arch/x86/static_checks.c, hypervisor/arch/x86/trampoline.c, hypervisor/boot/include/reloc.h, hypervisor/boot/reloc.c, hypervisor/bsp/uefi/uefi.c, hypervisor/common/vm_load.c, hypervisor/include/arch/x86/boot/boot_context.h, hypervisor/include/arch/x86/boot/idt.h, hypervisor/include/arch/x86/guest/guest.h, hypervisor/include/arch/x86/guest/vm0_boot.h, hypervisor/include/arch/x86/trampoline.h
Boot component prepares the very basic platform boot env. It finally call
into platform initilization entries:
- bsp_boot_init & cpu_secondary_init for start up
- or restore_s3_context for wakeup
this patch move functions for AP trampoline into trampoline.c from reloc.c
=> Boot modulization

hypervisor/include/debug/sbuf.h
There APIs are removed:
- sbuf_clear_flags
- sbuf_set_flags
- sbuf_add_flags
=> hv: remove unused flags related APIs in sbuf

hypervisor/arch/x86/assign.c, hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/cpuid.c, hypervisor/arch/x86/mmu.c, hypervisor/arch/x86/mtrr.c, hypervisor/arch/x86/notify.c, hypervisor/arch/x86/pm.c, hypervisor/arch/x86/trusty.c, hypervisor/arch/x86/virq.c, hypervisor/arch/x86/vtd.c, hypervisor/debug/profiling.c, hypervisor/include/arch/x86/io.h, hypervisor/include/lib/bits.h, hypervisor/lib/memory.c
hv: fix "Procedure has more than one exit point"
Reduce the count of the "return entries".
Fix the violations which is comply with the cases list below:
1.Function has 2 return entries.
2.The first return entry is used to return the error code of
checking variable whether is valid.
Fix the violations in "if else" format.
=> hv: fix "Procedure has more than one exit point"

hypervisor/include/debug/sbuf.h
separate the function definitions into debug/release directories
to better distinguish debug/release libraries
v1 -> v2:
- sbuf_get is defined in 'debug/sbuf.c' but not used anywhere.
remove the declaration in 'include/debug/sbuf.h' and keep the
definition in 'debug/sbuf.c' in case it will used later.
- sbuf_put and sbuf_share_setup is not used under RELEASE version.
remove the file 'release/sbuf.c'.
=> hv: clean up function definitions in sbuf.h

hypervisor/arch/x86/assign.c, hypervisor/arch/x86/boot/cpu_primary.S, hypervisor/arch/x86/boot/trampoline.S, hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/ept.c, hypervisor/arch/x86/guest/guest.c, hypervisor/arch/x86/guest/vcpu.c, hypervisor/arch/x86/guest/vlapic.c, hypervisor/arch/x86/guest/vm.c, hypervisor/arch/x86/io.c, hypervisor/arch/x86/trusty.c, hypervisor/arch/x86/vmx.c, hypervisor/arch/x86/vtd.c, hypervisor/common/hypercall.c, hypervisor/debug/shell.c, hypervisor/debug/shell_priv.h, hypervisor/include/arch/x86/apicreg.h, hypervisor/include/arch/x86/cpu.h, hypervisor/include/arch/x86/guest/vcpu.h, hypervisor/include/arch/x86/guest/vlapic.h, hypervisor/include/arch/x86/guest/vm.h, hypervisor/include/arch/x86/mmu.h, hypervisor/include/arch/x86/page.h, hypervisor/include/arch/x86/per_cpu.h, hypervisor/lib/memory.c
This patch series clean up CPU_PAGE_SIZE/CPU_PAGE_SHIFT/CPU_PAGE_MASK defined in cpu.h.
=> clean up CPU_PAGE_SIZE/CPU_PAGE_SHIFT/CPU_PAGE_MASK

hypervisor/arch/x86/ioapic.c, hypervisor/dm/vpci/msix.c, hypervisor/include/arch/x86/io.h
Input parameter of mmio_write64/mmio_write32/mmio_write16/mmio_write8
should be 'void *addr' rather than 'const void *addr' since the object
pointed by 'addr' is modified in these operations.
This patch change the param type of mmio_write** and update its usage
accordingly.
=> hv: change the param type of mmio_write**

hypervisor/arch/x86/guest/vm.c, hypervisor/arch/x86/io.c, hypervisor/arch/x86/irq.c, hypervisor/arch/x86/trusty.c, hypervisor/arch/x86/virq.c, hypervisor/debug/profiling.c
fix following violations:
1."Expression is not boolean"
2."No prototype for non-static function"
3.dead code
=> hv: fix misra violations

doc/developer-guides/modularity.rst
Modularity Design doc had replicated references to citatation docs.
=> doc: fix citation references in modularity doc

doc/acrn.doxyfile, doc/developer-guides/hld/hv-timer.rst, hypervisor/include/arch/x86/timer.h
This patch adds more comment to describe functions that are
interfaces to the other modules in the hypervisor. The comments
are in doxygen-style for document generation.
=> doc: hv: add comments to timer APIs for documentation

hypervisor/lib/crypto/mbedtls/md.h
The code in comments was removed from md_wrap.c, so modify comments
to avoid confusion
Tracked-On: #1966
Signed-off-by: Chen Gang G <gang.g.chen@intel.com>
=> HV: Remove some comments for crypto library

hypervisor/arch/x86/guest/instr_emul.c, hypervisor/include/arch/x86/irq.h, hypervisor/include/arch/x86/vmexit.h, hypervisor/include/debug/logmsg.h, hypervisor/release/logmsg.c
This patch does:
- remove the unused API declaration
- fix use of uninitialized variable in instr_emul.c
=> hv: fixes related to unused API and uninitialized variable

devicemodel/core/main.c, devicemodel/hw/pci/xhci.c, devicemodel/hw/platform/usb_pmapper.c, devicemodel/include/xhci.h
1. Losing USB device(s) after resuming from S3;
2. Fail to enumerate USB device after many times of suspending and resuming;
3. Long dalay (~20 seconds) for USB headset enumeration.
Tracked-On: #1894,#1893,#1895
=> Fix some USB virtualization issues

hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/guest/vmsr.c, hypervisor/include/arch/x86/cpu.h
On platforms, that do not support APICv register virtualization, all the
x2APIC MSRs need to intercepted by ACRN for emulation.
Tracked-On: #1973
=> hv: x2APICv support on platforms w/o APICv reg virtualization

tools/acrnlog/acrnlog.c, tools/acrntrace/acrntrace.c, tools/acrntrace/acrntrace.h
If module acrn_trace is configured as "m" and we don't insert it before
launching acrntrace tool, acrntrace will run normally instead of throw
out an error in current implementation. And no trace files are generated.
It will cause confusing here.
So, this patch throw out an error massage to user about the absence of acrn
trace devices.
BTW, this patch replaces cpuid/num related concept to devid/cnt which is more
suitable for /dev/acrn_trace_xxx.
Tracked-On: #1975
=> Refine acrntrace acrnlog

hypervisor/Makefile
_FORTIFY_SOURCE is a Glibc feature which adds memory
and string function protection, this flag is only for
Glibc. The _FORTIFY_SOURCE is not used by hypervisor
because hypervisor is not include Glibc.
=> security: remove cflag _FORTIFY_SOURCE in hypervisor

hypervisor/Makefile
Hypervisor uses '-O2' compiler option,
it will omit frame pointer by default for '-O2',
This patch add 'no-omit-frame-pointer' in debug version.
Tracked-On: #1979
=> hv: add 'no-omit-frame-pointer' in debug version

devicemodel/core/main.c
The tpm patch delete the "break" for CMD_OPT_DEBUGEXIT branch.
Tracked-On: #1978
=> dm: add "break" removed by mistake.

doc/static/acrn-custom.css
Change background colors of API elements to improve readability and
match configuration documentation look.
=> doc: tweak CSS for doxygen API usability

doc/getting-started/apl-nuc.rst
1, changed Clear Linux installation from "automatically" to "manually"
2, removed bundle "soft-defined-cockpit" installation
3, removed bundle "openssh-server" installation
4, add a bundle"desktop-autostart" as the default installation. so that a desktop is showing for the first time reboot after setup done
5, add a non room user with “sudoers” privilege to avoid using root directly
6,  removed section "Device Manager memory allocation mechanism"
Tracked-On: #1794
=> doc:  update gsg to adapt latest release

doc/developer-guides/hld/hld-power-management.rst, doc/developer-guides/hld/hld-virtio-devices.rst, doc/developer-guides/hld/hld-vm-management.rst, doc/developer-guides/hld/virtio-blk.rst, doc/developer-guides/l1tf.rst, doc/developer-guides/modularity.rst, doc/getting-started/apl-nuc.rst, doc/tutorials/using_partition_mode_on_up2.rst
Fix documentation misspellings missed during the regular review.
=> doc: fix doc misspellings

hypervisor/arch/x86/mtrr.c
52 S Unsigned expression negated.
Negating unsigned integer leads to confusion.
=> hv: fix one MISRA-C violation in mtrr.c

hypervisor/arch/x86/guest/vmsr.c
127 S MISRAC requires that the array size should be declared explicitly.
=> hv: fix "Array has no bounds specified" in vmsr.c

hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/page.c, hypervisor/arch/x86/vtd.c, hypervisor/boot/acpi.c, hypervisor/boot/dmar_parse.c, hypervisor/boot/include/acpi.h, hypervisor/boot/include/acpi_priv.h, hypervisor/common/hypercall.c, hypervisor/common/vm_load.c, hypervisor/include/arch/x86/zeropage.h, hypervisor/include/public/acrn_common.h
v1-v2:
Make clear which page table page used for which level, ie rename pgtable_page to pml4/pdpt/pd/pt_page.
v1:
Identifier reuse may arise confusion. So should minimize the case of it
as much as possible. This patch is try to do this except the PCI related
module.
=> minimize the case of "identifier reuse"

devicemodel/samples/nuc/launch_uos.sh
this patch is for updating path of the UOS image in launch_uos.sh script to adapt latest getting started guide, 
Tracked-On: #2003 
=> DM: updating launch_uos.sh

devicemodel/arch/x86/pm.c, devicemodel/core/mevent.c, devicemodel/core/timer.c, devicemodel/hw/pci/virtio/vhost.c, devicemodel/hw/pci/virtio/virtio_console.c, devicemodel/hw/pci/virtio/virtio_input.c, devicemodel/hw/pci/virtio/virtio_mei.c, devicemodel/hw/pci/virtio/virtio_net.c, devicemodel/hw/uart_core.c, devicemodel/include/mevent.h
This is the first cycle mevent race issue fixing patch. It includes the core API change and the CSE mediator code update according to new API.
Tracked-On: #1877
=> Mevent fix1 push

hypervisor/arch/x86/guest/vcpu.c, hypervisor/arch/x86/guest/vlapic.c, hypervisor/arch/x86/guest/vmsr.c, hypervisor/arch/x86/trusty.c, hypervisor/arch/x86/vmx.c, hypervisor/include/arch/x86/guest/guest.h, hypervisor/include/arch/x86/guest/vcpu.h
- moved guest_msrs[] from struct acrn_vcpu to struct acrn_vcpu_arch
- create per world world_msrs[] to help emulate MSRs that need world isolation
- cleanup IA32_PAT and TSC_DEADLINE code according new data structure
=> hv: vMSR reshuffling: rearrange emulated MSR data structures

devicemodel/hw/pci/xhci.c
After mutiple usb devices send enable slot commnad and get slot id each
other, address device setup flow is not sorted by slot id. According to
current design, it will casue assert failure. This patch takes off this
restriction.
Tracked-On: #2017
Signed-off-by: Yang Liang <liang3.yang@intel.com>
=> DM: xHCI: unbind slot id and ndevices relationship.

devicemodel/samples/apl-mrb/runC.json, devicemodel/samples/nuc/runC.json
This patch adds the runC container config file, we will run acrn-dm
in runC container, and set acrn QoS parameters based on runC.
In the config file we mount SOS root directory to the container and
disable network/mount/ipc namespace.
Tracked-On: projectacrn/acrn-hypervisor#2020
=> ACRN: Add runC container sample config file

devicemodel/core/main.c
To fix the issue that watchdog reset hang issue. At previous change,
we assume the reset comes from guest. But watchdog reset or dm killed
by signal is different. It's possible the vm_loop stick on ioreq
attaching.
The new fixing has two parts:
- fixing from kernel side to remove the race issue in ioreq attach,
req_complete_notify and client destory.
- Move the client destroy before waiting of vm_loop exit.
Tracked-On: #1986
Reviewed-by: Liu Shuo <shuo.a.liu@intel.com>
=> dm: adjust the sequence of destroy client and wait for vm_loop exit

devicemodel/hw/pci/virtio/virtio_input.c
EV_MSC is configured as INPUT_PASS_TO_ALL in input driver. There is
a loop in the use case of virtio-input. They should not be forwarded
back to BE since they have already been sent to native driver before
sending to FE.
Tracked-On: #2006
=> dm: virtio-input: ignore all MSC events from FE

doc/conf.py
With the 0.4 release, we can now add the 0.4 doc version menu option
=> doc: add 0.4 to doc version menu

hypervisor/Makefile, hypervisor/arch/x86/boot/trampoline.S, hypervisor/arch/x86/mmu.c, hypervisor/bsp/ld/link_ram.ld.in, hypervisor/include/arch/x86/mmu.h
- enable NX feature in hypervisor:
1. Set 'XD' bit for all pages, including pages for guests
when initialize MMU tables in hypervisor.
2. remove 'XD' bit for pages that contain hypervisor instructions.
3. enable MSR EFER.NXE,which will enable page access restriction by
preventing instruction fetches form pages with XD bit set.
- remove "-Wl -z noexecstack" GCC flag option in hypervisor
Makefile as it would not affect stack attribute in hyervisor,
which setup stack itself, instead of by loader.
v2 update:
1) move variable(_ld_text_end) declaration from cpu.h to mmu.h
2) add more comments
=> hv[v2]: enable NX in hypervisor

tools/acrn-manager/acrnctl.c
The 'acrnctl reset' command stop an UOS and restart it again.
When UOS takes more than 10s to shutdown, that cause 'acrnctl reset'
command fail, and the UOS is not restarted. But in fact, UOS can
shutdown successfully.
This problem can be solved if 'acrnctl reset' wait a little longer
for UOS shutdown.
Tracked-On: #2016
=> tools: acrnctl: Change STOP_TIMEOUT to 30s

doc/tutorials/building_uos_from_clearlinux.rst
Upload the tutorial of "Build UOS from Clear Linux"
1.  Introduce how to use "uos-image.json" to set configuration for building UOS image and kernel together
2.  No more 
"$ cp -r ~/uos-kernel-build/usr/lib/modules/4.19.0-22.iot-lts2018/ /mnt/lib/modules/
$ cp -r ~/uos-kernel-build/usr/lib/kernel /lib/modules" 
needed when use the image built by "ister";
Signed-off-by: Xie, zhengtian zhengtian.xie@intel.com
=> Doc: Upload the tutorial of "Build UOS from Clear Linux"

doc/user-guides/acrn-dm-parameters.rst
Use a table instead of a dictionary list to make the parameter
description layout more readable.
=> doc: improve acrn-dm param layout

doc/release_notes_0.3.rst, doc/release_notes_0.4.rst, doc/user-guides/acrn-dm-parameters.rst, tools/acrntrace/README.rst
Sphinx transforms ``--`` into an en-dash within a paragraph (not within
a code, pre, or kbd block though).  This presents a problem documenting
command parameters such as ``--name`` where the ``--`` is transformed
into a single en-dash.  Rather than disabling all smartquote
transformations in the Sphinx conf.py (setting ``smartquotes = False``),
we fixes cases where ``--`` should not be transformed by using a block
that is ignored by the smartquote transformation.
=> doc: fix use of double dashes

devicemodel/Makefile, devicemodel/core/hugetlb.c, devicemodel/core/main.c, devicemodel/core/sw_load_bzimage.c, devicemodel/core/sw_load_common.c, devicemodel/core/sw_load_elf.c, devicemodel/core/sw_load_ovmf.c, devicemodel/core/sw_load_vsbl.c, devicemodel/core/vmmapi.c, devicemodel/include/dm.h, devicemodel/include/sw_load.h, devicemodel/include/vmmapi.h, doc/developer-guides/hld/hld-devicemodel.rst, doc/user-guides/acrn-dm-parameters.rst
Add support for loading OVMF into the High BIOS area and booting it from acrn-dm.
Use generic code for BIOS/ROM image loading at High BIOS region.
Tracked-On: #1832
=> dm: add OVMF booting support

hypervisor/common/hv_main.c, hypervisor/debug/profiling.c, hypervisor/include/debug/profiling.h, hypervisor/release/profiling.c
This patch fixes incorrect vm_id captured when sampling PMU data. Currently,
the vm_id gets attributed to ACRN hypervisor, rather than actual guest vm_id.
The issue is identified that the existing code captures the guest vm info
after vmexit_hander function is completed, in which the profiling module
points its context to VMM. When the vmexit happens by PMI, the guest context
should be captured so that the attribution to proper guest vm can happen.
This change will also allow to capture more accurate TSC when vmexit happens.
Tracked-On: #2043
=> profiling: split profiling_vmexit_handler into two functions

hypervisor/Makefile, hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/init.c, hypervisor/debug/dump.c, hypervisor/include/arch/x86/cpu.h, hypervisor/include/arch/x86/init.h
reorg both init functions, separate the initilization of different
components.
v2:
- separate into 2 patches, 1 for reorg, 1 for pure move.
Acked-by: Xu, Anthony <anthony.xu@intel.com>
=> Init modulization upstream

devicemodel/hw/platform/tpm/tpm_emulator.c
There are several issues which uninitialized variables
are used. This patch will fix those issues.
Tracked-On: #2052
Signed-off-by: weideng <wei.a.deng@intel.com>
Signed-off-by: yingbinx <yingbinx.zeng@intel.com>
Reviewed-by: Zhu Bing <bing.zhu@intel.com>
=> dm: Fix issues for tpm_emulator

hypervisor/arch/x86/guest/vmsr.c, hypervisor/arch/x86/trusty.c, hypervisor/include/arch/x86/guest/vcpu.h
Intercept IA32_TSC_ADJUST MSR so that writing IA32_TSC_ADJUST from the
guests won't impact the TSC in root mode or potentially other vCPUs in
the same pCPU.
- MSR TSC_ADJUST needs to be isolated between normal and secure world,
so it's included in NUM_WORLD_MSRS.
- Upon writing to either IA32_TSC_ADJUST or IA32_TSC from the guests,
don't write to physical MSRS so it won't impact the host side, but
update the TSC offset VM-execution control.
- don't need to intercept rdmsr for IA32_TIME_STAMP_COUNTER.
- add the missing statement in save_world_ctx() to save the tsc_offset
during world switch.
=> hv: emulate IA32_TSC_ADJUST MSR

hypervisor/arch/x86/ept.c, hypervisor/arch/x86/timer.c, hypervisor/lib/string.c
This is a simple demo. If this could work for almost the case, will apply it.
refine strnlen_s/strstr_s to only one exit point
timer: fix procedure has more than one exit point
remove goto in ept_violation_vmexit_handler
Signed-off-by: Li, Fei1 fei1.li@intel.com
=> Coding style: try to make a function to only one exit point and don't use goto

devicemodel/hw/pci/virtio/vhost.c, devicemodel/hw/pci/virtio/virtio_console.c, devicemodel/hw/pci/virtio/virtio_input.c, devicemodel/hw/pci/virtio/virtio_net.c, devicemodel/include/vhost.h
This patchset is to follow up the new mevent APIs implemented by Fengwei.
Teardown callbacks are added to mevent to make sure the resources are freed safely.
The following drivers are changed:
virtio-input
virtio-console
virtio-net
vhost-proxy
Tracked-On: #1877
=> Virtio mevent teardown

devicemodel/core/monitor.c, devicemodel/hw/platform/tpm/tpm_crb.c, devicemodel/hw/platform/usb_pmapper.c, tools/acrn-manager/acrn_mngr.c
When issue happen, we could identify which thread is impacted.
This could help stability issue debugging.
Tracked-On: #2037
=> dm: set correct thread name

hypervisor/arch/x86/assign.c, hypervisor/arch/x86/cpu.c, hypervisor/common/hypercall.c, hypervisor/common/ptdev.c, hypervisor/include/public/acrn_common.h
- cpu_secondary_init() @cpu.c
- ptirq_intx_pin_remap() @ assign.c
etc.
=> hv: fix possible buffer overflow issues

hypervisor/arch/x86/guest/vmsr.c, hypervisor/arch/x86/vmx.c, hypervisor/include/arch/x86/guest/guest.h
106D No prototype for non-static function.
2 functions missing prototyle declarations in header file.
120S Use of bit operator on signed type.
123S Use of underlying enum representation value.
enum values are treated like unsigned integer in vmsr.c
=> hv: vmsr: fix MISRA_C violations

hypervisor/dm/vpci/msix.c, hypervisor/dm/vpci/pci_priv.h, hypervisor/include/dm/pci.h
36D Prototype and definition name mismatch
pci_scan_bus() and sharing_mode_find_vdev() wrong parameter in prototype.
14D Attempt to change parameter passed by value.
vmsix_table_rw() uses function parameter as local viarable.
=> hv: vpci: 2 MISRA-C violation fixes

devicemodel/hw/pci/xhci.c
When doing S3 with many USB devices connected, there is a high probability
that UOS fails to enumerate all of them. This patch set is used to fix
this issue.
Tracked-On: #1893
=> Fix a bug for USB S3

doc/developer-guides/hld/hv-timer.rst, hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/init.c, hypervisor/arch/x86/irq.c, hypervisor/arch/x86/timer.c, hypervisor/common/schedule.c, hypervisor/include/arch/x86/cpu.h, hypervisor/include/arch/x86/timer.h
these two patches removed check_tsc function and refined cpu_dead function.
=> remove check_tsc and refine cpu_dead

devicemodel/hw/pci/ahci.c, devicemodel/hw/pci/core.c, devicemodel/hw/pci/gsi_sharing.c, devicemodel/hw/pci/gvt.c, devicemodel/hw/pci/npk.c, devicemodel/hw/pci/passthrough.c, devicemodel/hw/pci/virtio/virtio_mei.c, devicemodel/hw/platform/acpi/acpi.c, devicemodel/include/pci_core.h
Replace banned functions with permitted string APi in device-model hw directory.
1.Replace sscanf with permitted string API
2.Replace strlen with strnlen
3.Replace sprintf with snprintf
Tracked-On: #2079
Reviewed-by: <yonghua.huang@intel.com>
Acked-by: Yu Wang <yu1.wang@intel.com
=> In device-model, sscanf, strlen and sprintf API is banned, so replace them with permitted API.

hypervisor/dm/vpci/msix.c, hypervisor/dm/vpci/partition_mode.c, hypervisor/dm/vpci/sharing_mode.c, hypervisor/dm/vpci/vpci.c, hypervisor/include/arch/x86/guest/vm.h, hypervisor/include/dm/vpci.h
13X: Identifier reuse: tag vs component.
A tag name shall be a unique identifier
Change the following names:
struct msi --> struct pci_msi
struct msix --> struct pci_msix
struct vpci --> struct acrn_vpci
union cfgdata -> union pci_cfgdata
=> hv: MISRA-C fix "identifier reuse" in vpci code

hypervisor/arch/x86/ept.c, hypervisor/arch/x86/guest/vm.c, hypervisor/arch/x86/vtd.c, hypervisor/include/arch/x86/guest/vm.h
For security, this patch add one flag per vm and disable snoop control
for sos and enable snoop control for uos by default.
v2: add one flag in vm, not in iommu domain.
Tracked-On: #2086
Signed-off-by: Zhipeng Gong <zhipeng.gong@intel.com>
=> hv: enable/disable snoop control bit per vm

hypervisor/arch/x86/cpu.c, hypervisor/include/arch/x86/cpufeatures.h, hypervisor/include/arch/x86/msr.h, hypervisor/include/lib/rtl.h, hypervisor/lib/memory.c
1) ACRN will use enhanced rep fast-string operation by default. So check this capability  at the very beginning.
2) Use enhanced rep fast-string operation to refine memset/memcpy_s.
=> HV: Refine memset and memcpy_s

hypervisor/common/ptdev.c
- 'buffer'with size of 'buffer_cnt',  will overflow in
next loop if 'index == buffer_cnt - 1'.
=> hv:fix possible buffer overflow in 'ptirq_get_intr_data()'

hypervisor/include/lib/rtl.h, hypervisor/lib/memory.c
hv: coding style: refine memory.c
1) Variable names shall start with a lower-case letter.
2) Multiplication and division come before addition and subtraction.
Everything else should be in parentheses.
=> coding style: refine memory.c

hypervisor/arch/x86/guest/vm.c, hypervisor/common/hypercall.c, hypervisor/include/arch/x86/guest/vm.h
-- fix MISRA-C violation "procedure has more than one exit point"
for this api
-- change start_vm to void type since it is always return 0
=> hv:refine prepare_vm0 api

hypervisor/arch/x86/guest/vmtrr.c, hypervisor/dm/vioapic.c, hypervisor/dm/vpic.c
7C: Procedure has more than one exit point.
=> hv: refine a few functions to only one exit point

hypervisor/dm/vpci/hostbridge.c, hypervisor/dm/vpci/msi.c, hypervisor/dm/vpci/msix.c, hypervisor/dm/vpci/partition_mode.c, hypervisor/dm/vpci/pci_priv.h, hypervisor/dm/vpci/pci_pt.c, hypervisor/dm/vpci/sharing_mode.c, hypervisor/include/dm/vpci.h
78D: Global variable should be declared const.
Global variables should be declared constant wherever possible to
avoid unintentional modification.
27D: Variable should be declared static
pci_ops_vdev_msi is not accessed by other files. Remove the declaration
from the header and define it with the static qualifier; Because it's
referenced by populate_msi_struct(), so move the define statements forward.
33D: No real declaration for external variable
certain variables are available in sharing mode or partition mode only,
so that the declarations in header files must be enclosed with
CONFIG_PARTITION_MODE
=> hv: vpci: fix MISRA-C violations related to variable declarations

hypervisor/arch/x86/guest/pm.c, hypervisor/arch/x86/pm.c, hypervisor/arch/x86/wakeup.S, hypervisor/boot/acpi.c, hypervisor/include/arch/x86/host_pm.h
1. move out vm related code from arch/pm.
2. remove unnecssary global variables.
3. keep the global variables as static, not used
by other modules directlly.
=> HV: modularization to refine pm related code.

hypervisor/arch/x86/guest/vmsr.c, hypervisor/dm/vpci/core.c, hypervisor/dm/vpci/hostbridge.c, hypervisor/dm/vpci/msi.c, hypervisor/dm/vpci/msix.c, hypervisor/dm/vpci/pci_priv.h, hypervisor/dm/vpci/pci_pt.c, hypervisor/dm/vpci/sharing_mode.c, hypervisor/include/arch/x86/guest/guest.h, hypervisor/include/dm/vpci.h
MIRSA-C requires the const qualifier should be applied to pointer parameters
that address data not subject to change in rule 120D.
Tracked-On #861
=> hv: fix MISRA-C violations "Pointer param should be declared pointer to const."

hypervisor/Makefile
We have used the option --ffreestanding to assert hypervisor
is a freestanding environment, and hypervisor does not include
standard library.
"-Wformat/-Wformat-security"
Check calls to the standard library functions printf and scanf, etc.,
to make sure that the arguments supplied have types appropriate to
the format string specified, and that the conversions specified in
the format string make sense. these flags disabled by -ffreestanding
or -fno-builtin.
=> security: remove gcc flags Wformat Wformat-security in HV

hypervisor/arch/x86/vmcs.c, hypervisor/arch/x86/vmx.c
hv: fix the MISRA-C violations related to VMCS
This patch series fix the MISRA-C violations related to VMCS.
=> hv: fix the MISRA-C violations related to VMCS

hypervisor/arch/x86/ioapic.c, hypervisor/arch/x86/notify.c, hypervisor/include/arch/x86/ioapic.h
IEC 61508, ISO 26262 standards highly recommand single-exit rule.
=> Misrac fix

hypervisor/arch/x86/cpu_caps.c, hypervisor/arch/x86/mmu.c
1) Separate ASM and C code inserts as pure procedures with a defined interface.
2) Fix procedure has more than one exit point.
=> hv: coding style: refine mmu.c

devicemodel/hw/pci/passthrough.c
This patch series remaps msix table to user space in DM passthru driver (in VM0).
The accesses in dm passthru driver to pci config space and msix table is in VM0, and will be trapped by HV io/mmio handler registered for VM0.
Tracked-On: #1782
=> dm: passthru: simplify msi/msix handling

hypervisor/common/ptdev.c, hypervisor/include/common/ptdev.h
This patch fixs MISRAC violations in common/ptdev.c and include/common/ptdev.h
=> hv: ptdev: fix MISRAC violations

hypervisor/arch/x86/assign.c, hypervisor/include/arch/x86/assign.h, hypervisor/include/common/ptdev.h
This patch series fixes the MISRA-C violations in arch/x86/assign.c
=> hv: assign: fix MISRA-C violations

hypervisor/debug/hypercall.c, hypervisor/include/public/acrn_hv_defs.h
acrntrace/log kernel modules will use this hypercall to fetch
pcpu num of hardware platform. Then, initialize driver accordingly.
Tracked-On: #1775;#1776
=> Debug: Add one hypercall to quary hardware info

hypervisor/include/arch/x86/gdt.h
There is no no real declaration for these external variables. So just
remove them.
=> hv: coding style: remove no real declaration for external variable

devicemodel/hw/pci/xhci.c
S3 emulation is complicated and greatly dependent on system timing,
hence this patch changes log level for some important logs to help
online debugging (could output log by modifing launch_uos.sh and
without re-compiling)
Tracked-On: #1893
=> DM USB: xHCI: change log level of some logs for S3 online debugging

hypervisor/arch/x86/trusty.c, hypervisor/common/trusty_hypercall.c, hypervisor/include/arch/x86/trusty.h
v2-v3:
1) Split the semantics change from MISRAC change.
2) minor change about not only the function to meet only  one exit but also the coding style not too ugly
v1-v2:
Split the patch into three small one.
Fix procedure has more than one exit point
Tracked-On: #2120
=> Optimize trusty logic to meet MISRA-C rules

devicemodel/samples/up2/launch_uos.sh
Physical NIC mac address is used for generate UOS mac address.
This patch uses a new parameters to pass this information
instead of vm name.
Tracked-On: #1987
Reviewed-by: Jie Deng <jie.deng@intel.com>
=> dm: pass mac seed not to use vm name on UP2

hypervisor/arch/x86/guest/vcpuid.c
1) eliminate recursion in find_vcpuid_entry
2) Fix procedure has more than one exit point
=> Cpuid: refine coding style

doc/getting-started/apl-nuc.rst
A stray empty code block is removed, along with trailing spaces
=> doc: fix formatting in NUC GSG

hypervisor/arch/x86/assign.c, hypervisor/arch/x86/ioapic.c, hypervisor/arch/x86/irq.c, hypervisor/arch/x86/pm.c, hypervisor/debug/shell.c, hypervisor/debug/vuart.c, hypervisor/include/arch/x86/hv_arch.h, hypervisor/include/arch/x86/ioapic.h
This adds few functions to access the daata structures
defined inside ioapic.c. Removes the same data structures
from ioapic.h
Also this modifies some of the names of existing APIs to
conform to the ioapic module name.
Modified gsi_table identifier to gs_table_data, to avoid
a MISRA C Violation.
=> Patch for modularising ioapic.[c/h] and related files.

hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/guest/vcpu.c, hypervisor/arch/x86/init.c, hypervisor/common/hv_main.c, hypervisor/common/schedule.c, hypervisor/include/arch/x86/guest/vcpu.h, hypervisor/include/arch/x86/hv_arch.h, hypervisor/include/common/schedule.h
this patch series reshuffle scheduler functions, it make basic scheduler
functions to be based on struct sched_object, and make it as a field in
struct vcpu to specify vcpu schedule related operations.
Acked-by: Eddie Dong <edide.dong@intel.com>
=> modularization for scheduler

hypervisor/arch/x86/cpu_state_tbl.c
This patch fixes the MISRA-C violations in arch/x86/cpu_state_tbl.c
* make the function have only one exit point
=> hv: cpu_state_tbl: fix multiple exits

hypervisor/Makefile, hypervisor/arch/x86/mmu.c, hypervisor/include/arch/x86/cpu.h, hypervisor/include/arch/x86/guest/vm.h, hypervisor/include/lib/bits.h
1) Try to minimize the C code in inline assembly function. Now only
construct data structure and return a value is permitted.
2) Refine the remaining functions in the head file to one exit point
=> hv: coding style: refine inline assembly use and one function one exit

devicemodel/include/virtio.h
As VIRTIO_CONFIG_S_NEEDS_RESET is not defined in standard virtio header
file on ubuntu, there will be compile issue. so add
VIRTIO_CONFIG_S_NEEDS_RESET to fix it.
Tracked-On: #2145
=> dm: virtio: fix compile issue on ubuntu

hypervisor/arch/x86/guest/vcpuid.c
According to SDM Vol. 2A 3-191 & Vol. 2A 3-213, leaf 02h has no subleaf.
This patch removes the un-needed code.
=> hv: vcpuid: leaf 02h has no subleaf

hypervisor/arch/x86/virq.c
hv: virq: refine vcpu_inject_hi_exception()
The MISRA-C Standards suggests use brackets to clarify the precedence order of logical conjunctions.
hv: virq: refine vcpu_inject_vlapic_int() has more than one exit point
The MISRA-C Standards suggests procedures to be single exit.
=>  hv: virq: refine hypervisor/arch/x86/virq.c for MISRA C standards 

hypervisor/arch/x86/guest/vmcall.c
Remove the goto by split the function into two,
dispatch_hypercall and vmcall_vmexit_handler.
=> hv: vmcall: fix "goto detected" violations

hypervisor/arch/x86/cpu_caps.c, hypervisor/arch/x86/vmcs.c
This patch fixes the duplicated functions introduced by cpu caps
modularization.
In cpu caps modularization, function `is_vmx_disabled` was supposed
to be moved from `arch/x86/vmcs.c` to`arch/x86/cpu_caps.c`,
but the original one was not removed.
=> hv: remove duplicated `is_vmx_disabled`

hypervisor/arch/x86/vtd.c, hypervisor/include/arch/x86/vtd.h
This patch does the following changes
According to VT-d spec Section 6.8 "Write Buffer Flushing" DRAM write buffers
are flushed implicitly upon Remapping Hardware Caches Invalidation even on
platforms that set RWBF to 1 in capability register. So removed write buffer
flushing as current ACRN issues cache invalidation commands in all cases.
Tracked-On: #1855
=> hv: Write Buffer Flush - VT-d

hypervisor/arch/x86/guest/vcpuid.c
cpuid leaf 0dh is percpu related, no need to init in vcpuid_entries for vm.
=> hv: vcpuid: leaf 0dh is percpu related

hypervisor/arch/x86/io.c
This patch fixes the MISRA-C violations in arch/x86/io.c
* make the for loop have only one `break`
=> hv: io: fix MISRA-C violations related to break

hypervisor/common/hypercall.c, hypervisor/common/vm_load.c, hypervisor/lib/sprintf.c
Fix the violations list below:
1.Procedure has more than one exit point.
2.Use of sizeof on an array parameter.
3.Expression needs brackets.
=> hv: fix sprintf and hypercall violations

hypervisor/arch/x86/mmu.c, hypervisor/include/arch/x86/mmu.h
- bugfix:the actual 'size' of memory region that
to be updated is incorrect.
- replace CONFIG_UEFI_STUB with DMAR_PARSE_ENABLED
when update memory pages for ACPI_RECLAIM region,
as DMAR_PARSE_ENABLED may be enabled on non-EFI
platform.
V2 update:
wrap roundup to 2M and rounddown to 2M inline
functions.
Tracked-On: #2056
=> HV: [v2] bugfix in 'hv_access_memory_region_update()'

hypervisor/arch/x86/vtd.c
this patch fix following violations:
- Use of single line comment(s).
- Logical conjunctions need brackets.
- More than one break or goto statement in loop.
=> hv:vtd: fix additional violations in vtd.c

hypervisor/arch/x86/ioapic.c
This patch mainly do the following:
Make pic_ioapic_pin_map static const by MISRA-C's requirement.
Make legacy_irq_to_pin and legacy_irq_trigger_mode static const as we will never change it.
=> HV: x86: Fix "Variable should be declared static"

hypervisor/debug/shell.c, hypervisor/debug/string.c, hypervisor/include/lib/rtl.h
this function is not from libc but has the same name,
atoi() in libc is unbounded and not safe.
replace this function with 'strtol_deci()' in this case.
Tracked-On: #2187
=> hv: remove the usage of 'atoi()'

Makefile, devicemodel/Makefile
This patch fix a bug due to use of deprecated PLATFORM and add `install-samples-up2` rule.
Tracked-On: #1995
=> Makefile: Add UP2 related stuff

doc/static/acrn-custom.css
Coding guidelines have examples for compliant and non-compliant code,
but they look the same when rendered as HTML.  Add a CSS style for
non-compliant-code examples with a red-tinted background.
Usage is:
```
.. rst-class:: non-compliant-code
.. code-block:: c
a=b=c=0;
```
or, for example:
```
.. rst-class:: non-compliant-code
Here's an example of non-compliant code::
a=b=c=0;
```
=> doc: add CSS for non-compliant code examples

hypervisor/common/trusty_hypercall.c
=> hv: tursty_hypercall: fix "Procedure has more than one exit point"

hypervisor/arch/x86/guest/vcpuid.c, hypervisor/include/arch/x86/cpuid.h
Two changes:
1. cpuid leaf 07h has subleaf:
According to SDM 3-194 Vol.2A, Table 3-8, cpuid leaf 07h has sub-leaves.
cpuid.07.eax reports the maximum input for sub-leaves.
Since there is no definition for subleaf > 0 in SDM, hv only supports subleaf 0.
2. In currently hv code, cpuid leaf function 14h is disabled,
CPUID.07H:EBX.INTEL_PROCESSOR_TRACE should be disabled as well.
Tracked-On: #2198
=> hv: vcpuid: cpuid leaf 07h has subleaf

devicemodel/hw/pci/lpc.c, devicemodel/hw/pci/uart.c, devicemodel/hw/pci/virtio/virtio_mei.c, devicemodel/hw/uart_core.c, devicemodel/include/uart_core.h
This patchset apply the new mevent API (mevent_add with teardown callback) to uart_core.c
Tracked-On: #1877
=> Mevent uart core fix push

hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/guest/vcpu.c, hypervisor/arch/x86/io.c, hypervisor/arch/x86/vtd.c, hypervisor/common/hv_main.c, hypervisor/common/io_request.c, hypervisor/common/schedule.c, hypervisor/debug/dump.c, hypervisor/include/arch/x86/cpu.h, hypervisor/include/arch/x86/ioreq.h, hypervisor/include/common/schedule.h, hypervisor/include/debug/logmsg.h
IO completion polling will access vcpu and vm structs. If doing it in idle
thread, there might be some race issues between vm destroying and idle
thread. They are running on different cores.
Got suggestion from Fengwei, decouple the polling action from idle thread
and just do it in vcpu thread, then we can guarantee idle thread in really idle
status.
Tracked-On: #1821 
=>  hv: decouple IO completion polling from idle thread

hypervisor/common/schedule.c
=> hv: schedule: fix "Procedure has more than one exit point"

hypervisor/arch/x86/mmu.c, hypervisor/debug/shell.c, hypervisor/include/arch/x86/mmu.h, hypervisor/include/lib/rtl.h, hypervisor/lib/string.c
porting security patch from master branch to apl_sdc_stable branch
HV: [v2] bugfix in 'hv_access_memory_region_update()' :
Tracked-On: #2056
hv: remove the usage of 'atoi()' :
Tracked-On: #2187 
=> hv: porting security patch from master branch to apl_sdc_stable branch

devicemodel/samples/up2/launch_uos.sh
Space is tampered with unseen characters.
Tracked-On: #1995
=> script: fix launch_uos script issue due to unseen character

devicemodel/hw/pci/lpc.c, devicemodel/hw/pci/uart.c, devicemodel/hw/pci/virtio/virtio_mei.c, devicemodel/hw/uart_core.c, devicemodel/include/uart_core.h
This patchset apply the new mevent API (mevent_add with teardown callback) to uart_core.c
Tracked-On: #1877
Signed-off-by: Yin Fengwei fengwei.yin@intel.com
=> Mevent uart core for sdc stable

devicemodel/hw/platform/acpi/acpi.c, devicemodel/include/acpi.h
Expose a new ACPI table PSDS to UOS.
This PSDS table show the security capability of the VM.
Only enable this table in UOS when PSDS presented in SOS.
Tracked-On: #888
=> dm: acpi: add PSDS table in ACPI table

hypervisor/arch/x86/assign.c, hypervisor/include/arch/x86/irq.h
Replace PAGE_SHIFT with MSI_ADDR_DEST_SHIFT in ptirq_build_physical_msi(), since it's not correct in semantics.
Tracked-On: #2209
=> hv: fix mis-usage of "PAGE_SHIFT"

hypervisor/dm/vioapic.c
With kernel 4.19, it's possible that same irq vector assigned
to different devices on different cpu.
So when we update the tmr, we should update the value for cpu
which is irq target.
Tracked-On:  #2212 
=> hv: fix sos kernel hang when migrate irq to different cpu

devicemodel/core/main.c, devicemodel/core/vmmapi.c, devicemodel/include/public/vhm_ioctl_defs.h, devicemodel/include/vmmapi.h, hypervisor/arch/x86/io.c, hypervisor/common/hv_main.c, hypervisor/common/io_request.c, hypervisor/common/schedule.c, hypervisor/include/arch/x86/ioreq.h, hypervisor/include/common/schedule.h
hv: decouple IO completion polling from idle thread
IO completion polling will access vcpu and vm structs. If doing it in
idle thread, there might be some race issues between vm destroying and
idle thread. They are running on different cores.
Got suggestion from Fengwei, decouple the polling action from idle
thread and just do it in vcpu thread, then we can guarantee idle thread
in really idle status.
Tracked-On: #1821
=> [backport stable] decouple IO completion polling from idle thread

devicemodel/arch/x86/pm.c, devicemodel/hw/platform/rtc.c
Clear Linux complains about RTC in ACPI:
platform rtc_cmos: registered platform RTC device (no PNP device found)
ACPI Error: Could not enable RealTimeClock event (20180531/evxfevnt-184)
ACPI Warning: Could not enable fixed event - RealTimeClock (4) (20180531/evxface-620)
Tracked-On: #2176
=> Fix RTC issues in ACPI

hypervisor/arch/x86/ept.c, hypervisor/arch/x86/guest/vcpuid.c, hypervisor/arch/x86/pagetable.c, hypervisor/arch/x86/trusty.c, hypervisor/include/arch/x86/cpu.h, hypervisor/include/arch/x86/guest/vm0_boot.h, hypervisor/include/arch/x86/mmu.h, hypervisor/include/arch/x86/per_cpu.h, hypervisor/include/public/acrn_common.h, hypervisor/partition/apl-mrb/mptable.c, hypervisor/partition/cb2_dnv/mptable.c
hv: coding style: use the defined data type __packed
1) Use __attribute__((packed)) instead of #pragma pack(1)
2) Use the defined data type __packed instead of __attribute__((packed))
hv: coding style: add `const` qualifier for some function
Add `const` qualifier for lookup_address and find_vcpuid_entry.
=> coding style: use the defined data type and add `const` qualifier for some function

hypervisor/arch/x86/assign.c, hypervisor/arch/x86/guest/vm.c, hypervisor/bsp/uefi/cmdline.c, hypervisor/debug/dbg_cmd.c, hypervisor/debug/uart16550.c, hypervisor/debug/vuart.c, hypervisor/include/debug/console.h, hypervisor/include/debug/vuart.h, hypervisor/release/console.c, hypervisor/release/vuart.c
1. to support set vuart params by HV command line, so it can be configured dyanmically
through UEFI shell.
2. refine cmdline.c code.
V2-->V3: modify func name to hv_used_dbg_intx as Eddie' comments; add is_dbg_uart_enabled before vuart_init   as Anthony's comments.
V1-->V2: add a new patch as Eddie & Fei's comments, to move debug related command into ./debug/dbg_cmd.c
Tracked-On: #2170
=>  improve uart/vuart to support one binary on UEFI HW && refine cmdline cod

hypervisor/arch/x86/virq.c
The MISRA-C Standards suggests use brackets to clarify the precedence
order of logical conjunctions.
=> hv: virq: refine hypervisor/arch/x86/virq.c

devicemodel/hw/pci/xhci.c
Array index of "vbdp_devs" may be out of bounds if
"i >= XHCI_MAX_VIRT_PORTS", so index checking is necessary.
=> DM: xHCI: array bound checking before it is used

hypervisor/arch/x86/virq.c
hypervisor/arch/x86/virq.c missed a new line at:
if (bitmap_test_and_clear_lock(...)) { vioapic_update_tmr(vcpu);
=> hv: virq: fix wrong coding style

devicemodel/hw/pci/xhci.c, hypervisor/arch/x86/Kconfig
DM: xHCI: array bound checking before it is used 
Revert "EFI: Disable RELOC by default temporary" 
=> array bound checking before it is used

devicemodel/samples/apl-mrb/launch_uos.sh
Currently whether audio works in virtio mediator or pass-through mode can be determined
by checking the device file of vbs_k_audio
But before the completion of loading audio virtio-BE module, the device file of /dev/vbs_k_audio
doesn't exist. In such case in course of loading UOS, the incorrect work mode is selected
for audio device (passthru instead of mediator). This is incorrect
Tracked-On: projectacrn/acrn-hypervisor#2247
=> DM: Try to load audio mediator BE driver before starting UOS

doc/developer-guides/hld/hv-virt-interrupt.rst, hypervisor/arch/x86/assign.c, hypervisor/common/hypercall.c, hypervisor/debug/vuart.c, hypervisor/dm/vioapic.c, hypervisor/dm/vpic.c, hypervisor/include/arch/x86/guest/vioapic.h, hypervisor/include/arch/x86/guest/vpic.h
vpic:
vpic_set_irq         --> vpic_set_irqline
vpic_get_irq_trigger --> vpic_get_irqline_trigger_mode
vioapic:
vioapic_set_irq_nolock --> vioapic_set_irqline_nolock
vioapic_set_irq        --> vioapic_set_irqline_lock
vioapic_send_intr      --> vioapic_generate_intr
=> hv:Rename several APIs for vpic and vioapic

hypervisor/arch/x86/guest/instr_emul.c, hypervisor/common/io_request.c, hypervisor/common/schedule.c
=> hv: clean the "Procedure has more than one exit point".

hypervisor/include/arch/x86/cpu_caps.h, hypervisor/lib/sprintf.c
Typedefs that indicate size and signedness should be used in place of
the basic numerical types
=> hv: coding style: remove basic type declaration use

Makefile
BOARD&FIRMWARE are wrong When 'make sbl-hypervisor-install' w/o parameters
due to default platform is uefi. So set them clearly.
Tracked-On: #1995
=> Makefile: specify BOARD&FIRMWARE in sb-hypervisor-install

tools/acrn-crashlog/acrnprobe/channels.c, tools/acrn-crashlog/acrnprobe/event_handler.c
After panic, kernel will do warm boot to reserve memory for log collecting.
Need to cold reboot system as the original behaviour.
Tracked-On:#1024
=> tools: acrn-crashlog: Reboot system to cold after collecting reserve log

hypervisor/debug/profiling.c, hypervisor/include/debug/profiling_internal.h
This PR includes two patches:
1. Fix crash by SMAP when performing profilings.
2. Align data types between hypervisor core and profiling to avoid unnecessary type conversions. 
Tracked-On: #2157
=> Fix crash by SMAP and align data types

hypervisor/arch/x86/assign.c, hypervisor/arch/x86/ioapic.c, hypervisor/debug/shell.c, hypervisor/debug/vuart.c, hypervisor/dm/vioapic.c, hypervisor/dm/vpic.c, hypervisor/include/arch/x86/assign.h, hypervisor/include/arch/x86/guest/vioapic.h, hypervisor/include/arch/x86/guest/vpic.h, hypervisor/include/arch/x86/ioapic.h, hypervisor/include/arch/x86/irq.h, hypervisor/include/common/ptdev.h, hypervisor/include/debug/vuart.h, hypervisor/include/public/acrn_hv_defs.h, hypervisor/release/vuart.c
-- change the type from uint8_t to uint32_t
-- unify the MACRO for invalid interrupt pin
=> cleanup the data type for interrupt pin

devicemodel/hw/platform/ioc.c
The issue will result in the loss of wakeup reason and signal
data, because the CBC header was not added when generating the
tx package.
Tracked-On: #2283
=> IOC mediator: fix the issue of abnormally missing tx package

doc/developer-guides/hld/hv-virt-interrupt.rst, hypervisor/arch/x86/guest/vlapic.c, hypervisor/arch/x86/irq.c, hypervisor/boot/uefi/uefi_boot.c, hypervisor/common/io_request.c, hypervisor/include/arch/x86/guest/vlapic.h
* rename `vlapic_set_intr_ready` to `vlapic_accept_intr`
* replace calling of `vlapic_intr_edge` with `vlapic_set_intr`
* remove `vlapic_intr_level` and `vlapic_intr_edge`
=> hv: vlapic: code clean-up

hypervisor/debug/profiling.c, hypervisor/include/debug/profiling_internal.h
This is the profiling code cleanup to avoid type conversion
and align tab/space in data structure definition
Tracked-On: #2257
=> profiling: code cleanup

doc/hardware.rst
Four kinds of KBL NUC supported added in document:
- nuc7i5bnh
- nuc7i7bnh
- nuc7i5dnhe
- nuc7i7dnhe
Signed-off-by: Zhengtian Xie zhengtian.xie@intel.com
=> doc: Four kinds of KBL NUC added in "Supported Hardware"

hypervisor/arch/x86/timer.c, hypervisor/include/arch/x86/guest/vcpu.h
fix
1."Value is not of appropriate type."
2."Function prototype/defn param type mismatch"
=> hv:fix violations

hypervisor/include/arch/x86/init.h
Header file shall not be included multiple times.
The following prototype shall be used.
#ifndef INIT_H
#define INIT_H
/* body */
#endif /* INIT_H*/
=> hv: init: minor fix related to header file

hypervisor/arch/x86/guest/instr_emul.c
1) refine vie_calculate_gla to void
2) remove goto in get_gva_di_check
3) refine decode_prefixes to one exit point
4) add const qualifier for some function
Signed-off-by: Li, Fei1 fei1.li@intel.com
=> hv: instr emul: remove some MISRA-C violations in instr_emul.c

hypervisor/dm/vioapic.c, hypervisor/dm/vpic.c, hypervisor/include/arch/x86/guest/vioapic.h, hypervisor/include/arch/x86/guest/vm.h, hypervisor/include/arch/x86/guest/vpic.h
120D: Pointer param should be declared pointer to const.
add 'const' qualifier to function signatures when it's possible.
- vioapic_set_irqline_nolock()
- vioapic_set_irqline_lock()
- master_pic()
- vpic_ocw2()
- vpic_ocw3()
- vpic_set_irqline()
- vpic_get_irqline_trigger_mode()
- vm_pic()
- vm_ioapic
93S: Value is not of appropriate type.
change '0' to '0U' in function vpic_icw1().
=> hv: fix MISRA-C violations in vpic.c and vioapic.c

hypervisor/arch/x86/guest/instr_emul.c
Signed integral type cast to unsigned. :  (unsigned long and long)
=> hv: fix 2 minor MISRA-C violations in inst_emul.c

hypervisor/boot/sbl/multiboot.c
fix this violation "Value is not of appropriate type"
in get_kernel_load_addr()
=> hv:fix MISRA-C violation in multiboot.c

hypervisor/arch/x86/virq.c, hypervisor/include/arch/x86/irq.h
The MISRA C stardand do not allow change parameter passed by value
=> hv: virq: fix attempt to change parameter passed by value

tools/acrn-manager/acrn_vm_ops.c, tools/acrn-manager/acrnctl.h, tools/acrn-manager/acrnd.c
Print more information at acrnd_add_work(), query_state(), try_do_works() and handle_acrnd_resume()
fix a race condition on updating VM state
Fix launch UOS by timer list without fork()
Tracked-On: #2306
=> tools: Acrnd timer expire when enter s3

devicemodel/hw/pci/passthrough.c, devicemodel/samples/apl-mrb/launch_uos.sh
During UOS reboot, sometime the wifi firmware status is wrong and can't
handled by UOS driver, this patch add gpio reset for the wifi chip in dm to avoid
such error.
Tracked-On: #2328 
=> dm: passthru: reset wifi chip via gpio

hypervisor/lib/string.c
Commit 005546 introduces some functions like s0, s1, s2.
This patch renames `s1` and `s2` in string.c to avoid the name conflict.
=> hv: string: rename `s1` and `s2`

hypervisor/arch/x86/guest/instr_emul.c, hypervisor/include/arch/x86/cpu_caps.h
1) remove superfluous prototype
2)  remove unnecessary conditional operators
=> hv: coding style: remove some unnecessary conditional operators,  function declartions

devicemodel/samples/apl-mrb/sos_bootargs_debug.txt, devicemodel/samples/apl-mrb/sos_bootargs_release.txt
Adding this parameter so that it could provide more info when
kernel panic happens. And this has almost no overhead as it only
uses several existing kernel APIs.
The 0x1f is a bitmask for type of info to be dumped, and it means
it will print task/memory/timer/lock/ftrace info when panic happens.
Tracked-On: https://github.com/projectacrn/acrn-hypervisor/issues/2330
Signed-off-by: Feng Tang <feng.tang@intel.com>
=> DM: sos_bootargs: Add panic_print parameter to help debugging

devicemodel/Makefile, devicemodel/core/main.c, devicemodel/include/dm.h, devicemodel/include/dm_kmsg.h, devicemodel/lib/dm_kmsg.c, devicemodel/samples/apl-mrb/launch_uos.sh
Collect the dm log to dmesg for profiing.
These mesage will be easy to profile when dm booting.
Tracked-On: #2336
=> dm: add dm log to kmsg for profiling

hypervisor/arch/x86/guest/vmsr.c
In enable_msr_interception(), by removing the local pointer declarations and
all pointer arithmetic operations, the following violations are fixed.
- Use of pointer arithmetic.
- Pointer arithmetic is not on array.
- Pointer not checked for null before use.
Change enable_msr_interception() signature, replacing "uint8_t *bitmap" with
"uint8_t bitmap[]" to fix violations:
- Pointer param should be declared pointer to const.
- Declaration does not specify an array.
=> hv: fix MISRA-C violations in vmsr.c

devicemodel/hw/pci/passthrough.c
Increase the delay to 200ms after wifi reset for link training done.
Tracked-On: #2328
=> dm: passthru: increase the delay after wifi reset

hypervisor/arch/x86/mmu.c
On platforms that put ACPI RSDT in E820 "Reserved" type memory, ACRN
fails to parse RSDP and therefore ACPI Tables. This patch adds
"Reserved" memory regions in E820 as Supervisor pages.
Tracked-On: #2320
=> hv: Make reserved regions in E820 table to Supervisor pages

hypervisor/arch/x86/guest/vcpu.c, hypervisor/arch/x86/guest/vlapic.c, hypervisor/arch/x86/virq.c, hypervisor/dm/vioapic.c, hypervisor/include/arch/x86/guest/guest.h, hypervisor/include/arch/x86/guest/vcpu.h, hypervisor/include/arch/x86/guest/vioapic.h, hypervisor/include/arch/x86/guest/vlapic.h
These patches make TMR set/clear behavior like real hardware, and update EOI_EXIT
bitmap upon changes to related fields of RTEs.
With these changes, we may get rid of current issue to support per_cpu vector in guest
OS. Because only target vlapic TMR bit will be set/cleared.
For EOI_EXIT_BITMAP, we removed the logic dependency from TMR, and update the bitmaps
according to contents of RTEs. And we also optimized the process to go through all
RTEs one-time on a singel cpu for each update.
Tracked-On: #2343
=> Rework TMR and EOI_EXIT_BITMAP updating logic

devicemodel/samples/apl-mrb/launch_uos.sh
echo 'high' instead of "out" to direction for gpio460 to avoid gpio pin value glitch.
Tracked-On: #2328
=> dm: script: echo 'high' instead of "out" to direction for gpio460

devicemodel/core/vmmapi.c, devicemodel/samples/apl-mrb/launch_uos.sh, devicemodel/samples/nuc/launch_uos.sh, devicemodel/samples/up2/launch_uos.sh, hypervisor/common/hypercall.c, hypervisor/common/io_request.c
This is the patch set that fixes the issue in
Tracked-On: #2355  #2356
1. It allows devicemodel to start guest OS on the renamed VHM module.
2. the default up-notification vector is changed from 0xF7 to 0xF3.
=> Change the default notification vector and start guest OS on the renamed vhm module

Makefile, devicemodel/Makefile, hypervisor/Makefile
Currently, we support SBL on two different boards.
So build and install them all in E2E build.
Tracked-On: #2344
=> Makefile: support SBL binary for E2E build

hypervisor/common/ptdev.c, hypervisor/include/arch/x86/timer.h
to edge interrupt, like eth device, it can triger the interrupt again
when its IRQ in softirq entry queue or in timer list.
in current design, for sofrirq entry, it calls "list_del" before
"list_add_tail", to avoid the entry added twice.
so for interrupt delay timer, add to check if it is started
then just drop the next one; to avoid it enqueue twice.
Tracked-On: #2365
=> HV: check to avoid interrupt delay timer add twice

devicemodel/samples/apl-mrb/launch_uos.sh
/sys/class/gpio/gpio460 is a directory,
should use -d instead of -f to check its existence.
Tracked-On: #2328
=> dm: script: use -d to check existence of gpio460

Makefile
Add rules for installing debug information.
Tracked-On: #2344
=> Makefile: add rules for installing debug information

devicemodel/Makefile, devicemodel/core/main.c, devicemodel/core/mem.c, devicemodel/core/mevent.c, devicemodel/core/timer.c, devicemodel/hw/pci/virtio/virtio.c, devicemodel/hw/pci/wdt_i6300esb.c, devicemodel/hw/platform/acpi/acpi.c, devicemodel/hw/platform/hpet.c, devicemodel/hw/platform/pit.c, devicemodel/hw/platform/rtc.c, devicemodel/include/acpi_hpet.h, devicemodel/include/hpet.h, devicemodel/include/timer.h
vHPET is used as a source of system timer by UEFI (e.g. OVMF).
This provides an alternative to using vPIT, which OVMF assumes is always connected to vPIC.
This is ported from Bhyve, with a few changes:
- move to user space, using acrn_timer
- enable timers only when necessary
Origin: FreeBSD
License: BSD-3-Clause
URL: https://svnweb.freebsd.org/
commit: 326257
Purpose: Adding vHPET support.
Maintained-by: External
Tracked-On: #2319
=> Add vHPET support

tools/acrn-manager/acrn_mngr.c
When do IPC with mngr_send_msg(), and ack is required but failed to
get ack,  mngr_send_msg() still return 0, that is not correct.
Tracked-On: #2398
=> tools: acrn-manager: fix mngr_send_msg() return 0 when read ack fail

devicemodel/hw/block_if.c
For virtio-blk, when the back-end is a regular file, the discard and is implemented by fallocate(), but this function will not wait for the discard command handled by disk.
So, add fdatasync to make sure the DISCARD is executed synchronously.
Tracked-On: #2395
Acked-by: Wang Yu <yu1.wang@intel.com>
=> dm: storage: change DISCARD to synchronous mode

scripts/kconfig/silentoldconfig.py
The existing .config may have missed or conflicting values if the file is
manually edited or Kconfig is changed. Kconfiglib will assign default values to
missed symbols and resolve conflicts when loading .config, but the current
silentoldconfig.py fails to write the updated symbol values back to .config.
This patch checks if any missed or conflicting symbol value is fixed by
Kconfiglib and write the updated values back to .config if necessary.
Tracked-On: #2371
=> kconfig: update .config on missed or conflicting symbol values

hypervisor/arch/x86/assign.c, hypervisor/arch/x86/guest/vlapic.c, hypervisor/dm/vioapic.c, hypervisor/include/arch/x86/guest/vlapic.h
- remove `calcvdest` and use `vlapic_calcdest` directly
=> hv: vlapic: remove `calcvdest`

doc/developer-guides/hld/hv-io-emulation.rst, hypervisor/Makefile, hypervisor/arch/x86/guest/vcpu.c, hypervisor/arch/x86/io_emul.c, hypervisor/arch/x86/sched.c, hypervisor/common/hv_main.c, hypervisor/common/hypercall.c, hypervisor/common/io_req.c, hypervisor/common/schedule.c, hypervisor/include/arch/x86/guest/vcpu.h, hypervisor/include/arch/x86/io_emul.h, hypervisor/include/arch/x86/io_req.h, hypervisor/include/arch/x86/per_cpu.h, hypervisor/include/common/schedule.h
Now each time when scheduling happen, it will reset its thread stack and resume
thread from the beggining, it adds the complexes for mmio post handling, and
is not suitable for future cpu sharing.
This patch series enabled full context switch scheduling, there will be per-cpu
idle schedule object plus per-vcpu thread schedule object, each of one has its
own stack. The scheduing will do full context switch based on these per-cpu and
per-vcpu stack.
After this patch series, only three fixed points will trigger schedule:
- vcpu_thread loop, before vm entry
- default_idle loop
- io request, for DM handling IO REQ
Tracked-On: #2394
Acked-by: Xu, Anthony <anthony.xu@intel.com>
=> add full context switch scheduling support

Makefile, devicemodel/Makefile, tools/Makefile
Using 'make' directly means that the jobserver environment variables don't get
passed down, so sub-builds for example don't use -j.
This is documented as the wrong thing to do:
https://www.gnu.org/software/make/manual/html_node/MAKE-Variable.html#MAKE-Variable
Use $(MAKE) instead, and compile times drastically improve:
acrn-devicemodel    do_compile   -13.5s   -89.6%      15.0s -> 1.6s
Tracked-On: #2370
Signed-off-by: Ross Burton <ross.burton@intel.com>
=> Use $(MAKE) when recursing

tools/acrn-manager/Makefile, tools/acrnlog/Makefile, tools/acrntrace/Makefile
The build environment might want to pass extra CFLAGS or LDFLAGS to the build of
the acrn tools. With conventional build systems like automake, Meson, etc this
is possible by just setting CFLAGS and LDFLAGS in the environment.
However as the tools are built using bare Makefiles, these environment variables
are overwritten.  Respect them by renaming the variables in the Makefiles to
e.g. LOG_CFLAGS and adding CFLAGS to that.
Tracked-On: #2316
Signed-off-by: Ross Burton <ross.burton@intel.com>
=> tools: respect CFLAGS and LDFLAGS from environment

hypervisor/include/debug/profiling_internal.h
The array index of 'vm_list' may be out of bound
vm_idx should be less than CONFIG_MAX_VM_NUM, so updated for loop
Bug : ACRN-2544
Tracked-On: #2385
Signed-off-by: Manisha Chinthapally <manisha.chinthapally@intel.com>
=> security: bounds checking to avoid buffer overflow error

efi-stub/boot.c, efi-stub/boot.h, efi-stub/efilinux.h, efi-stub/malloc.c, hypervisor/arch/x86/Kconfig, hypervisor/arch/x86/mmu.c, hypervisor/arch/x86/trampoline.c, hypervisor/bsp/uefi/uefi.c
The patch set is to fix some issues when RELOC is enabled in Kconfig,  the last patch of the set is to enable RELOC to default to "Yes".
8fd1f68f (HEAD -> reloc, mygit/reloc) HV: modify RELOC kconfig option default to "enable"
743b4d85 HV: fix per-cpu stack relocation in trampoline.c
048bb06a HV: init_paging() wrongly calcuate the size of hypervisor
52aab666 HV: adjust the starting addr of HV to be 2M-aligned
2a8a473d HV: save efi_ctx into HV to use after init_paging()
d7ef43bb EFI: Allocate EFI boot related struct from EFI allocation pool
51ff395d EFI: Allocate 2M aligned memory for hypervisor image
Tracked-On: https://github.com/projectacrn/acrn-hypervisor/issues/2349
Signed-off-by: Chaohong guo <chaohong.guo@intel.com>
Reviewed-By: Yin Fengwei <fengwei.yin@intel.com>
Reviewed-by: Zide …
=> fix hypervisor relocation issue and enable it as default in kconfig

hypervisor/Makefile
There is a missing dependency between lib and bin in Makefile.
BTW, this issue is triggered by concurrent build.
Tracked-On: #2370
=> Makefile: add missing dependency

devicemodel/arch/x86/pm.c, devicemodel/core/vmmapi.c, devicemodel/hw/pci/core.c
dm: add log for debuging pci while vm reset
Print some log to dmesg when init/deinit vdev.
Tracked-On: #2419
=> dm: add log for debuging pci while vm reset

hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/mmu.c, hypervisor/arch/x86/trampoline.c, hypervisor/boot/include/reloc.h, hypervisor/boot/reloc.c, hypervisor/include/arch/x86/boot/ld_sym.h, hypervisor/include/arch/x86/cpu.h, hypervisor/include/arch/x86/mmu.h, hypervisor/include/arch/x86/trampoline.h
-- add header file ld_sym.h in include/arch/x86/boot/
-- move 'ld_bss_start/end' from cpu.h to ld_sym.h,
avoid reverse dependency
-- move 'ld_text_end' from mmu.h to ld_sym.h
-- move 'ld_trampoline_load/start/end' to ld_sym.h
=> hv:Move severl variable declaration for boot code

tools/acrn-manager/acrnd.c
The wait_for_stop() first check if all VM are stopped or suspended.
It first check if VMs are stopped, then check if they are suspend.
If the VMs change state from running to stoped, after check VMs
stopped fail, before start check suspend state. wait_for_stop() will
mistake resopnse 'All vms have entered S3 state successfully'
To fix that, wait_for_stop() must only update VMs's state once, and
see if they are stopped, or suspended.
Tracked-On: #2398
=> tools: acrnd: fix wait_for_stop() return wrong vm state

hypervisor/arch/x86/guest/vlapic.c, hypervisor/arch/x86/virq.c
- vlapic_pending_intr() is called only for case no
APICv/VID(Virtual Interrupt Delivery) feature support,
in this case, there is no need to test VID case.
- remove 'apicv_pending_intr()' function.
Tracked-On: #2427
=> hv: remove redundant code for virtual interrupt injection

devicemodel/core/main.c, devicemodel/core/mptbl.c, devicemodel/core/vmmapi.c, devicemodel/include/dm.h, devicemodel/include/public/acrn_common.h, devicemodel/samples/nuc/launch_hard_rt_vm.sh, hypervisor/arch/x86/assign.c, hypervisor/arch/x86/guest/vcpuid.c, hypervisor/arch/x86/guest/vlapic.c, hypervisor/arch/x86/guest/vmsr.c, hypervisor/arch/x86/lapic.c, hypervisor/arch/x86/virq.c, hypervisor/arch/x86/vmcs.c, hypervisor/common/hv_main.c, hypervisor/common/hypercall.c, hypervisor/include/arch/x86/guest/vlapic.h, hypervisor/include/arch/x86/guest/vm.h, hypervisor/include/arch/x86/lapic.h, hypervisor/include/debug/logmsg.h
This is a patch series to extend lapic passthrough support for DM-launched VMs. 
The DM launched VM with lapic_pt is generally for hard RT scenarios, should be trapped to hypervisor at boot time only, must never trapped at runtime.
The main changes of this patch series include:
- extend lapic passed through for DM-launched vm;
- change the msi remap/msi inject logic slightly to make it work
with lapic pass-through;
- add option to devicemodel for LAPIC_PT.
Known issues:
- SMP is not supported for VM with lapic_pt;
- S5 is not supported for VM with lapic_pt.
Tracked-On:   #2351
=> Enabling DM-launched VM with lapic_pt

doc/scripts/requirements.txt
Versions of kconfiglib lower than 10.2 cannot build the documentation
correctly. The minimum version required is >=10.2. This patch updates
the 'requirements.txt' accordingly.
Tracked-On: #2429
=> Documentation build tools: update min version for kconfiglib

hypervisor/arch/x86/guest/vlapic.c, hypervisor/arch/x86/vmcs.c
Fixed violations in vlapic_x2apic_pt_icr_access()
- Procedure has more than one exit point;
- Value is not of appropriate type;
- Narrower init conversion without cast;
- Implicit conversion: actual to formal param (MR)
Fixed violation in switch_apicv_mode_x2apic()
- No space between if, while, for and expresn.
=> hv: fix misra-c violations in reused partition mode functions

efi-stub/boot.c, efi-stub/boot.h, hypervisor/arch/x86/Kconfig
EFI: fix potential memory overwrite due to mmap table
Some bios may have more mmap table entry than our current limitation
which is 128. This will lead to a memory overwrite, so add a check to
prevent this and enlarge the limitation to 256. This should fix most
bioses.
Kconfig: enlarge range of maximum number of IOMMU  …
Some arches have more than two IOMMUs, so change this limitation.
Tracked-On: #2435
=> Fix two issues found on a new platform

hypervisor/arch/x86/guest/vmcall.c, hypervisor/arch/x86/virq.c, hypervisor/arch/x86/vmexit.c
This patch series has the following changes:
- Add specific handler for vmx operations for guest, will inject #UD exception if guest execute these instructions.
- Fix a logic bug when inject low priority exceptions.
Tracked-On: #2405 
=> Fix exception injection bug

hypervisor/debug/profiling.c, hypervisor/include/debug/profiling_internal.h
tool
The msr load/restore during vmexit/vmenty is enabled in HV by
default. The profiling has assumption that it's only user for this
feature, which could overwrite of HV default setting.
This fix combines the msr load list for vmexit when profiling.
Tracked-On: #2422
=> profiling: fix the system freeze issue when running profiling

efi-stub/Makefile, efi-stub/boot.c, hypervisor/Makefile, hypervisor/arch/x86/guest/guest.c, hypervisor/arch/x86/guest/vcpu.c, hypervisor/arch/x86/guest/vm.c, hypervisor/arch/x86/irq.c, hypervisor/arch/x86/trampoline.c, hypervisor/arch/x86/vmx.c, hypervisor/boot/acpi.c, hypervisor/boot/uefi/uefi_boot.c, hypervisor/bsp/include/bsp_extern.h, hypervisor/bsp/include/uefi/uefi.h, hypervisor/bsp/sbl/sbl.c, hypervisor/bsp/uefi/uefi.c, hypervisor/include/arch/x86/ioapic.h, hypervisor/include/arch/x86/per_cpu.h
1. in UEFI bsp code, not need UEFI macro; it is controlled in makefile.
2. in vm/acpi/interrupt code, unify the API name for SBL & UEFI.
3. remove unnecessary header including and unused code.
=> HV: modularization improve UEFI macro control code

doc/developer-guides/hld/hld-devicemodel.rst, doc/developer-guides/hld/hv-virt-interrupt.rst, doc/user-guides/acrn-dm-parameters.rst
- added description of lapic pt feature based on vlapic in HLD virt-interrupt part;
- updated the doc to include description of new acrn-dm option "--lapic_pt".
Tracked-On: #2351
=> doc: update documents for "--lapic_pt" feature

doc/developer-guides/hld/hld-overview.rst, doc/developer-guides/hld/hld-security.rst, doc/developer-guides/primer.rst, doc/faq.rst, doc/getting-started/apl-nuc.rst, doc/getting-started/building-from-source.rst, doc/release_notes_0.1.rst, doc/release_notes_0.2.rst, doc/release_notes_0.3.rst, doc/release_notes_0.5.rst, doc/tutorials/agl-vms.rst, doc/tutorials/building_uos_from_clearlinux.rst, doc/tutorials/docbuild.rst, doc/tutorials/skl-nuc.rst, doc/tutorials/static-ip.rst, doc/tutorials/using_partition_mode_on_up2.rst, doc/tutorials/using_ubuntu_as_sos.rst
Proper use of the Clear Linux name is with a noun, specifically "OS".
Also fixed some grammar edits along the way.
=> doc: fix correct use of Clear Linux OS

doc/developer-guides/hld/hld-devicemodel.rst, doc/developer-guides/hld/hv-memmgt.rst, doc/developer-guides/hld/hv-startup.rst, doc/developer-guides/hld/hv-vt-d.rst, doc/developer-guides/primer.rst, doc/faq.rst, doc/introduction/index.rst
Using term of VM0 would mislead to a VM with VM id 0 easily, whereas
VM id 0 could be used for any PRE_LAUNCHED_VM. So replace VM0 with
SOS_VM.
=> doc: change term of vm0 to sos_vm

hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/guest/virtual_cr.c, hypervisor/arch/x86/pagetable.c, hypervisor/boot/acpi.c, hypervisor/boot/sbl/multiboot.c, hypervisor/common/schedule.c
v1-v2:
Retrun 0 in parse_madt and let the caller call panic if something wrong with parse_madt.
v1:
Now panic and ASSER are misused: Panic should only be used when system booting.
Once the system boot done, it could never be used. While ASSERT could be used
in some situations, such as, there are some pre-assumption for some code,
using ASSERT here for debug.
TODO: there still have panic misused in vlapic.c and ASSERT misused in some files.
Li, Fei1 (3):
hv: replace improper use of panic with ASSERT
hv: multiboot: replace improper use of ASSERT with panic
hv: replace improper use of ASSERT with panic for parse_madt
Acked-by: Eddie Dong <eddie.dong@inte.com>
=> [RFC PATCH v2 0/3] correct improper use of panic and ASSERT

hypervisor/arch/x86/cpu.c, hypervisor/debug/shell.c, hypervisor/debug/shell_priv.h, hypervisor/include/arch/x86/cpu.h
Add these commands to  HV console:
1.rdmsr [-p<pcpu_id>] [reg_num]
read MSR register, eg., 'rdmsr 0xc8f' read MSR with address 0xc8f;
'rdmsr -p1 0xc8f' read MSR address 0xc8f, on PCPU1.
1.wrmsr [-p<pcpu_id>] [reg_num] [value]
write to MSR register, eg., 'wrmsr 0xc8f 0x100000000' write
0x100000000 to MSR, which address is 0xc8f;
'wrmsr -p1 0xc8f 0x100000000' write 0x100000000 to MSR address
0xc8f, on PCPU1.
=> rdmsr/wrmsr HV debug cmd

hypervisor/arch/x86/guest/vlapic.c, hypervisor/arch/x86/guest/vmcs.c
With lapic_pt based on vlapic, guest always see vitual apic_id.
We need to convert the virtual apic_id from guest to physical apic_id
before writing ICR.
SMP for VM with lapic_pt is supported with this fix.
Tracked-On: #2351
=> hv: fix dest of IPI for CPU with lapic_pt

doc/tutorials/rt_linux.rst
Add a caption to the figure describing the Real-Time Linux VM running
on ACRN. Without this text, the HTML output does not add the Figure
number below it. That figure number is still used in the paragraph
making it hard for the reader to understand which figure is really
referenced (except by clicking on the hyperlink)
=> Documentation: add caption to the "PREEMPT_RT VM on ACRN" figure

efi-stub/MpService.h, efi-stub/boot.c
In current hv implementation, we assume all AP have no context before
jumping into guest mode. But this is not true in all UEFI bios. BIOS
could have enabled all (or some of) APs at first. These APs could stay
in a run loop or wait for a semaphore. But after hv takes over control from
efi-stub, all of these AP environments will be simply dropped because
we don't support AP context save/restore for now. As a result,
BSP's ExitBootService will hang forver because it's waiting for AP in its
way (by waiting for a semaphore for example), unfortunately APs are now
in the context that hv provides in which they usually stay in idle loop.
To fix the issue above, we could have two solutions:
1. Save AP's runtime context before entering hv and restore context
after hv jumps back.
2. After hv jumps …
=> efi-stub: reset all APs after entering guest mode

devicemodel/core/main.c, devicemodel/hw/pci/wdt_i6300esb.c, devicemodel/include/vmmapi.h
Per debugging requirement, map the watchdog reset to warm reset.
So the ramconsole could be used to capture the kernel log of UOS
before watchdog is hit.
Tracked-On: #2471
=> watchdog: map the watchdog reset to warm reset

hypervisor/debug/profiling.c, hypervisor/include/debug/profiling_internal.h
The msr load/restore during vmexit/vmentry is enabled in HV by
default. The profiling has assumption that it's only user for this
feature, which could overwrite of HV default setting.
This fix combine the msr load list for vmexit when profiling.
Tracked-On: #2422
=> profiling: fix the system freeze issue when running profiling tool

Makefile, devicemodel/Makefile, devicemodel/hw/platform/acpi/acpi.c
The ASL_COMPILER macro is hard coded as /usr/sbin/iasl, it is
complained by some developers. This patch changes it to a
flexible way, by which the following make command lines are
supported:
make
make devicemodel
make ASL_COMPILER=/path/to/iasl
make ASL_COMPILER=/path/to/iasl devicemodel
Tracked-On: #2298
=> DM: ACPI: Avoiding hard code the ASL_COMPILER macro

devicemodel/hw/platform/ioc.c, devicemodel/include/ioc.h
The dummy channels can emulate cbc lifecycle, cbc signal and cbc raw
channel instead canbox, and the feature can be enabled by ioc command
line within wakeup reason bit 24.
Tracked-On: #2481
=> IOC mediator: dynamically enable dummy channels

hypervisor/arch/x86/guest/virtual_cr.c, hypervisor/include/arch/x86/vmx.h
CRx 'guest/host mask' is widely used when talking
about CR0/CR4 virtualization in SDM spec,
rename them to 'VMX_CRx_GUEST_HOST_MASK'.
=> hv: rename MACROs 'VMX_CRx_MASK"

hypervisor/Makefile, hypervisor/arch/x86/configs/apl-mrb/ve820.c, hypervisor/arch/x86/configs/dnv-cb2/ve820.c, hypervisor/arch/x86/e820.c, hypervisor/arch/x86/guest/vm.c, hypervisor/common/vm_load.c, hypervisor/include/arch/x86/e820.h, hypervisor/include/arch/x86/guest/vm.h, hypervisor/partition/apl-mrb/vm_description.c, hypervisor/partition/dnv-cb2/vm_description.c
- move e820 entry out of vm description;    
- add e820 info in struct acrn_vm;
- rename rebuild_sos_vm_e820() to create_sos_vm_e820();
- add create_prelaunched_vm_e820() for partition mode;
- rename create_e820_table() to create_zeropage_e820() and merge for
both sharing mode and partition mode;
- move create_xxx_vm_e820() to vm.c;
- move create_zeropage_e820() to vm_load.c;
=> HV: E820 refinement

hypervisor/arch/x86/e820.c, hypervisor/arch/x86/guest/vm.c, hypervisor/bsp/include/bsp_extern.h, hypervisor/include/arch/x86/e820.h, hypervisor/include/arch/x86/guest/vm.h
Remove redundancy code since they are not used now.
-- remove 'max_ram_blk_base' & 'max_ram_blk_size' in
struct e820_mem_params
-- remove 'gpa_lowtop' in struct vm_hw_info
-- remove MACRO 'UOS_DEFAULT_START_ADDR'
=> hv:remove several redundancy variables related memory

hypervisor/arch/x86/configs/apl-mrb/partition_config.h, hypervisor/arch/x86/configs/apl-mrb/pt_dev.c, hypervisor/arch/x86/configs/dnv-cb2/partition_config.h, hypervisor/arch/x86/configs/dnv-cb2/pt_dev.c, hypervisor/arch/x86/configs/partition_config.c, hypervisor/dm/vpci/partition_mode.c, hypervisor/include/arch/x86/guest/vm.h
Use acrn_vm_pci_ptdev_config struct for PCI PT devices configuration
in acrn_vm_config, the only needed configure item is PT devices's
vBDF and pBDF info. When init PT devices, the BDF info will be stored
in pci_vdevs[] of acrn_vm.
With this patch, the previous vpci_vdev_array struct is not needed.
=> HV: repace vpci_vdev_array with pci_ptdev config

doc/acrn.doxyfile, hypervisor/arch/x86/guest/vmx_asm.S, hypervisor/include/arch/x86/e820.h, hypervisor/include/arch/x86/guest/guest_memory.h, hypervisor/include/arch/x86/guest/vcpu.h, hypervisor/include/arch/x86/guest/vm.h, hypervisor/include/arch/x86/guest/vmexit.h, hypervisor/include/arch/x86/hv_arch.h, hypervisor/include/arch/x86/irq.h, hypervisor/include/arch/x86/msr.h
- move functions related vmexit from `guest.h` to `vmexit.h`
- move functions related msr from `guest.h` to `msr.h`
- move functions related vm_sw_loader from `guest.h` to `vm.h`
- move function `vmx_vmrun` from `guest.h` to `vcpu.h`
- move MACROs related to vcpu from `guest.h` to `vcpu.h`
- move MACRO `E820_MAX_ENTRIES` from `guest.h` to `e820.h`
- move MACROs related to irq from `guest.h` to `irq.h`
- rename `guest.h` to `guest_memory.h`
Tracked-On: #2503 
=> hv: refine `guest.h`

hypervisor/arch/x86/guest/vcpu.c, hypervisor/arch/x86/guest/vm.c, hypervisor/include/arch/x86/guest/trusty.h, hypervisor/include/arch/x86/guest/vcpu.h, hypervisor/include/arch/x86/guest/vcpuid.h, hypervisor/include/arch/x86/guest/vlapic.h, hypervisor/include/arch/x86/guest/vm.h, hypervisor/include/arch/x86/guest/vmcs.h, hypervisor/include/arch/x86/hv_arch.h, hypervisor/include/arch/x86/mmu.h, hypervisor/include/arch/x86/timer.h, hypervisor/include/arch/x86/vtd.h, hypervisor/include/common/schedule.h, hypervisor/include/dm/vioapic.h, hypervisor/include/dm/vpic.h
hypervisor.h is an universal set of header file for HV,
most modules include this header file, actually some header files
are not necessary,we will remove hypervisor.h in future, these two patches
are only for vm and vpu modules cleanup.
=> Cleanup head file

doc/developer-guides/hld/hv-vt-d.rst, hypervisor/arch/x86/guest/assign.c, hypervisor/arch/x86/guest/virtual_cr.c, hypervisor/arch/x86/guest/vm.c, hypervisor/arch/x86/guest/vmexit.c, hypervisor/arch/x86/init.c, hypervisor/arch/x86/pm.c, hypervisor/arch/x86/vtd.c, hypervisor/bsp/sbl/const_dmar.c, hypervisor/common/hypercall.c, hypervisor/dm/vpci/pci_pt.c, hypervisor/include/arch/x86/hv_arch.h, hypervisor/include/arch/x86/vtd.h
This patch is a modified one. It removes the usage
of acrn_vm struct from inside vtd.c.
It also puts struct iommu_domain inside vtd.h,
from vtd.c.
It modifies the signature of init_iommu_domain
in order to remove dependency on acrn_vm from
inside vtd.c.
Incorporated comments from Jason and Eddie.
Changed the name of sos_vm_domain to
fallback_iommu_domain
Removed any reference of sos_vm from vtd.[c|h]
files, including comments.
Tracked-On:https://github.com/projectacrn/acrn-hypervisor/issues/2496
=> HV: Modularize vtd.c to remove acrn_vm usage

devicemodel/samples/up2/sos_bootargs_debug.txt, devicemodel/samples/up2/sos_bootargs_release.txt
For UP2 releases, we don't need enable_initial_modeset, just as the NUC
platforms, so remove this parameter from the boot args.
Tracked-On: #2516
=> script: remove enable_initial_modeset for UP2 platform

hypervisor/arch/x86/guest/ept.c, hypervisor/arch/x86/guest/vm.c, hypervisor/arch/x86/vtd.c, hypervisor/include/arch/x86/guest/vm.h
Removed the remaining reference of acrn vm from
inside of vtd.c.
Removed usage of snoopy_mem, and added code to achieve
the same using iommu_snoop.
Initialize iommu_snoop to true in create default iommu.
Tracked-On: #2496
=> HV: Remove snoopy_mem from iommu

doc/getting-started/apl-nuc.rst, efi-stub/clearlinux/acrn.conf
* Update kernel versions to the latest (to reflect the new 'release'
number used in the 'iot-lts2018' kernel
* Add a one-line command to insert the PARTUUID into the acrn.conf
file (without copying it all manually)
=> Documentation: tweak GSG (and acrn.conf)

hypervisor/debug/sbuf.c, hypervisor/include/arch/x86/cpu.h
For apl_sdc_stable branch, we now have stac and clac to set and
clear AC bit of rflags. But it can't handle following sequence:
stac
stac
clac
user mode address access here will trigger page fault
clac
This patch introduce two more functions:
- stac_save: Save the rflags and set AC bit
- ac_restore: Restore the AC bit saved to rflags
Now, only sbuf_put/get are using these new APIs.
Tracked-On: #2525
=> hv: extend the AC bit of rflags operations for smap

devicemodel/Makefile, devicemodel/hw/pci/virtio/virtio_gpio.c, devicemodel/include/virtio.h
GPIO virtualization is based on virtio, and it can support basic GPIO operations
including set/get value, set input/output direction and set config, the backend is
based on gpiolib, which is the linux standard gpio user space interface.
v2:
- correct license information
- improve virtio gpio framework, use synchronous mode instead interrupt,
use an inbuf and an outbuf as GPIO operation request and response instead
one outbuf.
- GPIO set one config returns successfully when the back-end does not support
this config, to make sure front-end GPIO works.
v3:
- code style improvements include removing virtio_gpio.h, code alignment.
- add "native_" prefix for all native variables and functions.
- fix a wrong iov length when handling gpio request.
- improve the native_gpio_open_line interface.
- …
=> GPIO virtualization implementation

hypervisor/arch/x86/guest/vmcall.c
ACRN HV hide VMX capability from guest. Only vmcall from SOS or some
specific vmcall from UOS are allowed.
Unsupported vmcall from UOS should be considered a "not in VMX
operation" case, and should be handled first according to SDM Vol. 3C 30-9.
HV passes the return value of vmcall by register RAX unconditionally.
However, if the vmcall is undefined for a guest, RAX value of guest vcpu
should not be changed.
According to SDM Vol. 3C 30-9, VMCALL is allowed from any CPL in guest.
VMCALL is NOT allowed from  CPL > 0 in vmx root mode.
ACRN hypervisor doesn't call VMCALL in vmx root mode, though.
In current code, ACRN also deny VMCALL from CPL > 0 in guest.
So for this case, #GP will not be injected, instead, modify the RAX to notify
the return value.
Tracked-On: #2405
Signed-off-by: Binbin …
=> vmcall handling fix

hypervisor/arch/x86/guest/vlapic.c
DCR is initialized to 0 which means divisor shift is 1. Currently, both are initialized to 0 which result in incorrect APIC timer counts if the vLAPIC's DCR is never programmed.
This bug was exposed by OVMF because OVMF does not program DCR during LAPIC initialization.
Tracked-On: #2543
=> hv: vlapic: properly initialize DCR

hypervisor/arch/x86/guest/vlapic.c
With APICv enabled, it's possible that the interrupt is not
injected through VMX_ENTRY_INT_INFO_FIELD. In that case, the
isrvec_stk_top will not be increased.
Tracked-On: #2558
=> hv: isrvec_stk_top could be zero once we enable APICv

doc/tutorials/agl-vms.rst, doc/tutorials/skl-nuc.rst, doc/tutorials/using_ubuntu_as_sos.rst, efi-stub/clearlinux/acrn.conf
- Remove some i915 options that are obsolete and irrelevant for the
Service OS kernel
- Adjust the plane assignment to make them consistent
- Update to the latest iot-lts2018 kernel version
Tracked-On: #2518
=> acrn.conf: clean-up SOS kernel options (EFI platforms)

hypervisor/arch/x86/guest/virq.c, hypervisor/include/arch/x86/irq.h
According to SDM 17.3.1.1, for any fault-class exception except a
debug exception generated in response to an instruction breakpoint,
the value pushed for RF is 1.
This patch set Resume Flag for fault class exceptions.
Tracked-On: #2405
=> hv: exception: fault type exception should set resume flag in rflags

hypervisor/arch/x86/guest/guest_memory.c, hypervisor/arch/x86/guest/virtual_cr.c, hypervisor/include/arch/x86/mmu.h
There are two bugs related to PDPT address calculation for PAE mode.
1. Current code doesn't ignore the "Ignored" fileds when load pdpt registers.
Mask the "Ignored" fileds according to SDM Figure 4-7 Vol3.
2. Current code only ignores 4bits instead of 5bits in low "Ignored" filed when
calculate PDPT address in PAE mode for guest memory address translation.
Another issue, PDPTE registers should be loaded for PAE paging mode when handling guest CR4.
Tracked-On: #2561
=> hv: pae: fix bug when calculate PDPT address

tools/Makefile, tools/acrn-manager/Makefile
This commit removes the unnecessary tool files in release build, including:
- entire acrnlog module
- entire acrntrace module
- acrnctl binary in acrn-manager
Tracked-On: #2575
=> tools: do not include unnecessary files in release build

doc/conf.py
Add the 0.6 version of documentation to the menu list (again)
=> doc: add 0.6 to doc version menu

doc/tutorials/using_partition_mode_on_up2.rst
Update doc to remove trailing spaces on lines, wrap long lines, add
formatting missed during regular review.
=> doc: fix formatting of up2 doc

devicemodel/hw/pci/xhci.c
The patch (commit id: b39524e) didn't achieve its purpose completely.
This patch is used to fix it.
Tracked-On: #2557
=> DM USB: xHCI: fix an error logic in DRD logic

devicemodel/hw/platform/usb_pmapper.c
When LINK type TRB are received among multiple BULK TRBs, the copying
logic in DM will miss one or more TRBs. This patch is used to fix it.
Tracked-On: #2581
=> DM USB: xHCI: fix an issue during BULK transfer

hypervisor/debug/npk_log.c
Otherwise, page fault will be triggered when writing npk log
to these mmio addresses.
Tracked-On: #2589
Signed-off-by: Zhi Jin <zhi.jin@intel.com>
=> hv: debug: mark the mmio address for npk log as hv owned

hypervisor/dm/vpci/partition_mode.c, hypervisor/dm/vpci/sharing_mode.c, hypervisor/dm/vpci/vpci.c, hypervisor/hw/pci.c, hypervisor/include/dm/pci.h, hypervisor/include/dm/vpci.h
Some vpci code bug fix and cleanup:
pci.c: fixes bar address non-zero checking for 64-bit bars
Fix comments issue
Define function bdf_is_equal() to compare bdf
Remove pbdf from struct pci_vdev
Tracked-On: #2534
=> VPCI  code bug fix and cleanup

doc/developer-guides/hld/hv-virt-interrupt.rst, hypervisor/arch/x86/guest/vlapic.c, hypervisor/include/arch/x86/guest/vlapic.h, hypervisor/include/arch/x86/guest/vm.h
These functions are only used by vlapic, it'd better to refine them as internal function. and remove vlapic un-related function out of vlapic.c
Tracked-On: #1842 
=> Vlapic: refine some functions to internal

hypervisor/boot/sbl/abl_seed_parse.c
Due to ABL design change, it will reword the "dev_sec_info.param_addr="
to "ABL.svnseed" in command line.
Tracked-On: projectacrn#2605
=> ABL seed parse new argument

devicemodel/Makefile, devicemodel/hw/pci/virtio/virtio_rpmb.c, devicemodel/hw/platform/rpmb/att_keybox.c, devicemodel/include/att_keybox.h
Retrieve the encrypted attestation Keybox from CSE
and provision it to RPMB storage.
Tracked-On: #2604
Signed-off-by: Wei Xinghai <xinghaix.wei@intel.com>
Signed-off-by: Chen Gang <gang.g.chen@intel.com>
=> DM: Attestation Keybox support in SOS DM

devicemodel/hw/pci/xhci.c, devicemodel/hw/platform/usb_pmapper.c, devicemodel/include/usb_core.h, devicemodel/include/usb_pmapper.h
This patch set is used to speed up resuming time. The test result shows
it could decrease this time by 500ms ~ 1000ms.
Tracked-On: #2576 
=> S3 implemetation to speed up resuming time

devicemodel/samples/apl-mrb/sos_bootargs_release.txt
as security request, release build can't inlcude console
configure, so remove it.
Tracked-On: #2613
=> DM: rm console in release args for security reuest

hypervisor/common/io_req.c
This issue is triggered when launch fuzzing test.
Fuzzing test thread will call destroy_vm(IC_DESTROY_VM)
to set the guest vCPU state to VCPU_ZOMBIE then VCPU_INIT
and then VCPU_OFFLINE, it will cause post-work can't resume
the guest vCPU and can't changes the state of the
corresponding I/O request slot to REQ_STATE_FREE.
So replace improper use of ASSERT with return error code.
Tracked-On: #2606
=> HV: return an error code when REQ state mismatch in acrn_insert_request

hypervisor/boot/sbl/abl_seed_parse.c
'len' and 'arg' might be used uninitialized in abl_seed_parse().
Fix them by setting initial value.
Tracked-On: #2618
=> hv: fix possibility of using uninitialized params

hypervisor/Makefile, hypervisor/arch/x86/guest/vcpuid.c, hypervisor/arch/x86/guest/vlapic.c, hypervisor/arch/x86/guest/vmsr.c, hypervisor/debug/hypercall.c, hypervisor/debug/profiling.c
make hypervisor PROFILING=0, it will disable profiling and pmu will be pass-thru and perf tools can be run directly inside UOS.
Tracked-On:#2598
=> Patches to passthru PMU to UOS

hypervisor/boot/sbl/abl_seed_parse.c
Due to ABL design change, it will reword the "dev_sec_info.param_addr="
to "ABL.svnseed" in command line.
Tracked-On: #2611
=> hv: search additional argument when parsing seed from ABL

devicemodel/hw/pci/virtio/virtio.c
Without memory barrier, the change of used ring index could not
immediately detected by FE, this would bring some problems.
For virtio-blk FE driver, when it receives an interrupt, and confirms the
used ring index has changed, it will first set ring flags with
VRING_AVAIL_F_NO_INTERRUPT, then get buffer from virtqueue, after
process this request, it will mask VRING_AVAIL_F_NO_INTERRUPT, and get
used ring index again before return. If used ring changes, it will
process it. At the same time, BE will read this flags before each notify,
if VRING_AVAIL_F_NO_INTERRUPT was set, BE will not inject interrupt.
Without memory barrier, before FE mask VRING_AVAIL_F_NO_INTERRUPT, BE
has finished notify without interrupt, then FE mask
VRING_AVAIL_F_NO_INTERRUPT, and get used ring index but failed (index …
=> dm: virtio: add memory barrier before notify FE

devicemodel/samples/apl-mrb/launch_uos.sh
This reverts commit 5df9cbe36a7a0a3a3e6a87f6fa9345db6080bc5a.
As DISCARD support will cause kernel hung in stability test of warm
reset, so not enable this feature in launch script.
Tracked-On: #2633
=> Revert "dm: script: enable discard feature for virtio-blk"

hypervisor/arch/x86/guest/vm.c, hypervisor/arch/x86/init.c, hypervisor/bsp/uefi/cmdline.c, hypervisor/debug/console.c, hypervisor/debug/dbg_cmd.c, hypervisor/debug/dump.c, hypervisor/debug/hypercall.c, hypervisor/debug/logmsg.c, hypervisor/debug/npk_log.c, hypervisor/debug/printf.c, hypervisor/debug/profiling.c, hypervisor/debug/sbuf.c, hypervisor/debug/shell.c, hypervisor/debug/string.c, hypervisor/debug/trace.c, hypervisor/debug/uart16550.c, hypervisor/debug/vuart.c, hypervisor/hw/pci.c, hypervisor/include/arch/x86/multiboot.h, hypervisor/include/debug/console.h, hypervisor/include/debug/dbg_cmd.h, hypervisor/include/debug/shell.h, hypervisor/include/debug/uart16550.h, hypervisor/include/debug/vuart.h
only include some necessary header files, doesn't include hypervisor.h
=> Cleanup header files for debug folder

hypervisor/arch/x86/guest/vcpu.c, hypervisor/arch/x86/guest/virq.c, hypervisor/arch/x86/guest/vlapic.c, hypervisor/dm/vioapic.c, hypervisor/include/arch/x86/guest/vcpu.h
v4: revise the commit message
v3: update EOI-exit bitmap only when updating TMR in a vcpu
v2: rename set_eoi_exit to set_eoi_exit_bitmap
v1:
1) The previous implementaion will recalculate the whole EOI-exit bitmap for
each RTE once the destination, trigger mode, delivery mode or vector of a RTE
has changed and update the EOI-exit bitmap for each vcpu of the VM.
In this patch, only set the corresponding bit of EOI-exit bitmap for
a vcpu when a level triggered interrupt has accepted in IRR or clear the
corresponding bit of EOI-exit bitmap for a vcpu when a dege triggered interrupt
has accepted in IRR which means only update a bit of EOI-exit bitmap in a vcpu
when updating TMR.
2) Rename set eoi_exit related API to set eoi_exit_bitmap.
Signed-off-by: Li, Fei1 …
=> hv: vmcs: simplify update EOI-exit bitmap

devicemodel/Makefile, tools/acrn-crashlog/Makefile, tools/acrn-manager/Makefile, tools/acrnlog/Makefile, tools/acrntrace/Makefile
Currently, we are enforcing the _FORTIFY_SOURCE=2 without any
previous detection if the macro has been already defined, e.g.
by environment, or is just enabled by compiler by default on
some distributions (e.g. Gentoo).
This could result in the error like this:
<command-line>:0:0: error: "_FORTIFY_SOURCE" redefined [-Werror]
<built-in>: note: this is the location of the previous definition
Tracked-On: #2344
=> Makefile: undefine _FORTIFY_SOURCE prior using it

hypervisor/release/console.c, hypervisor/release/dump.c, hypervisor/release/hypercall.c, hypervisor/release/logmsg.c, hypervisor/release/npk_log.c, hypervisor/release/profiling.c, hypervisor/release/trace.c, hypervisor/release/vuart.c
cleanup release folder, only include some necessary
header files,doesn't include hypervisor.h
modified:   release/console.c
modified:   release/dump.c
modified:   release/hypercall.c
modified:   release/logmsg.c
modified:   release/npk_log.c
modified:   release/profiling.c
modified:   release/trace.c
modified:   release/vuart.c
=> hv:cleanup header files for release folder

tools/acrn-crashlog/acrnprobe/event_handler.c, tools/acrn-crashlog/acrnprobe/history.c, tools/acrn-crashlog/acrnprobe/include/load_conf.h, tools/acrn-crashlog/acrnprobe/sender.c, tools/acrn-crashlog/common/strutils.c
Since "history_event" file records limited events (5000 lines by default),
a new file named "all events" to count all kind of events.
=>  tools: acrn-crashlog: new file to count all events happened in system

hypervisor/common/hv_main.c, hypervisor/common/hypercall.c, hypervisor/common/io_req.c, hypervisor/common/ptdev.c, hypervisor/common/schedule.c, hypervisor/common/softirq.c, hypervisor/common/stack_protector.c, hypervisor/common/trusty_hypercall.c, hypervisor/common/vm_load.c, hypervisor/dm/vioapic.c, hypervisor/dm/vmptable.c, hypervisor/dm/vpci/core.c, hypervisor/dm/vpci/hostbridge.c, hypervisor/dm/vpci/msi.c, hypervisor/dm/vpci/msix.c, hypervisor/dm/vpci/partition_mode.c, hypervisor/dm/vpci/pci_pt.c, hypervisor/dm/vpci/sharing_mode.c, hypervisor/dm/vpci/vpci.c, hypervisor/dm/vpic.c, hypervisor/dm/vrtc.c
it removes hypervisor.h and just includes needed header files.
=> HV: cleanup header files under hypervisor dm&common

devicemodel/hw/pci/virtio/virtio_gpio.c
For virtio-based device, it needs to use virtio_base as the first member
otherwise, virtio_linkup will fail.
=> DM: virtio-gpio: use virtio_base as the first member of virtio_gpio

devicemodel/core/hugetlb.c, devicemodel/core/smbiostbl.c, devicemodel/core/sw_load_common.c, devicemodel/core/vmmapi.c, devicemodel/hw/pci/core.c, devicemodel/hw/pci/virtio/vhost.c, devicemodel/include/pci_core.h, devicemodel/include/sw_load.h, devicemodel/include/vmmapi.h, hypervisor/arch/x86/Kconfig, hypervisor/include/arch/x86/page.h
Add 1G PCI high MMIO address space
OVMF will check the bar address 64 bits bar and it asserts 64 bits
bar address should be above 4G. This patch adds 1G address space
from 4G to 5G which servers this requirement. The changes include:
1) Add additional 8MB RAM size for UOS in hypervisor because currently
pages used for EPT mapping is statically defined. Additional 2MB is
required for 1G per VM. The default VM number is 4.
2) Allocate 64bit MMIO above 4G strictly to pass OVMF check
3) Change the EPT mapping, device model user space address mapping and
e820 table accordingly.
Tracked-On: #2577
=> Pci bar64 highmem

devicemodel/samples/apl-mrb/launch_uos.sh
Fix run launch_uos script with "-d" parameter fail issue.
Tracked-On: #2659
=> ACRN: dm: Fix luanch UOS script "-d" parameter fail issue

doc/developer-guides/coding_guidelines.rst
This patch fixes the typo related to tab.
=> doc: fix the typo related to tab

hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/init.c
move 'init_iommu()' & 'ptdev_init()' before starting
all secondary cores to avoid access uninitialized resource
in partition mode.
=> hv:move forward the initialization for  iommu & ptdev

hypervisor/arch/x86/vtd.c, hypervisor/boot/dmar_parse.c, hypervisor/bsp/sbl/const_dmar.c
get_dmar_info API is called from multiple functions in vtd.c. This patch
calls get_dmar_info once during init and uses the cached info during
runtime.
Tracked-On: #2657
=> hv: Remove redundant get_dmar_info API calls

hypervisor/common/vm_load.c
vcpu returned by get_primary_vcpu API is BSP vcpu of the VM. So
checking is_vcpu_bsp on vcpu is redundant.
Tracked-On: #2668
=> hv: fix a redundant check in general_sw_loader

hypervisor/arch/x86/guest/vcpuid.c, hypervisor/include/arch/x86/cpuid.h
ECS.bit31 is not used and always return 0 in SDM Vol.2A 3-195. It's a
standard way to indicate whether there is a hypervisor.
Track-On: #2490
Ref: https://lwn.net/Articles/301888/
=> [hv] set ECX.bit31 to indicate the presence of a hypervisor

hypervisor/arch/x86/guest/vlapic.c, hypervisor/include/arch/x86/guest/vlapic.h
Correct wrong use of vector where lvt_index should be used.
=> hv: vlapic: correct wrong use of vector

hypervisor/arch/x86/guest/virq.c, hypervisor/boot/uefi/uefi_boot.c, hypervisor/common/vm_load.c, hypervisor/include/arch/x86/guest/vm.h
This patch simplifies `get_primary_vcpu` and `vcpu_from_vid`.
The target_vcpu could be get from the index directly.
=> hv: simplify `get_primary_vcpu` and `vcpu_from_vid`

hypervisor/arch/x86/guest/vlapic.c
1) call vlapic_accept_intr directly in vlapic_set_error  to fire it directly. Otherwise, if LVT ERR vector is invalid, an invalid interrupt will be accepted in IRR.
2) add vector check for x2apic SELF IPI
3) move LVT IRQ vector check to vlapic_fire_lvt to simple the vector check for LVT IRQ
=> Vlapic: refine vlapic Error Handling

devicemodel/core/main.c, devicemodel/hw/pci/core.c
There was a workaround in DM that allocates PCI 64bit mem bar in 32bit mem space
if the bar size is within 32MB.
After the workaround being removed, there is an issue to enter fastboot
mode for inappropriate handling of 64bit mem bar in guest driver.
The patch bring the workaround back, and skip the workaround when the guest
is booted by OVMF.
Revert the patch after the guest fixs the issue of handling 64bit mem bar in
fastboot mode.
Tracked-On: #2677
=> [RevertMe] dm: pci: restore workaround when alloc pci mem64 bar

devicemodel/samples/apl-mrb/launch_uos.sh
Script: Fix snd_soc_skl typo in launch script 
Tracked-On:https://github.com/projectacrn/acrn-hypervisor/issues/2666
=> Script: Fix snd_soc_skl typo in launch script

hypervisor/arch/x86/guest/vlapic.c, hypervisor/debug/profiling.c
This patch refined the pmu passthru irq handling, which will re-enable
the PMC interrupt in the vlapic handler. So that can avoid some
interrupt storm situation happens.
This patch can fix the remaining Android perf CTS failure.
Tracked-On: #2598
=> hv: refined the pmu passthru irq handling

devicemodel/include/dm_kmsg.h, devicemodel/lib/dm_kmsg.c
String function of strlen()/vsnprintf() shuould be replaced.
This patch remove the strlen(). And vsnprintf() replaced by vasprintf().
Tracked-On: #2687
Reviewed-by: Tianhua Sun <tianhuax.s.sun@intel.com>
=> dm: replace unsafe string api for acrn-dm

hypervisor/arch/x86/Kconfig
change the config type of COM_IRQ from "hex" to "int"; make
it consistent with its default value.
Tracked-On: #2689
=> HV: correct COM_IRQ default config type

hypervisor/common/hypercall.c, hypervisor/debug/shell.c
to validate the ID and state of vCPU in below functions:
- hcall_set_vcpu_regs()
- hcall_notify_ioreq_finish()
- shell_vcpu_dumpreq()
=> hv:validate ID and state of vCPU for related APIs

doc/developer-guides/hld/hv-timer.rst, hypervisor/arch/x86/guest/vcpuid.c, hypervisor/arch/x86/timer.c, hypervisor/include/arch/x86/timer.h, hypervisor/include/lib/rtl.h
-- change 'tsc_khz' to static
-- move these APIs from rtl.h to timer.c
us_to_ticks()
ticks_to_us()
ticks_to_ms()
rdtsc()
=> hv:move several tsc APIs to timer.c

devicemodel/arch/x86/pm.c
check the power button acpi driver firstly, then find input event
corresponding to the power button.
Tracked-On: #2695
=> dm: use power button acpi device to find its input event

doc/api/devicemodel_api.rst, doc/developer-guides/doc_guidelines.rst, doc/developer-guides/hld/hld-security.rst, doc/getting-started/apl-nuc.rst, doc/getting-started/up2.rst, doc/hardware.rst, doc/tutorials/agl-vms.rst, doc/tutorials/trustyACRN.rst
Found some broken links to external sites in the documentation.
=> doc: fix broken external links

hypervisor/arch/x86/configs/vm_config.c
Previous change 'HV: modularization vm config code', commit id
1bb15c64a668a82c87b92aa5b5e3ceb88f264d2a, lost CAT code when move
sanitize_vm_config() from vm.c to vm_config.c
=> HV: Fix modularization vm config code lost CAT code

hypervisor/arch/x86/guest/vm.c
In partition mode, unassign_iommu_device() is called from vpci_cleanup(),
so when shutdown_vm() is called, unassign_iommu_device() could fail because
of "domain id mismatch" and DMAR is not cleared.
Also move destroy_ept() after the call to destroy_iommu_domain().
=> hv: destroy IOMMU domain after vpci_cleanup()

doc/tutorials/create-up2-images.sh
The board name for building images for UP2 has been changed from 'up2' to 'apl-up2' by the commit https://github.com/projectacrn/acrn-hypervisor/commit/f9b5e21bdc325a57a253001685d26174984d212c
Tracked-On: #2661
=> doc: use the new board name for UP2 in create-up2-images.sh script

hypervisor/arch/x86/guest/assign.c, hypervisor/arch/x86/vtd.c, hypervisor/include/arch/x86/vtd.h
Except for few translation structures in x86 IOMMU, all translation
structures are 128-bit. All the translation structures used by ACRN
are 128 bit. So removed multiple definitions and defined a struct
that accomodates 128 bit entries.
Tracked-On: #2668
=> hv: Remove multiple definitions for dmar translation structures

hypervisor/hw/pci.c
Add a fatal warning when an PCI device is added with an MSI-X table_count
larger than CONFIG_MAX_MSIX_TABLE_NUM. This is fatal since the init function
in the handler for MSI-X (vmsix_init) only looks at table_count when
populating the table. Since CONFIG_MAX_MSIX_TABLE_NUM is the max size of the
table array entry in the pci_msix struct. This will cause the msix handler
to write outside of the table array.
Tracked-On: #2624
=> Add fatal warning PCI MSIX table count > conf max

doc/user-guides/acrn-shell.rst
Update the "ACRN Shell Commands" user guide in the following aspects:
* Improve the text (help) for some commands to improve readability
* Remove commands that are no longer available
* Add the 'vioapic' command that was missing
Note: this patch does not add a description for both the "[rd|wr]msr"
commands.
Tracked-On: #2684
=> Documentation: update the "ACRN Shell Commands" user guide

devicemodel/core/sw_load_elf.c
Dynamic memory stored in 'elf32_phdr' allocated
through 'calloc' be lost.
Tracked-On: #2705
=> dm: fix possible memory leak in 'load_elf32()'

devicemodel/core/main.c
To reduce the io emulation impact to audio FE which could
trigger audio glitch.
Tracked-On: #2717
=> acrn-dm: set realtime sched policy for vcpu thread

doc/developer-guides/coding_guidelines.rst
This patch fixes typos in coding guidelines.
Tracked-On: #2711
=> doc: fix typos in coding guidelines

devicemodel/hw/pci/virtio/virtio_net.c
Dynamic memory stored in 'net' allocated through function 'calloc'
should be freed correspondingly when return fail.
Tracked-On: #2704
=> dm: virtio-net: fix memory leak

devicemodel/core/main.c
typo fix:
/sys/fs/cgroup/cpu/task -> /sys/fs/cgroup/cpu/tasks
Tracked-On: #2717
=> dm: fix typo of path for cgroup cpu tasks

hypervisor/arch/x86/guest/guest_memory.c
Accessing memory of guest will cause page fault when SMAP is enabled.
This patch stac()/clac() correspondingly to get rid of this situation.
Tracked-On: #2713
=> HV: PAE: Add stac()/clac() in local_gva2gpa_pae

tools/acrn-manager/acrn_mngr.c, tools/acrn-manager/acrn_mngr.h, tools/acrn-manager/acrn_vm_ops.c, tools/acrn-manager/acrnctl.h, tools/acrn-manager/acrnd.c
Backport acrnd patches from apl_sdc_stable
Print more information at acrnd_add_work(), query_state()
try_do_works() and handle_acrnd_resume()
Tracked-On: #2716
=> Backport acrnd patches from apl_sdc_stable

hypervisor/arch/x86/cpu_caps.c, hypervisor/arch/x86/guest/vcpu.c, hypervisor/arch/x86/guest/virq.c, hypervisor/arch/x86/guest/vlapic.c, hypervisor/arch/x86/guest/vmcs.c, hypervisor/arch/x86/guest/vmsr.c, hypervisor/include/arch/x86/cpu_caps.h
Add two functions to combine constraint for APICv:
is_apicv_basic_feature_supported: check the physical platform whether support
"Use TPR shadow", "Virtualize APIC accesses" and "Virtualize x2APIC mode"
is_apicv_advanced_feature_supported: check the physical platform whether support
"APIC-register virtualization", "Virtual-interrupt delivery" and
"Process posted interrupts".
If the physical platform only support APICv basic feature, enable "Use TPR shadow"
and "Virtualize APIC accesses" for xAPIC mode; enable "Use TPR shadow" and
"Virtualize x2APIC mode" for x2APIC. Otherwise, if the physical platform support
APICv advanced feature, enable APICv feature for xAPIC mode and x2APIC mode.
=> hv: vlapic: add combined constraint for APICv

tools/acrn-manager/acrnctl.c
When run 'acrnctl add', acrnctl dryruns launch script to get
vmname. Acrnctl assumes there are no more than 64 words in each
line of the script, and creates a buffer to hold 64 pointers to these
words. But we didn't check if the number of words exceed 64 limitation,
which can lead to buffer overflow. This commit fixed this potential
overflow problem.
And also refine some confusing error messages in 'acrnctl add'
Tracked-On: #2734
Acked-by: Yan Like <like.yan@intel.com>
=> tools: acrnctl fix potential buffer overflow

tools/acrn-manager/acrnctl.c
When run 'acrnctl add', acrnctl dryruns launch script to get
vmname. Acrnctl assumes there are no more than 64 words in each
line of the script, and creates a buffer to hold 64 pointers to these
words. But we didn't check if the number of words exceed 64 limitation,
which can lead to buffer overflow. This commit fixed this potential
overflow problem.
And also refine some confusing error messages in 'acrnctl add'
Tracked-On: #2734
Acked-by: Yan Like <like.yan@intel.com>
=> tools: acrnctl fix potential buffer overflow for apl_sdc_stable

hypervisor/arch/x86/vtd.c
Fix compile warning on UEFI platform when check bus number.
Tracked-On: #2743 
=> hv: vtd: fix compile warning on UEFI platform

hypervisor/arch/x86/guest/instr_emul.c, hypervisor/arch/x86/guest/io_emul.c, hypervisor/arch/x86/pm.c, hypervisor/arch/x86/timer.c, hypervisor/arch/x86/vmx.c, hypervisor/include/arch/x86/guest/instr_emul.h, hypervisor/include/arch/x86/guest/vcpu.h, hypervisor/include/arch/x86/per_cpu.h
--now the 'cpu_mode' is unused in struct vm_guest_paging,
and there is the  same variable in struct acrn_vcpu_arch
--  move instr_emul_ctxt instance from struct per_cpu_region
to struct vcpu, and rename it from g_inst_ctxt to inst_ctxt
=> move instr_emul_ctxt instance to struct vcpu

hypervisor/arch/x86/guest/guest_memory.c, hypervisor/boot/dmar_parse.c, hypervisor/boot/sbl/abl_seed_parse.c, hypervisor/boot/sbl/multiboot.c, hypervisor/boot/sbl/sbl_seed_parse.c, hypervisor/boot/uefi/uefi_boot.c, hypervisor/include/arch/x86/abl_seed_parse.h, hypervisor/include/arch/x86/guest/guest_memory.h, hypervisor/include/arch/x86/sbl_seed_parse.h
In order to remove the usage of hypervisor.h,
modularize the boot folder.
Current changes include modifications to remove
usage of acrn_vm structure pointer, from some of
the call, and remove calls to hypervisor.h,
as and when deemed fit.
Removed hva2gpa, as this was not used anywhere else
after the changes.
Tracked-On: #2694 
=> HV: Modularize boot folder

hypervisor/dm/vpci/hostbridge.c, hypervisor/dm/vpci/msi.c, hypervisor/dm/vpci/msix.c, hypervisor/dm/vpci/partition_mode.c, hypervisor/dm/vpci/pci_priv.h, hypervisor/dm/vpci/pci_pt.c, hypervisor/dm/vpci/sharing_mode.c, hypervisor/include/dm/vpci.h
Changes include:
Remove the populate_msi_struct() function, put msi initialization specific
functionality into msi.x, and put msix initialization specific functionality
into msix.c
Declare and export sharing mode's vdev functions as global instead of static local
Declare and export partition mode's vdev functions as global instead of static local
Minor code cleanup for partition mode
Tracked-On: #2534
Signed-off-by: dongshen dongsheng.x.zhang@intel.com
Will need to post more patches to eventually unify the VPCI partition/sharing mode code
=> Unifying the VPCI partition mode and sharing mode code (patch series #3)

hypervisor/Makefile, hypervisor/arch/x86/guest/trusty.c, hypervisor/arch/x86/init.c, hypervisor/arch/x86/seed/seed.c, hypervisor/arch/x86/seed/seed_abl.c, hypervisor/arch/x86/seed/seed_abl.h, hypervisor/arch/x86/seed/seed_sbl.c, hypervisor/arch/x86/seed/seed_sbl.h, hypervisor/boot/sbl/multiboot.c, hypervisor/include/arch/x86/guest/trusty.h, hypervisor/include/arch/x86/seed.h
New component to maintain seed retrieval and derivation: seed.
1. Retrieve seed from bootloader in Hypervisor's boot stage.
2. Derive virtual seed for Guest/Trusty if need.
Tracked-On: #2724
Reviewed-by: Zhu Bing <bing.zhu@intel.com>
=> hv: refactor seed management

devicemodel/samples/apl-mrb/launch_uos.sh
audio-mediator: load updated audio kernel modules because audio kernel modules updates names and add two news from SOS 28100
Tracked-On: #2744 
=> audio-mediator: load updated audio kernel modules 

devicemodel/hw/pci/gvt.c, devicemodel/hw/pci/passthrough.c
Otherwise it causes the memory leak.
V1->V2: Fix the leak of pi->arg as gvt structure also needs to be released.
Track-On: https://github.com/projectacrn/acrn-hypervisor/issues/2762
=> Fix the memory leak of pci_gvt_init and passthru_init in DeviceModel

devicemodel/hw/block_if.c, devicemodel/hw/pci/core.c
1. free memory allocated by strdup in blockif_open
2. free msix.table when its pci device deinit
Tracked-On: #2704
=> DM: fix memory leak

doc/conf.py
With the 0.7 release published, we can add the v0.7 doc menu choice.
=> doc: add v0.7 version to master branch (/latest)

hypervisor/arch/x86/e820.c, hypervisor/arch/x86/guest/vm.c, hypervisor/arch/x86/mmu.c, hypervisor/boot/reloc.c, hypervisor/common/hypercall.c
The init page tables installed in either cpu_primary.S or trampoline.S
are 1:1 mapping and won't be changed in the future.
The 'actual' hypervisor page table installed in enable_paging() is 1:1
mapping currently but it could be changed in the future. Both hva2hpa() and
hpa2hva() are implemented based on these page tables and can't be used
when the init page tables take effect.
This patch does the following cleanup:
- remove all hva2hpa()/hpa2hva() before calling enable_paging()
- get_hv_image_base() returns HVA, not HPA. So add hva2hpa() for all cases
that are called afte enable_paging().
=> hv: cleanup some hva/hpa conversion code

hypervisor/arch/x86/guest/trusty.c, hypervisor/include/arch/x86/guest/vcpu.h
Remove vmx_cr0/vmx_cr4 from ext_context structure, they are duplicated
with cr0/cr4 fields in run_context.
Switch cr0/cr4 of run_context structure on demand when do world switch.
Remove vmx_cr0_read_shadow/vmx_cr4_read_shadow from ext_context structure.
These fields should be same for both normal world and secure world.
Tracked-On: #2773
=> hv: trusty: refine control registers switching method

hypervisor/arch/x86/seed/seed.c, hypervisor/arch/x86/seed/seed_abl.c, hypervisor/arch/x86/seed/seed_sbl.c, hypervisor/include/arch/x86/guest/trusty.h, hypervisor/include/arch/x86/seed.h
1. move seed_info structure from trusty.h to seed.h
2. replace "#include <hypervisor.h>" with necessary including headers
in seed.c/seed_abl.c/seed_sbl.c
Tracked-On: #2777
=> hv: seed: refine header file

Makefile
apl-nuc will be the default board building for.
Tracked-On: #2780
=> Makefile: build for apl-nuc by default

hypervisor/include/arch/x86/vm_config.h
VM use CLOS when set CLOS_REQUIRED in guest flags of vm_config. The
wrong comment is 'if guest_flags has CAT_ENABLED', and should be fixed
as 'if guest_flags has CLOS_REQUIRED'
=> hv: fix wrong comment message about CLOS usage in vm config

devicemodel/core/vmmapi.c, devicemodel/hw/pci/passthrough.c, devicemodel/include/vmmapi.h, hypervisor/dm/vpci/sharing_mode.c
The msi/msix interrupt information is not properly configured after a pci device un-assigned from UOS.
The patch series pass physcial bdf, which is needed in hypervisor to find the right pci dev.
After the pci device un-assigned from UOS, the virtual bdf should be restored.
Tracked-On: #2788
=> Fix msi/msix interrupt after pci device un-assigned from uos

hypervisor/arch/x86/guest/vm.c, hypervisor/dm/vpci/hostbridge.c, hypervisor/dm/vpci/msi.c, hypervisor/dm/vpci/msix.c, hypervisor/dm/vpci/pci_priv.h, hypervisor/dm/vpci/pci_pt.c, hypervisor/dm/vpci/sharing_mode.c, hypervisor/include/dm/vpci.h
Changes include:
Extract common code blocks to has_msi_cap and has_msix_cap functions
Remove intercepted_gpa and intercepted_size from struct pci_msix
Add const qualifier for the deinit vdev op functions
Remove vdev ops for sharing mode
Misra c violation fix
Tracked-On: #2534
Signed-off-by: dongshen dongsheng.x.zhang@intel.com
Will need to post more patches to eventually unify the VPCI partition/sharing mode code
=> Unifying the VPCI partition mode and sharing mode code (patch series #4)

hypervisor/arch/x86/guest/vcpu.c
Suppose run_ctx.cr0/cr4 are correct when do world switching, so call
vcpu_set_cr0/cr4() to update cr0/cr4 directly before resume to guest.
This design is only for trusty world switching.
Tracked-On: #2773
=> hv: update CR0/CR4 on demand in run_vcpu()

hypervisor/Makefile, hypervisor/arch/x86/guest/vm.c, hypervisor/include/arch/x86/guest/vm.h
Previously vrtc is for partition mode only, now enable it for sharing mode;
=> HV: add vrtc for sharing mode

hypervisor/Makefile, hypervisor/arch/x86/configs/apl-mrb/ve820.c, hypervisor/arch/x86/configs/apl-up2/ve820.c, hypervisor/arch/x86/configs/dnv-cb2/ve820.c, hypervisor/arch/x86/configs/nuc6cayh/ve820.c, hypervisor/arch/x86/configs/nuc7i7bnh/ve820.c, hypervisor/arch/x86/guest/vm.c, hypervisor/include/arch/x86/board.h, hypervisor/include/arch/x86/e820.h
Preparing for hybrid mode:
- create vE820 for pre-launched VMs and do other init code when the
vm_config->type is PRE_LAUNCHED_VM.
- create ve820.c for each board because without wrapping by
CONFIG_PARTITION_MODE, ve820_entry[] needs to be visible even when
compiling target boards that haven't enabled pre-launched VMs.
- remove create_prelaunched_vm_e820() from vm.c and implement board
specific function for each $(CONFIG_BOARD)/ve820.c. The reasons being:
- don't need to define ve820_entry[32] for those boards that don't
support pre-launched VMs.
- more importantly, this makes it much easier to create different per-VM
vE820 when it's needed.
=> hv: remove CONFIG_PARTITION_MODE for pre-launched VM vE820 creation

doc/user-guides/acrn-shell.rst
Add 'rdmsr' and 'wrmsr' to the "ACRN Shell Commands" documentation. Both are
already described via the interactive help command but not (yet) included in our
on-line documentation.
Tracked-On: #2684
=> doc: add rdmsr/wrmsr to the "ACRN Shell Commands" documentation

doc/tutorials/increase-uos-disk-size.rst
Add a tutorial on how to increase the disk size of a User OS (UOS)
based on Clear Linux. The tutorial is largely inspired from Clear Linux
tutorial and refers to it. It mostly explains how to resize the .img
file using the 'qemu-img' tool since ACRN does not have any dedicated
tool for manipulating virtual disk image files.
=> doc: add tutorial on how to increase the UOS disk size

hypervisor/boot/sbl/multiboot.c, hypervisor/debug/shell.c, hypervisor/debug/uart16550.c
strncpy_s(d, dmax, s, slen): the 'dmax' includes the null terminator, while
slen doesn't. Thus if (dmax == slen == strlen(s)), strncpy_s() chooses to
discard the last character from s and instead write '\0' to d[dmax - 1].
strnlen_s(s, maxsize): if there is no terminating null character in the
first maxsize characters pointed to by s, strnlen_s() returns maxsize.
So in the following example or similar cases, we need to increase the size
of d[] by 1 to accommodate the null terminator, and add '1' to the dmax
argument to strncpy_s().
uint8_t d[MAX_LEN];
size = strnlen_s(s, MAX_LEN);
strncpy_s(d, MAX_LEN, s, size);
=> hv: minor fixes to a few calls to strncpy_s()

hypervisor/arch/x86/vtd.c, hypervisor/include/arch/x86/vtd.h
ACRN uses global invalidation for all DMAR translation caches. Whenever
a UOS is shutdown or rebooted, it ends up clearing entries in translation
caches belonging to other VMs/domains. This patch adds support for
domain/device level invalidation for DMA translation caches and index
based invalidation for Interrupt Remapping Cache
Tracked-On: #2738
=> hv: Use domain/device specific invalidation for DMAR translation caches

hypervisor/dm/vpci/hostbridge.c, hypervisor/dm/vpci/msi.c, hypervisor/dm/vpci/msix.c, hypervisor/dm/vpci/partition_mode.c, hypervisor/dm/vpci/pci_priv.h, hypervisor/dm/vpci/pci_pt.c, hypervisor/dm/vpci/sharing_mode.c, hypervisor/dm/vpci/vdev.c, hypervisor/dm/vpci/vpci.c, hypervisor/include/dm/vpci.h
Changes include:
Remove vdev ops for partition mode, change related code to directly call the corresponding
functions instead.
Do not call vpci ops, call the corresponding sharing mode/partition functions
directly instead
Various misra C violations fix
Unify the sharing mode and partition mode coding style for similar functions
Centralize the pci cfg read/write sanity checking code
Tracked-On: #2534
Signed-off-by: dongshen dongsheng.x.zhang@intel.com
Will need to post more patches to eventually unify the VPCI partition/sharing mode code
=> Unifying the VPCI partition mode and sharing mode code (patch series #5)

hypervisor/arch/x86/guest/vcpuid.c, hypervisor/arch/x86/guest/vmexit.c, hypervisor/arch/x86/guest/vmsr.c, hypervisor/include/arch/x86/cpu.h, hypervisor/include/arch/x86/cpuid.h
This patch hide Memory Protection Extention (MPX) capability from guest.
- vCPUID change:
Clear cpuid.07H.0.ebx[14]
Clear cpuid.0DH.0.eax[4:3]
- vMSR change:
Add MSR_IA32_BNDCFGS to un-supported MSR array.
- XCR0[4:3] is not allowed to set by guest.
Tracked-On: #2821
=> hv: disable mpx capability for guest

hypervisor/arch/x86/guest/vmsr.c
Linux access TSC_ADJUST to verify it has not tampered every time when enter idle.
So for RTVM running rt-linux, the access will cause vm exit which affect real-time performance.
This commit pass through TSC_ADJUST to VM with lapic_pt, to avoid TSC_ADJUST caused vm_exit.
For other VMs, TSC_ADJUST msr access is still trapped and emulated.
Tracked-On: #2813
=> hv: passthru TSC_ADJUST to VM with lapic pt

hypervisor/debug/shell_priv.h
Enhance the ACRN shell interactive help. It is close to a 1-1 mapping with
the online documentation but cut a little shorter in various places to make it
more user-friendly when using it from the ACRN console.
Tracked-On: #2829
=> hv: enhance ACRN shell interactive help

doc/tutorials/using_zephyr_as_uos.rst
This patch add tutorial about using zephyr as guest.
Tracked-On: #2713
=> Doc: Add tutorial about using zephyr as uos

devicemodel/core/mem.c, devicemodel/core/sw_load_common.c, devicemodel/core/sw_load_ovmf.c, devicemodel/hw/pci/core.c, devicemodel/include/mem.h, devicemodel/include/public/acrn_common.h, devicemodel/include/sw_load.h, devicemodel/include/tree.h
OVMF requires a more descriptive mechanism than RTC CMOS to retrieve ACRN's memory layout, so we now pass the E820 map to it, starting at 0xEF000 (ROM area).
ACRN currently uses [4GB, 5GB) as its 64-bit PCI host aperture. This is inconsistent with OVMF's assumption of its platform's memory layout, because it derives the size of high memory from RTC CMOS, which is incapable of describing the 64-bit PCI hole.
By default, OVMF uses RTC CMOS 0x5b/0x5c/0x5d to determine the size of high memory. This value only tells OVMF how much memory is above 4GB, but not the platform's memory layout above 4GB.
Using RTC CMOS works for QEMU, because QEMU places its 64-bit PCI host aperture above its highmem. Therefore, OVMF can always assume highmem is located at [4GB, 4GB + highmem), which is not where …
=> Pass ACRN E820 map to OVMF

hypervisor/bsp/include/firmware.h
Added a struct acrn_vm in firmware.h to remove
a compiler warning.
No change in logic.
Tracked-On: #2830
=> HV: Fix a compiler warning in firmware.h

devicemodel/hw/pci/virtio/virtio_gpio.c
virtio GPIO IRQ emulates a GPIO IRQ controller to support
level trigger and edge trigger interrupts, it uses two virtqueues
one is for IRQ chip operations and the other is to notify IRQ sources.
v2: 1) refine code style.
2) refine IRQ controller that removing the IRQ generating thread.
3) add ACPI GPIO dsdt.
v3: 1) fix IRQ missing case.
2) if an IRQ is disabled, reconfig it to GPIO mode.
3) refine code style.
v4: 1) remove ndesc check since the FE driver will not kick the queue.
2) add comments.
3) add UOS and SOS flags for GPIO IRQ diagram.
=> DM: virtio-gpio: implement GPIO IRQ

hypervisor/arch/x86/seed/seed.c, hypervisor/boot/sbl/multiboot.c, hypervisor/common/vm_load.c, hypervisor/include/arch/x86/multiboot.h, hypervisor/include/arch/x86/vm_config.h
- for all cases of referring guest bootargs size, replace MEM_2K with
CONFIG_MAX_BOOTARGS_SIZE for better readability.
- remove duplicated MAX_BOOTARGS_SIZE definition from vm_config.h.
Also fix one minor issue in general_sw_loader() which uses copy_to_gpa()
to copy a string. Since copy_to_gpa() makes use of memncpy_s() to do the
job, the size parameter should include the string null ternimator.
Tracked-On: #2806
=> hv: replace MEM_2K with a new macro MAX_BOOTARGS_SIZE for bootargs size

hypervisor/arch/x86/guest/vmsr.c, hypervisor/debug/profiling.c, hypervisor/include/arch/x86/guest/vcpu.h
Currently MSR IA32_MISC_ENABLE is passthrough to guest.
However, guest may change the value of this MSR, which will cause issue in hypervisor.
This patch uses VMX MSR store area to isolate the MSR IA32_MISC_ENABLE between guest and host.
TODO:
Some bits of the MSR IA32_MISC_ENABLE is not just per core, but per package.
So need to check if need to prevent guest from setting or clearing these bits that may affect other cores.
Tracked-On: #2834
=> hv: vmsr: add IA32_MISC_ENABLE to msr store area

doc/developer-guides/sw_design_guidelines.rst
For open source, just need to refer FuSa standard instead
of listing concrete fulfillment matrix.
Add related FuSa standard reference and remove related
fulfillment matrix.
Signed-off-by: Xiangyang Wu <xiangyang.wu@linux.intel.com>
=> DOC:Update standard reference of SW design guidelines

doc/tutorials/increase-uos-disk-size.rst
Update the instructions on how to increase the size of a UOS disk image so that
the entire operation can be performed on the development host. This has the
advantage that it can be done completely offline (the UOS must be powered off
in fact) and no extra tools need to be installed in the UOS to do this.
=> doc: update the instructions to increase the size of a UOS disk image

doc/user-guides/acrn-dm-parameters.rst
OVMF images are now part of the source tree.
=> doc: update OVMF image location

devicemodel/core/sw_load_common.c, devicemodel/hw/pci/core.c, devicemodel/hw/platform/acpi/acpi.c, devicemodel/include/pci_core.h
Guest OS (e.g. Linux) may rely on a gap in E820 map in the 32-bit memory
space to determine the MMIO space for its PCI devices. Leave this gap
when building E820 map to keep the guest's PCI subsystem working.
After commit 7752d5cfe3d11ca0bb9c673ec38bd78ba6578f8e, Linux kernel no
longer requires the MMCONFIG region to be reserved in the E820 map.
Nonetheless, keep it in the reserved region to be on the safe side.
Tracked-On: #2843
=> dm: leave a gap for 32-bit PCI hole in E820 map

hypervisor/arch/x86/guest/virtual_cr.c, hypervisor/arch/x86/guest/vlapic.c, hypervisor/arch/x86/guest/vmsr.c, hypervisor/include/arch/x86/guest/vlapic.h
1) Shouldn't trap TPR since we always enable "Use TPR shadow"
2) remove TPR set/get API
Since we always enable "Use TPR shadow", so operate on TPR will not
trigger VM exit. So remove these APIs.
=> refine x2apic MSR bitmap setting part 1

hypervisor/arch/x86/guest/vm.c, hypervisor/common/hypercall.c, hypervisor/include/arch/x86/guest/vm.h
In hypervisor fuzzing test, hypervisor will hang
if issuing HV_VM_SET_MEMORY_REGIONS hypercall after
target VM is destroyed.
this patch is to fix above vulnerability.
Tracked-On: #2849
=> hv: fix vulnerability when VM is destroyed

hypervisor/debug/dump.c
In the cases when more than one CPU has something to print, exception
dump from one CPU is overlapped with other CPU's messages and the final
text that is printed on console is all mixed up and does not make any sense.
Changing printf to pr_err so that the messages are printed one after
the other.
Tracked-On: #2858
=> hv: Debug messages from a CPU are overlapped with other CPUs messages

hypervisor/arch/x86/guest/io_emul.c, hypervisor/arch/x86/guest/vm.c, hypervisor/include/arch/x86/guest/io_emul.h, hypervisor/include/arch/x86/guest/vm.h
Add the default handlers for PIO and MMIO access which returns all
FFs on read and discards write. These default handlers are registered
when SOS VM or pre-launched VM is created.
v2 -> v3:
- use runtime vm type instead of CONFIG_PARTITION_MODE
- revise the pio/mmio emulation functions
- revise the pio/mmio default read functions according to MISRA C
- revise the commit message
v1 -> v2:
- add default handlers members in struct acrn_vm and add interfaces
to register default handlers for PIO and MMIO.
Tracked-On: #2860
=> hv: add default handlers for PIO/MMIO access

tools/acrn-manager/acrnctl.c
Tools: acrnctl fix return value when it fails to execute the commands
acrnctl commands can manage multiple vms with a single
command launched, which is not useful actually.
To make the logic simple, this patch makes it to manage
only a single vm by each command.
Tracked-On: #1262
Signed-off-by:liuyonggang <yonggangx.liu@intel.com>
=> Acrn 2358 tools acrnctl

doc/tutorials/using_partition_mode_on_up2.rst, doc/tutorials/using_ubuntu_as_sos.rst
PLATFORM=xxx is no longer supported, use BOARD instead.
Tracked-On: #2708
=> doc: minor changes according to one binary for SBL and UEFI

hypervisor/arch/x86/configs/vm_config.c, hypervisor/arch/x86/guest/vm.c, hypervisor/common/hypercall.c, hypervisor/common/io_req.c, hypervisor/debug/profiling.c, hypervisor/debug/shell.c, hypervisor/debug/vuart.c, hypervisor/dm/vpci/vpci.c, hypervisor/include/arch/x86/guest/vm.h
Following changes are included in this PR:
- sanitize vm_id from user input from hv shell;
- cleanup invalid NULL pointer check of acrn_vm pointers, because it is always not NULL after using get_vm_from_vmid();
- rename local variable "guest_no" to a more common used name "vm_id".
Tracked-On:  #2520
=> vm_id and acrn_vm pointer cleanup

hypervisor/dm/vpic.c
This patch removes the unnecessary equality operation for
boolean variables.
=> hv: remove the unnecessary equality operation

hypervisor/common/hypercall.c
'vector_cnt' is vector count of MSI/MSIX, and it come from 'table_count'
in the the pci_msix struct. 'CONFIG_MAX_MSIX_TABLE_NUM' is the maximum
number of MSI-X tables per device, so 'vector_cnt' must be less then
or equal to 'CONFIG_MAX_MSIX_TABLE_NUM'.
Tracked-On: #2881
=> hv: check vector count when set/reset msix info

devicemodel/hw/block_if.c, devicemodel/hw/pci/virtio/virtio.c, devicemodel/hw/pci/virtio/virtio_block.c, devicemodel/hw/pci/virtio/virtio_coreu.c, devicemodel/hw/pci/virtio/virtio_hdcp.c, devicemodel/hw/pci/virtio/virtio_mei.c, devicemodel/hw/pci/virtio/virtio_net.c, devicemodel/hw/pci/virtio/virtio_rnd.c, devicemodel/hw/platform/ioc.c, devicemodel/hw/platform/tpm/tpm_crb.c, devicemodel/include/virtio.h
pthread_cond_wait() should take care of spurious wakeups and is usually used in conjunction with a predicate. Fix the uses of pthread_cond_wait() that can result in unintended behavior (e.g. segfault).
Several minor cleanups/fixes related to the code paths involving pthread_cond_wait() are also included.
Tracked-On: #2763
=> Fix pthread_cond_wait() usage

devicemodel/arch/x86/pm.c, devicemodel/hw/platform/acpi/acpi.c, devicemodel/include/acpi.h, hypervisor/include/public/acrn_common.h
To keep consistency between HV and DM about PM1A_CNT_ADDR,
it is better to replace the PM1A_CNT related MACROs used in DM
with VIRTUAL_PM1A_CNT related MACROs in acrn_common.h.
Tracked-On: #2865
=> DM: Keep consistency between HV and DM about PM1A_CNT_ADDR

hypervisor/arch/x86/guest/assign.c, hypervisor/arch/x86/guest/io_emul.c, hypervisor/arch/x86/guest/virq.c, hypervisor/arch/x86/guest/vm.c, hypervisor/arch/x86/irq.c, hypervisor/dm/vpci/pci_pt.c, hypervisor/dm/vpci/vmsi.c, hypervisor/dm/vpci/vmsix.c, hypervisor/dm/vpci/vpci.c, hypervisor/dm/vpci/vpci_priv.h, hypervisor/include/arch/x86/guest/assign.h, hypervisor/include/arch/x86/guest/vm.h, hypervisor/include/arch/x86/irq.h
This patch series achieves three goals
1) Support Interrupt Remapping for Pre-launched VMs MSI interrupts in ACRN software
2) Support VT-d Interrupt Remapping for Pre-launched VMs MSI interrupts
3) Remove the need for separate interrupt dispatch routine for Pre-launched VMs
Tracked-On: #2879
=> Support HV Interrupt Remapping for pre-launched VMs

devicemodel/hw/pci/xhci.c, devicemodel/hw/platform/usb_pmapper.c, devicemodel/include/usb_pmapper.h
1. free memory during pci_xhci_dev_destroy.
2. add libusb_free_device_list to free the list of devices previously
discovered using libusb_get_device_list().
3. fix possible memory corruption.
Tracked-On: #2892
=> DM USB: fix memory leak during reboot

doc/user-guides/kernel-parameters.rst
Columns were switched for the description of the memmap parameter
=> doc: fix memmap parameter description

doc/user-guides/kernel-parameters.rst
Remove an incorrect link reference (and target) and fix some
misspellings.
=> doc: remove odd GVT-g link

doc/user-guides/kernel-parameters.rst
=> doc: fix broken link to kernel options

doc/Makefile, doc/scripts/publish-robots.txt
use a robots.txt file to prevent search engines from indexing old
content.
=> doc: add robots.txt

doc/user-guides/acrn-dm-parameters.rst, doc/user-guides/index.rst
Few tweaks to the "User Guides" and "ACRN Device Model parameters" docs:
- Enhance the help text for the '--rtvm' option description
- Correct the flag name to IO_COMPLETION_POLLING
- Use double-backticks instead of quotes in various places
- Explicitly list all docs in 'index.rst' to enforce special ordering
=> doc: tweaks to the "User Guides" section (esp. "ACRN DM parameters")

devicemodel/hw/pci/virtio/virtio_gpio.c, devicemodel/include/gpio_dm.h
GPIO set/get value can be operated by accessing PIO space and the PIO
register definition for GPIO is in gpio_dm.h, frontend driver or ACPI
control methods can operate GPIO based on it.
GPIO mediator also defines ACPI control methods to support GPIO
operations, GPIO consumers can invoke PIO_GPIO_SET_VALUE/PIO_GPIO_GET_VALUE
in their own DSDT to set/get one GPIO value via ACPI control method.
v2: 1) Fix code style.
2) Use virtio configuration space callbacks to implement GPIO PIO operations
that replace pci_gpio_read/pci_gpio_write with virtio_cfgread/virtio_cfgwrite.
3) Return 0xFFFFFFFF as invalid result of PIO reading instead 0.
=> DM: virtio-gpio: implement GPIO operations by PIO

hypervisor/include/arch/x86/guest/vcpu.h
Add, update '@return' and '@retval' statements to the API descriptions related
to vCPU operations.
Tracked-On: #1844
=> doc: fix '@return' and '@retval' statements for vCPU ops

hypervisor/include/arch/x86/cpu.h
ACRN uses CONFIG_PARTITION_MODE  macro to compile out CPU_IRQ_ENABLE/DISABLE
APIs. With vector remapping enabled for pre-launched VMs, this is of no use.
And for VMs with LAPIC pass-thru, interrupts stay disabled in vmexit loop
with the help of is_lapic_pt() API.
Tracked-On: #2903
=> hv: Remove CONFIG_PARTITION_MODE used to compile out irq enable/disable

doc/developer-guides/coding_guidelines.rst
This patch updates the rules category in coding guidelines.
Move some rules in 'Statements' part to 'Expressions' part and
'Functions' part, which is more reasonable.
No functional change is involved.
=> doc: update rules category in coding guidelines

devicemodel/hw/pci/virtio/virtio_net.c, devicemodel/samples/apl-mrb/launch_uos.sh, devicemodel/samples/apl-up2/launch_uos.sh, devicemodel/vmcfg/apl-mrb/mrb-env-setup.sh, tools/acrnbridge/Makefile, tools/acrnbridge/acrn.network, tools/acrnbridge/tap0.netdev
Some projects based on ACRN don't want tap name to contain "acrn_"
prefix. This patch removes that prefix.
Tracked-On: #2509
=> dm: remove "acrn_" prefix from tap name

doc/tutorials/debug.rst
Update the "ACRN Debugging Tools" tutorial:
* Remove sections on how to build and install the hypervisor, refer to the
corresponding user guides instead
* Simplify the flow for checking loglevel (console and mem)
* Add a little text to improve readability
=> doc: update the "ACRN Debugging Tools" tutorial

doc/developer-guides/hld/virtio-net.rst, doc/getting-started/apl-nuc.rst, doc/tutorials/agl-vms.rst, doc/tutorials/launch_uos.sh, doc/tutorials/static-ip.rst, doc/tutorials/using_ubuntu_as_sos.rst
Update the documentation, and associated scripts to reflect the fact
that the TAP device used by 'acrn-dm' no longer use the "acrn_" prefix.
Tracked-On: #2509
=> doc: update documentation to the latest TAP name (no acrn_ prefix)

devicemodel/hw/pci/xhci.c, devicemodel/hw/platform/usb_pmapper.c, devicemodel/include/usb_core.h
The current xHCI mediator doesn't well support disable endpoint command.
This patch is one workaround for disable endpoint command to avoid
xHCI mediator to continue handle already dropped data.
Tracked-On: #2927
=> DM USB: xHCI: WA for an isochronous crash issue

devicemodel/hw/pci/passthrough.c
Add SDC ACPI device in dsdt, and assign GPIO 0 to SDC for SD card
detection.
Currently, the SD card hotplug function needs to insert SD card when
system boot, otherwise, it does not work. Since it needs P2SB virtualization
to set SD card presence state, and P2SB does not support user space interfaces
so this is an known issue.
=> dm: passthru: support SD hotplug

devicemodel/samples/apl-mrb/launch_uos.sh
For multiple guest os and particular audio features support domain id
and name is required.
Tracked-On: #2924
reviewed-by: Yu Wang <yu1.wang@intel.com>
reviewed-by: Yakui zhao <yakui.zhao@intel.com>
reviewed-by: Binbin Wu <binbin.wu@intel.com>
Signed-off-by: Marcin Pietraszko <marcin.pietraszko@intel.com>
=> Domain id and name added to launch_uos.sh

devicemodel/hw/pci/xhci.c, devicemodel/samples/apl-mrb/launch_uos.sh
This patch set fix two USB mediator stability issues.
Tracked-On: #2922
=> DM USB: fix two stability issues

hypervisor/arch/x86/guest/vlapic.c, hypervisor/dm/vmptable.c
For Pre-launched VMs, ACRN uses mptable for reporting APIC IDs to guest OS.
In current code, ACRN uses physical LAPIC IDs for vLAPIC IDs.
This patch is to let ACRN use vCPU id for vLAPIC IDs  and also report the same
when building mptable. ACRN should still use physical LAPIC IDs for SOS
because host ACPI tables are passthru to SOS.
Tracked-On: #2934
=> hv: Use virtual APIC IDs for Pre-launched VMs

devicemodel/hw/pci/xhci.c, devicemodel/hw/platform/usb_pmapper.c
The old logic to process control transfer failure only include two cases:
1 Short packet
2 Stall.
This patch includes all possible failures reported by Libusb and does
related emulation for UOS
Tracked-On: #2918
=> DM USB: xHCI: refine the failure process logic of control transfer

hypervisor/arch/x86/guest/vlapic.c, hypervisor/arch/x86/guest/vmsr.c, hypervisor/include/arch/x86/guest/vlapic.h
1) hv: vlapic: remove vlapic_rdmsr/wrmsr
We could call vlapic API directly, remove vlapic_rdmsr/wrmsr to make things easier.
2) hv: vlapic: minor fix about vlapic write
1) In x2apic mode, when read ICR, we want to read a 64-bits value.
2) In x2apic mode, write self-IPI will trap out through MSR write when VID isn't enabled.
=> Apicv: prepare for wrap apicv APIs

hypervisor/arch/x86/guest/vmcall.c, hypervisor/common/hypercall.c, hypervisor/include/common/hypercall.h, hypervisor/include/public/acrn_hv_defs.h
to wrap hypercalls that get platform information,
such as API version, physical CPU number.
Tracked-On: #2538
=> hv: add new hypercall to fetch platform configurations

tools/acrn-crashlog/acrnprobe/load_conf.c, tools/acrn-crashlog/common/fsutils.c
This patch is to fix some possible memory leak issues, which are
reported by static analysis tool.
1. free uptime in error case handling of function parse_uptime.
2. unmap f in error case handling of function _file_read_key_value.
Tracked-On: #2917
=> tools: acrn-crashlog: fix some possible memory leak

efi-stub/boot.c, efi-stub/boot.h, hypervisor/arch/x86/configs/nuc7i7bnh/pci_devices.h, hypervisor/arch/x86/configs/nuc7i7bnh/ve820.c, hypervisor/bsp/firmware_wrapper.c, hypervisor/bsp/include/firmware.h
Enable simple logical partition mode on KBL NUC i7, there are
two pre-launched VM with virtual LAPIC and multiboot compliant
boot loader (GRUB is one candidate) need to be used to boot
hypervisor and provides the address of guest OS image, this boot
loader only runs during boot time.So the following updates need to
be made:
(1) Update efi stub to support boot loader name in the its multiboot
header;
(2) Update firware detection and operations selecting logic to detect
more multiboot compiliant firware (such as GRUB and UEFI loader)
explicitly, different operations is selected according to the
boot load name through a static mapping table between boot load name
and firmware operations. GRUB loader can use the SBL operations
to handle multiboot information parsing and vm booting since
these …
=> Enable logic partition scenario on KBL NUC i7

Makefile, devicemodel/Makefile, devicemodel/core/main.c, devicemodel/hw/pci/wdt_i6300esb.c, devicemodel/include/vmmapi.h
the patches are used when UOS watchdog reset happens, DM will trigger a
warm reset first, let UOS gets a chance to dump system info for debug.
it is ported from apl_sdc_stable branch and  just used for debug build.
Wei Liu (1):
acrn-dm: enable debug option for acrn-dm
enable acrn-dm debug option via RELEASE=0(by default)
Tracked-On: #2939
Yin Fengwei (1):
watchdog: map the watchdog reset to warm reset
Per debugging requirement, map the watchdog reset to warm reset.
So the ramconsole could be used to capture the kernel log of UOS
before watchdog is hit.
Tracked-On: #2471
Acked-by: Yu Wang …
=>  DM: enable debug macro and remap watchdog reset

doc/developer-guides/hld/hv-vt-d.rst, hypervisor/arch/x86/guest/vm.c, hypervisor/arch/x86/vtd.c, hypervisor/common/hypercall.c, hypervisor/dm/vpci/vpci.c, hypervisor/dm/vpci/vpci_priv.h, hypervisor/include/arch/x86/vtd.h
In the presence of SOS, ACRN uses fallback_iommu_domain which is the same
used by SOS, to assign domain to devices during ACRN init. Also it uses
fallback_iommu_domain when DM requests ACRN to remove device from UOS domain.
This patch changes the design of assign/remove_iommu_device to avoid the
concept of fallback_iommu_domain and its setup. This way ACRN can commonly
treat pre-launched VMs bringup w.r.t. IOMMU domain creation.
Tracked-On: #2965
=> hv: Remove need for init_fallback_iommu_domain and fallback_iommu_domain

hypervisor/arch/x86/guest/vcpuid.c, hypervisor/arch/x86/guest/vmsr.c, hypervisor/include/arch/x86/guest/vcpu.h
Enable vMCE feature to boot windows guest.
vMCE is set in EDX from Microsoft TLFS spec, to support windows guest
vMCA and vMCE should be supported by guest CPUID.
Support MSR_IA32_MCG_CAP and MSR_IA32_MCG_STATUS reading when vMCE is enabled,
but they are not emulated yet, so return 0 directly.
=> hv: enable vMCE from guest CPUID

hypervisor/debug/dump.c
ACRN dumps host registers in case of an exception in root mode operation.
This patch adds CR2 register to the dump. It is useful for
page-fault debug in HV to know the offending address.
Tracked-On: #2969
=> hv: Add host CR2 to exception dump

devicemodel/include/public/vhm_ioctl_defs.h
Add interface to get hardware information and
configurations for current platform.
Tracked-On: #2538
=> dm: add IOCTL command to get platform information

README.rst
Add survivability plan for ACRN Open source project.
Tracked-On: #2945
=> doc: add security advisory section in ACRN introduction website

hypervisor/dm/io_req.c, hypervisor/dm/vioapic.c, hypervisor/dm/vpci/pci_pt.c, hypervisor/include/dm/io_req.h
in this patch(2b79c6df) move some common APIS to io_req.c
and rename common/io_irq.c to dm/io_req.c,
this api(register_mmio_emulation_handler) has been changed
before this patch, there is no conflict when rebasing
because of the movement and rename, this patch fix it.
=> hv:hotfix for register_mmio_emulation_handler

hypervisor/arch/x86/guest/virq.c, hypervisor/arch/x86/guest/vlapic.c, hypervisor/include/arch/x86/guest/vlapic.h
v5:
bug fix: set TPR threshold to 0 in tpr_below_threshold_vmexit_handler to
bypass VM-Execution Control Fields check.
v4:
back to the v1 implement since
The following check is performed if the “use TPR shadow” VM-execution control
is 1 and the “virtualize APIC accesses” and “virtual-interrupt delivery”
VM-execution controls are both 0: the value of bits 3:0 of the TPR
threshold VM-execution control field should not be greater than the value of
bits 7:4 of VTPR (see Section 29.1.1) according SDM Vol 3 26.2.1.1
VM-Execution Control Fields.
v3:
Simplify TPR threshold implement by setting TPR threshold to highest value (0xF)
to trap out the almost TPR settting.
v2:
add comments.
v1:
Add TPR below threshold implement for "Virtual-interrupt delivery" not support.
Windows will use it to delay …
=> hv: vlapic: add TPR below threshold implement

Makefile, devicemodel/Makefile, devicemodel/core/main.c, devicemodel/hw/pci/wdt_i6300esb.c, devicemodel/include/vmmapi.h
enable acrn-dm debug option via RELEASE=0(by default)
Tracked-on: #2939
=> acrn-dm: enable debug option for acrn-dm

hypervisor/arch/x86/guest/vcpu.c, hypervisor/debug/sbuf.c, hypervisor/include/debug/sbuf.h, hypervisor/release/sbuf.c
When shutting down SOS VM, the shared sbuf is released from guest OS, but
the per cpu sbuf pointers in hypervisor keep inact. This creates a problem
that after SOS is re-launched, hypervisor could write to the shared
buffer that no longer exists.
This patch implements sbuf_reset() and call it from reset_vcpu() to
reset sbuf pointers.
=> hv: reset per cpu sbuf pointers during vcpu reset

hypervisor/arch/x86/seed/seed_sbl.c
The 'boot_params' and 'entry' might be dereferenced after they were
positively checked for NULL. Refine checking logic to fix the issue.
Tracked-On: #2979
=> hv: seed: fix potential NULL pointer dereferencing

hypervisor/arch/x86/guest/vm.c, hypervisor/common/hypercall.c
If launch two UOS with same UUID by acrn-dm, current code path will
return same VM instance to the acrn-dm, this will crash the two UOS.
Check VM state and make sure it's in VM_STATE_INVALID state before
creating a VM.
Tracked-On: #2984
Signed-off-by: Cai Yulong <yulongc@hwtc.com.cn>
=> hv: check vm state before creating a VM

devicemodel/core/inout.c, devicemodel/core/mem.c, devicemodel/hw/pci/core.c, devicemodel/include/inout.h, devicemodel/include/mem.h
Following up on d648df766c263512c93356a55ff97cb3e23fe3e4, surgically remove all the functions related to enable_bar()/disable_bar() that got introduced in 8787b65fdee622639925ad75fe920913e0e7f102.
Also, make accesses to mmio_hint in mem.c thread-safe because it can potentially be accessed concurrently in emulate_mem().
Tracked-On: #2902
=> Completely remove enable_bar()/disable_bar() functions

hypervisor/arch/x86/guest/vm.c, hypervisor/common/hypercall.c, hypervisor/include/arch/x86/guest/vm.h
- The target vm in most of hypercalls should be a NORMAL_VM, in some
exceptions it might be a SOS_VM, we should validate them.
- Please be aware that some hypercall might have limitation on specific
target vm like RT or SAFETY VMs, this leaves "TODO" in future;
- Unify the coding style:
int32_t hcall_foo(vm, target_vm_id, ...)
{
int32_t ret = -1;
...
if ((is_valid_vm(target_vm) && is_normal_vm(target_vm)) {
ret = ....
}
return ret;
}
Tracked-On: #2978
=> HV: validate target vm in hypercall

hypervisor/arch/x86/Kconfig, hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/guest/vm.c, hypervisor/arch/x86/pm.c, hypervisor/common/hypercall.c, hypervisor/include/arch/x86/cpu.h, hypervisor/include/lib/errno.h, hypervisor/scenarios/logical_partition/vm_configurations.h, hypervisor/scenarios/sdc/vm_configurations.h
This patchset aims at fixing the following issues:
- There will be some DM set flags remained after shutdown the vm. This patchset fix it by clear
all DM set flags when shutdown the vm.
- Since lapic is passthroughed to guest, there may be wrong lapic state after lapic_pt vm shutdown.
For example, the lapic will disabled by linux guest when shutdown and we can't boot one normal
vm successfully in this situation. This patchset fix by reset all physical cores when shutdown
lapic_pt vm.
Tracked-On: #2991
=> Fix the bug about failing to boot normal vm on the pcpu which ever run lapic_pt vm

hypervisor/arch/x86/guest/instr_emul.c, hypervisor/arch/x86/guest/vmcs.c
1) Shouldn't try to set APIC-register virtualization if the physical doesn't
support APICV advanced mode.
2) Remove all APICv features VMCS setting when LAPIC is passed through to guest.
However, if emulated this in MRB board, the android can't boot because when switch to trusty world, 
it will check  "Delivery Status" in ICR first. It turns out that this Bit Test instruction is not emulated  
correctly.  This's because not every instruction supports the operand-size bit (w). This patch try to 
correct what done in commit-id 9df8790 by setting a flag VIE_OP_F_BYTE_OP to indicate which
instruction supports the operand-size bit (w).
=> Vlapic: minor fix about APICv feature setting

hypervisor/arch/x86/guest/vlapic.c
Possible buffer overflow will happen in vlapic_set_tmr()
and vlapic_update_ppr(),this path is to fix them.
=> hv: fix possible buffer overflow in vlapic.c

devicemodel/hw/pci/gvt.c
will access null pointer if 'gvt' is null.
Tracked-On: #1479
=> dm: fix possible null pointer dereference in pci_gvt_deinit

devicemodel/hw/pci/virtio/virtio_gpio.c, tools/acrn-manager/acrnctl.c
explicitly initialize the cmd_cap string array.
Tracked-On: #3001
=> Fix some potential overflow

doc/developer-guides/hld/hv-virt-interrupt.rst, hypervisor/arch/x86/cpu_caps.c, hypervisor/arch/x86/guest/virq.c, hypervisor/arch/x86/guest/vlapic.c, hypervisor/arch/x86/guest/vlapic_priv.h, hypervisor/arch/x86/guest/vmsr.c, hypervisor/include/arch/x86/guest/vlapic.h, hypervisor/include/arch/x86/msr.h
v1-v2:
1) rebase the code
v1:
ACRN will always requires to support basic APICv features ("Use TPR
shadow", "Virtualize APIC accesses"
and "Virtualize x2APIC mode"). If fully APICv features (besides the basic
features, plus "Virtual-interrupt delivery", "APIC-register virtualization" and
"Process posted interrupts") is supported, we enable fully APICv features
which names apicv advanced mode. Otherwise, we will draw back to apicv
basic mode which only enable basic APICv features.
Once the APICv features is detected in a platform, the APICv operation is
decided. We don't need to do the check on runtimes.
These patch tries to simplfy the code by (1) the default APICv operations is
used for APICV basic mode (2) once the APICv features are detected in the
platform when booting, the APICv …
=> hv: vlapic: add encapsulation APIs for APICv operation

hypervisor/arch/x86/guest/virq.c
the problem is : System will crash when run crashme.
The root cause of this problem is that when the ACRN_REQUEST_EXCP flag is set by calling
the vcpu_make_request function, the flag is not cleared.
Add the following statement to the vcpu_inject_exception function to fix the problem:
bitmap_test_and_clear_lock(ACRN_REQUEST_EXCP, &vcpu->arch.pending_req);
Tested that one night, there was no crash.
Tracked-On: #2527
Signed-off-by: bing.li<bingx.li@intel.com>
Acked-by:      Eddie Dong<eddie.dong@intel.com>
=> HV: fix the issue of ACRN_REQUEST_EXCP flag is not cleared.

hypervisor/arch/x86/pm.c
This patch just removes unnecessary indent before #include in pm.c.
Tracked-On: #2991
=> HV: Remove unnecssary indent in pm.c

hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/pm.c, hypervisor/include/arch/x86/cpu.h
It is better to use an unified MACRO. So, this patch moves AP_MASK to cpu.h
and removes the defination of the MACRO spanning different source files.
Tracked-On: #2991
=> HV: move AP_MASK to cpu.h

hypervisor/arch/x86/guest/assign.c, hypervisor/arch/x86/guest/vlapic.c, hypervisor/common/hypercall.c, hypervisor/include/arch/x86/guest/vlapic.h
According to SDM 10.6.1, if dest fields is 0xffU for register
ICR operation, that means the IPI is for broadcast.
According to SDM 10.12.9, 0xffffffffU of dest fields for x2APIC
means IPI is for broadcast.
We add new parameter to vlapic_calc_dest() to show whether the
dest is for broadcast. For IPI, we will set it according to
dest fields. For ioapic and MSI, we hardcode it to false because
no broadcast for ioapic and MSI.
Tracked-On: #3003
=> vlapic: refine IPI broadcast to support x2APIC mode

hypervisor/arch/x86/guest/vm.c, hypervisor/scenarios/logical_partition/vm_configurations.c
The guest flags of GUEST_FLAG_IO_COMPLETION_POLLING work for NORMAL_VM only;
=> HV: correct usage of GUEST_FLAG_IO_COMPLETION_POLLING

tools/acrn-crashlog/acrnprobe/main.c
Meet compiling error:
In function ‘strncpy’,
inlined from ‘main’ at main.c:88:4:
/usr/include/bits/string_fortified.h:106:10: error: ‘__builtin_strncpy’
specified bound 4096 equals destination size
[-Werror=stringop-truncation]
106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos
(__dest));
|
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
This patch aims to fix it.
=> tools:acrn-crashlog: fix the compiling error

devicemodel/hw/pci/gvt.c
When the "i915.enable_gvt=0" is added for SOS kernel boot args, ACRN-DM will
fail in course of gvt initialization and errno is returned directly.
As the errno defined in linux/errno.h is positive, it will continue
the unexpected initialization in ACRN-DM and then the segment fault is
triggered.
So negative errno is returned in order to terminate the initialization.
Tracked-On: #2584
=> acrn/dm: gvt returns negative errno to terminate the initialization

devicemodel/hw/pci/virtio/virtio_gpio.c
When UOS set failling irq type, gpio BE will only request GPIOEVENT_REQUEST_FAILLING_EDGE
event from native gpio driver which will cause the last_level value is always 0.
So last_level can't be used to check whether interrupt should be injected or not.
It is the same for rising irq type.
v2: refine commit message.
Tracked-On: #3010
Signed-off-by: fuyongjie <fuyongjie@neusoft.com>
=> DM: virtio-gpio: fix falling or rising irq can't work

devicemodel/Makefile, tools/acrn-manager/Makefile
With latest gcc, there are build error with current ACRN code.
Fixing could involve many code changes. We use gcc option to
remove build error as temperary workaround. And will fix the
build error one by one.
Tracked-On: #3010
=> Makefile: add gcc option to workaround build issue with latest gcc

hypervisor/arch/x86/guest/vm.c, hypervisor/common/vm_load.c
There are 2 reasons why SOS ve820 has to be separated from host e820:
- in hybrid mode, SOS may not own all the host memory.
- when SOS is being re-launched, it needs an untainted version of host
e820 to create SOS ve820.
This patch creates sos_e820 table for SOS and keeps host e820 intact
during SOS creation.
=> hv: separate host e820 and SOS ve820

hypervisor/arch/x86/guest/vm.c, hypervisor/arch/x86/guest/vmcall.c, hypervisor/debug/vuart.c
If the vmcall param passed from guest is representing a vmid, we should
make sure it is a valid one because it is a pre-condition of following
get_vm_from_vmid(). And then we don't need to do NULL VM pointer check
in is_valid_vm() because get_vm_from_vmid() would never return NULL.
Tracked-On: #2978
=> HV: check vm id param when dispatching hypercall

hypervisor/arch/x86/configs/apl-mrb/pci_devices.h, hypervisor/arch/x86/configs/dnv-cb2/pci_devices.h, hypervisor/arch/x86/configs/nuc7i7bnh/pci_devices.h, hypervisor/scenarios/logical_partition/pt_dev.c, hypervisor/scenarios/logical_partition/vm_configurations.h
- The pci device config is related to VM configurations, so move the device
mapping MACROs from pci_devices.h to vm_configurations.h. Also considering
pci_devices.h should be generated by offline parse tool, this code change
would decouple the relationship between VM configuration tool and target
paser tool;
- Another minor change is add post-fix in number for each PCI device subclass
name to make target parse tool interface friendly;
=> HV: minor changes on pci devices config

devicemodel/hw/pci/virtio/virtio_gpio.c
When vm reset,the gpio line state is busy if we don't close the fd.
Tracked-On: #3028
Signed-off-by: fuyongjie <fuyongjie@vip.qq.com>
=> DM: virtio-gpio: close gpio line fd

hypervisor/Makefile, hypervisor/arch/x86/Kconfig, hypervisor/scenarios/industry/vm_configurations.c, hypervisor/scenarios/industry/vm_configurations.h
This scenario is typical for industry usage with 3 VMs: 1 pre-launched SOS VM,
1 post-launched user VM for HMI and 1 post-launched  RT VM for real-time control.
Tracked-On: #3039
=> hv: add scenario for the industry use case

devicemodel/core/vmmapi.c, devicemodel/hw/pci/passthrough.c, devicemodel/include/vmmapi.h, hypervisor/common/hypercall.c, hypervisor/dm/vpci/vpci.c, hypervisor/dm/vpci/vpci_priv.h
PCI resources
1) IOMMU domain switch
2) Relese UOS MSI host IRQ/IRTE
3) Update vdev info in SOS vdev
Cleanup mentioned above is  taken care when DM releases UOS resources
during a UOS reboot or shutdown
In the following cases, where DM does not get chance to cleanup
1) DM crash/segfault
2) SOS triple fault/hang
3) SOS reboot before shutting down POST_LAUNCHED_VMs
ACRN must cleanup to make sure vpci data structures represent
transition of PT device back to SOS.
=> vPCI resource cleanup for POST_LAUNCHED_VMs

tools/acrn-crashlog/acrnprobe/Makefile, tools/acrn-crashlog/acrnprobe/android_events.c, tools/acrn-crashlog/acrnprobe/channels.c, tools/acrn-crashlog/acrnprobe/crash_reclassify.c, tools/acrn-crashlog/acrnprobe/event_handler.c, tools/acrn-crashlog/acrnprobe/event_queue.c, tools/acrn-crashlog/acrnprobe/include/android_events.h, tools/acrn-crashlog/acrnprobe/include/event_queue.h, tools/acrn-crashlog/acrnprobe/include/load_conf.h, tools/acrn-crashlog/acrnprobe/include/probeutils.h, tools/acrn-crashlog/acrnprobe/include/vmrecord.h, tools/acrn-crashlog/acrnprobe/load_conf.c, tools/acrn-crashlog/acrnprobe/probeutils.c, tools/acrn-crashlog/acrnprobe/sender.c, tools/acrn-crashlog/acrnprobe/vmrecord.c, tools/acrn-crashlog/common/fsutils.c, tools/acrn-crashlog/common/include/fsutils.h, tools/acrn-crashlog/common/include/strutils.h, tools/acrn-crashlog/common/strutils.c, tools/acrn-crashlog/data/acrnprobe.xml
This patch set aims to refine the IO operation on the eMMC.
Check a folder's size need to traverse all nodes of files and subdirs,
in the case of extreme memory strain, accessing these log file nodes
frequently will highly increase the pressure of io operation.
Previously, all log files will be accessed and counted in each space
check, this patch aims to refine it by only calculating the increment of new
logs.
In order to achieve this purpose, acrnprobe must maintain one variate to
record the total size of all logs, and modify it after each time
log changed. To avoid the using of lock, the access of this variate must
be single-threaded.
So, firstly, these serial patches unify the handling process of each kind
of events to:
analyze events - request resources -  collect logs - record …
=>  tools: acrn-crashlog: refine IO operation

doc/developer-guides/c_coding_guidelines.rst
This patch renames rules ID to reflect the language, in order
to support multiple programming languages.
=> doc: rename rules ID in C coding guidelines

doc/developer-guides/hld/hv-partitionmode.rst, doc/tutorials/debug.rst, doc/tutorials/using_partition_mode_on_up2.rst, doc/user-guides/acrn-shell.rst
Change shell command 'sos_console' to 'vm_console' as it is not only
used to switch console to SOS.
=> DOC: change hv shell cmd sos_console to vm_console

doc/getting-started/building-from-source.rst
Update the instructions on how to build ACRN on Ubuntu 16.04,
specifically:
* Add 'pkg-config' package
* Upgrade 'binutils' to 2.27
Note: there is still an issue with regards to the GPIO header
(linux/gpio.h) which needs to be resolved.
Tracked-On: #2737
=> doc: update instructions for building ACRN on Ubuntu 16.04

hypervisor/scenarios/industry/vm_configurations.c, hypervisor/scenarios/sdc/vm_configurations.c
As commit info of 2362e58509484fd7f6d54b42f224a73a53eb6374, the guest flags
of GUEST_FLAG_IO_COMPLETION_POLLING work for POST_LAUNCHED_VM only, this
patch fix the wrong setting in SOS_VM;
=> HV: correct GUEST_FLAG_IO_COMPLETION_POLLING in SOS

hypervisor/arch/x86/guest/ept.c, hypervisor/arch/x86/seed/seed_sbl.c, hypervisor/common/hypercall.c, hypervisor/debug/profiling.c, hypervisor/include/arch/x86/cpu.h
Shared buffer is allocated by VM and is protected by SMAP.
Accessing to shared buffer between stac/clac pair will invalidate
SMAP protection.This patch is to remove these cases.
Fix minor stac/clac mis-usage,and add comments as stac/clac usage BKM
Tracked-On: #2526
=> hv:remove accessing shared log buffer cases between stac/clac

doc/developer-guides/hld/hv-interrupt.rst, hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/irq.c, hypervisor/include/arch/x86/irq.h
This patch renames 'interrupt_init' to 'init_interrupt'.
=> hv: rename 'interrupt_init' to 'init_interrupt'

hypervisor/arch/x86/guest/vmx_io.c, hypervisor/dm/io_req.c, hypervisor/include/arch/x86/guest/vmx_io.h, hypervisor/include/dm/io_req.h
Rename 'type' in struct io_request to 'io_type' to be more readable.
Tracked-On: #3061
=> HV: rename 'type' in struct io_request

hypervisor/arch/x86/guest/assign.c, hypervisor/arch/x86/guest/vm.c, hypervisor/common/ptdev.c, hypervisor/include/common/ptdev.h
IRTE is freed if ptirq entry is released from remove_msix_remapping() or
remove_intx_remapping(). But if it's called from ptdev_release_all_entries(),
e.g. SOS shutdown/reboot, IRTE is not freed.
This patch adds a release_cb() callback function to do any architectural
specific cleanup. In x86, it's used to release IRTE.
On VM shutdown, vpci_cleanup() needs to remove MSI/MSI-X remapping on
ptirq entries, thus it should be called before ptdev_release_all_entries().
=> hv: release IOMMU irte when releasing ptirq remapping entries

doc/developer-guides/hld/hld-devicemodel.rst, doc/developer-guides/hld/hv-ioc-virt.rst, doc/introduction/index.rst
Correct spelling of the trademarked name is Wi-Fi
=> doc: Fix references to be Wi-Fi

devicemodel/core/monitor.c, devicemodel/hw/pci/core.c, devicemodel/hw/pci/virtio/virtio_block.c, devicemodel/include/monitor.h, devicemodel/include/pci_core.h, doc/developer-guides/primer.rst, tools/acrn-manager/README.rst, tools/acrn-manager/acrn_mngr.h, tools/acrn-manager/acrn_vm_ops.c, tools/acrn-manager/acrnctl.c, tools/acrn-manager/acrnctl.h
The following patches adds rescan support for virtio-blk device.
This feature stems from the kata container requirement, which hot-plugs container rootfs to the guest VM. 
1. Tools patch adds a new acrnctl command called "blkrescan" to 
initiate rescan of virtio-blk device.
2. DM patch updates the virtio-blk device launched with 
dummy backend file with correct backend file, size
and triggers the guest OS to revalidate the disk resulting
in adding blk device to guest VM.
=> virtio-blk rescan feature

hypervisor/arch/x86/Kconfig, hypervisor/arch/x86/configs/apl-mrb/platform_acpi_info.h, hypervisor/arch/x86/guest/pm.c, hypervisor/arch/x86/pm.c, hypervisor/boot/acpi.c, hypervisor/boot/include/acpi.h, hypervisor/bsp/firmware_wrapper.c, hypervisor/bsp/include/firmware.h, hypervisor/include/arch/x86/host_pm.h, hypervisor/scenarios/logical_partition/vm_configurations.h
Previously ACPI PM1A register info was hardcoded to 0 in HV for generic boards, but SOS still can know the real PM1A info so the system would hang if user trigger S3 in SOS. Enabling PM1A register info fixup will let HV be able to intercept the operation on PM1A and then make basic function of S3 work for
all boards;
Also, the MACRO of CONFIG_CONSTANT_ACPI will be defined per scenario usage, so move it from Kconfig to vm_configurations.h;
=> HV: enable acpi pm1a register info fixup

hypervisor/boot/acpi.c
In commit b68aee6ef1d8217f592df0cdd3446618d5a770f9, acpi.c
removed "hypervisor.h" which includes "acrn_common.h", but
commit e2d723d4fa914071fa99c801c7e3ef93ab7ec269 is depend on
"acrn_common.h", this caused build error
Tracked-On: #3073
=> HV: hotfix for acpi.c compile error

doc/getting-started/apl-nuc.rst
APL NUC Getting started guide has some obsolete information (such as
saying the user had to build ACRN as part of the installation process
and changed instructions because the Clear Linux installer changed),
along with some spelling and grammar issues.
=> doc: update APL NUC GSG

hypervisor/dm/vpci/vhostbridge.c, hypervisor/dm/vpci/vpci.c, hypervisor/dm/vpci/vpci_priv.h
Rename hostbridge related functions
vdev_hostbridge_init --> vhostbridge_init
vdev_hostbridge_cfgread --> vhostbridge_cfgread
vdev_hostbridge_cfgwrite --> vhostbridge_cfgwrite
vdev_hostbridge_deinit --> vhostbridge_deinit
Replace partition mode with pre-launched VM in comments
Tracked-On: #3056
=> VPCI code function renaming and fix comment

hypervisor/arch/x86/configs/vm_config.c, hypervisor/arch/x86/pm.c, hypervisor/include/arch/x86/guest/vcpu.h, hypervisor/include/arch/x86/guest/vm.h, hypervisor/scenarios/industry/vm_configurations.c, hypervisor/scenarios/logical_partition/vm_configurations.c, hypervisor/scenarios/sdc/vm_configurations.c
vm_config.h has included types.h/acrn_common.h/vm_configurations.h,
acrn_common.h has included types.h, so remove the redundant includes;
=> HV: remove some redundant includes

hypervisor/arch/x86/guest/vm.c, hypervisor/common/hypercall.c, hypervisor/debug/console.c, hypervisor/debug/profiling.c, hypervisor/debug/shell.c, hypervisor/include/arch/x86/guest/vm.h
Replace the vm state VM_STATE_INVALID to VM_POWERED_OFF.
Also replace is_valid_vm() with is_poweroff_vm().
Add API is_created_vm() to identify VM created state.
Tracked-On: #3082
=> vm_state: Update vm state VM_STATE_INVALID to VM_POWERED_OFF

tools/acrnlog/README.rst
This commit updates the usage of "loglevel" command in README.rst, which was
out-of-date due to change of "loglevel" command.
Tracked-On: #2712
=> doc: acrnlog: update loglevel usage

doc/developer-guides/c_coding_guidelines.rst
This patch adds rules in C coding guidelines for function
naming convention.
=> doc: add rules in C coding guidelines

doc/developer-guides/hld/virtio-blk.rst
Add the description of option 'b' to indicate the boot device including
the bootable image.
Tracked-On: #1917
=> Doc: virtio-blk: add description of boot device option

.travis-dockerfiles/Dockerfile.ubuntu16.04
Update the Ubuntu 16.04 Dockerfile to add some missing dependencies and
updates, specifically:
* Need binutils 2.27 (or higher)
* Need pkg-config
* Need GPIO header file [1]
[1] Note that the current instructions for adding the GPIO header file
(linux/gpio.h) are still incomplete and compilation will fail.
Tracked-On: #2737
=> Dockerfile: update Ubuntu 16.04 Dockerfile to include all deps

tools/acrn-manager/acrn_vm_ops.c
With latest gcc version 9.1.1 20190506 from Clear Linux, we hit
following build issue in blkrescan code:
In function ‘strncpy’,
inlined from ‘blkrescan_vm’ at acrn_vm_ops.c:468:2:
/usr/include/bits/string_fortified.h:106:10: error: \
‘__builtin___strncpy_chk’ specified bound depends on the length \
of the source argument [-Werror=stringop-overflow=]
When calling strncpy, the size n should be set to max dest size
instead of src size.
Tracked-On: #3096
=> build fix: fix build issue with latest gcc for blkrescan

hypervisor/arch/x86/guest/instr_emul.c
There're some instructions which not support bit 0(w bit) flag but which
memory opcode size is fixed and the memory opcode size is not equal to the
register opcode size. In our code, there is movzx (which opcode is 0F B7)
which memory opcode size is fixed to 16 bits. So add a flag VIE_OP_F_WORD_OP
to indicate a instruction which memory opcode size is fixed to 16 bits.
Tracked-On: #1337
=> hv: instr_emul: fix movzx return memory opsize wrong

devicemodel/samples/apl-mrb/launch_uos.sh, devicemodel/samples/apl-up2/launch_uos.sh, devicemodel/samples/nuc/launch_uos.sh, devicemodel/samples/nuc/launch_vxworks.sh, devicemodel/samples/nuc/launch_zephyr.sh
for vm_name  with vxworks_vm1  or zephyr_vm1 or vm1
grep "vm1" will match three of them, add -w option fix this issue
Tracked-On:#3081
Signed-off-by: zhangyun <yunx.zhang@intel.com>
=> dm:add grep -w option for uos launch sh

hypervisor/arch/x86/guest/vlapic.c, hypervisor/arch/x86/guest/vm.c
v2-v3:
back to v1. Conghui will take care of the vioapic/vpic initialization.
v1-v2:
Add fix about vioapic and vpic initialization when create a VM. For prelaunched VM
and postlaunched RT VM, we don't support ioapic and pic, so we don't need to do
vioapic and vpic initialization when create a VM.
v1:
1. Windows will call OVMF to report guest memory size in nvram cells through RTC ioport.
However, the vRTC emulated in hypervisor doesn't provide this feature. It's only used for
pre-launched VM. For the post-launched VM, we need the DM to emulate the vRTC for us.
2. The previous implement of TPR virtualization has two bugs: a) we need to retain the RIP
b) we need to update the PPR before finding a deliverable interrupt. …
=> bug fix to boot waag

hypervisor/boot/guest/vboot_wrapper.c, hypervisor/boot/include/acpi.h
The acpi_fixup() is only called when CONFIG_ACPI_PARSE_ENABLED is enabled;
Tracked-On: #3107
=> HV: hot fix on usage of CONFIG_ACPI_PARSE_ENABLED

hypervisor/include/arch/x86/host_pm.h
The header need struct pm_s_state_data info which declared in acrn_common.h;
=> HV: fix MISRA violation of host_pm.h

devicemodel/hw/pci/virtio/virtio_gpio.c
virtio_gpio_ops variable type is static,so use "+=" will let
the value keep increasing when acrn-dm reset.
Tracked-On: #3118
Signed-off-by: fuyongjie <fuyongjie@neusoft.com>
=> DM: virtio-gpio: fixed static variable keeps increasing issue

devicemodel/core/main.c, devicemodel/hw/pci/wdt_i6300esb.c, devicemodel/include/vmmapi.h
Map SIGINT(2) to watchdog reset.
NOTE:
We required guest to do a full reset after detect the recent last
reset type is watchdog. This is used to resume the passthru devices
in UOS.
Tracked-On: #3103
=> signal SIGINT: map SIGINT to watchdog reset

hypervisor/acpi_parser/acpi_ext.c, hypervisor/acpi_parser/dmar_parse.c, hypervisor/boot/acpi_base.c, hypervisor/boot/guest/direct_boot_info.c, hypervisor/include/arch/x86/per_cpu.h
remove some unnecessary includes,
some can cause reverse dependency.
modified:   acpi_parser/acpi_ext.c
modified:   acpi_parser/dmar_parse.c
modified:   boot/acpi_base.c
modified:   boot/guest/direct_boot_info.c
modified:   include/arch/x86/per_cpu.h
=> hv:remove some unnecessary includes

devicemodel/samples/apl-mrb/launch_uos.sh, devicemodel/samples/apl-up2/launch_uos.sh, devicemodel/samples/nuc/launch_hard_rt_vm.sh
As vm config tool will override the passthrough devices if run on
different hw, and it will take a lot of work to search and
replace the passthrough device.
This patch refine the passthrough devices that tools to overwrite.
Tracked-On: #3127
=> dm: refine the passthrough devices with dictionary

hypervisor/common/vm_load.c
The definition of CONFIG_REMAIN_1G_PAGES has been removed by patch (4627cd4d HV: build: drop useless files).
So, remove the whole CONFIG_REMAIN_1G_PAGES in repo.
---
v1 -> v2:
Address Fei's comment about changing reserving_1g_pages from int32_t to int64_t
Address Jason's comment about adding MACRO NUM_REMAIN_1G_PAGES
Tracked-On: #3128
=> HV: Remove undefined CONFIG_REMAIN_1G_PAGES

hypervisor/dm/vpci/pci_pt.c, hypervisor/dm/vpci/vdev.c, hypervisor/dm/vpci/vhostbridge.c, hypervisor/dm/vpci/vmsi.c, hypervisor/dm/vpci/vmsix.c, hypervisor/dm/vpci/vpci.c, hypervisor/dm/vpci/vpci_priv.h, hypervisor/include/hw/pci.h
There is no more “partition_mode” or “sharing_mode” concept so any names or strings of these should be removed. We only has pre-launched VM, SOS, post-launched_vm.
Changed partition_mode to prelaunched_vm, change sharing_mode to sos_vm, and unified the code by combing the functions if possible.
Renamed a few functions based on c coding guideline
Some misra-c fixes
Tracked-On: #3056
=> Remove sharing_mode/partition_mode from vpci code

hypervisor/arch/x86/cpu_caps.c, hypervisor/lib/sprintf.c
1. Fix cpu family calc,  according to SDM documentation:     
Extended Family ID bit[20-27],      Family ID bit[8-11].
2. Modifie the parameter 'fl' order .
Tracked-On:https://github.com/projectacrn/acrn-hypervisor/issues/3142
Signed-off-by: Qiang Liu cdliuqiang@gmail.com
=> fix cpu family calculation

hypervisor/dm/vpci/pci_pt.c, hypervisor/dm/vpci/vpci.c, hypervisor/include/arch/x86/vm_config.h, hypervisor/include/dm/vpci.h, hypervisor/scenarios/logical_partition/pt_dev.c
HV: predefine pci vbar's base address for pre-launched VMs in vm_config
For pre-launched VMs, currently we set all vbars to 0s initially in
bar emulation code, guest OS will reprogram the bars when it sees the bars are uninited (0s).
We consider this is not the right solution, change to populate the
vbars (to non zero valid pci hole address) based on the vbar base
addresses predefined in vm_config.
HV: rename vdev_pt_cfgwrite_bar to vdev_pt_write_vbar and some misra-c fix
Tracked-On: #3022
=>  HV: predefine pci vbar's base address for pre-launched VMs in vm_config

hypervisor/arch/x86/configs/vm_config.c, hypervisor/include/arch/x86/vm_config.h
The enum of UNDEFINED_VM has never been used, remove it;
=> HV: remove unused UNDEFINED_VM

doc/developer-guides/hld/hv-memmgt.rst, doc/developer-guides/hld/hv-virt-interrupt.rst, hypervisor/arch/x86/guest/guest_memory.c, hypervisor/arch/x86/guest/vcpu.c, hypervisor/arch/x86/guest/virq.c, hypervisor/arch/x86/guest/vm.c, hypervisor/arch/x86/vtd.c, hypervisor/debug/sbuf.c, hypervisor/debug/uart16550.c, hypervisor/include/arch/x86/guest/guest_memory.h, hypervisor/include/arch/x86/guest/vcpu.h, hypervisor/include/arch/x86/guest/vm.h, hypervisor/include/arch/x86/irq.h, hypervisor/include/arch/x86/vtd.h, hypervisor/include/debug/uart16550.h, hypervisor/release/console.c
v2->v3
Keep get_sos_boot_mode. It will be used by init_vm_boot_info.
v1->v2
Address review comments. Keep ticks_to_ms, TRACE_6C, vuart_deinit and vuart_deinit_connect for future use.
yliu79 (7):
HV: remove unused function disable_iommu
HV: remove unused function shutdown_vcpu
HV: remove unused function resume_vm
HV: remove unused function copy_to_gva
HV: remove unused function vcpu_inject_ac
HV: remove unused function sbuf_is_empty and sbuf_get
HV: remove unused function is_dbg_uart_enabled
hypervisor/arch/x86/guest/guest_memory.c         |  6 -----
hypervisor/arch/x86/guest/vcpu.c                 |  7 ------
hypervisor/arch/x86/guest/virq.c                 |  6 -----
hypervisor/arch/x86/guest/vm.c                   | 15 ------------
hypervisor/arch/x86/vtd.c                        |  5 …
=> Remove some unused functions in hypervisor

doc/user-guides/acrn-shell.rst
Add the <vm_id> parameter to the documentation for the ACRN shell
"vm_console" command.
=> doc: add <vm_id> parameter to the "vm_console" command description

doc/user-guides/acrn-dm-parameters.rst
Using vSBL is only supported on Apollo Lake (APL) platforms at the
present. It cannot be used on other platforms supported by ACRN such as
KBL. Make this explicit with an additional note in the documentation.
Tracked-On: #2798
=> doc: add note to indicate that vSBL is only supported on APL platforms

doc/developer-guides/hld/hv-interrupt.rst, doc/developer-guides/hld/hv-memmgt.rst, doc/developer-guides/hld/hv-virt-interrupt.rst, hypervisor/include/arch/x86/guest/vcpu.h, hypervisor/include/arch/x86/ioapic.h, hypervisor/include/arch/x86/irq.h, hypervisor/include/arch/x86/lapic.h, hypervisor/include/arch/x86/pgtable.h
This patch removes hard-coded interfaces in .rst files and
refers to the definition via doxygen style comments.
This patch mainly focus on Hypervisor part.
Other parts will be covered in seperate patches.
=> doc: remove hard-coded interfaces in .rst files

doc/.known-issues/doc/dupdecl.conf, doc/extensions/kerneldoc.py
Sphinx 2.0 reports some "expected errors" differently, so add the new
message patterns to our known-errors scanning.
Also, the kerneldoc tool has a problem with sphinx 2.0, but a fix was
available.
=> doc: prepare for sphinx 2.0 upgrade

hypervisor/arch/x86/guest/assign.c, hypervisor/arch/x86/guest/vcpu.c, hypervisor/arch/x86/guest/vcpuid.c, hypervisor/arch/x86/guest/vlapic.c, hypervisor/arch/x86/guest/vm.c, hypervisor/arch/x86/guest/vmcs.c, hypervisor/common/hv_main.c, hypervisor/common/hypercall.c, hypervisor/include/arch/x86/guest/vlapic.h, hypervisor/include/arch/x86/guest/vm.h
ACRN supports LAPIC emulation for guests using x86 APICv. When guest OS/BIOS
switches from xAPIC to x2APIC mode of operation, ACRN also supports switching
froom LAPIC emulation to LAPIC passthrough to guest. User/developer needs to
configure GUEST_FLAG_LAPIC_PASSTHROUGH for guest_flags in the corresponding
VM's config for ACRN to enable LAPIC passthrough.
This patch does the following
1)Fixes a bug in the abovementioned feature. For a guest that is
configured with GUEST_FLAG_LAPIC_PASSTHROUGH, during the time period guest is
using xAPIC mode of LAPIC,  virtual interrupts are not delivered. This can be
manifested as guest hang when it does not receive virtual timer interrupts.
2)ACRN exposes physical topology via CPUID leaf 0xb to LAPIC PT VMs. This patch
removes that condition and exposes …
=> hv: distinguish between LAPIC_PASSTHROUGH configured vs enabled

hypervisor/arch/x86/configs/vm_config.c, hypervisor/dm/vpci/pci_pt.c, hypervisor/dm/vpci/vpci.c, hypervisor/hw/pci.c, hypervisor/include/hw/pci.h
Some minor VPCI code cleanup:
- Remove function pci_pdev_foreach() per discussion with Eddie
- Call function is_prelaunched_vm() instead to reduce code
Tracked-On: #3056
=>  Some minor VPCI code cleanup

devicemodel/samples/nuc/launch_hard_rt_vm.sh
Hostbridge is necessary for passing kernel pci subsystem initialization
sanity check which is located in pci_sanity_check(). It will check
whether a host bridge exists.
BTW, set rtvm flag explicitly.
Tracked-On: #3152
=> DM: add virtual hostbridge in launch script for RTVM

hypervisor/arch/x86/guest/vm.c, hypervisor/arch/x86/guest/vm_reset.c, hypervisor/include/arch/x86/guest/vm.h, hypervisor/include/public/acrn_common.h, hypervisor/scenarios/industry/vm_configurations.c, hypervisor/scenarios/sdc/vm_configurations.c
- add the GUEST_FLAG_HIGHEST_SEVERITY flag to indicate that the guest has
privilege to reboot the host system.
- this flag is statically assigned to guest(s) in vm_configurations.c in
different scenarios.
- implement reset_host() function to reset the host. First try the ACPI
reset register if available, then try the 0xcf9 PIO.
Tracked-On: #3145
=> hv: initial host reset implementation

tools/acrn-crashlog/acrnprobe/event_handler.c
Make sure vm event is not NULL before freeing vm_msg.
Reviewed-by: Liu, Xiaojing <xiaojing.liu@intel.com>
=> tools:acrn-crashlog: fix potential memory corruption

hypervisor/arch/x86/guest/vm.c
filter out pre_launched vm memory from e820 table
and unmap pre_launched vm memory from ept table
before boot service OS
Tracked-On: #3148
=> hv:not allow SOS to access pre_launched vm memory

devicemodel/hw/pci/xhci.c
Provide a minor fix for following issue:
Emulated USB controller Vendor ID and Device ID are swapped.
Tracked-On: #3053
Reviewed-by: Xu, Anthony <anthony.xu@intel.com>
=> DM: Fix minor issue of USB vendor ID

hypervisor/arch/x86/guest/vmsr.c, hypervisor/include/arch/x86/guest/vcpu.h, hypervisor/include/arch/x86/guest/vm.h, hypervisor/include/arch/x86/msr.h
At the time the guest is switching to X2APIC mode, different VCPUs in the
same VM could expect the setting of the per VM msr_bitmap differently,
which could cause problems.
Considering different approaches to address this issue:
1) only guest BSP can update msr_bitmap when switching to X2APIC.
2) carefully re-write the update_msr_bitmap_x2apic_xxx() functions to
make sure any bit in the bitmap won't be toggled by the VCPUs.
3) make msr_bitmap as per VCPU.
We chose option 3) because it's simple and clean, though it takes more
memory than other options.
BTW, need to remove const modifier from update_msr_bitmap_x2apic_xxx()
functions to get it compiled.
Tracked-On: #3166
Acked-by: …
=> hv: move msr_bitmap from acrn_vm to acrn_vcpu_arch

hypervisor/arch/x86/guest/vm.c
In current code, vpci do the pci enumartion and add pci devices to the
context table of iommu.
Need to enable iommu DMA address translation later than vpci init.
Otherwise, in UEFI platform, there will be a shot time that address translation
is enabled, but the context table is not setup.
For the devices active in UEFI environment will have problem on address translation.
Tracked-On: #3160
=> hv: vm: enable iommu after vpci init

devicemodel/hw/pci/xhci.c, devicemodel/include/xhcireg.h
This patchset enable the USB mediator mode for USB xHCI. Currently, USB mouse,
USB keyboard, USB disk and USB hub could work as expected on Windows 10.
Tracked-On: #3163
=> Enable USB xHCI mediator mode on WaaG

devicemodel/Makefile
1. debug/release: Enable enable -g option for debug build
-g option should only be enabled for debug build and disabled
for release build.
Tracked-On: #3164 
=> debug/release: Enable enable -g option for debug build

hypervisor/arch/x86/configs/vm_config.c, hypervisor/dm/vmptable.c, hypervisor/include/arch/x86/vm_config.h, hypervisor/scenarios/logical_partition/vm_configurations.c
Define a static mptable array and each VM could index its vmptable by
vm id, then mptable is not needed in vm configurations;
=> HV: remove mptable in vm_config

hypervisor/arch/x86/vtd.c
Fix a logic error when set iommu page walk coherent.
Tracked-On: #3160 
=> hv: vtd: fix a logic error when set iommu page walk coherent

hypervisor/arch/x86/guest/vm.c
When we call reset_vm() function to reset vm, the vm state
should be reset to VM_CREATED as well.
Tracked-On: #3182
=> vm state: reset vm state to VM_CREATED when reset_vm is called

hypervisor/arch/x86/guest/vlapic.c
Since the vapic_id is from VM, need to check for pre-condition before passing
vcpu_id to vcpu_from_vid. This is in the path of LAPIC passthrough ICR
access
Tracked-On: #3170
=> hv: Precondition checks for vcpu_from_vid

hypervisor/arch/x86/guest/virtual_cr.c
v2:
1) make the patch more readable: only add the bits which want to trap for FuSa.
2) still trap the bit which is 0 in IA32_VMX_CR4_FIXED1 (except the reserved bits).
3) don't touch CR4.MCE which need to trap when the guest wants to hide this capability.
v1:
We set CR4 guest/host mask to trap "MOV to CR4" for three reasons:
1) We need to make extra effort besides setting CR4:
a) invalidate the TLB (CR4_PSE | CR4_SMEP | CR4_SMAP | CR4_PKE)
b) track paging mode (CR4_PAE)
2) We need to always mask some bits in CR4 which is 1 in IA32_VMX_CR4_FIXED0.
CR4_VMXE for now.
3) We need to unmask some bits in CR4 which we want to hide the capability
from guest. (CR4_PCIDE, CR4_MCE for some type guest).
The others bits in CR4, as well as the reserved bits and bit is 0 in
IA32_VMX_CR4_FIXED1, we don't …
=> hv: vmcs: refine CR4 guest/host mask setting

hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/init.c, hypervisor/boot/acpi_base.c, hypervisor/boot/guest/deprivilege_boot.c, hypervisor/boot/guest/vboot_wrapper.c, hypervisor/boot/include/guest/vboot.h
Currently when get_rsdp is called, the EFI depriv_boot env is not initialized.
In such case it will fallback to the legacy mechanism of ACPI table.
If the ACPI table based on legacy mechanism is not found, it will fail to get
the ACPI table and then the system will hang.
On the old platform it still can parse the ACPI table from legacy mechanism.
In fact when EFI RSDP exists, the EFI RSDP is preferred instead of legacy ACPI
RSDP.
Tracked-On: #3184
=> ACRN/HV: Initialize the depriv_boot env to avoid the uninitialized RSDP

devicemodel/hw/pci/core.c, devicemodel/hw/pci/passthrough.c, devicemodel/include/pci_core.h
For PCI passthrough device when guest OS updates the BAR address
the corresponding EPT mapping should be updated as well.
Tracked-On: #2962
Signed-off-by: Liu Shuo A <shuo.a.liu@intel.com>
=> dm: pci: update MMIO EPT mapping when update BAR address

hypervisor/acpi_parser/acpi_ext.c
Since ACPI 2.0 a new field has been added to the table, X_FirmwareControl of type GAS,
which is 64bit. So use it conditionally.
Tracked-On: #3198
=> hv: use 64bit FACS table address only beyond ACPI2.0

hypervisor/dm/vpci/vmsi.c, hypervisor/dm/vpci/vmsix.c, hypervisor/include/common/ptdev.h
is_msix, part of ptirq_msi_info, is not used in the code.
Tracked-On: #3205
=> hv: Remove unused variable in ptirq_msi_info

devicemodel/hw/pci/virtio/virtio.c
In vxworks, virtio-console FE driver only initiate 2 virtqueues, but BE
creates 2+ virtqueues for it. So the rest of the virtqueues are not
initiated. vq->used->flags cannot be used directly without any
condition.
Tracked-On: #3203
=> dm: virtio: bugfix for polling mode

tools/acrn-crashlog/usercrash/client.c
This patch is to fix error logs in client sending to server via socket.
Since gdb inherits the socket descriptor of client which is used as its
stderr, in this case, the error logs from gdb will mess up server, so
closing the inheritance when the socket is created.
Tracked-On: #3200
=> tools:acrn-crashlog: fix error logs writing to server

devicemodel/hw/pci/core.c, devicemodel/include/pci_core.h
PCI spec says that the procedure of sizing a BAR is as follows:
1) disable the decode via command register
2) save the original value of BAR register
3) write all-1 to the BAR register
4) read BAR register back, calculate the size
5) restore the original value to BAR register
6) re-enable the decode via command register
Some driver does not disable the decode of BAR register via the
command register before sizing a BAR. This will lead to a overlay
of the BAR addresses when trying to register the intermediate
BAR address via register_bar. A stateful variable sizing is used
to keep track of such kind of BAR address changes and workaroud
this violation.
Currently this issue is only found when audio device is passed
through to Windows 10 guest. When it is fixed in the Windows
audio driver, …
=> dm: pci: fix the MMIO regions overlap when getting bar size

devicemodel/hw/pci/passthrough.c
Some physical bar sizes are not page aligned, in order to support them,
we map a bigger region which is page aligned.
Tracked-On: #3181
=> dm: passthrough: allow not page-aligned sized bar to be mapped

hypervisor/arch/x86/guest/vm.c, hypervisor/dm/vuart.c
When enable Transmitter Holding Register Empty interrupts, vuart should
trigger interrupt when the THR is empty. In the previous code, only
after the data is written to THR, the flag thre_int_pending is set to
true. The thre_int_pending should also be true after THRE is set.
Besides, add logic to make sure interrupt is in right state when vuart
is initiated.
Add vuart_deinit to vm shutdown so that the vuart resource can be
reset, and when the Guest VM restart, it could have right state.
=>  HV: vuart: Bugfix for no interrupts on THRE

devicemodel/core/main.c, devicemodel/hw/pci/virtio/virtio_console.c
When virtio-console is used as console port with socket backend,
guest kernel tries to hook it up with hvc console and sets it up.
It doesn't check if a client is connected and can result in ENOTCONN
with virtio-console backend being reset. This will prevent client
connection at a later point. To avoid this, ignore ENOTCONN error.
PS: For Kata, the runtime first launches VM and then proxy which acts
as a client connects to this socket. If this error is not handled,
proxy will never be able to connect as the backend itself will be reset.
Tracked-On: #3189
=> Fix hvc console handle sigpipe

hypervisor/arch/x86/configs/apl-mrb/misc_cfg.h, hypervisor/arch/x86/configs/apl-mrb/ve820.c, hypervisor/arch/x86/configs/apl-up2/misc_cfg.h, hypervisor/arch/x86/configs/dnv-cb2/misc_cfg.h, hypervisor/arch/x86/configs/dnv-cb2/ve820.c, hypervisor/arch/x86/configs/generic/misc_cfg.h, hypervisor/arch/x86/configs/nuc6cayh/misc_cfg.h, hypervisor/arch/x86/configs/nuc7i7bnh/misc_cfg.h, hypervisor/arch/x86/configs/nuc7i7bnh/ve820.c, hypervisor/arch/x86/guest/vm.c, hypervisor/boot/guest/vboot_info.c, hypervisor/common/vm_load.c, hypervisor/include/arch/x86/guest/vm.h, hypervisor/include/arch/x86/vm_config.h, hypervisor/scenarios/industry/vm_configurations.c, hypervisor/scenarios/industry/vm_configurations.h, hypervisor/scenarios/logical_partition/vm_configurations.c, hypervisor/scenarios/logical_partition/vm_configurations.h, hypervisor/scenarios/sdc/vm_configurations.c, hypervisor/scenarios/sdc/vm_configurations.h
The patch set will try to enable Zephyr as pre-launched VM.
Currently most of struct and function in vboot part are limited in Linux so
we need to rename them first, and then we need to abstract loading method
from Linux specific to more generic interface.
Secondly, we need to relove the problem that how to distinguish the
different modules for each VM in the multiboot file. The solution is use
a tag in module string to identify the usage of the module, and user could
specify the module in VM configurations. Before implemention we need to move
SOS bootargs to vm configuration because module string of mods[0] was occupied
by SOS bootargs.
Lastly, Zephyr kernel is a stripped ram binary, its entry and load address
are explicitly defined by users, so we need to add these items in
vm …
=> HV: patch set to enable Zephyr as pre-launched VM

doc/user-guides/acrn-shell.rst
The 'reboot' command from the ACRN shell has been removed. Remove the
corresponding documentation from the ACRN Shell user guide.
Tracked-On: #3210
=> doc: remove 'reboot' command from ACRN shell user guide

hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/init.c, hypervisor/arch/x86/mmu.c, hypervisor/arch/x86/seed/seed.c, hypervisor/arch/x86/seed/seed_abl.c, hypervisor/arch/x86/seed/seed_sbl.c, hypervisor/arch/x86/trampoline.c, hypervisor/arch/x86/vtd.c
hv: correctly grant DRHD register access rights to hypervisor
hv: delay enabling SMEP/SMAP until the end of PCPU initialization
Tracked-On: #3194
=> hv: improve code to grant DRHD register access rights for HV

doc/tutorials/using_partition_mode_on_nuc.rst, doc/tutorials/using_partition_mode_on_up2.rst
The multiboot module string will be used to identify the usage of current
module, it must exactly match with "kernel_mod_tag" which configured in
VM configurations files;
=> doc: add multiboot module string parameter

devicemodel/core/hugetlb.c, devicemodel/core/main.c, devicemodel/include/vmmapi.h
If you run two acrn-dm processes at the same time,
hugetblfs will be mounted twice, which will cause a memory leak.
The specific solution is :different virtual machines mount hugetblfs
into different directories.
Tracked-On:#2854
Signed-off-by: bing.li <bingx.li@intel.com>
Reviewed-by: Minggui Cao<minggui.cao@intel.com>
Acked-by: Yin Fengwei<fengwei.yin@intel.com>
=> dm: Solve the problem of repeat mount hugetblfs

hypervisor/arch/x86/guest/assign.c, hypervisor/arch/x86/vtd.c
This patch fix potential null pointer dereference
1, will access null pointer if 'context' is null.
2, if entry already been added to the VM when add
intx entry for this vm, but parameter virt_pin
is not equal to entry->virt_sid.intx_id.pin. So
will saves this entry address to
vpin_to_pt_entry[entry->virt_sid.intx_id.pin] and
vpin_to_pt_entry[virt_pin]. In this case, this entry
will be freed twice.
Tracked-On: #3217
=> hv: fix possible null pointer dereference

hypervisor/arch/x86/guest/vmexit.c, hypervisor/include/arch/x86/cpu.h
According to SDM vol1 13.3:
Write 1 to reserved bit of XCR0 will trigger GP.
This patch make ACRN behavior align with SDM definition.
Tracked-On: #3239
=> xsave: inject GP when guest tries to write 1 to XCR0 reserved bit

doc/getting-started/building-from-source.rst
- add an introduction part for building ACRN hypervisor
- clarify why ACRN hypervisor does not support one binary
for all platforms
=> doc: add an introduction for building hypervisor

devicemodel/samples/apl-mrb/launch_uos.sh
When the IO/MMIO acccess on Android guest causes the trap to hypervisor,
it will be blocked until the ioreq emulation is completed.
In order to get the better performance, it will be better that the ioreq
emulation can be completed ASAP. As it is handled in SOS kernel, the
corresponding thread priority will be raised.
Tracked-On:#3242
Signed-off-by: Liu, Shuo <shuo.liu@intel.com>
=> DM: Adjust the priority related with ioreq emulation for Android Guest

hypervisor/arch/x86/guest/vmcall.c, hypervisor/common/hypercall.c, hypervisor/include/arch/x86/guest/vm.h
On SDC scenario, SOS VM id is fixed to 0 so some hypercalls from guest
are using hardcoded "0" to represent SOS VM, this would bring issues
for HYBRID scenario which SOS VM id is non-zero.
Now introducing a new VM id concept for DM/VHM hypercall APIs, that
return a relative VM id which is from SOS view when create VM for post-
launched VMs. DM/VHM could always treat their own vm id is "0". When they
make hypercalls, hypervisor will convert the VM id to the absolute id
when dispatch the hypercalls.
Tracked-On: #3214
=> HV: introduce relative vm id for hcall api

devicemodel/core/main.c, devicemodel/hw/pci/core.c, devicemodel/hw/pci/lpc.c, devicemodel/hw/platform/acpi/acpi.c, hypervisor/arch/x86/guest/vm.c, hypervisor/dm/vioapic.c, hypervisor/dm/vpic.c, hypervisor/include/dm/vioapic.h
These two commits remove IOAPIC & PIC related entries in ACPI table for RT VM and skipped the initialization of vIOAPIC and vPIC.
Tracked-On: #3227
=> No vioapic/pic for RT VM

hypervisor/arch/x86/guest/assign.c, hypervisor/arch/x86/guest/virq.c, hypervisor/common/hypercall.c, hypervisor/dm/vpic.c, hypervisor/dm/vuart.c, hypervisor/include/dm/vpic.h
V1:Initial Patch
Modularize vpic. The current patch reduces the usage
of acrn_vm inside the vpic.c file.
Due to the global natire of register_pio_handler, where
acrn_vm is being passed, some usage remains.
These needs to be a separate "interface" file.
That will come in smaller newer patch provided
this patch is accepted.
V2:
Incorporated comments from Jason.
Reviewed-by: Xu, Anthony <anthony.xu@intel.com>
=> HV:Modularize vpic code to remove usage of acrn_vm

devicemodel/hw/pci/xhci.c, devicemodel/hw/platform/usb_pmapper.c, devicemodel/hw/usb_core.c, devicemodel/include/usb_core.h, devicemodel/include/usb_pmapper.h
This patchset re-implements the USB isochronous transfer and could support
at least 800x600 real time USB camera capturing.
BTW: currently, the USB isochronous transfer could not work normally under
WaaG.
=> Improve the performance of isochronous transfer

devicemodel/Makefile, devicemodel/core/main.c, devicemodel/core/vmmapi.c, devicemodel/hw/platform/rtc.c, devicemodel/include/log.h, devicemodel/log/disk_logger.c, devicemodel/log/kmsg_logger.c, devicemodel/log/log.c, devicemodel/samples/apl-up2/launch_uos.sh, devicemodel/samples/nuc/launch_uos.sh
add logger to save log into file system, also improve some parts of log system.
patch as followings:
DM: add static for local variables
DM: add disk-logger to write log into file system
DM: add disk-logger configure in launch script
DM: use pr_dbg in vrtc instead of printf
DM: add deinit API for loggers
Tracked-On: #3012
=> DM: add disk logger and improve log system 

hypervisor/arch/x86/guest/assign.c, hypervisor/arch/x86/guest/vcpu.c, hypervisor/arch/x86/guest/vlapic.c, hypervisor/arch/x86/guest/vm.c, hypervisor/common/hv_main.c, hypervisor/common/hypercall.c, hypervisor/include/arch/x86/guest/vcpu.h, hypervisor/include/arch/x86/guest/vlapic.h, hypervisor/include/arch/x86/guest/vm.h
This patch series introduces an API to check vLAPIC state across
vCPUs of a VM.
Tracked-On: #3253
=> Introduce vLAPIC state for VMs

devicemodel/samples/nuc/launch_vxworks.sh
This patch adds --lapic_pt option to launch VxWorks as hard-rt VM.
=> DM: Samples: Enable VxWorks as hard-rt VM

hypervisor/dm/vpci/pci_pt.c, hypervisor/dm/vpci/vmsix.c, hypervisor/include/dm/vpci.h
Rename MSI-X struct, pci_msix, member from tables to table_entries
Tracked-On: #3265
=> hv: Rename tables member of vPCI msix struct pci_msix

devicemodel/samples/nuc/launch_uos.sh
The patch adds new argument for launch_uos script for NUC.
In the patch add "-C" parameter for launch_uos script. When launch
the script with the parameter the ACRN-dm will be launched in the
runC container. For more information about this please refer to
ACRN-dm QoS document.
Tracked-On: #2020
=> ACRN: DM: Add new options for NUC launch_uos script.

doc/Makefile
The doxygen-collected API information about function preconditions has a
uninspired title of "pre".  This change tweaks that to be
"preconditions" in the generated HTML output by editing the generated
xml output before it is processed by Sphinx/Breathe.
=> doc: tweak doxygen precondition label

doc/getting-started/acrn_quick_setup.sh, doc/getting-started/apl-nuc.rst
Clear Linux changed from systemd-networkd to NetworkManager as default
"network manager", We need to install "systemd-networkd-autostart"
bundle to enable systemd-networkd to create ACRN network bridges and Tap
devices.
Signed-off-by: Lei Lu <leix.lu@intel.com>
=> doc: add systemd-networkd-autostart bundle in APL GSG

devicemodel/samples/nuc/launch_uos.sh
When FE virtio devices work in polling mode, sshd.service can't start
normally and blocks at generating random bytes. When reading from
the random source, getrandom() blocks caused by no random bytes.
Tracked-On: #3268
=> dm: add virtio-rnd device to command line

devicemodel/core/mem.c, devicemodel/hw/pci/virtio/virtio_audio.c, devicemodel/hw/pci/virtio/virtio_console.c, devicemodel/hw/pci/virtio/virtio_gpio.c, devicemodel/hw/pci/virtio/virtio_hyper_dmabuf.c, devicemodel/hw/pci/virtio/virtio_net.c, devicemodel/hw/pci/virtio/virtio_rnd.c, devicemodel/hw/pci/xhci.c
During static code analysis for ACRN hypervisor source code,
there have some issues.
1, buffer overflow - array index out of bounds
2, use of banned functions in source code
3, potential memory leak found.
=> fix some security issues

hypervisor/common/hypercall.c
In hcall_inject_msi, we check vlapic state of SOS by mistake.
If the SOS's vlapic state doesn't equal to target_vm's, the OVMF will
hang when boot up. Instead, we should check the target_vm's
vlapic state.
=> HV: Fix OVMF hang issue when boot with lapic_pt

hypervisor/arch/x86/guest/vlapic.c, hypervisor/include/arch/x86/guest/vmcs.h
v2:
add MACRO to define APIC-Access access type
v1:
The current implement doesn't clear which access type we support for
APIC-Access VM Exit:
1) linear access for an instruction fetch
-- APIC-access page is mapped as UC which doesn't support fetch
2) linear access (read or write) during event delivery
-- Which is not happened in normal case except the guest went wrong, such as,
set the IDT table in APIC-access page. In this case, we don't need to support.
3) guest-physical access during event delivery;
guest-physical access for an instruction fetch or during instruction execution
-- Do we plan to support enable APIC in real mode ? I don't think so.
=> hv: vlapic: clear which access type we support for APIC-Access VM Exit

devicemodel/arch/x86/pm.c, devicemodel/core/hugetlb.c, devicemodel/core/inout.c, devicemodel/core/main.c, devicemodel/core/mem.c, devicemodel/core/post.c, devicemodel/core/sw_load_common.c, devicemodel/core/sw_load_elf.c, devicemodel/core/sw_load_ovmf.c, devicemodel/core/sw_load_vsbl.c, devicemodel/core/timer.c, devicemodel/core/vmmapi.c, devicemodel/hw/pci/irq.c, devicemodel/hw/pci/wdt_i6300esb.c, devicemodel/hw/platform/acpi/acpi.c, devicemodel/hw/platform/rtc.c
Cleanup "assert" usages for below files in Devicemodel:
arch/x86/pm.c
core/hugetlb.c
core/main.c 
core/sw_load_common.c
core/sw_load_elf.c
core/sw_load_ovmf.c
core/sw_load_vsbl.c
hw/pci/wdt_i6300esb.c
hw/platform/acpi/acpi.c
hw/platform/rtc.c
core/mem.c 
core/post.c
core/inout.c
core/timer.c
core/vmmapi.c
hw/pci/irq.c
=> Device Model  'assert'  cleanup patches set

hypervisor/arch/x86/cpu_caps.c, hypervisor/arch/x86/guest/ept.c, hypervisor/arch/x86/guest/vm.c, hypervisor/arch/x86/guest/vmexit.c, hypervisor/arch/x86/mmu.c, hypervisor/include/arch/x86/cpufeatures.h, hypervisor/include/arch/x86/guest/ept.h, hypervisor/include/arch/x86/guest/vm.h, hypervisor/include/arch/x86/mmu.h
wbinvd is used to write back all modified cache lines in the processor's
internal cache to main memory and invalidates(flushes) the internal caches.
Using clflushopt instructions to emulate wbinvd, and if clflushopt instruction
is not supported, boot will fail.
v2: 1) flush cache by walking through ETP instead seperated memory regions
2) Check RT VM firstly before wbinvd emulation, if there is no RT VM,
invoke wbinvd instruction directly.
3) Do not flush uncached page.
4) It also needs to emulate wbinvd instruction for SOS, not only UOS.
v3: 1) Add CLFLUSHOPT supporting check in boot time.
2) Refine walking ept table interface.
3) Add flush_cache interface in mmu.c
4) Add get_ept and ept_mr_flush interfaces.
v4: 1) Splite the patch.
2) Add comments for API.
3) Remove sfence.
4) Refine …
=>  HV: Implement wbinvd instruction emulation

devicemodel/hw/pci/core.c, devicemodel/hw/pci/lpc.c, devicemodel/hw/pci/virtio/virtio_coreu.c, devicemodel/hw/pci/virtio/virtio_hdcp.c, devicemodel/hw/pci/virtio/virtio_ipu.c, devicemodel/hw/pci/virtio/virtio_mei.c, devicemodel/hw/platform/atkbdc.c, devicemodel/hw/platform/cmos_io.c, devicemodel/hw/platform/ps2kbd.c, devicemodel/hw/platform/ps2mouse.c, devicemodel/include/pci_core.h, devicemodel/include/types.h
Clean up assert() in DM, changes include
devicemodel/hw/pci/core.c                | 159 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++---------------------------------------------------------------------
devicemodel/hw/pci/lpc.c                 |   8 ++++++--
devicemodel/hw/pci/virtio/virtio_coreu.c |  11 +++++++++--
devicemodel/hw/pci/virtio/virtio_hdcp.c  |  17 +++++++++++------
devicemodel/hw/pci/virtio/virtio_ipu.c   |   5 ++---
devicemodel/hw/pci/virtio/virtio_mei.c   |  24 +++++++++++++++++-------
devicemodel/hw/platform/atkbdc.c         |  24 ++++++++++++++++--------
devicemodel/hw/platform/cmos_io.c        |   6 ------
devicemodel/hw/platform/ps2kbd.c         |  10 +++++-----
devicemodel/hw/platform/ps2mouse.c       |  13 +++++-------- …
=> DM Assert cleanup

hypervisor/arch/x86/guest/vm.c
There are a lot of works to do between create_vm (HV will mark vm's state
as VM_CREATED at this stage) and vm_run (HV will mark vm's state as VM_STARTED),
like building mptable/acpi table, initializing mevent and vdevs. If there is
something goes wrong between create_vm and vm_run, the devicemodel will jumps
to the deinit process and will try to destroy the vm. For example, if the
vm_init_vdevs failed, the devicemodel will jumps to dev_fail and then destroy
the vm.
For normal vm in above situation, it is fine to destroy vm. And we can create and
start it next time. But for RTVM, we can't destroy the vm as the vm's state is
VM_CREATED. And we can only destroy vm when its state is VM_POWERING_OFF. So, the
vm will stay at VM_CREATED state and we will never have chance to destroy it. …
=> HV: Allow pause RTVM when its state is VM_CREATED

devicemodel/hw/pci/virtio/virtio_gpio.c, devicemodel/hw/platform/ioc.c
This patch is to clean up assert from ioc and virtio-gpio
=> dm: clean up assert from ioc and virtio-gpio

devicemodel/samples/nuc/launch_vxworks.sh
Current launch script leave stdio to OVMF console and, vxworks console to pty, so user
need to use additional toll like minicom to connect to pty device to use vxWorks.
To be more convinient, this commit changes the vxWorks to use the stdio by default, and OVMF
is not availabe by default.
=> dm: samples: use stdio as vxWorks console by default

hypervisor/arch/x86/guest/vcpu.c
MISRA-C requires inline functions should be declared static,
these APIs are some external interfaces in this patch,remove inline
modified:   arch/x86/guest/vcpu.c
=> hv:Fix MISRA-C violations for static inline

hypervisor/arch/x86/Kconfig, hypervisor/arch/x86/ioapic.c, hypervisor/include/arch/x86/ioapic.h
Remove couple of run-time ASSERTs in ioapic module by checking for the
number of interrupt pins per IO-APICs against the configured MAX_IOAPIC_LINES
in the initialization flow.
Also remove the need for two MACROs specifying the max. number of
interrupt lines per IO-APIC and add a config item MAX_IOAPIC_LINES for the
same.
Tracked-On: #3299
=> hv: Avoid run-time buffer overflows with IOAPIC data structures

devicemodel/core/mevent.c, devicemodel/hw/pci/uart.c, devicemodel/hw/pci/virtio/virtio_console.c, devicemodel/hw/uart_core.c
Remove unnecessary assert and add error handling when required.
=> dm: refine assert usage

hypervisor/debug/shell.c, hypervisor/debug/shell_priv.h
When debugging the HV, we may want to check the HV version information
frequently. In current HV shell command, there is no such kind of command
to check this information. We can only scroll up the HV console log to
get the information. If there are very huge amount of lines of log, it
will be very time-wasting to get the HV version information.
So, this patch adds 'version' command to get the HV version information
conveniently.
Tracked-On: #3310
=> HV: Debug: Add version command

hypervisor/arch/x86/configs/vmptable.c, hypervisor/arch/x86/guest/assign.c, hypervisor/arch/x86/guest/vm.c, hypervisor/arch/x86/vtd.c, hypervisor/boot/acpi_base.c, hypervisor/boot/guest/vboot_info.c, hypervisor/dm/vrtc.c, hypervisor/dm/vuart.c
Fix the violations not touched the logical.
1.Function return value not checked.
2.Logical conjuctions need brackets.
3.No brackets to then/else.
4.Type conversion without cast.
=> HV:fix simple violations

devicemodel/hw/pci/xhci.c, devicemodel/hw/platform/usb_mouse.c, devicemodel/hw/platform/usb_pmapper.c
Remove assert in USB mediator code.
=> DM USB: clean up the assert usage

hypervisor/arch/x86/guest/vlapic.c, hypervisor/include/arch/x86/guest/vlapic.h
v3:
remove isr_nr
some minor fix about the comments.
v2:
remove isrvec_stk completely.
v1:
The current implement will do ISR vector stack check when updating PPR. However,
there is no need to do this because:
1) We will not touch vlapic->isrvec_stk[0] except doing vlapic_reset:
So we don't need to do vlapic->isrvec_stk[0] check.
2) We only deliver higher priority interrupt from IRR to ISR:
So we don't need to check whether vlapic->isrvec_stk interrupts is always increasing.
3) There're only 15 different priority interrupt, It will not happened that more that
15 interrupts could been delivered to ISR:
So we don't need to check whether vlapic->isrvec_stk_top will larger than
ISRVEC_STK_SIZE which is 16.
=> hv: vlapic: remove ISR vector stack

hypervisor/dm/vpci/pci_pt.c, hypervisor/dm/vpci/vhostbridge.c, hypervisor/hw/pci.c, hypervisor/include/dm/vpci.h, hypervisor/include/hw/pci.h
Remove unused function find_pci_pdev
Add get_offset_of_caplist() function to return capability offset based on header type
Add union pci_bar and is_64bit_high to struct pci_bar
Add uint32_t nr_bars to struct struct pci_pdevpci_vdev to track # of bars
Tracked-On: #3241 
=> VPCI code cleanup/reorg

hypervisor/arch/x86/guest/vcpu.c, hypervisor/arch/x86/guest/vm.c, hypervisor/debug/sbuf.c, hypervisor/include/debug/sbuf.h, hypervisor/release/sbuf.c
The sbuf is allocated for each pcpu by hypercall from SOS. Before launch
Guest OS, the script will offline cpus, which will trigger vcpu reset and
then reset sbuf pointer. But sbuf only initiate once by SOS, so these
cpus for Guest OS has no sbuf to use. Thus, when run 'acrntrace' on SOS,
there is no trace data for Guest OS.
To fix the issue, only reset the sbuf for SOS.
Tracked-On: #3335
=> hv: bugfix for sbuf reset

tools/acrn-manager/README.rst, tools/acrn-manager/acrnd.c
Enhance and re-order the help messages for the `acrnd` tools (daemon for
ACRN VM management). Fix a few typos in the process.
=> tools: enhance online and built-in help messages

devicemodel/samples/nuc/launch_hard_rt_vm.sh
This commit adds "noapic" boot option to rt-linux, to skip IOAPIC probe.
Tracked-On: #3227
=> dm: add "noapic" to rt-linux kernel parameters

hypervisor/arch/x86/guest/vcpu.c, hypervisor/arch/x86/guest/virq.c, hypervisor/include/arch/x86/guest/vcpu.h
vcpu is never scan because of scan tool will be crashed!
After modulization, the vcpu can be scaned by the scan tool.
Clean up the violations in vcpu.c.
Fix the violations:
Huihuang Shi (2):
HV:fix vcpu violations
V1->V2:
change the type of "vcpu->arch.irq_window_enabled" to bool.
HV:fix vcpu more than one return entry
V1->V2:
change the code path to:
if (condition) {
normal path
} else {
abnormal path
}
=> Clean up vcpu

hypervisor/dm/vpci/pci_pt.c, hypervisor/hw/pci.c, hypervisor/include/arch/x86/vm_config.h, hypervisor/include/dm/vpci.h, hypervisor/include/hw/pci.h, hypervisor/scenarios/logical_partition/pt_dev.c
Extract functions from code to improve code reuse and readability
Remove uint64_t base from struct pci_bar
Add get_pbar_base()/get_vbar_base to get pbar/vbar base address in 64-bit
Remove the function get_bar_base()
Tracked-On: #3241
Signed-off-by: dongshen dongsheng.x.zhang@intel.com
Acked-by: Eddie Dong eddie.dong@intel.com
=> VPCI code cleanup/reorg #2

doc/developer-guides/c_coding_guidelines.rst, doc/developer-guides/sw_design_guidelines.rst
In the current design guidlines, it is not clear about
how to check application constraints and how to record
them.
Add description about it is optional to do error checking
for application constraints during hypversisor boot time;
Add reference about how to record design assumptions.
Signed-off-by: Xiangyang Wu <xiangyang.wu@linux.intel.com>
=> doc:add more description about application constraints

tools/acrn-manager/README.rst, tools/acrn-manager/acrnctl.c, tools/acrn-manager/acrnd.c
Add a check to acrnd and acrnctl to make sure we are running with root
privileges. If not, print out a message instructing the user to run with root
privileges and exit returning an error (-1).
Add notes to the documentation as well to make it more obvious.
Tracked-On: #3330
=> tools: add check to verify that running with root privileges

hypervisor/arch/x86/guest/ept.c, hypervisor/include/arch/x86/pgtable.h
According to SDM, bit N (physical address width) to bit 63 should be masked when calculate
host page frame number.
Currently, hypervisor doesn't set any of these bits, so gpa2hpa can work as expectd.
However, any of these bit set, gpa2hpa return wrong value.
Hypervisor never sets bit N to bit 51 (reserved bits), for simplicity, just mask bit 52 to bit 63.
Tracked-On: #3352
Reviewed-by: Eddie Dong<eddie.dong@intel.com>
=> hv: ept: mask EPT leaf entry bit 52 to bit 63 in gpa2hpa

devicemodel/core/gc.c, devicemodel/hw/pci/gvt.c, devicemodel/hw/pci/virtio/virtio_hyper_dmabuf.c
Code clean up. Handle the errors more gracefully instead of assert()
If failed create the pci device, dm will not clean up the failed
device. So no chance to call .vdev_deinit(). Driver needs to handle this
case by itself. So in v2, do more clean up to address the assert() case
v2: do more clean up for gvt.
Liu Xinyun (3):
dm: gc: clean up assert
dm: hyper_dmabuf: clean up assert
dm: gvt: clean up assert
devicemodel/core/gc.c                         |  1 -
devicemodel/hw/pci/gvt.c                      | 72 +++++++++++--------
.../hw/pci/virtio/virtio_hyper_dmabuf.c       |  6 +-
3 files changed, 45 insertions(+), 34 deletions(-)
=> Fix assert

devicemodel/samples/nuc/launch_hard_rt_vm.sh
This reverts commit c42b41fe2b723a0d24b2084a780be41e0a7dff5c.
Kernel will stay in xapic mode with this boot arg, lapic won't be passthru, so revert.
Tracked-On: #3227
=> Revert "dm: add "noapic" to rt-linux kernel parameters"

devicemodel/core/main.c, devicemodel/core/timer.c, devicemodel/hw/platform/hpet.c, devicemodel/hw/platform/pit.c
Remove the use of assert() in vPIT and vHPET.
Reviewed-by: <yonghua.huang@intel.com>
Acked-by: Yin, Fengwei <fengwei.yin@intel.com>
=> Clean up asserts in vPIT and vHPET

hypervisor/acpi_parser/acpi_ext.c, hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/guest/vm_reset.c, hypervisor/arch/x86/guest/vmexit.c, hypervisor/common/ptdev.c, hypervisor/include/arch/x86/guest/vm_reset.h, hypervisor/include/common/ptdev.h
Now atomic APIs are used in some places where them don't needed or are used wrong
to plan to guarantte the access to the corresponding structure is atomic.
This patch is just a beginning, it tries to remove the unnecessary atomic using and
correct a wrong using case.
Li, Fei1 (4):
hv: ptdev: refine ptdev active flag
hv: cpu: remove CPU up count
hv: vm_manage: minor fix about triple_fault_shutdown_vm
hv: io_req: refine vhm_req status setting
=> Correct atomic API using

hypervisor/dm/vpci/pci_pt.c, hypervisor/dm/vpci/vdev.c, hypervisor/dm/vpci/vmsi.c, hypervisor/dm/vpci/vmsix.c, hypervisor/dm/vpci/vpci.c, hypervisor/dm/vpci/vpci_priv.h, hypervisor/hw/pci.c, hypervisor/include/dm/vpci.h, hypervisor/include/hw/pci.h
Current bar emulation code requires bar size <= 4GB, and report 64-bit bar as 32-bar to 
VMs. Also, currently bar emulation is only enabled for pre-launched VMs.
This PR fixed the above 2 issues:
Adds support for 64-bit bar emulation and enabled bar emulation for SOS.
Enabled PIO bar emulation.
Tracked-On: #3241
=> Add support for 64-bit bar emulation and enable bar emulation for SOS

devicemodel/core/vrpmb.c, devicemodel/hw/pci/core.c, devicemodel/hw/platform/debugexit.c, devicemodel/hw/platform/tpm/tpm.c, devicemodel/hw/platform/tpm/tpm_crb.c, devicemodel/hw/platform/tpm/tpm_emulator.c, devicemodel/hw/platform/usb_mouse.c, devicemodel/hw/platform/usb_pmapper.c, devicemodel/hw/usb_core.c
- check input by condition check, instead of assert.
- remove redundant header file including for some files.
Reviewed-by: Shuo Liu <shuo.a.liu@intel.com>
=> dm: cleanup assert in core.c

hypervisor/arch/x86/guest/vmexit.c
According to SDM, xsetbv writes the contents of registers EDX:EAX into the 64-bit
extended control register (XCR) specified in the ECX register. (On processors
that support the Intel 64 architecture, the high-order 32 bits of RCX are ignored.)
In current code, RCX is checked, should ingore the high-order 32bits.
Tracked-On: #3360
=> hv: vmexit: ecx should be checked instead of rcx when xsetbv

devicemodel/Makefile, devicemodel/hw/pci/virtio/virtio_i2c.c, devicemodel/include/virtio.h
In current code, when the Guest OS wants to access to a slave I2C device, it should pass through the whole I2C adapter. But if the adapter has two or more slave devices, and need to be used by different Guests, pass through cannot meet the requirement.
To be more flexible, virtio-i2cadap was put forward, and it should have features:
1. Work as an I2C adapter.
2. Slave devices under same physical adapter can be assigned to different virtio-i2c adapters.
3. Support >= 1 slave devices.
4. I2C slave devices driver needn't change.
=> DM: support virtio-i2c

hypervisor/arch/x86/guest/assign.c, hypervisor/dm/vioapic.c
Need to set correct initial pin state of vioapic, and avoid generate
redundant interrupt into the guest:
1. set initial pin state accoring to rte attributes, ignore the value of
entry->polarity because entry->polarity is uninitialized.
2. since vioapic_generate_intr relys on rte, we should build rte
beforegenerating an interrput.
This patch fix the interrupt lost, typically the first interrput of
external device, and fix the redundant interrupts generated into guest.
Tracked-On: #3362
Signed-off-by: Cai Yulong <yulongc@hwtc.com.cn>
=> hv: vioapic: fix interrupt lost of external device

devicemodel/core/mem.c, devicemodel/hw/pci/virtio/virtio_net.c, devicemodel/hw/pci/xhci.c
dm: porting patch from master to apl_sdc_stable branch
During static code analysis for ACRN hypervisor source code,
there have some issues.
1, buffer overflow - array index out of bounds
2, potential memory leak found.
Tracked-On: #3331
Tracked-On: #3333
=> Apl sdc stable

hypervisor/Makefile
Since 9c81f4c32c1f ("hv:build library to lib_mod.a"), the parallel build
system was broken. You cannot use "make -j #" to build ACRN.
To fix this we need to declare explicit rules for the files to be built.
Also remove "$(LIB_FLAGS): lib " and " MOD_DEPS " since they are
redundancy after this change.
This closes #3351
Tracked-On: projectacrn#3351
=> makefile: fix parallel build

hypervisor/arch/x86/guest/instr_emul.c, hypervisor/include/arch/x86/guest/instr_emul.h
ACRN Coding guidelines requires no dead code.
=> HV: remove instr_emul.c dead code

hypervisor/arch/x86/guest/vcpu.c, hypervisor/arch/x86/guest/virq.c, hypervisor/common/hv_main.c, hypervisor/include/arch/x86/guest/vcpu.h, hypervisor/include/arch/x86/irq.h
One cycle of vmexit/vmentry might lost interrupts.
This is the scenario,
1) vmexit, vmexit_handlers
2) softirq & disable interrupt
3) acrn_handle_pending_request
4) schedule if needed, then back to 1) and loop again.
5) vmentry
The step 3) might be executed twice. The problem is at the second
execution of acrn_handle_pending_request, we might overwrite
VMX_ENTRY_INT_INFO_FIELD of current vmcs, which cause guest lost
interrupts.
The fix is moving 4) prior to 3), then we will handle the pending
requests and vmentry directly.
Tracked-On: #3374
=> Fix potential interrupt list issue

hypervisor/arch/x86/configs/vmptable.c, hypervisor/dm/vuart.c, hypervisor/include/dm/vuart.h
fix violations touched in vuart.c vcpu.c and vmptables.
fix the violations below:
1.parameter needs to add const.
2.Function shall have one return entry.
3.Do not use -- or ++ opertaion.
4.For loop should be simple,shall not use comma operations.
=> fix violations violate Coding guideline

devicemodel/core/hugetlb.c
Current hugetlbfs code has a limitation on file path length.
The path string comprises of mount path + vm name.
Something like /run/hugepage/acrn/huge_lv1/vm1.
To this UUID (32 bytes) is added and the total path length
should be less than 128.
This works fine but in cases where the VM name is large as
in case kata, this check fails. Kata passes a sandbox-id
as VM name and so path + 32 for UUID easily exceed 128 bytes.
“/run/hugepage/acrn/huge_lv1/
sandbox-6d455fa48788eae82dee42410fc3d38849c2a5196f930b3d6944805aed8d24c7"
To address this, increase the size of MAX_PATH_LEN from
128 to 256 bytes.
Tracked-On: #3379
=> DM: Increase hugetlbfs MAX_PATH_LEN from 128 to 256

devicemodel/samples/nuc/launch_uos.sh, hypervisor/scenarios/hybrid/vm_configurations.c
1. add vuart for VM2 in hybrid scenario.
2.  Set virtio-console BE to stdio for LaaG. Remove 'com1' but still keep
'console=ttyS0' in Laag kernel cmdline.
'console=ttyS0' means LaaG will use ttyS0 (0x3F8) as a console port, and
during bringup, it will access port ttyS0. When the same port is added
to hypervisor configuration file as a console port, the output will be
captured by hypervisor console, and can switch by "vm_console <vm_id>".
=> Enable vuart console for VM2 in hybird scenario

hypervisor/arch/x86/security.c, hypervisor/include/arch/x86/cpufeatures.h
Hypervisor exposes mitigation technique for Speculative
Store Bypass(SSB) to guests and allows a guest to determine
whether to enable SSBD mitigation by providing direct guest
access to IA32_SPEC_CTRL.
Before that, hypervisor should check the SSB mitigation support
on underlying processor, this patch is to add this capability check.
Tracked-On: #3385
=> HV: check security mitigation support for SSBD

hypervisor/arch/x86/configs/apl-mrb/ve820.c, hypervisor/arch/x86/configs/dnv-cb2/ve820.c, hypervisor/arch/x86/configs/nuc7i7bnh/ve820.c, hypervisor/arch/x86/configs/vmptable.c, hypervisor/arch/x86/guest/vm.c, hypervisor/common/vm_load.c, hypervisor/debug/logmsg.c, hypervisor/debug/profiling.c, hypervisor/debug/sbuf.c, hypervisor/debug/trace.c, hypervisor/include/arch/x86/guest/vm.h, hypervisor/include/arch/x86/per_cpu.h
ACRN Coding guidelines requires two different types pointers pointer can't convert to each other.
=> HV: fix "Casting operation to a pointer"

tools/acrn-manager/Makefile
The ioc-cbc-tools package depends on "acrn_mgr.h". This header was
updated with new includes since b2f2d952464e ("tools: acrnctl restrict
length of vmname to 32 bytes") and  in 517707dee4ca ("DM/HV: Increase VM
name len") was updated to include dm.h
This commit add all "acrn_mngr.h" dependencies and install them to
"$(DESTDIR)/usr/include/acrn".
Also modify install mode to 0644 to headers and libacrn-mngr.a file.
This closes projectacrn/acrn-hypervisor#3368
Tracked-On: #3368
=> tools: acrn-manager: fix headers install for ioc cbc tools

devicemodel/hw/pci/xhci.c, devicemodel/hw/platform/usb_pmapper.c
This patch series fixes some issues under WaaG and LaaG.
1. USB BT device can't do scaning
2. Need long time to enumerate certain brand USB disk.
Tracked-On: #3401
=> Fix some corner cases for USB mediator

hypervisor/dm/vpci/vhostbridge.c, hypervisor/dm/vpci/vmsi.c, hypervisor/dm/vpci/vmsix.c, hypervisor/dm/vpci/vpci.c, hypervisor/dm/vpci/vpci_priv.h, hypervisor/include/dm/vpci.h
This patch set add pci vdev ops and invoke callback in general pci vdev config space access.
It also move the hostbridge from SOS to HV to prevent hostbridge operation from SOS impact higher severity VM.
Tracked-On: #3241
=> add vpci ops to replace the device specific function invoke

tools/acrn-crashlog/acrnprobe/channels.c, tools/acrn-crashlog/acrnprobe/crash_reclassify.c, tools/acrn-crashlog/acrnprobe/include/crash_reclassify.h, tools/acrn-crashlog/acrnprobe/include/load_conf.h, tools/acrn-crashlog/acrnprobe/load_conf.c, tools/acrn-crashlog/acrnprobe/sender.c, tools/acrn-crashlog/common/fsutils.c, tools/acrn-crashlog/data/acrnprobe.xml
As all pstore files may include the kernel panic information, this patch
tries to find the clue from all messages under /sys/fs/pstore instead of
console-ramoops-0.
To avoid the constant growing of logs, it has to remove the pstore
files after panic being detected.
Tracked-On: #3390
=> tools:acrn-crashlog: detect the panic event from all pstore files

hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/init.c, hypervisor/include/arch/x86/cpu.h
When initialize secondary pcpu, pass INVALID_CPU_ID as param of init_pcpu_pre()
looks weird, so change the param type to bool to represent whether the pcpu is
a BSP or AP.
Tracked-On: #3420
=> HV: change param type of init_pcpu_pre

hypervisor/dm/vuart.c
When a VM send data to its communication vuart, the vuart driver should
inject a DR interrupt to target VM and also inject a THRE interrupt to
self VM. But the original code inject the THRE interrupt to target VM,
correct it in this patch.
Tracked-On: #3423
=> hv: vuart: bugfix for communication vuart

hypervisor/Makefile, hypervisor/arch/x86/Kconfig, hypervisor/scenarios/sdc2/vm_configurations.c, hypervisor/scenarios/sdc2/vm_configurations.h
Per community requirement;up to three post-launched VM might be
needed for some automotive SDC system, so add SDC2 scenario to
satisfy this requirement.
Tracked-On: #3429
=> HV: add SDC2 config in hypervisor/arch/x86/Kconfig

devicemodel/hw/block_if.c, devicemodel/hw/platform/acpi/acpi.c, hypervisor/arch/x86/lapic.c, hypervisor/arch/x86/notify.c, tools/acrn-crashlog/common/log_sys.c, tools/acrn-crashlog/usercrash/crash_dump.c
These patches fix some issues reported by penetration test.
1, hv:  fix some potential array overflow risk
2, dm: fix variable argument list read without ending with va_end
3, tools: fix variable argument list read without ending with va_end
4, dm: fix some possible memory leak
Tracked-On: #3407
Tracked-On: #3406
Tracked-On: #3405
Signed-off-by: Tianhua Sun tianhuax.s.sun@intel.com
Reviewed-by: Yonghua Huang yonghua.huang@intel.com
Acked-by: Gang Chen gang.c.chen@intel.com
=> Apl sdc stable: fix some issues reported by penetration test

CODEOWNERS
Deb (@deb-intel) added as a reviewer for ACRN documentation.
=> doc: update CODEOWNERS for doc reviews

devicemodel/hw/pci/virtio/virtio_i2c.c
Change the condition of checking native adapter number.
Change sprintf to snprintf.
Tracked-On: #3437
=> dm: virtio-i2c: minor fix

devicemodel/Makefile, hypervisor/Makefile, tools/acrn-manager/Makefile
In release environment, binary files must be stripped in
order to remove debugging code sections and symbol information
that aid attackers in the process of disassembly and reverse
engineering.
Use '-s' linking option to remove symbol table and relocation
information from release binaries.
Tracked-On: #3433
=> apl_sdc_stable:hv: fix symbols not stripped from release binaries

hypervisor/arch/x86/guest/vcpu.c, hypervisor/arch/x86/guest/vlapic.c, hypervisor/arch/x86/guest/vlapic_priv.h, hypervisor/include/arch/x86/guest/vlapic.h
Because we depend on guest OS to switch x2apic mode to enable lapic pass-thru, vlapic is working at the early stage of booting, eg: in virtual boot loader.
After lapic pass-thru enabled, no interrupt should be injected via vlapic any more.
To enforce that, this series add an ops pointer in vlapic structure and reset the vlapic to clear the pending status and assign the ops with invalid ptapic_ops.
Tracked-On: #3227
=>  Enforce no interrupt to RT VM via vlapic once lapic pt

doc/scripts/sign_image.sh, doc/tutorials/sign_clear_linux_image.rst
This tutorial will describe steps to sign binaries of
a Clear Linux image that allows user to launch VM
throught the secure boot enabled OVMF.
=> doc: Add tutorial to learn to sign binaries of a Clear Linux image.

doc/tutorials/acrn-dm_QoS.rst, doc/tutorials/using_partition_mode_on_nuc.rst, doc/tutorials/using_partition_mode_on_up2.rst, doc/tutorials/using_vxworks_as_uos.rst, doc/tutorials/using_zephyr_as_uos.rst
Neither ACRN tag nor Clear Linux version is specified in some tutorials.
Declare those information for those tutorials.
=> doc: Add ACRN tag or Clear Linux version info for some tutorials

doc/getting-started/apl-nuc.rst, doc/getting-started/up2.rst
As the vuart config option is not support anymore, remove it.
=> doc: remove vuart configuration in nuc and up2

hypervisor/arch/x86/guest/vcpu.c, hypervisor/arch/x86/guest/vmexit.c, hypervisor/arch/x86/irq.c, hypervisor/common/hv_main.c, hypervisor/common/softirq.c, hypervisor/dm/vioapic.c, hypervisor/dm/vpic.c, hypervisor/dm/vuart.c, hypervisor/include/arch/x86/per_cpu.h
This patch set is used to revise the hv_main loop to prevent acrn_handle_pending_request
called twice in one vmexit.
Tracked-On: #3387
=> Hv main refine

devicemodel/core/hugetlb.c, devicemodel/core/main.c, devicemodel/core/sw_load_ovmf.c, devicemodel/include/sw_load.h, devicemodel/include/vmmapi.h
To support modification of OVMF NV storage, give write permission to guest for writeback support. Add an option "w" for --ovmf to write the changed OVMF NV storage back to the original OVMF image from guest memory before deinit operations.
=> DM: Ovmf NV storage writeback support

hypervisor/dm/vpci/vhostbridge.c, hypervisor/dm/vpci/vpci.c, hypervisor/include/dm/vpci.h
This is a followup patch to fix the coding style issue introduced
in by commit "c2d25aafb889ade954af8795df2405a94024d860":
The unmodified pointer should be defined as const
Also addressed one comments from Fei to use reversed function call
in vpci_init_pt_dev and vpci_deinit_pt_dev.
Tracked-On: #3241
=> vpci: fix coding style issue

hypervisor/arch/x86/configs/apl-mrb/pci_devices.h, hypervisor/arch/x86/configs/nuc7i7dnb/pci_devices.h, hypervisor/scenarios/logical_partition/pt_dev.c
The vbar info which hard-coded in scenarios/logical_partition/pt_dev.c
is board specific actually, so move these information to
arch/x86/configs/$(CONFIG_BOARD)/pci_devices.h.
Please be aware that the memory range of vBAR should exactly match with
the e820 layout of VM.
Tracked-On: #3214
=> HV: move vbar info to board specific pci_devices.h

hypervisor/arch/x86/guest/vmsr.c
Per SDM, writing 0 to MSR_IA32_MCG_STATUS is allowed, HV should not
return -EACCES on this case;
Tracked-On: #3454
=> HV: allow write 0 to MSR_IA32_MCG_STATUS

doc/tutorials/create-up2-images.sh
SOS bootargs is specified in vm_configurations.h in different scenarios.
The files in devicemodel/samples/<board>/sos_bootargs_*.txt are removed.
remove deprecated sos_bootargs in create-up2-images.sh
Tracked-On: [#3443
](https://github.com/projectacrn/acrn-hypervisor/issues/3443)
Signed-off-by: Lei Lu <leix.lu@intel.com>
=> doc: remove deprecated sos_bootargs

hypervisor/debug/uart16550.c
Now if the uart is mapped to a PIO address space, the uart base address is a physical
PIO address; if it's mapped to a MMIO address space, the uart base address is a
virtual MMIO address. Add union uart_addr structure to imply this.
And define a console_uart structure to add all uart related fields into this structure.
=> hv: uart: make uart base address more readable

devicemodel/hw/pci/virtio/virtio_console.c, devicemodel/hw/pci/virtio/virtio_i2c.c
Remove the possible NULL pointer access code for virtio-console.c
Add '\0' to end of native_patch[], to avoid the potential issue when
using %s to print the array for virtio-i2c.c
Tracked-On: #3467
Reviewed-by: Yonghua Huang <Yonghua.huang@intel.com>
=> dm: array bound and NULL pointer issue fix

hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/cpu_caps.c, hypervisor/arch/x86/mmu.c, hypervisor/boot/cmdline.c, hypervisor/boot/guest/deprivilege_boot.c, hypervisor/debug/console.c, hypervisor/debug/uart16550.c, hypervisor/include/arch/x86/pgtable.h, hypervisor/include/debug/uart16550.h, hypervisor/release/uart16550.c
v2:
Change uart_base_address to host virtual address so that APIs doesn't need to do hpa2hva conversion for MMIO cases. And uart16550_init can achieve the different va per early boot.
v1:
Now if we configure platform ram size wrong, the platform may panic without any
warnning, enable early boot uart could help us to find why is the system goes
weird. And we should do hardware support detection as early as possible. However,
without early boot uart, the unsupported platform will hang silently too.
This serial try to enable uart when early boot and use printf to debug when there's
something wrong.
=> Uart: enable early boot uart for debugging

hypervisor/arch/x86/cpu.c, hypervisor/include/arch/x86/cpu.h
monitor/mwait is used to wait for the specific write op from the other CPUS. It will firstly check whether the condition is expected before entering monitor/mwait. If it is not expected, monitor and mwait will be executed.
But if the write happens between check and monitor, it will have the possible lockup.
This is to fix the race condition of monitor/mwait in wait_sync_change
=> The race condition pf monitor/mwait in wait_sync_change

hypervisor/arch/x86/guest/pm.c, hypervisor/arch/x86/guest/vcpu.c, hypervisor/arch/x86/guest/vlapic.c, hypervisor/arch/x86/guest/vm.c, hypervisor/dm/vpic.c, hypervisor/include/arch/x86/guest/vcpu.h
After "commit f0e1c5e init vcpu host stack when reset vcpu", SOS resume form S3
wants to schedule to vcpu_thread not the point where SOS enter S3. So we should
schedule to idel first then reschedule to execute vcpu_thread.
Tracked-On: #3387
=> hv: schedule: schedule to idel after SOS resume form S3

devicemodel/hw/pci/virtio/virtio_console.c
when stdio is set as a virtio-console, guest run in backend, the open
file descriptor is not referring to a terminal.
Tracked-On: #3473
=> dm: bugfix for remote launch guest issue

hypervisor/dm/vpci/pci_pt.c, hypervisor/dm/vpci/vmsi.c, hypervisor/dm/vpci/vmsix.c, hypervisor/dm/vpci/vpci.c, hypervisor/dm/vpci/vpci_priv.h
Clean up vpci code introduced by vdev ops and enabling vhostbridge for sos:
Remove redundant function calling:
The caller function has already done the checking to make sure the req is targeted
for the called functions, so there is no need to do the same checking in called
functions.
Make functions void because their return values are always 0 and are not used.
=> More vpci cleanup

doc/Makefile, doc/developer-guides/hld/virtio-net.rst, doc/tutorials/docbuild.rst
PR #3483 cleaned up the project root folder and moved stuff that was in
/tools into a new /misc folder.  There were a few references to
the old /tools folder missed in that update, addressed in this PR.
=> doc: fix issues from moving tools to misc/tools

devicemodel/core/monitor.c, misc/acrn-manager/acrn_vm_ops.c, misc/acrn-manager/acrnctl.c, misc/acrn-manager/acrnctl.h, misc/acrn-manager/acrnd.c
Run 'acrnctl stop VM_NAME --force‘ to force stop VM
When run 'acrnctl stop VM_NAME', acrn-dm let guest OS to shutdown
itself. If something wrong with guest OS, it can't shutdown, we can
run 'acrnctl stop VM_NAME --force', thus acrn-dm directly set suspend
mode to VM_SUSPEND_POWEROFF and quit main loop.
Tracked-On: #3484
=> Acrnctl support force stop VM

hypervisor/lib/string.c
In lib/string.c, strncmp doesn't consider condition "n_arg=0",
just add a process to "n_arg=0".
Tracked-On: projectacrn/acrn-hypervisor#3466
Signed-off-by: YanX Fu <yanx.fu@intel.com>
Acked-by: Dong Eddie <eddie.dong@intel.com>
=> acrn-hv: code review fix lib/string.c

hypervisor/hw/pci.c
To fix below err format:
"%s" is used to output 'secondary_bus' with type of 'uint8_t'
=> hv: fix debug message format in 'init_pci_pdev_list'

devicemodel/hw/pci/xhci.c, devicemodel/hw/platform/usb_pmapper.c
Fix Potential NULL pointer deference and
buffer overflow issues on DM.
Tracked-On: #3434
=> dm: Fix potential NULL pointer deference and buffer overflow issues

misc/acrn-config/README, misc/acrn-config/board_config/README, misc/acrn-config/board_config/acpi_platform_h.py, misc/acrn-config/board_config/board_c.py, misc/acrn-config/board_config/board_cfg_gen.py, misc/acrn-config/board_config/board_cfg_lib.py, misc/acrn-config/board_config/pci_devices_h.py, misc/acrn-config/launch_config/README, misc/acrn-config/library/hypervisor_license, misc/acrn-config/scenario_config/README, misc/acrn-config/target/README, misc/acrn-config/target/acpi.py, misc/acrn-config/target/board_parser.py, misc/acrn-config/target/clos.py, misc/acrn-config/target/dmar.py, misc/acrn-config/target/dmi.py, misc/acrn-config/target/parser_lib.py, misc/acrn-config/target/pci_dev.py
1.   acrn-config: generate board information on target board
These tools run on the target board and genearate board information.
usage: python3 board_parser.py <board_name> [--out board_info_file]
sample:
$ sudo python3 board_parser.py apl-up2
v1-v2:
1. allow board parameter for new board
v2-v3:
1. add the usage descriptions for tools
2. add description of kernel cmd line for README
3. output informations to a xml type
4. coding as PEP8 guildline
2.    acrn-config: generate a patch and apply to acrn-hypervisor
the script will parser the the board information which already generated on
target board, and apply to the acrn-hypervisor as a patch.
usage: board_cfg_gen.py --board <board_info_file>
sample:
$ python3 board_cfg_gen.py --board ../target_board/board_info.xml
v1-v2:
1. allow to …
=> Acrn config tools

Makefile, hypervisor/Makefile
Add to include acrn.32.out during cl rpm
generation as acrn.(board).efi.32.out
This is required for Hybrid mode bringup in multios
Tracked-On: #3487 
Signed-off-by: Nikhil Rane <nikhil.rane@intel.com>
=> Makefile: Add install for uefi firmware

hypervisor/arch/x86/guest/vmcs.c, hypervisor/arch/x86/guest/vmsr.c
The policy of vART is that software in native can run in
VM too. And in native side, the relationship between the
ART hardware and TSC is:
pTSC = (pART * M) / N + pAdjust
The vART solution is:
- Present the ART capability to guest through CPUID leaf
15H for M/N which identical to the physical values.
- PT devices see the pART (vART = pART).
- Guest expect: vTSC = vART * M / N + vAdjust.
- VMCS.OFFSET = vTSC - pTSC = vAdjust - pAdjust.
So to support vART, we should do the following:
1. if vAdjust and vTSC are changed by guest, we should change
VMCS.OFFSET accordingly.
2. Make the assumption that the pAjust is never touched by ACRN.
For #1, commit "a958fea hv: emulate IA32_TSC_ADJUST MSR" has implementation
it. And for #2, acrn never touch pAdjust.
--
v2 -> v3:
- Add comment when handle …
=> HV: Enable vART support by intercepting TSC_ADJUST MSR

hypervisor/arch/x86/guest/vcpuid.c, hypervisor/include/arch/x86/guest/vcpuid.h
In some case, guest need to get more information under virtual environment,
like guest capabilities. Basically this could be done by hypercalls, but
hypercalls are designed for trusted VM/SOS VM, We need a machenism to report
these information for normal VMs. In this patch, vCPUID leaf 0x40000001 will
be used to satisfy this needs that report some extended information for guest
by CPUID.
Tracked-On: #3498
=> HV: return extended info in vCPUID leaf 0x40000001

README.rst
The URL for the "Getting Started Guide" needs to be updated. This patch fixes this.
Fixes #3509 
Signed-off-by: Alex Merritt <mail@alexmerritt.us>
=> README: Fix Getting Started URL

hypervisor/scenarios/hybrid/vm_configurations.c
In hybrid mode, pre-launched VM should have the highest severity to
handle platform reset, the flag should not be set in SOS VM;
Tracked-On: #3505
=> HV: fix highest severity flag in hybrid mode

doc/develop.rst, doc/index.rst, doc/try.rst
Home page "button" links needed to be manually updated (because of the
raw html usage) after content around.
Move partition mode docs from try to develop persona pages.
=> doc: fix broken links after content reorg

doc/static/acrn-custom.css
The ACRN icon on the new graphical home page looked fine with firefox,
edge, and chrome browsers, but not on IE.  This PR fixes that
=> doc: fix image proportions on home page for ie

misc/efi-stub/clearlinux/acrn.conf
acrn.conf:add memmap phys-addr 2M for hvlog,
not mapped by kernel.
Tracked-On: projectacrn/acrn-hypervisor#3533
Signed-off-by: YanX Fu <yanx.fu@intel.com>
=> memmap:reserve phys-addr for hvlog

doc/developer-guides/sw_design_guidelines.rst, doc/tutorials/using_partition_mode_on_up2.rst, hypervisor/Makefile, hypervisor/arch/x86/configs/apl-mrb/pci_devices.h, hypervisor/arch/x86/configs/dnv-cb2/pci_devices.h, hypervisor/arch/x86/configs/nuc7i7dnb/pci_devices.h, hypervisor/arch/x86/configs/pci_dev.c, hypervisor/arch/x86/guest/vm.c, hypervisor/common/hypercall.c, hypervisor/dm/vpci/pci_pt.c, hypervisor/dm/vpci/vpci.c, hypervisor/dm/vpci/vpci_priv.h, hypervisor/hw/pci.c, hypervisor/include/arch/x86/pci_dev.h, hypervisor/include/arch/x86/vm_config.h, hypervisor/include/dm/vpci.h, hypervisor/include/hw/pci.h, hypervisor/scenarios/logical_partition/pt_dev.c, hypervisor/scenarios/logical_partition/vm_configurations.c
v5:
revert "update find_vdev logic for SOS by PCI vBDF number"
v4:
1) refine PCI device type by adding PCI_DEV_TYPE_PTDEV, PCI_DEV_TYPE_HVEMUL, PCI_DEV_TYPE_SOSEMUL
2) make fill_pci_dev_config more readable
3) update find_vdev logic for SOS by PCI vBDF number
v3:
Build a global PCI device configure which doesn't contain pre-launched VM PT devices.
And assign it to SOS if there's a SOS.
v2:
Build PCI configure in VM configure for SOS to align with pre-launched VM to initialize
vPCI devices for guest.
Li, Fei1 (4):
hv: vpci: rename ptdev_config to pci_dev_config
hv: vm_config: build pci device configure for SOS
hv: vpci: refine init_vdevs
hv: vpci: create iommu domain in vpci_init for all guests
=> Vpci: refine init_vdevs

devicemodel/hw/pci/virtio/virtio_i2c.c
If failed to create native_adapter, free allocated native_adapter memory before return.
Tracked-On: #3543
Signed-off-by: Yifan Luo <luoyifan@cmss.chinamobile.com>
=> dm: virtio-i2c: fix native_adapter memory leak

hypervisor/debug/shell.c
String buffer temp_str is defined with size TEMP_STR_SIZE(60U) but accessed with MAX_STR_SIZE(256U). Better to limit the access bound to TEMP_STR_SIZE to prevent potential issue.
Tracked-On: #3549
Signed-off-by: Yifan Luo <luoyifan@cmss.chinamobile.com>
=> HV: shell: fix temp_str out of bounds buffer access

hypervisor/Makefile
now the dependency is like this in Makefile:
acrn.bin << xxxx.a << xxxx.obj
if excute 'make' in hypervsior fold for the first time,
it can generate acrn.bin, if excute 'make' for second
time, it can not do the final link because there are
the same timestamp for acrn.bin and xxxx.a generated by
previous build, add PHONY to fix this issue.
Tracked-On: #3542
=> hv:fix need to make twice in hypervisor folder

hypervisor/Makefile, hypervisor/arch/x86/configs/pci_dev.c, hypervisor/arch/x86/guest/vm.c, hypervisor/dm/vpci/vhostbridge.c, hypervisor/dm/vpci/vpci.c, hypervisor/include/arch/x86/pci_dev.h, hypervisor/include/arch/x86/vm_config.h, hypervisor/include/dm/vpci.h, hypervisor/scenarios/hybrid/vm_configurations.c, hypervisor/scenarios/industry/vm_configurations.c, hypervisor/scenarios/logical_partition/pci_dev.c, hypervisor/scenarios/logical_partition/vm_configurations.c, hypervisor/scenarios/logical_partition/vm_configurations.h, hypervisor/scenarios/sdc/vm_configurations.c, hypervisor/scenarios/sdc2/vm_configurations.c
v2:
Use vm_config directly instead of the internal configure data when accessing vm configure.
Here we should access SOS pci device configure through the SOS vm configure, not the global
sos_pci_devs.
v1:
Add a field (vdev_ops) in struct acrn_vm_pci_dev_config to configure a PCI CFG
operation for an emulated PCI device. Use pci_pt_dev_ops for PCI_DEV_TYPE_PTDEV
by default if there's no such configure.
Li, Fei1 (2):
hv: vpci: add emulated PCI device configure for SOS
hv: vpci: add each vdev_ops for each emulated PCI device
=> vpci: add support for customizing special pci operations for each emulated PCI device

hypervisor/arch/x86/configs/pci_dev.c, hypervisor/dm/vpci/vdev.c, hypervisor/dm/vpci/vpci.c, hypervisor/dm/vpci/vpci_priv.h, hypervisor/include/dm/vpci.h, hypervisor/scenarios/hybrid/vm_configurations.c
Post-launched VM should use itself vdev, not the vdev in SOS's structure.
Li, Fei1 (2):
hv: vpci: split vPCI device from SOS for post-launched VM
hv: vpci: remove pBDF configure for emulated device
=> Vpci: split vPCI device from SOS for post-launched VM

Makefile
The top-level Makefile white-lists ``BOARD``s to generate UEFI executable by default, but more UEFI BOARDs have been supported since then. As a result, the build instructions in existing documents may not be sufficient for those new ``BOARD`` targets, if the reader misses to supply the ``FIRMWARE`` variable while building the hypervisor.
Instead of adding new UEFI BOARD types using the original long **if-else** statements, I'd like to propose to white-list SBL BOARD types, and add the new SBL BOARD types to the list while needed. The Makefile will generate ``acrn.efi`` for non-white-listed SBL boards by default.
Tracked-On: #3541
=> make: white-list SBL firmware boards

hypervisor/Makefile
Hardcode "RELEASE=0" will cause the value of "CONFIG_RELEASE"
to be 'n' in kconfig.mk, it will be overwritten "CONFIG_RELEASE"
with Kconfig setting.
Tracked-On: #3565
=> hv: fix failed to build release version build with Kconfig setting

hypervisor/arch/x86/guest/vmcs.c, hypervisor/arch/x86/guest/vmsr.c, hypervisor/include/arch/x86/guest/vmcs.h
This patch moves vmx_rdmsr_pat/vmx_wrmsr_pat from vmcs.c to vmsr.c,
so that these two functions would become internal functions inside
vmsr.c.
This approach improves the modularity.
v1 -> v2:
* remove 'vmx_rdmsr_pat'
* rename 'vmx_wrmsr_pat' with 'write_pat_msr'
=> hv: move vmx_rdmsr_pat/vmx_wrmsr_pat from vmcs.c to vmsr.c

devicemodel/samples/nuc/launch_win.sh
This patch is used to expand WaaG memory from 2G to 4G in launch script.
Tracked-On: #3576
=> dm: expand default WaaG memory to 4G

devicemodel/include/sw_load.h, hypervisor/arch/x86/configs/vm_config.c, hypervisor/arch/x86/configs/vmptable.c, hypervisor/arch/x86/guest/assign.c, hypervisor/arch/x86/guest/instr_emul.c, hypervisor/arch/x86/guest/pm.c, hypervisor/arch/x86/guest/vcpu.c, hypervisor/arch/x86/guest/vlapic.c, hypervisor/arch/x86/irq.c, hypervisor/include/arch/x86/guest/vcpu.h, hypervisor/include/arch/x86/guest/vlapic.h, hypervisor/include/arch/x86/per_cpu.h
fix violations touched below:
1.Cast operation on a constant value
2.signed/unsigned implicity conversion
3.return value unused.
V1->V2:
1.bitmap api will return boolean type, not need to check "!= 0", deleted.
2.The behaves ~(uint32_t)X and (uint32_t)~X are not defined in ACRN hypervisor Coding Guidelines,
removed the change of it.
=> hv: fix Violations touched ACRN Coding Guidelines

doc/introduction/index.rst
While we internally call the "new" ACRN architecture 2.0, it could be
confusing to users since we also are calling the upcoming release v1.2
and there is no 2.0 release yet.  Remove references to 2.0 in the
introduction.
=> doc: remove references to 2.0 in intro

hypervisor/arch/x86/guest/pm.c, hypervisor/arch/x86/guest/vm_reset.c, hypervisor/dm/io_req.c, hypervisor/dm/vpci/vpci.c, hypervisor/dm/vpic.c, hypervisor/dm/vrtc.c, hypervisor/dm/vuart.c, hypervisor/include/dm/io_req.h
From the view of port i/o handler, struct acrn_vm * pointer
is redundant as input, as context of acrn_vm is aleady linked
in struct acrn_vcpu * by vcpu->vm, 'vm' is not required as input.
this patch removes argument '*vm' from 'io_read_fn_t' &
'io_write_fn_t', use '*vcpu' for them instead.
=> hv: refine the function pointer type of port I/O request handlers

doc/static/js/modernizr.min.js
modernizr.min.js is no longer used by Sphinx's rtd theme and is causing
some browsers to have a noticable flash when pages are loaded. While we
can't easily remove it from the RTD theme, we can replace the script
with an empty file instead.
=> doc: remove modernizr.min.js

devicemodel/samples/nuc/launch_uos.sh
OVMF will open source for V1.2, so enable launch LaaG with OVMF.
Tracked-On: #3506
=> HV: switch launch LaaG with OVMF by default

hypervisor/scenarios/industry/vm_configurations.c
Enable console vuart for the reset of VMs in industry scenario.
Tracked-On: #3370
=> hv: enable console vuart in industry scenario

hypervisor/arch/x86/guest/pm.c, hypervisor/arch/x86/guest/vm_reset.c, hypervisor/dm/vpci/vpci.c, hypervisor/dm/vpic.c, hypervisor/dm/vrtc.c, hypervisor/dm/vuart.c, hypervisor/include/dm/io_req.h
Currently, 'flags' is defined and set but never be used
in the flow of handling i/o request after then.
=> hv: remove 'flags' field in struct vm_io_range

hypervisor/arch/x86/guest/vcpu.c, hypervisor/common/vm_load.c, hypervisor/include/arch/x86/guest/vcpu.h
Now, we use native gdt saved in boot context for guest and assume
it could be put to same address of guest. But it may not be true
after the pre-launched VM is introduced.
This patch is used to put the init gdt by following
kernel/bootarg/ramdisk images. Which should be safe for any guest
configuration.
Tracked-On: #3532
=> vm_load: update init gdt preparation

devicemodel/samples/apl-up2/launch_uos.sh, doc/tutorials/partition_desc.ini, hypervisor/arch/x86/configs/apl-up2/misc_cfg.h, hypervisor/arch/x86/configs/apl-up2/ve820.c
- set sos root dev of apl-up2 to mmcblk0p3;
- prepare ve820 table to enable prelaunched VM for apl-up2 board;
Tracked-On: #3214
=> HV: enable hybrid for apl up2 uefi board

devicemodel/core/main.c, doc/user-guides/acrn-dm-parameters.rst
ACRN-DM does not support "pincpu" option to pin 'vcpu' to 'hostcpu', ACRN support vcpu to pcpu static mapping
via vm_config.
This commit removes the "pincpu" option.
Tracked-On: #3598
=> dm: remove unsupported "pincpu" option

hypervisor/acpi_parser/acpi_ext.c, hypervisor/arch/x86/guest/vm_reset.c, hypervisor/arch/x86/pm.c, hypervisor/include/arch/x86/guest/vm_reset.h, hypervisor/include/arch/x86/host_pm.h
move some data structures and APIs related host reset
from vm_reset.c to pm.c, these are not related with guest.
=> hv:move some APIs related host reset to pm.c

hypervisor/arch/x86/cpu_caps.c, hypervisor/arch/x86/guest/guest_memory.c, hypervisor/arch/x86/guest/vmsr.c, hypervisor/common/hypercall.c, hypervisor/include/arch/x86/cpu.h, hypervisor/include/arch/x86/guest/vcpu.h, hypervisor/include/arch/x86/guest/vmcs.h, hypervisor/include/arch/x86/msr.h
-- move 'RFLAGS_AC' to cpu.h
-- move 'VMX_SUPPORT_UNRESTRICTED_GUEST' to msr.h
and rename it to 'MSR_IA32_MISC_UNRESTRICTED_GUEST'
-- move 'get_vcpu_mode' to vcpu.h
-- remove deadcode 'vmx_eoi_exit()'
=> hv: cleanup vmcs.h

hypervisor/arch/x86/guest/trusty.c, hypervisor/arch/x86/guest/vm.c, hypervisor/arch/x86/mmu.c, hypervisor/arch/x86/page.c, hypervisor/arch/x86/pagetable.c, hypervisor/arch/x86/vtd.c, hypervisor/include/arch/x86/mmu.h, hypervisor/include/arch/x86/page.h, hypervisor/include/arch/x86/pgtable.h, hypervisor/include/arch/x86/vtd.h
Some VT-d hardware implementation doesn't support page-walk coherency. When the translation table entries are modified,
the cacheline of the entries should be flushed, so that the modificiation is visible to VT-d hardware.
In current code, VT-d shares the EPT table of a VM, considering no GPA to HPA mapping change after VM started, hypervisor
globally invalidate cache per VM when creating the VM.
However, when RTVM in industry scenario is introduced, a global cache invalidation may affect the cache usage of RTVM.
The patch series flush cacheline on EPT entry change, and remove the global cache invalidation per VM.
Tracked-On: #3607
=> Flush CPU cacheline on EPT entry change for VT-d

devicemodel/hw/platform/usb_pmapper.c
Fix potential risk to crash due to null pointer.
Tracked-On: #3612
=> DM USB: fix potential crash risk due to null pointer

devicemodel/hw/pci/virtio/virtio_console.c
Add subclass for virtio-console pci device. Without the subclass, the
device may be probed by 8250_pci serial driver,  and lead to segment
fault in acrn-dm. This issue appears when running debian as Guest OS.
But there is a potential issue, if a new serial driver, which use class
and subclass same as virtio-console, the problem may still trigger. Need
to fix it case by case.
Tracked-On: #3615
=> dm: virtio-console: add subclass

Makefile, hypervisor/Makefile, misc/efi-stub/Makefile
We are trying to add both industry and sdc images to CL build. To
maintain the build interface unchanged (no change from CL side), we
extend the build command to generate the different target images.
To identity different images, we use rule:
$(HV_FILE).$(BOARD).$(FIRMWARE).$(SCENARIO)
as target image file name.
Tracked-On: #3593
=> Makefile: Refine Makefile to generate both industry and sdc images

devicemodel/core/main.c
Change hardcode of vcpu number to the real value when process VM's IO
request in DM, so we can handle all requests from different vcpus.
Tracked-On: #3425
=> dm: support VM running with more than 4 vcpus

hypervisor/arch/x86/cat.c, hypervisor/arch/x86/guest/vcpu.c, hypervisor/arch/x86/guest/vmcs.c, hypervisor/arch/x86/guest/vmsr.c, hypervisor/include/arch/x86/cat.h, hypervisor/include/arch/x86/cpu.h, hypervisor/include/arch/x86/guest/vcpu.h
Currently, the clos id of the cpu cores in vmx root mode is the same as non-root mode.
For RTVM, if hypervisor share the same clos id with non-root mode, the cacheline may
be polluted due to the hypervisor code execution when vmexit.
The patch adds hv_clos in vm_configurations.c
Hypervisor initializes clos setting according to hv_clos during physical cpu cores initialization.
For RTVM,  MSR auto load/store areas are used to switch different settings for VMX root/non-root
mode for RTVM.
=> hv: cat: isolate hypervisor from rtvm

hypervisor/arch/x86/guest/virq.c, hypervisor/arch/x86/mmu.c, hypervisor/include/arch/x86/mmu.h, hypervisor/include/arch/x86/pgtable.h
change the input parameter from *vcpu to *eptp in order to let this api
more generic, no need to care normal world or secure world.
=> hv:change function parameter for invept

doc/getting-started/building-from-source.rst
Add 'zlib1g-dev' to the list of build tools and dependencies to be installed
in Debian in order to build the ACRN project.
=> doc: add 'zlib1g-dev' to list of dependencies in Debian

doc/glossary.rst
Add three new glossaries: "Hybrid Mode", "Partition Mode", "Sharing Mode".
=> doc: Add three new glossaries

misc/acrn-manager/README.rst
Add the new and optional "-f/--force" flag to the 'acrnctl'
documentation.
=> doc: add "-f/--force' optional arg to 'acrnctl' documentation

hypervisor/dm/io_req.c
As the pr_dbg will access sbuf which will call stac/clac inside, so can
not put pr_dbg between stac/clac, it will case Page Fault.
acrn_print_request is a debug feature, and it calls pr_dbg. when the
loglevel is set to 6, there will be Page Fault.
So, remove the caller for acrn_print_request and mask the function as
unused, reserved for debug.
Tracked-On: #3648
=> hv: remove pr_dbg between stac/clac

devicemodel/core/sw_load_common.c, devicemodel/include/sw_load.h
Add 16M@0xDF000000 for GVT usage as below. Currently, use 8M for GOP
framebuf, it satisfies display resolution of 1920x1080@32bpp
start         end          size    Note
[0x 00000000, 0x 000A0000] 640K
[0x 000A0000, 0x 00100000] 384K
[0x 00100000, 0x 7ff00000] 2G-1M   lowmem-1M
[0x 80000000, 0x 88000000] 128M    [lowmem, +128M]
[0x DF000000, 0x E0000000] 16M     *gvt*
[0x e0000000, 0x100000000] 512M
[0x100000000, 0x140000000] 1G
*gvt*:
[0xDF000000, 0xDF800000] 8M      GOP FB
[0xDFFFD000, 0XE0000000] 12K     opregion
Tracked-On: #3624
Signed-off-by: Liu Xinyun <xinyun.liu@intel.com>
=> dm: reserve 16M hole for gvt in e820 table

CODEOWNERS
Add Nanlin (@NanlinXie) as a reviewer for ACRN documentation.
Add Terry and Shuang (@terryzouhao @szhen11) as the reviewers for misc component.
=> doc: update CODEOWNERS for doc, misc reviews

hypervisor/arch/x86/cpu.c, hypervisor/include/arch/x86/guest/vcpu.h
pcpu_active_bitmap was read continuously in wait_pcpus_offline(),
acrn_vcpu->running was read continuously in pause_vcpu(),
add volatile keyword to ensure that such accesses are not
optimised away by the complier.
=> hv:add volatile keyword for some variables

hypervisor/arch/x86/pagetable.c
1) add strict check for adding page table mapping to stop guest re-program conflict PCI BAR region
2) remove strict check for deleting page table mapping to support guest delete a PCI BAR more than once
=> Vpci: adjust EPT APIs to support guest re-program PCI BAR

devicemodel/core/main.c
Remove the '-p' ("pincpu" option) from the help displayed when calling 'acrn-dm
-h'.
Tracked-On: #3600
=> dm: remove '-p' option from the embedded help

.gitignore
Update the .gitignore file to reflect the fact that the tools are now located
under misc/ and no longer under tools/.
One of the temporary folder created during the documentation generation was
doc/tools and it was therefore ignored by Git. It is now better to *not*
ignore it as it will cause documention build issues if such previous folder
exists.
=> doc: update .gitignore to reflect the new location of the tools

doc/user-guides/acrn-dm-parameters.rst
Add the '--logger_setting' parameter information to the 'acrn-dm' parameter
document.
=> doc: add 'logger_setting' parameter information to acrn-dm documentation

hypervisor/dm/vpci/pci_pt.c, hypervisor/dm/vpci/vpci.c, hypervisor/hw/pci.c, hypervisor/include/hw/pci.h
1) PCI BAR physical base address will never changed. Cache it to avoid calculating
it every time when we access it.
2) vPCI device should use its virtual configure space to access its BAR after vPCI
device initialized.
This patch also remove corner case "vPCI device will use its 64 bits BAR high idx
to access its BAR base address".
=> Vpci: refine vPCI device BAR access

misc/acrn-config/config_app/app.py, misc/acrn-config/config_app/configs.py, misc/acrn-config/config_app/controller.py, misc/acrn-config/config_app/requirements, misc/acrn-config/config_app/static/main.js, misc/acrn-config/config_app/static/styles.css, misc/acrn-config/config_app/templates/base.html, misc/acrn-config/config_app/templates/launch.html, misc/acrn-config/config_app/templates/scenario.html, misc/acrn-config/config_app/views.py
The web UI application for ACRN VM configuration tool based on Flask web framework:
1. import board info xml which is generated by acrn-config/target on target boards; or select one
board from the imported list of UI.
2. load scenario settings or import scenario settings from local.
3. edit scenario settings from web UI.
4. export and save the edited scenario setting, the application will prompt error messages from UI
if there are illegal configured items.
5. generate board source code, generate scenario source code.
6. load launch settings or import launch settings from local.
7. edit launch settings from web UI.
8. export and save the edited launch setting; the application will prompt error messages from UI
if there are illegal configurable items
9. generate launch scripts based on …
=> acrn-config: web UI app for acrn-config tool

hypervisor/arch/x86/configs/nuc7i7dnb/platform_acpi_info.h
Currently nuc7i7dnb board is using default platform acpi info file so causes
S3/S5 not working properly.
This patch updates the correct ACPI info for nuc7i7dnb board.
Tracked-On: #3609
=> HV: add acpi info header for nuc7i7dnb

devicemodel/Makefile, devicemodel/core/main.c, devicemodel/core/monitor.c, devicemodel/core/pm_vuart.c, devicemodel/hw/platform/ioc.c, devicemodel/hw/platform/pty_vuart.c, devicemodel/include/pm_vuart.h, devicemodel/include/pty_vuart.h, devicemodel/samples/nuc/launch_hard_rt_vm.sh, devicemodel/samples/nuc/launch_uos.sh, doc/user-guides/acrn-dm-parameters.rst
1. Separate pty master/slave operation from IOC module 
2. Use pty in vuart (com2) for UOS S5; it register into vm-ops. when received UOS shutdown command, it will send "shutdown" to UOS,  and wait "acked" from UOS.
3. Add the setting into launch script for NUC platform
4. Update user guide.
Tracked-On: #3564
=> to support S5 through vuart

hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/guest/assign.c, hypervisor/arch/x86/guest/vm.c, hypervisor/common/ptdev.c, hypervisor/common/schedule.c, hypervisor/include/arch/x86/cpu.h, hypervisor/include/arch/x86/guest/vm.h, hypervisor/include/arch/x86/per_cpu.h, hypervisor/include/common/ptdev.h, hypervisor/include/common/schedule.h
hv: ptdev: move softirq_dev_entry_list from vm structure to per_cpu region
Using per_cpu list to record ptdev interrupts is more reasonable than
recording them per-vm. It makes dispatching such interrupts more easier
as we now do it in softirq which happens following interrupt context of
each pcpu.
Tracked-On: #3663
=> preparation for cpu sharing 

misc/life_mngr/life_mngr.c, misc/life_mngr/life_mngr.service
For cross-VM S5 notify via vUART, life_mngr service is running on UOS.
It is listening on /dev/ttyS1 to get SOS's commands.
The protocol is: SOS send "shutdown", UOS feedback "acked".
When SOS triggle shutdown, SOS can 1) check VM's status until UOS
stopped, 2) retry shutdown UOS normally with timeout.
So, no matter life_mngr server is running, SOS's shutdown procedure will
properly finish.
Tracked-On: #3564
Signed-off-by: fuyanX <yanx.fu@intel.com>
=> Misc: lifemngr-daemon-on-UOS

doc/acrn.doxyfile, hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/guest/assign.c, hypervisor/arch/x86/guest/trusty.c, hypervisor/arch/x86/guest/vcpu.c, hypervisor/arch/x86/guest/vmcs.c, hypervisor/arch/x86/pm.c, hypervisor/arch/x86/vtd.c, hypervisor/include/arch/x86/cpu.h, hypervisor/include/arch/x86/guest/vcpu.h, hypervisor/include/arch/x86/guest/vm.h, hypervisor/include/arch/x86/vtd.h, hypervisor/include/common/ptdev.h
these patches move down some structures from the upper-layer
to avoid  reversed dependency.
=> move down some structures to avoid reversed dependency

hypervisor/dm/vpci/vmsix.c, hypervisor/dm/vpci/vpci.c
1) a minor fix about handling vmsix table mmio access for post-launched VM
2) a minor fix about vpci_init_pt_dev
=> hv: vPCI: minor fix about the vPCI device

hypervisor/Makefile
commit 5d19962d removed O2 option improperly,
this patch re-enable it.
=> hv:enable the O2 option for HV

devicemodel/samples/nuc/launch_uos.sh
Adjust the 'launch_uos.sh' script used to start a LaaG User VM to user the
OVMF.fd bios file installed under /usr/share/acrn/bios. It currently points
at a file in the local folder but neither our instructions nor our installation
script file puts it in this location. That results in an error when you try
to launch it.
Tracked-On: #3673
=> DM: make LaaG launch script use the OVMF.fd from the Service VM

Makefile, hypervisor/Makefile, misc/efi-stub/Makefile
1. if SCENARIO=$(SCENARIO) is specified in make param, then override
the default CONFIG_$(SCENARIO) value in existed .config. This means
we don't need to modify the default SCENARIO config in Kconfig file
to build the hypervisor;
2. Some board name shortcuts like apl-nuc/kbl-nuc-i7 need to be converted
to official board name to make sure overrides working;
3. Previously make sbl-hypervisor did not load the defconfig so the
defconfig for boards are lost, this patch fix this issue;
4. remove SCENARIO param when make hypervisor, because SCENARIO could
be got from SCENARIO_NAME which parsed from .config;
Tracked-On: #3593
=> Makefile: override .config with specified scenario

hypervisor/arch/x86/cat.c, hypervisor/arch/x86/cpu_caps.c, misc/acrn-manager/acrnctl.c
CPUID(EAX = 10H, ECX = ResID=1 or 2).EAX Bits 04 - 00: Length of the capacity bit mask for the corresponding ResID using minus-one notation
The Extended Model ID needs to be examined only when the Family ID is 06H or 0FH
check_name function, print info error
Tracked-On:#3675
Signed-off-by: Andy andyx.liu@intel.com
=> fix cbm length calculation, Extended model judge,  print info error

hypervisor/arch/x86/pm.c, hypervisor/include/arch/x86/per_cpu.h
TSC would be reset to 0 when enter suspend state on some platform.
This will fail the secure timer checking in secure world because
secure world leverage the TSC as source of secure timer which should
be increased monotonously.
This patch save/restore TSC in host suspend/resume path to guarantee
the mono increasing TSC.
Note: There should no timer setup before TSC resumed.
Tracked-On: #3697
=> hv: save/restore TSC in host's suspend/resume path

devicemodel/samples/nuc/launch_hard_rt_vm.sh
The default script is for nvme passthrough to RT_LaaG; you can change it
to sata or using virtio_blk
Tracked-On: #3506
Reviewed-by: binbin.wu@intel.com; kaige.fu@intel.com
=> dm: switch to launch RT_LaaG with OVMF by default

hypervisor/dm/vpci/pci_pt.c, hypervisor/hw/pci.c, hypervisor/include/hw/pci.h
Initialize vBAR configure space when doing vPCI BAR initialization. At this time,
we access the physical device as we needs, no need to cache physical PCI device
BAR information beforehand.
=> hv: vpci: refine vPCI BAR initialization

misc/acrn-config/xmls/board-xmls/apl-up2-n3350.xml, misc/acrn-config/xmls/board-xmls/apl-up2.xml, misc/acrn-config/xmls/config-xmls/apl-up2-n3350/logical_partition.xml, misc/acrn-config/xmls/config-xmls/apl-up2-n3350/sdc_launch_1uos_laag.xml, misc/acrn-config/xmls/config-xmls/generic/hybrid.xml, misc/acrn-config/xmls/config-xmls/generic/industry.xml, misc/acrn-config/xmls/config-xmls/generic/sdc.xml, misc/acrn-config/xmls/config-xmls/generic/sdc2.xml
Currently the default apl-up2 board xml is for ATOM-N3350 variant, change it to ATOM-N4200 which is a 4 cores variant.
=> acrn-config: change default apl up2 support to N4200

hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/cpu_caps.c, hypervisor/common/hypercall.c, hypervisor/common/trusty_hypercall.c, hypervisor/debug/hypercall.c, hypervisor/debug/profiling.c, hypervisor/include/arch/x86/cpu.h
-- remove redundant memset in some cases
-- fix violation for variable-length arry
=> fix_variable_length_array_violation

CODEOWNERS
Folder names need to end with a slash
Tracked-On: #3723
=> fix foldernames in CODEOWNERS

misc/efi-stub/Makefile
To be back compatible, the default acrn.efi should be built when
BOARD param is nuc6cayh, because apl-nuc was overridden to nuc6cayh
in acrn-hypervisor/Makefile;
=> Makefile: build default acrn.efi with nuc6cayh

doc/getting-started/acrn_quick_setup.sh, doc/getting-started/apl-nuc.rst
1. From Clear Linux 31030, we could use kernel-iot-lts2018-sos kernel
command line as Service OS kernel command line directly, so update
the steps and codes to set the Service OS kernel command line.
2. Command "swupd verfiy" and the flag "-m" is superseded, use "swupd
repair" and the flag "-V" instead
3. As UOS is launched by OVMF, the old steps and code to set up UOS does
not work on Clear Linux 31030, update its related steps and code.
4. Update install Clear Linux steps.
5. Fix some small issues.
=> doc: update gsg and acrn_quick_setup.sh

doc/tutorials/create-up2-images.sh, doc/tutorials/using_sbl_on_up2.rst
1. Fix the broken link to download UP2 Board BIOS
2. In Clear Linux 31030 the acrn.apl-up2.sbl name is changed to
acrn.apl-up2.sbl.sdc.32.out, so we need to update the creaet-up2-imgages.sh
3. Command "swupd verify --install -m" has been superseded, use "swupd
os-install -V" instead.
=> update using_sbl_on_up2 doc and create-up2-images.sh

hypervisor/acpi_parser/dmar_parse.c, hypervisor/arch/x86/configs/pci_dev.c, hypervisor/arch/x86/guest/assign.c, hypervisor/arch/x86/vtd.c, hypervisor/common/hypercall.c, hypervisor/debug/shell.c, hypervisor/dm/vpci/vdev.c, hypervisor/include/hw/pci.h
- add one more filed in "union pci_bdf"
- remove following interfaces:
* pci_bus
* pci_slot
* pci_func
* pci_devfn
- update the argument type to union for function "bdf_is_equal"
Declaring argument as pointer is not necessary since it
only does the comparison.
=> hv: clean up pci

doc/getting-started/acrn_ootb.rst, doc/try.rst
This tutorial describes how to generate, deploy OOTB Service VM
RTVM image so that all of the users are able to use ACRN, boot
RTVM immediately after installation without any configuration or
modification.
=> doc: Use out-of-the-box image to boot ACRN RTVM

doc/scripts/publish-robots.txt
Exclude older documentation from search engines (< 1.0)
=> doc: update robots.txt to exclude old docs

devicemodel/hw/pci/xhci.c, devicemodel/hw/platform/usb_mouse.c, devicemodel/hw/platform/usb_pmapper.c, devicemodel/hw/usb_core.c, devicemodel/include/usb_core.h, devicemodel/include/usb_pmapper.h, devicemodel/include/xhci.h
This series of patches enable the isochronous transfer in Windows 10,
which supports devices such as USB headset, USB microphone and USB
camera.
Tracked-On: #3628
Signed-off-by: Xiaoguang Wu xiaoguang.wu@intel.com
=> Enable Isochronous transfer in Windows 10

doc/getting-started/acrn_quick_setup.sh, doc/getting-started/apl-nuc.rst
1. update clearlinux version to 31090
2. update acrn.efi name to acrn.nuc6cayh.sdc.efi
=> doc: update clearlinux version and acrn.efi name in GSG

doc/getting-started/acrn_ootb.rst
1. Update the Service OS VM default install disk to SATA, and Preempt-RT User
VM default install disk to NVMe.
2. Update the Launch Preempt-RT User VM setup.
=> doc: update acrn_ootb.rst

misc/acrn-config/xmls/config-xmls/apl-mrb/sdc_launch_1uos_aaag.xml, misc/acrn-config/xmls/config-xmls/apl-mrb/sdc_launch_1uos_aliaag.xml, misc/acrn-config/xmls/config-xmls/apl-mrb/sdc_launch_1uos_laag.xml, misc/acrn-config/xmls/config-xmls/apl-up2-n3350/sdc_launch_1uos_laag.xml, misc/acrn-config/xmls/config-xmls/apl-up2/sdc_launch_1uos_aaag.xml, misc/acrn-config/xmls/config-xmls/apl-up2/sdc_launch_1uos_laag.xml, misc/acrn-config/xmls/config-xmls/generic/hybrid_launch_1uos.xml, misc/acrn-config/xmls/config-xmls/generic/industry_launch_1uos.xml, misc/acrn-config/xmls/config-xmls/generic/industry_launch_2uos.xml, misc/acrn-config/xmls/config-xmls/generic/industry_launch_3uos.xml, misc/acrn-config/xmls/config-xmls/generic/sdc_launch_1uos.xml, misc/acrn-config/xmls/config-xmls/nuc6cayh/industry_launch_1uos_hardrt.xml, misc/acrn-config/xmls/config-xmls/nuc6cayh/industry_launch_1uos_vxworks.xml, misc/acrn-config/xmls/config-xmls/nuc6cayh/industry_launch_1uos_waag.xml, misc/acrn-config/xmls/config-xmls/nuc6cayh/industry_launch_2uos.xml, misc/acrn-config/xmls/config-xmls/nuc6cayh/industry_launch_3uos.xml, misc/acrn-config/xmls/config-xmls/nuc6cayh/sdc_launch_1uos_laag.xml, misc/acrn-config/xmls/config-xmls/nuc6cayh/sdc_launch_1uos_zephyr.xml, misc/acrn-config/xmls/config-xmls/nuc7i7dnb/industry_launch_1uos_hardrt.xml, misc/acrn-config/xmls/config-xmls/nuc7i7dnb/industry_launch_1uos_vxworks.xml, misc/acrn-config/xmls/config-xmls/nuc7i7dnb/industry_launch_1uos_waag.xml, misc/acrn-config/xmls/config-xmls/nuc7i7dnb/industry_launch_2uos.xml, misc/acrn-config/xmls/config-xmls/nuc7i7dnb/industry_launch_3uos.xml, misc/acrn-config/xmls/config-xmls/nuc7i7dnb/sdc_launch_1uos_laag.xml, misc/acrn-config/xmls/config-xmls/nuc7i7dnb/sdc_launch_1uos_zephyr.xml
align with sample launch script for Preempt-RT Linux, remove ethernet
device from config file.
Tracked-On: #3751
=> acrn-config: remove ethernet device from pass through config

doc/getting-started/acrn_ootb.rst, doc/getting-started/rt_industry.rst, doc/try.rst, doc/tutorials/using_cat_on_up2.rst
This tutorial is introducing how to build service vm, preempt_rt kernel and
industry scenario hypervisor; Update built kernel and launch the preempt_rt vm.
=> doc: Add introduction for using Preempt_RT VM with Industry scenario

Makefile
For history reason, we use targets: sbl-hypervisor, sbl-hypervisor-install
and sbl-hypervisor-install-debug to build/install default images.
To maintain the compatible with Clearlinux, we use these targets to build
all images we need as well.
This patchset refine the makefile and make it easy to add new images to
these targets.
=> Makefile refine

misc/acrn-config/board_config/pci_devices_h.py
Current python code could handle pci sub class name contain "-" as
expected, but some space characters may still exist. This patch support
to parse similar strings which contain "-" and ' ' for pci sub class name.
Also, add the index number as suffix for the similar strings
Tracked-On: #3788
=> acrn-config: fix pci sub class name contain "-" and ' '

devicemodel/core/main.c, devicemodel/hw/pci/virtio/virtio_block.c, devicemodel/hw/pci/virtio/virtio_input.c, devicemodel/hw/pci/virtio/virtio_net.c, devicemodel/include/dm.h, devicemodel/include/virtio.h, devicemodel/samples/nuc/launch_win.sh
After Windows 10, version 1607, the cross-signed drivers are forbiden
to load when secure boot is enabled.
Details please refer to
https://docs.microsoft.com/en-us/windows-hardware/drivers/install/kernel-mode-code-signing-policy--windows-vista-and-later-
That means the kvm-guest-drivers-windows can't work when secure boot enabled.
So we found another windows virtio FE drivers from Oracle to resolve this issue
but have to change another subsystem vendor ID for the virtio BE services.
This patch introduces a new DM CMD line "--windows" to launch WaaG with Oracle virtio devices including
virtio-blk, virtio-net, virtio-input instead Redhat. It can make virtio-blk, virtio-net and virtio-input
devices work when WaaG enabling secure boot.
Tracked-On: #3583
Signed-off-by: Yuan Liu …
=> dm: Add Oracle subsystem vendor ID

Makefile
In commit "d0489ef3b7efcd4feca0a5ee11b1fd4f9a88864a", try to
move the sbl-hypervisor target to function. But missed the
EFI_OBJDIR parameter for install/install-debug function.
Another problem is we use same EFI_OBJDIR for all uefi build.
We now put the EFI_OBJDIR to the build out to avoid this issue.
Acked-by: Binbin Wu <binbin.wu@intel.com>
=> makefile: fix efi stub install issue

hypervisor/common/hypercall.c
this patch is to fix error debug message
for invalid 'param' case, there is no string
variable for '%s' output, which will potenially
trigger hypervisor crash as it may access random
memroy address and trigger SMAP violation.
Tracked-On: #3801
=> hv: fix error debug message in hcall_set_callback_vector

hypervisor/dm/vpci/vmsi.c, hypervisor/hw/pci.c, hypervisor/include/hw/pci.h
The MSI Message Address and Message Data have no valid data after Power-ON. So
there's no need to initialize them by reading the data from physical PCI configuration
space.
=> hv: vpci: remove pci_msi_cap in pci_pdev

.gitignore, doc/Makefile, doc/scripts/filter-doc-log.sh
Modify the documentation Makefile (doc/Makefile) and scripts to only modify and
create content inside the $BUILDDIR folder.
The folders that were created inside 'doc/' previously are now all created
inside '$BUILDDIR/rst'. The '.gitignore' file has also been updated accordingly.
Tracked-On: #3686
=> doc: update doc generation tooling to only work within the $BUILDDIR

devicemodel/hw/pci/ahci.c, devicemodel/hw/pci/npk.c, devicemodel/hw/pci/virtio/virtio_block.c
int snprintf(char *str, size_t size, const char *format, ...)
The functions snprintf() write at most size bytes (including the
terminating null byte('\0')) to str.
only when returned value of snprintf is non-negative and less than size,
the string has been completely written.
Tracked-On: #3789
Signed-off-by: Junhao Gao <junhao.gao@intel.com>
=> dm: refine the check of return value of snprintf

devicemodel/hw/pci/gsi_sharing.c, devicemodel/hw/pci/virtio/virtio_mei.c
When removing node in list, list_foreach_safe will be safer than
LIST_FOREACH.
Tracked-On: #3778
Signed-off-by: Junhao Gao <junhao.gao@intel.com>
=> dm: reduce potential crash caused by LIST_FOREACH

doc/getting-started/Dockerfile, doc/getting-started/building_acrn_in_docker.rst
Optimize the size of the Clear Linux container that can be used to build ACRN.
This patch reduces the size of the container from approx. 10.8GB down to a
little less than 1.4GB.
=> doc: optimize Clear Linux "ACRN builder" container image

misc/acrn-config/launch_config/com.py, misc/acrn-config/launch_config/pt.py, misc/acrn-config/library/launch_cfg_lib.py
To match launch config xml, supply more optional passthrough device to
vm.
Tracked-On: #3812
=> acrn-config: supply optional passthrough device for vm

hypervisor/arch/x86/guest/vcpu.c, hypervisor/arch/x86/sched.S, hypervisor/common/hv_main.c, hypervisor/common/schedule.c, hypervisor/include/arch/x86/guest/vcpu.h, hypervisor/include/arch/x86/per_cpu.h, hypervisor/include/common/schedule.h
1. change naming   
prepare_switch_out -> switch_out
prepare_switch_in -> switch_in
prepare_switch -> do_switch
run_thread_t -> thread_t
sched_object -> thread_object
sched_object.thread -> thread_object.thread_entry
sched_obj -> thread_obj
sched_context -> sched_control
sched_ctx -> sched_ctl
2. remove runqueue from current schedule logic
3. move pcpu_id from acrn_vcpu to thread_object
=> change schedule related structs and vars naming for scheduler abstraction

devicemodel/hw/pci/npk.c
DIR handler is referenced after release, need to be adjusted before
released.
Tracked-On: #3821
=> dm: modify DIR handler reference postion

devicemodel/hw/pci/core.c
slot value should be checked in range before used to access
bi->slotinfo[].
Tracked-On: #3822
=> dm: validation for input to public functions

misc/acrn-config/board_config/board_cfg_gen.py, misc/acrn-config/config_app/static/main.js, misc/acrn-config/config_app/views.py, misc/acrn-config/launch_config/launch_cfg_gen.py, misc/acrn-config/library/common.py, misc/acrn-config/library/launch_cfg_lib.py, misc/acrn-config/scenario_config/scenario_cfg_gen.py
acrn-config: add confirmation for commit of generated source in config app
add a confirmation interface to let user to commit changes into local tree
or not commit after generated source codes in config app.
acrn-config: add "enable_commit" parameter for config tool
Config tool will generate files for board/scenaro/launch, some files are
part of souce code for specify board. Git add/commit these files should
be one optional of user experience. Add "--enable_commit" parameter to
enable git add/commit.
usage:
--enable_commit: flag of whether to do git commit the config file changes
to current git branch. Do commit with this flag and not do without the flag.
Tracked-On: #3834
Acked-by: Victor …
=> acrn-config: add confirmation for commit of generated source in config app

hypervisor/arch/x86/guest/vlapic.c
Consider the following case when TPR shadow is used with vlapic
basic mode:
1) 2 interrupts are pending in vlapic. INTa's priority > TPR and
INTb's priority <= TPR.
2) TPR threshold is set to zero and INTa is injected to guest.
3) Guest set TPR to the priority of INTa.
4) EOI of INTa. PPR is updated to TPR which equals INTa's priority.
INTb cannot be injected because its priority <= PPR.
5) Guest set TPR to zero. Because TPR threshold is still zero, there is
no TPR threshold vmexit. But since both TPR and ISRV are zero at
this time, the PPR is zero as well. INTb still cannot be injected.
This is a bug.
This patch adds one TPR threshold update in EOI to fix above issue.
Tracked-On: #3795
=> hv: fix a bug that tpr threshold is not updated

devicemodel/core/sw_load_elf.c
In acrn_load_elf(), file pointer 'fp' is kept in
open state after 'load_elf32()', this patch is to
fix this bug.
Tracked-On: #3817
=> dm: close filepointer before return from acrn_load_elf()
