bsp/uefi/efi/Makefile

Currently acrn.efi is installed to /usr/share, this PR changes the installation directory to /usr/share/acrn.
Even more the conf file was not installed, this PR install it to /usr/share/acrn/demo

Install efi and conf file to /usr/share/acrn

---

bsp/uefi/clearlinux/acrn.conf

acrn.efi is an EFI executable image and not a linux kernel image.
This commit changes linux to efi in the boot-loader configuration.
For more reference please review:
https://www.freedesktop.org/wiki/Software/systemd/systemd-boot/

use efi instead of linux in acrn.conf

---

Makefile

"-O2 -D_FORTIFY_SOURCE=2":
GCC C-Compiler can analyze the source code to be compiled and detect
certain insecure sections, that might create a security problem. The
compiler will replace the insecure function calls with special hardened
code that will perform extra runtime checks while the process is
executed.
"-Wformat -Wformat-security":
It warns about calls to "printf" and "scanf" functions where the format
string is not a string literal and there are no format arguments, as in
"printf (foo);". This may be a security hole if the format string came
from untrusted input and contains %n.
Tracked-On: 224003
Signed-off-by: wenshelx <wenshengx.wang@intel.com>

security: fortify source and format string check

---

arch/x86/interrupt.c
common/schedule.c
include/arch/x86/guest/vcpu.h
include/arch/x86/irq.h

And re-inject the event after vcpu is scheduled in.

apicv: cancel event injection if vcpu is scheduled out

---

arch/x86/ept.c
arch/x86/guest/vm.c
arch/x86/mmu.c
arch/x86/vmx.c
common/hypercall.c
include/arch/x86/guest/vm.h
include/arch/x86/hv_arch.h
include/arch/x86/trusty.h
include/public/acrn_common.h

add key info structure
add sworld_eptp in vm structure, and rename ept->nworld_eptp
add secure world control structure
Change-Id:
Tracked-On:220921

add data structure in vm for enable trusty feature

---

lib/mem_mgt.c
lib/memcpy.c
lib/strcpy.c
lib/strncpy.c

Replace ASSERT in lib functions with error message print and return a
value indicating error to allow the caller of lib functions to handle
the error.
Change-Id: If166484238dc0734041adfdbb19a5b374c044e33

Remove ASSERT in lib functions

---

Makefile
arch/x86/mmu.c
arch/x86/trusty.c

This patch is prepared for enabling secure world feature.
this api will create new eptp for secure world, whose PDPT
entries are copied form normal world,the PML4/PDPT for secure
world are separated from Normal World, PD/PT are shared in the
Secure World's EPT and Normal World's EPT.Secure world can
access Normal World's memory, but Normal World can not access
Secure World's memory
This function implemented：
-- Unmap specific memory from guest ept mapping
-- Copy PDPT from Normal world to Secure world
-- Map specific memory for Secure world
-- Unmap specific memory from SOS ept mapping

add create secure world ept API

---

arch/x86/ept.c
arch/x86/guest/vlapic.c
arch/x86/vmexit.c

- align coding style to avoid redundant operations
when operating on reading  VMX_EXIT_QUALIFICATION

align the coding style when access VMEXIT_QUAL

---

arch/x86/mmu.c
include/arch/x86/cpu.h
include/arch/x86/mmu.h

Now used IA32E_REF_MASK when calculate the address,
it will clear bit63, should use CPU_PAGE_MASK

Add page mask MACRO

---

Makefile
arch/x86/guest/guest.c
arch/x86/guest/vm.c
boot/multiboot.c
include/arch/x86/guest/guest.h
include/arch/x86/multiboot.h

1. refine multiboot related code, move to /boot.
2. firmware image files and ramdisk can be stitched in iasImage;
and they will loaded as multiboot modules.

to support firmware & ramdisk as multiboot mods

---

arch/x86/vmx_asm.S

…ails in vmresume
It is possible that the vm-entry fails in vmresume instr under some scenarios.
It will pass to next instruction following vmresume. In such case it will call
the vmlaunch again.

Jmp to vm_exit directly if vm-entry fails in vmresume

---

arch/x86/assign.c

info->phys_pin need be used by ptdev_build_native_rte when updating entry
TODO: currently ptdev entry is virtual based, the better solution should
be physical based.

ptdev: fix bug when update ptdev entry

---

arch/x86/guest/guest.c
boot/multiboot.c
common/vm_load.c
include/arch/x86/zeropage.h

According to the explaination for pref_address
in Documentation/x86/boot.txt, a relocating bootloader
should attempt to load kernel at pref_address if possible.
But due to a non-relocatable kernel will unconditionally
move itself and to run at perf address, no need to copy
kernel to perf_address by bootloader.

vm load: fix bug in loading kernel

---

arch/x86/ept.c
arch/x86/mmu.c
arch/x86/trusty.c
include/arch/x86/mmu.h

rename 'PT_HOST' to 'PTT_HOST'
rename 'PT_EPT' to 'PTT_EPT'
rename 'ept_type' to 'table_type'

mmu: Rename several variables related to page table type

---

.gitignore

If you build for a platform (e.g. uefi) and right after that for
another platform ('sbl'), the new build will fail and a version.h
file is left in the tree (bsp/uefi/include/bsp/version.h or
bsp/sbl/include/bsp/version.h depending on the order you built one
after the other). This commit makes git ignore any of those in case
it is there. Note that 'make clean' with the corresponding
PLATFORM variable will clean this file.

.gitignore: add 2 entries to ignore version.h file if present

---

bsp/uefi/efi/Makefile

As mentioned in https://github.com/projectacrn/acrn-documentation/pull/38 , 
on some operating systems, the ``gnu-efi`` package installs the
linker under a ``gnuefi`` folder in ``${LIBDIR}``. This is the
case in Fedora for example. Check if the gnuefi folder is there
and use it if it is, in the path to the linker.  This PR fixes the Makefile rather
than documenting how to edit it yourself.

makefile: adjust linker path in Makefile

---

arch/x86/guest/vlapic.c
arch/x86/vmexit.c
include/arch/x86/guest/vlapic.h

to keep aligned with the vmexit reasons' name defined in
SPEC.

hv: rename VM exit handlers in vlapic

---

arch/x86/cpu.c
arch/x86/intr_lapic.c
arch/x86/vmx.c
include/arch/x86/cpu.h
include/arch/x86/vmx.h

Add a global boot_cpu_data to cache common cpu capbility/feature
for detect cpu capbility/feature.
Acked-by: Xu, Anthony <anthony.xu@intel.com>

Add cpuinfo_x86 to cache cpu capability/feature

---

Makefile
arch/x86/guest/instr_emul_wrapper.h
arch/x86/guest/ucode.c
arch/x86/guest/vmsr.c
include/arch/x86/guest/guest.h
include/arch/x86/guest/ucode.h

microcode update from UOS is disabled.
microcode version checking is available for both SOS and UOS.
There are two TODOs of this patch:
1. This patch only update the uCode on pCPUs SOS owned. For the
pCPUs not owned by SOS, the uCode is not updated. To handle
this gap, we will have SOS own all pCPUs at boot time. So
all pCPUs could have uCode updated. This will be handled
in the patch to enable SOS own all pCPUs at boot time.
2. gva2gpa now doesn't check possible page table walk failure.
Will add the failure check in gva2gpa in different patch.
Reviewed-by: Anthony Xu (anthony.xu@intel.com)
Acked-by: Tian, Kevin <kevin.tian@intel.com>

hv: microcode: Enable microcode update from SOS.

---

arch/x86/cpuid.c
arch/x86/guest/ucode.c
arch/x86/guest/vm.c
arch/x86/vmexit.c
include/arch/x86/cpuid.h
include/arch/x86/guest/vm.h

Generate all common virtual cpuid entries for flexible support of
guest VCPUID emulation, by decoupling from PCPUID.
Acked-by: Xu, Anthony <anthony.xu@intel.com>
Acked-by: Chen, Jason CJ <jason.cj.chen@intel.com>

cpuid restruct

---

include/debug/assert.h

ASSERT is only for debug purpose, for release version, it should try
error handling instead of deadloop there.
v1:
- change the ASSERT under release version to empty code
TODO: revise all ASSERT usage
Acked-by: Eddie Dong (Eddie.dong@intel.com)

debug: make ASSERT empty under release version

---

bsp/uefi/efi/boot.c
bsp/uefi/uefi.c
include/arch/x86/apicreg.h
include/arch/x86/cpu.h

Straight forward compiler warning fix patch when building with PLATFORM=uefi
The most controversial bits are where to place the function definitions for the uefi related functions.  Instead of adding a new header I just placed them in a CONFIG_EFI_STUB protected section of apicreg.h.  Not sure if there is a better place.

Fix compiler warnings when building for UEFI

---

arch/x86/assign.c

for release version, the vuart is not be used - pin 4 then is not used
by hypervisor.
this patch adds check for vm0->vuart to distinguish it.

ptdev: fix ptdev_hv_owned_intx under release version

---

Documentation/Trusty.txt
Makefile
arch/x86/guest/vmcall.c
arch/x86/io.c
arch/x86/trusty.c
arch/x86/vtd.c
common/hypercall.c
common/trusty_hypercall.c
debug/console.c
include/arch/x86/trusty.h
include/common/hypercall.h
include/lib/rtl.h
include/public/acrn_hv_defs.h
lib/udelay.c

This patch series enables trusty feature base on ACRN hypervisor.
There are four main parts of this patch series.
1. HC_WORLD_SWITCH hypercall
This hypercall is used to simulate Secure Monitor Call(SMC) instruction to
switch vCPU world state between Normal World and Secure World.
2. HC_INITIALIZE_TRUSTY hypercall
This hypercall is used by UOS_Loader to request hypervisor to init Secure World
environment and launch Trusty-OS.
3. Add key_info for Trusty
key_info is a structure which contains many sensetive info such like seed,
rpmp_key, platform, manufacturing state, etc. This structure must be provided
when Trusty OS boot up, otherwise Trusty OS will fail to boot. Per previsous
design, hypervisor will got key_info from bootloader and derive vkey_info for
Trusty. Currently, bootloader did …

Trusty enabling patch series

---

arch/x86/trusty.c

On some toolchain configurations direct struct assignments will
default to a memcpy operation which is not present in this
environment, so explicitly use the internal memcpy_s function.
Signed-of-by: Rusty Lynch <rusty.lynch@intel.com>

Fix compile error caused by missing memcpy function

---

arch/x86/trusty.c

A bugfix for saving secure world memory info.
Maybe there are multiple UOS, each VM has its own secure
world and normal world, should save memory info into individual VM.

hv: Save secure world memory info into vm instead of vm0

---

arch/x86/cpu.c
include/arch/x86/mmu.h
include/lib/mem_mgt.h

According to C99:
The empty list in a function declarator that is not part of a definition of
that function specifies that no information about the number or types of the
parameters is supplied.
This means gcc is happy with the following code, which is undesirable.
void foo();    /* declaration with an empty parameter list */
void bar() {
foo();     /* OK */
foo(1);    /* OK */
foo(1, 2); /* OK */
}
This patch fixes declarations of functions with empty parameter lists by adding
an unnamed parameter of type void, which is the standard way to specify that a
function has no parameters. The following coccinelle script is used.
@@
type T;
identifier f;
@@
-T f();
+T f(void);
New compilation errors are fixed accordingly.
Acked-by: Eddie Dong …

treewide: fix declarations of functions with empty parameter lists

---

arch/x86/guest/vmsr.c

1.it doesn't support VMX for guest OS
2.for MSR out of control, inject GP to guest os.

add vmx msr ops protection from guest OS

---

.travis.yml
Dockerfile

Hello projectacrn team,
As @gvancuts suggested in the other pull request, I created an example `Dockerfile` and associated `.travis.yml` script.
The [build is running fine](https://travis-ci.org/shrmrf/acrn-hypervisor) for me.

Use Docker for building ACRN

---

arch/x86/trusty.c

Remove TODO comments since it has been done below the comments.
Typo fix: startup_info --> startup_param.

trusty: fix typo of comments

---

arch/x86/vtd.c
debug/sbuf.c

malloc: allocate a block of memory, the contents of the block are undefined.
calloc: allocate a block of memory for an array of num elements and initializes all its bits to zero.
Signed-off-by: yechunliang <yechunliangcn@163.com>

replace malloc and memset with calloc

---

include/common/hypercall.h

Documentation for parameters must match exactly in spelling and case.
Parameter named "vcpu" was incorrectly documented as "VCPU", and
parameter named "param" was documented as "param's".

doc: fix hypercall API doxygen errors

---

bsp/uefi/efi/boot.c

Previously with the help from gcc, __builtin_return_address(0) is
used as the guest entry address, but it can't work well with gcc 7.3
and leads to the guest unable to return to UEFI correctly.
Let's get it explicitly.

UEFI: get the guest entry address explicitly

---

arch/x86/trusty.c

Per trusty design, trusty requires a monotonic increasing
secure tick(TSC) at run time. This secure tick will used
to mitigate password/pin force attack, control key expiration,
etc.
Currently, the TSC_OFFSET is enabled. And guest will got
(host_tsc + tsc_offset) when execute rdtsc/rdtscp/rdmsr to
aquire tsc value. The host_tsc is always keeping increasing
during the runtime.
So initialize tsc_offset of trusty to 0 will ensure the
secure tick feature.

trusty: initialize tsc_offset to zero

---

Documentation/ACRN_UEFI.txt
bsp/uefi/clearlinux/acrn.conf
bsp/uefi/efi/boot.c
bsp/uefi/include/bsp/bsp_cfg.h

Since the boot flow had been changed to that sos kernel is lanuched
by cl bootloader directly, replace the payload acrn.efi with bzImage.efi
in the acrn.conf file, and specify ROOTDEV with UUID in the command line.
The UEFI firmware launches the EFI/org.clearlinux/bootloaderx64.efi
as os loader not the EFI/BOOT/BOOTX64.EFI, so fix the issue in the document
ACRN_UEFI.txt which guides user with incorrect steps.
Reviewed-by: Jack, Ren <jack.ren@intel.com>

UEFI: update acrn.conf and Document

---

arch/x86/cpu_secondary.S
arch/x86/ept.c
arch/x86/guest/guest.c
arch/x86/guest/vcpu.c
arch/x86/trusty.c
arch/x86/vmx.c
common/vm_load.c
include/arch/x86/cpu.h
include/arch/x86/guest/vm.h
include/arch/x86/mmu.h
include/arch/x86/trusty.h

Before this patch, guest temporary page tables were generated by hardcode
at compile time, HV will copy this page tables to guest before guest
launch.
This patch creates temporary page tables at runtime for the range of 0~4G,
and create page tables to cover new range(511G~511G+16M) with trusty
requirement.

mmu:create temporary page tables for guest at run time 

---

include/public/acrn_common.h

Now the MACRO SECURE_WORLD_ENABLED (1<<0)
Change it to 64 bit data
SECURE_WORLD_ENABLED (1UL<<0)

hv:add suffix(UL)for MACRO(SECURE_WORLD_ENABLED)

---

arch/x86/guest/vlapic.c
arch/x86/guest/vmsr.c
arch/x86/trusty.c
arch/x86/vmexit.c

Guest write tsc: cache the offset into run_context.tsc_offset;
Guest read tsc : use run_context.tsc_offset to calculate guest_tsc.

hv: cache tsc_offset

---

.travis-dockerfiles/Dockerfile.fedora26
.travis-dockerfiles/Dockerfile.fedora27

The 'find' command was not installed in our minimal Fedora 26
and 27-based Docker images. This resulted in a non-fatal error
when performing a 'make clean'. This commit adds this utility
(available in the 'findutils' package).

Add 'findutils' to Fedora-based Docker images

---

common/hypercall.c

Signed-off-by: Rusty Lynch <rusty.lynch@intel.com>

Fix warning about unused variable

---

common/hypercall.c

Input('vm0_gpa') should be validated when handling
hypercall 'HC_VM_SET_MEMMAP to create EPT for UOS
in 'hcall_set_vm_memmap()' function.
at least 'hpa' range (from 'vm0_gpa') can't overlap
hypervisor memory region.

Add range check for 'vm0_gpa' before creating EPT

---

include/common/hypercall.h

Before copy data between guest and host, should convert the GPA
to HVA and do the copy.
Reviewed-by: Chen, Jason Cl <jason.cj.chen@intel.com>
Reviewed-by: Yakui, Zhao <yakui.zhao@intel.com>

hypercall: bug fix on the address convertion while hypercall

---

arch/x86/assign.c

Before using a node of list, initialize it.

ptdev: bug fix on operating list

---

arch/x86/guest/vmsr.c
arch/x86/vmx.c

Switch all the referenced virtual address to physical address
include ept mapping, vmcs field, vmxon, vmclear, and vmptrld.
Reviewed-by: Chen, Jason Cl <jason.cj.chen@intel.com>
Reviewed-by: Yakui, Zhao <yakui.zhao@intel.com>

VMX: bug fix on operating vmx

---

arch/x86/vmx.c

This is workaround patch to resolve Disti performance issue.
In kernel 4.14, PAT is skipped to initialize if MTRR is not enabled,
while graphics driver need set WC to GGTT memory to accelerate memcpy,
if PAT is not initialized, default PAT register will treat UC- as
uncacheable, which will impact gfx performance. Change PAT default
register value to treat UC- as WC to workaroud this problem.
Revert me when PAT/MTRR strong correlation is removed in kernel.
Signed-off-by: Fei Jiang <fei.jiang@intel.com>

[acrn-dev] [PATCH] VMX: change PAT register default value

---

arch/x86/ept.c
arch/x86/guest/vm.c
arch/x86/io.c
common/hypercall.c
include/arch/x86/guest/vm.h

This address maybe invalid if a hostile address was set
in hypercall 'HC_SET_IOREQ_BUFFER'.
In the perspective of security, this address should be
validated before using.

Add IO requrest 'req_buf' check before reference

---

lib/sprintf.c

In the case that the copy sz is 0, it is unnecessary to do copy.
Reviewed-by: Chen, Jason Cl <jason.cj.chen@intel.com>
Reviewed-by: Yakui, Zhao <yakui.zhao@intel.com>

sprintf: bug fix in sprintf implemented code

---

include/lib/spinlock.h

Using ebx will truncate the high 32bit part of 64bit virtual address.
So using rbx instead of ebx.
Reviewed-by: Yakui, Zhao <yakui.zhao@intel.com>

spinlock: bug fix in spinlock code

---

arch/x86/cpu.c
arch/x86/guest/vpic.c
arch/x86/intr_lapic.c
arch/x86/io.c
arch/x86/ioapic.c
bsp/uefi/efi/multiboot.h
bsp/uefi/uefi.c
debug/console.c
debug/serial_internal.h
debug/uart16550.c
debug/vuart.c
include/arch/x86/io.h
include/arch/x86/lapic.h
include/lib/types.h

remove data defination of mmio_addr_t, vaddr_t, paddr_t,
and ioport_t.

refine: remove redundant data type definition

---

arch/x86/ept.c
arch/x86/guest/vmcall.c
arch/x86/guest/vmsr.c
arch/x86/interrupt.c
arch/x86/io.c
arch/x86/vmexit.c
include/arch/x86/guest/guest.h
include/arch/x86/io.h
include/arch/x86/irq.h
include/arch/x86/mmu.h
include/arch/x86/vmexit.h

this patch is to align the suffix of the handlers' name.

rename vmexit handlers

---

arch/x86/guest/instr_emul.c
arch/x86/guest/instr_emul.h
arch/x86/guest/vcpu.c
common/hv_main.c
include/arch/x86/guest/vcpu.h

SDM 24.9.1 Volume3:
- 'Exit reason' field in VMCS is 32 bits.
SDM 24.9.4 in Volume3
- 'VM-exit instruction length' field
in VMCS is 32 bits.
This patch is to redefine the data types of above fields
in 'struct vcpu_arch' and udpate the code using these
two fields.

revise type of 'exit_reason' and 'inst_len' in vcpu_arch

---

arch/x86/interrupt.c
arch/x86/intr_lapic.c
arch/x86/ioapic.c
arch/x86/mmu.c
arch/x86/vtd.c
boot/acpi.c
boot/include/acpi.h
bsp/uefi/cmdline.c
bsp/uefi/uefi.c
debug/uart16550.c
include/arch/x86/io.h
include/arch/x86/mmu.h

a, Change the address arguments type of mmio access api from uint64_t
to void*.
b, before referencing to physical address of devs such as lapic, ioapic,
vtd, and uart, switch to virtual address.
c, before referencing to phisical address of acpi tables, switch it to
virtual address.
d, before pasing commandline from boot param, switch the phisical address
of param to virtaul address.

Bug fix on address convertion

---

include/lib/spinlock.h

These APIs are not used, and not as safe as spinlock_irqsave_obtain/
spinlock_irqrestore_release.

hv: remove spinlock_irq_obtain/spinlock_irq_release

---

debug/logmsg.c

Add percpu earlylog sbuf within hypervisor memory space to accommodate log
before sos booting, and copy the earlylog to SOS allocated sbuf at the first
do_logmsg after SOS sets the sbuf during booting.
With the patch, earlylog of hypervisor could be captured with acrnlog
service if SOS booted. And it may help debugging hv issue if SOS failed to
boot, with "logdump" command.

hv: save early hv logmsg before sos booted

---

arch/x86/interrupt.c
arch/x86/vmexit.c
include/arch/x86/guest/vcpu.h
include/arch/x86/vmx.h

1. In function 'exception_vmexit_handler()' ,
Extract exception vector and other info. only if
bit31 (Valid) of 'VM-Exit Interruption-Information
field is set. -Intel SDM 24.9.2, Vol3
2.  Rename 'exit-interrupt_info' to 'idt_vectoring_info'
in 'struct vcpu_arch', which is consistent to
SDM 24.9.3, Vol3
3. 'IDT-vectoring information' in VMCS is 32bit
-Intel SDM 24.9.3, Vol3
Set the type of 'idt_vectoring_info' in 'struct vcpu_arch'
to 'uint32_t' instead of 'uint64_t'.

check validity of 'VM-exit Int-Info' before extracting vector

---

arch/x86/vmexit.c
arch/x86/vmx.c

before just AP can run "rdtscp" intruction, if run it on BSP,
it will cause "illegal instruction"; now align BSP & AP.
also remove duplicated code.

enable rdtscp instruction for guest OS all vCPUs

---

Makefile
arch/x86/cpu.c
arch/x86/cpu_state_tbl.c
arch/x86/guest/pm.c
arch/x86/guest/vm.c
arch/x86/guest/vmsr.c
common/hypercall.c
include/arch/x86/cpu.h
include/arch/x86/guest/pm.h

Split pm.c from cpu_state_tbl.c to put guest power management related
functions, keep cpu_state_tbl.c to store host cpu state table and
related functions.
Acked-by: Kevin Tian <kevin.tian@intel.com>

HV: code cleanup for cpu state

---

arch/x86/cpu.c
arch/x86/mmu.c
common/hv_main.c
include/arch/x86/cpu.h
include/arch/x86/cpufeatures.h
include/arch/x86/mmu.h

Now just add some basic feature/capability detect (not all). Vapic
didn't add here for if we must support vapic then the code which
for vapic not supported must remove, like mmio apic r/w.

hv: add hardware_detect_support to detect which hardware we support

---

arch/x86/cpu.c

Using eax will truncate the high 32bit part of 64bit virtual address.
And the type of sync is unsigned long, so using rbx instead of ebx.

hv: bug fix on synchronizing with APs

---

bsp/uefi/uefi.c

Due to redundant waking up APs When rebooting UOS, the crash occurs
and fail to reboot UOS.

UEFI: bug fix on redundant waking up APs

---

bsp/sbl/vm_description.c
bsp/uefi/vm_description.c

remove deadcode of vm1 config in vm_description

---

arch/x86/assign.c
arch/x86/ioapic.c
common/hypercall.c
include/arch/x86/assign.h
include/arch/x86/ioapic.h

currently, pass-thru devices are managed by per-vm's remapping entries
which is virtual based:
- MSI entry is identified by virt_bdf+msix_index
- INTx entry is identified by virt_pin+vpin_src
it works but it's not a good design for physical resource management, for
example a physical IOAPIC pin could belong to different vm's INTx entries,
the Device Model then must make sure there is no resource conflict from
application's level.
This patch change the design from virtual to physical based:
- MSI entry is identified by phys_bdf+msix_index
- INTx entry is identified by phys_pin
The physical resource is directly managed in hypervisor, a miss adding
entry will be found by hypervisor and return error message with failure.
Acked-by: Xu, …

ptdev: change remapping entry from virtual to physical based

---

arch/x86/cpu_state_tbl.c
arch/x86/guest/pm.c
arch/x86/io.c
common/hypercall.c
include/arch/x86/cpu.h
include/arch/x86/guest/pm.h
include/arch/x86/guest/vm.h
include/arch/x86/io.h
include/public/acrn_common.h

Like guest pstate control, guest must have intel_idle driver or acpi-idle
driver enabled in kernel to enable guest cstate control. Especialy for
acpi-idle subsystem, idle space info is needed in ACPI FACP or DSDT table.
Acrn Cx enabling is similar with Px enabling implementation:
1. Hard code the host Cx data in HV;
2. Host load the host Cx data and store them to boot_cpu_data
during boot;
3. Each VM has a Cx data copy saved in its pminfo when create VM;
4. Add a VHM service in kernel that could interact with HV and DM
on data transtion. HV would expose native cx data to VHM/DM
without validation, because guest OS would check it before
enter idle;
5. Before launching UOS, DM query HV the supported Cx data;
6. DM generate the ACPI CST objects for UOS with these Cx data;
7. For CPU …

HV: Guest Cstate control support

---

Makefile
arch/x86/cpu.c

- Add "DBG" or "REL" to indicate the DBG build or REL build explicityly;
- Change the build time format to "%F %T".
Example:
HV version 0.1-rc4-2018-04-28 14:20:32-b2d7282-dirty DBG build by like

hv: add build type and detail time to version string

---

arch/x86/cpuid.c

We should consider the boundary condition although we didn't
access it.
@yonghuah

hv: cpuid: don't reference the crossed array

---

arch/x86/assign.c
arch/x86/trusty.c
debug/shell_internal.c

- NULL pointer reference risk
- buffer overflow risk

security: fix issues reported by Klocwork

---

bsp/uefi/efi/boot.c
bsp/uefi/include/bsp/bsp_cfg.h

This patch makes the Service OS bootloader configurable by passing
a command-line argument to 'acrn.efi' when setting up the EFI
bootloader using, e.g., 'efibootmgr'. If no argument is passed, the
default bootloader used is: "\EFI\org.clearlinux\bootloaderx64.efi".
This is the default bootloader/setting used by Clearlinux and is set
in the bsp/uefi/include/bsp/bsp_cfg.h file (via the
CONFIG_UEFI_OS_LOADER_NAME define)
The general format of the argument is: "bootloader=<\path\to\bootloader>".
As a concrete example, imagine the following set-up:
* You have installed the Service OS (bare-metal for now)
* Bootloader is "\EFI\org.clearlinux\bootloaderx64.efi"
* Boot device is '/dev/sda'
* EFI System Partition (ESP) is '1'
* You put the ACRN hypervisor under "\EFI\acrn\"
To change the default …

Make the Service OS bootloader configurable

---

arch/x86/ept.c
arch/x86/guest/vm.c
arch/x86/io.c
common/hypercall.c
include/arch/x86/guest/vm.h

- rename it to 'io_shared_page' to keep consistent
with ACRN HDL foils.
- update related code that reference this data structure.

rename 'req_buf' field in 'struct vm_sw_info'

---

include/public/acrn_common.h

The name of acrn_register is too generic, rename to acpi_generic_address
which is more common.
Acked-by: Kevin Tian <kevin.tian@intel.com>

HV: rename acrn_register to acpi_generic_address

---

arch/x86/mmu.c

Page fault could be raised if writing to read-only pages. This is
useful for debugging.

HV: Enable CR0.WP

---

doc/Makefile
doc/README.md
doc/contribute.rst
doc/getting_started/index.rst
doc/primer/index.rst
doc/scripts/publish-README.md

Documentation updates were needed to account for changes caused by the
recent merging of the three acrn-hypervisor, acrn-devicemodel, and
acrn-documentation repos.

doc: post-merge changes to docs

---

doc/contribute.rst

Update the "Contributing Guidelines" document to point at the
top-level LICENSE file that was created after the merger of
the three acrn-{hypervisor,devicemodel,documentation} repositories

Documentation: update the contributing guide to use new LICENSE file

---

hypervisor/Makefile
hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/guest/vioapic.c
hypervisor/arch/x86/vmx.c
hypervisor/bsp/uefi/efi/Makefile
hypervisor/include/arch/x86/cpu.h
hypervisor/include/arch/x86/vmx.h

This is one patch set that tries to enable the -O2 option.
The patch[1..5] are used to fix the issues when trying
to enable -O2 option.
The patch6 is used to enable the -O2 option.

Optimize patch

---

hypervisor/arch/x86/io.c

- add check for spanning i/o devices access
- remove ASSERT in I/O instr. VM exit handler

I/O VM-exit handler cleanup

---

.gitignore
Makefile
tools/acrn-manager/Makefile
tools/acrnlog/Makefile
tools/acrntrace/Makefile

it can be used as following:
make ==> to make hypervisor & devicemodel & tools
also modify tools makefile to support out-dir setting.

add a makefile under project root directory

---

CODEOWNERS

Seed an initial CODEOWNERS file.  Update as owners for specific areas
are defined.
You can use a CODEOWNERS file to define individuals or teams that are
responsible for code in a repository. The listed names must have write
permissions for the repository.
Code owners are automatically requested for review when someone opens a
pull request that modifies code that they own. When someone with admin
or owner permissions has enabled required reviews, they also can
optionally require approval from a code owner before the author can
merge a pull request in the repository.

devops: Add CODEOWNERS for GitHub review

---

hypervisor/arch/x86/io.c

- device driver should register valid i/o handlers
in any cases, avoid referencing to default handler
- remove i/o handler test code as they shall
never be NULL.

remove potential using default i/o handler

---

devicemodel/hw/pci/core.c

Entries of pci_businfo[] allocated in function "pci_parse_slot"
using calloc need to be freed when deinit.
Reviewed-by: Anthony Xu <anthony.xu@intel.com>

dm: free entries in pci_businfo[] when deinit

---

doc/introduction/index.rst

The Android-IA project is re-branding as Celadon.
Signed-off-by: Tonny Tzeng tonny.tzeng@intel.com

doc: link the Android guest to Celadon

---

hypervisor/arch/x86/guest/vmcall.c
hypervisor/common/hypercall.c
hypervisor/include/common/hypercall.h
hypervisor/include/public/acrn_hv_defs.h

Add set_memmaps hypercall to support multi regions memmap.

hypercall: add set_memmaps hypercall support

---

hypervisor/arch/x86/guest/vcpu.c

Lock should be on target vcpu in function pause_vcpu(), not current vcpu.

HV: operate schedule lock on correct vcpu

---

hypervisor/debug/shell_internal.c
hypervisor/debug/shell_internal.h
hypervisor/debug/shell_public.c

Remove cmd register API. And use static pre-defined cmd array
instead.

hv: cleanup the shell cmd code.

---

Makefile
tools/acrn-manager/Makefile
tools/acrnlog/Makefile
tools/acrntrace/Makefile

We have some conventions in existing code and documents, these patches are to follow those conventions:
(1) Current documents presume build the code with 'make PLATFORM=uefi'
(2) Both HV and DM invoke compiler with $(CC) for flexibility, the new tools code should follow the same practice
Signed-off-by: Tonny Tzeng tonny.tzeng@intel.com

Makefile: compliant with existing conventions

---

hypervisor/arch/x86/ept.c
hypervisor/arch/x86/guest/instr_emul.h
hypervisor/arch/x86/guest/instr_emul_wrapper.c
hypervisor/arch/x86/guest/vlapic.c

MMIO access size is not initialized before
instruction emulation.

hv: bugfix - MMIO access size was not properly initialized.

---

Makefile

The variable PLAT was renamed to PLATFORM, but was not updated in the
install target giving a failure when installing ACRN hypervisor.
Fixes: fc2b6fbe86e8 ("Makefile: keep using 'PLATFORM' variable for existing documentation")

Makefile: fix PLATFORM variable at install target

---

hypervisor/arch/x86/interrupt.c
hypervisor/arch/x86/vmx.c

HV only print out message for #MC then inject it back to guest.

exception: only trap #MC

---

hypervisor/include/debug/trace.h

Macro GEN_CASE in hypervisor is not used. It's just for userspcace tool
acrntrace and we get one copy of it in ./tools/acrntrace/trace_event.h.
So, remove it.

HV: Trace: Remove macro GEN_CASE

---

devicemodel/hw/pci/core.c

This commit is reported to cause UOS reboot fail becasue the
pci_businfo[] only be allocated when calling pci_parse_slot
in dm initialization while UOS reboot will not allocate again.
So we can't free it here.
This reverts commit 7aaff68798a4ba3564e4d913678eb84c610dad6c.

Revert "dm: free entries in pci_businfo[] when deinit"

---

doc/primer/index.rst

Remove UEFI boot material that was causing doc build to fail (seems to
be a duplicate of material in the Getting Started Guide anyway)
Fix reST formatting for the DM memory allocation section.
Update folder layout description
Fixes: #202

doc: fix primer reST errors, update folder layout

---

devicemodel/hw/platform/ioc.c

Pointer 'tmp' may be NULL before passing it to 'strtoul()'

DM: avoid NULL pointer dereferenced in 'ioc_parse()'

---

hypervisor/include/common/hypercall.h

fix wrong description for hcall_get_cpu_pm_state/hcall_world_switch

doxygen: fix wrong description in hypercall.h

---

hypervisor/arch/x86/ept.c
hypervisor/arch/x86/guest/instr_emul.c
hypervisor/arch/x86/guest/instr_emul.h
hypervisor/arch/x86/guest/instr_emul_wrapper.c
hypervisor/arch/x86/guest/vlapic.c

update:
1. remove 'struct mem_io *'from input arguments
2. return 'opsize' instead of status.
3. rename 'vmm_decode_instruction()'

HV: refine 'decode_instruction() function

---

Makefile

The 'ROOT_OUT' variable does not allow to set the folder in
which all output files (objects, binaries, etc.) are built
and placed.
Overriding it from the command-line leads to 'build' folders
of the name set that are created in the tree eventually leading
to a failure during the build. This patch changes how the
output directory is constructed so that *all* output files
are put in there. It introduces a new variable called
'BUILD_DIR' to that effect.
It also incidentally fix the fact that 'make clean' only removes
that output directory which means it does not properly clean up
the tree if one overrides the 'ROOT_OUT' variable manually today.
To change where the build artefacts are placed, set 'BUILD_DIR'
to whatever you want, e.g.:
$ make BUILD_DIR=build-test
Will create a top-level …

Fix the logic that sets the top-level build directory

---

hypervisor/arch/x86/interrupt.c

Now use hardcode when inject GP/NMI to guest,
replace it with MACRO.

hv:Use exception vector MACRO instead of hardcode

---

hypervisor/arch/x86/vmx.c

- to avoid complains from code static scan tool

HV:initialize variables before reference in vmx.c

---

devicemodel/hw/pci/core.c

suspicious dereference of pointer 'fi->fi_devi'
by passing it to function 'pci_emul_free_bars()'
before  NULL check.

DM:fix suspicious dereference of pointer in 'pci_emul_deinit()

---

devicemodel/core/sw_load_bzimage.c
devicemodel/core/sw_load_common.c
devicemodel/core/sw_load_vsbl.c
devicemodel/hw/platform/acpi/acpi.c

function 'strncpy' may incorrectly check buffer boundaries
and may overflow buffers.

DM:fix the possible buffer overflow issue using 'strncpy'

---

devicemodel/core/vmmapi.c

DM: initialize 'create_vm' before reference it in 'vm_opn'

---

devicemodel/core/hugetlb.c

Add buffer boundaries to avoid overflow

DM: fix buffer overflow risk issues in hugetlb.c

---

hypervisor/include/common/hypercall.h

Add missing documentation for hcall_get_cpu_pm_state vm parameter

doc: add missing param documentation hypercall.h

---

hypervisor/arch/x86/ept.c
hypervisor/arch/x86/guest/instr_emul.h
hypervisor/arch/x86/guest/instr_emul_wrapper.c
hypervisor/arch/x86/guest/vlapic.c

HV:remove redundant field 'mmio' from 'struct emul_cnx'

---

tools/acrn-crashlog/Makefile
tools/acrn-crashlog/acrnprobe/Makefile
tools/acrn-crashlog/acrnprobe/event_handler.c
tools/acrn-crashlog/acrnprobe/sender.c
tools/acrn-crashlog/usercrash/Makefile

Define a macro HAVE_TELEMETRICS_CLIENT to distinguish the compiling
environment which is not include telemetrics client.

tools: acrn-crashlog: compile without telemetrics client

---

doc/CODEOWNERS
doc/_templates/footer.html
doc/conf.py
doc/contribute/contribute_guidelines.rst
doc/contribute/doc_guidelines.rst
doc/contribute/index.rst
doc/index.rst
doc/substitutions.txt

Add documentation contributing information with project specific
recommentations along with some common reST and Sphinx constructs.
Reorganize contributing section to fit this new doc in.
Also
* Cleanup stray file (CODEOWNERS) from when docs were in their own repo.
* Remove licensing footer on generated pages (not really needed).
* Pull replacement strings into substitutions.txt for easier management.

doc: add doc contributing guide, plus cleanup

---

doc/static/acrn-custom.css

Typo caused some styles to be missed

doc: fix error in custom CSS file

---

hypervisor/arch/x86/guest/vm.c

HV: Add NULL pointer check in 'vm_fixup()' function.

---

devicemodel/core/monitor.c

-memory was dereferenced after being freed:
object 'client' was derefenced after being freed
by call 'vmm_client_free_res()'
-Root cause: MACRO 'LIST_FOREACH()' dereference
'client' for next list node after 'client'
was freed.

DM: bugfix - use of freed memory in 'monitor_close()'

---

hypervisor/arch/x86/guest/ucode.c
hypervisor/arch/x86/vmexit.c

According in C99 manual 6.7.8,'=' is required.

fix "obsolete use of designated initializer without '='"

---

Makefile

To build with only one command the sbl and efi hypervisor a target was
added which build the SBL hypervisor version.
Now you can call "make all sbl-hypervisor" and
"make install sbl-hypervisor-install"
This HELPS autospec 

Makefile: add a target to build sbl hypervisor

---

devicemodel/core/inout.c

- check the port address range explicitly
to avoid buffer overflow.

DM: validate port range explicitly in inout.c

---

devicemodel/hw/platform/ioc.c
devicemodel/hw/platform/ioc_cbc.c
devicemodel/include/ioc.h

This patch set implements IOC mediator lifecycle work flow that including
suspend, shutdown and resume. IOC mediator needs notify suspend/shutdown
event for PM DM once received corresponding heartbeat messages from UOS.
And VM Manager needs forward S3/S5 wakeup reason to IOC DM to resume/boot UOS.
Liu Yuan (3):
IOC mediator: Separate wakeup reason and heartbeat
IOC mediator: Implement state transfer framework
IOC mediator: Implement state transfer operations
v2:
1) Replace the term of FSM with IOC state.
2) Refine the patches order.
3) Embed ioc_dev in cbc_pkt to simplify data exchange.

Ioc mediator：Support lifecycle emulation

---

devicemodel/core/hugetlb.c
devicemodel/core/sw_load_bzimage.c
devicemodel/core/sw_load_common.c
devicemodel/core/sw_load_vsbl.c
devicemodel/hw/platform/acpi/acpi.c

- check buffer boundaries to avoid buffer overflow

DM: using 'strncpy' coding style cleanup

---

hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vmsr.c

Range expression in switch statement is in gcc extension standard(gcc
manual 6.28),not in c99 standard.
GCC manual 6.28 reference link below:
(https://gcc.gnu.org/onlinedocs/gcc-8.1.0/gcc/Case-Ranges.html#Case-Ranges)

fix "warning:range expression in switch statements are not standard"

---

doc/getting_started/index.rst
doc/getting_started/up2.rst

The sambles scripts where moved to another directory but did not update
all the references in the documentation.
Fixes: 977d48d55042 ("hypervisor: install acrn.efi to /usr/lib")
Fixes: 9563e248b784 ("samples: move samples to specifi platform diretory")

doc: fix references from scripts

---

hypervisor/bsp/uefi/efi/boot.c

Fix a bug:
When the hypervisor cmdline is empty, the hypervisor will be
unable to boot up.

hv: handle the case of empty hypervisor cmdline

---

devicemodel/Makefile
devicemodel/README.rst
devicemodel/hw/pci/xhci.c
devicemodel/hw/platform/usb_mouse.c
devicemodel/hw/platform/usb_pmapper.c
devicemodel/hw/usb_core.c
devicemodel/include/usb.h
devicemodel/include/usb_core.h
devicemodel/include/usb_pmapper.h

Those patches enable xHCI emulation which supports ports sharing for
specified Guest OS.

xHCI Port Sharing mode implementation

---

hypervisor/arch/x86/guest/ucode.c

The macro GET_DATA_SIZE's code style is not correct,
it is merged by accident,the Pull Request #262
<fix "obsolete use of designated initializer without '='"> 
have two commid id,the second commit changed the ucode.c
by mistake.
Now fixed.

refomatted GET_DATA_SIZE macro

---

hypervisor/arch/x86/guest/vioapic.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vpic.c
hypervisor/arch/x86/vtd.c
hypervisor/include/debug/logmsg.h

It is an extension of GCC CPP to:
* allow omitting a variable macro argument entirely, and
* use ## __VA_ARGS__ to remove the the comma before ## __VA_ARGS__ when
__VA_ARGS__ is empty.
The only use of ## _VA_ARGS__ is to define the pr_xxx() macros, with the first
argument being the format string and the rest the to-be-formatted arguments. The
format string is explicitly spelled out because another macro pr_fmt() is used
to add to the format string a prefix which is customizable by defining what
pr_fmt() expands to.
For C99 compliance, this patch changes the pr_xxx() macros in the following
pattern.
- #define pr_fatal(fmt, ...)				\
-     do_logmsg(LOG_FATAL, pr_fmt(fmt), ## __VA_ARGS__);	\
+ #define pr_fatal(...)					\
+     do_logmsg(LOG_FATAL, pr_prefix __VA_ARGS__);		\
Reference:
* …

HV: debug: stop using ## __VA_ARGS__

---

doc/getting_started/index.rst

This adds basic information about the new ACRN tools that have
been integrated in the the acrn-hypervisor repo (under tools/).
It also adds the build dependencies for the different development
environment that we support.

Getting Started Guide: add build instructions for the ACRN tools

---

doc/getting_started/index.rst
doc/getting_started/up2.rst
doc/hardware.rst

Fix formatting and adhere to the recommendations published by
the documentation owner when writing reST documents.
Minor modifications on the technical content:
* Remove the partition number to the '-d' argument of 'efibootmgr'
* Replace a 'cp' operation by 'make devicemode-install'

Getting Started Guide for the UP2 board: fix formatting

---

hypervisor/arch/x86/guest/vlapic.c
hypervisor/include/arch/x86/apicreg.h

Pointer arithmetic is currently used to calculate the address of a specific
Local Vector Table (LVT) register (except LVT_CMCI) in lapic, since the
registers are continuously placed with fixed padding in between. However each of
these registers are declared as a single uint32_t in struct lapic, resulting
pointer arithmetic on a non-array pointer which violates MISRA C requirements.
This patch refactors struct lapic by converting the LVT registers fields (again
except LVT_CMCI) to an array named lvt. The LVT indices are reordered to reflect
the order of the LVT registers on hardware, and reused to index this lvt array.
The code before and after the changes is semantically equivalent.

lapic: continuous LVT registers as an array

---

hypervisor/include/lib/types.h

uint32_t occures two times in hypervisor/include/lib/types.h,
remove one of them.
acked-by kevin

fix "warning:redefinition of typedef 'uint32_t'"

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/vmx.c
hypervisor/bsp/include/bsp_extern.h
hypervisor/bsp/sbl/vm_description.c
hypervisor/bsp/uefi/vm_description.c
hypervisor/common/hv_main.c
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/debug/logmsg.h

v2:
1. fix cover letter comments grammar error
2. datail patch descriptions.
v1:
ASSERT will hang the whole system in debug version while doing nothing
in release version. However, in most of the case, we should not hang
the whole system: like invalid input parameter or creating an UOS. And
in release version, we shouldn't do nothing when something bad happened.
So ASSERT cleanup is necessary. This serial is just a beginning.
It will panic the system when creating SOS failed while not when create
UOS failed. It just returns error number to the caller when something
nonfatal error heppened otherwise panic when something fatal error happened.
In this serial, failure to create SOS is an fatal error.

ASSERT cleanup for SOS/UOS creation

---

doc/getting_started/index.rst

Sphinx was complaining about a missing argument, and fixed some trailing
spaces.

doc: tweak to GSG to fix code-block

---

doc/tools.rst
tools/acrn-manager/README.rst
tools/acrnlog/README.rst
tools/acrntrace/README.rst

This continues the editing from PR #276 with formatting and clarity
edits to have these tool documents blend in with the rest of the ACRN
documentation.  It also builds on PR #307 that set up the doc build
infrastructure to allow leaving these tool docs within the tools/
folder.

doc: fix tools docs formatting and clarity

---

doc/.known-issues/doc/hypercall.conf

Changes to the nested unnamed unions in type definitions require a tweak
to the pattern matching used to detect known issues reported by the API
doc generation.

doc: adjust known issues pattern

---

hypervisor/arch/x86/guest/instr_emul_wrapper.h

Included file not protected with #define, this
feature is required.

fix MISRA-C 243S

---

devicemodel/hw/pci/xhci.c
devicemodel/include/xhci.h
devicemodel/include/xhcireg.h

On Intel ApolloLake platform, there has one couple USB2/USB3 ports
shared one couple USB2/USB3 PHY with xDCI(dwc3) controller to support
dual role mode. There has one hardware logic inside xHCI controller
to support dynamic USB PHY switch between xHCI and xDCI. And two
xHCI mmio registers are used for controling this logic, which are exposed
as xHCI extended capability for software.
This patch set implements USB dual role switch for Intel ApolloLake platform.
DRD which means dual role device is used for switching xHCI and xDCI between
PHY USB2&USB3.

Support DRD capability for APL xHCI.

---

misc/cbc_lifecycle/Makefile
misc/cbc_lifecycle/cbc_lifecycle.c

The cbc_lifecycle service will listen on /dev/cbc-lifecycle tty port to
receive "wakeup reason" information from ioc controller as well as send
heartbeat to ioc to set different power cycle method.
The RTC funtionality is not implemented by current ioc firmware yet,
hence the service leaves it as an empty handler now.

ioc: add cbc_lifecycle service

---

tools/acrnlog/README.rst

Make it clear that some commands mentionned in the 'acrnlog' tool
documentation are meant to be run in the hypervisor shell and *not*
the Service OS shell (as are the other commands throughout the rest
of that document).

Documentation: small addition to the 'acrnlog' tool documentation

---

devicemodel/samples/apl-mrb/launch_uos.sh

This patch turn on WIFI/BT in launch_UOS.sh based on WIFI BDF on SBL,
which is different from ABL. Still need WIFI/BT driver in Android to
make WIFI/BT passthrough work.

DM: Turn on WIFI/BT passthrough for Android UOS

---

tools/acrn-manager/acrnctl.c

commit(4d274a5 Tools: acrn-manager-interface) change location and naming scheme
to the follow.
/run/acrn/mngr/vmname.monitor.pid.socket
This patch adapt parse vmname according new naming scheme.

tools: acrnctl: Fix regression of acrnctl list

---

devicemodel/include/virtio.h

Fixes a recent PR #311 that added a new API but the doxygen comments for
one of the parameters didn't match the parameter name.

doc: fix doxygen comments in virtio.h

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/guest/guest.c
hypervisor/arch/x86/trusty.c
hypervisor/include/arch/x86/trusty.h

Acked-by:Eddie Dong
_Static_assert is supported in C11 standard.
Please see N1570(C11 mannual) 6.4.1.
replace _Static_assert with ASSERT.
Signed-off-by: huihuang shi <huihuang.shi@intel.com>

fix "ISO C99 does not support '_Static_assert'"

---

devicemodel/hw/platform/ioc.c
devicemodel/samples/apl-mrb/launch_uos.sh

Update MRB launch_uos.sh script to enable IOC mediator by default.
And change the PTY path from the /tmp/ioc_$vm_name to /run/acrn/ioc_$vm_name for aligning with acrnctl.
Set one default boot wakeup reason to avoid acrn-dm boot failed with invalid wakeup reason parameter.
v2):
1. Avoid enable invalid wakeup reason bit.
2. Add restriction comments in check_dir function-call.

Enable IOC mediator by default on MRB

---

devicemodel/core/sw_load_bzimage.c
devicemodel/core/sw_load_vsbl.c
hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/guest/guest.c
hypervisor/arch/x86/guest/instr_emul.c
hypervisor/arch/x86/guest/instr_emul_wrapper.c
hypervisor/arch/x86/guest/ucode.c
hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/trusty.c
hypervisor/arch/x86/vmx.c
hypervisor/common/vm_load.c
hypervisor/debug/dump.c
hypervisor/debug/shell_internal.c
hypervisor/include/arch/x86/guest/guest.h
hypervisor/include/arch/x86/vmx.h

Note: this patch series need to work with new vSBL (start from real mode) on SBL platform!
In current code, hv only support starting vcpu from real mode or 64bit mode.
And sos/uos bsp can only start from 64bit mode. gva2gpa translation only works
on long mode.
This patch series adds support to start vcpu from protected mode. And has the
following vcpu start mode settings:
- For sbl platform:
This patch starts sos bsp from protected mode by default.
CONFIG_START_VM0_BSP_64BIT is defined to allow start sos bsp
from 64bit mode. If a config CONFIG_START_VM0_BSP_64BIT
defined in config file, then sos bsp will start from 64bit mode.
This patch start uos bsp from real mode, which needs the integration
of virtual bootloader (vsbl).
- For uefi platform:
This patch sets sos bsp vcpu mode according …

Support different vcpu modes

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/gdt.c
hypervisor/arch/x86/guest/instr_emul_wrapper.c
hypervisor/arch/x86/guest/instr_emul_wrapper.h
hypervisor/arch/x86/irq.c
hypervisor/arch/x86/softirq.c
hypervisor/arch/x86/timer.c
hypervisor/bsp/ld/link_ram.ld.in
hypervisor/common/hv_main.c
hypervisor/common/schedule.c
hypervisor/debug/logmsg.c
hypervisor/debug/sbuf.c
hypervisor/include/arch/x86/cpu.h
hypervisor/include/arch/x86/gdt.h
hypervisor/include/arch/x86/per_cpu.h
hypervisor/include/arch/x86/timer.h
hypervisor/include/common/schedule.h
hypervisor/include/debug/logmsg.h
hypervisor/include/debug/sbuf.h
hypervisor/include/debug/trace.h

The current implementation of per_cpu relies on several non-c99 features,
and in additional involves arbitrary pointer arithmetic which is not MIS-
RA C friendly.
This patch introduces struct per_cpu_region which holds all the per_cpu
variables. Allocation of per_cpu data regions and access to per_cpu vari-
ables are greatly simplified, at the cost of making all per_cpu varaibl-
es accessible in files.
Signed-off-by: huihuang shi <huihuang.shi@intel.com>

HV:treewide:C99-friendly per_cpu implementation

---

devicemodel/samples/apl-mrb/launch_uos.sh

Enable IOC for android on MRB by default.
Reviewed-by: Like Yan <like.yan@intel.com>

IOC mediator: Enable IOC for android in launch_uos.sh

---

devicemodel/samples/apl-mrb/launch_uos.sh

Now the IPU devices are always enabled. But they don't exist on some
boards. In such case some errors are warned and the system can't be booted.
Reviewed-by: Yin FengWei <fengwei.yin@intel.com>

DM/samples: Check whether IPU devices exists before using IPU devices

---

devicemodel/samples/apl-mrb/launch_uos.sh

enable IPU passthrough for Android UOS on MRB by default
v1 -> v2:
* add comments for i2c controller passthrough
* add indentation for 'if' statements

dm: enable IPU passthrough for Android UOS

---

devicemodel/samples/apl-mrb/launch_uos.sh

When connecting three monitors to MRB, we will assign the first one to
SOS and assign remaining ones to UOS.

script: support two monitors in UOS

---

doc/conf.py

graphviz lets us create graphic images via a text language rather than
creating drawings in other tools (eliminating the need to keep the
sources for the images available, such as a powerpoint file).

doc: add graphviz extension

---

hypervisor/Makefile
hypervisor/arch/x86/trusty.c
hypervisor/boot/sbl/hob_parse.c
hypervisor/boot/sbl/multiboot.c
hypervisor/include/arch/x86/hob_parse.h
hypervisor/include/arch/x86/trusty.h

Retrieve dseed from SeedList HOB(Hand-Off-Block).
SBL passes SeedList HOB to ACRN by MBI modules.
Reviewed-by: Zhu Bing <bing.zhu@intel.com>
Reviewed-by: Wang Kai <kai.z.wang@intel.com>

HV: Parse SeedList HOB

---

tools/acrn-crashlog/data/acrnprobe_prepare.sh

This patch is to change the source of config file according
to the doc of telemetrics-client:
There is a config file installed at
``/usr/share/defaults/telemetrics/telemetrics.conf``
To make modifications, copy that file to
``/etc/telemetrics/telemetrics.conf``
and modify the /etc version.
Otherwise, the modification may be lost after ``swupd update``.
Reviewed-by: Zhang Di <di.zhang@intel.com>
Reviewed-by: Jin Zhi <Zhi.jin@intel.com>
Reviewed-by: Liu Xinwu <xinwu.liu@intel.com>

tools: acrn-crashlog: change source of config file

---

Makefile
tools/Makefile
tools/acrn-manager/Makefile
tools/acrnlog/Makefile
tools/acrntrace/Makefile

Add a Makefile under ./tools to avoid changing top-level Makefile frequently

Tools: add Makefile for all tools

---

devicemodel/Makefile
devicemodel/hw/pci/npk.c
devicemodel/include/npk.h

The Intel Trace Hub (aka. North Peak, NPK) is a trace aggregator for
Software, Firmware, and Hardware. On the virtualization platform, it
can be used to output the traces from SOS/UOS/Hypervisor/FW together
with unified timestamps.
There are 2 software visible MMIO space in the npk pci device. One is
the CSR which maps the configuration registers, and the other is the
STMR which is organized as many Masters, and used to send the traces.
Each Master has a fixed number of Channels, which is 128 on GP. Each
channel occupies 64B, so the offset of each Master is 8K (64B*128).
Here is the detailed layout of STMR:
M=NPK_SW_MSTR_STP (1024 on GP)
+-------------------+
|    m[M],c[C-1]    |
Base(M,C-1)  +-------------------+
|        ...        |
+-------------------+
|     m[M],c[0]     | …

DM: implement emulated npk pci device

---

hypervisor/arch/x86/vmx.c

This patch series ajust the order of control registers for more clear  in logic, but no change in guest init stage.
And in current code, on uefi platform, vmcs will be overwritten according to uefi context, using the exec_vmwrite directly. This patch series uses vmx_write_cr<#> interface to init control registers, which can be more clear, and some check logic can be reused.
Add comment to point out CR4 value should be inited before CR0, due to CR4 value will be checked when set CR0.

Refine guest control register initialization

---

devicemodel/samples/apl-mrb/launch_uos.sh

clearlinux package will remove ifconfig/brctl tools.

replace ifconfig & brctl with ip command

---

misc/cbc_lifecycle/cbc_lifecycle.service

The service type was set twice and inconsistent.
Reviewed-by: Miguel Bernal Marin <miguel.bernal.marin@linux.intel.com>

cbc_lifecycle: fix a service typo

---

tools/acrn-manager/acrn_mngr.h

There are some inappropriate descrition related to mngr, like "vmm msg".
Replace all "vmm" with "mngr".
No functional change.

tools: acrnctl: Fix wrong descrition of mngr

---

misc/cbc_attach/cbc_attach.service

This is one workaround patch to resolve read/write failed for /dev/cbc-lifecycle
and /dev/cbc-signals cdev nodes. It cause cbc_lifecycle service can't send
heartbeat to IOC firmware, also can't receive any signal data from IOC firmware.
This patch need to be revert once the IOC firmware or CBC driver fixed the root
cause.
The [-f] option means enable hardware flow control by set CRTSCTS attribute for
c_cflag of termios, without [-f] option will unset the attribute.
Reviewed-by: Vineetha G Jaya Kumaran <vineetha.g.jaya.kumaran@intel.com>
Reviewed-by: Alex Du <alek.du@intel.com>

IOC mediator: Disable hardware flow control by default

---

hypervisor/arch/x86/interrupt.c

if error code not valid, do not vmwrite VMX_ENTRY_EXCEPTION_EC. In cancel_event_injection, the
inject_info.error_core is not assigned if error code not valid.
Signed-off-by: Chris Ye <chris.ye@intel.com>

apicv: only write VMX_ENTRY_EXCEPTION_EC when error code valid

---

hypervisor/arch/x86/ept.c
hypervisor/arch/x86/vmexit.c
hypervisor/arch/x86/vmx.c
hypervisor/boot/acpi.c
hypervisor/include/lib/types.h
hypervisor/lib/sprintf.c
hypervisor/lib/string.c

MISRC C required pointer to zero should be replace with NULL

fix MISRA C"Literal zero used in pointer context"

---

hypervisor/arch/x86/guest/vioapic.c
hypervisor/arch/x86/guest/vlapic.c

V2->V3 modified the description
V1->V2 add __unused to handler_private_data
while misra c analyse callback function, it will dereference the pointer
plus an implicit getting address when extra parentheses with inner
star(example:(*foo)()). the first dereference should be removed.
reviewed-by: Li,Fei1 <fei1.li@intel.com>
reviewed-by: Junjie Mao <junjie.mao@intel.com>

fix MISRA C:"Statement with no side effect"

---

hypervisor/arch/x86/Kconfig

MTRR feature was added after commit bce7ed17151d4af96 ("HV: config:
add Kconfig and defconfigs"), so the generated config.h doesn't
include CONFIG_MTRR_ENABLED

hv: add MTRR_ENABLED entry to Kconfig

---

tools/acrn-manager/acrn_mngr.h

There is a mistake on description for mngr_send_msg() in acrn_mngr.h
We mistake the ack_len to req_len

Tools:acrn-manager Fix wrong description of mngr_send_msg()

---

hypervisor/arch/x86/assign.c
hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/guest/vioapic.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vlapic_priv.h
hypervisor/arch/x86/guest/vpic.c
hypervisor/arch/x86/interrupt.c
hypervisor/arch/x86/ioapic.c
hypervisor/arch/x86/irq.c
hypervisor/arch/x86/notify.c
hypervisor/arch/x86/vtd.c
hypervisor/include/arch/x86/guest/vcpu.h
hypervisor/include/arch/x86/guest/vioapic.h
hypervisor/include/arch/x86/guest/vlapic.h
hypervisor/include/arch/x86/guest/vpic.h
hypervisor/include/arch/x86/ioapic.h
hypervisor/include/arch/x86/irq.h

Currently irq and vector numbers are used inconsistently.
* Sometimes vector or irq ids is used in bit operations, indicating
that they should be unsigned (which is required by MISRA C).
* At the same time we use -1 to indicate an unknown irq (in
common_register_handler()) or unavailable irq (in
alloc_irq()). Also (irq < 0) or (vector < 0) are used for error
checking. These indicate that irq or vector ids should be signed.
This patch converts irq and vector numbers to unsigned 32-bit integers, and
replace the previous -1 with IRQ_INVALID or VECTOR_INVALID. The branch
conditions are updated accordingly.

irq: convert irq/vector numbers to unsigned

---

devicemodel/core/main.c

vmexit_pause should align with P(upper), added -b in usage print, remove some tab blank to keep make same indentation.
Signed-off-by: Chris Ye <chris.ye@intel.com>

align usage info with command line

---

tools/acrn-crashlog/README.rst
tools/acrn-crashlog/acrnprobe/README.rst
tools/acrn-crashlog/usercrash/README.rst

This patch adds the documents for acrn-crashlog:
README.rst: General introduction for acrn-crashlog.
acrnprobe/README.rst: Introduction for acrnprobe in detail.
usercrash/README.rst: Introduction for usercrash in detail.
Signed-off-by: Liu Xinwu <xinwu.liu@intel.com>

tools: acrn-crashlog: add documents for acrn-crashlog

---

devicemodel/samples/nuc/launch_uos.sh

we should use hugetlb as default uos memory allocation solution

nuc-samples: use huge page as default launch_uos cmdline

---

tools/acrn-crashlog/acrnprobe/README.rst

There is a mismatch in the 'telemetrics-clients' reference which
causes a warning (and a dead link).

Documentation: fix incorrect link in acrn-probe documentation

---

hypervisor/Makefile
hypervisor/arch/x86/guest/pm.c
hypervisor/arch/x86/guest/vm.c
hypervisor/bsp/include/bsp_extern.h
hypervisor/bsp/sbl/platform_acpi_info.c
hypervisor/bsp/uefi/platform_acpi_info.c
hypervisor/include/arch/x86/guest/pm.h
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/public/acrn_common.h

On some occations HV operates relying on host acpi info, eg. S3/S5/RTC...,
etc. Add ACPI parser code in HV would increase code size and complexity,
so a simple approach is use a c file to store all needed data in bsp.
Fow now we can store the data by hardcoding but we will provide a user
space tool shortly that run on target first to collect the data and then
generate the C file automatically.
The limitation is if ACPI data get changed due to BIOS update, we have to
regenerate the file and rebuild the HV. But this case is very rare.
Changelog:
v3:	Remove Kconfig for different ApolloLake SKU,
since all APL platform on SBL should use same
ACPI table except _PSS.
v2:	Add Kconfig support
v1:	Initial version

HV: add bsp acpi info support

---

devicemodel/samples/apl-mrb/launch_uos.sh

This patch is to limit the plane numbers in UOS as a workaround for
some known issues.

script: workaround to limit the plane numbers in UOS

---

doc/getting_started/index.rst

This update is to reflect the changes for acrnbridge to start
with systemd-networkd instead of running a script.
Requested by Eddie to go PR to be reviewed by David
Signed-off-by: Tan Shen Joon <shen.joon.tan@intel.com>

update documentation for acrnbridge

---

tools/Makefile
tools/acrn-manager/Makefile

The debug macro -DMNGR_DEBUG is selected by RELEASE value.
E.g., run 'make RELEASE=1' at the root of source code.

Tools:acrn-manager: use RELEASE in Makefile

---

hypervisor/arch/x86/softirq.c
hypervisor/common/hv_main.c
hypervisor/include/lib/bits.h

HV: bug fix in operating softirq
a. handle a race condition in current softirq code.
b. add volatile declaration to pointer parameter in current bit operation code.

Handle softirq race condition

---

hypervisor/arch/x86/guest/vcpu.c

HV: fix a print typo in create_vcpu

---

hypervisor/arch/x86/guest/vpic.c
hypervisor/arch/x86/vmexit.c
hypervisor/arch/x86/vtd.c

There are some __unused attached to variables. But, those variables
are used by the function actually.
This patch remove them. No functional change.

HV: Remove misuesed __unused

---

hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/include/arch/x86/guest/vlapic.h

This change is to fix a guest vm hang issue at vm reset, especially easy to
be seen when it's a watchdog timeout reset.
vlapic_init create and init vlapic.vlapic_timer without deleting the
timer from cpu_times list, which breaks the list, results in a timer remains
with callback points to an invalid location.

hv: replace vlapic_init by vlapic_reset in vcpu_reset

---

tools/acrn-crashlog/Makefile

This patch is to fix libtelemetry.so typo in Makefile.
Signed-off-by: Liu Xinwu <xinwu.liu@intel.com>

tools: acrn-crashlog: fix typo in Makefile

---

Makefile
doc/Makefile
doc/acrn.doxyfile

There are multiple commits in this PR as there were some (unrelated) problems that I had to fix in order to test my changes.
**Note:** that this does **not** enable the documentation build by default but with this, we're one very short step away from enabling it (and which would allow us to close #218).
**Note2:** the documentation build is still broken since we merged #387 . A fix for that is being reviewed on the mailing list so it's not being addressed in this PR.

Add `make doc` target to top-level Makefile

---

hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vlapic_priv.h

Enable guest LAPIC one-shot/periodic timer support.
Change-Id: I368e28beaa81d6566de2626bbe26c9f8972f0891
v1 - v2 rename set_target_expiration to set_expiration

hv: vlapic_timer: add vlapic one-shot/periodic timer support

---

hypervisor/Makefile
hypervisor/arch/x86/assign.c
hypervisor/common/ptdev.c
hypervisor/include/arch/x86/assign.h
hypervisor/include/common/ptdev.h

Move common stuff, like ptdev entry and softirq, to new ptdev.c

HV: move common stuff from assign.c

---

hypervisor/arch/x86/vmx.c

This reverts commit 3a3aeac09f477d5cba7bb85be2c0e9c7f9d0bf72.
MTRR has been emulated in hypervisor, then don't need this workaround
patch.
Signed-off-by: Fei Jiang <fei.jiang@intel.com>

Revert "VMX: change PAT register default value"

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/mmu.c
hypervisor/include/arch/x86/cpu.h
hypervisor/include/arch/x86/mmu.h

- this patch is to enable SMEP in hypervisor, SMEP protects
guests' memory from supervisor-mode instruction fetches,
in other words, hypervisor which operating in supervisor
mode can't fetch instructions from (guests' memory)
linear addresses that are accessible in user mode.

HV: enable SMEP in hypervisor

---

hypervisor/arch/x86/cpu.c

cpu_find_logical_id() is called redundantly, remove one.

HV: remove redundant code in cpu_secondary_init

---

doc/howtos/process/docbuild.rst
doc/scripts/requirements.txt

The latest versions of Sphinx and Breathe work well together so we're
updating the requirements.txt installation information (and
documentation) to use the latest versions of these tools.
Fixes: #395

doc: update doc building tools versions

---

.gitignore
doc/Makefile
doc/index.rst
doc/reference/kconfig/readme.txt
doc/scripts/genrest.py
doc/scripts/requirements.txt

Modify the Zephyr project script for creating documentation from Kconfig
files to generate the hypervisor option configuration docs.

doc: add hypervisor kconfig option reference

---

hypervisor/lib/udelay.c

Changed the CYCLES_PER_MS to US_TO_TICKS

udelay waits for corresponding number of milliseconds passed to API.

---

hypervisor/arch/x86/assign.c

remove_intx_remapping is not global function.
Unlike global functions in C, access to static functions is restricted to the file where they are declared. Another reason for making functions static can be reuse of the same function name in other files
Signed-off-by: Chris Ye <chris.ye@intel.com>

bugfix: make remove_intx_remapping static

---

hypervisor/debug/shell_internal.c
hypervisor/debug/shell_internal.h
hypervisor/debug/shell_public.c

this patch add shell command trigger crash for testing crashmode/ramdump
Signed-off-by: zhouji3x <jianfengx.zhou@intel.com>

hv: add shell command to trigger crash

---

tools/Makefile
tools/acrn-manager/Makefile
tools/acrnlog/Makefile

1. mkdir ./tools/build if it does not exist;
2. correct static lib path for acrn-manager;
3. do not remove acrnlog.service if build under source code dir by default.
Reviewed-by: Geoffroy VanCutsem <geoffroy.vancutsem@intel.com>

tools: correct several Makefile problems

---

tools/acrnlog/README.rst
tools/acrnlog/acrnlog.c

1. add warning when log incompleteness observed;
2. decrease default polling interval to reduce chance of log incompleteness;
3. add option "-t" to allow user to specify the polling interval;
4. modified README.rst to reflect the options.

tools: acrnlog: improve for log incompleteness problem

---

hypervisor/arch/x86/assign.c
hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/guest/vioapic.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/interrupt.c
hypervisor/arch/x86/intr_lapic.c
hypervisor/arch/x86/irq.c
hypervisor/arch/x86/timer.c
hypervisor/arch/x86/vtd.c
hypervisor/common/hv_main.c
hypervisor/common/io_request.c
hypervisor/debug/console.c
hypervisor/debug/vuart.c
hypervisor/include/arch/x86/guest/guest.h
hypervisor/include/arch/x86/guest/vcpu.h
hypervisor/include/arch/x86/guest/vioapic.h
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/arch/x86/irq.h
hypervisor/include/arch/x86/lapic.h
hypervisor/include/arch/x86/timer.h
hypervisor/include/arch/x86/vmexit.h
hypervisor/include/common/ptdev.h
hypervisor/include/lib/spinlock.h
hypervisor/lib/spinlock.c

MISRA C required that return value should be used, missing for it should
add "(void)" prefix before the function call.
Some function can be declared without return value to avoid this problem.

fix parted of "missing for discarded return value"

---

hypervisor/debug/dump.c

This patch is for crashmode/ramdump. when exception occur:
1) save registers;
2) flush cache
Signed-off-by: zhouji3x <jianfengx.zhou@intel.com>

hv: save registers on exception

---

tools/acrn-crashlog/acrnprobe/android_events.c
tools/acrn-crashlog/acrnprobe/channels.c
tools/acrn-crashlog/acrnprobe/crash_reclassify.c
tools/acrn-crashlog/acrnprobe/history.c
tools/acrn-crashlog/acrnprobe/include/load_conf.h
tools/acrn-crashlog/acrnprobe/load_conf.c
tools/acrn-crashlog/acrnprobe/main.c
tools/acrn-crashlog/acrnprobe/probeutils.c
tools/acrn-crashlog/acrnprobe/sender.c

The aim of this patch set is to fix potential issues, which are reported by
static analysis tool, for acrnprobe.
For the convenience of review, break it into two patches.

 tools: acrn-crashlog: fix potential issues for acrnprobe

---

tools/acrnlog/README.rst

A merged change had problems with the formatting of acrnlog options.

doc: fix formatting in acrnlog doc

---

devicemodel/hw/pci/core.c

acrn-dm runs to segmentation fault when failed to create VMs with
improper parameters.
If vdevs failed to be created, they are still be freed in deinit(),
and dereference the null pointers leads to segfault.

dm: check pci_vdev before using

---

hypervisor/arch/x86/guest/vlapic.c
hypervisor/include/arch/x86/guest/vlapic.h

change the argument 'cpu_id' to 'vcpu_id'

HV: 'vlapic_set_local_intr()' code cleanup

---

tools/acrn-crashlog/common/cmdutils.c
tools/acrn-crashlog/common/fsutils.c
tools/acrn-crashlog/common/log_sys.c
tools/acrn-crashlog/common/strutils.c
tools/acrn-crashlog/usercrash/client.c
tools/acrn-crashlog/usercrash/crash_dump.c
tools/acrn-crashlog/usercrash/debugger.c
tools/acrn-crashlog/usercrash/include/packet.h
tools/acrn-crashlog/usercrash/protocol.c
tools/acrn-crashlog/usercrash/server.c

This patch is to fix potential issues, which are reported by static
analysis tool, for common and usercrash.
Changes:
1. Handle the fd properly in the failing case.
2. Fix buffer overflow issues and null pointer access issues.
3. Fix the format issue in log_sys.c.
4. Remove the useless branch and adjust the function logic.
5. Add some checks for the string length before using strcpy/strcat/memcpy.
6. Fix strncpy warning issues.
7. Change the return value to unify the return type.
Reviewed-by: Liu Xinwu <xinwu.liu@intel.com>

tools: acrn-crashlog: fix potential issues under common and usercrash

---

hypervisor/arch/x86/irq.c

When guest frees vector, counts needs to be reset. "int" command from hv shell ends up incrementing per cpu irq_count. Fixed it.

irq_count accounting

---

hypervisor/include/debug/console.h

function definition in header file must be signed as static inline type
Signed-off-by: Cai Yulong <yulongc@hwtc.com.cn>

hv: fix compile error

---

hypervisor/include/common/ptdev.h

Vectors are unsigned integers now. This patch converts the vectors in struct
ptdev_msi_info to uint32_t so that all variables representing interrupt vectors
are aligned.
No other changes needed except the type declarators since the other functions
manipulating vectors already takes/returns uint32_t.

HV: ptdev: convert vectors in msi_info to unsigned integers

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/guest/guest.c
hypervisor/arch/x86/guest/instr_emul.c
hypervisor/arch/x86/guest/vioapic.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/ioapic.c
hypervisor/arch/x86/vtd.c
hypervisor/include/arch/x86/vtd.h

MISRA C doesn't allowed negative shift, changed any potential signed value
to unsigned value.

 fix "negative shift" 

---

hypervisor/arch/x86/ept.c
hypervisor/arch/x86/guest/guest.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/mmu.c
hypervisor/arch/x86/mtrr.c
hypervisor/arch/x86/trusty.c
hypervisor/common/hypercall.c
hypervisor/include/arch/x86/mmu.h

v1-v2:
1. minor fix when mask EPT cache type.
v1:
Now the hv mmu & ept map/unmap/modify logic is not clear. Map may map
mapped page tables; unmap may unmap non-mapped or unmapped page tables;
modify may modify gfn to mfn mapping besides page table attributes or
modify non-mapped page table.
We want to change this. Let's set some rules first:
1. map can only map unmapped page tables
2. unmap can only unmap mapped page tables;
3. modify can only modify mapped page tables' attributes.
Besides, we want to move configure page table attributes outsides internal
implement logic.
This patch is the serial one.
After this serial, we can achieve:
1. We would not unmap unmap non-mapped or unmapped page tables;
2. set page tables attributes at frist before call internal implement function.
Next will …

hv mmu & ept revisit

---

hypervisor/arch/x86/guest/guest.c
hypervisor/boot/sbl/multiboot.c
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/hypervisor.h

Update the structure definition to define the address type
(HVA vs HPA vs GPA) explicitly.
Convert address to HVA before access the GPA/HPA type of address.

hv: refine the address used in sbl multiboot code

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/irq.c
hypervisor/arch/x86/mmu.c
hypervisor/arch/x86/softirq.c
hypervisor/arch/x86/timer.c
hypervisor/common/hv_main.c
hypervisor/common/schedule.c
hypervisor/debug/logmsg.c
hypervisor/debug/sbuf.c
hypervisor/include/arch/x86/irq.h
hypervisor/include/arch/x86/per_cpu.h
hypervisor/include/debug/trace.h

phys_cpu_num is more popular than phy_cpu_num, update them
through command.

Rename phy_cpu_num as phys_cpu_num

---

hypervisor/bsp/uefi/efi/Makefile

The previous logic assumes LIBDIR to be /usr/lib64 if it exists.
some x86_64 distros, like ubuntu and debian, the default x86_64 libs(gnu-efi)
are installed into /usr/lib while /usr/lib64 is for i386
~/workspace$ dpkg -L gnu-efi | grep elf_x86_64_efi.lds
/usr/lib/elf_x86_64_efi.lds
~/workspace$ dpkg -S /usr/lib64
libc6-amd64:i386: /usr/lib64
so it failed to compile efi perviously as following errors:
-----------------
ld: cannot open linker script file /usr/lib64/elf_x86_64_efi.lds: No such file or directory
Makefile:102: recipe for target '/home/lizj/workspace/acrn-hypervisor/build/hypervisor/bsp/uefi/efi/boot.so' failed
make[2]: *** [/home/lizj/workspace/acrn-hypervisor/build/hypervisor/bsp/uefi/efi/boot.so] Error 1
make[2]: Leaving directory …

HV Makefile: fix detection of gnu-efi tools location

---

doc/getting_started/index.rst

Add some basic development tools needed to build the ACRN project.
These were not specifically called out (although most likely
already installed in any development system).

Getting Started Guide: update build dependencies and tools

---

hypervisor/arch/x86/cpu_primary.S
hypervisor/arch/x86/trampoline.S
hypervisor/arch/x86/vmx_asm.S

MISRA C requires that unsigned constants should have the 'U' suffix, while this
C syntax is not accepted by binutils assembler per binutil manual.
This patch explicitly spells out the unsigned constants used in the assembly
files while tracking the original expressions in comments. This fixes build
failure when using binutils <= 2.26.
This patch fixes #480.
v2 -> v3:
* Explicitly spell out the unsigned constants in assembly, instead of
duplicating the macros in headers which break the integrity of the
definitions.
v1 -> v2:
* Define different macros instead of wrapping all unsigned constants.

HV: treewide: fix C-style unsigned constants in assembly

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/cpu_primary.S
hypervisor/arch/x86/trampoline.S

for bsp_boot_init/cpu_secondary_init, they are on temp stack.
for bsp_boot_post/cpu_secondary_post, they are on runtime stack.
define SWITCH_TO MACRO to switch runtime stack then jump to post functions.

init: separate init function based on different stack

---

.travis-dockerfiles/Dockerfile.centos7
.travis-dockerfiles/Dockerfile.clearlinux
.travis-dockerfiles/Dockerfile.debian8
.travis-dockerfiles/Dockerfile.fedora26
.travis-dockerfiles/Dockerfile.fedora27
.travis-dockerfiles/Dockerfile.fedora28
.travis-dockerfiles/Dockerfile.ubuntu14.04
.travis-dockerfiles/Dockerfile.ubuntu16.04
.travis-dockerfiles/Dockerfile.ubuntu18.04
.travis-dockerfiles/README.md

This adds Python3 and the 'kconfiglib' tool to all Dockerfiles.
This is required in order to build (and/or configure) the ACRN
hypervisor.
It also adds 'findutils' to all Fedora Dockerfiles as both 'find'
and 'xargs' are used in some Makefiles and provided by this package.

Dockerfiles: add Python3 and kconfiglib build dependency

---

hypervisor/Makefile

For hypervisor, we initliaze the flags used in build command
to empty to avoid flags set in default env impact to hypervisor
build.
Acked-by: VanCutsem Geoffroy <geoffroy.vancutsem@intel.com>

hv: Makefile flags initialization

---

hypervisor/arch/x86/ioapic.c
hypervisor/arch/x86/irq.c

Fix the type for vector in ioapic setup, which is a potential problem:
- return VECTOR_INVALID instead of false in irq_desc_alloc_vector()
when irq is out of range;
- change variable type from int to uint32_t for vector, and correct
the returned value check.

hv: irq: fix type for vector in ioapic setup

---

devicemodel/hw/pci/passthrough.c

This helps achieving valid dev state after UOS restart

DM: reset each ptdev before assignment

---

hypervisor/include/arch/x86/guest/guest.h

The for loop statement should work in both & and &&, but it seems
make more sense to have && when executing a condtion.

guest.h: Condition operator fix of foreach_vcpu loop

---

devicemodel/Makefile
devicemodel/hw/pci/virtio/virtio_audio.c

Add the device model of audio mediator, and enable it in Makefile. In the launch script add "-s <slot number>, virtio-audio" to add the audio virtual PCI device.

Audio mediator device model

---

hypervisor/common/hv_main.c
hypervisor/common/hypercall.c
hypervisor/common/io_request.c
hypervisor/common/schedule.c
hypervisor/common/trusty_hypercall.c
hypervisor/common/vm_load.c
hypervisor/include/arch/x86/cpu.h
hypervisor/include/arch/x86/guest/guest.h

The local variable type should be transfer to non-basic type,
chaned it to length-prefix(uint32_t,int32_t ...) type.
Char *type or char array type which used to pointer a string
will be keeped.
V1->V2 add extra comments.

HV:common:transfer local variable type

---

hypervisor/arch/x86/guest/vpic.c

This patch series cleans up the integral types in vpic by changing icw_num and rd_cmd_reg to uint8_t, converting port addresses and width to be unsigned in alignment with the general port I/O interfaces, and fixing the uses of boolean variables.

HV: vpic: cleanup integral types

---

devicemodel/Makefile
hypervisor/Makefile
tools/acrn-crashlog/acrnprobe/Makefile
tools/acrn-crashlog/usercrash/Makefile

Some build environment might has no USER pre-defined. So use id tool to
get builder username instead of USER environemnt.
Also add a version cleanup for tools to keep them updated.

build: Using id tool to get builder username

---

devicemodel/core/main.c
devicemodel/core/vmmapi.c
devicemodel/include/public/vhm_ioctl_defs.h
devicemodel/include/vmmapi.h
devicemodel/samples/apl-mrb/launch_uos.sh
devicemodel/samples/nuc/launch_uos.sh
doc/getting_started/index.rst

v1-v2:
1. remove how to support cma document.
2. remove sample script about how to use hugetlb by default 
3. remove git commit changed-id
v1:
Now the hv mmu & ept map/unmap/modify logic is not clear. Map may map 
mapped page tables; unmap may unmap non-mapped or unmapped page tables;
modify may modify gfn to mfn mapping besides page table attributes or
modify non-mapped page table.
We want to change this. Let's set some rules first:
1. map can only map unmapped page tables
2. unmap can only unmap mapped page tables;
3. modify can only modify mapped page tables' attributes.
Besides, we want to move configure page table attributes outsides internal
implement logic.
This patch is the serial two 1st half.
After this serial, we can achieve:
1. emove cma support in the dm;
Note:
We should …

hv mmu & ept revisit serial 2

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/lapic.c
hypervisor/arch/x86/vtd.c
hypervisor/include/arch/x86/cpu.h
hypervisor/include/arch/x86/lapic.h

According intel mannual and ACPI mannual,lapic_id length is 1 byte.
V1->V2:
Add U suffix to the numeric when do arithmetic operation on lapic.

modified the lapic_id type to uint8_t

---

tools/acrn-crashlog/acrnprobe/android_events.c
tools/acrn-crashlog/acrnprobe/include/android_events.h
tools/acrn-crashlog/acrnprobe/include/load_conf.h
tools/acrn-crashlog/acrnprobe/load_conf.c
tools/acrn-crashlog/acrnprobe/main.c
tools/acrn-crashlog/acrnprobe/property.c
tools/acrn-crashlog/acrnprobe/sender.c
tools/acrn-crashlog/common/fsutils.c
tools/acrn-crashlog/common/include/fsutils.h
tools/acrn-crashlog/common/include/strutils.h
tools/acrn-crashlog/common/strutils.c

In the original design, acrnprobe marked all handled VMs'events as "synced"
in file vmrecordid(this patch changes the name to VM_eventsID.log).
Currently, the Android log events are not logged if the first attempt at
reading collecting them from the VM fails. This patch changes the logic
so that the acrn-crashlog tool will retry continuously.
This patch defines different tags for handled VMs'events, and only marks
VMs'events "synced" after it returns successfully.
Reviewed-by: xiaojin2 <xiaojing.liu@intel.com>
Reviewed-by: Jin Zhi <zhi.jin@intel.com>
Acked-by: Chen gang <gang.c.chen@intel.com>

tools: acrn-crashlog: Defer the vm events processing when failed

---

hypervisor/bsp/uefi/cmdline.c
hypervisor/debug/shell_internal.c
hypervisor/include/lib/rtl.h
hypervisor/lib/string.c

- replace 'strtol()' with 'strtol_deci()'
-- supports string with decimal format
- replace 'strtoul()' with 'strtoul_hex()'
-- support string with hex format

HV:- Refine strtol() & strtoul()

---

hypervisor/arch/x86/guest/vcpu.c
hypervisor/debug/vuart.c
hypervisor/include/arch/x86/gdt.h
hypervisor/include/arch/x86/guest/vcpu.h
hypervisor/include/arch/x86/idt.h
hypervisor/include/arch/x86/io.h
hypervisor/include/common/schedule.h

The struct member types should be transfer to non-basic types,
chaned it to length-prefix(uint32_t,int32_t ...) type.

HV:treewide:transfer the struct member types to non-basic types

---

misc/cbc_attach/Makefile
misc/cbc_attach/cbc_attach.c
misc/cbc_attach/cbc_attach.service

This patch resolved systemd be blocking for 20 seconds due to waiting the
"READY=1" from cbc_attach. And cbc_attach will retry 60 sec at the worst case
which can be reproduced on non-IOC boards.
This is one temporary solution. The final solution need modify SBL to export IOC
ACPI device through ACPI table, and also Linux IOC CBC driver need trigger
uevent which should be the trigger of launching cbc_attach service.
This patch changes the service type to simple instead of notify due to systemd is
needn't wait cbc related services. And change Restart to no due to cbc_attach
already has retry mechanism.
These changes are also reasonable for the board integrated IOC component.
So they should be keep even the long term final solution implemented. …

misc: fix cbc_attach blocks APL NUC boot for 20 seconds

---

doc/getting-started/apl-nuc.rst

Fix a minor rendering issue in the Getting Started Guide where a
code-block is not appearing as such.

Documentation: fix minor rendering issue in GSG

---

doc/tutorials/static-ip.rst

Add a tutorial on how to change the default configuration that
uses DHCP and assign a static IP address to the system.

Documentation: add tutorial to set up a static IP address

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/guest/vcpu.c
hypervisor/include/arch/x86/cpu.h
hypervisor/include/arch/x86/guest/vcpu.h
hypervisor/include/arch/x86/softirq.h
hypervisor/include/common/schedule.h
hypervisor/include/lib/bits.h

For reducing sign conversion in hypervisor:
Update parameters of bitmap operations as unsigned type;
Update the input of related caller as unsigned type when the
caller's input parameter is const variable or the variable is
only used by bitmap operations.
V1-->V2:
(1) Explicit casting for the first parameter
of all bitmap operations;
(2) Remove mask operation for explicit casting
of all bitmap operations, since masking is
useless. Otherwise, this trucation is dangerous.
V2-->V3:
(1) Explicit casting for all bitmap operations parameter;
(2) Masking bit offset with 6-bit;
(3) Add few comments about bit offset.
V3-->V4:
add '\' for some statement of bitmap macro

HV:treewide:Cleanup the type for parameters of bitmap operations

---

hypervisor/arch/x86/mmu.c
hypervisor/include/arch/x86/mmu.h

struct map_params's member page_table_type is enum _page_table_type,
transferred it.

HV:transfer page_table_type type

---

hypervisor/arch/x86/guest/vm.c
hypervisor/debug/shell_internal.c
hypervisor/include/arch/x86/guest/vm.h

We define attr.name in struct vm and named as ("vm_%d", attr.id). attr.name only
be used in debug tool vm_list. It does't deserve to do so in OS created flow
(aka function create_vm). It's better to handle this in vm_list tool.
Acked-by: Eddie Dong <eddie.dong@inte.com>

HV: Remove vm->attr.name

---

hypervisor/arch/x86/cpu.c
hypervisor/include/arch/x86/cpu.h
hypervisor/include/arch/x86/per_cpu.h

enum cpu state is better than cpu state macro.
V1->V2:
move enum cpu_state under #ifndef ASSEMBLER MACRO to avoid
assembler compiler scan.

HV:change the cpu state to enum type

---

hypervisor/lib/string.c

lib/string.c: In function 'strtoul_hex':
lib/string.c:25:26: warning: suggest parentheses around comparison in
operand of '&' [-Wparentheses]
.define ISSPACE(c) (((c) & 0xFFU == ' ') || ((c) & 0xFFU == '\t'))

HV: Fix compiler warnings in string.c

---

devicemodel/core/inout.c
devicemodel/core/main.c
devicemodel/include/inout.h

- UOS will boot fail if 'strictio' is enabled ('-e' option), in this
case (with '-e'), device model will block all PIO accesses whose
handlers were not registered, after that, device model program will
exit, hence UOS boot fail.
actually, such kind of accesses exist, e.g. UOS would program
PIT registers (port address: 0x43) if hpet is disabled.
- For debug, we can trap unexpected PIO access in 'default_inout()'

DM: Remove 'strictio' from UOS bootargs' options

---

hypervisor/arch/x86/assign.c
hypervisor/arch/x86/guest/vioapic.c
hypervisor/arch/x86/ioapic.c
hypervisor/arch/x86/irq.c
hypervisor/common/hv_main.c
hypervisor/common/io_request.c
hypervisor/include/arch/x86/guest/guest.h
hypervisor/include/arch/x86/guest/vioapic.h
hypervisor/include/arch/x86/ioapic.h
hypervisor/include/arch/x86/irq.h
hypervisor/include/arch/x86/vmexit.h
hypervisor/include/common/ptdev.h

There are multiple helpers for collecting info to be printed on the ACRN uart
console. They are unreachable code in release builds in which the uart console
is removed.
To define a precise boundary for safety-related activities, this patch wraps the
declarations and definitions to these helpers with "#ifdef HV_DEBUG" so that
these unreachable APIs will be dropped in release builds.
v1 -> v2:
* Fix coding style: no empty lines between #ifdef and the wrapped code.
* Also drop get_rte_info() in ioapic.c, which is solely used by
get_ioapic_info().

HV: treewide: drop debug-only helpers in release build

---

hypervisor/arch/x86/guest/guest.c
hypervisor/boot/sbl/multiboot.c

Function prepare_vm0_memmap_and_e820 and init_vm0_boot_info are specific for vm0.
There is no need to check is_vm0 again in those functions.
This patch remove the unnecssary checks.
v1 -> v2:
- Add pre-condition comment before the function as Junjie's suggestion.

HV: Remove unnecessary vm0 check in vm0 specific func

---

hypervisor/arch/x86/guest/guest.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vpic.c
hypervisor/arch/x86/softirq.c
hypervisor/common/hypercall.c
hypervisor/common/schedule.c
hypervisor/include/arch/x86/cpu.h
hypervisor/include/arch/x86/cpuid.h
hypervisor/include/arch/x86/guest/vlapic.h
hypervisor/include/arch/x86/softirq.h
hypervisor/include/lib/bits.h
hypervisor/include/lib/mem_mgt.h
hypervisor/lib/div.c
hypervisor/lib/memory.c

Update return value type as unint16 for bit operations
Update the type of bit index, vcpu id, softirq id, 
event id as uint16_t to reduce type conversion, the 
following steps are doing:
(1) Update return value type for fls and clz;
(2) Update return value type for fls64 and clz64;
(3) Update return value type for ffs64 and ffz64.
For each step, for the related caller,the type of
variables which store return value is updated as
uint16_t and return value checking is updated.
V1-->V2:
INVALID_BIT_INDEX instead of INVALID_NUMBER;
INVALID_CPU_ID instead of INVALID_PCPU_ID or INVALID_VCPU_ID;
"%hu" is used to print vcpu id (uint16_t);
Add 'U/UL' for constant value as needed.
V2-->V3:
Clean up extra updates, such as add "%hu";
For bit operations, it return INVALID_BIT_INDEX
directly when input …

Update return value type as unint16 for bit operations

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/cpuid.c
hypervisor/arch/x86/timer.c
hypervisor/common/hv_main.c
hypervisor/debug/logmsg.c
hypervisor/include/lib/rtl.h
hypervisor/lib/udelay.c

Representing TSC freqeuency in Hz generally needs a uint64_t with range checks
upon use to avoid integer overflow. This patch series uses KHz instead to reduce
the TSC frequency to a uint32_t.

HV: timer: convert tsc_hz to tsc_khz

---

misc/cbc_attach/Makefile
misc/cbc_lifecycle/Makefile

The install -D is misleading people since it only creates the leading
directories.
The problem was hidden due to we always call make install and the
destination folder was already created in previous install script.

cbc: fix the install issue when do make misc-install only

---

tools/acrn-crashlog/Makefile

This patch is to fix the dependency issue with autospec.
Using ldconfig in the autospec build environment is not
going to work as the packages do not have the cache
generate after a rpm install. This patch replaces ldconfig
with pkg-config to check the existance of the libraries.
Reviewed-by: Jin Zhi <zhi.jin@intel.com>
Reviewed-by: Liu Xinwu <xinwu.liu@intel.com>

tools: acrn-crashlog: replace ldconfig with pkg-config in Makefile

---

hypervisor/arch/x86/vmx.c

There are some cases that we write to VMX_HOST_XXX regs but have debug message
like "pr_dbg("VMX_GUEST_XXX ...")".

HV: Fix wrong log message in init_host_state

---

hypervisor/arch/x86/guest/vlapic.c
hypervisor/include/lib/bits.h

Rename bit operation function fls as fls32, keep name
style with other bit operation function.

HV:treewide: Rename bit operation function fls as fls32

---

doc/tutorials/static-ip.rst

Clear Linux is a stateless system, also systemd.
https://clearlinux.org/features/stateless
This tutorial advice to modify a file in /usr/lib which is used by vendors.
Instead of that, this change advice to use the local administration
network directory at /etc/systemd/network.
See more reference using:
man systemd.network
Fixes: 25eae47836b9 ("Documentation: add tutorial to set up a static IP address")

Documentation: fix set up a static IP tutorial

---

hypervisor/arch/x86/guest/instr_emul_wrapper.c

We pass retval to vmm_emulate_instruction and assign the return value to retval
at the same time. The retval will be passed to mmio_read/write finally as memarg
and the functions don't use the parameter actually. Apparently, we misused the
retval.
This patch fix it by passing 'NULL' to vmm_emulate_instruction.

HV: Don't pass retval to vmm_emulate_instruction()

---

hypervisor/include/debug/logmsg.h

logmsg() expects the severity given to be uint32_t. This patch adds the 'U'
suffix to the severity constants.

HV: debug: make log severity constants unsigned

---

hypervisor/arch/x86/ept.c
hypervisor/arch/x86/guest/guest.c
hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/io.c
hypervisor/arch/x86/mtrr.c
hypervisor/common/hypercall.c
hypervisor/common/io_request.c
hypervisor/common/vm_load.c
hypervisor/debug/dump.c
hypervisor/debug/shell_internal.c
hypervisor/include/arch/x86/guest/guest.h
hypervisor/include/arch/x86/guest/vcpu.h
hypervisor/include/arch/x86/guest/vlapic.h

In the hypervisor, virtual cpu id is defined as "int" or "uint32_t"
type in the hypervisor. So there are some sign conversion issues
about virtual cpu id (vcpu_id) reported by static analysis tool.
Sign conversion violates the rules of MISRA C:2012.
BTW, virtual cpu id has different names (vcpu_id, cpu_id, logical_id)
for different modules of HV, its type is defined as "int" or "uint32_t"
in the HV. cpu_id type and logical_id type clean up will be done in
other patchs.
V1-->V2:
More clean up the type of vcpu id;
"%hu" is for vcpu id in the print function.

HV:Treewide:Update the type of vcpu id as uint16_t

---

hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/irq.c
hypervisor/arch/x86/lapic.c
hypervisor/arch/x86/softirq.c
hypervisor/common/hv_main.c
hypervisor/debug/dump.c
hypervisor/debug/logmsg.c
hypervisor/include/arch/x86/guest/vcpu.h
hypervisor/include/arch/x86/irq.h
hypervisor/include/debug/dump.h
hypervisor/include/debug/logmsg.h

There are extra type conversion in the HV since cpu_id
type is uint32_t and the return value type of get_cpu_id
is uint16_t. BTW, the name of cpu_id is not clear enough
to express its usage.
So the following updates are made in this patch:
Update cpu_id type as unit_16 to reduce type casting;
Update related temporary variables type;
Update related print argument;
Change the input parameter name of interrupt_init as
cpu_id to keep align with function implement;
Rename related cpu_id as pcpu_id as needed.

HV:treewide:Update cpu_id type as uint_16 and rename related cpu_id

---

hypervisor/arch/x86/cpu.c
hypervisor/include/arch/x86/cpu.h

There are extra type conversion in the HV since logical_id
type is uint32_t and the input argument of bitmap operations
is uint16_t. BTW, the name of logical_id is not clear enough
to express its usage.
So the following updates are made in this patch:
Update logical_id type as unit_16 to reduce type casting;
Update related print argument;
Rename related logical_id as pcpu_id as needed.
Note: logical_id in the interrupt_init definition have been
updated in cpu_id cleanup patch.

HV:CPU:Update logical_id type as uint_16 and rename logical_id

---

hypervisor/arch/x86/guest/vioapic.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/ioapic.c
hypervisor/arch/x86/pm.c
hypervisor/debug/shell_internal.c

- replace MACROs with inline functions
- remove unused local viarbles
- fix build errors

HV: cleanup coding style violation

---

hypervisor/arch/x86/guest/vlapic.c
hypervisor/include/arch/x86/guest/vlapic.h

rename 4 APIs:
x2apic_msr -> is_ x2apic_msr
vlapic_msr -> is_vlapic_msr
vlapic_mmio_write -> vlapic_write_mmio_reg
vlapic_mmio_read -> vlapic_read_mmio_reg

hv:rename several APIs in vlapic.c

---

hypervisor/arch/x86/cpu.c
hypervisor/boot/acpi.c
hypervisor/debug/dump.c
hypervisor/debug/serial.c
hypervisor/debug/serial_internal.h
hypervisor/debug/shell_internal.h
hypervisor/debug/shell_public.c
hypervisor/include/debug/assert.h

In the hypervisor, some strings are assigned to non const
object, this violates MISRA C:2012.
Update the type of the object as const type since it always
points to string.

HV:treewide:string assigned to const object

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/trampoline.S
hypervisor/include/arch/x86/cpu.h

- rename 'cpu_set_logical_id()' to 'set_current_cpu_id()'
- rename 'cpu_find_logical_id()' to 'get_cpu_id_from_lapic_id()'
- some clean up in cpu.c & trampolines.s

HV: rename functions in cpu.c

---

devicemodel/include/vmm.h
hypervisor/arch/x86/guest/instr_emul.c
hypervisor/arch/x86/guest/instr_emul.h
hypervisor/arch/x86/guest/instr_emul_wrapper.c
hypervisor/arch/x86/guest/instr_emul_wrapper.h
hypervisor/include/arch/x86/vmx.h

Though the fields in the structures used in the instruction emulator has                                                                                                                                            
well-defined signedness and width, plain 'int' is widely seen in the                                                                                                                                                
implementation, giving rise to lots of violations to MISRA C rules related to                                                                                                                                       
integral types. …

HV: instr_emul: integral type revisit

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/cpu_state_tbl.c
hypervisor/arch/x86/ept.c
hypervisor/arch/x86/guest/guest.c
hypervisor/arch/x86/guest/instr_emul.c
hypervisor/arch/x86/guest/pm.c
hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vmsr.c
hypervisor/arch/x86/io.c
hypervisor/arch/x86/irq.c
hypervisor/arch/x86/mmu.c
hypervisor/arch/x86/trusty.c
hypervisor/boot/sbl/hob_parse.c
hypervisor/bsp/uefi/efi/boot.c
hypervisor/bsp/uefi/efi/malloc.c
hypervisor/common/hypercall.c
hypervisor/common/vm_load.c
hypervisor/debug/logmsg.c
hypervisor/debug/printf.c
hypervisor/debug/shell_internal.c
hypervisor/lib/memory.c
hypervisor/lib/spinlock.c
hypervisor/lib/sprintf.c

No need to check the return value for memset
code like this:
int a(void) {
return 0;
}
int b(void){
a();
}
fix as follow:
int a(void) {
return 0;
}
int b(void){
(void)a();
}

hv:fix "missing for discarded return value" for memset

---

hypervisor/arch/x86/guest/vioapic.c
hypervisor/include/arch/x86/guest/vioapic.h
hypervisor/include/public/acrn_common.h

IOAPIC pins always fit in 8-bit and we already use uint8_t for virt_pins. This
patch converts pins in vioapic to uint8_t.
This is based on Arindam's previous patch ("was: hv: Cleanup and optimise
vioapic.c"), with SOS boot failure resolved, format string updated, complex
arithmetic expression with implicit type conversion decoupled. Also make some
local variables representing interrupt vectors uint32_t.

HV: vioapic: use uint8_t for pins

---

hypervisor/debug/uart16550.c

To prevent the value is devided by zero, checks the denominator
before the calculation. Adding the if statement to check before use.
If the baud_rate is equal to zero, using default baud_rate.

HV: uart16550.c: check the denominator before use

---

tools/acrntrace/README.rst

Fix missing parameter documentation, and a misspelling

doc: fix acrntrace parameter documentation

---

tools/acrnbridge/Makefile

This patch set improves and fixes the systemd network units used                                                                                   
in the acrn-bridge.                                                                                                                                
It fixed the install target and rename the installed files to add                                                                                  
a 50- prefix, this allow the units to be processed before the others                                                                               
units in Clear Linux, and add a constrain to be processed in a virtual                                                                             
machine environment. …

Improve acrn-bridge 

---

hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/mmu.c
hypervisor/arch/x86/timer.c
hypervisor/arch/x86/vtd.c
hypervisor/debug/printf.c
hypervisor/debug/serial.c
hypervisor/debug/shell_internal.c
hypervisor/lib/div.c
hypervisor/lib/mdelay.c
hypervisor/lib/memory.c
hypervisor/lib/sprintf.c

To follow the Misra-c standard, any operators should be done outside
the conditions. Removed the prefix, postfix and bitwise shift from
conditions.

HV: Moving operators out from conditions

---

doc/tutorials/using_ubuntu_as_sos.rst

Add a tutorial explaining how to use Ubuntu as the Service OS
running on ACRN and providing all the device sharing services
(devicemodel) and tools to manage virtual machines.
Signed-off-by: Ailin Yang <ailin.yang@intel.com>

Documentation: tutorial on how to use Ubuntu as the SOS

---

doc/developer-guides/virtio-hld.rst

Layout of note at the end of the doc had a CSS formatting problem solved
by adding a leading sentence before the bullet list.

doc: fix a formatting issue in the virtio-hld

---

doc/conf.py

A recent PR changed where the release version is maintained (was in the
hypervisor/Makefile, now in a VERSION file) and format (was a RC_VERSION
variable, now a EXTRA_VERSION variable).  The doc build process uses the
version information when generating documents.

doc: handle new VERSION file and format

---

hypervisor/arch/x86/ept.c
hypervisor/arch/x86/guest/guest.c
hypervisor/arch/x86/guest/instr_emul.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/mmu.c
hypervisor/arch/x86/trusty.c
hypervisor/arch/x86/virq.c
hypervisor/include/arch/x86/guest/vcpu.h
hypervisor/include/arch/x86/mmu.h

Removed function-like macro of MEM_WRITE and VCPU_RETAIN_RIP. To be consist, change from MEM_READ to mem_read as well.

HV: Remove function-like macro 

---

hypervisor/arch/x86/cpuid.c
hypervisor/arch/x86/guest/ucode.c
hypervisor/arch/x86/guest/vioapic.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/vmx.c
hypervisor/common/io_request.c

To follow the Misra C standard, doing one assignment per line to
make code is clearly readable and reduces the confusion of its
intetion or typo.

HV: Avoiding the chained assignment

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/irq.c
hypervisor/arch/x86/mmu.c
hypervisor/common/io_request.c
hypervisor/include/arch/x86/cpu.h

- code cleanup to set a more smooth name

HV: Rename 'CPU_BOOT_ID' to 'BOOT_CPU_ID'

---

devicemodel/hw/pci/lpc.c
devicemodel/hw/pci/uart.c
devicemodel/hw/uart_core.c

The lpc dm causes that UOS can't boot if the parameters are set incorrectly,
it is not friendly to users.
This patch optimizes the lpc error handle flow. UOS always can boot successfully
whatever the lpc settings are.

lpc: resolve UOS boot-up issue caused by lpc.

---

devicemodel/core/sw_load_vsbl.c
devicemodel/hw/pci/wdt_i6300esb.c

6300esb has bit in its register to show whether the watchdog
timeout is hit.
This patch adds this bit support. So the guest could query
whether last reset is triggered by watchdog reset.
Reviewed-by: Cao Minggui <minggui.cao@intel.com>
Tested-by: Binbin Wu <binbin.wu@intel.com>

DM: extend i6300esb device to support watchdog timeout query

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/cpuid.c
hypervisor/boot/acpi.c
hypervisor/debug/vuart.c
hypervisor/lib/memory.c
hypervisor/lib/sprintf.c
hypervisor/lib/string.c

Removed the postfix and prefix operation in assignment expression.
Noncompliant code example:
1) *a++ = *b ++;
2) a = arr[--b];

HV: Assignment should not mix with operator

---

hypervisor/arch/x86/ept.c
hypervisor/arch/x86/guest/guest.c
hypervisor/arch/x86/guest/vioapic.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/trusty.c
hypervisor/debug/shell_internal.c
hypervisor/include/arch/x86/guest/vm.h

transfer num_vcpus,exp_num_vcpus to uint16_t.
transfer vm_hw_num_cores to uint16_t.

HV:modified vm_description and vm_hw_info memebers' type

---

hypervisor/arch/x86/guest/guest.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/debug/serial.c

The assigment should be done outside while loop condition. To fix
it, one assigment initializaion and update statement of for loop
have been applied. The only while loop reminds to avoid very long
for loop expression.

HV: No assignment inside while loop condition

---

devicemodel/hw/pci/xhci.c
devicemodel/include/xhcireg.h

Change xHCI DRD mode switch path and operational model in DRD emulation
followed with DRD driver change in linux kernel. And make xHCI VID and
PID parameters scalable with different platforms.
Liang Yang (2):
DM USB: xHCI: Set correct PCI VID/PID for APL DRD cap.
DM USB: xHCI: Update the native DRD interfaces.

Refine Intel Apollo Lake xHCI DRD emulation.

---

hypervisor/debug/printf.c

Operation should be done outside return expression. Moved the assignment out from return expression.

HV: printf.c: Do not return expression contains subexpression

---

hypervisor/arch/x86/guest/vioapic.c

Using suffix "UL" rather than type casting 0xffffffff.

vioapic.c: Using suffix rather than casting

---

hypervisor/arch/x86/guest/vm.c

Check the return value for prepare_vcpu/start_vm

hv:fix return value violation in prepare_vm0

---

hypervisor/arch/x86/cpu.c
hypervisor/include/arch/x86/msr.h

there is a bug for system hang on SBL bootloader after we enabled turbo mode.
so add tmp patch to disable turbo mode as the work-around.
after SBL fixed it, we revert this patch.

[REVERT-ME]: disable turbo mode

---

hypervisor/Makefile
hypervisor/arch/x86/trusty.c
hypervisor/arch/x86/trusty2.c
hypervisor/include/arch/x86/trusty.h

This is a temp solution to handle discontinuous hpa
when create/destroy secure world ept.

[REVERT-ME]:handle discontinuous hpa for trusty

---

hypervisor/arch/x86/guest/vioapic.c

Current code incorrectly assumes that RTL cannot be updated while
the interrupt is masked.
Signed-off-by: Abdul Rehman <abdulrehmanee010@gmail.com>

HV: bug fix update RTE when interrupt is unmasked

---

hypervisor/Makefile
hypervisor/arch/x86/Kconfig
hypervisor/boot/reloc.c

The relocation feature relies on the ld option "-z noreloc-overflow" which is
only available for binutils >= 2.27, while on Ubuntu 16.04 or older the default
version of binutils is 2.26.
This patch wraps the relocation code with a configurable macro and make it
undefined by default to avoid default build failures.
NOTE: This is just a hotfix. The code dropped with undefined CONFIG_RELOC needs
to be reviewed by the original author of this feature. Checks to the binutils
version will also follow up.

HV: build: make relocation-related code configurable

---

.travis-dockerfiles/Dockerfile.clearlinux

"RUN git config --global http.sslVerify false" was needed with
a cloud-based CI system else it failed to clone the repository.
The project does not use that cloud-based CI system and hence
this workaround (security by-pass) is not needed.
Fix #654 

Dockerfile: remove security by-pass in Clear Linux Dockerfile

---

tools/acrn-crashlog/acrnprobe/android_events.c
tools/acrn-crashlog/acrnprobe/channels.c
tools/acrn-crashlog/acrnprobe/crash_reclassify.c
tools/acrn-crashlog/acrnprobe/history.c
tools/acrn-crashlog/acrnprobe/include/load_conf.h
tools/acrn-crashlog/acrnprobe/include/probeutils.h
tools/acrn-crashlog/acrnprobe/include/startupreason.h
tools/acrn-crashlog/acrnprobe/probeutils.c
tools/acrn-crashlog/acrnprobe/sender.c
tools/acrn-crashlog/acrnprobe/startupreason.c
tools/acrn-crashlog/common/cmdutils.c
tools/acrn-crashlog/common/fsutils.c
tools/acrn-crashlog/common/include/cmdutils.h
tools/acrn-crashlog/common/include/fsutils.h
tools/acrn-crashlog/data/acrnprobe.service
tools/acrn-crashlog/data/acrnprobe.xml

Since ACRN has the capability to reboot and reboot reason is available
in SOS, acrnprobe could detect the crash of acrn and SOS kernel.
List of added crash types:
1. ACRNCRASH		- crashed in hypervisor, this detection depends on
files in /tmp/acrnlog_last(provided by acrnlog).
2. IPANIC		- crashed in SOS kernel, this detection depends on
pstore.
3. SWWDT_IPANIC		- crashed in SOS kernel and reboot reason is wdt.
4. HWWDT_UNHANDLE	- only recognize reboot reason is global, there is no
further clues that it's a SOS kernel crash or a
hypervisor crash.
5. SWWDT_UNHANDLE	- only recognize reboot reason is wdt, there is no
further clues that it's a SOS kernel crash or a
hypervisor crash.
6. UNKNOWN		- only recognize reboot reason is warm, there is no
further clues that it's a SOS kernel crash or a …

 tools:acrn-crashlog: Detect and classify the crash in ACRN and kernel

---

hypervisor/arch/x86/trusty.c
hypervisor/include/public/acrn_hv_defs.h

Per new design of trusty memory allocation: VHM will reserve contiguous
memory for trusty when DM launch guest with trusty enabled. And OSloader
will relocate trusty to 511G directly and pass trusty's base/entry to HV
by trusty_boot_param when call HC_INIITIALIZE_TRUSTY.
So in this patch:
1. Extend trusty_boot_param to support addr/entry above 4G.
2. Remove size check for old version compatibility.

HV: trusty: revise trusty_boot_param structure

---

hypervisor/arch/x86/irq.c

- Define the array for 'struct irq_desc' with its size
The array size for 'struct irq_desc' is constant and will not be
changed.
- Use array rather than a pointer to avoid the pointer arithmetic.

hv: irq: fix 'Pointer arithmetic is not on array'

---

devicemodel/core/hugetlb.c
devicemodel/hw/platform/rpmb/rpmb_backend.c

- @'rpmb_check_frame()', avoid buffer overflow access
when calling 'memcmp()'

DM: Fix potential buffer overflow and uninitialized variable

---

doc/Makefile
doc/conf.py

Normal publication is to the /latest/ folder.  With the tagged 0.1
release, we now have an alternative frozen version of the docs.
Also, tweaked the code for collecting version information from the
VERSION file to create document version number, and Makefile needed to
create the publish directory for a new tagged version.

doc: add v0.1 doc choice

---

hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vlapic_priv.h
hypervisor/include/arch/x86/apicreg.h
hypervisor/include/arch/x86/guest/guest.h
hypervisor/include/arch/x86/guest/vcpu.h
hypervisor/include/arch/x86/guest/vlapic.h
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/arch/x86/mmu.h
hypervisor/include/arch/x86/vmx.h

A summary of changes made in this patch:
* Use uint32_t for register offsets.
* Use uint32_t for isrvec_stk_top which equals to the number of vectors in the
stack.
* Use local variables to hold struct members before using them, to avoid
confusions from static checkers.
* Use uint32_t for tpr, though the higher 24 bits are reserved.
* For-loops with loop variables counting down to 0 are converted to while-loops
to make the loop variable unsigned when necessary.
* 'U' suffix for constants in unsigned contexts.
* Local variables are typed so that explicit casts are minimized.
Issues yet to be closed include
* Conversions due to atomic APIs taking/returning signed values.
* Conversions due to exec_[vmread|vmwrite] always work on 64-bit integers.
* IOAPIC RTE constants are 64-bit instead of …

HV: vlapic: integral type cleanup

---

hypervisor/arch/x86/virq.c
hypervisor/common/ptdev.c
hypervisor/debug/console.c
hypervisor/debug/logmsg.c
hypervisor/debug/printf.c
hypervisor/debug/serial.c
hypervisor/debug/shell_internal.c
hypervisor/debug/uart16550.c
hypervisor/include/arch/x86/irq.h
hypervisor/include/common/ptdev.h
hypervisor/include/debug/console.h
hypervisor/include/debug/trace.h

Change these 4 APIs to void type:
vcpu_inject_pf
uart16550_calc_baud_div
uart16550_set_baud_rate
ptdev_activate_entry
No need to return 'entry' for ptdev_activate_entry
since the input parameter is 'entry'.

hv:fix MISRA-C return value violation

---

hypervisor/arch/x86/guest/vm.c
hypervisor/bsp/sbl/vm_description.c
hypervisor/bsp/uefi/vm_description.c
hypervisor/common/hv_main.c
hypervisor/include/arch/x86/guest/vm.h

rename vm_hw_logical_core_ids to vm_pcpu_ids
and changed the type to uint16_t.
V1->V2:rename the vm_hw_logical_core_ids

HV:transfer vm_hw_logical_core_ids's type and rename it

---

hypervisor/arch/x86/cpu.c
hypervisor/boot/acpi.c
hypervisor/include/arch/x86/cpu.h

Use the array for lapic_id directly to avoid the unnecessary pointer
arithmetic.
With current implementation,
lapic_id_base is always a byte array with CPU_PAGE_SIZE elements
- replace 'uint8_t *lapic_id_base' with 'uint8_t
lapic_id_array[CPU_PAGE_SIZE]' to make the boundary explicit
- add a range check to ensure that there is no overflow
v2 -> v3:
* update the array size of lapic_id_array per discussion with Fengwei
v1 -> v2:
* remove the unnecessary range check in parse_madt in cpu.c

hv: cpu: fix 'Pointer arithmetic is not on array'

---

devicemodel/hw/pci/virtio/virtio_net.c

We should keep variable name in function declaration. It makes
things clearer and easier to be understood.

dm: virtio-net: add variable name in function declaration

---

hypervisor/arch/x86/guest/vioapic.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/trusty.c
hypervisor/arch/x86/vtd.c
hypervisor/common/hypercall.c
hypervisor/common/io_request.c
hypervisor/debug/shell_internal.c
hypervisor/debug/vuart.c
hypervisor/include/arch/x86/guest/vioapic.h
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/arch/x86/vtd.h
hypervisor/include/public/acrn_common.h
hypervisor/include/public/acrn_hv_defs.h

vmid's type prefered to be uint16_t.
V1->V2:vmid from uint32_t transfer to uint16_t
V2->V3:add range check to hcall's vmid parameter
V3->V4:seperate the declaration and actual code.
V4->V5:remove range check from hcall's vmid parameter

HV:transfer vmid's type to uint16_t

---

hypervisor/boot/acpi.c

With current implementation:
If the case 'entry->length < sizeof(struct acpi_subtable_header)' is
triggered, it will lead to a dead loop.
Gracefully return when this case is triggered.
Why:
If 'entry->length < sizeof(struct acpi_subtable_header)', it means that
there is no valid 'struct acpi_subtable_header' starting from the entry.
There must be something wrong. It should not happen in normal case.
v1 -> v2:
* Remove the unacceptable ASSERT, just gracefully return

hv: fix the potential dead loop in _parse_madt

---

hypervisor/arch/x86/vmx.c

In non real mode, for segment registers other than CS, the guest segment
base should be zero, otherwise the guest's segmentation results in wrong
effective addresses.
Linux boots with the wrong segment registers (base address in hidden part),
because it happens that it assigns the segment registers before using any
of them, which effectively reloads the segment base addresses from GDT.

hv: set guest segment base to zero if VCPU does not start in real mode

---

hypervisor/Makefile
hypervisor/boot/reloc.c
hypervisor/bsp/uefi/efi/malloc.c

commit ia23549aa915e7dc2c ("build: make relocation-related code
configurable") adds CONFIG_RELOC to make relocation configurable
This patch corrects the behavior when CONFIG_RELOC is disabled
- Don't use "CFLAGS += -fpie" and put back "LDFLAGS += -static"
- __emalloc(): forced to allocate exactly the asked address, which is
CONFIG_RAM_START

hv: further fix to configurable relocatoin

---

hypervisor/arch/x86/cpu.c

The cpu offline requester monitor the target cpu state
to detect whether target cpu is put to offline already.
So we should only update the cpu state to offline after
all other operations are finished.
Reviewed-by: Eddie Dong <Eddie.dong@intel.com>

hv: cpu state update should be moved just before halt.

---

hypervisor/arch/x86/assign.c
hypervisor/arch/x86/vtd.c
hypervisor/common/hv_main.c
hypervisor/common/hypercall.c
hypervisor/common/io_request.c
hypervisor/common/ptdev.c
hypervisor/common/vm_load.c
hypervisor/include/arch/x86/assign.h
hypervisor/include/arch/x86/guest/vcpu.h
hypervisor/include/arch/x86/vtd.h
hypervisor/include/common/ptdev.h
hypervisor/include/public/acrn_common.h

Signed/unsigned conversion should add cast explicitily
or change the type of them to the same.
V1->V2:Fixed the 0U to 0UL because of the mistakes.
V2->V3:remove unsed macro
Signed-off-by: HuiHuang Shi <huihuang.shi@intel.com>

HV:misc:fix "signed/unsigned conversion with cast"

---

hypervisor/lib/sprintf.c

The array size of upper_hex_digits and lower_hex_digits are same and
constant.
Use an array rather than a pointer to fix the violation - 'Declaration
does not specify an array'
v3 -> v4:
* Update the array size of 'digits'
* Update the usage of 'digits'
v2 -> v3:
* Update the usage of 'digits'
v1 -> v2:
* Define a MACRO for the array size of 'digits'
* Simplify the declaration of 'digits'

hv: sprintf: fix 'Declaration does not specify an array'

---

hypervisor/Makefile
hypervisor/include/arch/x86/per_cpu.h

With Kconfig, it would be common to rebuild the hypervisor with a few
configuration symbols changed. But for a proper rebuild, users are required to
execute ''make clean'' first, which deletes the configuration file at all.
This patch leverages the compiler to generate a target that add involved headers
as dependencies to a specific file. The inclusion of version.h is dropped in
per_cpu.h to avoid forcefully rebuild of all files since version.h is created on
build.

HV: consider header depenencies when rebuilding

---

hypervisor/arch/x86/assign.c
hypervisor/arch/x86/guest/vioapic.c
hypervisor/arch/x86/ioapic.c
hypervisor/include/arch/x86/apicreg.h
hypervisor/include/arch/x86/guest/vioapic.h
hypervisor/include/arch/x86/ioapic.h

This patch series fix MISRA C violations related to integral types, with:
* the first unifying access patterns to ioapic/vioapic RTEs to avoid
implicit narrowing, and
* the second fixing rest of the violations that can be fixed locally.
v1 -> v2:
* Instead of two 32-bit ''low'' and ''high'', define a union that allows
either 32-bit or 64-bit accesses to RTEs.
* Drop duplicated definitions to IOAPIC register offsets.
* Drop the ''size'' parameter of vioapic_mmio_[read|write] and
vioapic_mmio_rw since vioapic_mmio_access_handler() ensures that size is
always 4.

HV: vioapic: fixes to integral-type-related violations

---

hypervisor/arch/x86/vtd.c
hypervisor/include/arch/x86/vtd.h

Function like macro changed to be inline function to limit
the return type and parameter type.

 HV:vtd change the macro to the inline function

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/irq.c
hypervisor/arch/x86/lapic.c
hypervisor/arch/x86/vtd.c
hypervisor/boot/dmar_parse.c
hypervisor/include/arch/x86/irq.h
hypervisor/include/arch/x86/lapic.h
hypervisor/include/arch/x86/vtd.h

Change these 6 APIs to void type:
init_default_irqs
interrupt_init
early_init_lapic
init_lapic
init_iommu
destroy_iommu_domain
It has checked the argument of destroy_iommu_domain in shutdown_vm,
then no need to check it again inside destroy_iommu_domain.

hv: change several APIs to void type

---

devicemodel/include/public/acrn_common.h
hypervisor/Makefile
hypervisor/arch/x86/assign.c
hypervisor/arch/x86/cpu.c
hypervisor/common/hv_main.c
hypervisor/common/hypercall.c
hypervisor/common/io_request.c
hypervisor/common/vm_load.c
hypervisor/include/arch/x86/assign.h
hypervisor/include/arch/x86/guest/vcpu.h
hypervisor/include/public/acrn_common.h
hypervisor/include/public/acrn_hv_defs.h

fix integer type violations,keep some violations which
related to hypcall and msix_entry_index.
V1->V2:1.modified API_MAJOR_VERSION from Makefile
2.sync acrn_common.h changed to device model

HV:common:fix "integer type violations"

---

hypervisor/arch/x86/cpu_primary.S
hypervisor/arch/x86/ept.c
hypervisor/arch/x86/guest/guest.c
hypervisor/arch/x86/guest/instr_emul_wrapper.c
hypervisor/arch/x86/guest/instr_emul_wrapper.h
hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vmsr.c
hypervisor/arch/x86/idt.S
hypervisor/arch/x86/trampoline.S
hypervisor/arch/x86/trusty.c
hypervisor/arch/x86/virq.c
hypervisor/arch/x86/vmexit.c
hypervisor/arch/x86/vmx.c
hypervisor/common/hypercall.c
hypervisor/include/arch/x86/guest/vcpu.h
hypervisor/include/arch/x86/vmx.h

There are many integer type conversions in VMX, timer
and MTTR module detected by static analysis tool, these
integer type conversions voilate MISRA C:2012.
The following steps are taken to fix above integer type
conversions:
Replace SEL MARCO with constant value in assembly code;
Update vmread and vmwrite operations to access 16 bit,
32 bit, 64 bit, and natural width VMCS fields;
Update related variables type for vmread/vmwrite operations;
Update related caller according to VMCS fields size.
V1-->V2:
Split patch as six part;
Update vmread/vmwrite operations and related caller;
V2-->V3:
Update code comments;
Update related variables type for vmread/vmwrite;
Add "hu" for uint16_t argument in log function.
V3-->V4:
Few updates for coding style;
Remove useless type conversion.
Reviewed-by: …

HV:treewide:Clean up vmread and vmwrite operations

---

hypervisor/arch/x86/guest/instr_emul.c

ASSERT/panic are called when we get invalid values. It is a little bit strict.
This patch replaces ASSERT/panic with pr_err and return -EINVAL.
v1 -> v2:
- v1 patch name (HV: instr_emul: Remove unnecessary check in decode_xxx)
- keep the check and replace ASSERT/panic with pr_err.

HV: instr_emul: Replace ASSERT/panic with pr_err

---

tools/acrn-crashlog/README.rst
tools/acrn-crashlog/acrnprobe/README.rst
tools/acrn-crashlog/usercrash/README.rst

The ``.. code-block::`` directive can specify a highlight language for
the body of the directive.  Previously the languages "none" and
"console" were the same, but we're now using "console" for creating
terminal-looking output (rather than doing images of terminal windows)
with a black background and white text.
This PR replaces unintended uses of the "console" highlighting language
with "none".

doc: use code-block:: none for command examples

---

devicemodel/core/monitor.c
misc/cbc_lifecycle/cbc_lifecycle.c
tools/acrn-manager/Makefile
tools/acrn-manager/acrn_mngr.c
tools/acrn-manager/acrn_mngr.h
tools/acrn-manager/acrn_vm_ops.c
tools/acrn-manager/acrnd.c

We replace payload[0] of struct mngr_msg with an union, which contains all payload data. So that type cast for mngr_send_msg() is no longer needed. And we can avoid potential out-of-boundary memory accessing and using of uninitialized variable.

tools: replace payload[0] of struct mngr_msg with an union

---

hypervisor/arch/x86/assign.c
hypervisor/arch/x86/guest/vioapic.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/include/arch/x86/guest/vlapic.h

Current code has a mistake associating destination with
redirectionhint. So just use the destination mode to work out
destination mode.
When injecting the msi interrupt to vcpu in hypervisor layer,
current code ingnores the redirection hint(RH) bit of msi address
message from guest, and just use the destination mode and
destination ID. So correctly before injecting, check the RH bit,
if set, choose the vcpu that has lowest priority to inject msi.
Reviewed-by: Zhao, Yakui <yakui.zhao@intel.com>
Reviewed-by: Yin, Fengwei <fengwei.yin@intel.com>

HV: bug fix on emulating msi message from guest

---

hypervisor/Makefile
hypervisor/arch/x86/ept.c
hypervisor/arch/x86/mmu.c
hypervisor/arch/x86/mtrr.c
hypervisor/arch/x86/pagetable.c
hypervisor/include/arch/x86/hv_arch.h
hypervisor/include/arch/x86/mmu.h
hypervisor/include/arch/x86/pgtable.h
hypervisor/include/arch/x86/pgtable_types.h
hypervisor/include/hypervisor.h

v1-v2:
1. fix MISRA-C violations
2. rename attr_set/attr_clr to prot_set/clr
3. add mmu_modify pre-assumption comments
v1:
This serial try to refine HV MMU & EPT modify memory address
page table attributes. And replace the old implement with new
one.

Revisit HV MMU & EPT change MR PAT

---

hypervisor/arch/x86/mtrr.c
hypervisor/arch/x86/timer.c
hypervisor/arch/x86/vmexit.c
hypervisor/arch/x86/vmx.c
hypervisor/include/arch/x86/cpu.h
hypervisor/include/arch/x86/gdt.h
hypervisor/include/arch/x86/msr.h
hypervisor/include/arch/x86/mtrr.h

There are some integer type conversions in the VMX, timer
and MTTR module detected by static analysis tool.
Update related integer type in VMX, timer and MTTR
module.
Add related constant value with 'U/UL' suffix.
V1-->V2:
Resolve few rebase conflicts.
V2-->V3:
Add 'h' for uint16_t argument in log function;
Update the type of temp variable 'type' as uint8_t
in MTTR module to reduce type conversion.

HV:treewide:Fix type conversion in VMX, timer and MTTR module

---

hypervisor/arch/x86/guest/instr_emul.c
hypervisor/arch/x86/guest/instr_emul_wrapper.c
hypervisor/arch/x86/guest/instr_emul_wrapper.h

In the current hypervisor, there are many members of CPU_reg_name
used to check range and useless register names.
Define some CPU_REG_XX_FIRST and CPU_REG_XX_LAST MACROs to
make range checking clear;
Remove useless register names CPU_REG_XX_LAST in CPU_reg_name;
Update the related caller.
V1-->V2:
Update a mistake, replace second CPU_REG_SEG_FIRST
with CPU_REG_SEG_LAST in ASSERT.

HV:INSTR_EMUL: Clean up CPU_reg_name

---

hypervisor/arch/x86/assign.c
hypervisor/arch/x86/cpuid.c
hypervisor/arch/x86/guest/instr_emul.c
hypervisor/arch/x86/guest/ucode.c
hypervisor/arch/x86/guest/vioapic.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vpic.c
hypervisor/arch/x86/io.c
hypervisor/arch/x86/mmu.c
hypervisor/arch/x86/virq.c
hypervisor/arch/x86/vmexit.c
hypervisor/arch/x86/vmx.c
hypervisor/common/hypercall.c
hypervisor/lib/sprintf.c
hypervisor/lib/string.c

MISRA C requires that a 'if' statement followed by one or more 'else if'
statement shall be terminated by an 'else' statement which contains either
side-effect or a comment, to ensure that conditions are considered
exhaustively.
Note that a simple 'if' statement is not required to be terminated by 'else'.
This patch fixes such violations by either refactoring the code or add the
'else' statement with either a comment (describing why this case can be skipped)
or logging the event. It may not be satisfactory for the release version where
logging is no-op, but properly handling these non-trivial cases is out of the
scope of this patch.
v1 -> v2:
* Fix unintended semantic changes in add_(msix|intx)_remapping and
io_instr_vmexit_handler.
* Simplify boolean checks in vpic_ocw2.
* Rephrase the …

HV: treewide: terminate 'if .. else if' constructs with 'else'

---

devicemodel/include/public/acrn_common.h
hypervisor/include/public/acrn_common.h
hypervisor/include/public/acrn_hv_defs.h

While fixing the MISRA C violations related to integral types, we have unified
the type of the following data:
uint8_t:
phys_pin, virt_pin, vpic_pin, ioapic_pin, vioapic_pin
uint16_t:
vm_id, pcpu_id, vcpu_id, vpid
uint32_t:
vector, irq
This patch revisits the types of the fields in vhm_request as well as the
structures used as parameters in the hypercalls, and make them aligned with the
types the hypervisor uses for such data. Reserved fields are added to keep the
size and layout of the structures. Implicit paddings are also made explicit as
reserved fields.

HV: hypercall: revisit types in structure parameters

---

hypervisor/arch/x86/ept.c

There is chance to destroy vm whose ept table was not created, for
example, dm fails to setup mem for vm. In this case, it's better
to check the value of eptp before calling free_ept_mem() rather than
relying on assertion in the function.

hv: check eptp value before calling free_ept_mem()

---

hypervisor/debug/shell_internal.h
hypervisor/include/arch/x86/guest/guest_pm.h
hypervisor/include/arch/x86/guest/vlapic.h
hypervisor/include/arch/x86/guest/vpic.h
hypervisor/include/arch/x86/vmx.h
hypervisor/include/common/hypercall.h
hypervisor/include/lib/rtl.h

- Remove those APIs without definition
- Minor changes to make sure the line length is less than 80

hv: treewide: fix 'No definition in system for prototyped procedure'

---

hypervisor/arch/x86/ept.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/mmu.c
hypervisor/arch/x86/trusty.c
hypervisor/arch/x86/trusty2.c
hypervisor/arch/x86/vmx.c
hypervisor/common/hypercall.c
hypervisor/common/trusty_hypercall.c
hypervisor/include/arch/x86/guest/vm.h

Most of the time, we use the virtual address of EPT PMl4 table, not physical address.

store virtual address of EPT PML4 table

---

tools/acrn-crashlog/README.rst
tools/acrn-crashlog/acrnprobe/README.rst
tools/acrn-crashlog/usercrash/README.rst
tools/acrn-manager/README.rst

Made the titles consistent across the tools (some had capital letters).
Fixed heading levels in acrnctl/acrnd doc  (had two H1 headings).
Changed a text-based drawing to use graphviz.
Some general grammar tweaks as well.

doc: clean up tools docs

---

hypervisor/arch/x86/vtd.c
hypervisor/include/arch/x86/mmu.h
hypervisor/include/arch/x86/vtd.h

HV:vtd:fix all integer related violations
Fix vtd.h and vtd.c all integer violations.

HV:vtd:fix all integer related violations

---

devicemodel/include/public/acrn_common.h
hypervisor/arch/x86/assign.c
hypervisor/include/common/ptdev.h
hypervisor/include/public/acrn_common.h

fix all assign.c integer violations except related
"Implicit conversion: actual to formal param".

fix assign.c interger violations

---

hypervisor/bsp/uefi/efi/Makefile
hypervisor/bsp/uefi/efi/boot.c
hypervisor/bsp/uefi/efi/boot.h

In current code, struct efi_ctx and dt_addr_t are defined in two places.
This patch removes one copy of the definitions.
Acked-by: Jack Ren <jack.ren@intel.com>

hv: efi: remove multiple defined struct efi_ctx & dt_addr_t

---

hypervisor/arch/x86/wakeup.S

We should use movq to restore rsp instead of mov.

HV: fix bug of restore rsp context

---

hypervisor/arch/x86/virq.c
hypervisor/arch/x86/vmexit.c
hypervisor/debug/dump.c
hypervisor/include/arch/x86/ioapic.h
hypervisor/include/arch/x86/mmu.h
hypervisor/include/arch/x86/vmx.h

- explicitly declare the array size to fix the violation 'Array has no
bounds specified'
- minor changes for comments style
v1 -> v2:
* add the definition for exit reasons from 0x39 to 0x40 based on "SDM
APPENDIX C VMX BASIC EXIT REASONS"

hv: treewide: fix 'Array has no bounds specified'

---

doc/.known-issues/doc/hypercall.conf

Changes to hypercall.h altered the error pattern match used to decide if
doxygen errors are "expected".  Update the pattern match.

doc: fix doc error filter patterns

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/ept.c
hypervisor/arch/x86/guest/guest.c
hypervisor/arch/x86/guest/instr_emul.c
hypervisor/arch/x86/guest/ucode.c
hypervisor/arch/x86/guest/vioapic.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vmcall.c
hypervisor/arch/x86/io.c
hypervisor/arch/x86/ioapic.c
hypervisor/arch/x86/timer.c
hypervisor/arch/x86/trusty.c
hypervisor/arch/x86/vmexit.c
hypervisor/arch/x86/vmx.c
hypervisor/arch/x86/vtd.c
hypervisor/common/hypercall.c
hypervisor/debug/dump.c
hypervisor/debug/logmsg.c
hypervisor/debug/shell_internal.c
hypervisor/include/arch/x86/mmu.h
hypervisor/include/arch/x86/vmx.h
hypervisor/include/arch/x86/vtd.h
hypervisor/include/lib/bits.h
hypervisor/include/lib/rtl.h
hypervisor/include/lib/util.h
hypervisor/lib/div.c
hypervisor/lib/memory.c
hypervisor/lib/sprintf.c

Series patches of misra-c violation fix. It is for clean up legacy and add brackets in  expression when there is same level of precedence operators.

HV: Clean up commented out code and add brackets of same level precedence expression 

---

hypervisor/Makefile

Currently we reply on CONFIG_RELEASE=n to determine if a debug version should be
built. Though this holds due to the configuration overriding in kconfig.mk, this
only applies to make >= 3.82. For make 3.81, $(eval $(call xxx)) does not work
as expected, and thus CONFIG_RELEASE is undefined for debug builds.
Instead of checking CONFIG_RELEASE=n, this patch checks CONFIG_RELEASE=y
instead, which is guaranteed without relying on the behavior of $(eval $(call
xxx)).

HV: make: check CONFIG_RELEASE=y for release build

---

hypervisor/bsp/uefi/efi/malloc.c

Fixed a typo in 621425da20d0 ("hv: further fix to configurable
relocation"). It shoud allocate fixed address if CONFIG_RELOC is
not defined.

hv: fix typo in relocation code

---

hypervisor/arch/x86/guest/guest.c
hypervisor/arch/x86/guest/instr_emul.c
hypervisor/arch/x86/vmx.c
hypervisor/arch/x86/vtd.c

In the hypervisor, there are many casts from
an void pointer to integer pointer, then from
integer pointer to structure pointer.
These pointer castings are detected by static analysis
tool. All pointer casts are violations, There are
some duplicated pointer cast. This will make deviation
analysis complex.
BTW, there are one useless pointer casting and one
wrong pointer casting in the hypervisor.
Remvoe duplicated pointer casts to make deviation analysis
simple;
Remove one useless pointer casting;
Update one wrong pointer casting.
Note: There are many void type pointer casts, non-void type
pointer is casted to void type pointer, char type pointer casts,
non-char type pointer is casted to char type pointer. These pointer
casting is need by the memory management module, IO moudle etc. …

HV:treewide:Fixing pointer castings

---

hypervisor/bsp/sbl/platform_acpi_info.c

- The previous wake vector address just work for ABL, need to change it
to accommodate the latest SBL;
- Fix wrong bit width value in the pm1a gas;

HV: change wake vector address to accommodate sbl

---

doc/Makefile
doc/scripts/pullsource.sh
doc/tutorials/docbuild.rst

API doc generation includes kernel components provided by ACRN that live
in the acrn-kernel repo (not the acrn-hypervisor repo). We need to
include fetching the latest acrn-kernel sources when we do doc
generation, and update the documentation to mention we now need the
acrn-kernel repo as a sibling folder for the acrn-hypervisor repo
contents.

doc: add script for syncing acrn-kernel for API gen

---

tools/acrntrace/README.rst
tools/acrntrace/acrntrace.c
tools/acrntrace/acrntrace.h
tools/acrntrace/sbuf.c

Current implementation save trace data files on tmpfs by default, acrntrace
would use up all the physical mem, which can affect system functioning.
This commit changes default location for trace data file to current dir, and
removes the codes for space reservation, which is not necessary.

tools: acrntrace: save trace data file under current dir by default

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/guest/instr_emul.c
hypervisor/arch/x86/guest/instr_emul_wrapper.h
hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/idt.S
hypervisor/arch/x86/io.c
hypervisor/arch/x86/trusty.c
hypervisor/arch/x86/vmexit.c
hypervisor/arch/x86/vmx_asm.S
hypervisor/arch/x86/wakeup.S
hypervisor/debug/dump.c
hypervisor/debug/shell_internal.c
hypervisor/include/arch/x86/guest/vcpu.h
hypervisor/include/arch/x86/irq.h

In current code, general-purpose register layout in run_context is not align
with the  general-purpose register index when vmexit. So hv needs to map the
index used during  vmexit to the index of the general-purpose register in
run_context.
This patch adjusts general-purpose register layout in run_context. So no need to
map general-purpose regs during vmexit.
This patch also unifies the layout of general-purpose regs in interrupt/excpetion context.

HV: align general-purpose reg layout with vmx

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/cpu_state_tbl.c
hypervisor/arch/x86/gdt.c
hypervisor/arch/x86/ioapic.c
hypervisor/arch/x86/lapic.c
hypervisor/arch/x86/timer.c
hypervisor/arch/x86/virq.c
hypervisor/arch/x86/vmexit.c
hypervisor/arch/x86/vmx.c
hypervisor/include/arch/x86/vmexit.h

Fix x86 directory violations which related to integer problems,
some of problems are skipped because of ldra's false positive.
V1->V2 1.modified the code style
2.fix all macro VM_EXIT_IO_INSTRUCTION related

fix x86 dir integer violations

---

hypervisor/arch/x86/vmexit.c

hv: add a missing semicolon in vmexit.c

---

hypervisor/arch/x86/guest/vm.c

hypervisor will crash if user try to call hypercall
HC_CREATE_VM in infinite style.
actually, the number of VMs hypervisor can support
depends on the bit width of 'vmid_bitmap'.should
return error in case of overflow.
other cleanup for this function to avoid memory leak
in case of failure.

HV:refine 'create_vm()' to avoid potential crash and memory leak

---

devicemodel/samples/apl-mrb/launch_uos.sh

it can auto check android image, if exists, then launch it;
if not, it will try to luanch clearlinux. it can be used by
acrn_guest.service to auto boot UOS.

DM: add param: -V 5 to auto check/boot UOS image

---

hypervisor/arch/x86/ept.c
hypervisor/arch/x86/guest/instr_emul_wrapper.c
hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/guest/vioapic.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/io.c
hypervisor/common/io_request.c
hypervisor/include/arch/x86/guest/guest.h
hypervisor/include/arch/x86/guest/vcpu.h
hypervisor/include/arch/x86/guest/vioapic.h
hypervisor/include/arch/x86/guest/vlapic.h
hypervisor/include/arch/x86/hv_arch.h
hypervisor/include/arch/x86/io.h
hypervisor/include/arch/x86/ioreq.h
hypervisor/include/arch/x86/mmu.h
hypervisor/include/public/acrn_common.h

This series moves I/O emulation related declarations to a separate ioreq.h and cleans up the duplication of I/O request-related structures in vcpu.
Next steps:
* Name cleanup ('pio' for port I/O, 'mmio' for memory mapped I/O, and 'io' for both)
* I/O emulation code cleanup
* Simplification of VHM request states
* Cleanup emulation under abnormal cases.

HV: io: I/O emulation path revisit (part 1)

---

hypervisor/arch/x86/assign.c
hypervisor/arch/x86/guest/guest.c
hypervisor/arch/x86/guest/vioapic.c
hypervisor/arch/x86/ioapic.c
hypervisor/arch/x86/irq.c
hypervisor/arch/x86/mmu.c
hypervisor/common/hv_main.c
hypervisor/common/io_request.c
hypervisor/debug/console.c
hypervisor/debug/printf.c
hypervisor/debug/serial.c
hypervisor/debug/serial_internal.h
hypervisor/include/arch/x86/guest/guest.h
hypervisor/include/arch/x86/guest/vioapic.h
hypervisor/include/arch/x86/ioapic.h
hypervisor/include/arch/x86/irq.h
hypervisor/include/arch/x86/vmexit.h
hypervisor/include/common/ptdev.h
hypervisor/include/debug/console.h
hypervisor/include/lib/rtl.h
hypervisor/include/lib/sprintf.h
hypervisor/lib/sprintf.c
hypervisor/lib/string.c

Parameter's type which is pointer should not be changed in the
scope of function,assign it's value to local variable to fixed
it out.

HV:treewide:fix "Reference parameter to procedure is reassigned"

---

hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vlapic_priv.h

The variable vlapic_timer's name is identical with struct
vlapic_timer's name. This MISRA C violation is detected
by static analysis tool.
Rename variable vlapic_timer as vtimer.
Replace regular expression: s/vlapic_timer\([ ;,.)\-]\+\)/vtimer\1
Signed-off-by: Xiangyang Wu <xiangyang.wu@linux.intel.com>

HV:VLAPIC:rename variable vlapic_timer in the struct and function

---

hypervisor/arch/x86/io.c
hypervisor/arch/x86/timer.c
hypervisor/debug/dump.c
hypervisor/debug/vuart.c
hypervisor/include/arch/x86/ioreq.h
hypervisor/include/lib/bits.h
hypervisor/lib/div.c
hypervisor/lib/sprintf.c

Misra c required parameter should not changed in the scope
of function,use local variable to replace it.

HV:treewide:fix rest of violations related parameter changed

---

devicemodel/Makefile
devicemodel/samples/apl-mrb/acrn_guest.service

add acrn_guest.service, and modify makefile to install it
into root fs.
Reviewed-by: Like Yan <like.yan@intel.com>

DM: add service to support auot boot UOS

---

devicemodel/core/vmmapi.c

this patch fixes such an information leaking issue:
in case that after a UOS is destroyed, its memroy
will be reclaimed and maybe re-allocated for a new UOS,
then the previous UOS sensitive data in memory may
be leaked to the new UOS.

HV: clear memory region used by UOS before it exit

---

hypervisor/arch/x86/guest/instr_emul.c
hypervisor/arch/x86/guest/instr_emul.h
hypervisor/arch/x86/guest/instr_emul_wrapper.c
hypervisor/arch/x86/guest/instr_emul_wrapper.h
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vlapic_priv.h
hypervisor/arch/x86/timer.c
hypervisor/debug/console.c
hypervisor/include/arch/x86/per_cpu.h
hypervisor/include/arch/x86/timer.h
hypervisor/include/debug/console.h

For data structure types "struct timer, struct vie", "struct emul_ctxt",
its name is identical with variable name in the same scope. This MISRA C 
violation is detected by static analysis tool.
Naming convention rule:If the data structure type is used by multi modules, 
its corresponding logic resource is only used by hypervisor/host and isn't 
exposed to external components (such as SOS, UOS), its name meaning is  
simplistic (such as timer), its name needs prefix "hv_". 
Naming convention rule:If the data structure type is used by only one 
module and its name meaning is simplistic, its name needs prefix 
shorten module name.
Follow naming convention rule to udpate data structure type "struct vie_op".
The following udpates are made:
struct timer-->struct hv_timer
struct vie-->struct …

Rename struct timer, vie, vie_op, emul_ctxt

---

hypervisor/debug/shell_internal.c

CR4 valuse was missing in the output.

hv: debug: add CR4 to vcpu_dumpreg output

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/ept.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vlapic_priv.h
hypervisor/arch/x86/mmu.c
hypervisor/arch/x86/trusty.c
hypervisor/arch/x86/trusty2.c
hypervisor/include/arch/x86/guest/vcpu.h
hypervisor/include/arch/x86/lapic.h
hypervisor/include/arch/x86/mmu.h
hypervisor/include/arch/x86/trusty.h

For data structure types "struct key_info, struct pir_desc,
struct map_params, union lapic_id, struct segment",
its name is identical with variable name in the same scope.
This MISRA C  violation is detected by static analysis tool.
Naming convention rule:If the data structure type is used by only one 
module and its name meaning is simplistic, its name needs prefix
shorten module name.
The following udpates are made:
struct key_info-->struct trusty_key_info
struct pir_desc-->struct vlapic_pir_desc
struct map_params-->struct mem_map_params
union lapic_id-->union lapic_id_reg
struct segment-->struct segment_sel

HV:treewide:add suffix or prefix to data structure name

---

devicemodel/hw/platform/ioc.c
devicemodel/include/ioc.h

This patch resolves IOC mediator deinit function is blocked due to IOC mediator
core thread enters into sleep by epoll_wait, then pthread_join cannot return.
Trigger an event to wakeup core thread when IOC mediator deinit is invoked.

IOC mediator: fix IOC mediator blocks acrn-dm shutdown flow

---

hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vlapic_priv.h
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/guest/vpic.c
hypervisor/common/hypercall.c
hypervisor/include/arch/x86/guest/vm.h

Naming convention rule:If the data structure type is used by only one 
module and its name meaning is simplistic, its name needs prefix
shorten module name.
Naming convention rule:Variable name can be shortened from its 
data structure type name.
Naming convention rule:If the type is function
pointer, its name needs suffix "_fn".
The following udpates are made:
struct pic pic-->struct i8259_reg_state i8259
struct iommu_domain-->struct vm_iommu_domain
*apicv_set_intr_ready-->*apicv_set_intr_ready_fn
*apicv_pending_intr-->*apicv_pending_intr_fn
*apicv_set_tmr-->*apicv_set_tmr_fn
*apicv_batch_set_tmr-->*apicv_batch_set_tmr_fn
*apicv_intr_accepted-->*apicv_intr_accepted_fn
*apicv_post_intr-->*apicv_post_intr_fn
*enable_x2apic_mode-->*enable_x2apic_mode_fn
V1-->V2:
Update function pointer when …

HV:treewide:rename struct pic, iommu_domain and function pointer

---

devicemodel/Makefile

We need create system directory before we copy into $(DESTDIR)/usr/lib/systemd/system/, otherwise it will fail in clearlinux make build.
Signed-off-by: Nanlin Xie <nanlin.xie@intel.com>

DM: fix make install issue in auto boot UOS service

---

doc/api/GVT-g_api.rst

API changes to acrn-kernel/include/linux/vhm/acrn_vhm_mm.h in
https://github.com/projectacrn/acrn-kernel/pull/48 renamed functions
that were referenced in the GTG-g_api.rst document, causing the
documentation build to fail.

doc: fix doc errors from acrn_vhm_mm.h API changes

---

doc/conf.py
doc/static/acrn-custom.js

Have the logo link to the project site rather than the doc site

doc: tweak logo href to projectacrn.org

---

hypervisor/arch/x86/guest/vmcall.c
hypervisor/common/hypercall.c
hypervisor/include/common/hypercall.h

Currently we don't support resume VM in HC API, the real meaning
of the code is to start VM.

HV: rename resume_vm to start_vm in hypercall api

---

devicemodel/samples/apl-mrb/launch_uos.sh

SBL used to use 4:0:0 for WIFI device BDF, now it change back to 3:0:0

samples: change WIFI BDF to 3:0:0

---

hypervisor/arch/x86/guest/vlapic.c
hypervisor/boot/include/acpi.h
hypervisor/debug/shell_internal.h
hypervisor/include/arch/x86/assign.h
hypervisor/include/arch/x86/guest/vioapic.h
hypervisor/include/arch/x86/guest/vlapic.h
hypervisor/include/arch/x86/irq.h
hypervisor/include/arch/x86/mmu.h
hypervisor/include/debug/logmsg.h

Fix the parameter type mismatch between API declaration and definition.

hv: treewide: fix 'Function prototype/defn param type mismatch'

---

tools/acrn-manager/Makefile

As first step to separate misc folder into github/intel/ioc-cbc-tools we
need let acrn create devel package. This package will let ioc-cbc-tools
use acrn manager interface API to control lifecycle.
The Clear Linux autospec script will *detect* /usr/include/acrn/*.h and
thus help us create the devel package. This devel pacakge will be in the
build_req for ioc-cbc-tools autospec.
Reviewed-by: Like Yan <like.yan@intel.com>

acrn-manager: create acrn-hypervisor-dev package

---

hypervisor/arch/x86/guest/guest.c
hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/io.c
hypervisor/arch/x86/trusty2.c
hypervisor/common/hypercall.c
hypervisor/common/ptdev.c
hypervisor/debug/logmsg.c
hypervisor/debug/printf.c
hypervisor/debug/sbuf.c
hypervisor/debug/shell.c
hypervisor/debug/vuart.c

Fix integer related violations.
V1->V2:
clean all memset/calloc integer violations excpet bsp/boot directory

HV:fix rest integer violations

---

hypervisor/bsp/uefi/cmdline.c
hypervisor/debug/console.c
hypervisor/debug/uart16550.c
hypervisor/debug/uart16550.h
hypervisor/debug/vuart.c
hypervisor/include/debug/console.h

-- Check uart enabled flag, it will return if the flag is false.
-- Add function declaration (uart16550_set_property) in console.h
-- Remove unnecessary function declaration(get_serial_handle)
-- Change uart_enabled and port_mapped to bool
-- Fix MISRA-C integer violations

hv:cleanup console/uart code

---

hypervisor/arch/x86/Kconfig

Adding Kconfig option to choose and compile partitioning mode for ACRN.
Current implementation does not allow ACRN to support sharing mode
and partitioning mode out of a single binary.

HV: Add Partitioning mode option for ACRN

---

hypervisor/arch/x86/guest/instr_emul.c
hypervisor/arch/x86/trusty.c
hypervisor/include/lib/macros.h

In the C99 standard, the order of evaluation associated with
multiple #, multiple ## or a mix of # and ## preprocessor
operator is unspecified. For this case, gcc 7.3.0 manual
does not specify related implementation. So it is unsafe
to use multiple # or ## in a macro.
BTW, there are some macros with one or more "##" which are
not used by hypervisor.
Update relate codes to avoid using multiple # or ## in a macro;
Remove unused macros with one or more "##";
Remove "struct __hack;" at the end of GETCC since it is useless.
Note:
'##' operator usage constraints: A ## preprocessing token shall
not occur at the beginning or at the end of a replacement list
for either form of macro definition.
V1--V2:
Update relate codes to avoid using multiple # or ## in a macro.
V2-->V3:
Remove unused macros …

HV:treewide:avoid using multiple # or ## in a macro

---

devicemodel/Makefile
devicemodel/arch/x86/pm.c
devicemodel/core/main.c
devicemodel/core/mevent.c
devicemodel/core/monitor.c
devicemodel/core/pm.c
devicemodel/hw/pci/wdt_i6300esb.c
devicemodel/hw/platform/acpi/acpi.c
devicemodel/include/acpi.h
devicemodel/include/pm.h
devicemodel/include/vmmapi.h
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/guest/vmcall.c
hypervisor/arch/x86/vmx.c
hypervisor/common/hypercall.c
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/common/hypercall.h
hypervisor/include/public/acrn_hv_defs.h

This patch series enable the UOS S3 support. And with patch [2/6],
the system reset also could work.
For most virtio and emulated virtual devices, we don't need to do
anything in BE side for S3. There is only 1 exception: watchdog.
We have to move watchdog reset out of guest to make sure watchdog
always takes effect for guest to handle guest hang.
Now, there are some issues related with S3 we are still working
on:
1. PT dev issue for S3. Some PT dev can't work after UOS and UOS
enter/exit S3.
2. Trusy S3 handling. We are waiting for dependency patch in. Then
we will submit the trusty S3 handling patches.
3. Some mediator may have issue with UOS S3. We need to enable
the basic UOS S3 first. So mediator owner could test/debug
the mediator for UOS S3.
ChangeLog:
v1 -> v2:
- Remove the …

Enable basic UOS S3 support

---

hypervisor/arch/x86/guest/vioapic.c
hypervisor/include/arch/x86/guest/vioapic.h

Change this API to void type
Add pre-condition, state the input parameters are not NULL.

hv:fix return value violation for vioapic_get_rte

---

hypervisor/arch/x86/vmx.c

Reshuffle VMX init code, and check both allowed 0-settings and
1-settings of related MSR to make the final VMCS control value.

HV: fully check VMCS control settings

---

devicemodel/hw/uart_core.c

mevent is added only if uart backend fd refers TTY in uart_opentty.
So we should only delete mevent if uart backend fd refers TTY in uart_closetty.
This issue can be reproduced by below steps
1) acrnd starts UOS
2) run poweroff command in UOS
3) crash happens

dm: uart: fix acrn-dm crash issue when invoke uart_closetty function

---

hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/vmx.c
hypervisor/common/hypercall.c
hypervisor/include/arch/x86/guest/vcpu.h

Replace 0(pcpu_id/vcpu_id) with BOOT_CPU_ID

hv:Replace 0(cpu_id) with BOOT_CPU_ID

---

hypervisor/arch/x86/assign.c
hypervisor/arch/x86/ept.c
hypervisor/arch/x86/guest/guest.c
hypervisor/arch/x86/guest/instr_emul.c
hypervisor/arch/x86/guest/instr_emul.h
hypervisor/arch/x86/guest/instr_emul_wrapper.c
hypervisor/arch/x86/irq.c
hypervisor/arch/x86/mmu.c
hypervisor/arch/x86/timer.c
hypervisor/boot/acpi.c
hypervisor/common/hypercall.c
hypervisor/common/io_request.c
hypervisor/common/vm_load.c
hypervisor/include/arch/x86/mmu.h

In order to comply with MISRA C rules, renamed vairables
and function names starting with "_".
The major changes invloves mostly static function
names, as they are being called inside the same file
by a wrapper function.

HV: Rename functions, variables starting with "_"

---

hypervisor/debug/shell_internal.h
hypervisor/include/arch/x86/guest/guest.h
hypervisor/include/arch/x86/ioreq.h
hypervisor/include/arch/x86/timer.h
hypervisor/include/common/irq.h

Add the parameter identifier for typedef function pointer.

hv: treewide: fix 'Procedure parameter has a type but no identifier'

---

hypervisor/Makefile
hypervisor/arch/x86/guest/mptable.c
hypervisor/include/arch/x86/guest/mptable.h
hypervisor/include/arch/x86/guest/vm.h

Partitioning mode of ACRN needs to build mptable for UOS.
UOS uses mptable instead of ACPI tables.

HV: Adding mptable support for partition mode ACRN

---

doc/user-guides/acrn-shell.rst

removed shell commands:
--vcpu_pause
--vcpu_resume
--lsreq
--(warm) reboot
--vcpu_dumpmem
updated shell commands:
--vm_console -> sos_console
--trigger crash -> reboot
--merge 'set_loglevel' & 'get_loglevel' to 'loglevel'
new adding shell commands:
--dumpmem --> dump host physical memory

Doc: Refine hypervisor shell commands

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/idt.S
hypervisor/common/hv_main.c
hypervisor/common/hypercall.c
hypervisor/include/arch/x86/cpu.h

'hv_main()' wraps several logic which has no dependencies
each other(enable VMX, prepare to create service os VM..),
in this case, split this function to make code logic clear.
remove 'is_vm0_bsp()' & 'hv_main()'

HV: Refine 'hv_main()' function usage

---

tools/acrn-manager/acrn_vm_ops.c
tools/acrn-manager/acrnctl.c
tools/acrn-manager/acrnd.c

this patch set resolves acrnd and acrnctl S3 issues.
-fix S3 flow between acrnd and cbc lifecycle service.
-fix issues that S3 cannot work in acrnd.
-fix an issue that acrnctl tool can not resume paused vm.
v2:
1) Use pthread_mutex_lock to ensure only one acrnd stop thread at a time.
2) Remove the acrnd shutdown patch from the patchset, because rootcause of
the acrnd shutdown issue is acrn-dm happen crash, and will fix this with
an independent patch.
Yuan Liu (4):
tools: fix an invalid parameter of send_msg in query_state
tools: fix an issue acrnd does not notify the vm stop state to cbc
lifecycle service
tools: fix resuming vm issue in acrnd
tools: fix resuming vm issue in acrnctl
tools/acrn-manager/acrn_vm_ops.c |  4 +-
tools/acrn-manager/acrnctl.c     |  6 +-- …

 tools: this patch set resolves acrnd and acrnctl S3 issues

---

hypervisor/arch/x86/guest/vioapic.c
hypervisor/arch/x86/vmx.c
hypervisor/include/arch/x86/apicreg.h
hypervisor/include/arch/x86/guest/vioapic.h

This is the first set patches for vioapic/vlapic/vpic reshuffle. It majorly for vioapic, the subsequent patch sets will cover vlapic/vpic which plan to submit soon.
-refines the coding style for some key vioapic functions.
-fix several bugs.
-remove 0x20 ioapic support related code.
-the 0012 patch is for apicv, others are for vioapic.
v2:
-drop the two patches:
hv: vioapic: support non-32-bits aligned access for vioapic
Assume all access are 32bits aligned.
hv: vioapic: change the vioapic->acnt to vioapic->state
acnt is used for irq sharing. So keep it.
-to create new macro for ioapic id mask, avoid impact lapic id mask.
-provide more detail description for the reason to clear remote irr when switch to edge trigger mode.
-to keep original apicv support check conditions.
-fix 4 MISRA C …

1st patch set for vioapic/vlapic/vpic reshuffle

---

hypervisor/arch/x86/timer.c
hypervisor/include/arch/x86/per_cpu.h

Since global vector table is being used on all pcpus, it's not necessary to request timer irq
at each cpu init. With this change, per_cpu timer nodes are removed, and only BSP registers
and unregisters timer irq.

hv: timer: request timer irq once only

---

hypervisor/arch/x86/assign.c
hypervisor/arch/x86/gdt.c
hypervisor/arch/x86/timer.c
hypervisor/arch/x86/vmx.c
hypervisor/include/arch/x86/gdt.h

There are potential value outside range of underlying type
in some assignment expressions. This violates Rule 10.3 or
Rule 10.4 of MISRA C:2012.
BTW, all operations shall be conducted in exactly the same
arithmetic (underlying) type, otherwise, there is a
value outside range violation.
Update related assignment expressions.
V1-->V2:
* Fix potential overflow in "pit_calibrate_tsc";
* Move PTDEV_INVALID_PIN definition before
get_entry_info since this MACRO is only used by
debug function.
Signed-off-by: Xiangyang Wu <xiangyang.wu@linux.intel.com>

HV:treewide:fix value outside range of underlying type

---

devicemodel/hw/uart_core.c

This patch resolves one arcn-dm crash issue when rebooting UOS.
The rootcause is that uart releases unopened backend tty.
One reproduced case is that the board does not support IOC but IOC
feature is enabled in the acrn-dm. After rebooting UOS, crash will
happen.
NOTE: This issue is not related to IOC, it also can be reproduced
with NON-IOC scenario. Just set one invalid PTY to the lpc, then
this issue should be reproduced.
We need re-visit the whole policy for such scenario in future.

dm: uart: add state check of backend tty before uart_closetty

---

hypervisor/arch/x86/ept.c

Removed assert since the caller has checked the parameter.

hv:removed assert in free_ept_mem

---

hypervisor/arch/x86/vmx.c

Remove uncessary variables and function parameter

HV: vmx code clean up

---

hypervisor/arch/x86/cpu.c
hypervisor/common/schedule.c
hypervisor/include/arch/x86/cpu.h

add wrap function cpu_do_idle in default_idle to handle arch cpu specific
idle operation.

add cpu_do_idle to handle idle

---

hypervisor/debug/printf.c
hypervisor/include/arch/x86/io.h

MISRA-C requirement:
The value of an expression shall be the same under any order of
evaluation.
The order in which side effects take place is unspecified and may lead
to unexpected results.
This patch add a temporary variable for temporary storage to avoid the
side effects of evaluation order.

hv: treewide: fix 'Potential side effect problem in expression'

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/guest/vm.c
hypervisor/include/arch/x86/guest/vm.h

Added prepare_vm function as a wrapper function on top of prepare_vm0.
This makes adding support for partition mode ACRN to boot multiple
VMs from HV cleaner.

hv: Adding a wrapper on top of prepare_vm0

---

devicemodel/samples/apl-mrb/acrn_guest.service
devicemodel/samples/apl-mrb/launch_uos.sh

some exceptions can happen if westnon or network name service
not started before launch uos guest, like gvt and network exceptions,
which can cause SOS reboot. so add the dependency.
add data partiton check in launch script, for it can be called in every
clearlinux platform.

DM: check more in guest service & launch script

---

hypervisor/arch/x86/assign.c
hypervisor/arch/x86/cpuid.c
hypervisor/arch/x86/guest/instr_emul.c
hypervisor/arch/x86/guest/vioapic.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/common/hypercall.c
hypervisor/debug/shell.c
hypervisor/debug/vuart.c

This patch add some comments after the default and before the break
in the switch statement based on MISRA-C requirement.

hv: treewide: fix 'Switch empty default has no comment'

---

misc/cbc_lifecycle/cbc_lifecycle.service
tools/acrn-crashlog/data/acrnprobe.service
tools/acrn-crashlog/data/usercrash.service
tools/acrn-manager/acrnd.service
tools/acrnlog/acrnlog.service

From systemd documentation: https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecStop=
> If this option is not specified, the process is terminated by sending the signal specified in KillSignal= when service stop is requested.
https://www.freedesktop.org/software/systemd/man/systemd.kill.html#KillSignal=
> Defaults to SIGTERM.
Signed-off-by: Tan Yew Wayne <yew.wayne.tan@intel.com>

misc: Remove unnecessary ExecStop in systemd services

---

Makefile
devicemodel/Makefile

there is no git repo, which download from github release,
however, acrn-dm -v will get tag info from this repo, in
such case, the tag info was null.
this patch will fix nul tag, which get it from CL mock build.

DM: add tag info while no repo in release

---

tools/acrn-crashlog/acrnprobe/sender.c
tools/acrn-crashlog/common/fsutils.c
tools/acrn-crashlog/common/log_sys.c
tools/acrn-crashlog/usercrash/protocol.c

The changes include:
1. modify the outparam only in successful cases.
2. return -1 instead of  a errno-style value if error happens.
3. check return value of strrchr.
Tracked-On: #971

tools:acrn-crashlog: Enhance some functions

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/guest/vm.c
hypervisor/bsp/sbl/vm_description.c
hypervisor/include/arch/x86/guest/vm.h

ACRN in partitioning mode boots multiple OS. Adding code to parse
VM description structure and a reference description structure for
booting 2 OSes.

hv: Boot multiple OS for Partitioning mode ACRN

---

hypervisor/arch/x86/ept.c
hypervisor/arch/x86/guest/guest.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/guest/vmcall.c
hypervisor/arch/x86/mmu.c
hypervisor/arch/x86/trusty.c
hypervisor/common/hypercall.c
hypervisor/common/trusty_hypercall.c
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/arch/x86/trusty.h
hypervisor/include/common/hypercall.h
hypervisor/include/public/acrn_hv_defs.h

This patch series provide virtual S3 support by Trusty.
Main parts of this patch:
1. secure_world_control structure refine
Previous definition of secure_world_control is not very accurate, break
sworld_enable into 2 bit flags: supported and active. Check active bit
instead of sworld_eptp. Record base_gpa_in_sos and base_gpa_in_uos since
they will be used in virtual S3/warm reset path. This assumes the trusty's
memory address is contiguous in both SOS and physical side.
2. Remove unused hypercall id: HC_GET_SEC_INFO
3. Log printing cleanup
4. New hypercall: HC_SAVE_RESTORE_SWORLD_CTX
In UOS S3 suspend path: trusty kernel driver will call this hypercall
to require Hypervisor save context of secure world.
In UOS S3 resume path: virtual firmware will call this hypercall to
require Hypervisor …

Provide virtual S3 support by Trusty.

---

hypervisor/Makefile
hypervisor/arch/x86/guest/vm.c
hypervisor/dm/vpci/hostbridge.c
hypervisor/dm/vpci/pci_priv.h
hypervisor/dm/vpci/pci_pt.c
hypervisor/dm/vpci/pci_vdev.c
hypervisor/dm/vpci/vpci.c
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/dm/vpci/vpci.h
hypervisor/partition/vm_description.c

From 46436bf4abfa21bce0a4cbbeb79e5ccef1ad2876 Mon Sep 17 00:00:00 2001
From: dongshen <dongsheng.x.zhang@intel.com>
Date: Tue, 7 Aug 2018 19:06:14 -0700
Subject: [PATCH 0/6] V4: Adding VPCI (PCI passthru) support for partition mode
The related files are ported from device model to hypervisor to 
support partition mode.
V4:
- Renamed members for struct pcibar
- License header fix
- Added vpci_vdev_array to struct vm_description
- Clear address cache info after a full cf8/cfc access
- Added NULL pointer checking
V3:
- Defined the static centralized vpci table to reduce code size,
previously many of the settings are obtained/generated dynamically
- Do not use ASSERT
- Assume 64-bit bar size is less than 4G to simply code, and 
report 64-bit MMIO to UOS as 32-bit bar
- Patches created in …

 Adding VPCI (PCI passthru) support for partition mode

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/ioapic.c
hypervisor/common/ptdev.c
hypervisor/debug/dump.c
hypervisor/include/arch/x86/ioapic.h
hypervisor/include/common/ptdev.h
hypervisor/lib/memory.c

Declare a variable with the static qualifier if it is of file scope and
not used in another file.
v1 -> v2:
* remove the unnecessary change to the following variables, which is
due to the report issue
struct multiboot_info *mbi = (struct multiboot_info *)
(HPA2HVA((uint64_t)boot_regs[1]));
struct multiboot_mmap *mmap =
(struct multiboot_mmap *)
HPA2HVA((uint64_t)mbi->mi_mmap_addr);

hv: treewide: fix 'Variable should be declared static'

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/guest/guest.c
hypervisor/arch/x86/lapic.c
hypervisor/include/arch/x86/guest/guest.h
hypervisor/include/arch/x86/guest/vm.h
hypervisor/lib/spinlock.c

MISRAC does not allow the use of an inline function with external
linkage.
- Add the static keyword for the function that is only used in the
definition file.
- Remove the inline keyword for the function that is used in multiple
files.
v1 -> v2:
* Move some functions to headers as static inline function if it is
possible

hv: treewide: fix 'inline function should be declared static'

---

hypervisor/arch/x86/ept.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/trusty.c
hypervisor/include/arch/x86/mmu.h
hypervisor/include/arch/x86/trusty.h

-- add clear trusty memory flag
In some cases such as UOS power off or UOS full reset,
need to clear trusty memory,no need to clear memory such as
UOS S3 or UOS system reset,then add a flag to distinguish it
when destroy secure world.
-- Restore trusty memory to guest normal world.
-- Moved free trusty EPT inside destroy_secure_world
In some cases such as UOS S3 or UOS system reset,
only need to free trusty EPT, this patch move free
trusty EPT inside destroy_secure_world.
Because PD/PT are shared in both secure world's EPT
and normal world's EPT,before freeing trusty EPT,
it will memset all PDPTEs except trusty memory,
then call 'free_ept_mem', it can only free trusty EPT,
and does't affect shared normal world EPT.
v2-->v3:
-- Used new mmu api ept_mr_add when restore trusty memory
to SOS …

hv:Refine destroy_secure_world API

---

hypervisor/arch/x86/idt.S
hypervisor/arch/x86/irq.c
hypervisor/arch/x86/virq.c
hypervisor/include/arch/x86/irq.h

ACRN in partition mode does not have vector and APIC ID remapping for
device interrupts. Only MSIs are supported. No IOAPIC and legacy interrupts
for the VMs in ACRN partition mode.

hv: Interrupt handling in ACRN partition mode

---

hypervisor/arch/x86/guest/vm.c

ACRN boots multiple OS in partitioning mode. This patch adds code to assign
vm_id in the vm data structure to be same as the one assigned at compile time.
This makes the vm id deterministic for each VM booted from HV directly.

HV: Add vm_id entry to VM description in partitioning mode

---

hypervisor/arch/x86/guest/instr_emul.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vpic.c

MISRAC requires that a switch statement shall contain a default clause.
This patch add the default clause and some comments for the ones
violated the rule.

hv: treewide: fix 'No default case in switch statement'

---

hypervisor/arch/x86/cpu.c
hypervisor/include/arch/x86/cpu.h

Use func(void) rather than func() for the function declaration and
definition based on MISRAC requirement.

hv: treewide: fix 'Empty parameter list to procedure/function'

---

hypervisor/arch/x86/guest/vm.c
hypervisor/boot/sbl/multiboot.c
hypervisor/include/arch/x86/multiboot.h

For Partition mode ACRN, kernel load address and Boot args load address
are hardcoded. Boot args are currently passed from vm description for
each VM. Renamed init_vm0_boot_info to init_vm_boot_info.

hv: Partition mode ACRN -kernel load and bootargs load address

---

hypervisor/arch/x86/guest/vm.c
hypervisor/bsp/sbl/vm_description.c
hypervisor/include/arch/x86/guest/vm.h

ACRN in partition mode emulates UART for the VMs directly launced
from HV. This patch adds an option to enable/disable vUART for a
VM.

hv: Add vuart flag to VM descriptions in partition mode

---

hypervisor/arch/x86/irq.c

Modified the vector MACRO that is failing build with PARTITION_MODE selected

hv: Fixing build issue with PARTITION_MODE

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/ept.c
hypervisor/arch/x86/vmx.c
hypervisor/include/arch/x86/cpu.h
hypervisor/include/arch/x86/mmu.h

Current EPT check runs after EPT enabling in init_exec_ctrl. This
patch fixes wrong order.

HV: VMX reshuffle: put EPT check before enabling

---

hypervisor/arch/x86/virq.c
hypervisor/arch/x86/vmexit.c
hypervisor/common/schedule.c

to avoid send IPI to self, also improve the related code:
1. get_cpu_id is uint16_t now
2. MISRA-C requirement. like add {}

HV: add pcpu id check before send IPI

---

devicemodel/samples/nuc/launch_uos.sh

with original script, user can not get 3 CPU cores info with cat/proc/cpuinfo in UOS.
it just show 1 only.  with this patch,  default,  user can see 1 cpu info in SOS and 3 cores info in UOS.
and remove 2M hugepages settings because it is not using any more.
echo 1024 > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
also, this patch is setting default UOS memory to 2G

fixed cpu info incorrect and remove 2M hugepages

---

hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/guest/vm.c

- clear run context when reset vcpu;
- destroy trusty without erase trusty memory when reset vm;
changelog:
v1 -> v2: fix misra violation on calling memset();
Signed-off-by: Sun Victor <victor.sun@intel.com>
Reviewed-by: Chi Mingqiang <mingqiang.chi@intel.com>

HV: handle trusty on vm reset

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/cpuid.c
hypervisor/arch/x86/timer.c

This is the patch set that adds the emulation of cupid 0x16 so that the guest can obtain the cpu hz by calling cupid.
At the same time HV also obtains the cpu hz by using cupid 0x16 if zero tsc is returned by cupid 0x15.

Add the emulation of Cpuid 0x16 for guest to obtain cpu hz by calling cpuid

---

hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/lapic.c

MISRA-C requires that shift operation cannot exceed the word length.
- Add the pre condition for 'init_lapic' regarding to 'pcpu_id'
Currently, max 8 physical cpus are supported.
Re-design will be required if we would like to support more physical
cpus.
So, add the pre condition here to avoid the unintentional shift
operation mistakes.
- Replace the id type with uint8_t in 'vlapic_build_id'
- For VM0, it uses 'lapic_id' as its id, which is uint8_t.
- For non VM0, it uses 'vcpu_id' as its id, which is uint16_t.
Cast this id to uint8_t to make sure there is no loss of data after
left shifting 24U.

hv: treewide: fix 'Shifting value too far'

---

hypervisor/arch/x86/irq.c
hypervisor/arch/x86/notify.c
hypervisor/arch/x86/timer.c
hypervisor/arch/x86/vtd.c
hypervisor/common/ptdev.c
hypervisor/include/arch/x86/irq.h
hypervisor/include/common/irq.h

Two commits included:
hv: pirq: add static irq:vector mappings
- to remove "vector" in irq API for special irq with vector determined statically;
hv: pirq: rename common irq APIs
- renamed the APIs to request_irq()/free_irq()

HV: pirq: renamed irq APIs

---

tools/acrntrace/scripts/irq_analyze.py
tools/acrntrace/scripts/vmexit_analyze.py

Originally, we don't format the output of analyser well. It is hard to read the
result.
This patch make every entry of the result align with the corresponding title to
make it easier for users to read.
Without patch:
Event                    NR_Exit         NR_Exit/Sec     Time Consumed(cycles)       Time Percentage
VMEXIT_INTERRUPT_WINDOW         78090   130.15  40      0.01
VMEXIT_CR_ACCESS        0       0.00    0       0.00
VMEXIT_APICV_ACCESS     0       0.00    0       0.00
VMEXIT_EXCEPTION_OR_NMI         0       0.00    0       0.00
VMEXIT_RDTSC    0       0.00    0       0.00
...
Vector          Count   NR_Exit/Sec
0x000000f0       82337  137.23
0x000000ef       247713         412.85
With patch:
Event                           NR_Exit         NR_Exit/Sec     Time Consumed(cycles) …

tools: acrnalyze: Make the result easier to read

---

hypervisor/arch/x86/guest/vmcall.c
hypervisor/common/hv_main.c
hypervisor/common/hypercall.c
hypervisor/include/arch/x86/per_cpu.h

Thare some debug specific code which don't run on release version, such as vmexit_time,
vmexit_cnt, sbuf related codes, etc...
This patch enclose these codes with #ifdef HV_DEBUG.

HV: Enclose debug specific code with #ifdef HV_DEBUG

---

hypervisor/arch/x86/ept.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/io.c
hypervisor/common/io_request.c
hypervisor/dm/vioapic.c
hypervisor/include/arch/x86/ioreq.h
hypervisor/include/public/acrn_common.h

Now the DM has adopted the new VHM request state transitions and
REQ_STATE_FAILED is obsolete since neither VHM nor kernel mediators will set the
state to FAILED.
This patch drops the definition to REQ_STATE_FAILED in the hypervisor, makes
''processed'' unsigned to make the compiler happy about typing and simplifies
error handling in the following ways.
* (dm_)emulate_(pio|mmio)_post no longer returns an error code, by introducing a
constraint that these functions must be called after an I/O request
completes (which is the case in the current design) and assuming
handlers/VHM/DM will always give a value for reads (typically all 1's if the
requested address is invalid).
* emulate_io() now returns a positive value IOREQ_PENDING to indicate that the
request is sent to VHM. This mitigates a …

HV: io: drop REQ_STATE_FAILED

---

hypervisor/arch/x86/guest/vcpu.c

conflicting types for ‘vcpu_dumpreg’

quick fix: fix build failure for release version

---

doc/getting-started/apl-nuc.rst

add user and enable weston service to fix issue: #663
#. Add new user
.. code-block:: console
#. Enable weston service
.. code-block:: console

enable weston to fix: #663

---

hypervisor/arch/x86/assign.c
hypervisor/common/hypercall.c
hypervisor/dm/vioapic.c
hypervisor/dm/vpic.c
hypervisor/include/arch/x86/guest/vioapic.h
hypervisor/include/arch/x86/guest/vpic.h

-- Change these APIs to void type, add pre-conditions,
and move parameter-check to upper-layer functions.
handle_vpic_irqline
vpic_set_irqstate
vpic_assert_irq
vpic_deassert_irq
vpic_pulse_irq
vpic_get_irq_trigger
handle_vioapic_irqline
vioapic_assert_irq
vioapic_deassert_irq
vioapic_pulse_irq
-- Remove dead code
vpic_set_irq_trigger
v1-->v2:
add cleanup vpic
change some APIs to void type, add pre-conditions,
and move the parameter-check to upper-layer functions.

hv:fix return value violations for vpic/vioapic

---

hypervisor/debug/vuart.c
hypervisor/include/debug/vuart.h

MISRA-C requires that shift operation cannot exceed the word length.
- Fix the bug in 'vuart_init'
The register 'dll' and 'dlh' should be uint8_t rather than char.
'dll' is the lower 8-bit of divisor.
'dlh' is the higher 8-bit of divisor.
So, the shift value should be 8U rather than 16U.
- Fix other data type issues regarding to the registers in 'struct
vuart'
The registers should be unsigned variables.
v1 -> v2:
* Use a local variable 'uint8_t value_u8 = (uint8_t)value' to avoid
mutiple times type conversion
* Use '(uint8_t)divisor' rather than '(uint8_t)(divisor & 0xFFU)' to
get the lower 8 bit of 'divisor'
Direct type conversion is safe and simple per Xiangyang's suggestion.
Reviewed-by: Junjie …

hv: vuart: fix 'Shifting value too far'

---

devicemodel/hw/pci/virtio/virtio_rpmb.c
devicemodel/include/rpmb.h

RPMB frontend driver in UOS kernel has fixed unstable issue,
which requires BE for update as well. E.g. structure adjustment,
definition modification and so on.
Signed-off-by: Deng Wei <wei.a.deng@intel.com>

DM: virtio rpmb backend driver updates

---

hypervisor/arch/x86/ioapic.c
hypervisor/arch/x86/irq.c
hypervisor/common/ptdev.c
hypervisor/debug/logmsg.c
hypervisor/include/arch/x86/cpu.h
hypervisor/include/lib/spinlock.h

- remove the global declaration of 'cpu_int_value'

HV: remove 'spinlock_rfags' declaration

---

hypervisor/arch/x86/io.c

struct io_request gets rid of "processed" element. Modified io exit handler
for partition mode to accomodate the change.

hv: Build fix for Partition mode

---

hypervisor/dm/vioapic.c

Now the guest may change "Destination Field", "Trigger Mode",
"Interrupt Input Pin Polarity" even "Interrupt Vector" when
"Interrupt Mask" not masked. So we should update the pass through
device interrupt pin rte in this situation. The old logic would
update it only when "Interrupt Mask" or "Trigger Mode" or
"Interrupt Input Pin Polarity" was changed.
update ptdev native ioapic rte when (a) something changed and
(b) the old rte interrupt mask is not masked or the new rte interrupt
mask is not masked.

hv: vioapic: bug fix update PTDEV RTE

---

hypervisor/arch/x86/guest/vcpu.c

BSPs for VMs booted in ACRN partition mode start in protected mode.

hv: VM BSP vcpu mode for ACRN partition mode

---

tools/acrn-crashlog/README.rst
tools/acrn-crashlog/data/acrnprobe_prepare.sh
tools/acrn-crashlog/usercrash/README.rst

This patch is to improve the way of updating the core_pattern content
in the shell script, since the previous configuration in core_pattern
will block coredumpctl.
This patch adds an inspection before changing the content of
core_pattern.
Reviewed-by: xiaojin2 <xiaojing.liu@intel.com>

tools: acrn-crashlog: update core_pattern content conditionally

---

doc/tutorials/using_ubuntu_as_sos.rst

1, update contents to align latest acrn and clear Linux release
2, change /etc/grub.d/40_custom file to specify 'insmod ext2', not 'insmod ext4' and github issue- https://github.com/projectacrn/acrn-hypervisor/issues/707
3, add tap device and network sharing enabling script as the example for ubuntu SOS
4, add several tips for new user to use ubuntu as the SOS
Signed-off-by: ailun258 ailin.yang@intel.com

update doc -Using Ubuntu as the Service OS

---

hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vlapic_priv.h
hypervisor/arch/x86/virq.c

The 2nd patch set is majorly for vmx vapic reshuffle. The lvt, nmi and split vmx_vapic are still WIP. 
-refine the interrupt-window related code.
-fix several bugs.
-remove x2apic, APIC ID register related code.
-cleanup the APIC-access VM exit handler.
-rename the apicv to vmx_vapic in vlapic.c.
-rename the vapic to vmx_vapic in virq.c.
This the first wave, the second wave need to submit v2 for continue review.

WAVE-1: 2nd patch set for vioapic/vlapic/vpic reshuffle

---

hypervisor/arch/x86/cpu_state_tbl.c
hypervisor/arch/x86/cpuid.c
hypervisor/arch/x86/ept.c
hypervisor/arch/x86/guest/guest.c
hypervisor/include/arch/x86/cpuid.h
hypervisor/include/arch/x86/guest/guest.h
hypervisor/include/arch/x86/io.h
hypervisor/include/arch/x86/mmu.h
hypervisor/include/arch/x86/pgtable.h
hypervisor/include/arch/x86/vmx.h

V1:
In order to better comply with MISRA C,
add const qualifiers whereever required.
In the patch, these are being added to pointers
which are normally used in "get" functions.
V2: Corrected the issues in the patch
pointed by Junjie in his review comments.
Moved the const qualifiers to the correct
places. Removed some changes which are not
needed.
V3: Updated patch comment.
This modifies a subset of all the functions
which might need constant qualifiers
for the their parameters.
This is not and exhaustive patch. This only
targets obvious places where we can use
the const qualifier. More changes will be
submitted in future patches, if required.

HV: Add const qualifiers where required

---

doc/developer-guides/primer.rst
hypervisor/include/arch/x86/trusty.h

Fix comments referring to wrong hypervisor name

hv: Fix comments referring to wrong hypervisor name

---

hypervisor/partition/vm_description.c

1) Changed VM memory size from 2 GB to 512 MB
Some platforms might not have a total of 4 GB above 4 GB in host e820
With this change, we need a total of only 1 GB above 4 GB in host e820
2) Update e820 entries for the above change
3) type fix for VM1_CPUS and VM2_CPUS
4) Add mptable pointer info to each VM vm_desc

hv: vm_description fix for partition ACRN

---

hypervisor/arch/x86/assign.c
hypervisor/arch/x86/ioapic.c
hypervisor/arch/x86/irq.c
hypervisor/arch/x86/notify.c
hypervisor/arch/x86/timer.c
hypervisor/arch/x86/vtd.c
hypervisor/common/ptdev.c
hypervisor/include/arch/x86/ioapic.h
hypervisor/include/arch/x86/irq.h
hypervisor/include/common/irq.h

This series makes following changes:
- refactored codes for irq request/free code clearer and easy to read;
- merged confusing irq handlers into a single generic one with lock removed;
- clean up irq_desc struct and function orders in irq.c.

hv: physical irq reshuffle - allocation/free and irq handler

---

hypervisor/include/lib/bits.h

Add ffz64_ex to find the first zero bit in a uint64_t array.
Note: the API is lockless.

hv: lib: add ffz64_ex

---

devicemodel/samples/nuc/launch_uos.sh

there are only 2 CPUs on UP2 platform, so we can only start 1 cpu for
uos on UP2 platform.
as this is only an example script, user can modify the uos start CPU
number according his requirement.

samples: let nuc uos only start with 1 cpu

---

hypervisor/arch/x86/ept.c
hypervisor/include/arch/x86/guest/vm.h

for secure and normal world has different EPTP, in secure world,
it could trap to hypervisor and call gpa2hpa function. So it need
check if it is in normal or secure world for EPTP selection.
Detailed explanation from Yadong Qi <yadong.qi@intel.com>:
Currently, trusty OS does not handle interrupt, so when an interrupt
is delivering in trusty, trusty will set it to LAPIC IRR register by
inject self_ipi() and then call world_switch to switch to Android,
So android will receive/handle the interrupt properly.Since the
vLAPIC is enabled in ACRN, so when trusty try to inject self_ipi(),
APIC-ACCESS vmexit will happen. Then ACRN will do instruction
decode/emulation, so the GPA2HPA will fail since page walk is using
nworld_eptp. It is probability an issue.
Signed-off-by: Minggui Cao …

HV: check secure/normal world for EPTP in gpa2hpa

---

hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/trusty.c
hypervisor/boot/reloc.c
hypervisor/boot/sbl/multiboot.c
hypervisor/debug/console.c
hypervisor/debug/shell.c
hypervisor/include/arch/x86/timer.h

-- change two timer callbacks to void type
-- ignore the return value for add_timer
-- add (void) before several functions(memset/memcpy/
vcpu_get_xxx)
v1-->v2:
ignore the return value for add_timer

hv:fixed several return value violations

---

devicemodel/core/sw_load_vsbl.c
devicemodel/hw/platform/cmos_io.c
devicemodel/include/vmmapi.h

CMOS offset from 0x20 to 0x9F is used to store rpmb key information.
vsbl loader will init vrpmb key in CMOS when boot/reboot.
vsbl loader will not init vrpmb key during S3 resume.
vsbl will read vrpmb key via CMOS interface.
After reading, the key value is cleared in CMOS. So the key can only be
read once until next boot.

dm: pass vrpmb key via cmos interface

---

hypervisor/debug/shell.c
hypervisor/debug/vuart.c
hypervisor/include/debug/vuart.h

ACRN in partition mode provides vUART for all VMs. This patch adds
support to add console redirection for multiple VMs.

hv: Support HV console for multiple VMs - ACRN partition mode

---

hypervisor/include/arch/x86/guest/vioapic.h

Remove two APIs without definition

hv: vioapic: fix 'No definition in system for prototyped procedure'

---

hypervisor/arch/x86/assign.c
hypervisor/arch/x86/lapic.c
hypervisor/arch/x86/virq.c
hypervisor/arch/x86/vmexit.c
hypervisor/debug/logmsg.c
hypervisor/include/arch/x86/lapic.h

-- change send_start_ipi/do_copy_earlylog to void type
-- drop the return value for vcpu_queue_execption
when inject GP/PF/UD/AC/SS

hv:fixed MISRA-C return value violations

---

devicemodel/samples/apl-mrb/launch_uos.sh

So far, the xHCI mediator does not support USB HUB over usb pmapper. But
there are some USB touch devices integrated internal USB HUB, then
cause such touch models can't be supported. Will consider to re-enable
xHCI mediator by default once HUB support related patches get merged in
the near future.
Signed-off-by: Liang Yang <liang3.yang@intel.com>
Reviewed-by: Binbin Wu<binbin.wu@intel.com>

DM USB: xHCI: Change the default USB xHCI support to pass through.

---

hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/vmx.c
hypervisor/include/arch/x86/guest/guest.h

MISRAC requires that the array size should be declared explicitly.
This patch fixes the issues caused by vm0_boot_context.
Fix pattern is like below:
extern char start_of_ROM, end_of_ROM, start_of_FLASH;
memcpy (& start_of_FLASH, & start_of_ROM, & end_of_ROM - &
start_of_ROM);

hv: vmx: fix 'Array has no bounds specified'

---

hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vlapic_priv.h
hypervisor/include/arch/x86/apicreg.h
hypervisor/lib/memory.c

- should free allocated memory in case of registering
mmio handler failure.

HV: fix potential memory leak in 'vlapic_create()'

---

hypervisor/arch/x86/irq.c
hypervisor/include/arch/x86/irq.h
hypervisor/include/common/irq.h

This commit replaces the "used" field of irq_desc with a bitmap to maintain
the irq use status to save memory and LOC, and improve the efficiency as well.

hv: pirq: use a bitmap to maintain irq use status

---

hypervisor/include/arch/x86/guest/vlapic.h
hypervisor/include/arch/x86/mmu.h
hypervisor/include/debug/console.h

Remove the functions without definition.

hv: fix 'No definition in system for prototyped procedure'

---

hypervisor/arch/x86/cpuid.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vmsr.c
hypervisor/debug/dump.c
hypervisor/debug/shell.c
hypervisor/debug/vuart.c
hypervisor/dm/vioapic.c
hypervisor/dm/vpci/pci_pt.c
hypervisor/include/arch/x86/vmx.h
hypervisor/lib/memory.c

- Clean up some code regarding to % and / operations since bit
operations are faster.
x % 64U ---> x & 0x3fU
x % 32U ---> x & 0x1fU
x % 16U ---> x & 0xfU
x % 8U  ---> x & 0x7U
x % 4U  ---> x & 0x3U
x % 2U  ---> x & 0x1U
x / 64U ---> x >> 6U
x / 32U ---> x >> 5U
x / 16U ---> x >> 4U
x / 8U  ---> x >> 3U
x / 4U  ---> x >> 2U
x / 2U  ---> x >> 1U
- Minor changes regarding to coding styles

hv: code clean up regarding to % and / operations

---

hypervisor/arch/x86/cpuid.c

We didn't emualte them well, so just disable them.
Here are PMU CPUID.0A, Intel RDT CPUID.0F and CPUID.10, Intel SGX CPUID.12,
Intel Processor Trace CPUID.14

hv: vcpuid: disable some features in cpuid

---

hypervisor/arch/x86/Kconfig
hypervisor/arch/x86/guest/vmcall.c
hypervisor/common/hypercall.c
hypervisor/debug/logmsg.c
hypervisor/debug/npk_log.c
hypervisor/debug/shell.c
hypervisor/debug/shell_priv.h
hypervisor/include/arch/x86/io.h
hypervisor/include/arch/x86/per_cpu.h
hypervisor/include/common/hypercall.h
hypervisor/include/debug/logmsg.h
hypervisor/include/debug/npk_log.h
hypervisor/include/hv_debug.h
hypervisor/include/public/acrn_hv_defs.h

This series of patches implement a log destination for the hypervisor,
npk_log, which is similar to the console_log and the mem_log.
The Intel Trace Hub (aka. North Peak, NPK) is a trace aggregator for
Software, Firmware, and Hardware. The npk_log utilizes the NPK by
writing the hypervisor logs directly to the MMIO address of the
reserved NPK master, so that the hypervisor logs can be consolidated
together with any other logs sent to the NPK from other parts of the
virtualization platform with an unified timestamp.
In order to enable/disable/configure the npk_log from the SOS kernel,
a hypercall HC_SETUP_HV_NPK_LOG (the first patch of the series) and a
kernel driver (covered by another patch series) are also added.

hv: debug: add the hypervisor NPK log

---

hypervisor/arch/x86/assign.c
hypervisor/common/hypercall.c
hypervisor/common/ptdev.c
hypervisor/dm/vioapic.c
hypervisor/dm/vpic.c
hypervisor/include/arch/x86/assign.h
hypervisor/include/common/ptdev.h

Try to simplify the ptdev logic:
1. simplify the lookup method: use source id to identify the ptdev;
2. only check whether phys_pin is valid in add_intx_remapping
3. remove unnecessary variable from structure ptdev_msi_info

ptdev cleanup

---

hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vlapic_priv.h

- call these functions directly, no need to register
callbacks.

HV: remove callbacks registration for APICv functions

---

hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/vtd.c
hypervisor/include/arch/x86/vtd.h

In current code, the address translation type for passthrough devices
in SOS is passthrough type, which means the device in SOS can access
the whole physcial memory.
This patch uses SOS EPT to translate address for passthrough
devices. So that the memory of VMM or trusty can be protected from
SOS PTDev.

hv: vtd: use EPT as translation table for PTDev in SOS

---

devicemodel/hw/pci/xhci.c

This patch is used to fix a potential issue resulted from typo.

DM USB: xHCI: fix a potential issue of crash

---

hypervisor/arch/x86/gdt.c
hypervisor/include/arch/x86/gdt.h

In the gdt.h, it defines unions and parameters which is not used
in hypervisor. Removed them to keep the gdt definition simple.

HV: Removed unused parameters and unions from gdt

---

tools/acrn-manager/acrn_vm_ops.c
tools/acrn-manager/acrnctl.h

This commit eliminates several compiler warnings via:
- added 'const' quilifier to the 1st argument of send_msg();
- added 'const' quilifier to vm ops functions.

tools: acrn-manager: fix several warnings

---

hypervisor/arch/x86/trusty.c

We should specify gpa for uos or sos when restore memory, otherwise
it would cause resume failure issue.
Reviewed-by: Mingqiang Chi <mingqiang.chi@intel.com>

HV: restore correct gpa for guest normal world

---

hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/guest/vmsr.c
hypervisor/include/arch/x86/guest/vcpu.h

Change guest_msrs in vcpu data structure from pointer to array, which
could avoid the dynamic memory allocation.
v1 -> v2:
* Remove the unnecessary initialization for guest_msrs[] since vcpu is
allocated by calloc.

hv: code clean up regarding to guest_msrs

---

hypervisor/arch/x86/ept.c
hypervisor/arch/x86/trusty.c

There is no requirement to  hpa2gpa for trusty memory,
now we use the same inverted eptp for normal world and secure world,
that is it can get some trusty memory information by the inverted
page tables in normal world,then this patch removed the inverted
page tables for trusty memory.

hv:No need to create inverted page tables for trusty memory

---

tools/acrn-crashlog/acrnprobe/README.rst
tools/acrn-crashlog/acrnprobe/conf.rst

This document explains all fields in acrnprobe.xml.
User could use it to control acrnprobe's behavior and configure their
own events.

tools:acrn-crashlog: Document of configuration file

---

devicemodel/hw/platform/cmos_io.c
devicemodel/include/vmmapi.h

The whole vmctx will be cleared during cold reset.
cmos data should not be cleared during cold reset.
Move cmos data out of vmctx.
Tracked-On: #1118

dm: cmos: move cmos storage out of vmctx

---

doc/Makefile
doc/scripts/extract_content.py
tools/acrn-crashlog/README.rst
tools/acrn-crashlog/acrnprobe/conf.rst
tools/acrn-crashlog/acrnprobe/images/crash-config.dot
tools/acrn-crashlog/acrnprobe/images/crash-match.dot
tools/acrn-crashlog/images/crashlog-workflow.dot
tools/acrn-crashlog/usercrash/README.rst

The doc build process copies files using script/extract-content.py from
outside of the doc/ folder (specifically content in the tools/ folders).
The script was not copying graphviz directive files.  This has been
fixed and the embedded graphviz directives are not (properly) stored in
separate image/*.dot files.
Note the extract-content.py file is derived from the Zephyr project.

doc: fix graphviz scanning and processing

---

hypervisor/arch/x86/idt.S
hypervisor/include/arch/x86/cpu.h

Since vmexit handling in ACRN partition mode is not complex (since no SOS and
all devices passthru), interrupts can stay disabled in root mode during
vmexit handling.

hv: Leave interrupts disabled during vmexit - ACRN partition mode

---

devicemodel/hw/platform/ioc.c

This patch fixes an issue that CBC signal channel
is inactive after SOS resuming, it leads to IOC mediator
cannot transfer any signals between UOS and SOS. So IOC
mediator sends the open channel command to activate CBC
signal channel after resuming.
Tracked-On: #1115

IOC mediator: fix no CBC signals after resuming

---

devicemodel/samples/apl-mrb/launch_uos.sh

remove extra "-l com1,stdio" option for dm
Tracked-On: #1123

samples: remove extra option for dm

---

devicemodel/Makefile
hypervisor/arch/x86/Kconfig
tools/acrn-manager/Makefile

To be sure hypervisor and DM are position independent
and executable.
Signed-off-by: wenshelx <wenshengx.wang@intel.com>

security: Enable '-fpie, -pie' options

---

doc/getting-started/apl-nuc.rst

Update the Getting Started Guide to correct the URL pointing at
the sample 'acrn.conf' file that is in the source code tree.

Documentation: correct URL pointing at sample 'acrn.conf' file

---

hypervisor/arch/x86/guest/mptable.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/partition/vm_description.c

VMs in partition mode uses a kernel patch to switch to physical mode xAPIC.
The kernel patch together with this patch makes sure device MSIs use
physical mode as DM and physical APIC IDs in Destination field. bootargs in
partition/vm_description.c uses a new parameter xapic_phys for the kernel patch
to take effect.

hv: Device MSIs in partition mode ACRN

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/cpu_primary.S
hypervisor/arch/x86/ept.c
hypervisor/arch/x86/guest/guest.c
hypervisor/arch/x86/mmu.c
hypervisor/arch/x86/mtrr.c
hypervisor/arch/x86/pagetable.c
hypervisor/arch/x86/trampoline.S
hypervisor/arch/x86/trusty.c
hypervisor/common/vm_load.c
hypervisor/include/arch/x86/mmu.h
hypervisor/include/arch/x86/pgtable.h
hypervisor/include/arch/x86/pgtable_types.h

Since we reshuffle mmu code, there're many MACRO or structure we don't use 
any more in mmu.h. This serial try to remove them and replace the outdated
with the new one.

Mmu: cleanup mmu.h

---

hypervisor/arch/x86/guest/guest.c
hypervisor/arch/x86/vtd.c
hypervisor/debug/shell.c

This patch fixes the following issues:
- No newline after semi colon.
- No space after semi colon in for expression.
- No space between if, while, for and expresn.

hv: fix MISRA-C issues related to space or newline

---

hypervisor/boot/reloc.c

commit a71dedecd4dc ("hv: treewide: fix 'Array has no bounds specified")
misses one '&', which breaks the hypervisor relocation feature.

hv: fix broken relocation feature

---

devicemodel/hw/pci/npk.c
devicemodel/samples/apl-mrb/launch_uos.sh

This series of patches enable the NPK virtualization for AaaG if the
NPK device/driver is present.
To align with the configuration of the host tool, the SW masters are
organized in slices of 8 masters each. The slice is also the minimal
unit to allocate the SW masters for each UOS.
The 1st patch is to update the parameter checking function.
The 2rd patch is to update the launching script to enable the NPK
virtualization for AaaG if the NPK device/driver is present.
Tracked-On: #1138
Signed-off-by: Zhi Jin <zhi.jin@intel.com>
Reviewed-By: Chen Gang <gang.c.chen@intel.com>

DM NPK: enable the NPK virtualization for AaaG

---

hypervisor/arch/x86/guest/ucode.c
hypervisor/arch/x86/io.c
hypervisor/arch/x86/vmexit.c
hypervisor/common/hv_main.c
hypervisor/include/arch/x86/cpu.h
hypervisor/include/arch/x86/vmexit.h

MISRA-C requires that each parameter in the MACRO shall be in brackets.
In some cases, adding brackets for all of the parameters may not be a
perfect solution.
For example, it may affect the code readability when there are many
parameters used in the MACRO.
And duplicated brackets will appear when one MACRO called another MACRO
which is using same parameters.
This patch convert some MACROs to inline functions to avoid such cases.
v1 -> v2:
* Remove the unnecessary changes in hypervisor/bsp/uefi/efi/boot.h

hv: treewide: convert some MACROs to inline functions

---

tools/acrn-crashlog/Makefile

This patch is to correct the path of usercrash-wrapper.

tools: acrn-crashlog: correct usercrash-wrapper path

---

tools/acrntrace/acrntrace.c

'err' may be used uninitialized and be dereferenced NULL.
This commit fix the reported issue via initializing 'err' to 0, and return 'err'
at the end of the func.
Tracked-On: #1157

tools: acrntrace: fix a variable uninitialized issue

---

devicemodel/hw/pci/wdt_i6300esb.c

1. The default prescaler clock is 1 KHz for a 20-bit counter, which
means approximate 1 second for 10 bits;
2. the default reset timer in seconds need to left shift 10 bits to
represent the value that set to i6300esb register;
Tracked-On: #1142

DM: watchdog: correct 2 MACRO define

---

hypervisor/arch/x86/guest/guest.c
hypervisor/arch/x86/ioapic.c
hypervisor/arch/x86/mmu.c
hypervisor/dm/vpic.c
hypervisor/include/arch/x86/guest/guest.h
hypervisor/include/arch/x86/guest/vpic.h
hypervisor/include/arch/x86/ioapic.h

MISRA-C requires that each function defined and declared shall be called
or referenced in code analyzed.
In some cases, we would like to keep the non-called functions for code
completeness, such as
vcpu_inject_extint/vcpu_inject_nmi/vcpu_inject_gp/vcpu_inject_pf
/vcpu_inject_ud/vcpu_inject_ac/vcpu_inject_ss.
This pacth removes some functions that are independent and are not
called in our code base.

hv: fix 'Procedure is not called or referenced in code analysed'

---

devicemodel/hw/platform/ioc.c
devicemodel/include/ioc.h

Support VBUS control for USB OTG.
Tracked-On: #1159

IOC mediator: add new signal for VBUS control

---

hypervisor/arch/x86/cpu.c

If hardware_detect_support() failed,as it return to
bsp_boot_init with a different stack and thus returning
from bsp_boot_init becomes an undefined behavior.

hv: replace 'return' with 'panic' in bsp_boot_post

---

hypervisor/arch/x86/guest/guest.c
hypervisor/arch/x86/guest/mptable.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vmsr.c
hypervisor/arch/x86/ioapic.c
hypervisor/arch/x86/lapic.c
hypervisor/arch/x86/mmu.c
hypervisor/arch/x86/pagetable.c
hypervisor/arch/x86/pm.c
hypervisor/arch/x86/trusty.c
hypervisor/arch/x86/virq.c
hypervisor/arch/x86/vmx.c
hypervisor/arch/x86/vtd.c
hypervisor/boot/acpi.c
hypervisor/boot/reloc.c
hypervisor/boot/sbl/multiboot.c
hypervisor/bsp/uefi/cmdline.c
hypervisor/bsp/uefi/uefi.c
hypervisor/common/hypercall.c
hypervisor/common/vm_load.c
hypervisor/debug/uart16550.c
hypervisor/dm/vpci/pci_pt.c
hypervisor/include/arch/x86/pgtable.h
hypervisor/include/hypervisor.h

Convert HPA2HVA, HVA2HPA, GPA2HVA and HVA2GPA to inline functions.
v1 -> v2:
* Modify the following statement.
rsdp = biosacpi_search_rsdp((char *)hpa2hva((uint64_t)(*addr << 4)),
0x400);
Instead of "(uint64_t)(*addr << 4)", "(uint64_t)(*addr) << 4U" would
be clearer.

hv: pgtable: fix 'Use of function like macro'

---

hypervisor/arch/x86/virq.c

The 3th patch set is majorly for "interrupt-window exiting" related reshuffle.
-avoid enable interrupt window if interrupt delivery enabled.
-enable interrupt-window if any vpic pending interrupts.
-refine the irq_window_enabled parameter usage.
Tracked-On: #1187, #1189, #1190
Signed-off-by: Yu Wang <yu1.wang@intel.com>

3th patch set for vioapic/vlapic/vpic reshuffle

---

hypervisor/arch/x86/assign.c
hypervisor/arch/x86/guest/vm.c
hypervisor/common/ptdev.c
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/common/ptdev.h

this patch is used to avoid pass-thru devices interrupt 
interferences between different VMs.
for each pass-thru device and its entry owned by one VM, 
so change the pass-thru device's softirq lock & entry list 
into per VM, so one VM's PT device interrupt process will 
not interfere with other VMs; especially in case one UOS
"interrupt storm" happens, it will have little effect on SOS.
Tracked-On: #866

HV: improve pass-thru device interrupt process

---

devicemodel/samples/apl-mrb/acrn_guest.service
devicemodel/samples/apl-mrb/launch_uos.sh

launch two clearlinux will use the same 'LaaG' as tap interface name. Add tap
name as parameter that will meet two UOS using different tap interface.
Tracked-On: projectacrn/acrn-hypervisor#1173
Signed-off-by: Jiangbo Wu <jiangbo.wu@intel.com>
Signed-off-by: Jiangbo Wu <jiangbo.wu@intel.com>

samples: Add tap name as launch function parameter

---

hypervisor/bsp/sbl/platform_acpi_info.c

MRB bootloader is switched to ABL, so change platform acpi info accordingly
to support system S3.
Tracked-On: #1196

HV: change wake vector info to accommodate abl

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/guest/guest.c
hypervisor/arch/x86/guest/instr_emul.c
hypervisor/arch/x86/guest/instr_emul.h
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/pagetable.c
hypervisor/arch/x86/vmx.c
hypervisor/arch/x86/vtd.c
hypervisor/boot/reloc.c
hypervisor/debug/dump.c
hypervisor/debug/logmsg.c
hypervisor/debug/npk_log.c
hypervisor/include/arch/x86/cpu.h
hypervisor/include/arch/x86/guest/vcpu.h
hypervisor/include/arch/x86/mmu.h
hypervisor/include/arch/x86/msr.h
hypervisor/include/arch/x86/vmx.h
hypervisor/include/lib/atomic.h
hypervisor/include/lib/macros.h
hypervisor/include/lib/util.h
hypervisor/lib/memory.c
hypervisor/lib/string.c

- convert function like macros to inline functions based on MISRA-C
requirement
- remove some unused and duplicated macros

hv: treewide: fix 'Use of function like macro'

---

hypervisor/arch/x86/cpu.c

In function start_cpus, we allocated memory under 1M when
preparing AP trampoline code.
With S3 feature enabled, start_cpus is called every time after
ACRN resume from S3 which leaks the allocated memory for AP
trampoline code.
To avoid memory leak, move the AP trampoline preparing function
out of start_cpus to make sure the memory for AP trampoline is
only allocated one time when system boot.
Tracked-On: #1156
Reviewed-by: Zide Chen <zide.chen@intel.com>

hv: avoid memory leak in trampoline code preparing

---

hypervisor/bsp/sbl/platform_acpi_info.c

MRB bootloader is switched to ABL ver 1820HF1_release, so change platform
acpi info accordingly to support system S3.
Tracked-On: #1196

HV: change wake vector to accommodate abl 1820HF1release

---

doc/conf.py

In special cases, we'd like to freeze doc versions based on a tag (e.g.,
tags/acrn-2018w34.4-140000p) and have that version show up on the
generated docs.  (Normally the version shown is from the
hypervisor/VERSION file.)
With this patch, if DOC_TAG=release then it uses a RELEASE=name
environment variable (e.g., from the make command line) to override the
displayed version:
make DOC_TAG=release RELEASE=acrn-2018w34.4-140000p html
make DOC_TAG=release RELEASE=acrn-2018w34.4-140000p publish
Assuming you've checked out the tagged branch (both for acrn-hypervisor
and acrn-kernel), these make commands will generate and publish docs to
https://projectacrn.github.io/acrn-2018w34.4-14000p

doc: allow overriding displayed doc version

---

devicemodel/hw/platform/ioc_cbc.c
devicemodel/include/ioc.h

This patch implements RTC feature that UOS can set RTC wakeup timer
to IOC firmware with a specific time before enter S3/S5. IOC mediator
also needs to indicate RTC wakeup reason to UOS after exit S3/S5.
Tracked-On: #1213

IOC mediator: add RTC feature

---

devicemodel/hw/pci/passthrough.c

In current code, when read/write msix table, it first handle the case
the offset is in pba range when msix talbe and pba share the same bar.
But the code didn't add the condition whether pba bar equals msix table
bar. It will cause problems for the passthrugh devices,whose pba and msix
table don't share the same bar.
Tracked-On: #1209

dm: passthru: fix a bug in msix read/write

---

hypervisor/arch/x86/vtd.c
hypervisor/dm/vpic.c

- remove the following unnecessary spinlock wrappers
#define IOMMU_LOCK(u) spinlock_obtain(&((u)->lock))
#define IOMMU_UNLOCK(u) spinlock_release(&((u)->lock))
- remove the unnecessary comments in vpic.c

hv: clean up spinlock wrappers

---

tools/acrn-crashlog/acrnprobe/history.c
tools/acrn-crashlog/acrnprobe/include/load_conf.h
tools/acrn-crashlog/acrnprobe/include/probeutils.h
tools/acrn-crashlog/acrnprobe/probeutils.c
tools/acrn-crashlog/acrnprobe/sender.c

Acrnprobe is using SHA to generate ids for events. These ids are only used
to index events, not for cryptographic purpose.
This patch unify the generating algorithm of short and long ids to
SHA256.

tools:acrn-crashlog: Change the algorithm of generating event key

---

hypervisor/common/hypercall.c

in local_set_vm_memory_region, hpa is not used for MR_DEL, and it does
not need check HV memory overlap for a MR_DEL operation.
this is a bug exposed by remapping SOS first page, as the remap page whose
gpa = 0 actually fall into HV memory area; while during MR_DEL, the input
param vm0_gpa is set to 0 by default.
Tracked-On: #1124

hypercall: no need check HV memory overlap for MR_DEL

---

hypervisor/arch/x86/guest/instr_emul.c
hypervisor/arch/x86/mmu.c
hypervisor/arch/x86/timer.c
hypervisor/arch/x86/trusty.c
hypervisor/arch/x86/vmx.c
hypervisor/boot/acpi.c
hypervisor/common/hypercall.c
hypervisor/common/vm_load.c
hypervisor/debug/dump.c
hypervisor/debug/logmsg.c
hypervisor/include/arch/x86/guest/guest.h
hypervisor/include/debug/logmsg.h
hypervisor/include/debug/sbuf.h
hypervisor/include/lib/bits.h
hypervisor/include/public/acrn_common.h

MISRAC has requirements about literal value requires a U suffix and
signed/unsigned conversion with cast. This patch is used to solve
these violations.
v1->v2
*Drop the cast of sz from uint32_t to int32_t, the signed/unsigned
violation of nchars will be solved by other patch together with
printf/sprintf/console/vuart/uart code.
*Delete the unnecessary L suffix of shifting operand.
Tracked-On: #861 

hv:treewide:fix multiple MISRAC violations

---

hypervisor/arch/x86/irq.c

This commit corrected the size of irq_alloc_bitmap[].

hv:irq: correct the size of irq_alloc_bitmap

---

hypervisor/arch/x86/guest/instr_emul.c

The vie->opcode should be updated when decode_two_byte_opcode(),
otherwise for two bytes opcode emulate(movzx/movsx) will fail.

HV: update opcode when decode_two_byte_opcode()

---

devicemodel/hw/pci/xhci.c
devicemodel/hw/platform/usb_pmapper.c
devicemodel/include/usb_pmapper.h
devicemodel/samples/apl-mrb/launch_uos.sh

This patch series is used to support 'flat mode' hub emulation and 'cold
plug' feature.
1. Flat mode hub emulation means DM only emulates USB devices under hub,
the Guest OS cannot see emulated hub. In the perspective of Guest OS,
all the emulated devices are under root hub.
2. Cold plug mode refers to USB devices are plugged in before Guest OS
is booted. In this case, the libusb will not report 'connect' event
to DM, and hence the Guest OS will have no opportunity to do enumeration
for those devices. The second patch is used to fix this issue.

Enable support for USB hub and 'cold plug' mode

---

doc/Makefile

Need to make sure the local projectacrn.github.io is in sync with the
master before starting up the publishing process.

doc: fix Makefile to address multiple publishers

---

hypervisor/lib/sprintf.c

In ACRN hypervisor, u/int64_t is defined as unsigned/ long.
It's nature to use %l to print it. But current printf use
%l to print int and only use %ll for long.
This patch fix it by treat long and long long same for printf.
Tracked-On: #1230

hv: long and long long is same for printf within x86_64

---

hypervisor/arch/x86/vtd.c

In current code of suspend_iommu/resume_iommu, there is potential buffer overflow
according to the code.
This patch put the buffer to struct dmar_drhd_rt, so that no need to access the buffer
via index.

hv: vtd: fix potential buffer overflow in suspend/resume

---

hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/lapic.c
hypervisor/include/arch/x86/apicreg.h

- remove 'PAD3' & 'PAD4'
- define local APIC registers by 'struct lapic_reg' type.

HV: refine 'struct lapic_regs' definition.

---

hypervisor/arch/x86/guest/guest.c
hypervisor/common/hypercall.c
hypervisor/include/arch/x86/guest/guest.h
hypervisor/include/common/hypercall.h

In the current hypervisor hypercall, first all vcpu is
allocated to SOS, vcpu's vm field is initialized to vm0.
When the vcpu is offlined, vcpu will be paused and vcpu's
vm field is set as NULL by DM. When UOS is created, vcpu's
vm field is set as UOS's vm. So when vmcall_vmexit_handler
is invoked, vcpu's vm filed is always non-NULL.
error checking for vm pointer is done in the function
"vmcall_vmexit_handler", vmcall_vmexit_handler will
guarantee that vm is vm0.
So all hypercall functions (these functions is just for handler
hypercall, except vmcall_vmexit_handler) don't need to check
whether invoking vm is NULL and don't need to check whether
invoking vm is vm0 or not.
Remove related invoking vm error checking for hypercall handling.
V1 --> V2:
Add pre-condition for hypercall in the …

HV:Hypercall:Remove redundant error checking

---

hypervisor/arch/x86/lapic.c
hypervisor/arch/x86/virq.c
hypervisor/arch/x86/vtd.c
hypervisor/debug/shell_priv.h
hypervisor/include/arch/x86/gdt.h
hypervisor/include/arch/x86/guest/vcpu.h
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/arch/x86/lapic.h
hypervisor/include/arch/x86/trusty.h
hypervisor/include/common/softirq.h
hypervisor/include/lib/types.h
hypervisor/include/public/acrn_hv_defs.h

MISRA-C states that redundant macros reduce the maintainability of code.
In some cases, we would like to keep the current unused macros for code
completeness, such as cpu registers. These macros might be used later.
This patch removes some unused macros that is not critical for code
completeness.
v1 -> v2:
* Keep TRUSTY_VERSION in trusty.c.
Yadong will cook another patch which will utilize TRUSTY_VERSION.

hv: remove unused MACROs

---

hypervisor/arch/x86/trusty.c

Replace if--else logic with switch--case when checking interface
version.
Tracked-On: #1265

HV: trusty: refine version checking when initializing trusty

---

hypervisor/arch/x86/guest/instr_emul.c
hypervisor/arch/x86/guest/instr_emul.h
hypervisor/arch/x86/irq.c
hypervisor/arch/x86/notify.c
hypervisor/common/hypercall.c
hypervisor/debug/npk_log.c
hypervisor/debug/shell.c
hypervisor/debug/uart16550.c
hypervisor/include/arch/x86/irq.h
hypervisor/include/debug/logmsg.h
hypervisor/include/lib/rtl.h
hypervisor/lib/string.c

MISRAC has requirement about implict conversion: actual to formal
param. This patch is used to fix part of these violations.
1.Add a new structure seg_desc_vmcs to hold the VMCS field address of
segment selector to clean up seg_desc structure.
2.Add the definition of maximum MSI entry and the relevant judgement.
3.The violations in shell.c, logmsg.c will be fixed in other series of
patches with modification of function snprintf(), vsnprintf() and other
related usages.
v1->v2:
*Move the definition of struct seg_desc_vmcs from instr_emul.h to
instr_emul.c.
*Modify the formal parameter type in function definition from uint8_t
to char instead of using cast.
*Drop the const declaration for char data in formal parameter.
v2->v3:
*update the data missing conversion.
*change type of internal …

hv:Fix Implict conversion:actual to formal param

---

hypervisor/arch/x86/Kconfig
hypervisor/boot/acpi.c
hypervisor/bsp/include/bsp_extern.h
hypervisor/bsp/sbl/platform_acpi_info.c
hypervisor/bsp/sbl/sbl.c
hypervisor/bsp/uefi/platform_acpi_info.c
hypervisor/bsp/uefi/uefi.c

The platform ACPI table might be changed before production, this brings
issue to us as current host_acpi_info data is hard-coded.
The patch set enable the feature that could parse the needed ACPI data
after boot and then override the host_acpi_info structure for system
usage.
change log:
v2 -> v1:
1) remove MACRO of CONST;
2) move parser code into acpi.c;
v3 -> v2:
1) remove memcpy to simplify parser logic;
2) remove strcmp to simplify signature verification;
3) move acpi_fix() caller to init_bsp();

HV: add ACPI fixup feature

---

hypervisor/bsp/sbl/sbl.c
hypervisor/bsp/uefi/uefi.c

These MACROs are never used by current code so remove it. The needed APIC
info is defined in other files with other MACROs.
We will unify kinds of APIC info definition in one place soon.
Tracked-On: #1274

HV: remove dead APIC info MACROs in bsp

---

hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/ioapic.c
hypervisor/dm/vpic.c
hypervisor/include/arch/x86/apicreg.h

- use sizeof(struct lapic_regs),instead of arbitrary size
to lear 'apic_page' memory region in vlapic.c
- fix potential buffer overflow issues in vpic.c & ioapic.c

HV:fix potential buffer overflow issues

---

devicemodel/samples/apl-mrb/launch_uos.sh

Change launch_uos.sh to enable USB xHCI full emulation support.

DM USB: xHCI: enable USB xHCI emulation in LaaG and AaaG.

---

devicemodel/hw/pci/core.c

This is temperory workaround for DM crash when doing fastboot
reboot. In fastboot, it will disable USB host functionality by
disable device respsone to one PCI bar. While DM code just release
the bar in this case. Which break the reboot functionality.
The workaround is to remove the assert to avoid DM abort. This is
safe because reboot will remove all memory range registered.
We will have offiical fixing later.
Tracked-On: #1277

dm: workaroud for DM crash when doing fastboot reboot

---

tools/Makefile

This patch is to exclude crashlog tool for release version.

tools: acrn-crashlog: exclude crashlog tool for release version

---

devicemodel/hw/pci/passthrough.c
devicemodel/hw/platform/acpi/acpi.c

CAVS audio driver depends on the NHLT table to get topology info.
Enable NHLT table in DM for audio passthrough.
Also increase the size reserved for NHLT in ACPI table from 2048B to 2560B.
Tracked-On: #1284

dm: passthru: enable NHLT table for audio passthru

---

doc/developer-guides/index.rst

We've got enough docs now that it would be better to put them in sorted
order by title.

doc: sort title in developer HLD section

---

doc/conf.py
doc/release_notes_0.2.rst

Update conf.py selector list to include version 0.2 documentation (and
fix an URL typo in the release notes).

doc: update doc version menu for v0.2 release

---

doc/static/acrn-custom.css

The .. code-block:: console directive (used for white text on a black
background) didn't handle some CSS cases properly resulting in
unreadable grey text on a black background.

doc: code-block text not readable

---

devicemodel/core/monitor.c
devicemodel/core/vmmapi.c
devicemodel/include/public/acrn_common.h
devicemodel/include/public/vhm_ioctl_defs.h
devicemodel/include/vmmapi.h
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/guest/vmcall.c
hypervisor/common/hypercall.c
hypervisor/common/ptdev.c
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/arch/x86/timer.h
hypervisor/include/common/hypercall.h
hypervisor/include/common/ptdev.h
hypervisor/include/public/acrn_common.h
hypervisor/include/public/acrn_hv_defs.h

This serial of patches are used to enhance the feature of "interrupt storm mitigation"; when interrupt storm happens on one UOS, SOS can delay the interrupt injection of UOS pass-through devices.
Tracked-On: #866

 interrupt storm detect(get data) & act as policy(delay intr) 

---

hypervisor/arch/x86/assign.c
hypervisor/arch/x86/ioapic.c
hypervisor/arch/x86/irq.c
hypervisor/include/arch/x86/ioapic.h

Convert GSI_MASK_IRQ and GSI_UNMASK_IRQ to inline functions.
v1 -> v2:
After changing GSI_MASK_IRQ and GSI_UNMASK_IRQ from MACROs to functions,
'gsi_(mask|unmask)_irq' are the exposed APIs and 'irq_gsi_mask_unmask'
becomes internal.
In order to reflect this change,
- change 'irq_gsi_mask_unmask' as internal function in ioapic.c
- declare 'gsi_(mask|unmask)_irq' in ioapic.h
- define 'gsi_(mask|unmask)_irq' in ioapic.c

hv: ioapic: convert some MACROs to inline functions

---

hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/mtrr.c
hypervisor/dm/vioapic.c
hypervisor/dm/vpic.c

MISRA-C requires that every switch case shall be terminated with break
to avoid the unintentional fall through.
The code will become redundant if we enforce this rule.
So, we will keep the current implementation for the following two cases.
1. The fall through is intentional.
2. The function is returned in the switch case.
If we decide to eliminate the mutiple returns in one function later,
this case would be handled properly at that time.
- add the mssing break for the default case
- add the pre condition for some functions and remove the corresponding
panic which will never happen since the function caller could guarantee
the pre condition based on the code implementation
v1 -> v2:
* remove the redundant cases above default in 'vlapic_get_lvtptr'
* add the similar …

hv: fix 'Switch case not terminated with break'

---

hypervisor/include/arch/x86/mmu.h

MISRA-C states that redundant code reduce the maintainability of code.
In some cases, we would like to keep the current unused static functions
for code completeness, such as checking register info. These functions
might be used later.
This patch removes the unused static function 'mmu_pt_for_pde'.
Looks like it is legacy code and not being used in our project.

hv: fix 'Static procedure is not explicitly called in code analysed'

---

tools/acrn-crashlog/Makefile
tools/acrn-crashlog/acrnprobe/Makefile
tools/acrn-crashlog/usercrash/crash_dump.c

These two patches are for updating makefile flags and fixing some compiler warning
-----------------------------------------------------------------------------------------
d624220
tools: acrn-crashlog: fix some compiler warnings  …
This patch is to fix some compiler warnings before enabling the flag to make
compiler warning as compiler error.
The warning message is like:
ignoring return value of ‘write’, declared with attribute warn_unused_result.
-----------------------------------------------------------------------------------------
8a090ef
tools: acrn-crashlog: update Makefile flags  …
This patch is to sync the compiler options as …

tools: acrn-crashlog: update Makefile flags and fix some compiler warning

---

tools/acrn-manager/acrnd.service

As a system service, acrnd will launch UOS, that must be done
after all required services and conditions are ready, such as
acrnprobe, weston, etc.
Tracked-On: #1278 

tools: acrnd: bugfix: service lack of prerequisition

---

tools/acrn-manager/Makefile
tools/acrn-manager/acrn_mngr.c
tools/acrn-manager/acrnd.c
tools/acrnlog/Makefile
tools/acrnlog/acrnlog.c
tools/acrntrace/Makefile
tools/acrntrace/acrntrace.c

Update the Makefile to sync the compiler options with devicemode and enable options to harden software.

Update Makefile and fix compiler warnings for acrnlog/acrntrace/acrn_manager

---

hypervisor/debug/dump.c

this patch change type of global variable for saving registers on execption.
global variable 'crash_ctx' should not be set to static.
crash_ctx is for offline analysis when system crashed, not for runtime usage.
as crash_ctx is only be set without being read, compiler will regard
crash_ctx as an useless variable if it is set to static, and will not
generate code for it.
Tracked-On: #1295
Signed-off-by: zhouji3x <jianfengx.zhou@intel.com>

hv: fix ramdump regression

---

hypervisor/arch/x86/assign.c
hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/cpuid.c
hypervisor/arch/x86/guest/pm.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/io.c
hypervisor/arch/x86/vmx.c
hypervisor/common/hypercall.c
hypervisor/common/schedule.c
hypervisor/debug/vuart.c
hypervisor/dm/vpci/vpci.c
hypervisor/dm/vpic.c
hypervisor/dm/vrtc.c
hypervisor/include/arch/x86/assign.h
hypervisor/include/arch/x86/cpu.h
hypervisor/include/arch/x86/guest/vlapic.h
hypervisor/include/arch/x86/ioreq.h

MISRA-C requires that there should be no unused parameters in
functions.
In some cases, we will keep the unused parameters.
vmexit handler is one example. It is used as function pointer.
Some of the vmexit handlers use the input parameter 'vcpu', some of
them don't. We still need to keep the unused parameters 'vcpu' for
those handlers don't use 'vcpu'.
This patch removes the unused parameters that is not being used
unconditionally.
v1 -> v2:
* remove the non-implemented API 'vlapic_id_write_handler'

hv: arch: fix 'Unused procedure parameter'

---

hypervisor/bsp/uefi/efi/Makefile
tools/acrn-crashlog/Makefile
tools/acrn-crashlog/acrnprobe/Makefile

To be able to support cross compilation, some fixes are needed as
follows:
- Replace all the host paths with a prefix sysroot, it defaults to be
empty.
- Use weak assignment to compiler variables, like CC, this allows them
to be overridden by environment variables passed to make.
Tracked-On: #1307
Signed-off-by: Ming Liu <liu.ming50@gmail.com>

Makefile: fix cross-compiling issues

---

hypervisor/arch/x86/guest/instr_emul.c
hypervisor/arch/x86/guest/ucode.c
hypervisor/arch/x86/mmu.c
hypervisor/arch/x86/trusty.c
hypervisor/arch/x86/vtd.c
hypervisor/common/hypercall.c
hypervisor/debug/shell.c
hypervisor/lib/sprintf.c

MISRAC checks whether a variable is assigned a value not used in
all branches of a program. Var value which is unused on all paths
can be removed with a consequent improvement in the readability
and efficiency of the code. This patch is used to fix these
violations.

hv:Fix unused var value on all paths

---

hypervisor/include/common/hypercall.h

Fix a Doxygen comment in the hypercall.h header file which is
missing the name of the parameter, this is causing warnings when
generating the documentation related to the
hcall_set_callback_vector() hypercall.
Tracked-On: #1335

Fix Doxygen comment in hypercall.h header file

---

doc/scripts/requirements.txt
doc/scripts/show-versions.py
doc/tutorials/docbuild.rst

Added a python script that displays versions of doc building tools
(e.g., doxygen, breathe, sphinx) to help verify doc building environment
is properly set up (can help doc building problem diagnostic, as shown
in issue #1333
Update doc build documentation to reference this script.

doc: add tool for verifying installed doc tools

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/io.c
hypervisor/debug/logmsg.c
hypervisor/dm/vioapic.c
hypervisor/include/arch/x86/guest/vioapic.h
hypervisor/include/arch/x86/ioreq.h
hypervisor/include/debug/logmsg.h
hypervisor/include/debug/trace.h

MISRA-C requires that there should be no unused parameters in
functions.
This patch removes the unused parameters that is not being used
unconditionally.

hv: include: fix 'Unused procedure parameter'

---

hypervisor/include/lib/atomic.h

This patch fixes the typo introduced in atomic operaions refine.
The usage of the parameter in function body was not updated according
to the changes of input parameter.

hv: bug fix in atomic.h

---

hypervisor/arch/x86/Kconfig
hypervisor/arch/x86/vtd.c

Currently, hypervisor doesn't have the information of pci devices
on the platform when init. In order to reduce boot time and memory
usage, hypervisor set a bus limitation for pci devices when init vtd.
However, maximum bus number varies on different platforms.
This patch add a config for the bus limitation.
Set 0xF as the default value for the maximum bus number on sbl platform.
Set 0xFF as the default value for the maximum bus number on uefi platfrom.
Tracked-On: #1339

hv: vtd: add config for bus limitation when init

---

hypervisor/arch/x86/cpu.c
hypervisor/common/hv_main.c

Now, the warning is promoted to error. The warning break ACRN
release build.
Tracked-On: #1343

hv: Fix the warning for ACRN release build

---

hypervisor/arch/x86/guest/instr_emul.c
hypervisor/include/lib/atomic.h
hypervisor/include/lib/bits.h

This patch fixes the following issue pointed by Xiangyang and Junjie.
There are some macro arguments acting as formal parameter names.
Drop such arguments since they make no difference to the expanded
implementation and they might confuse some developers.
Here is an example.
'ptr' is dropped in this patch, which is acting as a formal parameter
name and make no difference to the expanded implementation.
-#define build_atomic_load(name, size, type, ptr)       \
+#define build_atomic_load(name, size, type)            \
static inline type name(const volatile type *ptr)      \
{                                                       \
type ret;                                       \
asm volatile("mov" size " %1,%0"                \
: "=r" (ret)                    \
: "m" (*ptr) …

hv: drop the macro arguments acting as formal parameter names

---

hypervisor/arch/x86/guest/vmcall.c
hypervisor/common/hypercall.c
hypervisor/include/common/hypercall.h
hypervisor/include/common/irq.h
hypervisor/include/public/acrn_common.h
hypervisor/include/public/acrn_hv_defs.h

- wraps ASSERT/DEASSERT IRQ line hypercalls.
- remove 'intr_type' from set/clear IRQ line interface.
- deprecate "IRQ_ASSERT", "IRQ_DEASSERT" & "IRQ_PULSE".
- new adding hypercall will support "GSI_SET_HIGH"/
"GSI_SET_LOW"/ "GSI_RAISING_PULSE"/ "GSI_FALLING_PULSE"
operations

HV: Add hypercall to set/clear IRQ line

---

devicemodel/Makefile
devicemodel/hw/pci/virtio/vhost.c
devicemodel/hw/pci/virtio/virtio.c
devicemodel/hw/pci/virtio/virtio_block.c
devicemodel/hw/pci/virtio/virtio_console.c
devicemodel/hw/pci/virtio/virtio_heci.c
devicemodel/hw/pci/virtio/virtio_input.c
devicemodel/hw/pci/virtio/virtio_net.c
devicemodel/include/vhost.h
devicemodel/include/virtio.h

This patchset implements the vhost proxy in device model. vhost proxy
acts as a framework in device model. It provides a set of unified
interfaces which can be used by virtio backend drivers in device model
to add their vhost support:
vhost_dev_init
vhost_dev_deinit
vhost_dev_start
vhost_dev_stop
vhost proxy is implemented based on the virtio framework and vhost char
dev. virtio device related information such as negotiated features and
guest memory map are conveyed to vhost in kernel. virtqueue related
information such as queue size, vring addresses and eventfd pair are
conveyed to vhost kernel as well. They are all done by ioctls of vhost
chardev.
vhost kernel interfaces to vhm thru eventfd. There are 2 eventfds for one
virtqueue, one is for kick and the other is for notify. eventfd …

Vhost support

---

tools/acrn-manager/acrn_vm_ops.c

To fix the issue that vmmngr_head may be used uninitialized.
Tracked-On: #1157

tools: acrn-manager: init vmmngr_head with LIST_HEAD_INITIALIZER

---

doc/getting-started/apl-nuc.rst

Add a note (and instruction) on how to use a specific version of
Clear Linux on a system. Picking up the image of a specific release
is not sufficient as Clear Linux always grabs the very latest image
when installing.

Documentation: add instruction to use a specific version of Clear

---

hypervisor/arch/x86/assign.c
hypervisor/common/hypercall.c
hypervisor/debug/vuart.c
hypervisor/dm/vioapic.c
hypervisor/dm/vpic.c
hypervisor/include/arch/x86/guest/vioapic.h
hypervisor/include/arch/x86/guest/vpic.h

- replace vpic/vioapic_xassert_irq() APIs
with vpic/vioapic_set_irq()
- unify the description of IRQ/PIN state in vpic. & vioapic.c

HV: remove IRQSTATE_ASSERT/IRQSTATE_DEASSERT/IRQSTATE_PULSE

---

hypervisor/arch/x86/lapic.c

MISRA-C states that a void procedure used in expressions is dangerous.
This patch removes the improper 'return' when calling the void procedure
'send_dest_ipi'.

hv: fix 'Void procedure used in expression'

---

hypervisor/debug/printf.c
hypervisor/include/debug/logmsg.h
hypervisor/include/lib/sprintf.h
hypervisor/lib/sprintf.c

In hypervisor, all the parameter and return value printf related are
unsigned int, this patch is used to fix the function definitions.
v1->v2:
*Modify the return value of various functions, such as printf(),
vprintf(), charout(), do_printf(), charmem, print_pow2(),
print_decimal to void due to never used, no necessary to use,
or has already returned by param.
*Delete the impossible judgement of param->emit due to the type
is unsigned.

hv:Clear up printf related definition

---

hypervisor/debug/vuart.c
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/debug/vuart.h

Replace dynamic allocation for vuart rx/tx buffer
with static array.
v2-->v3:
--  Reduce the size of vuart tx buffer from 64K to 8K
--  For non-partition mode, will use global rx/tx buffer,
for partition mode, will use per VM rx/tx buffer.
--  Change several APIs to inline
v1-->v2:
--  Move vuart rx/tx buffer into acrn_vuart data structure
Reviewed-by: Anthony Xu <anthony.xu@intel.com>

hv:Replace dynamic memory allocation for vuart

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/irq.c
hypervisor/arch/x86/timer.c
hypervisor/include/arch/x86/timer.h

Current free_irq sequence will release vector first, then use the
released vector to free irq number.It will cause irq leak for MSI IRQ.
At present, there is no one to free the irqs which in irq_static_mappings,
So this patch will only make sure free non-gsi irqs.
Tracked-On: #1359

hv: fix irq leak for MSI IRQ 

---

hypervisor/arch/x86/assign.c
hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/ioapic.c
hypervisor/arch/x86/irq.c
hypervisor/boot/sbl/multiboot.c
hypervisor/common/hv_main.c
hypervisor/common/vm_load.c
hypervisor/debug/console.c
hypervisor/debug/uart16550.c
hypervisor/debug/uart16550.h
hypervisor/dm/vioapic.c
hypervisor/include/arch/x86/guest/vioapic.h
hypervisor/include/arch/x86/ioapic.h
hypervisor/include/arch/x86/irq.h
hypervisor/include/arch/x86/vmexit.h
hypervisor/include/common/ptdev.h
hypervisor/include/debug/console.h
hypervisor/lib/sprintf.c

The printf related functions have been called by other various
functions, e.g. get_ptdev_info(), get_ioapic_info, etc. The patch
is used to clear up the usage.

hv:clear up the usage of printf data struct

---

devicemodel/hw/pci/xhci.c
devicemodel/hw/platform/usb_pmapper.c

This patch series does two things
1. Change Enable Slot and Address Device emulation logic according xHCI spec.
2. Fix a corner case under Flat Mode Hub implementation.
Tracked-On: #1365 #1366 

fix several corner cases for USB emulation

---

hypervisor/include/common/hypercall.h

Doxygen API comment added to hypercall.h was incorrect causing the doc
build process to fail with a warning (parameter not documented).
Fixes: #1353
Tracked-On: #1353

doc: fix doxygen error in hypercall.h

---

hypervisor/arch/x86/irq.c
hypervisor/include/arch/x86/irq.h

The patch is replace irq_static_mappings type from 2 dimension array
into structure and one dimension array.
Tracked-On: #1375
Reviewed-by: Jason Chen <jason.cj.chen@intel.com>

hv: modify static irq mappings into array of structure

---

hypervisor/arch/x86/Kconfig

Commit 6085781 replaced __emalloc() with a call to uefi allocate_page()
and allows UEFI FW to allocate memory for hypervisor from high to low
address below 4GB. However, this change triggers an issue (might be
memory corruption), in turn, PXE boot cannot work.
Since root cause the issue might take some time, the PXE boot issue
blocks auto-test, we disable hypervisor relocation by default for the
time being in config option, and users can enable it by themselves. In
the following weeks, if we root cause the issue, we can re-enable
relocation feature.`
Tracked-On: #1371
Signed-off-by: Chaohong guo <chaohong.guo@intel.com>

EFI: Disable RELOC by default temporary

---

devicemodel/samples/apl-mrb/launch_uos.sh

on MRB, if memory >= 8GB, will allocate 6GB to UOS;
for MRB now just runs one UOS with more workload.
Tracked-On: #1369

DM: increase UOS memory size for MRB

---

devicemodel/hw/platform/rtc.c
devicemodel/include/macros.h
devicemodel/include/rtc.h
devicemodel/include/sw_load.h

Some firmware (e.g. UEFI) uses RTC CMOS to fetch the system's memory
configuration. Put lowmem / highmem info in the designated area.
This is a port of Bhyve vRTC's user-space logic.
v1 -> v2:
* move KB/MB/GB to macros.h
* move nvram offset definitions to rtc.h
Tracked-On: #1390

dm: vrtc: add memory configuration in RTC CMOS

---

devicemodel/core/inout.c
devicemodel/core/mem.c
devicemodel/hw/pci/core.c
devicemodel/include/inout.h
devicemodel/include/mem.h

This patchset revert the old temporary workaround and add fixing for the issue of
memory range disable/enable for PCI.
Tracked-On: #1277

Memory range disable push

---

hypervisor/include/arch/x86/vmx.h

MISRA-C required the suffix(U), such as:
(1U << 0) ---> (1U << 0U)
This patch will add the suffix(U) to come up MISRA-C.
Tracked-On: #1385

hv: add suffix(U) in vmx.h to come up MISRA-C

---

devicemodel/samples/apl-mrb/launch_uos.sh

Currently there're two issues which prevent UOS with 4.19-rc kernel from
booting:
1. GVT-g PVMMIO ppgtt update optimization causes GPU hang
2. audio driver causes kernel panic
This patch is a temporary workaround to prelimarily support 4.19-rc UOS.
And it will be reverted after above two issues are fixed.
Tracked-On: #1413

script: workarounds for UOS of 4.19-rc kernel

---

devicemodel/hw/pci/virtio/virtio_console.c
devicemodel/hw/pci/virtio/virtio_input.c

Use strnlen instead of strlen to avoid potential security issue.
Tracked-On: #1364

dm: virtio: use strnlen instead of strlen

---

devicemodel/hw/platform/ioc.c

Revise strtok and snprintf functions
v2: adjust the patch sequence.
Tracked-On: #1401 
Yuan Liu (2):
IOC Mediator: Add return value check for snprintf
IOC Mediator: Replace strtok with strsep
devicemodel/hw/platform/ioc.c | 64 +++++++++++++++++++++++++++++--------------
1 file changed, 44 insertions(+), 20 deletions(-)

IOC Mediator: Revise banned functions

---

hypervisor/arch/x86/guest/guest.c
hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/vmx.c
hypervisor/include/arch/x86/guest/vcpu.h

When setting some bits of vmx cr0/4, the guest would trap out. If these bits
want to enable/disable the paging or modify paging access right, we should
invalidate cached translation information. This serial is for this.
Tracked-On: #1379
v1->v2:
return bool for guest paging related APIs which added by this patch.

fix bug when set vmx_cr0/4

---

hypervisor/arch/x86/ept.c
hypervisor/arch/x86/pagetable.c
hypervisor/arch/x86/trusty.c
hypervisor/common/hypercall.c
hypervisor/dm/vpci/pci_pt.c
hypervisor/include/arch/x86/mmu.h

Page table operation would not fault except:
1. the hypervisor it out of memory to allcate a page for page table operation
2. there is a bug with page table operation in hypervisor or devicemodle
While we assue that these would not happened in our platform when release, so
there is no need to check whether there is a fault with page table operation. However,
for debug version, we would panic the hypervisor if we can't meet the conditions really.
Tracked-On: #1124

hv: mmu: make page table operation no fault

---

devicemodel/hw/pci/xhci.c

This is an issue result from incomplete process logic of commit:
"ba68bd4 DM USB: xHCI: fix enumeration error after rebooting".
This patch is used to fix it.
Tracked-On: #1425

DM USB: xHCI: fix a crash issue when usb device is disconnected

---

devicemodel/core/main.c

atkbdc_init will call pci_irq_reserve to reserve irq 1 & 12, which need
pci_irq_init be called first.
Tracked-On: #1402

dm: fix assertion in pci_irq_reserve

---

devicemodel/core/monitor.c

@set_wakeup_timer(), "ack" is not initialized before
passing it to "mngr_send_msg() as input.

dm: fix use of uninitialized variable in monitor.c

---

hypervisor/arch/x86/cpu.c

- improve the readability of ept_cap_detect
right shift 32 bits of msr_val to check bits 63:32 of msr_val

hv: improve the readability of ept_cap_detect

---

hypervisor/arch/x86/ept.c
hypervisor/arch/x86/guest/guest.c
hypervisor/arch/x86/mmu.c
hypervisor/arch/x86/pagetable.c
hypervisor/arch/x86/trusty.c
hypervisor/common/hypercall.c
hypervisor/include/arch/x86/mmu.h

In the current hypervisor design, when HPA is not
found for the specified gpa by calling gpa2hpa or
local_gpa2hpa, 0 will be returned as a error code,
but 0 may be a valid HPA for vm0; error checking
is missed when invoking gpa2hpa or local_gpa2hpa;
when invoking lookup_address, the caller guarantees
that parameter pointer pml4_page and pointer pg_size
is not NULL.
If local_gpa2hpa/gpa2hpa returns a invalid HPA,
it means that this function fails to find the
HPA of the specified gpa of vm. If local_gpa2hpa/gpa2hpa
return value is a valid HPA, it means that this
function have found the HPA of the specified gpa of vm.
Each valid vm's EPTP is initialized during vm creating,
vm's EPTP is valid until this vm is destroyed. So the caller
can guarantee parameter pointer pml4_page is not NULL.
The …

HV:MM:gpa2hpa related error checking fix

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/ept.c
hypervisor/arch/x86/guest/instr_emul.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/lapic.c
hypervisor/arch/x86/mtrr.c
hypervisor/arch/x86/notify.c
hypervisor/arch/x86/pagetable.c
hypervisor/arch/x86/pm.c
hypervisor/arch/x86/virq.c
hypervisor/arch/x86/vmexit.c
hypervisor/arch/x86/vmx.c
hypervisor/arch/x86/vtd.c
hypervisor/boot/reloc.c
hypervisor/common/hypercall.c
hypervisor/common/ptdev.c
hypervisor/common/softirq.c
hypervisor/debug/logmsg.c
hypervisor/debug/npk_log.c
hypervisor/debug/shell.c
hypervisor/dm/vioapic.c
hypervisor/include/lib/bits.h

- add missing brackets for 'if/else' statements based on MISRA-C
requirements
v1 -> v2:
* add brackets for each conditions in 'if' statements to improve
the readability
* modify 'ptdev_init' to make the logic clearer

hv: fix 'No brackets to then/else'

---

devicemodel/include/rpmb_sim.h
devicemodel/include/usb_core.h

An inline function defined in headers must be static
otherwise compilation may fail, depending on gcc optimization level,
particularly if dropping -O2 from the Makefile dm doesn't
compile reporting unresolved symbols.
Tracked-On: #1406

dm: inline functions defined in header must be static

---

devicemodel/core/mevent.c
devicemodel/include/mevent.h

dm: mevent: remove useless vmname global variable - trivial fix
dm: mevent: implement enable/disable functions - implement required API.
Added edge triggered read and write events.
For mei mediator we need to detect changes in
sysfs files, it's not possible to do it via
level based triggers as the files are always
readable.
Tracked-On: #1417
Change-Id: Ib360ad31f30afa576b2b7b833f9bb139c269a030
Signed-off-by: Aviad Nissel <aviad.nissel@intel.com>

dm mevent fixes and enhancements 

---

hypervisor/common/hypercall.c

'target_vm' returned from 'get_vm_from_vmid()' maybe NULL,
passing to 'is_vm0()' without check.

hv: fix NULL pointer dereference in "hcall_set_vm_memory_regions()"

---

devicemodel/samples/apl-mrb/launch_uos.sh
devicemodel/samples/nuc/launch_uos.sh

This reverts commit 072e77e746f39e3f9cfc50de19d9d77572f3a30c so that
plane_restriction can be enabled.
Tracked-on: https://github.com/projectacrn/acrn-hypervisor/issues/1373

Revert "DM: Disable plane_restriction on 4.19 kernel"

---

devicemodel/hw/pci/virtio/virtio.c

movb is used for registers STATUS and CFGGENERATION whose size is 1
byte. Previously hv cannot report the correct MMIO trap size for
movb and virtio hard coded their size to 4 as a workaround. hv fixed
movb instruction emulation and MMIO size can be reported correctly.
This patch removes those workaround.
commit 9df8790ffc50 ("hv: Fix two minor issues in instruction emulation code")
Tracked-On: #1449

dm: virtio: use the correct register size

---

hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/vmx.c
hypervisor/bsp/uefi/uefi.c
hypervisor/common/vm_load.c
hypervisor/include/arch/x86/guest/guest.h
hypervisor/include/arch/x86/guest/vcpu.h

This patchset is 2nd cycle refine to vcpu state initialization. It mainly focus
on the SOS BSP and all AP state initialization.
Tracked-On: #1231

2nd vcpu stat init refine

---

devicemodel/hw/pci/passthrough.c
hypervisor/arch/x86/virq.c

Two patches:
1, hv: virq: update apicv irr/rvi before handle vmcs event injection
2, dm: passthru: correct the name of xdci dsdt write function
Tracked-On: #1443
Signed-off-by: Yu Wang <yu1.wang@intel.com>
Acked-by: Eddie Dong <eddie.dong@intel.com

hv: virq: update apicv irr/rvi before handle vmcs event injection

---

devicemodel/core/main.c
devicemodel/core/sw_load_bzimage.c
devicemodel/core/sw_load_vsbl.c
devicemodel/core/vmmapi.c
devicemodel/include/public/acrn_common.h
devicemodel/include/public/vhm_ioctl_defs.h
devicemodel/include/vmmapi.h
hypervisor/arch/x86/guest/guest.c
hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/guest/vmcall.c
hypervisor/bsp/uefi/uefi.c
hypervisor/common/hypercall.c
hypervisor/common/vm_load.c
hypervisor/include/arch/x86/guest/guest.h
hypervisor/include/arch/x86/guest/vcpu.h
hypervisor/include/common/hypercall.h
hypervisor/include/public/acrn_common.h
hypervisor/include/public/acrn_hv_defs.h

This is third cycle vcpu init state refine patch. After this patchset, we don't need HV help to load UOS software any more.
Tracked-On: #1231

3nd vcpu state refine push

---

hypervisor/arch/x86/cpu.c
hypervisor/debug/shell.c
hypervisor/debug/shell_priv.h
hypervisor/include/arch/x86/cpu.h
hypervisor/include/arch/x86/per_cpu.h

Now we have name reuse definitions in hypervisor as following:
"enum cpu_state cpu_state" in per_cpu.h,
"struct shell_cmd *shell_cmd" in shell_priv.h.
MISRAC requires that tag names shall not be reused anywhere
with in a program.So these definitions violate MISRAC rules
"identifier resue".This patch is used to fix it.
1. modify the definitions to "enum pcpu_boot_state boot_state"
and "struct shell_cmd *cmds".
2. modifty the relevant usage.
v1->v2
update commit message to be more explicit.
v2->v3
update the enum definition.

hv: Fix identifier reuse

---

hypervisor/arch/x86/Kconfig
hypervisor/arch/x86/guest/guest.c
hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/io.c
hypervisor/arch/x86/virq.c
hypervisor/arch/x86/vmx.c
hypervisor/common/hypercall.c
hypervisor/common/io_request.c
hypervisor/dm/vpic.c
hypervisor/include/arch/x86/guest/guest.h
hypervisor/include/arch/x86/guest/vcpu.h
hypervisor/include/arch/x86/guest/vlapic.h
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/arch/x86/ioreq.h
hypervisor/include/arch/x86/irq.h

-- Replace dynamic memory allocation with static memory
-- Remove parameter check if vcpu is NULL

hv:Replace dynamic memory with static for vcpu

---

devicemodel/hw/pci/passthrough.c
devicemodel/hw/platform/acpi/acpi.c

NHLT table contains the settings some audio drivers need.
An ACPI method is used to get NHLT table address & length.
In current DM code, the NHLT talbe length in the ACPI method
is hardcoded, which will cause troubles when the length of the
table changed.
This patch replaces the hardcoded NHLT table length according to
the table length read from SOS.
Tracked-On: #1461

dm: passthru: fix hardcoded nhlt table length

---

hypervisor/dm/vpic.c
hypervisor/include/arch/x86/guest/vpic.h

use pin_state[pin] to record vpic pin signal, and change the interface name
accordingly.
Tracked-On: #1269

vpic: change assert/deassert method

---

hypervisor/arch/x86/virq.c

An issue reported on KBL NUC (No APIC-V), when runing GVT test
case, it is easily to cause SOS/UOS hung. This patch is to root
cause it and how to avoid it.
On some platforms with no APIC-V support, this modidication can
avoid SOS hung when no IRR but event pending bit set.
If no APIC-V, interrupt injection will use IRR in vLAPIC and
event pending bitmap; work logic as following (set ABC for notes):
1. in ISR or when UOS send an interrupt to SOS/VHM (like IO request),
step A: set IRR --> step B: set event pending bit;
2. in SOS event handing,  step C: check/clear event pending bit -->
step D: probe/get IRR --> step E: clear/handle IRR.
3. after that, it will probe IRR again to check if other IRR left:
step F: probe IRR --> step G: set event pending bit --> step H:
enable IRQ window in …

HV: allow no IRR when pending bit set if no APIC-V

---

hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/include/arch/x86/apicreg.h
hypervisor/include/arch/x86/cpu.h
hypervisor/include/arch/x86/irq.h
hypervisor/include/arch/x86/lapic.h
hypervisor/include/arch/x86/msr.h
hypervisor/include/arch/x86/mtrr.h
hypervisor/include/arch/x86/trusty.h
hypervisor/include/arch/x86/vtd.h
hypervisor/include/public/acrn_common.h
hypervisor/include/public/acrn_hv_defs.h

MISRA-C required the suffix(U/UL), such as:
(1) ---> (1U)
(1) ---> (1UL)
(1U << 0) ---> (1U << 0U)
This patch will add the suffix(U/UL) to come up MISRA-C into
hypervisor/include directory.
Tracked-On: #1468

hv: add suffix(U/UL) to come up MISRA-C into include

---

tools/acrn-manager/acrn_mngr.c
tools/acrn-manager/acrn_vm_ops.c

Fixed Acrnd crash caused by fd leaking and removed an unnecessary pre-assumption that fd num less than 1024.
Tracked-On: #1477
Signed-off-by: Tao, Yuhong <yuhong.tao@intel.com>

Fixed Acrnd crash caused by fd leaking

---

devicemodel/samples/apl-mrb/launch_uos.sh

This reverts partial of commit: 9bf5aafe "script: workarounds for UOS of
4.19-rc kernel", since our fixing patch for kernel crash when audio passthru
is ready.
Tracked-On:#1461

script: re-enable audio passthru

---

hypervisor/arch/x86/guest/ucode.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/irq.c
hypervisor/arch/x86/mtrr.c
hypervisor/arch/x86/vtd.c
hypervisor/common/hypercall.c

Return value should be checked,fix it by add
"void" when the function return value is not used.
V1->V2:
replace printf with pr_warn.
V2->V3:
change the commit to make read easily.
Tracked-On::#861

HV:fix 'missing for discarded return value' violations

---

hypervisor/arch/x86/virq.c

According to SDM 6.5 exception classification, if the fault
happens, the CPU will return to the faulting instruction. So
we shouldn't change rip to the next instruction if inject fault
to guest.
Tracked-on: #1473

hv: retain rip if the fault is injected to guest

---

devicemodel/Makefile
devicemodel/core/timer.c
devicemodel/hw/pci/wdt_i6300esb.c
devicemodel/hw/platform/rtc.c
devicemodel/include/timer.h

We will use timerfd and epoll mechanism to emulate kinds of timers like
PIT/RTC/WDT/PMTIMER/... in device model under Linux. The api is unified
in this patch.
Compare with sigevent mechanism, timerfd has a advantage that it could
avoid race condition on resource accessing in the async sigev thread.
This patch set replace timer api for RTC and WDT.
change log:
v1 -> v2: add NULL pointer check for function parameter;
v2 -> v3: rename file name of vtimer.* to timer.*;
rename structure name of vtimer to acrn_timer;
add read() in timer handler to consume I/O event;
v3 -> v4: replace bool clock_realtime with int clockid;
close acrn_timer->fd properly;

DM: add acrn_timer api for timer emulation

---

hypervisor/arch/x86/trusty.c
hypervisor/bsp/uefi/efi/multiboot.h
hypervisor/bsp/uefi/efi/pe.c
hypervisor/include/arch/x86/per_cpu.h
hypervisor/include/common/hypercall.h

Replace "//" with '/*','*/' couples.
Tracked-on:#861

fix "use of single line comments(s) //"

---

doc/tutorials/using_ubuntu_as_sos.rst

Minor update to the tutorial on how to use Ubuntu as the Service OS
with ACRN. Specifically, the instructions for making the Grub menu
visible at boot time now involved modify the /etc/default/grub file
and not the /boot/grub/grub.cfg as before.

Documentation: minor update to the tutorial about Ubuntu as SOS

---

doc/getting-started/apl-nuc.rst

There is a compilation error when using the stock gcc compiler
from Ubuntu 16.04. This adds a note to our Getting Started
Guide to indicate what the error is and how to work around it.
Tracked-On: #1482

Documentation: add note and instructions for Ubuntu 16.04

---

doc/tutorials/using_ubuntu_as_sos.rst

Fix one typo (in a command) in the tutorial entitled "Using
Ubuntu as the Service OS".
Add a note explaining that a script may have to be adjusted
based on the HW set-up (network interface name).
Tracked-On: #1502

Documentation: typo in Ubuntu tutorial and additional note

---

doc/developer-guides/contribute_guidelines.rst

For traceability, all changes must include a Tracked-On: line indicating
the issue driving this change.
Tracked-On: #1420

doc: Update contrib doc with Tracked-On

---

hypervisor/arch/x86/assign.c
hypervisor/debug/vuart.c
hypervisor/include/debug/vuart.h

vuart: change irq from 4 to 6
irq 4 is sharing with idma, after change vuart to level trigger, the idma
driver could handle this irq 4 and send out EOI, which cause the irq storm.
move vuart irq to a not used 6.
Tracked-On: https://github.com/projectacrn/acrn-hypervisor/issues/1476

vuart: change irq from 4 to 6

---

tools/acrn-manager/acrn_vm_ops.c
tools/acrn-manager/acrnd.c

When guest enter S5, its monitor socket will be closed. If we try to use it to
query the vm state, an error msg will be print out. Acctually, we should not take
it as an error.
So, this patch refine the log msg to show more details when guest trying to enter
S3/S5.
Tracked-On: #1506

tools: acrnd: Refine log msg to avoid confusing.

---

devicemodel/hw/pci/virtio/virtio_rpmb.c
devicemodel/include/rpmb.h

As RPMB mux kernel module is going to be created,
there are two corresponding changes required for DM:
1. The name has been changed to /dev/rpmbmux.
2. DM does NOT check MAC of RPMB result returned by kernel
module because DM doesn't own the real key.
Tracked-On: #1508
Signed-off-by: Huang, Yang <yang.huang@intel.com>

dm: rpmb: DM customized changes for RPMB mux kernel module

---

hypervisor/dm/vpic.c

Input 'pin' should be less than 'NR_VPIC_PINS_TOTAL'
Tracked-On: #1479

hv: fix potential buffer overflow in vpic_set_pinstate()

---

devicemodel/hw/pci/xhci.c
devicemodel/hw/platform/usb_pmapper.c
devicemodel/hw/usb_core.c
devicemodel/include/usb_core.h
devicemodel/include/usb_pmapper.h
devicemodel/include/xhci.h

This patch series enable support for multiple hubs and multiple layers
of hubs under Flat Mode, which means the physical hub is not visible to
UOS and all ports of the hub are mapped to the root hub ports of UOS.
Tracked-On: #1434
Signed-off-by: Liang Yang <liang3.yang@intel.com>

USB: Enable multiple hubs support (Flat Mode)

---

hypervisor/arch/x86/assign.c
hypervisor/arch/x86/guest/pm.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vm.c
hypervisor/common/hypercall.c
hypervisor/common/ptdev.c
hypervisor/dm/vioapic.c
hypervisor/include/arch/x86/assign.h
hypervisor/include/arch/x86/guest/guest_pm.h
hypervisor/include/arch/x86/guest/vioapic.h
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/common/hypercall.h
hypervisor/include/common/ptdev.h

Pointer param should be declared pointer to const if
the parameter is keeped read-only.
This patch changes pointer param whose name is vm.
Tracked-On:#861

HV:fixed "Pointer param should be declared pointer to const"

---

tools/acrn-crashlog/acrnprobe/sender.c

get_sender_from_name would return NULL if the name of sender is not
configured in acrnprobe.xml.
This patch check the return value of it.
Reviewed-by: Huang Yonghua <yonghua.huang@intel.com>

tools: acrn-crashlog: check the pointer after getting sender

---

hypervisor/arch/x86/ept.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/trusty.c
hypervisor/boot/sbl/sbl_seed_parse.c
hypervisor/common/vm_load.c
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/arch/x86/mmu.h
hypervisor/include/hypervisor.h

We want to remove the dynamic memory allocation in memory management. So we
must reserve a very big page pool for paging tables. Now we need these paging
tables to transfer gpa to hpa or hpa to gpa. For each direction walking, we need
to reserve about 20 MB for a VM which has 8 GB system memory plus 2 GB pci hole.
While there has very few changes to use hpa2gpa. Now there only has about four place
and only SOS will use it. However, the gpa to hpa is identical mapping in SOS.
The patch wants to add two pre-assumption for hpa2gpa: (a) it only used by SOS; (b) 
the gpa to hpa is identical mapping in SOS.
After this, we could not need to reserve the paging pool which paging tables are used to
walk hpa to gpa.
v1-v2:
add check hpa should not large than physical address length and add error …

add pre-assumption for hpa2gpa

---

hypervisor/arch/x86/timer.c

If a timer added more than once, assert the debug information.
Tracked-On: #1546

hv: timer: add debug information for add_timer

---

tools/acrn-manager/acrnctl.c

UOS requires an wakeup reason when resumed from S3 suspend. If user
use "acrnctl resume [VMNAME]" without an reason, 0x0 will be used
as default reason, and this is not work. We can use CBC_WK_RSN_BTN
instead.
Tracked-On: #1550
Signed-off-by: Tao, Yuhong <yuhong.tao@intel.com>

tools: acrnctl: fix: resume default wakeup reason is CBC_WK_RSN_BTN

---

hypervisor/include/debug/npk_log.h

The commit id "c5f4c5" translats from enum to macro, the content
is not correct,fixed now.
Tracked-On: #1553

HV:fix MACRO value mismatch

---

devicemodel/hw/pci/virtio/virtio_rpmb.c
devicemodel/hw/platform/rpmb/rpmb_backend.c

physical RPMB is accessed if "phisycal_rpmb" is specified
in launch.sh.
Also it reserves some RPMB area with a fixed size(32KB) for
AttKB and future usage, which is RO for UOS.
Tracked-On: #1544
Signed-off-by: Huang, Yang <yang.huang@intel.com>

dm: rpmb: Support RPMB mode config from launch.sh

---

devicemodel/hw/pci/virtio/virtio_net.c
devicemodel/include/dm_string.h
devicemodel/lib/dm_string.c

dm: add const declaration for dm_strto* APIs
dm: virtio-net: replace banned functions
Tracked-on: #1496
Reviewed-by: Conghui Chen <conghui.chen@intel.com>

dm: replace banned functions with their safe alternative

---

.checkpatch.conf
doc/developer-guides/contribute_guidelines.rst

ACRN hypervisor follows MISRA-C which has some inconsistencies with the Linux
kernel coding style. Namely,
* Braces are required even for single-statement blocks.
* Zero-initialisers to global variables are allowed.
* Line limit is 120 instead of 80.
This patch adds a .checkpatch.conf so that checkpatch.pl stops warning on the
exceptions above when invoked under the root directory of the acrn-hypervisor
repository.
The coding style documentation is updated accordingly.
Tracked-On: #1557

HV: checkpatch: add configurations to customize checkpatch.pl

---

tools/acrn-manager/acrnd.c
tools/acrn-manager/acrnd.service

When SOS shutdown/reboot, systemd will send SIGTERM to acrnd. We should catch up
this signal and stop all vms gracefully.
BTW, this path also fix the following error when stop acrnd service by removing
ExecStop config. Systemd will send SIGTERM signal to process by default.
systemd[9378]: acrnd.service: Failed to execute command: No such file or directory
systemd[9378]: acrnd.service: Failed at step EXEC spawning /usr/bin/killall: No such file or directory
-- Subject: Process /usr/bin/killall could not be executed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- The process /usr/bin/killall could not be executed and failed.
--
-- The error number returned by this process is 2.
Tracked-On: #1563
Signed-off-by: Kaige Fu …

tools: acrnd: Stop all vms when SOS shutdown/reboot

---

devicemodel/core/monitor.c
hypervisor/common/ptdev.c

It need correct two points:
1. DM can trigger a "fake" interrupt storm during warm reboot; compare the two unsigned 
number before minus to avoid overflow.
2. Correct HV interrupt delay timer handling; detailed in patch.

fix bug: multi-warm reboot UOS can cuase SOS/HV hung 

---

devicemodel/samples/apl-mrb/launch_uos.sh
devicemodel/samples/nuc/launch_uos.sh

if acrnd or acrn_guest service enabled, launch_uos.sh will be called
early time during system boot up, while a pci driver module may be
insmod and disable cpu hotplug in short time, which could make
cpu offline fail, we need check it to make sure cpu offline real happen
before hypercall to disable vcpu.
Tracked-On: https://github.com/projectacrn/acrn-hypervisor/issues/1584

launch_uos.sh: make sure cpu offline by retry

---

tools/acrn-crashlog/usercrash/client.c
tools/acrn-crashlog/usercrash/crash_dump.c
tools/acrn-crashlog/usercrash/debugger.c
tools/acrn-crashlog/usercrash/include/protocol.h
tools/acrn-crashlog/usercrash/protocol.c
tools/acrn-crashlog/usercrash/server.c

Since strlen/vsnprintf/ato* api are not safe, so use strnlen instead of
strlen, use vasprintf instead of vsnprintf and use strtol instead of
atoi.
Tracked-On: #1254
Reviewed-by: Huang Yonghua <yonghua.huang@intel.com>

tools: acrn-crashlog: remove unsafe apis in usercrash

---

hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/guest/vm.c
hypervisor/common/vm_load.c

After the vm loader reshuffle, the partition mode booting was broken because we only do guest sw loading for VM0. For partition mode, we need to do it for all VMs.
Tracked-On: #1565

Partition boot fix

---

devicemodel/core/main.c

That string was changed by accident and introduced the removed
items.
Tracked-On: #1465

DM: correct the predefine DM option string.

---

hypervisor/arch/x86/guest/vlapic.c
hypervisor/include/arch/x86/guest/vlapic.h

This api is not used, remove it.

hv:Remove deadcode 'vm_lapic_from_pcpuid'

---

devicemodel/core/sw_load_elf.c

The () was missed during the patch refine. This patch add it.
Tracked-On: #1465

DM: multiboot info address in DM for elf loader is wrong.

---

tools/acrn-crashlog/README.rst
tools/acrn-crashlog/usercrash/README.rst

This patch updates the documents according to the latest implementation
of crashlogctl.
Reviewed-by: Miguel Bernal Marin <miguel.bernal.marin@linux.intel.com>

tools: acrn-crashlog: update the documents

---

doc/scripts/filter-doc-log.sh

When the doc log is scanned for potential "new" errors, if any are found
it wasn't returning a non-zero error code.
Tracked-on: #1514

doc: filter error exit status incorrect

---

doc/developer-guides/hld/hld-emulated-devices.rst
doc/developer-guides/hld/hld-hypervisor.rst
doc/developer-guides/hld/hld-io-emulation.rst
doc/developer-guides/hld/index.rst

I/O emulation section was in a different place than in the HLD 0.7 doc
Tracked-on: #1592

doc: move docs to match HLD 0.7 org

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/vtd.c

When drdh_info_array[0].ignore = false with partition mode enabled,the following
assert error will be triggered when trying to boot vm:
Assertion failed in file arch/x86/vtd.c: fatal error
The root cause is that root_table_addr reading from CPU3(vm2's bsp) is NULL.
This patch move the init_iommu which initialize root_table_addr before starting
secondary cores and flush the cache at the end if the function to avoid getting
NULL pointer from secondary cores.
Tracked-On: #1160
Reviewed-by: Binin Wu <binbin.wu@intel.com>

HV: Fix boot failure of partition mode

---

hypervisor/debug/shell.c

If vUART is not configured in partition mode and we try to connect vm's console
through sos_console vmid, it will trigger crash of HV.
This patch check whether vUART is configured. If no, just print out "No vUART
configured for xxx" and return.
Tracked-On: #1160

HV: debug: Check if vUART is configured in partition mode

---

hypervisor/Makefile
hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/guest/vmcall.c
hypervisor/arch/x86/irq.c
hypervisor/arch/x86/virq.c
hypervisor/common/hv_main.c
hypervisor/debug/hypercall.c
hypervisor/debug/profiling.c
hypervisor/debug/sbuf.c
hypervisor/include/arch/x86/irq.h
hypervisor/include/arch/x86/msr.h
hypervisor/include/arch/x86/per_cpu.h
hypervisor/include/common/hypercall.h
hypervisor/include/common/irq.h
hypervisor/include/debug/profiling.h
hypervisor/include/debug/profiling_internal.h
hypervisor/include/debug/sbuf.h
hypervisor/include/hv_debug.h
hypervisor/include/public/acrn_hv_defs.h

Support for the tools[SEP/SOCWATCH] program the performance and power hardware registers to collect the analysis data.
Basic design consists of SEP/SoCWatch driver running inside the SoS sends all information required for configuration to the hypervisor via the hypercalls implemented in this patch set. In turn hypervisor uses the data sent from the driver to program PMU. The patch includes data collection of various counter during an interrupt, buffers the data and periodically sends the data to sampling driver.
Functionality provided by the hypervisor:
Fetch the VM information
Transfer PMU/Power programming information to hypervisor
Profiling collection control - start/stop
Provide physical cpuid information
Retrieve buffered PMU samples to SoS
Fetch VM switch trace information …

Add support for profiling [sep/socwatch tools]

---

hypervisor/arch/x86/notify.c

smp_call_function:
smp_call_mask can be modified by more than one process which can cause kernel hang and timeout
Adding a lock to smp_call_mask to prevent race condition
Tracked-On: #1606
Acked-by:   Xu, Anthony <anthony.xu.intel.com>
Signed-off-by: Manisha Chinthapally <manisha.chinthapally@intel.com>

Fix to kernel hang in smp_call_function

---

doc/tutorials/using_partition_mode_on_up2.rst

Tweak the 'Using partition mode on UP2' tutorial by removing
a couple of Grub menu entries that are not present by default
(nor introduced as part of the tutorial).
Also make it more obvious that there is still a default entry
called 'Ubuntu' which is the one by default.

Documentation: tweak 'partition mode' tutorial

---

devicemodel/hw/pci/virtio/virtio_console.c

Virtio-console device specific configuration is readonly, callback
for the cfgwrite is not required. This patch removed the unused
virtio_console_cfgwrite.
Tracked-On: #1364

dm: virtio-console: remove unused virtio_console_cfgwrite

---

devicemodel/core/vrpmb.c

The virtual rpmb key transfer path is ready now, so replace
previous temporary fixed key solution with random key
solution.
Tracked-On: #1636

DM: generate random virtual RPMB key

---

.checkpatch.conf

The checkpatch configuration set by commit 7b06be9 ("HV: checkpatch: add
configurations to customize checkpatch.pl") is unintendedly set to 20 (instead
of 120). This patch fix the setting to the expected value.
Tracked-On: #1557

checkpatch: fix the line limit back to 120

---

hypervisor/arch/x86/guest/vlapic.c

Functions shall not call themselves, either directly or indirectly.
V1->V2:
add pre-assumption.

fix "Recursion in procedure calls found"

---

hypervisor/arch/x86/guest/vmcall.c
hypervisor/common/hypercall.c
hypervisor/include/public/acrn_common.h
hypervisor/include/public/acrn_hv_defs.h

below hypercalls are wrapped to HC_SET_IRQLINE:
- HC_ASSERT_IRQLINE
- HC_DEASSERT_IRQLINE
- HC_PULSE_IRQLINE

hv: remove deprecated hypercalls

---

devicemodel/samples/apl-mrb/launch_uos.sh

on 8GB MRB: cat /proc/meminfo|head -n 1|awk '{print $2}'
it is: 7993388, it is not 8000000, so set it compare
with 7500000, then it can allocate 6GB to UOS.
Tracked-On: #1657

DM: correct memory allocation size for UOS

---

devicemodel/hw/platform/usb_pmapper.c

Accoring to xHCI spec, there are some TRBs with zero data length
which used to pass command to xHCI. In the DM, those TRBs should
not be sent to native device through libusb. The logic in the
current implentation fails to process some corner cases, this
patch is used to fix it.
Tracked-On: #1639

DM USB: xHCI: fix process logic of TRB which has zero data length

---

hypervisor/include/common/hypercall.h

Below functions are deprecated, remove them from hypercall.h
hc_assert_irqline()/hc_deassert_irqline()/hc_pulse_irqline()

hv: remove deprecated functions declartion

---

devicemodel/hw/pci/virtio/virtio_mei.c

The FW reset is currently detected from two points upon
a read failure from native read and from the reset
handler.
The fix removes the detection from the mevent rx callback,
leaving a single detection point.
To prevent reset hiccup, hw_ready is not set if a full rescan is
performed, it will be set only when virtio FW will request the FW reset.
Tracked-On: #1570
Signed-off-by: Alexander Usyskin <alexander.usyskin@intel.com>

Virtio mei reset Tracked-On: #1632

---

hypervisor/lib/sprintf.c

%x could be used to replace the %o print option.
%x could be used to replace the %p print option also.
Tracked-On: #1656

snprintf: Remove the %o and %p support

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/vtd.c
hypervisor/boot/dmar_parse.c
hypervisor/include/arch/x86/mmu.h
hypervisor/include/arch/x86/vtd.h

v6 since v5:
- remove dom_id field.
- remove dmar_hdrh_unit_count.
- export cpu_page structure and redefine
iommu_root_table&iommu_ctx_table
v5 since v4:
- remove the new api for retrieving dmar count.
- fix a potential bug in dmar looping.
- check init_iommu()
v4 since v3:
- remove domain id dynamic allocation.
- export a new api for retrieving the dmar number.
- fix a minor bug in v3 when memclr domain structure.
v3 since v2:
- move iommu number check into hardware_detect_support()
- more comments on domain index.
v2 since v1:
- use predefine macros in Kconfig instead of defining a new one.
- remove unnecessary bus_no and dmar_index check.
- add a new patch for stripping iommu_domain dynamic allocations.
Tw (3):
hv: vtd: remove dynamic page allocation for root&ctx table
hv: vtd: remove …

Remove vtd dynamic allocation

---

hypervisor/arch/x86/assign.c
hypervisor/arch/x86/guest/guest.c
hypervisor/arch/x86/guest/instr_emul.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/mmu.c
hypervisor/arch/x86/trusty.c
hypervisor/arch/x86/virq.c
hypervisor/arch/x86/vmx.c
hypervisor/arch/x86/vtd.c
hypervisor/dm/vpic.c
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/lib/rtl.h

The operands to shift operations (<<, >>) shall be unsigned integers.
v1 -> v2:
* replace 12U with CPU_PAGE_SHIFT when it is address shift case.
* replace 6UL with 0x6UL

hv: fix integer violations

---

hypervisor/arch/x86/vtd.c

For partition mode, there is no vm0_domain created for iommu.
In current code, it will return error when try to remove a device
from vm0_domain, which casue failure of device assignment in
partition mode.
Tracked-On: #1680

hv: vtd: fix device assign failure for partition mode

---

hypervisor/arch/x86/assign.c
hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/ioapic.c
hypervisor/arch/x86/irq.c
hypervisor/common/hv_main.c
hypervisor/debug/shell.c
hypervisor/dm/vioapic.c
hypervisor/include/arch/x86/guest/vcpu.h

on KBL-NUC when input "vmexit" in hypervisor console,
the console or HV/SOS could be hung, the root cause is:
the log buffer is overflow for 8 CPU cores info.
for the command just used in debug build, so to resolve
this bug in a simple way, just increase shell log buffer
size from 2 pages to 6 pages, it should be enough for more
CPU core info (like 12 cores or more).
Tracked-On: #1587

HV: increase shell log buf size for debug build

---

hypervisor/arch/x86/cpu.c
hypervisor/include/lib/atomic.h

It's possible that the up_count_spinlock is not release during
system enter S3. The case is like following:
BSP                                  AP
stop_cpus                            cpu_dead
cpu_set_current_state
spinlock_abtain
up_count--
wait_for up_count == 1
enter S3
spinlock_release
Especially, considering the real spinlock release could be delayed
by cache.
Actually, the most content protected by up_count_spinlock is per
cpu data and could be changed without lock. Only left is up_count.
This patchset remove the up_count_spinlock and use atomic API
for up_count changing.
Tracked-On: #1691

hv: Remove the up_count_spinlock and use atomic for up_count

---

doc/.known-issues/doc/dupdecl.conf

Sphinx/Breathe have a known problem with processing unnamed nested
structs and unions that cause a "Duplicate definition" warning.
Use our .known-issues filter to hide these in the HLD content.
Tracked-on: #1706

doc: hide doxygen duplicate definition warnings

---

hypervisor/Makefile
hypervisor/arch/x86/Kconfig
hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/ept.c
hypervisor/arch/x86/guest/guest.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/mmu.c
hypervisor/arch/x86/page.c
hypervisor/arch/x86/pagetable.c
hypervisor/arch/x86/trusty.c
hypervisor/arch/x86/vtd.c
hypervisor/boot/reloc.c
hypervisor/bsp/ld/link_ram.ld.in
hypervisor/bsp/uefi/efi/boot.c
hypervisor/bsp/uefi/efi/boot.h
hypervisor/common/hypercall.c
hypervisor/dm/vpci/pci_pt.c
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/arch/x86/hv_arch.h
hypervisor/include/arch/x86/mmu.h
hypervisor/include/arch/x86/page.h
hypervisor/include/arch/x86/pgtable.h
hypervisor/include/arch/x86/trusty.h
hypervisor/include/lib/mem_mgt.h
hypervisor/lib/memory.c

v6:
1. configure all the uos to have the same address space for the moment. Would configure
it according the real use of the UOS later.
2. some fix about the comments.
v5:
refine the implement.
v3-v4:
split this patch into two part: the first part is to add the static allocation API;
the second part is to replace the dynamic memory allocation in memory management with
the static allocation API.
Besides, remove the "node" concept, using vm_id to identify the page array for EPT.
As for HV PRIMARY, it use the fixed page array.
v2-v3:
1. make Kconfig name more clear
2. change related function protetype form (..., paging_table_falg, ...) to (..., paging_table_type, paging_table_node, ...)
paging_table_node here means from which paging_table_array whose node id euqal to paging_table_node to get …

hv: mmu: remove dynamic memory allocation in memory management

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/cpuid.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vlapic_priv.h
hypervisor/arch/x86/guest/vmsr.c
hypervisor/arch/x86/vmx.c
hypervisor/include/arch/x86/apicreg.h
hypervisor/include/arch/x86/guest/vlapic.h
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/arch/x86/msr.h
hypervisor/include/arch/x86/vmx.h
hypervisor/partition/vm_description.c

This patch series adds x2APIC support for ACRN guests. Also adds support for LAPIC pass-thru for guests running using partition mode of ACRN.
Tracked-On: #1626
Reviewed-by: Xu Anthony <anthony.xu@intel.com>

x2APIC support for ACRN guests

---

hypervisor/arch/x86/Kconfig
hypervisor/arch/x86/mmu.c

And fix a bug when the start address of the e820 not align to 2MB.

hv: mmu: add 16GB RAM support for uefi platform

---

doc/acrn.doxyfile
doc/developer-guides/hld/hv-vt-d.rst
hypervisor/include/arch/x86/vtd.h

This patch series adds the structure and API documentation to vdt.h in doxygen style and replace the hard-coded API docs with doxygen-generated ones.

Complement struct/API doc of VT-d for HLD

---

doc/getting-started/apl-nuc.rst
doc/tutorials/docbuild.rst

Getting Started Guide: add one more bundle to be added on a Clear
Linux development machine to make sure 'make' and other development
packages are available.
ACRN Documentation Generation: expand the 'PATH' variable to include
'~/.local/bin' where 'sphinx-build' is installed.
Tracked-On: #1650

Documentation: add 'make' to GSG and expand PATH for `sphinx-build`

---

doc/acrn.doxyfile

doc: add doyxgen alias for easy reST inclusion

---

doc/acrn.doxyfile
doc/developer-guides/hld/hv-io-emulation.rst
hypervisor/arch/x86/io.c
hypervisor/common/io_request.c
hypervisor/include/arch/x86/ioreq.h
hypervisor/include/public/acrn_common.h

This patch series adds the structure and API documentation to header and C
sources in doxygen style and replace the hard-coded API docs with
doxygen-generated ones.

Complement struct/API doc for HLD

---

hypervisor/dm/vpci/vpci.c

Currently vpci treats IO port CF9 as a regular PCI CONFIG_ADDRESS port,
so that SOS can't do system reboot through port CF9.
This patch handles port CF9 in this way:
- SOS (vm0): it is allowed to actually access the physical IO port for byte
accesses.
- UOS (non-vm0) or partitioning guests: any accesses to port CF9 are
ignored.
Tracked-On: #1568
Signed-off-by: Zide Chen zide.chen@intel.com

hv: vPCI needs to handle reset IO port CF9 differently

---

devicemodel/samples/apl-mrb/launch_uos.sh

The /dev/vbs_ipu is used as the backend driver of IPU mediator on SOS kernel.
If the file of /dev/vbs_ipu exists, it indicates that IPU works in mediator mode.
Other it will fall back to the pass-through mode.
Tracked-on: https://github.com/projectacrn/acrn-hypervisor/issues/1373

DM:Check the device file of /dev/vbs_ipu to determine IPU mode

---

hypervisor/common/hypercall.c
hypervisor/common/trusty_hypercall.c

For all the hypercalls, we sync the comments from .h to .c as
comments in .h file are used in architectural design and the
comments in .c are used in module design.

hypercall doc: Sync the comments for each hypercall from .h to .c

---

hypervisor/debug/printf.c
hypervisor/include/lib/sprintf.h
hypervisor/lib/sprintf.c

The print_param struct's member emit who is used for callback,
the forth parameter of it is used for transmit the private data
of the "print_param".
The type translation between "void *" and private date broke the
violations.
Use the same type to fix it out.
Acked-by: Xu Anthony <anthony.xu@intel.com>

fix "Casting operation to a pointer"

---

devicemodel/hw/platform/ioc_cbc.c

IOC mediator should keep sending acnrd boot reason until received
UOS heartbeat init message, then turn to send SOS wakeup reason
through read native cbc lifecycle cdev.
Tracked-On: #1727

IOC mediator: fix wakeup reason issue when UOS resuming

---

devicemodel/samples/apl-mrb/sos_bootargs_debug.txt
devicemodel/samples/apl-mrb/sos_bootargs_release.txt

Difficult to review the changes of sos_bootargs when the args is a single line.
Split sos boot args into multiple lines.
Tracked-On: #1730

DM: sos_bootargs: split sos_bootargs into multiple lines

---

hypervisor/arch/x86/vtd.c

domain count should be CONFIG_MAX_VM_NUM+1 instead of CONFIG_MAX_IOMMU_NUM+1

hv:vtd: fix minor bug in domain count

---

hypervisor/common/hypercall.c
hypervisor/include/common/hypercall.h

The old doc update commit changed the code by accident and broke
release version build. This patch fix the release build issue.

hv: fix release build issue

---

hypervisor/arch/x86/guest/vm.c

It is not necessary to use atomic operation to
set the initial value for 'created_vcpu' in vm structure.

hv:Remove atomic operation to set initial value for 'created_vcpu'

---

devicemodel/hw/pci/npk.c

Otherwise, after UOS crashes, the PTE for the MMIO may be added
again.
Tracked-On: #1745
Signed-off-by: Zhi Jin <zhi.jin@intel.com>

DM NPK: unmap the MMIO in pci_npk_deinit

---

hypervisor/arch/x86/assign.c
hypervisor/arch/x86/vtd.c
hypervisor/include/arch/x86/vtd.h
hypervisor/include/dm/pci.h

According to MISRA-C, function like should be replaced with inline function.
And use the predefined inline function for bdf calculation.
Tracked-on: #1747 

Replace function like macro with inline function

---

hypervisor/arch/x86/assign.c
hypervisor/arch/x86/guest/guest.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/mmu.c
hypervisor/boot/sbl/abl_seed_parse.c
hypervisor/boot/sbl/sbl_seed_parse.c
hypervisor/debug/profiling.c
hypervisor/dm/vpci/msi.c
hypervisor/dm/vpci/msix.c
hypervisor/dm/vpci/vpci.c
hypervisor/dm/vpic.c
hypervisor/include/common/ptdev.h
hypervisor/include/dm/vpci.h

MISRA-C requires that the controlling expression of an if statement or
an iteration-statement shall be Boolean type.
v1 -> v2:
* update the U suffix of constant to let the type of operands
to bit operations (&) is the same.
* update the type of 'i' from uint64_t to uint16_t in
'profiling_set_control' since it is limited by phys_cpu_num,
which is uint16_t.

hv: fix 'Expression is not Boolean'

---

hypervisor/arch/x86/guest/vmcall.c
hypervisor/common/hypercall.c
hypervisor/include/common/hypercall.h
hypervisor/include/public/acrn_hv_defs.h

Since it's discarded.
Tracked-On: #1124

hv: hypercall: remove hcall_set_vm_memory_region

---

hypervisor/common/hypercall.c
hypervisor/include/common/hypercall.h

The the bdf(bus/dev/func) is used to determine which pass-through device should
be assigned/released. Now the hypervisor parses the corresponding bdf from the guest
physical address when hcall_assign_ptdev/hcall_deassign_ptdev is called.
As it is only uint16_t, it is unnecessary to use the GPA to pass the bdf parameter.
Instead the parameter can be used as the bdf directly.
In order to keep the compatibility, it still can get the bdf by using
copy_from_gpa when SOS passes the parameter based on the buffer. But this will
be depreciated.
This is based on the assumption that the GPA in SOS is greater than 0x10000
when one buffer is allocated to pass the corresponding hypercall parameter.
After the SOS uses the bdf to pass the hypercall paremeter, we can remove the code
that gets the bdf by …

HV: Use parameter directly to pass bdf for hcall_assign/deassign_ptdev

---

devicemodel/core/main.c
devicemodel/core/monitor.c
devicemodel/include/monitor.h
devicemodel/samples/apl-mrb/launch_uos.sh

expose the params setting in DM; so it is easy for user to adjust the params in launch-uos script.
Tracked-On: #1724

 improvement for “interrupt storm mitigation”: expose the params setting in DM

---

hypervisor/arch/x86/ept.c

Current, SNP control bit is only set in ept_mr_add for cacheable memory.
However, memory type for VM0 is added as uncacheable type.
So SNP control is not set for VM0.
Add code to set SNP control bit for cacheable memory when ept modification.
Tracked-On: #1762

hv: ept: set snp control when modify

---

doc/developer-guides/hld/hv-io-emulation.rst
hypervisor/arch/x86/guest/pm.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/io.c
hypervisor/debug/vuart.c
hypervisor/dm/vpci/vpci.c
hypervisor/dm/vpic.c
hypervisor/dm/vrtc.c
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/arch/x86/io.h
hypervisor/include/arch/x86/ioreq.h

-- Add emulated port IO index
-- Add emulated port IO array in vm structure
-- Remove port list in vm structure
-- Remove free_io_emulation_resource/register_io_handler/
create_io_handler APIs
v2-->v3:
-- not add 'is_emulated', check len == 0U
-- Check if io_read/io_write handler is NULL before calling
-- Replace ENUM with MACRO for emulated pio index to avoid
MISRA-C violations
v1-->v2:
-- Remove EMUL_PIO_NUM in Kconfig, add emulated pio index
for PIC/PCI/UART/RTC/PM

hv:Replace dynamic memory with static for port IO

---

hypervisor/arch/x86/cpu_state_tbl.c

The cpu model name of "Intel(R) Celeron(R) CPU N3350 @ 1.10GHz" is used in
APL UP2 board, which is in Acrn official support list.
Tracked-On: #1767

HV: add px cx data of bxt n3350 SOC

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/trampoline.S

Branch addressing using registers or memory operands must be prefixed by
a '*' in AT&T ASM language.
This change is to fix these warnings:
arch/x86/cpu.c:409: Warning: indirect call without `*'
arch/x86/cpu.c:553: Warning: indirect call without `*'
arch/x86/trampoline.S:168: Warning: indirect jmp without `*'
Ref: https://csiflabs.cs.ucdavis.edu/~ssdavis/50/att-syntax.htm
Tracked-On: #1764
Reviewed-By: Yin Fengwei <fengwei.yin@intel.com>

hv: fix branch addressing syntax warning

---

doc/getting-started/apl-nuc.rst

updates:  
1, update Clear Linux version to 26120 support v0.3 release
2,  update product kernel to kernel-iot-lts2018 since there is new named bundle 

Doc: update getting started guide to support V0.3 release

---

hypervisor/bsp/uefi/clearlinux/acrn.conf

updated kernel name  from kernel-org.clearlinux.pk414-sos.4.14.52-63 to kernel-org.clearlinux.iot-lts2018-sos.4.19.0-16 for v0.3 release

HV: update kernel name to kernel-org.clearlinux.iot-lts2018-sos.4.19.0-16

---

devicemodel/samples/nuc/launch_uos.sh

1, update Clear Linux version to 26120 
2, update kernel name to *iot-lts2018* 

DM: update clear Linux version to 26120 in guest os launch script 

---

doc/Makefile

Sphinx supports making a single (large) html file instead of a
full website with a collection of html pages.  This ``make singlehtml``
option provides the basis for creating a Word document (for example)
via a cut-and-paste of a section of the documentation (not easily
possible when the docs are in multiple HTML files.)

doc: add Makefile option for singlehtml

---

doc/developer-guides/contribute_guidelines.rst

Update the capitalization of "Tracked-On" in the documentation.
"Tracked-on" should work but it throws a warning so it's better
to make the documentation focus on using "Tracked-On" only.

Documentation: adjust "Tracked-On" capitalization in documentation

---

hypervisor/dm/vpci/vpci.c
hypervisor/dm/vpic.c

Assign function pointer without the unary & operator.
Take 'register_io_emulation_handler' as an example:
void register_io_emulation_handler(struct acrn_vm *vm,
const struct vm_io_range *range,
io_read_fn_t io_read_fn_ptr,
io_write_fn_t io_write_fn_ptr)
The last two parameters are function pointer.
Sometimes we use function designator directly, while sometimes
with the unary & operator, as shown below.
- without &
register_io_emulation_handler(vm, &range, vuart_read, vuart_write);
- with &
register_io_emulation_handler(vm, &pci_cfg_range,
&pci_cfg_io_read, &pci_cfg_io_write);
To unify the coding style, we will go with the first way.

hv: unify the function pointer assignment

---

hypervisor/arch/x86/guest/vmcall.c

this patch is to avoid posisble inconsisent states for
VMs and vCPUs in configuration that  SOS is SMP based
and Device Model may be multi-threads based.

hv:add global lock for VM & vCPU management hypercalls

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/gdt.c
hypervisor/arch/x86/timer.c
hypervisor/arch/x86/trusty.c
hypervisor/arch/x86/vmx.c
hypervisor/arch/x86/vtd.c
hypervisor/debug/dump.c
hypervisor/include/arch/x86/cpu.h
hypervisor/include/arch/x86/vmx.h

Misra C reqires assembly code should comply with
the rules list below:
The assembly code's functionality should match the function's
name.If not,pls encapsulate the assembly code and give a suitable
name for describing the functionality.
V1->V2:
1.remove the dead code
2.update detail comment

fix "Procedure is not pure assembler"

---

hypervisor/arch/x86/guest/vcpu.c

to decrease the value of 'create_vcpus' in fail case.

hv: fix possible inconsistent issue for 'vm->hw.create_vcpus'

---

hypervisor/arch/x86/Kconfig
hypervisor/arch/x86/vtd.c

In current code, there is an out of range access to the array buses defined in struct struct context_table.
This patch defines CONFIG_IOMMU_BUS_NUM to replace CONFIG_IOMMU_INIT_BUS_LIMIT, which is clearer.
CONFIG_IOMMU_BUS_NUM equals to (CONFIG_IOMMU_INIT_BUS_LIMIT + 1).
Tracked-On: #1807

hv: vtd: fix the pre-allocated context table number

---

hypervisor/dm/vpic.c

Functions shall not call themselves, either directly or indirectly.

HV:fix "Recursion in procedure calls found"

---

hypervisor/dm/hw/pci.c
hypervisor/dm/vpci/core.c
hypervisor/dm/vpci/hostbridge.c
hypervisor/dm/vpci/msi.c
hypervisor/dm/vpci/msix.c
hypervisor/dm/vpci/partition_mode.c
hypervisor/dm/vpci/pci_pt.c
hypervisor/dm/vpci/vpci.c

This patch series fixes all MISRA-C violations in dm/vpci except for two
instances found from runtest-tailored.sh. 
msi.c: 227   Function pointer is of wrong type. : No. of formal parameters differ;
pci_ops_vdev_msi.deinit: 1, vmsi_cfgwrite: 4
MISRA-C:1998 105
msi.c: 228  Function pointer is of wrong type. : Types of parameter 4 differ;
pci_ops_vdev_msi.cfgwrite: unsigned int, vmsi_cfgread: unsigned int
MISRA-C:1998 105
The code in question is in dm/vpci.msi.c:
struct pci_vdev_ops pci_ops_vdev_msi = {
.deinit = vmsi_deinit,
.cfgwrite = vmsi_cfgwrite,
.cfgread = vmsi_cfgread,
};
I can 'fix' this violation with the following code, which doesn't make sense
to me. So I leave these violations open for now.
+ static int vmsi_init(struct pci_vdev *vdev)
+ {
+    return 0;
+ }
struct pci_vdev_ops …

hv: fix MISRA-C violations in dm/vpci

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/guest/instr_emul.c
hypervisor/arch/x86/io.c
hypervisor/arch/x86/pm.c
hypervisor/dm/vioapic.c
hypervisor/dm/vpic.c
hypervisor/include/arch/x86/host_pm.h

MISRA-C requires that the function call in which the returned
value is discarded shall be clearly indicated using (void).
This patch fixes the violations related to the following
function calls.
- instr_check_gva
- vlapic_set_local_intr
- prepare_vm
- enter_s3
- emulate_instruction
- ptdev_intx_pin_remap
- register_mmio_emulation_handler
v1 -> v2:
* discard the return value of enter_s3

hv: fix '(void) missing for discarded return value'

---

tools/acrn-crashlog/common/fsutils.c

this patch fix potential issue of initialization
about local variable in fsutils.c
Signed-off-by: Zhonghua <zhonghua.sun@intel.com>

tools:acrn-crashlog:fix potential issue

---

hypervisor/arch/x86/guest/vm.c

Even in partition mode, we also need to clear vmid in vmid_bitmap to
indicate the VM is not present.
Tracked-On: projectacrn#1821

hv: partition mode also needs free vm id when shutdown vm

---

hypervisor/arch/x86/guest/vm.c
hypervisor/common/io_request.c
hypervisor/include/arch/x86/ioreq.h

ioreqs acrossing VM reset is meaningless. So we reset their status when
VM reset.
Please note, device model and service os need to handle various ioreqs
pending status in emergency reset condition carefully. Otherwises, the
post processing of such ioreqs might overwrite this reset.
Tracked-On: projectacrn#1821

hv: reset VM ioreqs in reset_vm

---

hypervisor/common/hv_main.c
hypervisor/debug/shell.c
hypervisor/debug/shell_priv.h
hypervisor/include/arch/x86/per_cpu.h

- Remove the usage of HV_DEBUG in hv_main.c
The usage of HV_DEBUG in hv_main.c is for the shell command 'vmexit'.
Since vmexit info has been captured by acrntrace, there is no need to
keep this duplicated feature in shell command.

hv: hv_main: clean up HV_DEBUG usage

---

hypervisor/arch/x86/vmx.c
hypervisor/include/arch/x86/cpu.h

1. CPU_SEG_WRITE->CPU_SEG_READ: it's actually seg read
2. 0x%hu -> 0x%x: it need print hex format
Tracked-On: #1833

vmx: tiny fix for MACRO name and print format
