projectacrn/acrn-hypervisor

doc/getting-started/Dockerfile

'rsync' is missing from the ACRN Builder Container (in 'doc/getting-started/Dockerfile').
Add it and also add the 'devpkg-graphviz' bundle specifically although it is
automatically included via the 'desktop-apps' (it does not use any additional
space and makes clearer that it is needed).

doc: add 'rsync' to the ACRN builder container

---

devicemodel/hw/platform/tpm/tpm_crb.c

In function crb_reg_write() in tpm_rbc.c
'tpm_vdev->request_mutex' will potentially kept
in locked state after crb_reg_write() returns.
Tracked-On: #3825
Reviewed-by: Yadong Qi <yadong.qi@intel.com>

dm: fix mutex lock issue in tpm_rbc.c

---

misc/acrn-manager/acrn_vm_ops.c
misc/acrn-manager/acrnd.c

The return value of 'strtol()' is not checked properly
in _get_vmname_pid() @acrn_vm_ops.c and parse_opt()@acnrd.c,
the return type of 'strtol' is 'long int', but it is assigned
to a variable with type of 'int' and compared to "LONG_MAX"
and "LONG_MIN", which is always false.
This patch is to fix above error case.
Tracked-On: #3859

vm-manager: fix improper return value check for "strtol()"

---

misc/acrn-config/board_config/pci_devices_h.py
misc/acrn-config/board_config/ve820_c.py
misc/acrn-config/launch_config/com.py
misc/acrn-config/library/board_cfg_lib.py
misc/acrn-config/library/common.py
misc/acrn-config/library/launch_cfg_lib.py

1. acrn-config: define vm name for Preempt-RT Linux in launch script
2. acrn-config: refine board name with undline_name api
3. acrn-config: acrn-config: add white list to skip item check
Tracked-On: #3852

acrn-config: define vm name while generating launch script for preempt RT

---

misc/acrn-config/xmls/config-xmls/apl-mrb/sdc_launch_1uos_aaag.xml
misc/acrn-config/xmls/config-xmls/apl-mrb/sdc_launch_1uos_aliaag.xml
misc/acrn-config/xmls/config-xmls/apl-up2-n3350/sdc_launch_1uos_laag.xml
misc/acrn-config/xmls/config-xmls/apl-up2/sdc_launch_1uos_laag.xml

1. acrn-config: modify ipu/ipu_i2c device launch config of apl-up2
2. acrn-config: correct launch config info for audio/wifi defice of apl-mrb
Tracked-On: #3863

acrn-config: correct ipu/ipu_i2c/audio/wifi default config from xml

---

hypervisor/Makefile
hypervisor/arch/x86/Kconfig
hypervisor/arch/x86/guest/hyperv.c
hypervisor/arch/x86/guest/vcpuid.c
hypervisor/arch/x86/guest/vmsr.c
hypervisor/include/arch/x86/guest/hyperv.h
hypervisor/include/arch/x86/guest/vm.h

These patches implement the minimum set of TLFS functionality together with the reference time enlightenment.
The minimum set of TLFS functionality includes 6 vCPUID leaves and
3 vMSRs:
- 0x40000001 Hypervisor Vendor-Neutral Interface Identification
- 0x40000002 Hypervisor System Identity
- 0x40000003 Hypervisor Feature Identification
- 0x40000004 Implementation Recommendations
- 0x40000005 Hypervisor Implementation Limits
- 0x40000006 Implementation Hardware Features
- HV_X64_MSR_GUEST_OS_ID Reporting the guest OS identity
- HV_X64_MSR_HYPERCALL Establishing the hypercall interface
- HV_X64_MSR_VP_INDEX Retrieve the vCPU ID from hypervisor
The reference time enlightenment includes 2 vMSRs:
- HV_X64_MSR_TIME_REF_COUNT is read only and it is used to return the
partition's reference counter …

Tlfs tsc ref time

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/guest/trusty.c
hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/guest/virq.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/guest/vm_reset.c
hypervisor/arch/x86/guest/vmcs.c
hypervisor/arch/x86/guest/vmexit.c
hypervisor/arch/x86/guest/vmsr.c
hypervisor/arch/x86/init.c
hypervisor/boot/guest/deprivilege_boot.c
hypervisor/boot/guest/vboot_info.c
hypervisor/common/hv_main.c
hypervisor/common/hypercall.c
hypervisor/common/schedule.c
hypervisor/debug/dump.c
hypervisor/debug/profiling.c
hypervisor/debug/shell.c
hypervisor/dm/io_req.c
hypervisor/include/arch/x86/guest/vcpu.h
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/arch/x86/guest/vmcs.h
hypervisor/include/arch/x86/per_cpu.h
hypervisor/include/common/schedule.h

hv: sched: move pcpu_id from acrn_vcpu to thread_object
hv: sched: use get_running_vcpu to replace per_cpu vcpu with cpu
sharing
hv: sched: support vcpu context switch on one pcpu
hv: sched: move schedule initialization to each pcpu init
hv: sched: add status for thread_object
hv: sched: add sleep/wake for thread object

Schedule noop preparation 

---

hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/page.c
hypervisor/include/arch/x86/page.h

Currently the parameter of init_ept_mem_ops is
'struct acrn_vm *vm' for this api,change it to
'struct memory_ops *mem_ops' and 'vm_id' to avoid
the reversed dependency, page.c is hardware layer and vm structure
is its upper-layer stuff.

hv:Change the function parameter for init_ept_mem_ops

---

misc/acrn-config/launch_config/com.py

Add the '--windows' option to launch WaaG vm.
Tracked-On: #3880

acrn-config: add '--windows' option for WaaG vm

---

misc/acrn-config/launch_config/com.py

Refine the vbootloader type of vm,
The vbootloader type should be select from vsbl/ovmf/none in webUI item.
Tracked-On: #3879

acrn-config: refine the vbootloader of vm

---

hypervisor/dm/vpci/vmsi.c

'info.pmsi_addr' may be written to physicall device's
PCI configuration field without initialization when
'enable' is false in 'vmsi_remap()'.
this patch is to fix above issues, 'PCIR_MSI_ADDR'
and 'PCIR_MSI_ADDR_HIGH' only be programmed when
'enable' is true.
Tracked-On: #3903

hv:fix reference to uninitialized variable in vmsi_remap()

---

misc/Makefile
misc/life_mngr/COPYING.MinGW-w64-runtime.txt
misc/life_mngr/Makefile
misc/life_mngr/life_mngr_win.c

For cross-VM S5 notify via vUART, life_mngr service is running on UOS.
It is listening on COM2 to get SOS's commands.
The protocol is: SOS send "shutdown", UOS feedback "acked".
When SOS triggle shutdown, SOS can 1) check VM's status until UOS
stopped, 2) retry shutdown UOS normally with timeout.
So, no matter life_mngr server is running, SOS's shutdown procedure will
properly finish.
Tracked-On: #3564

Misc: lifemngr-daemon-on-UOS for windows

---

hypervisor/arch/x86/guest/vm.c
hypervisor/dm/io_req.c
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/dm/io_req.h

- The default behaviors of PIO & MMIO handlers are same
for all VMs, no need to expose dedicated APIs to register
default hanlders for SOS and prelaunched VM.
Tracked-On: #3904

hv[v2]: remove registration of default port IO and MMIO  handlers

---

Makefile

Usually We use '==' or '=' to compare strings under sh environment,
but '==' is not supported by dash which is the default sh environment
on Ubuntu, this leads efi build failure with current makefile.
Change the '==' to '=' to support both bash and dash.

makefile: add dash support to build efi

---

misc/acrn-config/config_app/templates/launch.html
misc/acrn-config/library/launch_cfg_lib.py
misc/acrn-config/library/scenario_cfg_lib.py

1.    acrn-config: filter out the proper wifi/ethernet device
Filter out the wifi/ethernet device from webUI with below PCI device class coding rule:
ethernet: 0200/0280;
wifi: 0280/0d20/0d21/0d80;
Tracked-On: #3917
2. acrn-config: fix the issue no error message in launch setting
3. acrn-config: fix the wrong 'key' type returned to webUI
Tracked-On: #3913

acrn-config: Fix web ui and filter out eth/wifi device to webUI

---

misc/acrn-config/library/scenario_cfg_lib.py
misc/acrn-config/target/misc.py
misc/acrn-config/xmls/board-xmls/apl-mrb.xml
misc/acrn-config/xmls/board-xmls/apl-up2-n3350.xml
misc/acrn-config/xmls/board-xmls/apl-up2.xml
misc/acrn-config/xmls/board-xmls/nuc6cayh.xml
misc/acrn-config/xmls/board-xmls/nuc7i7dnb.xml

The previous method to handle ttyS info has an assumption that PCI
serial devices are all mmio type, this caused incorrect BDF info in
board XML file.
This patch fix this issue by dropping serial device BDF info and
replace it with IO type.
Tracked-On: #3900

acrn-config: refine ttyS info of board file

---

hypervisor/Makefile
hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/guest/virq.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vm.c
hypervisor/common/sched_noop.c
hypervisor/common/schedule.c
hypervisor/include/arch/x86/guest/vcpu.h
hypervisor/include/arch/x86/per_cpu.h
hypervisor/include/common/schedule.h

This patchset refines schedule module of ACRN for modularization and extendibility.
It mainly does
1) polish vcpu and schedule modulization
2) abstract scheduler object for schedule module to enhance scalability
3) keep current schedule policy in a 'noop' scheduler
We also add status for thread_object. There are three valid status for thread_object now: THREAD_STS_RUNNING, THREAD_STS_RUNNABLE, THREAD_STS_BLOCKED.
In general, thread_obj starts from THREAD_STS_BLOCKED, then be changed to THREAD_STS_RUNNABLE after wake up and be changed to THREAD_STS_RUNNING by being scheduled in. THREAD_STS_RUNNING -> THREAD_STS_RUNNABLE happens in schedule out.
thread_obj will be changed to THREAD_STS_BLOCKED while doing sleep operation.
For scheduler object, we define a struct named acrn_scheduler:
struct …

Abstract scheduler from sched module and polish sched framework

---

devicemodel/hw/platform/acpi/acpi.c

The device model generating ACPI table use the old ASL
standard(version:20190816), then the iasl in clearlinux(version:31360)
is 20191018, it can't disassemble the ACPI table compiled by old
standard.
Tracked-On: #3933

dm: update ACPI with latest ASL standard

---

hypervisor/scenarios/industry/vm_configurations.c
hypervisor/scenarios/industry/vm_configurations.h

This patch makes the following changes:
- Remove the 4th VM
- Make the default vcpu num of RTVM as 2
Tracked-On: #3925

hv: Update industry scenarios configuration

---

doc/reference/hardware.rst
hypervisor/arch/x86/boot/trampoline.S
hypervisor/arch/x86/trampoline.c

Patch lets ACRN use 1GB large pages for trampoline code execution.
Adds a new section to doc/reference/hardware.rst to list the
requirement of 1GB large pages.
Tracked-On: #3899
Signed-off-by: Sainath Grandhi sainath.grandhi@intel.com
Acked-by: Eddie Dong eddie.dong@intel.com

Let trampoline execution use 1GB pages

---

hypervisor/arch/x86/guest/ept.c
hypervisor/arch/x86/guest/vm.c
hypervisor/common/hypercall.c
hypervisor/dm/io_req.c
hypervisor/dm/vpci/pci_pt.c
hypervisor/include/arch/x86/guest/ept.h
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/dm/io_req.h

ToDo:
preserve concurrent access for PCI configuration space
v4:
1. minor refine input parameter mmio_idx for register_mmio_emulation_handler
2. detail comment for vdev_pt_remap_msix_table_vbar
v3:
1. refine unregister_mmio_emulation_handler implementation
2. delete the MSI-X table BAR EPT memory region mapping for pre-launched VM
3. move EPT operation out of mmio emulation handler register function.
v2:
1. rename is_ept_mr_valid to ept_is_mr_valid
2. add unregister_mmio_emulation_handler API
3. add PCI MSI-X table BAR re-programming support
v1:
add PCI BAR re-programing address check

Vpci: add PCI MSI-X table BAR re-programming support

---

doc/getting-started/apl-nuc.rst
doc/tutorials/static-ip.rst

PR #3665 moved the doc build folder, so files referenced via directives
had an incorrect path (need to add an additional ../../ to the front of
relative paths that were referencing files outside of the doc folder).

doc: fix broken include paths

---

doc/developer-guides/hld/hld-security.rst
doc/developer-guides/hld/hv-cpu-virt.rst
doc/developer-guides/hld/hv-virt-interrupt.rst
doc/developer-guides/hld/index.rst
doc/developer-guides/hld/vuart-virt-hld.rst
doc/tutorials/using_windows_as_uos.rst

As reported in PR #3959, doc build errors were being masked by a script
error.  This PR fixes a chunk of them.

doc: fix doc build errors previously masked

---

doc/develop.rst
doc/developer-guides/hld/virtio-i2c.rst
doc/release_notes/release_notes_0.6.rst
doc/release_notes/release_notes_1.3.rst

This should get us back to a clean doc build now...

doc: fix remaining masked doc build errors

---

doc/conf.py
doc/scripts/filter-doc-log.sh

PR #3665 moved all the doc build artifacts into the _build folder and
updated scripts and Makefile to account for this, except missed a fix in
the script that checks for known issues. This patch fixes that but shows
we've got a bunch of issues that have not been being reported so we'll
need to fix those problems to resolve failing doc builds.
Also fixed processing of the VERSION file in conf.py since the path to that
file was changed by PR #3665 as well and was raising an exception that
was being masked.

doc: doc build errors not being reported

---

misc/acrn-config/launch_config/com.py
misc/acrn-config/launch_config/pt.py

- acrn-config: 'keep_gsi' flag set for Android vm
- acrn-config: Remove virtio-blk for PREEMPT-RT LINUX
Tracked-On: #3949

acrn-config: Hotfix for launch config

---

Makefile
misc/efi-stub/Makefile

Remove default acrn.efi and modify KBL-NUC/sdc for default build 
Tracked-On: #3953

Modify KBL-NUC/SDC for default build

---

hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vm_reset.c
hypervisor/arch/x86/seed/seed.c

ul is used as immediate integer suffix with type uint64_t.
Tracked-On: #3214

hv: fixed by replace ull to ul.

---

hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/guest/vmcs.c

We should use INIT signal to notify the vcpu threads when
powering off the hard RTVM. To achive this, we should set
the vcpu->thread_obj.notify_mode as SCHED_NOTIFY_INIT.
Patch (27163df9 hv: sched: add sleep/wake for thread object)
tries to set the notify_mode according `is_lapic_pt_enabled(vcpu)`
in function prepare_vcpu. But at this point, the is_lapic_pt_enabled(vcpu)
will always return false. Consequently, it will set notify_mode
as SCHED_NOTIFY_IPI. Then leads to the failure of powering off
hard RTVM.
This patch fixes it by:
- Initialize the notify_mode as SCHED_NOTIFY_IPI in prepare_vcpu.
- Set the notify_mode as SCHED_NOTIFY_INIT after passthroughing lapic to guest.
Tracked-On: #3974

HV: Fix poweroff issue of hard RTVM

---

hypervisor/dm/io_req.c
hypervisor/dm/vioapic.c
hypervisor/dm/vpci/pci_pt.c

v3:
revert "remove the constraint of 64 bits PCI BAR remapping".
v2:
This patch try to do unmap/map in vdev_pt_write_vbar directly and remove
the constraint of 64 bits PCI BAR remapping.
v1:
This patch try to do unmap/map in vdev_pt_remap_mem_vbar directly and remove
the constraint of 64 bits PCI BAR remapping.

hv: vpci: reshuffle vdev_pt_write_vbar implementation

---

misc/acrn-config/launch_config/com.py
misc/acrn-config/library/board_cfg_lib.py
misc/acrn-config/xmls/board-xmls/whl-ipc-i5.xml
misc/acrn-config/xmls/board-xmls/whl-ipc-i7.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/hybrid.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/industry.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/industry_launch_1uos_hardrt.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/industry_launch_1uos_vxworks.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/industry_launch_1uos_waag.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/industry_launch_2uos.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/logical_partition.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/sdc.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/sdc2.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/sdc_launch_1uos_laag.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/sdc_launch_1uos_zephyr.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/hybrid.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/industry.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/industry_launch_1uos_hardrt.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/industry_launch_1uos_vxworks.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/industry_launch_1uos_waag.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/industry_launch_2uos.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/logical_partition.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/sdc.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/sdc2.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/sdc_launch_1uos_laag.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/sdc_launch_1uos_zephyr.xml

- refine mem_size_set function
- refine interrupt_storm function
- add support to generate launch script
- remove runC script from unnecessary launch script
- add config files for whl-ipc-i7 board
- add config files for whl-ipc-i5 board
- remove parser for console

acrn-config: Support whiskylake i5 and whiskylake i7 board

---

misc/acrn-config/board_config/board_cfg_gen.py
misc/acrn-config/board_config/new_board_kconfig.py
misc/acrn-config/library/board_cfg_lib.py

Enhance the $(board).config for new board.
Serial config should be set in $(board).config for new board.

acrn-config: add serial config in new $(board).config

---

hypervisor/arch/x86/guest/vm.c
hypervisor/dm/io_req.c
hypervisor/dm/vpci/vdev.c
hypervisor/dm/vpci/vpci.c
hypervisor/dm/vpci/vpci_priv.h
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/dm/vpci.h

1)  define PCI CONFIG_ADDRESS Register as its physical layout
2) add a global PCI lock for each VM
3)  add a lock to protect mmio_node access

hv: vpci:  add lock to protect PCI or MSI-X BAR concurrent access

---

misc/acrn-config/launch_config/com.py

Enable xhci usb mediator for whl-ipc-i5/whl-ipc-7 and KBL NUC for LaaG
and WaaG.

acrn-config: add 'xhci' usb mediator for laag and waag

---

Makefile
hypervisor/Makefile

This reverts commit 9ddf27669bc2a7dab643b138fe55572fcb2cba6c.
Souce code should be generate out firstly to solve the dependency for
make all acrn-hypervisor code. 9ddf27669bc commit does not work in some
scenario, so revert it.

Revert "Makefile: add default defconfig for new board"

---

doc/user-guides/acrn-dm-parameters.rst

This commit updates the DM parameters reference document to reflect
the removal of the guest cpu number option '-c' implementation.
Tracked-On: #3989

doc: remove the guest cpu number option '-c' from the document

---

doc/tutorials/running_deb_as_user_vm.rst
doc/tutorials/running_ubun_as_user_vm.rst
doc/tutorials/using_celadon_as_uos.rst

Remove redundant copy of ovmf.fd firmware as the lunach script now
instructs the DM to user the OVMF.fd firmware directly from the rootfs.
Tracked-On: #3972 

doc: remove redundant copy of ovmf.fd firmware

---

devicemodel/hw/pci/core.c

checking the inputs explicitly instead of using Assert.
Tracked-On: #3991
Reviewed-by: Shuo Liu <shuo.a.liu@intel.com>

dm: validate the input in 'pci_emul_mem_handler()'

---

doc/developer-guides/hld/hv-cpu-virt.rst

schedule_vcpu should be replaced by launch_vcpu
Tracked-On: #3963

doc: schedule_vcpu was removed

---

hypervisor/arch/x86/e820.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/mmu.c
hypervisor/include/arch/x86/e820.h
misc/efi-stub/boot.c

Now the default board memory size is 16 GB. However, ACRN support more and more boards
which may have memory size large than 16 GB. This patch try to remove un-configure
high memory form EFI memory map.
Tracked-On: #4007

Mmu: remove unconfigure high memory from EFI memory map

---

hypervisor/arch/x86/guest/vmcall.c

hypcall_id has a type of uint64_t and should use 'llx' as
formatting flag instead of '%d'. Otherwise, we will get a
confusing error log when not-allowed hypercall occurs.
Without this patch:
[96707209us][cpu=1][sev=3][seq=2386]:hypercall -2147483548 is only allowed from SOS_VM!
With this patch:
[84613395us][cpu=1][sev=3][seq=2136]:hypercall 0x80000064 is only allowed from SOS_VM!
So, we can figure out which not-allowed hypercall has been triggered more conveniently.
BTW, this patch adds hypcall_id which triggered from non-ring0 into error log.
Tracked-On: #4012

HV: correct the formatting flag of hypcall_id

---

misc/acrn-config/library/board_cfg_lib.py

acrn-config: chose ttyS1 for vuart1
For vuart1, if it's mapped to a real native serial port, we must
re-use the native serial port io base and irq number. If no native
serial port is mapped to vuart1, non-exist io base and irq should
be used.
Please note: UOS launch script may need be updated according to
which serial port index is used by vuart1.
Now, we are using ttyS1 of SOS for vuart1 in our release. User may
need to remap vuart to different ttySx by following above rule if
ttyS1 in user platform is used by other devices like Bluetooth/Wifi.
Tracked-On: #4016
Acked-On: Victor Sun <victor.sun@intel.com>

acrn-config: modify board config for whl-ipc-i5/whl-ipc-i7

---

doc/reference/hardware.rst

KBL NUC NUC7i5DNH has serial port;
The default binary will not support 2 core / 2 thread any more, so the minimun system requirements for ACRN should be 2 core/4 thread or 4 core+;
Add the cores and threads for each CPU.
Signed-off-by: Xie Zhengtian <zhengtian.xie@intel.com>

doc:  correct some mistakes add add cores and threads for CPU of supported hardware

---

doc/scripts/filter-doc-log.sh
doc/scripts/pullsource.sh

doc: add copyright/license header to doc scripts

---

hypervisor/arch/x86/guest/instr_emul.c

remove unnecessary wrapper for this api(emulate_instruction)

hv:remove unnecessary wrapper for emulate_instruction

---

misc/acrn-config/launch_config/com.py
misc/acrn-config/launch_config/pt.py

- acrn-config: 'keep_gsi' flag set for Android vm
Tracked-On: #3955

acrn-config: keep_gsi set for android only

---

misc/acrn-config/board_config/board_cfg_gen.py
misc/acrn-config/board_config/new_board_kconfig.py
misc/acrn-config/launch_config/com.py
misc/acrn-config/library/board_cfg_lib.py
misc/acrn-config/xmls/board-xmls/whl-ipc-i5.xml
misc/acrn-config/xmls/board-xmls/whl-ipc-i7.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/hybrid.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/industry.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/industry_launch_1uos_hardrt.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/industry_launch_1uos_vxworks.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/industry_launch_1uos_waag.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/industry_launch_2uos.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/logical_partition.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/sdc.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/sdc2.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/sdc_launch_1uos_laag.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/sdc_launch_1uos_zephyr.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/hybrid.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/industry.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/industry_launch_1uos_hardrt.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/industry_launch_1uos_vxworks.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/industry_launch_1uos_waag.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/industry_launch_2uos.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/logical_partition.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/sdc.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/sdc2.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/sdc_launch_1uos_laag.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/sdc_launch_1uos_zephyr.xml

these patches are cherry-pick from Release 1.4
-  add 'xhci' usb mediator for laag and waag
-  add serial config in new $(board).config
- refine mem_size_set function
- refine interrupt_storm function
- add support to generate launch script
- remove runC script from unnecessary launch script
- add config files for whl-ipc-i7 board
- add config files for whl-ipc-i5 board
- chose ttyS1 for vuart1

acrn-config: Cherry pick patch from 1.4

---

misc/acrn-config/board_config/board_c.py

without the msr.h file the build will be failed when CAT is enabled.
Tracked-On: #4066

acrn-config: include msr.h in board.c

---

Makefile
hypervisor/Makefile
hypervisor/scripts/kconfig/kconfig.mk
misc/acrn-config/kconfig/silentoldconfig.py
misc/acrn-config/library/cfg_update.mk

Currently make hypervisor will depend on a $(BOARD).config file to load
board defconfig which triggered by oldconfig process, this will block
make from XMLs for a new board because $(BOARD).config never exist.
This requires us to patch configuration for new board earlier than make
oldconfig.
Tracked-On: #4067

Makefile: support make new board from xml

---

misc/efi-stub/Makefile

Move hypervisor related include path from CFLAGS to INCLUDE_PATH to make
structure more clean.

Makefile: refine include path for efi_stub

---

Makefile

If we don't enforce passing BOARD_FILE/SCENARIO_FILE param to
hypervisor/Makefile, the BOARD_FILE/SCENARIO_FILE value would
not be overridden to its realpath in hypervisor/Makefile when
make hypervisor.
Tracked-On: #4067

Makefile: pass BOARD/SCENARIO FILE to make hv

---

devicemodel/samples/nuc/launch_hard_rt_vm.sh

The parameter of intel_pstate should be 'disable' instead of 'disabled'.
This patch fixes it.
Tracked-On: #4094

DM: samples: Correct parameter of intel_pstate

---

hypervisor/arch/x86/guest/vmx_io.c
hypervisor/arch/x86/page.c
hypervisor/arch/x86/pagetable.c
hypervisor/include/arch/x86/page.h

Issue description:
-----------------
Machine Check Error on Page Size Change
Instruction fetch may cause machine check error if page size
and memory type was changed without invalidation on some
processors[1][2]. Malicious guest kernel could trigger this issue.
This issue applies to both primary page table and extended page
tables (EPT), however the primary page table is controlled by
hypervisor only. This patch mitigates the situation in EPT.
Mitigation details:
------------------
Implement non-execute huge pages in EPT.
This patch series clears the execute permission (bit 2) in the
EPT entries for large pages. When EPT violation is triggered by
guest instruction fetch, hypervisor converts the large page to
smaller 4 KB pages and restore the execute permission, and then
re-execute the …

hv: ept: disable execute right on large pages

---

hypervisor/debug/dump.c
hypervisor/include/arch/x86/irq.h

In 64-bit mode, processor pushes SS and RSP onto stack unconditionally.
Also when dumping the exception info, it makes more sense to dump
the RSP at the point of interrupt, rather than the RSP after pushing
context (including GPRs)
Tracked-On: #4102

hv: Fix the definition of struct representing interrupt hw frame

---

hypervisor/dm/vpci/pci_pt.c
hypervisor/dm/vpci/vdev.c
hypervisor/dm/vpci/vpci.c
hypervisor/dm/vpci/vpci_priv.h
hypervisor/include/dm/vpci.h
hypervisor/include/hw/pci.h

v4:
move vBAR base setting into pci_vdev_write_bar.
v3:
1. reorder patch sequence
2. refine patch comment by detail describing why we need this change.
v2:
1. split patch into three small ones.
2. refine PCI IO BAR map
v1:
1. revert commit 95d10d pci_bar structure restruction
2. remove 64 bits PCI BAR map logic constraint

hv: vpci: reshuffle pci_bar structure

---

devicemodel/core/sw_load_elf.c
devicemodel/hw/pci/ahci.c
devicemodel/hw/pci/gsi_sharing.c
devicemodel/hw/pci/npk.c
devicemodel/hw/pci/virtio/virtio_block.c
devicemodel/hw/pci/virtio/virtio_mei.c
devicemodel/hw/platform/tpm/tpm_crb.c
hypervisor/arch/x86/guest/guest.c
hypervisor/arch/x86/pagetable.c
hypervisor/common/hypercall.c
hypervisor/lib/string.c
tools/acrn-crashlog/usercrash/server.c
tools/acrn-manager/acrn_vm_ops.c

This PR back ports recent fix on ACRN baseline onto GP2.0 /apl_sdc_stable branch
Patches List:
1 | Improper Usage Of MACRO   LIST_FOREACH() |  
2 | Descriptor of Directory Stream   Is Referenced After Release |  
3 | DM: FILE Pointer Is Not Closed   After Operations in acrn_load_elf |  
4 | DM: 'tpm_vdev->request_mutex'   is potentially not unlocked in 'crb_reg_write()' |  
6 | DM: The return value of snprintf   is improperly checked |  
7 | the return value of   "strtol" is not validated properly |  
8 | Invalid pointer validation in   "crash_completed_cb()" |  
9 | AP Trampoline Code in Hypervisor   Is Potentially Accessible to Service VM |  
10 | Hypervisor crash when run   syz_ic_set_callback_vector. |  
11 | Buffer overflow will happen in   'strncmp' when 'n_arg' is 0 |  

Gp2.0 Patches back-porting

---

devicemodel/core/sw_load_elf.c
devicemodel/hw/pci/ahci.c
devicemodel/hw/pci/gsi_sharing.c
devicemodel/hw/pci/npk.c
devicemodel/hw/pci/virtio/virtio_block.c
devicemodel/hw/pci/virtio/virtio_mei.c
devicemodel/hw/platform/tpm/tpm_crb.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/pagetable.c
hypervisor/common/hypercall.c
hypervisor/lib/string.c
tools/acrn-crashlog/usercrash/server.c
tools/acrn-manager/acrn_vm_ops.c

This PR back ports recent fix on ACRN baseline onto ACRN 1.0 stable branch
Patches List:
1 | Improper Usage Of MACRO LIST_FOREACH() |  
2 | Descriptor of Directory Stream Is Referenced After Release |  
3 | DM: FILE Pointer Is Not Closed After Operations in acrn_load_elf |  
4 | DM: 'tpm_vdev->request_mutex' is potentially not unlocked in 'crb_reg_write()' |  
6 | DM: The return value of snprintf is improperly checked |  
7 | the return value of "strtol" is not validated properly |  
8 | Invalid pointer validation in "crash_completed_cb()" |  
9 | AP Trampoline Code in Hypervisor Is Potentially Accessible to Service VM |  
10 | Hypervisor crash when run syz_ic_set_callback_vector. |  
11 | Buffer overflow will happen in 'strncmp' when 'n_arg' is 0 |

ACRN V1.0 stable patches back- porting

---

hypervisor/arch/x86/Kconfig
hypervisor/arch/x86/guest/vmx_io.c
hypervisor/arch/x86/page.c
hypervisor/arch/x86/pagetable.c
hypervisor/arch/x86/security.c
hypervisor/include/arch/x86/msr.h
hypervisor/include/arch/x86/page.h
hypervisor/include/arch/x86/security.h

Issue description:
-----------------
Machine Check Error on Page Size Change
Instruction fetch may cause machine check error if page size
and memory type was changed without invalidation on some
processors[1][2]. Malicious guest kernel could trigger this issue.
This issue applies to both primary page table and extended page
tables (EPT), however the primary page table is controlled by
hypervisor only. This patch mitigates the situation in EPT.
Mitigation details:
------------------
Implement non-execute huge pages in EPT.
This patch series clears the execute permission (bit 2) in the
EPT entries for large pages. When EPT violation is triggered by
guest instruction fetch, hypervisor converts the large page to
smaller 4 KB pages and restore the execute permission, and then
re-execute the …

Mitigation for Machine Check Error on Page Size Change (release v1.4)

---

hypervisor/arch/x86/guest/trusty.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/guest/vmx_io.c
hypervisor/arch/x86/mmu.c
hypervisor/arch/x86/page.c
hypervisor/arch/x86/pagetable.c
hypervisor/arch/x86/vtd.c
hypervisor/include/arch/x86/mmu.h
hypervisor/include/arch/x86/page.h
hypervisor/include/arch/x86/pgtable.h
hypervisor/include/arch/x86/vtd.h

Issue description:
-----------------
Machine Check Error on Page Size Change
Instruction fetch may cause machine check error if page size
and memory type was changed without invalidation on some
processors[1][2]. Malicious guest kernel could trigger this issue.
This issue applies to both primary page table and extended page
tables (EPT), however the primary page table is controlled by
hypervisor only. This patch mitigates the situation in EPT.
Mitigation details:
------------------
Implement non-execute huge pages in EPT.
This patch series clears the execute permission (bit 2) in the
EPT entries for large pages. When EPT violation is triggered by
guest instruction fetch, hypervisor converts the large page to
smaller 4 KB pages and restore the execute permission, and then
re-execute the …

Mitigation Machine Check Error on Page Size Change (for release_1.0)

---

misc/acrn-config/board_config/acpi_platform_h.py
misc/acrn-config/board_config/misc_cfg_h.py
misc/acrn-config/library/board_cfg_lib.py
misc/acrn-config/library/scenario_cfg_lib.py

- enhance the board config that has no serial port
- set S3/S5 to default value while BIOS not support them
- modify the key of vuart base
Tracked-On: #4128

acrn-config: Refinement for board config

---

Makefile
hypervisor/Makefile

The $(BOARD)_acpi_info.h is generated by acrn-config tool, remove this
header in make clean would cause failure when user finish configuring
in webUI and start to make acrn-hypervisor by the command
"make hypervisor BOARD=xxx SCENARIO=yyy" because we mandatory do make
clean before making hypervisor.
The patch replace the file removal with a warning string to hint user
to check the file validity.

Makefile: do not rm board acpi info header

---

doc/getting-started/rt_industry.rst

No need rt kernel info in gsg doc.

doc: remove rt gsg kernel info

---

hypervisor/arch/x86/e820.c

add panic if there is no memory map info during booting.

hv:panic if there is no memory map in multiboot info

---

doc/reference/hardware.rst
hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/vtd.c
hypervisor/hw/pci.c
hypervisor/include/arch/x86/vtd.h
hypervisor/include/hw/pci.h

These patches introduce changes to:
1. Correctly handle IOMMU-to-device association when DMAR DRHD entries
contain Bridge type device scope
2. Handle multi-function devices more gracefully
Tracked-On: #4134

Fix gaps in ACRN support for server platforms

---

hypervisor/arch/x86/Kconfig
misc/efi-stub/boot.c
misc/efi-stub/stdlib.h

Add a Kconfig parameter called UEFI_OS_LOADER_NAME to hold the Service VM EFI
bootloader to be run by the ACRN hypervisor. A new string manipulation function
to convert from (char *) to (CHAR16 *) has been added to facilitate the
implementation.
The default value is set to systemd-boot (bootloaderx64.efi)
Tracked-On: #2793

hv: add Kconfig parameter to define the Service VM EFI bootloader

---

doc/developer-guides/hld/hv-dev-passthrough.rst
hypervisor/arch/x86/guest/assign.c
hypervisor/dm/vpci/pci_pt.c
hypervisor/dm/vpci/vmsi.c
hypervisor/dm/vpci/vmsix.c
hypervisor/dm/vpci/vpci_priv.h
hypervisor/include/arch/x86/guest/assign.h

1. rename ptirq_msix_remap to ptirq_prepare_msix_remap
2. name vmsi with verb-object style

hv: vmsi: refine function name 

---

misc/acrn-config/board_config/board_c.py
misc/acrn-config/board_config/board_cfg_gen.py
misc/acrn-config/board_config/pci_devices_h.py
misc/acrn-config/config_app/controller.py
misc/acrn-config/config_app/static/main.js
misc/acrn-config/config_app/templates/scenario.html
misc/acrn-config/config_app/views.py
misc/acrn-config/launch_config/com.py
misc/acrn-config/launch_config/launch_item.py
misc/acrn-config/library/common.py
misc/acrn-config/library/launch_cfg_lib.py
misc/acrn-config/library/scenario_cfg_lib.py
misc/acrn-config/scenario_config/scenario_cfg_gen.py
misc/acrn-config/scenario_config/vm_configurations_c.py
misc/acrn-config/scenario_config/vm_configurations_h.py
misc/acrn-config/target/dmar.py
misc/acrn-config/xmls/config-xmls/apl-mrb/sdc.xml
misc/acrn-config/xmls/config-xmls/apl-up2/sdc.xml
misc/acrn-config/xmls/config-xmls/generic/sdc.xml
misc/acrn-config/xmls/config-xmls/nuc6cayh/sdc.xml
misc/acrn-config/xmls/config-xmls/nuc7i7dnb/sdc.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/sdc.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/sdc.xml

- skip the DRHDn_IGNORE when no device scope
- walk secondary PCI Bus for target board
- refinement for DmarDevScope struct
- modify SDC config xml to support kata vm config in webUI
- add UI to add or remove Kata VM for sdc scenario
- launch refinement on vcpu affinity and uos image
- refine vcpu affinity/number for SDC scenario
- print warning if MMIO BAR size above 4G
- modify the git commit message for gen_patch
Tracked-On: #4143

acrn-config: Refinemen vcpuaffinity and walk secondary PCI Bus

---

misc/acrn-config/library/launch_cfg_lib.py

The function of get_leaf_tag_map(info_file, prime_item, item='') in
launch_config_lib.py is redundant and it will be called incorrectly
when generating the launch script. This patch remove the function.

acrn-config:  remove extra function in launch config library

---

hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vmsr.c

Changes to make sure guest read the same TSC_DEADLINE value it wrote, if the timer has not expired; and if the timer has expired, read 0.

Fix tsc_deadline read/write issues

---

misc/acrn-config/board_config/acpi_platform_h.py
misc/acrn-config/target/acpi.py
misc/acrn-config/xmls/board-xmls/apl-mrb.xml
misc/acrn-config/xmls/board-xmls/apl-up2-n3350.xml
misc/acrn-config/xmls/board-xmls/apl-up2.xml
misc/acrn-config/xmls/board-xmls/nuc6cayh.xml
misc/acrn-config/xmls/board-xmls/nuc7i7dnb.xml
misc/acrn-config/xmls/board-xmls/whl-ipc-i5.xml
misc/acrn-config/xmls/board-xmls/whl-ipc-i7.xml

- add MMCFG_BASE_INFO item in board config
- get default pci mmcfg base address
Tracked-On: #4173

acrn-config: add mmcfg base address for board config

---

hypervisor/acpi_parser/acpi_ext.c
hypervisor/arch/x86/configs/nuc7i7dnb/platform_acpi_info.h
hypervisor/arch/x86/configs/platform_acpi_info.h
hypervisor/arch/x86/cpu.c
hypervisor/boot/guest/vboot_wrapper.c
hypervisor/boot/include/acpi.h
hypervisor/hw/pci.c
hypervisor/include/hw/pci.h

The default PCI mmcfg base is stored in ACPI MCFG table, when
CONFIG_ACPI_PARSE_ENABLED is set, acpi_fixup() function will
parse and fix up the platform mmcfg base in ACRN boot stage;
when it is not set, platform mmcfg base will be initialized to
DEFAULT_PCI_MMCFG_BASE which generated by acrn-config tool;
Please note we will not support platform which has multiple PCI
segment groups.
Tracked-On: #4157

HV: parse default pci mmcfg base

---

hypervisor/arch/x86/guest/virq.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/guest/vmcs.c
hypervisor/common/hv_main.c
hypervisor/include/arch/x86/guest/vcpu.h

After changing init_vmcs to smp call approach and do it before
launch_vcpu, it could work with noop scheduler. On real sharing
scheudler, it has problem.
pcpu0                  pcpu1            pcpu1
vmBvcpu0                vmAvcpu1         vmBvcpu1
vmentry
init_vmcs(vmBvcpu1) vmexit->do_init_vmcs
corrupt current vmcs
vmentry fail
launch_vcpu(vmBvcpu1)
This patch mark a event flag when request vmcs init for specific vcpu. When
it is running and checking pending events, will do init_vmcs firstly.
Tracked-On: #4178

hv: make init_vmcs as a event of VCPU

---

hypervisor/arch/x86/Kconfig
hypervisor/arch/x86/page.c
hypervisor/arch/x86/pagetable.c
hypervisor/arch/x86/security.c
hypervisor/include/arch/x86/msr.h
hypervisor/include/arch/x86/page.h
hypervisor/include/arch/x86/security.h

In order to mitigate the issue Machine Check Error on Page Size Change, hypervisor force to break large pages (2MB/1GB) to 4KB pages in EPT on instruction fetch in VM.
However, the mitigate has performance penalty. So only apply the mitigation conditionally.
- Turn off the mitigation for the processor models that are known immune to the issue.
- Add an option to force to disable the mitigation when all VMs are trusted.
- Build 4KB page mapping in EPT for RTVM
Tracked-On: #4101

hv: ept: apply MCE on page size change mitigation conditionally

---

hypervisor/arch/x86/guest/vmcs.c

PMU is hidden from any guest, UD is expected when guest
try to execute 'rdpmc' instruction.
this patch sets 'RDPMC exiting' in Processorbased
VM-execution control.
Tracked-On: #3453

hv: trap RDPMC instruction execution from any guest

---

hypervisor/arch/x86/guest/vmexit.c
misc/tools/acrntrace/scripts/formats

We care more about leaf and subleaf of cpuid than vcpu_id.
So, this patch changes the cpuid trace-entry to trace the leaf
and subleaf of this cpuid vmexit.

trace leaf and subleaf of cpuid

---

hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/guest/vmcs.c
hypervisor/debug/logmsg.c
hypervisor/debug/shell.c
hypervisor/dm/io_req.c
hypervisor/include/arch/x86/guest/vmcs.h

This patchset will add one scheduler named sched_iorr which support cpu sharing.
sched_iorr is short for IO sensitive Round-robin scheduler. It aims to schedule
threads with round-robin as basic policy, and be enhanced with some faireness
configuration such as preemption occurs on running out of timeslice, IO request
pending thread will be scheduled in high priority.
The patchset also add PAUSE-loop, HLT emulation support. HLT emulation is a simple
version for improving cpu sharing performance for now, which will be improved later.
There are also some bugfixs in the first few patches of the patchset.
Conghui Chen (1):
hv: bugfix for debug commands with smp_call (in this PR)
Shuo A Liu (12):
hv: print current sched_object in acrn logmsg (in this PR)
hv: io: do schedule if we need in IO …

Some bugfixs and preparation patches for sched_iorr

---

devicemodel/core/vmmapi.c
devicemodel/hw/pci/core.c
devicemodel/hw/pci/gvt.c
devicemodel/include/pci_core.h
devicemodel/include/vmmapi.h

In previous design:
1. GVT-g sets vgpu bars' value from physical gpu bars.
2. ACRN-DM sets pci bars according to its policy.
These two paths don't communicate with each other, but
they deal with the same thing:pci bars.
So there's a risk that ACRN-DM bars region overlap with GVT-g.
In the following four patches, we will keep DM consistent with 
GVT-g when deal with pci bars.
In the following description, 
patch 1 refers dm:gvt:reserve gvt bar regions in ACRN-DM
patch 2 refers dm:gvt:adjust pci bar region with reserved bar regions
patch 3 refers dm:gvt:update gvt bars before other pci devices write bar address
patch 4 refers dm:gvt:Enable gvt bar registration
In our design:
1. When ACRN-DM init gvt, it will read physical gpu bars, 
and reserve these bar regions.
patch 1 will complete this …

keep DM consistent with GVT-g when deal with pci bars

---

hypervisor/arch/x86/guest/assign.c
hypervisor/dm/vpci/vmsi.c
hypervisor/dm/vpci/vmsix.c
hypervisor/include/dm/vpci.h

1. Do vMSI-X remap only when Mask Bit in Vector Control Register for MSI-X Table Entry is unmask
2. fix the Message Control Register check logic when doing vmsi/vmsi-x remap
3. fix the HV doesn't really disable MSI/MSI-X when guest wants to.

vpci: refine vmsi/vmsi-x remap

---

Makefile

If "make menuconfig" chooses hybrid or logical_partition scenario,
currently the build fails with "SCENARIO <$(SCENARIO)> is not supported.".
- CONFIG_LOGICAL_PARTITION: "awk -F "_|=" '{print $$2}'" yields the second
field (LOGICAL) only. The new "cut -d '_' -f 2-" keeps all fields after
"CONFIG_".
- Add the missing HYBRID scenario.
Tracked-On: #4067

Makefile: fix make failure for logical_partition or hybrid scenario

---

hypervisor/arch/x86/guest/vm_reset.c

To handle reboot requests from pre-launched VMs that don't have
GUEST_FLAG_HIGHEST_SEVERITY, we shutdown the target VM explicitly
other than ignoring them.

hypervisor: handle reboot from non-privileged pre-launched guests

---

hypervisor/arch/x86/Kconfig

This patch updates kconfig to support server platforms
for increased number of VCPUs per VM and PT IRQ number.
Tracked-On: #4196

HV: Kconfig changes to support server platform.

---

devicemodel/Makefile
misc/acrn-manager/Makefile
misc/efi-stub/Makefile
misc/life_mngr/Makefile

Add the below flags, they are needed in -O2:
-fno-delete-null-pointer-checks:
tells the compiler NOT to assume that null pointer deference does
not exist.
-fwrapv:
tells the compiler that signed overflow always wraps.
Tracked-On: #4194

Makefile: add gcc flags to prevent some optimization

---

misc/acrn-config/config_app/static/main.js
misc/acrn-config/config_app/templates/launch.html

This is to make acrn config UI supports to edit more than one virtio
input devices in multi-lines
Tracked-On: #4163

acrn-config: UI supports to edit mulitple virtio input devices

---

hypervisor/Makefile
hypervisor/arch/x86/Kconfig
hypervisor/common/sched_iorr.c
hypervisor/common/schedule.c
hypervisor/include/arch/x86/per_cpu.h
hypervisor/include/common/schedule.h

This patchset will add one scheduler named sched_iorr which support cpu sharing.
sched_iorr is short for IO sensitive Round-robin scheduler. It aims to schedule threads with round-robin as basic policy, and be enhanced with some faireness configuration such as preemption occurs on running out of timeslice, IO request pending thread will be scheduled in high priority.
The patchset also add PAUSE-loop, HLT emulation support. HLT emulation is a simple version for improving cpu sharing performance for now, which will be improved later.
v2: Add @pre and assert for sched_iorr_init
Shuo A Liu (9):
hv: sched_iorr: Add IO sensitive Round-robin scheduler
hv: sched_iorr: add init functions of sched_iorr
hv: sched_iorr: add tick handler and runqueue operations
hv: sched_iorr: add some interfaces …

Add one scheduler which support cpu sharing: sched_iorr

---

doc/getting-started/building-from-source.rst

"9e9e1f61 acrntrace: Add opt to specify the cpus where we should capture the data"
uses APIs of libnuma. So this patch adds dependency of libnuma in building-from-source.rst.
libnuma functions have been included in os-core-dev bundle of clearlinux.
Tracked-On: #4175

Doc: Add libnuma dependency for acrntrace

---

misc/acrn-config/board_config/ve820_c.py

This patch fixes an issue with generation of guest ve820 when the size
of the memory is >512MB. The issue is primarily with respect to converting
between hex and int.
Tracked-On: #4219

acrn-config: Fix ve820 table generation when guest memory size is >512MB

---

hypervisor/arch/x86/vtd.c

The initialization of "dmar_unit->gcmd" shall be done via reading from
Global Status Register rather than Global Command Register.
Rationale:
According to Chapter 10.4.4 Global Command Register in VT-d spec, Global Command
Register is a write-only register to control remapping hardware.
Global Status Register is the corresponding read-only register to report remapping
hardware status.

hv: vtd: fix improper use of DMAR_GCMD_REG

---

Makefile

Update build option for 'acrn-hypervisor', build release
version by default.
Tracked-On: #4222

Makefile: Build Release version by default

---

hypervisor/include/arch/x86/guest/vm.h

remove 'guest_init_pml4' and 'tmp_pg_array' in vm_arch
since they are not used.

hv:remove 2 unused variables in vm_arch structure

---

hypervisor/arch/x86/Kconfig
hypervisor/arch/x86/configs/apl-mrb/misc_cfg.h
hypervisor/arch/x86/configs/apl-up2/misc_cfg.h
hypervisor/arch/x86/configs/dnv-cb2/misc_cfg.h
hypervisor/arch/x86/configs/generic/misc_cfg.h
hypervisor/arch/x86/configs/nuc6cayh/misc_cfg.h
hypervisor/arch/x86/configs/nuc7i7dnb/misc_cfg.h
hypervisor/arch/x86/configs/vacpi.c
hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/guest/assign.c
hypervisor/arch/x86/guest/hyperv.c
hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/lapic.c
hypervisor/arch/x86/notify.c
hypervisor/boot/acpi_base.c
hypervisor/boot/include/acpi.h
hypervisor/common/hypercall.c
hypervisor/debug/profiling.c
hypervisor/debug/shell.c
hypervisor/include/arch/x86/cpu.h
hypervisor/include/arch/x86/guest/vlapic.h
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/arch/x86/per_cpu.h
hypervisor/include/arch/x86/vm_config.h
hypervisor/include/debug/profiling_internal.h
hypervisor/include/dm/vacpi.h
hypervisor/pre_build/static_checks.c
hypervisor/scenarios/sdc/vm_configurations.c
misc/acrn-config/board_config/misc_cfg_h.py

In current architecutre, the maximum vCPUs number per VM could not
exceed the pCPUs number. Given the MAX_PCPU_NUM macro is provided
in board configurations, so remove the MAX_VCPUS_PER_VM from Kconfig
and add a macro of MAX_VCPUS_PER_VM to reference MAX_PCPU_NUM directly.
Tracked-On: #4230

HV: remove MAX_VCPUS_PER_VM in Kconfig

---

misc/acrn-config/board_config/ve820_c.py
misc/acrn-config/xmls/config-xmls/apl-mrb/hybrid.xml
misc/acrn-config/xmls/config-xmls/apl-mrb/logical_partition.xml
misc/acrn-config/xmls/config-xmls/apl-up2-n3350/logical_partition.xml
misc/acrn-config/xmls/config-xmls/apl-up2/hybrid.xml
misc/acrn-config/xmls/config-xmls/apl-up2/logical_partition.xml
misc/acrn-config/xmls/config-xmls/nuc6cayh/hybrid.xml
misc/acrn-config/xmls/config-xmls/nuc6cayh/logical_partition.xml
misc/acrn-config/xmls/config-xmls/nuc7i7dnb/hybrid.xml
misc/acrn-config/xmls/config-xmls/nuc7i7dnb/logical_partition.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/hybrid.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/logical_partition.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/hybrid.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/logical_partition.xml

For currently supported hardware such as KNL NUC, the scenario xml file is not generated and the newly added non-contiguous variables will not be present. This can lead to build issues. This patch adds the second non-contiguous HPA variable to all supported hardware for both logical_partition and hybrid modes. It also adds checks to ensure that HPA2 is valid before using it while creating the guest VM ve820.
Tracked-On: #4242

acrn-config: Add non-contiguous HPA to currently supported hardware.

---

Makefile
hypervisor/arch/x86/Kconfig

- Set default CONFIG_KATA_VM_NUM to 1 in SDC scenario so that user could
have a try on Kata container without rebuilding hypervisor.
- When user use make menuconfig to configure memory related kconfig items,
we need add range check to avoid compile error or other potential issues.
Tracked-On: #4229

HV: Kconfig: set kata num to 1 and add some memory range check 

---

hypervisor/common/hypercall.c

Input 'vcpu_id' and the state of target vCPU should be validated
properly:
- 'vcpu_id' shall be less than 'vm->hw.created_vcpus' instead
of 'MAX_VCPUS_PER_VM'.
- The state of target vCPU should be "VCPU_PAUSED", and reject
all other states.
Tracked-On: #4245

hv:fix crash issue when handling HC_NOTIFY_REQUEST_FINISH

---

hypervisor/arch/x86/guest/vmsr.c
hypervisor/include/arch/x86/msr.h

Reserved bits in a 8-bit PAT field has been checked in pat_mem_type_invalid.
Remove this redundant check "(PAT_FIELD_RSV_BITS & field) != 0UL" in
write_pat_msr.

hv: msr: remove redundant check in write_pat_msr

---

hypervisor/arch/x86/guest/ept.c
hypervisor/arch/x86/guest/vm.c
hypervisor/include/arch/x86/guest/vm.h

EPT table can be changed concurrently by more than one vcpus.
This patch add a lock to protect the add/modify/delete operations
from different vcpus concurrently.
Tracked-On: #4253

hv: add lock for ept add/modify/del

---

doc/getting-started/Dockerfile

Since commit 9e9e1f61, a new build dependency on the NUMA library has been
introduced. We therefore need to add the `devpkg-numactl` bundle to our
Dockerfile used to build the Clear Linux "ACRN builder" container image.
Tracked-On: #4175

doc: add new dependency to Clear Linux ACRN builder container

---

doc/getting-started/building-from-source.rst

Update guidance to build ACRN from source,
as debug feature is disabled by default in Makefile.
'RELEASE' shall be 0 if debug feature is required.
Tracked-On: #4222

doc:debug feature is disabled by default

---

hypervisor/arch/x86/guest/vcpu.c
hypervisor/include/arch/x86/cpu.h

In current code, XCR0 and XSS are not in default value during vcpu
launch, it will result in a warning in Linux:
WARNING: CPU: 0 PID: 0 at arch/x86/kernel/fpu/xstate.c:614
fpu__init_system_xstate+0x43a/0x878
For security reason, we set XCR0 and XSS with feature bitmap get from
CPUID, and run XRSTORS in context switch in. This make sure the XSAVE
area to be fully in initiate state.
But, before enter guest for the first time, XCR0 and XSS should be set to
default value, as the guest kernel assume it.

hv: hotfix for xsave

---

hypervisor/arch/x86/timer.c
hypervisor/dm/vpci/pci_pt.c
hypervisor/dm/vpci/vpci.c
hypervisor/hw/pci.c
hypervisor/include/arch/x86/timer.h
hypervisor/include/dm/vpci.h
hypervisor/include/hw/pci.h

v3:
1. Update commit comments
2. refine usleep to msleep
3. rename vdev_pt_do_flr to pdev_do_flr
v2:
1. replace udelay instead of usleep
2. warp a function to do the save, reset and restore.
3. update some comment.
v1:
This patch tries to trap PCI AF FLR or PCIe FLR. Then restore BARs information to physical CFG space.
Tracked-On: #3465

vpci: trap PCI AF FLR or PCIe FLR and restore BARs information

---

misc/acrn-config/xmls/config-xmls/apl-mrb/sdc.xml
misc/acrn-config/xmls/config-xmls/apl-up2/sdc.xml
misc/acrn-config/xmls/config-xmls/nuc6cayh/sdc.xml
misc/acrn-config/xmls/config-xmls/nuc7i7dnb/sdc.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/sdc.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/sdc.xml

Currently kata vm is supported in SDC scenario by default, both vm1
and kata vm would share pcpu id 3 for vcpu affinity even when cpu
sharing is not enabled.
Remove pcpu id 3 from vm1 in SDC scenario config xmls.
Tracked-On: #4286

acrn-config: remove pcpu3 from vm1 in SDC scenario

---

misc/acrn-config/library/common.py
misc/acrn-config/xmls/config-xmls/apl-mrb/logical_partition.xml
misc/acrn-config/xmls/config-xmls/apl-up2-n3350/logical_partition.xml
misc/acrn-config/xmls/config-xmls/apl-up2/logical_partition.xml
misc/acrn-config/xmls/config-xmls/nuc6cayh/logical_partition.xml
misc/acrn-config/xmls/config-xmls/nuc7i7dnb/logical_partition.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/logical_partition.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/logical_partition.xml

Modify the hpa start size value for logical_partition scenario to avoid
build issue, and make the memory size of pre-launched VM configurable.

acrn-config: modify hpa start size value for logical_partition scenario

---

misc/acrn-config/library/scenario_cfg_lib.py
misc/acrn-config/scenario_config/pci_dev_c.py
misc/acrn-config/scenario_config/vm_configurations_c.py
misc/acrn-config/scenario_config/vm_configurations_h.py

scenario_cfg_lib.py:
- removed extra white space before ','
pci_dev_c.py:
- follow style in other files, added two empty lines
- removed extra line at the end of the .c file
vm_configurations_c.py
- alignment
vm_configurations_h.py
- alignment

acrn-config: fix a few formatting issues

---

doc/tutorials/using_partition_mode_on_up2.rst
hypervisor/scenarios/logical_partition/vm_configurations.c
misc/acrn-config/xmls/config-xmls/apl-mrb/logical_partition.xml
misc/acrn-config/xmls/config-xmls/apl-up2-n3350/logical_partition.xml
misc/acrn-config/xmls/config-xmls/apl-up2/logical_partition.xml
misc/acrn-config/xmls/config-xmls/generic/logical_partition.xml
misc/acrn-config/xmls/config-xmls/nuc6cayh/logical_partition.xml
misc/acrn-config/xmls/config-xmls/nuc7i7dnb/logical_partition.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/logical_partition.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/logical_partition.xml

- commit 69152647 ("hv: Use virtual APIC IDs for Pre-launched VMs")
enables virtual APIC IDs for pre-launched VMs thus xapic_phys is no
longer needed to force guest xAPIC to work in physical destination mode.
- HVC is not available in logical partition mode and "console=hvc0" should
be removed from guest Linux bootargs.

acrn-config: some cleanup for logical partition mode Linux bootargs

---

devicemodel/core/main.c

This patch refactors the CMD_OPT_LAPIC_PT case branch
to explicity add the dependency of option RTVM at the
same branch, it is decoupled from the next case branch
to comply with strict code standard and improve the
code readability.
Tracked-On: #4283
Signed-off-by: Gary <gordon.king@intel.com>

devicemodel: refactor CMD_OPT_LAPIC_PT case branch

---

hypervisor/dm/vpci/pci_pt.c
hypervisor/dm/vpci/vdev.c
hypervisor/hw/pci.c
hypervisor/include/dm/vpci.h

1. minor fix of coding style about pci_read_cap
2. rename pci_bar to pci_vbar

vpci: minor refine of the coding style

---

hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/lapic.c
hypervisor/common/hypercall.c
hypervisor/include/arch/x86/guest/vcpu.h
hypervisor/include/arch/x86/guest/vlapic.h
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/arch/x86/lapic.h

- correct apic lvt reset value
- clean up redundant macro in lapic.h
- rename function of vlapic_xxx_write_handler
- refine reset_vcpu api
- ensure valid vcpu state transition
- restore lapic state and apic id upon INIT
Tracked-On: #4267

hv: patch set for vlapic reset and vcpu state transition

---

hypervisor/arch/x86/configs/vm_config.c
hypervisor/dm/vuart.c

- target vm_id of vuart can't be un-defined VM, nor the VM itself.
- fix potential NULL pointer dereference in find_active_target_vuart()

hv: add sanity check for vuart configuration

---

hypervisor/arch/x86/guest/instr_emul.c

It is found that 0xf6 test instruction is used to access MMIO in
Windows. This patch added emulation for 0xf6 test instruction.

hv: instr_emul: add emulation for 0xf6 test instruction

---

devicemodel/core/main.c
devicemodel/hw/pci/passthrough.c
devicemodel/include/dm.h
hypervisor/arch/x86/timer.c
hypervisor/common/hypercall.c
hypervisor/dm/vpci/pci_pt.c
hypervisor/dm/vpci/vpci.c
hypervisor/dm/vpci/vpci_priv.h
hypervisor/hw/pci.c
hypervisor/include/arch/x86/timer.h
hypervisor/include/dm/vpci.h
hypervisor/include/hw/pci.h

v4:
Since there're some PT devices don't support FLR or PM reset (like Audio, USB). So now only print error message for this case.
v3:
refine BAR restore logic
v2:
revisit BAR restore by doing this when writing Command Register if reset was detected.
v1:
1. restore PCI BARs CFG when setting power state from D3HOT to D0
2. add assumption for passthrough PCI device for each PT device should support FLR or PM reset
3. do reset for passthrough PCI device by default
Tracked-On: #3465

vpci: revisit BAR restore

---

misc/acrn-config/target/misc.py

/proc/cpuinfo represents online CPUs only, and the number of CPUs is
limited by the 'maxcpus' option.
/sys/devices/system/cpu/possible is a better option for our purpose
since it represents the possible CPUs that can ever be available in the
system, including the offline CPUs. And it's not limited by 'maxcpus'.
Though the Linux command line parameter nr_cpus and possible_cpus still
have impact on /sys/devices/system/cpu/possible.

acrn-config: dump CPU info from /sys/devices/system/cpu/possible

---

hypervisor/arch/x86/guest/vcpuid.c
hypervisor/arch/x86/guest/virtual_cr.c
hypervisor/arch/x86/guest/vmcs.c

Guest OS kernels, like Linux kernel, enabled Kernal Page Table Isolation (KPTI) as the mitigation of Meltdown.
Enabling KPTI without the support of PCID will cause significant performance loss when user/kernel space switch is frequent.
This patch series passes-through PCID capabilities to guest VM.
Note: On the hardware platforms that are not affected by Miltdown, Linux doesn't enabled KPTI unless it is forced by kernel parameter "pti=on".
Tracked-On: #4296

PCID Virtualization Support

---

doc/tutorials/building_acrn_in_docker.rst

Fix the name of the Docker Container image that is used to build the kernel
for an RTVM (Preempt-RT kernel) when that image was built by the user
him/herself.
Tracked-On: #4322

doc: fix wrong Docker container image in tutorial

---

hypervisor/arch/x86/configs/apl-mrb/board.c
hypervisor/arch/x86/configs/apl-mrb/misc_cfg.h
hypervisor/arch/x86/configs/apl-up2/board.c
hypervisor/arch/x86/configs/apl-up2/misc_cfg.h
hypervisor/arch/x86/configs/dnv-cb2/board.c
hypervisor/arch/x86/configs/dnv-cb2/misc_cfg.h
hypervisor/arch/x86/configs/generic/board.c
hypervisor/arch/x86/configs/generic/misc_cfg.h
hypervisor/arch/x86/configs/icl-rvp/board.c
hypervisor/arch/x86/configs/nuc6cayh/board.c
hypervisor/arch/x86/configs/nuc6cayh/misc_cfg.h
hypervisor/arch/x86/configs/nuc7i7dnb/board.c
hypervisor/arch/x86/configs/nuc7i7dnb/misc_cfg.h
hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/guest/vm.c
hypervisor/debug/uart16550.c
hypervisor/dm/vpci/vpci.c
hypervisor/hw/pci.c
hypervisor/include/arch/x86/board.h
hypervisor/include/debug/uart16550.h
hypervisor/include/dm/vpci.h
hypervisor/include/hw/pci.h
hypervisor/release/uart16550.c
misc/acrn-config/board_config/board_c.py
misc/acrn-config/board_config/misc_cfg_h.py
misc/acrn-config/library/board_cfg_lib.py

v6:
expose BIOS hided PCI devices to SOS more generically.
v5:
expose P2SB to SOS
v4:
Add PCI-compatible Configuration Mechanism (IO port) access back for early debug.
v3:
update PCIe MMCONFIG region to be owned by hypervisor.
v2:
Remove PCIe ECAM access emulation for pre-launched VM since it doesn't mean to support PCIe ECAM access.
v1:
Now ACRN HV only trap PCI mmconfig access for pre-launched VM and SOS and emulate
the front 256 bytes configuration space access add pass through the PCI external
configuration space access.

PCI: Add PCIe ECAM access support

---

devicemodel/core/hugetlb.c
devicemodel/core/mevent.c
devicemodel/core/timer.c
devicemodel/hw/block_if.c
devicemodel/hw/pci/core.c
devicemodel/hw/pci/gvt.c
devicemodel/hw/pci/virtio/virtio_block.c
devicemodel/hw/pci/wdt_i6300esb.c
devicemodel/log/disk_logger.c
devicemodel/log/kmsg_logger.c

use acrn-dm logger function instread of perror,
this helps the stability testing log capture.
Tracked-On: #4098

dm:replace perror with pr_err

---

hypervisor/dm/vpci/vpci.c

This patch checks the validity of 'target_vdev' and
'target_vdev->pdev' before calling 'move_pt_device()'
to avoid potential hypervisor crash when destroying VM
with crafted input.
Tracked-On: #4336

hv:validate input in 'deinit_postlaunched_vm_vpci()'

---

hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/guest/vmcs.c
hypervisor/common/hypercall.c
hypervisor/debug/shell.c
hypervisor/dm/io_req.c
hypervisor/include/arch/x86/guest/vm.h

Due to vcpu and its thread are two different perspective modules, each
of them has its own status. Dump both states for better understanding
of system status.

show vcpu thread status in vcpu_list debug command

---

doc/tutorials/kbl-nuc-sdc.rst
doc/tutorials/run_kata_containers.rst

Update the "Using SDC Mode on the NUC" tutorial to use ACRN v1.5. The Clear
Linux used in this update is 32080 which is also the first release that includes
a Service VM (linux-iot-lts2018-sos) kernel that supports MACVLAN and MACVTAP,
both of which are need to run Kata Containers on ACRN.

doc: update the "Using SDC Mode on the NUC" tutorial

---

hypervisor/hw/pci.c

it is better to init bdfs_from_drhds.pci_bdf_map_count
before it is passed to other function to do:
bdfs_from_drhds->pci_bdf_map_count++
Tracked-On: #3875

HV: init local variable before it is used.

---

doc/getting-started/building-from-source.rst

Project ACRN is targetting to keep the hypervisor's total number of lines of
code (LOC) below 40K. Update the "Build ACRN from Source" document to accurately
reflect that.

doc: update project's target max LOC

---

devicemodel/core/sw_load_common.c
devicemodel/hw/pci/core.c
devicemodel/hw/pci/passthrough.c
devicemodel/include/pcireg.h
devicemodel/include/sw_load.h
hypervisor/acpi_parser/dmar_parse.c
hypervisor/arch/x86/vtd.c

1. 2 hypervisor patches to clean  IOMMU snoop control bit, this is global and has side effect. These patches need to be revised.
2. 5 dm patches are cherry-picked from\ master branch.   
2 for set bar lowbits from HW ; 
3 for reserve memory space for stolen memory and opregion in dm. 
Junming Liu (7):
dm:keep pci bar property unchanged when updating pci bar address
dm:derive the prefetch property of PCI bar for pass-through device
dm:reserve 64M hole for graphics stolen memory in e820 table
dm:passthrough graphics stolen memory to uos gpu
dm:passthrough opregion to uos gpu
Always disable the iommu_snoop when enabling the IOMMU for GPU
hv: More changes to enable GPU passthru
devicemodel/core/sw_load_common.c   | 25 ++++++++--
devicemodel/hw/pci/core.c           | 13 +++-- …

For GVT-D 1.5-release Validation Only

---

misc/acrn-config/target/misc.py

When generating the board configuration XML file, script ``misc.py`` reads file ``/sys/devices/system/cpu/possible`` on the target machine. There is a range ``N-M`` for CPU IDs that are available. The script identifies only CPU IDs ``N-(M-1)``.
Fix: change ``<`` to ``<=`` to include the final CPU ID.

Python scripts discovering CPU IDs are off by 1

---

hypervisor/debug/uart16550.c

Tracked-On: #4390 
See prior commit which added this typo
`eraly_boot -> early_boot`
```
commit cc47dbe7698b1991bc5844a609fb5f00608af0f8
Author: Li, Fei1 <fei1.li@intel.com>
Date:   Wed Jul 24 17:50:27 2019 +0800
hv: uart: enable early boot uart
Enable uart as early as possible to make things easier for debugging.
After this we could use printf to output information to the uart. As for
pr_xxx APIs, they start to work when init_logmsg is called.
diff --git a/hypervisor/debug/uart16550.c b/hypervisor/debug/uart16550.c
index 11bd859a..98837a6b 100644
--- a/hypervisor/debug/uart16550.c
+++ b/hypervisor/debug/uart16550.c
@@ -131,12 +131,17 @@ static void …
```

acrn: rename param in uart16550_init

---

doc/tutorials/using_ubuntu_as_sos.rst

Update the "Using Ubuntu as the Service OS" tutorial to tweak the instructions
pertaining to the Grub bootloader configuration. Specifically, update to reflect
the content of '/etc/default/grub' in Ubuntu 18.04 and also make loading the
Service OS kernel the default.

doc: update Grub configuration instructions for Ubuntu (Service VM)

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/init.c
hypervisor/arch/x86/timer.c

Currently panic() and pr_xxx() statements before init_primary_pcpu_post()
won't be printed, which is inconvenient and misleading for debugging.
This patch makes pr_xxx() APIs working before init_pcpu_pre():
- clear .bss in init.c, which makes sense to clear .bss at the very beginning
of initialization code. Also this makes it possible to call init_logmsg()
before init_pcpu_pre().
- move parse_hv_cmdline() and uart16550_init(true) to init.c.
- refine ticks_to_us() to handle the case that it's called before
calibrate_tsc(). As a side effect, it prints "0us" in early pr_xxx() calls.
- call init_debug_pre() in init_primary_pcpu() and after this point,
both printf() and pr_xxx() APIs are available.
However, this patch doesn't address the issue that pr_xxx() could be called
on PCPUs that …

hv: enable early pr_xxx() logs

---

devicemodel/samples/nuc/launch_win.sh

Delete pass-through audio to WaaG in default because WHL cannot support audio reset.
Tracked-On: #4397

Delete pass-through audio to WaaG in default

---

misc/acrn-config/scenario_config/vm_configurations_c.py

- python script crashes if the desired 'clos' tag doesn't exist in the
scenario xml file. In the following example, tag '0' doesn't exist:
clos_set: {1: '0', 2: '0'}
referring to tag 0 directly ("vm_info.clos_set[0] == None") causes crash.
To fix it, this patch uses "if i in vm_info.clos_set:" where 'i' is the
VM id and serves as the tag in the clos_set dictionary, to sanity
check the dictionary.
- if the hardware doesn't support CAT, don't need to generate clos entry
in the vm_config[], which could be confusing.
- to reduce redundant code, wrap the clos generation code as a function.

acrn-config: a few changes on vm_config[] clos generation

---

hypervisor/boot/guest/vboot_wrapper.c

acrn: add pxelinux as known bootloader
PXE implements Multiboot and allows you to boot acrn via the network boot.

Add PXE boot loader string to known boot loaders

---

hypervisor/Makefile

In some build env (Ubuntu 19.10 as example), gcc enabled the option
-fcf-protection by default. But this option is not compatible with
-mindirect-branch. Which could trigger following build error:
fail to build with gcc-9 [error: ‘-mindirect-branch’ and
‘-fcf-protection’ are not compatible]
-mindirect-branch is mandatory for retpoline mitigation and always
enabled for ACRN build. We disable -fcf-protection here for ACRN
build.
Tracked-On: #4358
Acked-by: Wu Binbin <binbin.wu@intel.com>

Makefile: disable fcf-protection for some build env

---

hypervisor/arch/x86/Kconfig
hypervisor/arch/x86/cat.c
hypervisor/arch/x86/configs/vm_config.c
hypervisor/arch/x86/cpu.c
hypervisor/include/arch/x86/cat.h
hypervisor/include/arch/x86/vm_config.h
hypervisor/include/public/acrn_common.h

In platforms that support CAT, when it is enabled by ACRN, i.e.
IA32_resourceType_MASK_n registers are programmed with customized values,
it has impacts to the whole system.
The per guest flag GUEST_FLAG_CLOS_REQUIRED suggests that CAT may be
enabled in some guests, but not in others who don't have this flag,
which is conceptually incorrect.
This patch removes GUEST_FLAG_CLOS_REQUIRED, and adds a new Kconfig
entry CAT_ENABLED for CAT enabling. When it's enabled, platform_clos_array[]
defines a set of system-wide Class of Service (COS, or CLOS), and the
per guest vm_configs[].clos associates the guest with particular CLOS.

hv: CAT is supposed to be enabled in the system level

---

hypervisor/arch/x86/guest/vcpu.c
hypervisor/common/event.c

On UEFI UP2 board, APs might execute HLT before SOS kernel INIT them.
After SOS kernel take over and will re-init the APs directly. The flows
from HV perspective is like:
HLT trap:
wait_event(VCPU_EVENT_VIRTUAL_INTERRUPT) -> sleep_thread
SOS kernel INIT, SIPI APs:
pause_vcpu(ZOMBIE) -> sleep_thread
-> reset_vcpu
-> launch_vcpu -> wake_vcpu
However, the last wake_vcpu will fail because the cpu event
VCPU_EVENT_VIRTUAL_INTERRUPT had not got signaled.
This patch will reset all vcpu events in reset_vcpu. If the thread was
previously waiting for a event, its waiting status will be cleared and
launch_vcpu will wake it to running.
Tracked-On: #4402

hv: reset vcpu events in reset_vcpu

---

devicemodel/hw/pci/lpc.c
devicemodel/hw/pci/passthrough.c
hypervisor/acpi_parser/dmar_parse.c
hypervisor/arch/x86/Kconfig
hypervisor/arch/x86/cpu_caps.c
hypervisor/arch/x86/vtd.c
hypervisor/include/arch/x86/cpu_caps.h

GPU IOMMU doesn’t support snoop control, to enable gvt-d, 
need to disable iommu snoop control for all VMs.
When enabling gvt-d, there is a restriction that 
Windows guest needs a lpc bridge device
located in 00:1f.0 PCI slot.
So add an extra lpc bridge.

disable iommu snoop control and add dummy lpc when enable gvt-d

---

hypervisor/Makefile

The previous fcf-protection fix broke the old gcc (older than
gcc 8 which is common on Ubuntu 18.04 and older distributions).
We only add fcf-protection=none for gcc8 and newer.
Tracked-On: #4358

Makefile: fix build issue on old gcc

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/guest/virq.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/guest/vm_reset.c
hypervisor/arch/x86/guest/vmx_io.c
hypervisor/arch/x86/init.c
hypervisor/arch/x86/irq.c
hypervisor/arch/x86/timer.c
hypervisor/boot/guest/vboot_info.c
hypervisor/common/hypercall.c
hypervisor/common/ptdev.c
hypervisor/common/vm_load.c
hypervisor/debug/profiling.c
hypervisor/debug/shell.c
hypervisor/dm/vpic.c
hypervisor/include/arch/x86/cpu.h
hypervisor/include/arch/x86/guest/vcpu.h

Repace hardcoded value with BOOT_CPU_ID when
ID of BSP is referenced.
Tracked-On: #851

hv: use BOOT_CPU_ID instead of hardcoded value

---

hypervisor/Makefile
hypervisor/arch/x86/Kconfig
hypervisor/common/sched_bvt.c
hypervisor/common/schedule.c
hypervisor/include/arch/x86/per_cpu.h
hypervisor/include/common/schedule.h

As the current IORR scheduler has below defects:
1) unfair
2) cannot prevent I/O attack: Use I/O to maliciously preempt pCPU resources
BVT is introduced. It can provide fair share of pCPU resource to vCPU,
and prevent I/O attack. BVT also has competitive I/O performance as IORR.

hv: support BVT scheduler

---

hypervisor/Makefile

We hit build issue if the ld version is 2.34:
error: PHDR segment not covered by LOAD segment
One issue was created to binutils bugzilla system:
https://sourceware.org/bugzilla/show_bug.cgi?id=25585
From the ld guys comment, this is not an issue of 2.34. It's an
issue fixing of the old ld. He suggested to add option
--no-dynamic-linker
to ld if we don't depend on dynamically linker to loader our binary.
Tracked-On: #4415

Makefile: Fix build issue if the ld is updated to 2.34

---

hypervisor/Makefile
hypervisor/arch/x86/Kconfig
hypervisor/arch/x86/boot/cpu_primary.S
hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/e820.c
hypervisor/arch/x86/init.c
hypervisor/arch/x86/seed/seed.c
hypervisor/boot/cmdline.c
hypervisor/boot/guest/deprivilege_boot.c
hypervisor/boot/guest/direct_boot.c
hypervisor/boot/guest/vboot_info.c
hypervisor/boot/guest/vboot_wrapper.c
hypervisor/boot/include/boot.h
hypervisor/boot/include/guest/vboot.h
hypervisor/boot/include/multiboot.h
hypervisor/boot/include/multiboot2.h
hypervisor/boot/multiboot.c
hypervisor/boot/multiboot2.c
hypervisor/common/vm_load.c
hypervisor/debug/console.c
hypervisor/include/arch/x86/vm_config.h
hypervisor/include/arch/x86/zeropage.h

Currently ACRN hypervisor can only boot from multiboot1 protocol, which
introduced a possible risk that when boot from a EFI platform, hypervisor
might have problem to parse host ACPI RSDP pointer, because RSDP might
exist in efi system table only, which is not visible for multiboot1.
The patch set enables multiboot2 support for ACRN. When CONFIG_MULTIBOOT2
is enabled, both multiboot1 and multiboot2 header magic would be existed in
hv image, and ACRN will be loaded accordingly per bootloader scenario.
When CONFIG_MULTIBOOT2 is disabled, only multiboot1 magic is existed and
ACRN can only boot from multiboot1 protocol.
Another benefit for multiboot2 enabling is it could pass host efi information,
make guest possible to boot with efi environment.
Bootloader scenario and multiboot usage:
1. …

HV: patch set to enable multiboot2

---

hypervisor/arch/x86/lib/retpoline-thunk.S

Per Section 4.4 Speculation Barriers, in
"Retpoline: A Branch Target Inject Mitigation" white paper,
"LFENCE instruction limits the speculative execution that
a processor implementation can perform around the LFENCE,
possibly impacting processor performance,but also creating
a tool with which to mitigate speculative-execution
side-channel attacks."
Tracked-On: #4424

hv: refine retpoline speculation barriers

---

misc/acrn-config/board_config/new_board_kconfig.py
misc/acrn-config/launch_config/launch_item.py
misc/acrn-config/library/launch_cfg_lib.py

- avoid conflict slot for launch config
- Kata VM is not supported on dual-core systems
Tracked-On: #4312

acrn-config: avoid conflict slot for launch config

---

hypervisor/acpi_parser/dmar_parse.c

The dedicated DMAR unit for Intel integrated GPU
shall be available on the physical platform.
So remove the assert and add application constraint
in handle_one_drhd func.
Tracked-On: #4405
Reviewed-by: Wu Binbin <binbin.wu@intel.com>
Reviewed-by: Wu Xiangyang <xiangyang.wu@linux.intel.com>

hv:refine comment about intel integrated gpu dmar

---

hypervisor/Makefile
hypervisor/dm/vpci/vpci.c
hypervisor/dm/vpci/vpci_bridge.c
hypervisor/include/dm/vpci.h
hypervisor/include/hw/pci.h

add vpci bridge operations in hypervisor, to avoid SOS mis-operations
to affect other VM's PCI devices.
assumption: before hypervisor bootup, the physical pci-bridge shall be
configured correctly by BIOS or other bootloader; for ACS (Access
Control Service) capability, it is configured by BIOS to support the
devices under it to be isolated and allocated to different VMs.
to simplify the emulations of vpci bridge, set limitations as following:
1. expose all configure space registers, but readonly
2. BIST not support; by default is 0
3. not support interrupt, including INTx and MSI.
TODO:
1. configure tool can select whether a PCI bridge is emulated or pass
through.
Open:
1. SOS how to reset PCI device under the PCI bridge?
Tracked-On: #3381
Signed-off-by: Yin Fengwei …

HV: add vpci bridge operations support

---

hypervisor/arch/x86/e820.c

It puts the new line in the wrong place, and the logs are confusing.
For example, for these entries:
mmap[0] - type: 1, base: 0x00000, length: 0x9800
mmap[1] - type: 2, base: 0x98000, length: 0x8000
mmap[2] - type: 3, base: 0xc0000, length: 0x4000
Currently it prints them in this way:
mmap table: 0 type: 0x1
Base: 0x0000000000000000 length: 0x0000000000098000
mmap table: 1 type: 0x2
Base: 0x0000000000098000 length: 0x0000000000008000
mmap table: 2 type: 0x3
Base: 0x00000000000c0000 length: 0x0000000000040000
With this fix, it looks like the following, and now it's of same style
with how prepare_sos_vm_memmap() logs ve820 tables.
mmap table: 0 type: 0x1
Base: 0x0000000000000000 length: 0x0000000000098000
mmap table: 1 type: 0x2
Base: 0x0000000000098000 length: 0x0000000000008000
mmap …

hv: refine confusing e820 table logging layout

---

hypervisor/Makefile
hypervisor/arch/x86/configs/pci_dev.c
hypervisor/dm/vpci/vpci.c
hypervisor/dm/vpci/vpci_priv.h
hypervisor/dm/vpci/vsriov.c
hypervisor/hw/pci.c
hypervisor/include/arch/x86/pci_dev.h
hypervisor/include/dm/vpci.h
hypervisor/include/hw/pci.h

This patch-set implements SRIOV-capable device discovery and add SRIOV capability interception entries.
SR-IOV(single root input/output virtualization) can isolate PCIe devices and
make the devices to have good performance, close to bare-metal. The SR-IOV
consists of two basic units, one is called PF(Physical Function) that supports
SRIOV PCIe extended capability and manages entire physical device, another is
called VF (Virtual Function) and is a "lightweight" PCIe function which is meant
to be given to a VM as a pass-through device. For more details, please refer to
PCI Express Base Specification Revision 4.0 Chapter 9. 

Introduce SR-IOV feature for ACRN

---

devicemodel/hw/pci/core.c
devicemodel/hw/pci/passthrough.c
devicemodel/include/pci_core.h

Since this callback is only useful for pass through PCIe device and now pass through
PCIe device emulation has splited from DM to HV. we could remove this callback now.

dm: remove vdev_update_bar_map callback for PCIe device

---

devicemodel/core/vmmapi.c

If the guest is RTVM, dm process exit doesn't mean RTVM is
shutdown. Only shutdown_vm in hypervisor guarantee RTVM is
shutodwn. So we should avoid touch guest memory content
from DM if the guest is RTVM.
Tracked-On: #4428

dm: avoid clear guest memory content if guest is RTVM

---

misc/acrn-config/board_config/pci_devices_h.py

Devices that support SR-IOV can expose their capabilities in
lspci -vv command as below. The offline tool, instead of picking
up the bios exposed memory region(bc000000) for the devices ends
picking up the SR-IOV memory region(00000000c0000000) and generates
VBAR address (in pci_devices.h). This is incorrect. This patch
fixes the offline tool to take the right memory region as the
VBAR address.
Sample lspic -vv log:
67:00.0 Ethernet controller: Intel Corporation Ethernet Connection
X722 for 10GbE backplane (rev 09)
Subsystem: Intel Corporation Device 0000
Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr+
Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort-
Latency: 0
Interrupt: pin A routed to IRQ 61
Region 0: Memory at bc000000 (64-bit, prefetchable) …

acrn-config: Fix vbar address generated by the offline tool

---

hypervisor/arch/x86/configs/pci_dev.c
hypervisor/dm/vpci/pci_pt.c
hypervisor/dm/vpci/vpci.c
hypervisor/dm/vpci/vpci_priv.h
hypervisor/dm/vpci/vsriov.c
hypervisor/hw/pci.c
hypervisor/include/arch/x86/pci_dev.h
hypervisor/include/dm/vpci.h
hypervisor/include/hw/pci.h

Refine the HV APIs about  adding pdev/pci_dev_config/vdev data structures, and implement VF device creation.
Yuan Liu (6):
hv: refine init_vdev_pt function
hv: implement SRIOV VF_BAR initialization
hv: refine init_pdev function
hv: refine init_one_dev_config
hv: refine vpci_init_vdev function
hv: initialize SRIOV VF device
hypervisor/arch/x86/configs/pci_dev.c | 15 +++++--
hypervisor/dm/vpci/pci_pt.c           | 85 ++++++++++++++++++++++++++++-------
hypervisor/dm/vpci/vpci.c             | 22 +++++++--
hypervisor/dm/vpci/vpci_priv.h        |  5 ++-
hypervisor/dm/vpci/vsriov.c           | 60 ++++++++++++++++++++++---
hypervisor/hw/pci.c                   | 19 ++++++--
hypervisor/include/arch/x86/pci_dev.h |  2 +-
hypervisor/include/dm/vpci.h          | 10 +++++
hypervisor/include/hw/pci.h …

The second SRIOV patch-set

---

misc/acrn-config/scenario_config/vm_configurations_h.py

Currently config tool generated 'console=/dev/ttySn' in boot cmdline
for logical_partiton scenario, need to strip '/dev/' to avoid kernel
boot issue.
Tracked-On: #4451

acrn-config: correct console argument for logical partition scenario

---

hypervisor/hw/pci.c

The pci_read_cap and pci_read_ext_cap are used to enumerate PCI
legacy capability and extended capability.
Change the name pci_read_cap to pci_enumerate_cap
Change the name pci_read_ext_cap to pci_enumerate_ext_cap

hv: refine pci_read_cap and pci_read_ext_cap

---

doc/developer-guides/hld/hv-dev-passthrough.rst
hypervisor/include/common/ptdev.h

One argument is missing for the function ptirq_alloc_entry.
This patch fixes the doc generation error.
Tracked-On: #3882

doc: fix a missing argument in the function description

---

hypervisor/arch/x86/cpu.c
hypervisor/hw/pci.c

Add some pre-assumption for PCIe ECAM:
1) ACRN only support platforms with PCIe ECAM to access PCIe device CFG space;
2) Must not use ECAM to access PCIe device CFG space before
pci_switch_to_mmio_cfg_ops was called. (In release version, ACRN didn't support
IO port Mechanism. ECAM is the only way to access the PCIe device CFG space).

hv: pci: add some pre-assumption for PCIe ECAM

---

hypervisor/arch/x86/Kconfig
hypervisor/arch/x86/boot/cpu_primary.S
hypervisor/arch/x86/boot/cpu_save_boot_ctx.S
hypervisor/boot/include/boot.h
hypervisor/boot/include/reloc.h
hypervisor/boot/reloc.c
hypervisor/bsp/ld/link_ram.ld.in
hypervisor/include/arch/x86/boot/ld_sym.h
misc/efi-stub/boot.c

- add multiboot2 tags to enable boot loader to relocate hypervisor image
- manually fixup relocation delta in code32
- change some existing fixup in code64 so it won't double fixup.
- update the 64-bit entry address to efi-stub

hv: enable 32bit relocation which is needed for multiboot2

---

devicemodel/core/main.c
devicemodel/hw/pci/passthrough.c

Let the ACRN HV to do this in shutdown sequence. In this case, the RTVM could be
still alive if something wrong happened to cause the DM died.
Tracked-On: #4428

dm: don't deassign pass through PCIe device in DM

---

hypervisor/dm/vpci/vpci_bridge.c
hypervisor/hw/pci.c
hypervisor/include/hw/pci.h

1. enable ARI in PCI bridge 
2. move out physical cfg write operation from vpci-bridge.

enable ARI in PCI bridge and improve vpci-bridge 

---

hypervisor/arch/x86/guest/assign.c
hypervisor/debug/shell.c
hypervisor/dm/vioapic.c
hypervisor/dm/vpic.c
hypervisor/include/arch/x86/guest/assign.h
hypervisor/include/common/ptdev.h

1. Renames DEFINE_IOAPIC_SID with DEFINE_INTX_SID as the virtual interrupt controller can
be IOAPIC or PIC
2. Rename the src member of source_id.intx_id to ctlr to indicate interrupt
controller
2. Changes the type of src member of source_id.intx_id from uint32_t to
enum with INTX_CTLR_IOAPIC and INTX_CTLR_PIC
Tracked-On: #4447

hv: Variable/macro renaming for handling PT dev interrupts using IOAPIC/PIC

---

hypervisor/dm/vpci/pci_pt.c
hypervisor/dm/vpci/vpci.c
hypervisor/dm/vpci/vpci_priv.h
hypervisor/include/hw/pci.h

v5:
refine comments and fix MISRA-C violation.
v4:
Add cfg_header_read_cfg and cfg_header_write_cfg to handle the 1st 64B
CFG Space header PCI configuration space.
Only Command and Status Registers are pass through;
Only Command and Status Registers and Base Address Registers are writable.
In order to implement this, we add two type bit mask for per 4B register:
pass through mask and read-only mask. When pass through bit mask is set, this
means this bit of this 4B register is pass through, otherwise, it is virtualized;
When read-only mask is set, this means this bit of this 4B register is read-only,
otherwise, it's writable. We should write it to physical CFG space or virtual
CFG space base on whether the pass through bit mask is set or not.
Signed-off-by: Li Fei1 …

hv: vpci: add a global CFG header configuration access handler

---

hypervisor/arch/x86/pagetable.c

In Commit 127c73c3, we remove the strict check for adding page table mapping. However,
we just replace the ASSERT of pr_fatal in add_pte. This is not enough. We still add
the virtual address by 4K if the page table mapping is exist and check the virtual
address is over the virtual address region for this mapping. Otherwise, The complain
will continue for 512 times at most.
Now On APL UP2, the SOS will re-program the PCI BAR for some Intel Corporation Sunrise Point-LP PCI Express Root Port. There're too many compalin like "add_pte, pte 0xXXXXXXXX is already present!"

hv: mmu: minor fix about add_pte

---

hypervisor/dm/vpci/pci_pt.c
hypervisor/dm/vpci/vdev.c
hypervisor/dm/vpci/vhostbridge.c
hypervisor/dm/vpci/vpci.c
hypervisor/dm/vpci/vpci_bridge.c
hypervisor/dm/vpci/vpci_priv.h

Removed the pci_vdev_write_cfg_u8/u16/u32 APIs and only used
pci_vdev_write_cfg as the API for writing vdev's cfgdata

hv: Refine code for API reduction

---

hypervisor/dm/vpci/pci_pt.c
hypervisor/dm/vpci/vdev.c
hypervisor/dm/vpci/vhostbridge.c
hypervisor/dm/vpci/vmsi.c
hypervisor/dm/vpci/vmsix.c
hypervisor/dm/vpci/vpci.c
hypervisor/dm/vpci/vpci_bridge.c
hypervisor/dm/vpci/vpci_priv.h

Add _v prefix for some function name to indicate this function wants to operate
on virtual CFG space or virtual BAR register.

hv: vpci: add _v prefix for some function name

---

hypervisor/pre_build/static_checks.c

Hypervisor uses 2MB large page, and if either CONFIG_HV_RAM_START or
CONFIG_HV_RAM_SIZE is not aligned to 2MB, ACRN won't boot. Add static check
to avoid unexpected boot failures.
If CONFIG_RELOC is enabled, CONFIG_HV_RAM_START is not directly referred
by the code, but it causes problems because ld_text_end could be relocated
to an address that is not 2MB aligned which fails mmu_modify_or_del().
Tracked-On: #4441

hv: add static check for CONFIG_HV_RAM_START and CONFIG_HV_RAM_SIZE

---

devicemodel/hw/pci/passthrough.c
hypervisor/dm/vpci/vpci.c
hypervisor/include/hw/pci.h

In order to add GVT-D support, we need pass through stolen memory and opregion memroy
to the post-launched VM. To implement this, we first reserve the GPA for stolen memory
and opregion memory through post-launched VM e820 table. Then we would build EPT mapping
between the GPA and the stolen memory and opregion memory real HPA. The last, we need to
return the GPA to post-launched VM if it wants to read the stolen memory and opregion
memory address and prevent post-launched VM to write the stolen memory and opregion memory
address register for now.
We do the GPA reserve and GPA to HPA EPT mapping in ACRN-DM and the stolen memory and
opregion memory CFG space register access emulation in ACRN-HV.

hv: vpci: pass through stolen memory and opregion memory for GVT-D

---

doc/static/acrn-custom.css

While the site is being reorganized, let's put a header on each page
letting people know.

doc: add site under construction page header

---

misc/life_mngr/life_mngr.c

Currently the life_mngr daemon has supported:
listen from the SOS shutdown command,
this patch add support listen shutdown command from RTVM.
and this life_mngr daemon can also run on SOS for listening
shutdown commond from acrn-dm(triggered by RTVM).
Tracked-On: #4446
Reviewed-by: Yuhong, Tao <yuhong.tao@intel.com>

misc:life_mngr: support S5 triggered by RTVM

---

hypervisor/dm/vpci/vmsi.c
hypervisor/dm/vpci/vmsix.c
hypervisor/dm/vpci/vpci.c
hypervisor/dm/vpci/vpci_priv.h

change vmsi_read_cfg to read_vmsi_cfg, same applies to writing
change vmsix_read_cfg to read_vmsix_cfg, same applies to writing

hv: refine read/write configuration APIs for vmsi/vmsix

---

doc/release_notes/release_notes_0.1.rst
doc/release_notes/release_notes_1.0.rst

We moved the Tools page in v1.6 (future) and this was causing RN 0.1 and 1.0 to throw errors because they referenced the Tools page. I updated the language on these pages.

Doc: Changed lines in RN 1.0 and 0.1 to correct ref issue.

---

misc/acrn-config/scenario_config/pci_dev_c.py

commit a68f655a118f707501cd0ed241f2e71554d31af3 added two extra header
include in pci_dev.c for logical_partition scenario but acrn-config did
not handle that.
This patch fix the issue.
Tracked-On: #4492

acrn-config: add missed include in pci_dev.c for logical partition

---

misc/acrn-config/launch_config/launch_cfg_gen.py
misc/acrn-config/library/launch_cfg_lib.py

If the bus number is not 0, then malloc a virtual slot for the device,
meanwhile, it should be added to PT_SLOT for the next query, otherwise
the passthru parameter would be lost in the launch script.
Tracked-On: #4494

acrn-config: fix missing passthru parameter for launch config

---

doc/develop.rst
doc/introduction/index.rst

Add ACRN Open Source Roadmap 2020 link to Intro/What is ACRN page
Add ACRN blog link to ACRN Intro page (under Roadmap)
Move ACRN Shell Commands to 'Tools' under Advanced Guides page

doc: More re-org updates; What is ACRN and Advanced Guides pages

---

hypervisor/dm/vpci/pci_pt.c
hypervisor/dm/vpci/vpci.c
hypervisor/dm/vpci/vpci_priv.h
hypervisor/dm/vpci/vsriov.c

To avoid information leakage, we need to ensure that the device is
inaccessble when it does not exist.
For SR-IOV disabled VF device, we have the following operations.
1. The configuration space accessing will get 0xFFFFFFFF as a
return value after set the device state to zombie.
2. The BAR MMIO EPT mapping are removed, the accesssing causes
EPT violation.
3. The device will be detached from IOMMU.
4. The IRQ pin and vector are released.

hv: unmap SR-IOV VF MMIO when the VF physical device is disabled

---

devicemodel/hw/pci/passthrough.c
devicemodel/include/public/vhm_ioctl_defs.h
hypervisor/arch/x86/configs/vm_config.c
hypervisor/arch/x86/guest/vm.c
hypervisor/dm/vpci/vpci.c
hypervisor/dm/vpci/vpci_priv.h
hypervisor/include/arch/x86/vm_config.h
hypervisor/include/dm/vpci.h
hypervisor/include/hw/pci.h
hypervisor/include/public/acrn_hv_defs.h

v4:
deliver IO request to DM for QUIRK PTDev when writing PCI CFG address register
v3:
refine some comments and a minor refine about acrn_assign_pcidev type MACRO definition.
v2:
1. refine the description: use term "severity" instead of "priority"
2. add get_vm_severity function to get a VM's severity
3. a minor bug fix about "the return value of read/write_pt_dev_cfg is not used"
v1:
throw the qurik part of pass through pci device to DM and keep HV clean

vPCI: throw the qurik part of pass through pci device to DM and keep HV clean

---

hypervisor/arch/x86/vtd.c

This is a WA to fix the invisible cursor issue. The TT_PASSTHROUGH
mode will not use iommu to do the address translation.
Tracked-On: #4509

hv: change GPU passthru translation mode to TT_PASSTHROUGH

---

doc/developer-guides/c_coding_guidelines.rst
doc/developer-guides/contribute_guidelines.rst
doc/developer-guides/hld/hld-security.rst
doc/developer-guides/l1tf.rst
doc/tutorials/acrn_ootb.rst
doc/tutorials/agl-vms.rst
doc/tutorials/increase-uos-disk-size.rst
doc/tutorials/kbl-nuc-sdc.rst
doc/tutorials/realtime_performance_tuning.rst
doc/tutorials/trustyACRN.rst
doc/tutorials/using_partition_mode_on_nuc.rst
doc/tutorials/using_partition_mode_on_up2.rst
doc/tutorials/using_ubuntu_as_sos.rst
misc/acrn-manager/README.rst

Fix links in documentation that have moved (e.g.,
clearlinux.org/documentation moved to docs.01.org/clearlinux/latest).

doc: fix docs with broken links

---

hypervisor/Makefile
hypervisor/arch/x86/Kconfig
hypervisor/arch/x86/boot/cpu_primary.S
hypervisor/boot/guest/vboot_wrapper.c
hypervisor/boot/multiboot.c

- need to specify the load_addr in the multiboot2 address tag. GRUB needs
it to correctly calculate the ACRN binary's load size if load_end_addr is
a non-zero value.
- multiboot2 can be enabled if hypervisor relocation is disabled.
- print the name of the boot loader. This might be helpful if the boot
loader, e.g. GRUB, inludes its version in the name string.
Tracked-On: #4441

hv: a few fixes for multiboot2 boot

---

doc/getting-started/rt_industry.rst
doc/tutorials/using_ubuntu_as_sos.rst

For some corner case; the bootloader will load fail if no space
at the end of efibootmgr bootloader; so add it for workaround.

Doc: add space at the end of efibootmgr bootloader

---

hypervisor/arch/x86/Kconfig
hypervisor/arch/x86/guest/assign.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/ioapic.c
hypervisor/arch/x86/irq.c
hypervisor/boot/acpi_base.c
hypervisor/boot/include/acpi.h
hypervisor/common/hypercall.c
hypervisor/debug/shell.c
hypervisor/dm/vioapic.c
hypervisor/dm/vpic.c
hypervisor/dm/vuart.c
hypervisor/include/arch/x86/guest/assign.h
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/arch/x86/ioapic.h
hypervisor/include/common/ptdev.h
hypervisor/include/dm/vioapic.h
hypervisor/include/dm/vpic.h
hypervisor/include/dm/vuart.h

This patchset adds support for emulating multiple vIO-APICs for SOS
on platforms with more than one IO-APIC.
Tracked-On: #4151

Support for platforms with multiple IO-APICs

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/cpu_caps.c
hypervisor/arch/x86/guest/ucode.c
hypervisor/arch/x86/guest/vcpuid.c
hypervisor/arch/x86/timer.c
hypervisor/include/arch/x86/cpuid.h

The cupid() can be replaced with cupid_subleaf, which is more clear.
Having both APIs makes reading difficult.
Tracked-On: #4526

hv: cpuid: remove cpuid()

---

misc/efi-stub/boot.c

UEFI pass option as unicode string to efi-stub. That string has
no end charactor ('\0'). Insteadly, the option has string size
and we should use the string size to decide the end of the option
string.
Tracked-On: #4520
Reviewed-by: Zide Chen <zide.chen@intel.com>

efi-stub: fix wrong bootloader name issue

---

misc/acrn-config/config_app/views.py

This commit creates the folder for hosting the temporary scenario .xml files if the folder doesn't exist to avoid the FileNotFound python exception.
Tracked-On: #4522

acrn-config: create temporary scenario file folder if it doesn't exist

---

devicemodel/hw/pci/lpc.c

previous patch fails to align SUBVID, SUBDID of igd-lpc with physical one.
this patch corrects the errors and refine the code.

dm: correct PCI configures of igd-lpc

---

hypervisor/arch/x86/guest/assign.c
hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vmcs.c
hypervisor/arch/x86/vtd.c
hypervisor/include/arch/x86/guest/vcpu.h
hypervisor/include/arch/x86/guest/vlapic.h
hypervisor/include/arch/x86/vmx.h
hypervisor/include/arch/x86/vtd.h

If VT-d Posted interrupts are supported by the platform , hypervisor shall be able to use it to deliver interrupts directly to partitions
Enable VT-d posted interrupts for eligible platforms such as ANL, if vt-d posted interrupt is detected ,pt devices for that vm will use vt-d posted interrupt to deliver interrupts to guest without vm-exits, which can improve performance for the pt devices.
This is only patch series No.1 to enable VT-d support,  more patch series will be posted soon.
[External_System_ID] ACRN-6085

Add support for VT-d Posted Interrupts (series #1)

---

hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vmtrr.c
hypervisor/arch/x86/timer.c
hypervisor/common/hv_main.c
hypervisor/common/sched_bvt.c
hypervisor/dm/vpci/pci_pt.c
hypervisor/dm/vpci/vdev.c
hypervisor/dm/vpci/vmsi.c
hypervisor/dm/vpci/vmsix.c
hypervisor/dm/vpci/vpci.c
hypervisor/dm/vpci/vpci_priv.h
hypervisor/dm/vpci/vsriov.c
hypervisor/dm/vpic.c
hypervisor/include/arch/x86/guest/vlapic.h
hypervisor/include/arch/x86/guest/vmtrr.h
hypervisor/include/dm/vpci.h
hypervisor/include/dm/vpic.h
hypervisor/include/lib/list.h

v3:
fix some MISRA-C complaints.
v2:
minor refine about container_of.
v1:
Use contain_of to cast a member of a structure out to the containing structure instead of declaring the structure pointer in the  containing structure.

Refine: use contain_of to cast a member of a structure out to the containing structure.

---

hypervisor/arch/x86/guest/vlapic.c

Since vcpu if remove from vlapic, we could not dereference it directly.

hv: vlapic: minor fix about dereference vcpu from vlapic

---

hypervisor/acpi_parser/dmar_parse.c
hypervisor/arch/x86/vtd.c
hypervisor/boot/include/acpi.h
hypervisor/hw/pci.c
hypervisor/include/arch/x86/vtd.h

Clean-up some codes.
hypervisor/acpi_parser/dmar_parse.c:
1.removed multiple returns
hypervisor/arch/x86/vtd.c:
1.corrected the return type of some functions,
2.simplified the logic of dmar_wait_completion() and iommu_read64(),
3.renamed some static functions
4.remove some code branches about iommu_domain.is_host and iommu_domain.is_tt_ept
since their values are determined
/hypervisor/include/arch/x86/vtd.h
1.removed the "is_host" and "is_tt_ept" members of struct iommu_domain
since their values are always determined
hypervisor/hw/pci.c
1.renamed some data structures to make them more understandable

Clean-up some codes

---

misc/acrn-config/library/scenario_cfg_lib.py

size and size_hpa2 can be greater than 2GB for Pre-Launched VMs.
Tracked-On: #4565

acrn-config: Limit check on Pre-Launched VM RAM size

---

doc/getting-started/acrn_quick_setup.sh
doc/getting-started/rt_industry.rst
doc/tutorials/using_windows_as_uos.rst

- Update quick setup script to support whl board.
- Change board to WHL NUC.
- Change the Service VM disk to NVMe.
- Update CL version to 32680 and ACRN tags info.

doc: update industry gsg to v1.6 release

---

hypervisor/Makefile
hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/e820.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/page.c
hypervisor/boot/guest/direct_boot.c
hypervisor/include/arch/x86/e820.h
hypervisor/include/arch/x86/page.h
hypervisor/include/arch/x86/vm_config.h

As ACRN prepares to support servers with large amounts of memory
current logic to allocate space for 4K pages of EPT at compile time
will increase the size of .bss section of ACRN binary.
Bootloaders could run into a situation where they cannot
find enough contiguous space to load ACRN binary under 4GB,
which is typically heavily fragmented with E820 types Reserved,
ACPI data, 32-bit PCI hole etc.
This patch does the following
1) Works only for "direct" mode of vboot
2) reserves space for 4K pages of EPT, after boot by parsing
platform E820 table, for all types of VMs.
Size comparison:
w/o patch
Size of DRAM            Size of .bss
48 GB                   0xe1bbc98 (~226 MB)
128 GB                  0x222abc98 (~548 MB)
w/ patch
Size of DRAM            Size of .bss
48 GB …

hv: Reserve space for VMs'  EPT 4k pages after boot

---

misc/acrn-config/board_config/misc_cfg_h.py
misc/acrn-config/board_config/new_board_kconfig.py
misc/acrn-config/target/misc.py
misc/acrn-config/xmls/board-xmls/apl-mrb.xml
misc/acrn-config/xmls/board-xmls/apl-up2-n3350.xml
misc/acrn-config/xmls/board-xmls/apl-up2.xml
misc/acrn-config/xmls/board-xmls/nuc6cayh.xml
misc/acrn-config/xmls/board-xmls/nuc7i7dnb.xml
misc/acrn-config/xmls/board-xmls/whl-ipc-i5.xml
misc/acrn-config/xmls/board-xmls/whl-ipc-i7.xml

- find 64-bit mmio for HI_MMIO_START/HI_MMIO_END
- update IOMEM_INFO of native board config xml
- dump iomem info from /proc/iomem
Tracked-On: #4569

acrn-config: find 64-bit mmio for HI_MMIO_START/HI_MMIO_END

---

hypervisor/arch/x86/vtd.c

In dmar_issue_qi_request, currently use a global var qi_status, which could
cause potential issue when concurrent call to dmar_issue_qi_request for different
DMAR units.
Use local var instead.
Tracked-On: #4535

hv: vtd: use local var instead of global var

---

hypervisor/boot/include/boot.h
hypervisor/boot/multiboot2.c

The patch fixed a few misra violations for multiboot2.c;
Tracked-On: #4419

HV: misra fix for multiboot2.c

---

misc/acrn-config/board_config/pci_devices_h.py
misc/acrn-config/library/board_cfg_lib.py
misc/acrn-config/library/common.py

This patch does the following
1) Removes the limitation on BAR size for 1 GB
2) Align the BAR address to the BAR size
Tracked-On: #4586

acrn-config: Fixes for BAR remapping logic

---

doc/index.rst

Adding a big box for the glossary disturbed the home page layout and is
overkill for this one document. Adding the glossary to the left
navigation menu is sufficient.

doc: remove "Glossary" icon box on home page

---

doc/asa.rst

Add headings to organize security advisory doc by release to make it a
bit easier to read.

doc: organize security advisory doc

---

hypervisor/arch/x86/guest/vm.c
hypervisor/dm/vpci/vpci.c
hypervisor/include/dm/vpci.h

Conceptually, the devices unregistration sequence of the shutdown process should be
opposite to create.

hv: vm: refine the devices unregistration sequence of vm shutdown

---

hypervisor/dm/vpci/vdev.c

Refine why we set the base_gpa to zero for a vBAR.

hv: vpci: detail comment for pci_vdev_update_vbar_base

---

doc/static/acrn-custom.css

Add styles for multi-column display, and for auto-numbered instruction
steps used in some other projects.
Also updating the used page width to 1100px following experience
improvements noted on other sites.  Pages are hard to read when
displayed full-screen on really wide monitors.

doc: update custom CSS with additional styles

---

doc/scripts/publish-robots.txt

Developers using google search can accidentally find older versions of
documents and lead to confusion.  While we do maintain previous release
documentation on the site, we should have a preference for the latest
documentation when using external search engines.  (Note the on-site
search always returns version-specific results.)

doc: update robots.txt exclusion list

---

hypervisor/arch/x86/guest/virq.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/include/arch/x86/guest/vlapic.h

Inject pending exception prior pending interrupt to complete the previous instruction.

hv: virq: refine pending event inject sequence

---

hypervisor/arch/x86/guest/vmcs.c

The VMCS field is an embedded array for a vCPU. So there's no need to check for
NULL before use.
Tracked-On: #3813

hv: vmcs: remove vmcs field check for a vcpu

---

hypervisor/arch/x86/configs/apl-mrb/misc_cfg.h
hypervisor/arch/x86/configs/apl-up2/misc_cfg.h
hypervisor/arch/x86/configs/dnv-cb2/misc_cfg.h
hypervisor/arch/x86/configs/generic/misc_cfg.h
hypervisor/arch/x86/configs/nuc6cayh/misc_cfg.h
hypervisor/arch/x86/configs/nuc7i7dnb/misc_cfg.h
hypervisor/arch/x86/configs/whl-ipc-i5/misc_cfg.h
hypervisor/arch/x86/mmu.c
hypervisor/arch/x86/page.c
misc/acrn-config/board_config/misc_cfg_h.py
misc/acrn-config/library/common.py

Handle PCI devices with 64-bit MMIO BARs and BAR Base addresses > 4G.
This patch series builds hypervisor page tables for 64-bit MMIO BARs and facilitates ACRN access MMIO for MSI-x Emulation.
Tracked-On: #4586

Ww12 64 bit mmio upstream

---

hypervisor/arch/x86/guest/virq.c
hypervisor/include/arch/x86/irq.h

Waag will send NMIs to all its cores during reboot. But currently,
NMI cannot be injected to vcpu which is in HLT state.
To fix the problem, need to wakeup target vcpu, and inject NMI through
interrupt-window.
Tracked-On: #4620

hv: fix for waag 2 core reboot issue

---

misc/acrn-config/launch_config/com.py
misc/acrn-config/launch_config/pt.py
misc/acrn-config/library/launch_cfg_lib.py
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/industry_launch_1uos_hardrt.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/industry_launch_1uos_vxworks.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/industry_launch_1uos_waag.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/industry_launch_2uos.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/sdc_launch_1uos_laag.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/sdc_launch_1uos_zephyr.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/industry_launch_1uos_hardrt.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/industry_launch_1uos_vxworks.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/industry_launch_1uos_waag.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/industry_launch_2uos.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/sdc_launch_1uos_laag.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/sdc_launch_1uos_zephyr.xml

Modify launch config tool to support passthroug GVT for WaaG by default.
Tracked-On: #4625

acrn-config: support passthroug GVT for WaaG by default

---

hypervisor/Makefile
hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/guest/assign.c
hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/guest/vmcs.c
hypervisor/arch/x86/irq.c
hypervisor/arch/x86/notify.c
hypervisor/arch/x86/platform_caps.c
hypervisor/arch/x86/vtd.c
hypervisor/include/arch/x86/guest/vcpu.h
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/arch/x86/irq.h
hypervisor/include/arch/x86/per_cpu.h
hypervisor/include/arch/x86/platform_caps.h
hypervisor/include/arch/x86/vtd.h

If VT-d Posted interrupts are supported by the platform , hypervisor shall be able to use it to deliver interrupts directly to partitions
Enable VT-d posted interrupts for eligible platforms such as ANL, if vt-d posted interrupt is detected and vm-config is set to use vt-d posted interrupt, pt devices for that vm will use vt-d posted interrupt to deliver interrupts to guest without vm-exits, which can improve performance for the pt devices.
[External_System_ID] ACRN-6085

HV: add support for VT-d Posted Interrupts (series #2)

---

hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/include/arch/x86/guest/vlapic.h

Currently vlapic_build_id() uses vcpu_id to retrieve the lapic_id
per_cpu variable:
vlapic_id = per_cpu(lapic_id, vcpu->vcpu_id);
SOS vcpu_id may not equal to pcpu_id, and in that case it runs into
problems. For example, if any pre-launched VMs are launched on PCPUs
whose IDs are smaller than any PCPU IDs that are used by SOS.
This patch fixes the issue and simplify the code to create or get
vapic_id by:
- assign vapic_id in create_vlapic(), which now takes pcpu_id as input
argument, and save it in the new field: vlapic->vapic_id, which will
never be changed.
- simplify vlapic_get_apicid() by returning te saved vapid_id directly.
- remove vlapic_build_id().
- vlapic_init() is only called once, merge it into vlapic_create().
Tracked-On: #4268 …

hv: fix SOS vapic_id assignment issue

---

hypervisor/debug/dump.c

now the actual address does not match with the MAP file
if enable CONFIG_RELO when there are some exceptions,
this patch print the delta between the actual load addess
and CONFIG_HV_RAM_START.
Tracked-On: #4144

hv:print relocation delta

---

hypervisor/arch/x86/guest/guest_memory.c

Align the implementation to SDM Vol.3 4.1.1.
Also this patch fixed a bug that doesn't check paging status first
in some cpu mode.
Tracked-On: #4628

hv: guest: fix bug in get_vcpu_paging_mode

---

doc/reference/hardware.rst

ACRN assumes certain state for the PCI devices w.r.t. resources assigned to them
before the platform BIOS hands control over to itself.
When the same BIOS is used with native OS boot, there should not be a need for
native kernel to re-program device BARs or bridge windows for bridge devices.

doc: Known Limitation regarding PCI devices and resources assignment

---

hypervisor/arch/x86/guest/ept.c
hypervisor/arch/x86/guest/virtual_cr.c
hypervisor/arch/x86/vtd.c
hypervisor/include/arch/x86/pgtable.h
hypervisor/include/arch/x86/vtd.h

Due to the fact that i915 iommu doesn't support snoop, hence it can't
access memory when the SNOOP bit of Secondary Level page PTE (SL-PTE)
is set, this will cause many undefined issues such as invisible cursor
in WaaG etc.
And further, ACRN disables Snoop Control in VT-d DMAR engines for simplifing
the implementation. Also, since the snoop behavior of PCIE transactions
can be controlled by guest drivers, some devices may take the advantage
of the NO_SNOOP_ATTRIBUTE of PCIE transactions for better performance
when snoop is not needed.
Tracked-On: #4509

disable iommu snoop and clean related code

---

hypervisor/common/hypercall.c
hypervisor/include/public/acrn_hv_defs.h

Hypervisor reports VM configuration information to SOS which can be used to
dynamically allocate VCPU affinity.
Servise OS can get the vm_configs in this order:
1. call platform_info HC (set vm_configs_addr with 0) to get max_vms and
vm_config_entry_size.
2. allocate memory for acrn_vm_config array based on the number of VMs
and entry size that just got in step 1.
3. call platform_info HC again to collect VM configurations.
Tracked-On: #4616

hv: provide vm_config information in get_platform_info hypercall

---

hypervisor/Makefile
hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/guest/assign.c
hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/guest/vmcs.c
hypervisor/arch/x86/irq.c
hypervisor/arch/x86/notify.c
hypervisor/arch/x86/platform_caps.c
hypervisor/arch/x86/vtd.c
hypervisor/include/arch/x86/guest/vcpu.h
hypervisor/include/arch/x86/guest/vlapic.h
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/arch/x86/irq.h
hypervisor/include/arch/x86/per_cpu.h
hypervisor/include/arch/x86/platform_caps.h
hypervisor/include/arch/x86/vmx.h
hypervisor/include/arch/x86/vtd.h

Backporting VT-d Posted Interrupts patches from master to release_1.6
[External_System_ID] ACRN-6085

HV: add support for VT-d Posted Interrupts (backporting)

---

hypervisor/arch/x86/init.c

This patch wrapps a common function to initialize physical
CPU for the second phase to reduce redundant code.

hv: wrap a function to initialize pCPU for second phase

---

misc/tools/acrn-crashlog/acrnprobe/Makefile
misc/tools/acrn-crashlog/usercrash/Makefile

main.c is compiled while version.h being generated. This will
result following error:
| main.c: In function 'main':
| main.c:95:5: error: 'AP_MAJOR_VERSION' undeclared (first use in this function)
|    95 |     AP_MAJOR_VERSION, AP_MINOR_VERSION,
|       |     ^~~~~~~~~~~~~~~~
| main.c:95:5: note: each undeclared identifier is reported only once for each function it appears in
| main.c:95:23: error: 'AP_MINOR_VERSION' undeclared (first use in this function)
|    95 |     AP_MAJOR_VERSION, AP_MINOR_VERSION,
|       |                       ^~~~~~~~~~~~~~~~
| main.c:96:5: error: 'AP_BUILD_VERSION' undeclared (first use in this function)
|    96 |     AP_BUILD_VERSION, AP_BUILD_USER,
|       |     ^~~~~~~~~~~~~~~~
| main.c:96:23: error: 'AP_BUILD_USER' undeclared (first use in this function) …

acrnprobe: avoid race condition

---

hypervisor/arch/x86/guest/pm.c
hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/guest/vm_reset.c
hypervisor/common/hypercall.c
hypervisor/include/arch/x86/guest/vcpu.h
hypervisor/include/arch/x86/guest/vm.h

add pre-condition for vm & cpu state transition instead of
check state before state transition.
Tracked-On: #4320

vm vcpu state cleanup

---

misc/life_mngr/life_mngr.c

1) fix a bug,resend shutdown cmd only send one character
2) move out accept routine from while loop, let this thread
can read data from acrn-dm continuously.
Tracked-On: #4446
Reviewed-by: Yuhong Tao <yuhong.tao@intel.com>
Reviewed-by: Wang, Yu1 <yu1.wang@intel.com>

life_mngr:fix resend shutdown cmd fail

---

doc/developer-guides/doc_guidelines.rst

Update the doc writing guidelines to include some new capabilities
(multi-column display, numbered instruction steps) and add more
information about writing tables.

doc: update doc guidelines

---

hypervisor/arch/x86/guest/ve820.c

The current logic puts hpa2 above GPA 4G always, which is incorrect. Need
to set gpa start of hpa2 right after hpa1 when hpa1 size is less then 2G;
Tracked-On: #4458

HV: fix wrong gpa start of hpa2 in ve820.c

---

hypervisor/arch/x86/Kconfig
hypervisor/arch/x86/configs/platform_acpi_info.h

On most board the MCFG base is set to 0xe0000000, so modify this value in
platform_acpi_info.h for generic boards;
The description of ACPI_PARSE_ENABLED is modified also to match its usage.
Tracked-On: #4157

HV: set default MCFG base for generic board

---

hypervisor/arch/x86/guest/virq.c

Wake up vCPUs that are blocked upon interrupts from vPIC.
Tracked-On: #4664

hv: Wake up vCPU for interrupts from vPIC

---

misc/tools/acrn-crashlog/acrnprobe/loop.c

gcc in latest clearlinux enabled the pointer-sign warning as
default. This breaks the acrn-crashlog build.
Make acrn-crashlog build issue fixed by convert to correct
pointer type.
Tracked-On: #4636

crashlog: fix build issue under latest clearlinux

---

misc/acrn-config/board_config/pci_devices_h.py
misc/acrn-config/library/board_cfg_lib.py
misc/acrn-config/scenario_config/pci_dev_c.py

Pre-Launched VMs need the vbar_base values pre-populated
for pass-thru PCI devices.
This patch moves the pci parser logic from board_cfg_gen to library
so that scenario_cfg_gen scripts can use pci parser routines while
generating pci_dev file logical partition scenario.
Tracked-On: #4666

acrn-config: Generate info in pci_dev file for Pre-Launched VMs

---

doc/conf.py
doc/scripts/requirements.txt

The sphinx-tabs extension let's us create a document that can
dynamically display alternate material based on clicking a tab, as used
in the Zephyr getting started guide:
https://docs.zephyrproject.org/latest/getting_started/index.html

doc: add sphinx-tabs extension

---

hypervisor/arch/x86/configs/vacpi.c
hypervisor/boot/include/acpi.h
hypervisor/dm/vpci/vpci.c
hypervisor/include/dm/vacpi.h

v2:
1. add ioapic madt table
2. re-define acpi_table_fadt structure to reduce some code
v1:
1. We need to add S5 support for pre-launched VM which needs FADT table.
2. We need to support pre-launched VM PCIe external CFG space ECAM access which needs MCFG
Tracked-On: #4623

vacpi: complete ACPI table to describe resource for pre-launched VM

---

misc/acrn-config/target/board_parser.py

Enhance and fix some typos in the text that gets printed out from the
board_parser.py script.

acrn-config: fix typos and text in board_parser.py tool

---

hypervisor/include/arch/x86/vm_config.h
hypervisor/scenarios/hybrid/vm_configurations.h
hypervisor/scenarios/industry/vm_configurations.h
hypervisor/scenarios/sdc/vm_configurations.h
misc/acrn-config/scenario_config/vm_configurations_h.py

The parameter of "idle=halt" for SOS cmdline is only needed when cpu sharing is enabled, otherwise it will impact SOS power.
Tracked-On: #4329

HV: refine usage of idle=halt in sos cmdline

---

hypervisor/arch/x86/ept.c
hypervisor/common/hypercall.c
hypervisor/include/arch/x86/mmu.h

This patch set is to back port security fix on master branch to apl_sdc_stable branch for ACRN GP2.0 release.

[GP2.0] security port to apl_sdc_stable branch

---

Makefile
hypervisor/scripts/makefile/cfg_update.mk
hypervisor/scripts/makefile/kconfig.mk

SCENARIO XML file has included RELEASE or DEBUG info already, so if RELEASE is not specified in make command, Makefile should not override RELEASE info in SCENARIO XML. If RELEASE is specified in make command, then RELEASE info in SCENARIO XML could be overridden by make command.
The patch also fixed a issue that get correct board defconfig when build
hypervisor from TARGET_DIR;
Tracked-On: #4688

Makefile: do not override RELEASE when build with XML

---

doc/tutorials/rtvm_performance_tips.rst

Fix a couple of typos that sneaked in in the 'rtvm_performance_tips.rst'
document.

doc: fix a coupe of typos in rtvm_performance_tips.rst doc

---

hypervisor/arch/x86/guest/ept.c
hypervisor/arch/x86/guest/vmcs.c
hypervisor/arch/x86/guest/vmexit.c
hypervisor/arch/x86/page.c
hypervisor/include/arch/x86/guest/ept.h
hypervisor/include/arch/x86/page.h
hypervisor/include/arch/x86/pgtable.h

Also clear all accessed bit in pagetables when the VM do wbinvd. Then
the next wbinvd will benefit from it.
Tracked-On: #4703

hv: Enable accessed bit in EPT paging

---

devicemodel/core/main.c
devicemodel/core/vmmapi.c
devicemodel/include/vmmapi.h

commit 71bdc27a0f9 ("acrn-dm: implement cpu_affinity command line argument")
doesn't use correct name.
Tracked-On: #4616

acrn-dm: change command option name from "pcpu_list" to "cpu_affinity"

---

devicemodel/hw/pci/passthrough.c
devicemodel/include/pcireg.h

EHL graphics data stolen memory(DSM) info has diff with KBL/WHL, which includes two parts:
(1) DSM register location in pci config: on KBL/WHL, the register locates on 0X5C, while on EHL, the register locates on 0xC0.
(2) DSM address length: On KBL/WHL,
DSM addr has 32 bits, while on EHL,DSM addr has 64 bits.
Here, refine graphics data stolen memory passthru to enable GVT-d on EHL platforms.

dm:refine graphics data stolen memory passthru for EHL platform

---

devicemodel/hw/pci/xhci.c

From xHCI spec 4.5.3.2, the only command that software is
allowed to issue for the slot in disabled state is the Enable
Slot Command. Drop other commands in command handle function.
Tracked-On: #4711
Signed-off-by: Liu Long <longliu@intel.com>

DM USB: xHCI: Drop commands if the slot is disabled

---

hypervisor/boot/acpi_base.c
hypervisor/dm/vioapic.c
hypervisor/include/arch/x86/apicreg.h
hypervisor/include/dm/vioapic.h

1. minor refine about ioapic madt parse
2. minor refine about vioapic_init

Vioapic: two minor refines

---

devicemodel/samples/nuc/launch_xenomai.sh

Passthroughed devices won't be restored back to SOS once launch
script exits by default. However you could revert this behavior
by specifying '-r' parameter if you want.
Tracked-On: #4514

sample: don't restore passthrough devices on exit by default

---

devicemodel/hw/pci/passthrough.c

Currently the DM will return the passthrough device to SOS when the DM
needs to be terminated. But the device is not reset. In such case it
will cause the garbage display issue when the GPU passthrough device
is used.
Tracked-On: #4719

ACRN/DM: Reset the passthrough device to fix garbage display issue

---

hypervisor/arch/x86/guest/guest_memory.c

Either INVALID_GPA or NULL returned from local_gpa2hpa means the
page walk failure. But current code only take care of NULL and
leave INVALID_GPA not detected.
It could trigger ACRN crash in root mode when guest have a invalid
gva.
We add INVALID_GPA check as well.

local_gpa2hpa: INVALID_GPA also means failure of address conversion

---

hypervisor/arch/x86/boot/cpu_primary.S
hypervisor/bsp/ld/link_ram.ld.in

The original stack used in CPU booting is: ld_bss_end + 4KB;
which could be out of the RAM size limit defined in link_ram file.
So add a specific stack space in link_ram file, and used in
CPU booting.
Tracked-On: #4738
Reviewed by: Yin Fengwei <fengwei.yin@intel.com>

HV: add a specific stack space used in CPU booting

---

devicemodel/core/vmmapi.c

- re-arange the code to make static code analysis tool happy.
- If no valid conversion could be performed, a zero value is returned
(0L) from strtol(), so add a sanity check "isdigit(cp[0])" to ensure
that it won't unexpectedly parse CPU 0 if the string starts or ends
with the valid delimiters ',' or '-', for example:
-- cpu_affinity 1,
-- cpu_affinity ,1
Tracked-On: #4616

acrn-dm: fix corner cases in acrn_parse_cpu_affinity()

---

hypervisor/arch/x86/configs/vm_config.c
hypervisor/arch/x86/guest/vm.c
hypervisor/common/hypercall.c
hypervisor/include/arch/x86/vm_config.h

The statically configured vm_configs[].cpu_affinity_bitmap should remain
intact during the life cycle of the SOS, otherwise user can't destroy
and create the same VM with different CPU affinity. For example:
- Initially vm_configs[1].cpu_affinity_bitmap is set to 0xF: pCPU 0/1/2/3.
- VM1 is created on pCPU1 and pCPU2 and vm_configs[1].cpu_affinity_bitmap
is overwritten as 0x6.
- VM1 is destroyed.
- Now VM1 can't be launched again on pCPU0 or pCPU3.
This patch fixes this by saving the static VM configuration before the
create_vm hypercall and restore it when the post-launched VM is shutting
down.
Tracked-On: #4616

hv: don't overwrite the statically configured vm_configs[] in hypercall

---

doc/tutorials/up2.rst

The UP2 EFI firmware is a bit capricious and does not consistantly keep the
boot order after adding one using `efibootmgr`. There is no magic recipe (or
known reliable sequence) and hence we add a note warning the user that this
can happen, and when it does the only solution is to try modifying some more
the list of boot entries (inc. re-ordering them).

doc: add note about capricious UP2 EFI firmware

---

misc/acrn-config/hv_config/board_defconfig.py
misc/acrn-config/xmls/config-xmls/nuc6cayh/industry_launch_6uos.xml
misc/acrn-config/xmls/config-xmls/nuc7i7dnb/industry_launch_6uox.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/industry_launch_6uox.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/industry_launch_6uox.xml

add 6 clearlinux UOSes for launch config xmls.
fix macros log level for board defconfig.
Tracked-On: #4641

acrn-config: add clearlinux UOS for launch config xmls

---

doc/developer-guides/hld/virtio-gpio.rst
doc/developer-guides/hld/virtio-i2c.rst
doc/release_notes/release_notes_1.5.rst
doc/tutorials/enable_s5.rst

Convert UTF-8 characters (typically pasted from Word for smart quotes
and such) into equivalent ASCII characters.

doc: remove stray UTF-8 characters

---

hypervisor/arch/x86/configs/vacpi.c
hypervisor/arch/x86/guest/guest_memory.c
hypervisor/common/vm_load.c

For return value of local_gpa2hpa, either INVALID_HPA or NULL
means the EPT walking failure. Current code only take care of
NULL return and leave INVALID_HPA as correct case.
In some cases (if guest page table is filled with invalid memory
address), it could crash ACRN from guest.
Add INVALID_HPA return check as well.
Also add @pre assumptions for some gpa2hpa usages.
Tracked-On: #4730

gpa2hva: add INVAVLID_HPA return value check

---

devicemodel/core/main.c
doc/user-guides/acrn-dm-parameters.rst

Update the documentation listing and describing all `acrn-dm` parameters as it
has gone out of sync with the actual implementation. Some parameters are missing
and others are now obsolete.
Tracked-On: #4732

update `acrn-dm` parameters documentation

---

hypervisor/arch/x86/Kconfig
hypervisor/arch/x86/cpu.c

#AC should be normally enabled for slpitlock detection, however,
community developers may want to run ACRN on buggy system.
In this case, CONFIG_ENFORCE_TURNOFF_AC can be used to turn off the
#AC, to let the guest run without #AC.
Tracked-On: #4765

HV: Config Splitlock Detection to be disable

---

doc/tutorials/using_celadon_as_uos.rst

Add a note to the "Run Celadon as the User VM" tutorial to indicate a serial
port connection to the platform (or change of the default config) may be needed
if the user uses a scenario other than SDC (the default one in the doc).
Tracked-On: #4554

doc: add note to the Celadon User VM tutorial

---

doc/tutorials/using_zephyr_as_uos.rst

Update the "Run Zephyr as the User VM" document to add a note indicating a
serial port connection to the platform is needed to see the Zephyr output.
Tracked-On: #4553

doc: update Zephyr document to indicate a serial port is needed

---

hypervisor/arch/x86/Kconfig
hypervisor/arch/x86/configs/vm_config.c
hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/rdt.c
hypervisor/include/arch/x86/rdt.h

These commits add CDP support to ACRN and do some RDT code refinement.
CDP is an extension of CAT. It enables isolation and separate prioritization of
code and data fetches to the L2 or L3 cache in a software configurable manner,
depending on hardware support.
The patches are verified on EHL only for now, because it's the only platform with CDP capability we have.
Tracked-On: #4604

add ACRN CDP support

---

hypervisor/arch/x86/configs/vm_config.c
hypervisor/arch/x86/guest/vm.c
hypervisor/common/hypercall.c
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/arch/x86/vm_config.h
hypervisor/scenarios/hybrid/vm_configurations.c
hypervisor/scenarios/industry/vm_configurations.c
hypervisor/scenarios/logical_partition/vm_configurations.c
hypervisor/scenarios/sdc/vm_configurations.c
misc/acrn-config/scenario_config/vm_configurations_c.py

This is to have separate cpu_affinity in both acrn_vm and vm_config, so that the configured affinity in vm_config will never be overwritten by acrn-dm. 
- add vm->hw.cpu_affinity
- change vmn_config->cpu_affinity_bitmap to vm_config->cpu_affinity
- removed vm_config->vcpu_num

hv: add cpu_affinity to struct acrn_vm

---

hypervisor/arch/x86/configs/apl-mrb/misc_cfg.h
hypervisor/arch/x86/configs/apl-up2/misc_cfg.h
hypervisor/arch/x86/configs/dnv-cb2/misc_cfg.h
hypervisor/arch/x86/configs/generic/misc_cfg.h
hypervisor/arch/x86/configs/nuc6cayh/misc_cfg.h
hypervisor/arch/x86/configs/nuc7i7dnb/misc_cfg.h
hypervisor/arch/x86/configs/whl-ipc-i5/misc_cfg.h
misc/acrn-config/xmls/config-xmls/apl-mrb/hybrid.xml
misc/acrn-config/xmls/config-xmls/apl-mrb/industry.xml
misc/acrn-config/xmls/config-xmls/apl-mrb/sdc.xml
misc/acrn-config/xmls/config-xmls/apl-up2/hybrid.xml
misc/acrn-config/xmls/config-xmls/apl-up2/industry.xml
misc/acrn-config/xmls/config-xmls/apl-up2/sdc.xml
misc/acrn-config/xmls/config-xmls/nuc6cayh/hybrid.xml
misc/acrn-config/xmls/config-xmls/nuc6cayh/industry.xml
misc/acrn-config/xmls/config-xmls/nuc6cayh/sdc.xml
misc/acrn-config/xmls/config-xmls/nuc7i7dnb/hybrid.xml
misc/acrn-config/xmls/config-xmls/nuc7i7dnb/industry.xml
misc/acrn-config/xmls/config-xmls/nuc7i7dnb/sdc.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/hybrid.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/industry.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/sdc.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/hybrid.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/industry.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/sdc.xml
misc/efi-stub/boot.c
misc/efi-stub/clearlinux/acrn.conf
misc/efi-stub/efilinux.h
misc/efi-stub/malloc.c

Currently in most boards, hvlog and ramoops buffers are hardcoded at SOS GPA near 512MB, this could be conflicted with the relocated hypervisor image.

hv/acrn-config: relocate HV to addr 256MB+ and hardcode hvlog under 256MB

---

hypervisor/arch/x86/guest/assign.c
hypervisor/dm/vpci/pci_pt.c
hypervisor/dm/vpci/vhostbridge.c
hypervisor/dm/vpci/vmsi.c
hypervisor/dm/vpci/vmsix.c
hypervisor/dm/vpci/vpci.c
hypervisor/dm/vpci/vpci_bridge.c
hypervisor/dm/vpci/vpci_priv.h
hypervisor/dm/vpci/vsriov.c
hypervisor/include/arch/x86/guest/assign.h
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/dm/vpci.h

v3:
Split the patch v2 [1/3] into three small patches and detial the comment.
v2:
refine the patch [1/3] comments
Li Fei1 (5):
hv: vpci: minor refine the vdev ownership data structure
hv: vpci: remove is_own_device()
hv: vpci: refine vpci deinit
hv: vpci: remove vpci->vm not equal to null pre-condition
hv: ptdev: refine look up MSI ptirq entry

vpci: some minor refine

---

devicemodel/core/monitor.c
misc/acrn-manager/README.rst
misc/acrn-manager/acrn_mngr.h
misc/acrn-manager/acrn_vm_ops.c
misc/acrn-manager/acrnctl.c

The 'pause/continue' acrnctl cmd is never used and their action are not
defined for ACRN VMs. Should be removed.

Acrnctl: Clean up pause/continue cmd

---

hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vm.c
hypervisor/include/arch/x86/guest/vcpu.h

RTVM (with lapic PT) boots hang when maxcpus is
assigned a value less than the CPU number configured
in hypervisor.
In this case, vlapic_state(per VM) is left in TRANSITION
state after BSP boot, which blocks interupts to be injected
to this UOS.
Tracked-On: #4803
Reviewed-by: Li, Fei <fei1.li@intel.com>

hv:fix rtvm hang with maxcpus=0/1 in bootargs

---

doc/developer-guides/hld/hv-cpu-virt.rst
doc/tutorials/cpu_sharing.rst

- changed the term from "vCPU affinity" to "CPU affinity"
- changed cpu_affinity_bitmap to cpu_affinity in struct acrn_vm_config
- misc fixes

doc: update cpu affinity related docs

---

misc/acrn-config/scenario_config/scenario_cfg_gen.py

With current acrn-config code, there would be no pci_dev.c generated
if no PCI devices were selected. This would cause a bug for logical_partition
scenario because of an old pci_dev.c is already in the folder and involved
for compiling. The configure tool should override the pci_dev.c, in this case,
to avoid building error.
Tracked-On; #4813

acrn-config: generate pci_dev.c file for logical partition

---

misc/acrn-config/library/scenario_cfg_lib.py
misc/acrn-config/scenario_config/scenario_cfg_gen.py
misc/acrn-config/scenario_config/scenario_item.py
misc/acrn-config/scenario_config/vm_configurations_c.py
misc/acrn-config/scenario_config/vm_configurations_h.py
misc/acrn-config/xmls/config-xmls/apl-mrb/hybrid.xml
misc/acrn-config/xmls/config-xmls/apl-mrb/logical_partition.xml
misc/acrn-config/xmls/config-xmls/apl-up2-n3350/logical_partition.xml
misc/acrn-config/xmls/config-xmls/apl-up2/hybrid.xml
misc/acrn-config/xmls/config-xmls/apl-up2/logical_partition.xml
misc/acrn-config/xmls/config-xmls/ehl-crb-b/hybrid.xml
misc/acrn-config/xmls/config-xmls/ehl-crb-b/logical_partition.xml
misc/acrn-config/xmls/config-xmls/generic/hybrid.xml
misc/acrn-config/xmls/config-xmls/generic/logical_partition.xml
misc/acrn-config/xmls/config-xmls/nuc6cayh/hybrid.xml
misc/acrn-config/xmls/config-xmls/nuc6cayh/logical_partition.xml
misc/acrn-config/xmls/config-xmls/nuc7i7dnb/hybrid.xml
misc/acrn-config/xmls/config-xmls/nuc7i7dnb/logical_partition.xml
misc/acrn-config/xmls/config-xmls/template/PRE_STD_VM.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/hybrid.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/logical_partition.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/hybrid.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/logical_partition.xml

- generate console=ttyS0 for PRE Launched VM
- remove rootfs item from PRE Launched VM
- remove configurable="0" for hybrid scenario config
Tracked-On: #4808

acrn-config: write direct rootfs/console in OS bootargs instead of select them from UI optional items

---

hypervisor/arch/x86/guest/assign.c
hypervisor/common/ptdev.c
hypervisor/include/common/ptdev.h
hypervisor/include/lib/hash.h
hypervisor/include/lib/list.h

Now searching in ACRN is done by walk each element in an array one by one. If the array
is big, the searching is slow. In order to improve this situation, Hashing was introduced
to ACRN. This serial is an example to use Hashing to speed up PTIRQ entry searching.
Acked-by: Eddie Dong<eddie.dong@Intel.com>

lib: introduce Hashing to speed up searching

---

doc/developer-guides/hld/hv-cpu-virt.rst
hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vm.c
hypervisor/common/hv_main.c
hypervisor/common/hypercall.c
hypervisor/debug/shell.c
hypervisor/include/arch/x86/guest/vcpu.h

-- remove VCPU_PAUSED and resume_vcpu
-- remove vcpu->prev_state in vcpu structure
-- rename pause_vcpu to zombie_vcpu
Tracked-On: #4320

hv:cleanup vcpu state

---

Makefile
devicemodel/Makefile
hypervisor/Makefile
hypervisor/debug/Makefile
hypervisor/release/Makefile
misc/efi-stub/Makefile

1. remove 'clean' to avoid each time rebuild whole ACRN-HV/DM
2. correct some dependency to avoid unnecessary rebuilding
Tracked-On: #2412

Makefile: avoid 'clean' each time building

---

hypervisor/arch/x86/guest/ept.c
hypervisor/arch/x86/guest/virq.c
hypervisor/arch/x86/guest/vmexit.c
hypervisor/include/arch/x86/guest/vcpu.h

Invalidate cache by scanning and flushing the whole guest memory is
inefficient which might cause long execution time for WBINVD emulation.
A long execution in hypervisor might cause a vCPU stuck phenomenon what
impact Windows Guest booting.
This patch introduce a workaround method that pausing all other vCPUs in
the same VM when do wbinvd emulation.
Tracked-On: #4703

hv: pause all other vCPUs in same VM when do wbinvd emulation

---

hypervisor/common/ptdev.c

The mask valuei 0x3F was added to prevent out of range in array access.
However, it should not be hardcoded.
Since in ptirq_alloc_entry_id, the valid allocated id is no greater
than CONFIG_MAX_PT_IRQ_ENTRIES, it will not cause out of range array
access without mask.
So this patch removes the mask.
Also, use bitmap_clear_lock instead of bitmap_clear_nolock becuase there
could be the chance that more than 1 core to access a same 64bit var.
Tracked-On: #4828

hv: ptirq : fix a bug in ptirq_release_entry

---

doc/contribute.rst
doc/develop.rst
doc/developer-guides/doc_guidelines.rst
doc/developer-guides/hld/index.rst
doc/release_notes/index.rst
doc/static/acrn-custom.css

Using ``.. rst-class:: rst-columns`` wasn't processed correctly because
of an error in the acrn-custom.css file.  Fix that, update the
documentation guidelines, and make use of the multi-column display in
documents where the toctree created a long list.  Now it will
appear in columns.
Also tweaked the toctree listing to use bold for the first-level items
(making a multi-column display look better, particularly when it has
subsections).

doc: fix rst-columns display

---

devicemodel/hw/pci/lpc.c
devicemodel/hw/pci/passthrough.c

two misc fixes for GVT-d passthrough.
One is to fix the gargabge on display screen after the GVT-d guest is
shutdown.
Another is to fix the issue that Linux GVT-d guest doesn't detect the
GPU platform correctly.

Acrn gpu fix for GVT-d passthrough

---

hypervisor/debug/logmsg.c
hypervisor/hw/pci.c

1. though "pci_device_lock" is set to 0 when system dose memory
initialization, it is better to explicitly init it before using.
2. unify spinlock_init usage
Tracked-On: #4827

HV: explicitly init pci device lock

---

devicemodel/Makefile

Since zlib is not used, remove linking to it. This reduces build
dependencies.
Tracked-On: #4838

dm: Do not link to zlib

---

hypervisor/arch/x86/guest/vm.c

in shutdown_vm, it uses guest flags when handling the phyiscal
CPUs whose LAPIC is pass-through. So if it is cleared first,
the related vCPUs and pCPUs can not be switched to correct state.
so move the clear action after the flags used.
Tracked-On: #4848

HV: fix bug to clear guest flags after it not used

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/lapic.c
hypervisor/include/arch/x86/lapic.h

As per the BWG a delay should be provided between the
INIT IPI and Startup IPI. Without the delay observe hangs
on certain platforms during MP Init sequence. So Setting
a delay of 10us between assert INIT IPI and Startup IPI.
Also, as per SDM section 10.7 the the de-assert INIT IPI is
only used for Pentium and P6 processors. This is not applicable
for Pentium4 and Xeon processors so removing this sequence.
Tracked-On: #4835

HV: Fix MP Init sequence hang by adding a delay

---

hypervisor/dm/vpci/vmsi.c
hypervisor/dm/vpci/vmsix.c
hypervisor/dm/vpci/vpci.c
hypervisor/dm/vpci/vpci_priv.h

v2:
some refine according to the comments
v1:
Guest may write a MSI/MSI-X capability register with only RW bits setting on.
This will over-write the corresponding RO bits in the vCFG space. This serial
tries to change this situation by only write RW bits in the vCFG space according
to a pre-defined RW permission mapping.

vpci: add vmsix/vmsix capability registers rw permission control

---

devicemodel/hw/platform/acpi/acpi.c
devicemodel/include/acpi.h

Kontron COMe-mAL10 does not provide an ACPI PSDS table as expected.
basl_fwrite_psds() expects to copy 33 bytes beginning at offset 46, thus
accessing the table up to offset 79. The PSDS table provided here is
shorter and thus should be ignored. Introduce a minimum length check
to achieve this.
Tracked-On: #4846

dm: acpi: validate minimal length of PSDS

---

devicemodel/Makefile
devicemodel/hw/pci/ivshmem.c

The ivshmem mediator emulates one standard PCI device which expose the shared memory region through its BAR2. The shared memory region is allocated through Linux shm mechanism and post-launched VM needs to specify the shm name and size as the acrn-dm parameter, the VMs have same shm name parameter can communicate over the shared memory.
For first stage, only support shared memory. Consider to support
notification(interrupt) in future.

 Support shared memory based inter-vm communication for ACRN post-launched VMs

---

doc/getting-started/building-from-source.rst

Remove zlib from the list of build dependencies and correct an error regarding the Ubuntu 16.04 build environment (which does *not* require to update `gcc` and `binutils`

doc: Remove zlib from the list of build dependencies

---

hypervisor/arch/x86/guest/virq.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/include/arch/x86/guest/vlapic.h

Inject pending exception prior pending interrupt to complete the previous instruction.

porting patch: hv: virq: refine pending event inject sequence

---

hypervisor/arch/x86/configs/pci_dev.c
hypervisor/arch/x86/configs/whl-ipc-i5/pci_devices.h
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/guest/vm_reset.c
hypervisor/dm/vpci/vpci.c
hypervisor/hw/pci.c
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/arch/x86/pci_dev.h
hypervisor/include/arch/x86/vm_config.h
hypervisor/include/hw/pci.h

v3:
1. add two new inline function: is_host_bridge and is_bridge
2. Add new input runtime for is_highest_severity_vm to check whether the vm is the highest severity VM on runtime or not
3. Adapt pdev_need_bar_restore/pdev_save_bar/pdev_restore_bar to Type 1 device
4. refine Patch 3 comment and coding style
v2:
1. check whether a device is host bridge or not by PCI Class
2. wrap a new function to get the highest severity VM of a scenario
v1:
two minor refine

vpci: refine pci device assignment logic

---

misc/acrn-config/library/hv_cfg_lib.py
misc/acrn-config/xmls/config-xmls/apl-up2-n3350/logical_partition.xml

refine sanity check for MASK_CLOS number by max clos in board xml.
Tracked-On: #4876

acrn-config: refine sanity check for MASK_CLOS number

---

hypervisor/Makefile
hypervisor/scripts/makefile/kconfig.mk

The $(VERSION) should be depended on config.h change. For example, when RELEASE
parameter is changed in make commmand, CONFIG_RELEASE need to be updated in
defconfig file, and then message in version.h should be updated.
The patch also fix a bug that a code path in make defconfig never be triggered
because shell will treat [ ! -f $(KCONFIG_FILE) ] as false when $(KCONFIG_FILE)
is not specified. (i.e. "$(KCONFIG_FILE)" == "")
Tracked-On: #2412

Makefile: minor fix on hypervisor dependency

---

devicemodel/Makefile
hypervisor/Makefile
misc/acrn-manager/Makefile
misc/acrnbridge/Makefile
misc/tools/acrn-crashlog/Makefile
misc/tools/acrnlog/Makefile
misc/tools/acrntrace/Makefile
paths.make

Don't hardcode install paths. Instead of hardcoding where binaries are
installed, add variables that installer can override.
Signed-off-by: Chee Yang Lee <chee.yang.lee@intel.com>
Signed-off-by: Naveen Saini <naveen.kumar.saini@intel.com>

use variables for installation directories.

---

hypervisor/hw/pci.c
hypervisor/include/hw/pci.h

We define some functions to read some fields of the CFG header registers. We
could remove them since they're not necessary since calling pci_pdev_read_cfg
is simple.

hv: pci: remove some unnecessary functions

---

devicemodel/hw/pci/xhci.c
devicemodel/hw/platform/usb_pmapper.c
devicemodel/include/usb_core.h

There is fd leakage during guest OS rebooting process, and this is
a WA patch to fix it. Formal patch will be made later.
Tracked-On: #4897

DM USB: xHCI: [REVERTME] release memory on port resetting.

---

hypervisor/arch/x86/init.c
hypervisor/arch/x86/lib/memory.c
hypervisor/arch/x86/seed/seed.c
hypervisor/boot/cmdline.c
hypervisor/boot/guest/deprivilege_boot.c
hypervisor/boot/guest/direct_boot.c
hypervisor/boot/guest/vboot_info.c
hypervisor/boot/guest/vboot_wrapper.c
hypervisor/boot/include/boot.h
hypervisor/boot/include/guest/vboot.h
hypervisor/boot/multiboot.c
hypervisor/boot/multiboot2.c
hypervisor/include/arch/x86/seed.h
hypervisor/include/lib/rtl.h
hypervisor/lib/string.c

Previously the VM kernel bootargs for pre-launched VMs and direct boot mode
of SOS VM are built-in hypervisor binary so end users have no way to change
it. Now we provide another option that the multiboot module string could be
used as bootargs also. This would bring convenience to end users when they
use GRUB as bootloader because the bootargs could be configurable in GRUB
menu.
The usage is if there is any string follows configured kernel_mod_tag in
module string, the string will be used as new kernel bootargs instead of
built-in kernel bootargs. If there is no string follows kernel_mod_tag,
then the built-in bootargs will be the default kernel bootargs.
Please note kernel_mod_tag must be the first word in module string in any
case, it is used to specify the module for which VM.
The …

HV: patch set to enable configurable bootargs

---

doc/tutorials/run_kata_containers.rst

This commit calls out specific ACRN and Ubuntu versions used for running the Kata Containers on ACRN.
Tracked-On: #4879

doc: specify component versions used by Kata-on-ACRN tutorial

---

doc/404.rst

A previous error (now fixed) in how the rst-columns CSS was written,
caused the default rst-columns to use 3 columns, when before (because of
the error) it being ignored.

doc: fix columns issue with 404 page display

---

doc/tutorials/setup_openstack_libvirt.rst

This commit adds the required dependencies for building the `acrn-libvirt` from source. The missing packages were installed for building the ACRN source code, it's no harm to `apt install` the packages if they are already installed, but this commit makes the build of `acrn-libvirt` independently.
Tracked-On: #4910 

doc: add dependencies for building acrn-libvirt independently

---

devicemodel/hw/pci/xhci.c

Fix XHCI_GET_SLOT macro check slot valid function, when the
slot value is bigger than XHCI_MAX_SLOT set the slot value
to zero.
Tracked-On: #4711

DM USB: xHCI: Fix XHCI_GET_SLOT value check issue

---

doc/tutorials/cl_servicevm.rst

Fix broken download links to the Service VM and RTVM images that are provided
for ACRN release 1.6.1.
Tracked-On: #4918

doc: fix broken links to pre-built images (release 1.6.1)

---

hypervisor/arch/x86/boot/trampoline.S
hypervisor/arch/x86/cpu_caps.c
hypervisor/arch/x86/page.c
hypervisor/arch/x86/pagetable.c
hypervisor/arch/x86/trampoline.c
hypervisor/include/arch/x86/mmu.h
hypervisor/include/arch/x86/page.h

There're some platforms still doesn't support 1GB large page on CPU side.
Such as lakefield, TNT and EHL platforms on which have some silicon bug and
this case CPU don't support 1GB large page.
This patch tries to release this constrain to support more hardware platform.
Note this patch doesn't release the constrain on IOMMU side.

mmu: release 1GB cpu side support constrain

---

devicemodel/hw/pci/passthrough.c
hypervisor/Makefile
hypervisor/arch/x86/Kconfig
hypervisor/arch/x86/guest/assign.c
hypervisor/arch/x86/vtd.c
hypervisor/common/ptdev.c
hypervisor/dm/vpci/pci_pt.c
hypervisor/dm/vpci/vmsi.c
hypervisor/dm/vpci/vmsix.c
hypervisor/dm/vpci/vmsix_on_msi.c
hypervisor/dm/vpci/vpci.c
hypervisor/dm/vpci/vpci_priv.h
hypervisor/hw/pci.c
hypervisor/include/arch/x86/guest/assign.h
hypervisor/include/arch/x86/vtd.h
hypervisor/include/common/ptdev.h
hypervisor/include/dm/vpci.h
hypervisor/include/hw/pci.h
hypervisor/pre_build/static_checks.c
misc/acrn-config/xmls/config-xmls/ehl-crb-b/hybrid.xml
misc/acrn-config/xmls/config-xmls/ehl-crb-b/industry.xml

Some passthrough devices require multiple MSI vectors, but don't
support MSI-X. In meanwhile, Linux kernel doesn't support continuous
vector allocation.
On native platform, this issue can be mitigated by IOMMU via interrupt
remapping. However, on ACRN, there is no vIOMMU.
vMSI-X on MSI emulation is one solution to mitigate this problem on ACRN.
This patch adds MSI-X emulation on MSI capability.
For the device needs to do MSI-X emulation, HV will hide MSI capability
and present MSI-X capability to guest.
The guest driver may need to modify to reqeust MSI-X vector.
For example:
ret = pci_alloc_irq_vectors(pdev, 1, STMMAC_MSI_VEC_MAX,
\-                                   PCI_IRQ_MSI);
\+                                   PCI_IRQ_MSI | PCI_IRQ_MSIX);
To enable MSI-X emulation, the device …

vmsix emulation on msi

---

doc/static/acrn-custom.css
doc/static/acrn-custom.js

As a UX improvement, use a separate tab when opening links to external
sites (use the same tab for internal links).  Also, use rel=noopener
attribute to improve security when linking to external sites.

doc: open external links in new tab

---

hypervisor/dm/vpci/vdev.c
hypervisor/dm/vpci/vpci.c
hypervisor/hw/pci.c
hypervisor/include/dm/vpci.h
hypervisor/include/hw/pci.h

HV: pci/vpci: refine pdev/vdev BDF-search with hash for better performance
1. Rename pci_pdev_array to pci_pdevs to make it clearer
2. Refine pci_lookup_drhd_for_pbdf with hash
3. Refine pci_find_vdev with hash
Tracked-On: #4857
Signed-off-by: Wang Qian <qian1.wang@intel.com>
Reviewed-by: Li Fei <Fei1.Li@intel.com>

HV: refine pdev/vdev BDF-search with hash

---

hypervisor/Makefile
hypervisor/arch/x86/cpu.c
hypervisor/debug/shell.c

As build variants for different board and different scenario growing, users
might make mistake on HV binary distributions. Checking board/scenario info
from log would be the fastest way to know whether the binary matches. Also
it would be of benifit to developers for confirming the correct binary they
are debugging.
Tracked-On: #4946

HV: add board and scenario info in log

---

devicemodel/hw/pci/ivshmem.c

Due to there is no inter-vm communication shared memory management
module, so each acrn-dm will call shm_unlink when VM rebooting/shutdown.
It causes one issue that if one of the two VMs is rebooting/shutdown,
the VM can't communicate with the peer again.
Currently, we don't release the shared memory to fix this issue.

dm: fixed an issue that VM can't communicate with peer after rebooting/shutdown

---

doc/api/GVT-g_api.rst
doc/developer-guides/hld/hld-APL_GVT-g.rst
doc/developer-guides/hld/hld-devicemodel.rst
doc/developer-guides/hld/hld-overview.rst
doc/developer-guides/hld/hld-power-management.rst
doc/developer-guides/hld/hv-interrupt.rst
doc/developer-guides/hld/hv-partitionmode.rst
doc/developer-guides/hld/hv-virt-interrupt.rst
doc/developer-guides/modularity.rst
doc/developer-guides/sw_design_guidelines.rst
doc/glossary.rst
doc/introduction/index.rst
doc/tutorials/debug.rst
doc/tutorials/rtvm_workload_design_guideline.rst
doc/user-guides/acrn-shell.rst

Attempt to replace all the variations of "pass-thru", "pass thru", "pass
through", and "pass-through" to be "passthrough" (except for doc labels
and in code or API uses)

doc: consistent spelling of passthrough

---

doc/static/acrn-custom.css

Fix CSS style for lists inside a note.  Previously the first list item
would overlap in the note heading box.

doc: fix style for lists in note

---

doc/introduction/index.rst
doc/tutorials/using_grub.rst

Lists inside of a note are displayed properly now, thanks to #4966 so
let's put some back in.

doc: restore lists inside of notes

---

hypervisor/arch/x86/cpu.c

The commit 'HV: Config Splitlock Detection to be disable' allows
using CONFIG_ENFORCE_TURNOFF_AC to turn off splitlock #AC. If
CONFIG_ENFORCE_TURNOFF_AC is not set, splitlock #AC should be turn on
Tracked-On: #4962

HV: Fix split-locked access detection is disabled by default

---

hypervisor/dm/vpci/vpci_priv.h
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/dm/vpci.h

Now we check whether a device is zombie by the ->user != NULL.

release_2.0: hv: vpci: a minor fix about is_zombie_vf

---

hypervisor/dm/vpci/vpci_priv.h
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/dm/vpci.h

Now we check whether a device is zombie by the ->user != NULL.

hv: vpci: a minor fix about is_zombie_vf

---

hypervisor/Makefile

We hit following build error when using gcc10:
arch/x86/page.c:240:48: error: array subscript is outside
array bounds of 'struct page[0][1]' [-Werror=array-bounds]
It happens with gcc10 on different Linux distributions.
Regarding the case that ACRN depends on zero length array in
sevaral places, we disable the zero length array warning by
gcc option.
Tracked-On: #4810

Build: disable zero length array warning

---

misc/acrn-config/board_config/board_c.py
misc/acrn-config/hv_config/hv_item.py
misc/acrn-config/library/common.py
misc/acrn-config/library/hv_cfg_lib.py
misc/acrn-config/scenario_config/scenario_cfg_gen.py

This patch adds support to configure MBA delay values from
scenario xml files just as it is done for CAT mask. This will
improve user experience when configuring RDT resource mask
values.
Tracked-On: #4943

acrn-config: Add missing MBA_delay configuration in scenario xml

---

hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/lapic.c

Currently, not all platforms support posted interrupt processing of both
VT-x and VT-d. On EHL, VT-d doesn't support posted interrupt processing.
So in such scenario, is_pi_capable() in vcpu_handle_pi_notification()
will bypass the PIR pending bits check which might cause a self-NV-IPI
lost.
With commit "bf1ff8c98 (hv: Offload syncing PIR to vIRR to processor
hardware)", the syncing PIR to vIRR is postponed and it is handled by a
self-NV-IPI in the following VMEnter. The process looks like,
a) vcpu A accepts a virtual interrupt ->
1) ACRN_REQUEST_EVENT is set
2) corresponding bit in PIR is set
3) Posted Interrupt ON bit is set
b) vcpu A does virtual interrupt injection on resume path due to
the pending ACRN_REQUEST_EVENT ->
1) hypervisor disables host interrupt
2) ACRN_REQUEST_EVENT is …

Fix the interrupts lost issue with PI support

---

hypervisor/acpi_parser/dmar_parse.c
hypervisor/hw/pci.c

From the VT-d spec 8.3:
If a DRHD structure with INCLUDE_PCI_ALL flag Set is reported for a
Segment, it must be enumerated by BIOS after all other DRHD structures
for the same Segment.
However, some broken BIOS violate the rules. To bring up ACRN with them,
change the ASSERT to a permissive check to unblock the BIOS limitation.
Also, scan the DRHD list to find the one who has INCLUDE_PCI_ALL flag.

Change to a permissive check with broken DMAR table

---

hypervisor/dm/vpci/vmsi.c
hypervisor/dm/vpci/vmsix.c
hypervisor/dm/vpci/vpci_priv.h

About the MSI/MSI-X Capability, there're some fields of it would never been changed
once they had been initialized. So it's no need to reset them once the vdev instance
is still used. What need to reset are the fields which would been changed by guest
at runtime.

hv: vpci: minor refine about MSI/MSI-X de-initialization

---

misc/Makefile
misc/life_mngr/Makefile

1. add life-mngr as a target in misc/Makefile, so it is
convenient to build and used in Yocto system.
2. add install target in life-mngr/Makefile to be packaged
into device file-system.
Tracked-On: #4870

tools: improve Makefile to build life-mngr

---

devicemodel/hw/pci/passthrough.c
devicemodel/include/pcireg.h

The way of passing DSM address on TGL is the same with on EHL.
Adding these code to support GVT-d on TGL.
Tracked-On: #5020
Signed-off-by: Sun Peng <peng.p.sun@intel.com>

dm: Data Stolen Memory (DSM) passthrough support for GVT-d on TGL

---

devicemodel/core/hugetlb.c

hugetlb_lv_max will get wrong value if the HUGETLB_LV2 mount failed.
Once hugetlb_lv_max is wrong, the following code logic messes up.
Tracked-On: #4937

dm: Fix wrong hugetlb_lv_max

---

doc/developer-guides/contribute_guidelines.rst

While changes to documentation can be submitted directly as PRs, changes
to code must be first submitted for approval to the developer mailing
list.  Update the contribution guidelines to talk about this.

doc: Update contribution guide instructions

---

misc/acrn-config/xmls/config-xmls/ehl-crb-b/industry.xml
misc/acrn-config/xmls/config-xmls/ehl-crb-b/industry_launch_1uos_hardrt.xml
misc/acrn-config/xmls/config-xmls/ehl-crb-b/industry_launch_1uos_waag.xml
misc/acrn-config/xmls/config-xmls/ehl-crb-b/industry_launch_2uos.xml
misc/acrn-config/xmls/config-xmls/ehl-crb-b/industry_launch_6uos.xml

- update passtrough device config for ehl-crb-b launch xmls
- support 6 VMs for ehl-crb-b industry xml
Tracked-On: #5015

acrn-config: refine scenario/launch xmls for ehl-crb-b

---

devicemodel/hw/platform/acpi/acpi.c
hypervisor/arch/x86/guest/vm.c
hypervisor/dm/vioapic.c
hypervisor/include/dm/vioapic.h

Some OSes assume the platform must have the IOAPIC. For example:
Linux Kernel allocates IRQ force from GSI (0 if there's no PIC and IOAPIC) on x86.
And it thinks IRQ 0 is an architecture special IRQ, not for device driver. As a
result, the device driver may goes wrong if the allocated IRQ is 0 for RTVM.
This patch expose vIOAPIC to RTVM with LAPIC passthru even though the RTVM can't
use IOAPIC, it servers as a place holder to fullfil the guest assumption.
After vIOAPIC has exposed to guest unconditionally, the 'ready' field could be
removed since we do vIOAPIC initialization for each guest.
Tracked-On: #4691

hv: vioapic: expose ioapic to guest unconditionally

---

doc/developer-guides/hld/ivshmem-hld.rst

ACRN 2.0 introduced Inter-VM communication feature by enabling the ivshmem v1.0 protocol/channel to communication
between VMs. To support the community's application Security Development Lifecycle (SDL), we provide a security hardening
guideline with some pointers to consider when using this channel by userspace application in case of additional security
requirments for Confidentiality, Integrity, or Authenticity.
Signed-off-by: Mostafa Naeem <mostafa.elsaid@intel.com>

doc: Update Inter-VM Communication with Security Hardening Guidelines

---

doc/static/acrn-custom.css

Propagated fix from other doxygen/breathe project to keep the
description found in the doxygen comments for the group being displayed
(in case there actually is a nice description given).

doc: keep doxygen group descriptions in doc output

---

hypervisor/common/hypercall.c

This patch is ported from mainline branch to v2.0 branch to fix
potential service VM hang issue when fuzzing hypercalls.
hv: hypercall: restrict the condition to assign/deassign a pci device to
a post-launched VM for safety
For the safety of post-launched VMs, pci devices assignments should
occur only when VM is being created (at VM_CREATED STATUS), and pci
devices de-assignment should occur only when VM is being created or
shutdown/reset (at VM_CREATED or VM_PAUSED status)
Tracked-On: #5024
Acked-by: Eddie Done <eddie.dong@intel.com>
Reviewed-by: Li Fei <Fei1.Li@intel.com>
Signed-off-by: Wang Qian <qian1.wang@intel.com>

HV: restrict conditions to assign/deassign pcidev

---

doc/introduction/index.rst

Instead of linking to a specific doc on projectacrn.org, update to just
link to the area on projectacrn.org/#resources where the roadmap doc can
be found.  Also remove mention of 2020 to keep it generic so it won't
need updating in 2021.

doc: update intro link to project roadmap

---

misc/acrn-config/xmls/config-xmls/tgl-rvp/industry.xml

Enable only 4 vms for TGL.
Tracked-On: #5013

acrn-config: enable only 4 vms for TGL

---

misc/acrn-config/launch_config/com.py

Minor fix for mac seed when generating launch script.
Tracked-On: #5039

acrn-config: minor fix mac seed for launch config

---

devicemodel/hw/pci/passthrough.c

OpRegion: 8KB(0x2000)
[ OpRegion Header      ] Offset: 0x0
[ Mailbox #1: ACPI     ] Offset: 0x100
[ Mailbox #2: SWSCI    ] Offset: 0x200
[ Mailbox #3: ASLE     ] Offset: 0x300
[ Mailbox #4: VBT      ] Offset: 0x400
[ Mailbox #5: ASLE EXT ] Offset: 0x1C00
Extended OpRegion: 8KB(0x2000)
[ Raw VBT              ] Offset: 0x0
Generally VBT stores in MailBox4 in OpRegion which max size is 6KB.
If VBT larger than 6KB, it will be stored in extended OpRegion which
is neighborhood with legacy OpRegion. In this case, we need to
passthrough extended OpRegion also to support GVT-d feature. The
OpRegion size that we passthrough should be (OpRegion+Extended)=16KB
ASLE.rvda stores the location of VBT.
For OpRegion 2.1+: ASLE.rvda = offset to OpRegion base address
For OpRegion 2.0:  ASLE.rvda = physical …

dm: Increase OpRegion size for bigger VBT

---

misc/acrn-config/launch_config/com.py

Generate '-s 1:0,lpc ' for none Hart RT in launch script.
Tracked-On: #5049

acrn-config: generate '-s 1:0,lpc ' for non-hart rt in launch script

---

hypervisor/arch/x86/guest/pm.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/guest/vm_reset.c
hypervisor/arch/x86/guest/vmcall.c
hypervisor/common/hv_main.c
hypervisor/common/hypercall.c
hypervisor/include/arch/x86/guest/vm.h

-- replace global hypercall lock with per-vm lock
-- add spinlock protection for vm & vcpu state change
v1-->v2:
change get_vm_lock/put_vm_lock parameter from vm_id to vm
move lock obtain before vm state check
move all lock from vmcall.c to hypercall.c
Signed-off-by: Mingqiang Chi <mingqiang.chi@intel.com

hv:add per-vm lock for vm & vcpu state change

---

devicemodel/hw/pci/xhci.c

There has one bug that the pci_xhci_dev_emu objects recorded in
xdev->devices haven't destroied when OVMF transfer to guest OS.
This will cause the the fds of usbfs can't be freed in libusb.
The OVMF xHCI driver needs to disable all enabled slots during
graceful existing flow, but it doesn't.
The USBCMD.HCRST bit is used for xHCI reset that will be triggered
in xHCI driver initialization. We can use this chance to clear all
pci_xhci_dev_emu objects
Tracked-On: #4897

DM: xHCI: Release all device resource when received HCRST.

---

hypervisor/arch/x86/guest/vcpu.c
hypervisor/common/schedule.c
hypervisor/include/arch/x86/guest/vcpu.h
hypervisor/include/common/schedule.h

Thread object's status is changed without context switch done. This is
not accurate. Move the status transition after context switch to make it
more accurate.
Also move kick_thread() logic from schedule framework to vcpu layer,
because it's more about vcpu notification which has less relevant with
scheduling.
Tracked-On: #5057

Refine status transition of thread object

---

hypervisor/arch/x86/cpu_caps.c
hypervisor/arch/x86/guest/vcpu.c
hypervisor/include/arch/x86/cpu.h

XSAVE area has the following format:
- The legacy region.
- X87 state
- SSE state
- The XSAVE header.
- The extended region.
Instructions fxsave/fxrstor operate the legacy region by default.
Instructions xsaves/xrstors operate the XSAVE area according to the
state componment bits in XCR0. The hypervisor use xsaves/xrstors to
save/restore the XSAVE area of each vCPU in context switch. So the
state componment in legacy region shoud be always covered during context
switch.
Set SSE feature bit in XCR0 during context switch.
Tracked-On: #5062

hv: fix possible SSE region mismatch issue

---

misc/acrn-config/launch_config/com.py

Refine mac seed when generating launch script.
Tracked-On: #5039

acrn-config: refine mac seed for launch config

---

devicemodel/Makefile
devicemodel/core/main.c
devicemodel/core/vmmapi.c
devicemodel/hw/mmio/core.c
devicemodel/hw/platform/acpi/acpi.c
devicemodel/include/dm.h
devicemodel/include/mmio_dev.h
devicemodel/include/public/vhm_ioctl_defs.h
devicemodel/include/tpm.h
devicemodel/include/vmmapi.h
hypervisor/Makefile
hypervisor/arch/x86/configs/vacpi.c
hypervisor/arch/x86/configs/whl-ipc-i5/misc_cfg.h
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/guest/vmcall.c
hypervisor/boot/include/acpi.h
hypervisor/common/hypercall.c
hypervisor/dm/mmio_dev.c
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/arch/x86/vm_config.h
hypervisor/include/common/hypercall.h
hypervisor/include/dm/mmio_dev.h
hypervisor/include/dm/vacpi.h
hypervisor/include/public/acrn_hv_defs.h
hypervisor/scenarios/hybrid/vm_configurations.c

v4:
1. refine the DM cmdline to pass MMIO PT parameter
2. add a MACRO to enable MMIO PT for pre-launched VM
3. check vm id is valid in dispatch_sos_hypercall
v3:
1. remove reserved0 in acrn_mmiodev structure.
2. refine the logic of TPM ACPI Table construct for pre-launched VM.
3. refine the MMIO passthrough Doc
v2:
1. add doc to describe how to pass through MMIO device in ACRN
2. enlarge TPM_CRB_MMIO_SIZE form 0x1000 to 0x5000
3. move TPM_BUFFER_XXX MACRO from platform_acpi_info.h to misc_cfg.h
4. Add two new ToDo and one FIXME
ToDo: a.1 refine cmdline from --tpm2 HID to --mmiopt HID if we support more type PT MMIO device
a.2 allocate MMIO resource in a reserved MMIO region rather than hard-coded
FIXME: Now we will don't allow pass through TPM device and emulate the vTPM at the same time …

Add MMIO device pass through support

---

misc/packaging/README.rst
misc/packaging/release.json

Update the draft content about Debian packaging with something more user
friendly and complete.
I removed the version of the release.json included in the doc and
instead just include the release.json file directly.  We should add
comments about the configuration parameters directly in the release.json
file, using the convention already being used there.
(If we updated the json python package being used to json5, the
release.json file could include comments using // convention.)
Tracked-On: #5022

doc: update debian packaging documentation

---

hypervisor/dm/vpci/vpci.c

When VM read pre-sriov header in ECAP of ptdev, only emulate the
reading if SRIOV is hidden.
Write to pre-sriov header is ignored so no need to fix writting.
Tracked-On: #5085

HV: fix hide all sriov in ecap

---

doc/tutorials/rtvm_performance_tips.rst

There seems to be a typo in the documentation.

doc: fixing the intel_pstate kernel command line setting

---

doc/developer-guides/hld/hld-devicemodel.rst
doc/developer-guides/hld/mmio-dev-passthrough.rst

Besides PCI passthru, ACRN can support passthru of a set of page-aligned
MMIO resources. One example is to passthru a TPM device which includes
a set of page aligned MMIO resources.

doc: add mmio device passthrough introduction

---

doc/developer-guides/hld/hld-hypervisor.rst

Doc was merged but not included in the TOC (CI indicated a pass on that
PR even though doc build failed).  This fixes that undetected error.

doc: add mmio-dev-passthrough to TOC

---

hypervisor/common/schedule.c

As we only set BLOCKED status in context switch_out, which means, only
running thread can be changed to BLOCKED, but runnable thread can not.
This lead to the deadloop in sleep_thread_sync.
To solve the problem, in sleep_thread, we set the status to BLOCKED
directly when the original thread status is RUNNABLE.
Tracked-On: #5115

hv: fix deadloop in sleep_thread_sync

---

hypervisor/arch/x86/guest/vm.c

arch_vm member of struct acrn_vm is page aligned. memset used in create_vm
subtracts only 8 bytes, sizeof(spinlock_t) from the size of acrn_vm and uses
the vm->arch_vm as the destination address. To do it right, it should subtract
4096 bytes. This would result in writing memory beyond the acrn_vm struct.
This patch fixes the issue by using offsetof compiler macro and subtracts the
right amount of size corresponding to the beginning of arch_vm member in
struct acrn_vm.
Tracked-On: #5107

hv: Fix size issue used for memset in create_vm

---

Makefile
hypervisor/arch/x86/Kconfig

The SDC scenario configurations will not be validated so remove it from
build makefile;
Tracked-On: #5077

HV: Make: remove sdc scenario build support

---

hypervisor/dm/vpci/vmsi.c

In MSI Capability Structure, bit 7 (64 bit address capable) of MSICTRL
is RO;
Tracked-On: #5125
Reviewed-by: Li Fei <fei1.li@intel.com>

HV: correct RO mask of MSI cap structure

---

hypervisor/arch/x86/guest/vm.c
hypervisor/dm/io_req.c
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/dm/io_req.h

-- move vm_state_lock to other place in vm structure
to avoid the memory waste because of the page-aligned.
-- remove the memset from create_vm
-- explicitly set max_emul_mmio_regions and vcpuid_entry_nr to 0
inside create_vm to avoid use without initialization.
-- rename max_emul_mmio_regions to nr_emul_mmio_regions
v1->v2:
add deinit_emul_io in shutdown_vm
Reviewed-by: Grandhi, Sainath <sainath.grandhi@intel.com>

hv:refine vm & vcpu lock

---

doc/developer-guides/hld/vuart-virt-hld.rst
doc/tutorials/acrn_configuration_tool.rst
doc/tutorials/debug.rst
doc/tutorials/vuart_configuration.rst

As noticed in PR #5134 scenario configurations were moved out of the
hypervisor folder over to the misc folder (within the acrn-hypervisor
repo).  Fix references and make them all consistent (referencing
misc/vm_configs)

doc: fix references to misc/vm_configs folder

---

devicemodel/core/main.c
devicemodel/core/vmmapi.c
devicemodel/include/dm.h
hypervisor/arch/x86/guest/vcpuid.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/guest/vmcs.c
hypervisor/arch/x86/guest/vmsr.c
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/public/acrn_common.h
hypervisor/scenarios/hybrid/vm_configurations.h
hypervisor/scenarios/industry/vm_configurations.h
hypervisor/scenarios/sdc/vm_configurations.h
misc/acrn-config/scenario_config/vm_configurations_h.py

hv: pmu: passthrough pmu to vm when GUEST_FLAG_PMU_PASSTHROUGH set
Add a new guest_flag GUEST_FLAG_PMU_PASSTHROUGH to indicate whether to
passthrough Performance Monitor Unit (PMU) to a VM or not.
If GUEST_FLAG_PMU_PASSTHROUGH is set for a VM, passthrough PMU.
Currently, PEBS is not supported.
In DM, added an option "--pmu" to enable PMU passthrough.
Tracked-On: #5132

Pmu passthrough

---

doc/user-guides/kernel-parameters.rst

After change to IDV display solution for gvt-g, the kernel parameters:
i915.domain_plane_owners, i915.domain_plane_owners and i915.enable_pvmmio
related instruction is invalid and should be removed.

doc: remove invalid kernel parameters for gvt-g

---

doc/tutorials/using_partition_mode_on_nuc.rst

Document was updated to use v2.1 but left a references to v1.6

doc: fix mismatched ACRN version

---

hypervisor/scripts/makefile/cfg_update.mk

realpath function would be got null while the directory or file is
not exist, modify the function abspath to instead realpath.
Tracked-On: #5146

Makefile: modify the realpath to abspath function

---

hypervisor/dm/vuart.c
hypervisor/include/arch/x86/guest/vmx_io.h
hypervisor/include/arch/x86/vm_config.h

Currently, there are 2 vuarts for each VM, vuart 0 is for console, vuart
1 is for communication.
As the requirement for communication between more VMs, add 2 additional
vuarts for each VM.
Tracked-On: #5138

hv: enlarge vuart number from 2 to 4 for each vm

---

doc/release_notes/release_notes_1.0.2.rst
doc/release_notes/release_notes_1.1.rst
doc/release_notes/release_notes_2.0.rst
doc/release_notes/release_notes_2.1.rst

Some months were spelled out, others were abbreviated, making the list
of all release notes look a bit off.

doc: use consistent month names in release notes

---

hypervisor/arch/x86/guest/instr_emul.c

This patch is used to fix asm instruction error such as stos and stosq.
Tracked-On: #5165

hv: fix stos and stosq asm instruction emulation error

---

devicemodel/hw/pci/passthrough.c

Some passthrough devices have no reset mechanisms which cause the device stay
in unknown status during boot/reboot flow. And such unknown status cause
unexpected behaviors in the guest. Except the ordinary reset mechanisms
like FLR, we can utilize enter/exit D3cold as the reset that D3cold will
power gate the entire hardware. But the D3cold is implemented as ACPI
method which has no user interface in the SOS side. But the D3cold is
implemented as ACPI method which has no user interface in the SOS side.
But base on our experience, some devices can utilize D3hot instead of
D3cold. But it is not useful for all PCI devices as the power status
of D3hot is implementation defined.
Provide one new API to program PowerState(D0/D1/D2/D3hot) in PMCSR
register.
Add "d3hot_reset" sub-parameter for …

DM: PT: Add "d3hot_reset" sub-parameter for passthrough device

---

misc/vm_configs/xmls/config-xmls/qemu/sdc.xml

when CONFIG_MAX_MSIX_TABLE_NUM was set to 64, it will trigger timeout ASSERT
on WHL-I5 board.
Tracked-On: #5178

acrn-config: set CONFIG_MAX_MSIX_TABLE_NUM to 16 in the qemu sdc xml

---

hypervisor/scripts/makefile/cfg_update.mk

realpath function would be got null while the directory or file is
not exist, modify the function abspath to instead realpath.
Tracked-On: #5146

[release 2.1]Makefile: modify the realpath to abspath function

---

hypervisor/include/arch/x86/cpuid.h

There's a corner case:
When want to get CPUID.01H:EDX value,
may have the following code snippet:
uint32_t unused,edx;
cpuid_subleaf(0x1U, 0x0U, &unused, &unused, &unused, &edx);
while in cpuid_subleaf:
*eax = leaf;
*ecx = subleaf;
eax and ecx point to the same location,
When deep into asm_cpuid, it's input value will be 0x0U and 0x0U.
but the expected input value is 0x1U and 0x0U.
This case will return CPUID.00H:EDX, which is the wrong answer.
Tracked-On: #4526

hv:cpuid:refine cpuid_subleaf interface

---

misc/vm_configs/xmls/config-xmls/tgl-rvp/hybrid.xml
misc/vm_configs/xmls/config-xmls/tgl-rvp/industry.xml
misc/vm_configs/xmls/config-xmls/tgl-rvp/logical_partition.xml
misc/vm_configs/xmls/config-xmls/tgl-rvp/sdc.xml

The default memory is 16G on TGL; the value of PLATFORM_RAM_SIZE and
SOS_RAM_SIZE is a little small in default xml.
Tracked-On: # 5184

acrn-config: update TGL platform and SOS RAM size

---

misc/acrn-config/library/scenario_cfg_lib.py

CPU sharing between pre-launch VMs and SOS, post-launch VMs were
forbidden.
Remove the limitation.
Tracked-On: #5153

acrn-config: Enable pre-launch VM sharing CPU with other VMs

---

misc/vm_configs/xmls/board-xmls/cfl-k700-i7.xml
misc/vm_configs/xmls/config-xmls/cfl-k700-i7/industry.xml

Add cfl-k700-i7 board xml and its industry xml to support ACRN industry
scenario on cfl-k700-i7 board.
Tracked-On: #5212

acrn-config: add cfl-k700-i7 industry xmls

---

hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/guest/vmcall.c
hypervisor/common/hypercall.c
hypervisor/debug/hypercall.c
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/common/hypercall.h
hypervisor/include/public/acrn_hv_defs.h
hypervisor/release/hypercall.c

-- use an array to fast locate the hypercall handler
to replace switch case.
-- uniform hypercall handler as below:
int32_t (*handler)(sos_vm, target_vm, param1, param2)

refine hypercall

---

doc/developer-guides/hld/hld-devicemodel.rst
doc/developer-guides/hld/hld-overview.rst
doc/developer-guides/hld/hld-security.rst
doc/developer-guides/hld/hostbridge-virt-hld.rst
doc/developer-guides/hld/hv-startup.rst
doc/developer-guides/hld/ivshmem-hld.rst
doc/developer-guides/sw_design_guidelines.rst
doc/getting-started/building-from-source.rst
doc/introduction/index.rst
doc/tutorials/acrn_configuration_tool.rst
doc/user-guides/hv-parameters.rst
doc/user-guides/kernel-parameters.rst

Also clear Linux is no longer supported either as SOS or post-launched VM kernel.
- When it mentions clear Linux, mostly replaced by Ubuntu.
- remove all contents re/lated to "UEFI boot".
- remove the term de-privilege mode, and direct mode as well.
Tracked-On: #5197

doc: remove UEFI/de-privilege boot mode from docs

---

misc/acrn-config/board_config/misc_cfg_h.py
misc/acrn-config/config_app/views.py
misc/acrn-config/library/scenario_cfg_lib.py

We use sos kernel cmdline maxcpus to limit the pCPU number of SOS
for hybrid or hybrid_rt scenarios by vcpu numbers calculation.
v2: add SOS CPU affinity calculation by total pCPU plus pCPUs
occupied by pre-launched VMs when no pcpuid configured
in SOS.
Tracked-On: #5216

acrn-config: add maxcpus to sos kernel cmdline in hybrid scenario

---

hypervisor/arch/x86/Kconfig
hypervisor/debug/dbg_cmd.c
hypervisor/debug/uart16550.c
hypervisor/include/debug/uart16550.h
misc/acrn-config/hv_config/board_defconfig.py
misc/vm_configs/xmls/board-xmls/ehl-crb-b.xml
misc/vm_configs/xmls/config-xmls/ehl-crb-b/industry.xml

hv: debug: Enable MMIO UART support
New board, EHL CRB, does not have legacy port IO UART. Even the PCI UART
are not work due to BIOS's bug workaround(the BARs on LPSS PCI are reset
after BIOS hand over control to OS). For ACRN console usage, expose the
debug UART via ACPI PnP device (access by MMIO) and add support in
hypervisor debug code.
Another special thing is that register width of UART of EHL CRB is
1byte. Introduce reg_width for each struct console_uart.
Tracked-On: #4937

Ehl uart enable

---

hypervisor/common/hypercall.c

Virtual interrupts injection and memory mapping operations can impact
target VM. By design, these type of operations from lower severity VM
to higher severity VM should be blocked by the hypervisor.
While the hypercalls are the interface between SOS VM and the
hypervisor, severity checks can be implemented at the beginning of
hypercalls needed.
Added severity checks in below hypercalls:
* hcall_set_vm_memory_regions()
* hcall_notify_ioreq_finish()
* hcall_set_irqline()
* hcall_inject_msi()
* hcall_write_protect_page()
Tracked-On: #5208

hv: Add severity check against SOS hypercalls

---

hypervisor/arch/x86/vtd.c

When trying to passthru a DHRD-ignored PCI device,
iommu_attach_device shall report success. Otherwise,
the assign_vdev_pt_iommu_domain will result in HV panic.
Same for iommu_detach_device case.
Tracked-On: #5240
Signed-off-by: Stanley Chang <stanley.chang@intel.com>

hv: passthru DHRD-ignored device

---

misc/acrn-config/hv_config/board_defconfig.py
misc/acrn-config/library/scenario_cfg_lib.py

Because ivshmem memory uses hv memory, if the ivshmem feature is
enabled, HV_RAM_SIZE will include IVSHMEM_SHM_SIZE.

acrn-config: make HV_RAM_SIZE include IVSHMEM_SHM_SIZE

---

hypervisor/include/arch/x86/vm_config.h
misc/acrn-config/board_config/board_info_h.py
misc/acrn-config/library/board_cfg_lib.py
misc/acrn-config/library/common.py
misc/acrn-config/library/hv_cfg_lib.py
misc/acrn-config/library/scenario_cfg_lib.py
misc/acrn-config/scenario_config/scenario_cfg_gen.py
misc/acrn-config/scenario_config/scenario_item.py
misc/acrn-config/scenario_config/vm_configurations_c.py
misc/vm_configs/scenarios/hybrid/vm_configurations.c
misc/vm_configs/xmls/config-xmls/apl-mrb/logical_partition.xml
misc/vm_configs/xmls/config-xmls/ehl-crb-b/hybrid.xml

V2:
- Address review comments
- Added code to support config UI tool
- Renamed pin to gsi for intx passthru for both xml file and generated code
- Fix error messages in code
V1:
- Support for direct assignment of P2SB bridge to one pre-launched safety VM for EHL
- Expose GPIO chassis interrupts as INTx to the safety VM for EHL
- Fix misspelled function name

acrn-config: P2SB Bridge Passthrough and expose GPIO Chassis Interrupt to the Safety VM as INTx

---

hypervisor/arch/x86/Kconfig
hypervisor/debug/dbg_cmd.c
hypervisor/debug/uart16550.c
misc/acrn-config/hv_config/board_defconfig.py

BDF string can be parsed by the configuration tool. A 16bit WORD value with
format (B:8, D:5, F:3) can be passed from configuration to the
hypervisor directly to save some BDF string parse code

Convert PCI UART paramter from a BDF string to a hex value

---

doc/developer-guides/contribute_guidelines.rst
doc/developer-guides/doc_guidelines.rst
doc/developer-guides/hld/hv-ioc-virt.rst
doc/developer-guides/hld/ivshmem-hld.rst
doc/developer-guides/hld/virtio-i2c.rst
doc/developer-guides/modularity.rst
doc/tutorials/acrn_on_qemu.rst
doc/tutorials/docbuild.rst
doc/tutorials/using_celadon_as_uos.rst

Replace white/black master/slave terms with alternatives.  We're not
changing "master" when used in the context of GitHub branches.  GitHub
advises they have a plan to help this transition.  I did though add the
word "branch" to bare uses of "master".

doc: update inclusive language terms in docs

---

misc/vm_configs/scenarios/hybrid/vm_configurations.c
misc/vm_configs/xmls/config-xmls/apl-mrb/hybrid.xml
misc/vm_configs/xmls/config-xmls/apl-up2/hybrid.xml
misc/vm_configs/xmls/config-xmls/ehl-crb-b/hybrid.xml
misc/vm_configs/xmls/config-xmls/generic/hybrid.xml
misc/vm_configs/xmls/config-xmls/nuc6cayh/hybrid.xml
misc/vm_configs/xmls/config-xmls/nuc7i7dnb/hybrid.xml
misc/vm_configs/xmls/config-xmls/tgl-rvp/hybrid.xml
misc/vm_configs/xmls/config-xmls/whl-ipc-i5/hybrid.xml
misc/vm_configs/xmls/config-xmls/whl-ipc-i7/hybrid.xml

After below commit in https://github.com/zephyrproject-rtos/zephyr
commit d0126a037d23484feebba00d2c0eac27e6393fef
Author: Zide Chen <zide.chen@intel.com>
Date:   Wed Feb 5 08:32:00 2020 -0800
boards/x86/acrn: build it in x86_64 mode and switch to X2APIC
The zephyr image for acrn would be built in x86_64 mode by default, then the
load/entry address for pre-launched Zephyr image should be changed from
0x100000 to 0x8000 accordingly per below definition in zephyr .ld file:
zephyrproject_src/zephyr/include/arch/x86/intel64/linker.ld
SECTIONS
{
/*
* The "locore" must be in the 64K of RAM, so that 16-bit code (with
* segment registers == 0x0000) and 32/64-bit code agree on addresses.
* ... there is no 16-bit code yet, but there will be when we add SMP.
*/
.locore 0x8000 : ALIGN(16)
{ …

acrn-config: zephyr entry and load address update

---

doc/developer-guides/hld/virtio-i2c.rst

A previous update changed "slave" to "secondary", but the code comments
were changed to use "client", so update the documentation to match.

doc: update virtio-i2c inclusive language

---

misc/acrn-config/board_config/board_c.py
misc/acrn-config/board_config/board_info_h.py
misc/acrn-config/library/board_cfg_lib.py
misc/vm_configs/xmls/board-xmls/ehl-crb-b.xml

Two PSE-GPIO controllers of EHL CRB require MSI-X emulation for
pass-thru because it uses multiple MSI vectors. Currently acrn-config
enables MSI-X emulation for only TSN devices. Enable MSI-X emulation
for PSE-GPIOs, too.
Tracked-On: #5242

acrn-config: add pse-gpio to vmsix_on_msi devices list

---

devicemodel/hw/pci/xhci.c

According to xHCI Spec 4.10.1 Transfer TRBS chapter, there have three scenarios shall
generate a Transfer Event TRB when transfer TRBs. The patch set fix the Transfer TRBs
error handler and  Add Null pointer check in Set TR Dequeue command handle function
to avoid Null pointer exception.
Tracked-On: #5263

DM: xHCI: Fix WaaG crash issue caused by Transfer TRBS.

---

hypervisor/Makefile
hypervisor/arch/x86/guest/assign.c
hypervisor/arch/x86/guest/vm.c
hypervisor/dm/vgpio.c
hypervisor/dm/vioapic.c
hypervisor/include/arch/x86/guest/assign.h
hypervisor/include/dm/vgpio.h
hypervisor/include/dm/vioapic.h
misc/acrn-config/board_config/board_info_h.py

Add the capability of forwarding INTx interrupts to pre-launched VMs as virtual interrupts per definitions in VM config. This is typically required for the sake of the GPIO device which can be accessed through only P2SB (Primary to Sideband) and which can support only INTx interrupts. Also for that GPIO device, add vgpio dm which emulates GPIO interrupt registers so that it can return the virtualized values upon read in accordance with the gsi to vgsi mappings given by the VM config.
Tracked-On: #5245
Tracked-On: #5246

hv: add INTx mapping for pre-launched VMs and vgpio dm for gpio interrupt registers emulation

---

misc/acrn-config/library/scenario_cfg_lib.py
misc/acrn-config/scenario_config/ivshmem_cfg_h.py
misc/vm_configs/scenarios/hybrid_rt/whl-ipc-i5/ivshmem_cfg.h

update the size of ivshmem memory region to [2MB, 512MB].

acrn-config: update the size range of ivshmem memory region

---

hypervisor/arch/x86/Kconfig
hypervisor/arch/x86/boot/cpu_primary.S

Previously the min load_addr for HV image is hard coded to 0x10000000 when
CONFIG_RELOC is enabled, now use CONFIG_HV_RAM_START as its prefer minimum
address like setting of CONFIG_PHYSICAL_START do in Linux kernel.
With this patch, we can offload the CONFIG_HV_RAM_START algorithm to
acrn-config or manually set it in scenario XML on some special boards.
Tracked-On: #5275

HV: set CONFIG_HV_RAM_START as min addr when RELOC enabled

---

hypervisor/dm/vpci/vhostbridge.c

hv: vpci: Add 0x45, which is the high-byte of device id of EHL,
to the enumeration array in vhostbridge.c. This is to fix the
problem that PCIe extended capabilities like SR-IOV cannot be
used on EHL.
Tracked-On: #5256
Signed-off-by: Qian Wang <qian1.wang@intel.com>

HV: Fix SR-IOV problem on EHL

---

misc/vm_configs/xmls/config-xmls/ehl-crb-b/hybrid_rt_fusa.xml

Add a new scenario xml file for EHL which is derived from hybrid_rt for
validation of certain passthru devices in prelaunched RTVM. Because the
configuration requires to disable GPIO support for SOS VM, it should
not be merged into the standard hybrid_rt scenario. According to this
change, remove the SCI passthru setting from existing hybrid_rt since
from now on hybrid_rt_fusa should be used for SCI passthru test.
Tracked-On: #5278

acrn-config: add hybrid_rt_fusa scenario for fusa related passthru test

---

misc/acrn-manager/Makefile

Build and install 'acrnctl' for regardless of the RELEASE value. Kata Containers
depends on 'acrnctl' in order to work correctly and we therefore need to make
sure that it is built and installed correctly regardless of whether this is a
debug or a release build.
Tracked-On: #4940

acrn-manager: build and install 'acrnctl' (release and debug)

---

misc/acrn-config/config_app/static/main.js
misc/acrn-config/config_app/views.py
misc/acrn-config/library/launch_cfg_lib.py

When creating a new launch setting, config app can't fine the
scenario config which caused the app failed to load the new
launch setting.
Tracked-On: #5282

acrn-config: fix the issue of failure to create a new launch setting.

---

misc/vm_configs/xmls/config-xmls/ehl-crb-b/hybrid.xml
misc/vm_configs/xmls/config-xmls/ehl-crb-b/hybrid_rt.xml
misc/vm_configs/xmls/config-xmls/ehl-crb-b/industry.xml
misc/vm_configs/xmls/config-xmls/ehl-crb-b/sdc.xml

EHL PSE TSN GbE driver is default set to use 32bit of dma addressing.
net: stmmac: configure PSE Gbe to 32bit dma addressing
https://github.com/intel/linux-intel-lts/commit/011c8f
When VM has more than 4GB physical memory, Linux kernel uses the bounce
buffers (swiotlb) to translate kernel data in 64bit memory to 32bit
range for the sake of the DMA because iommu is not available. The
default swiotlb value 32768 is insufficient to support two PSE TSN GbEs
at the same time. Increase the value to 131072 otherwise two GbEs can't
link up.
Tracked-On: #5243

acrn-config: add swiotlb to sos kernel bootargs to increase bounce bufs

---

hypervisor/acpi_parser/acpi_ext.c
hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/guest/vm.c
hypervisor/dm/vpci/vhostbridge.c
hypervisor/dm/vpci/vpci.c
hypervisor/hw/pci.c
hypervisor/include/dm/vacpi.h
hypervisor/include/dm/vpci.h
hypervisor/include/hw/pci.h
misc/acrn-config/board_config/acpi_platform_h.py
misc/vm_configs/boards/ehl-crb-b/platform_acpi_info.h
misc/vm_configs/boards/nuc7i7dnb/platform_acpi_info.h
misc/vm_configs/boards/whl-ipc-i5/platform_acpi_info.h
misc/vm_configs/boards/whl-ipc-i7/platform_acpi_info.h

Per PCI Firmware Specification Revision 3.0, 4.1.2. MCFG Table Description:
Memory Mapped Enhanced Configuration Space Base Address Allocation Structure assign the Start Bus Number and the End Bus Number which could decoded by the Host Bridge. We should not access the PCI device which bus number outside of the range of [Start Bus Number, End Bus Number). The Start Bus Number and End Bus Number is retrieved from native board information.
For ACRN,  we should:
1. Don't detect PCI device which bus number outside the range of [Start Bus Number, End Bus Number) of MCFG ACPI Table.
2. Only trap the ECAM MMIO size: [MMCFG_BASE_ADDRESS, MMCFG_BASE_ADDRESS + (End Bus Number - Start Bus Number + 1) * 0x100000) for SOS.
Tracked-On: #5233
Li Fei1 (1):
pci: mcfg: limit device bus numbers which could …

pci: mcfg: limit device bus numbers which could access by ECAM

---

misc/vm_configs/xmls/config-xmls/ehl-crb-b/hybrid_rt.xml

For EHL hybrid_rt scenario, the requirement needs a network device
passthough to pre-launched VM0.
Tracked-On: #5286

config: EHL passthough network to pre-launched VM for hybrid_rt

---

misc/acrn-config/library/board_cfg_lib.py
misc/acrn-config/library/scenario_cfg_lib.py
misc/acrn-config/scenario_config/scenario_cfg_gen.py
misc/acrn-config/scenario_config/scenario_item.py
misc/vm_configs/xmls/config-xmls/apl-mrb/hybrid.xml
misc/vm_configs/xmls/config-xmls/apl-mrb/logical_partition.xml
misc/vm_configs/xmls/config-xmls/apl-up2-n3350/logical_partition.xml
misc/vm_configs/xmls/config-xmls/apl-up2/hybrid.xml
misc/vm_configs/xmls/config-xmls/apl-up2/logical_partition.xml
misc/vm_configs/xmls/config-xmls/ehl-crb-b/hybrid_rt.xml
misc/vm_configs/xmls/config-xmls/ehl-crb-b/hybrid_rt_fusa.xml
misc/vm_configs/xmls/config-xmls/generic/hybrid.xml
misc/vm_configs/xmls/config-xmls/generic/hybrid_rt.xml
misc/vm_configs/xmls/config-xmls/generic/logical_partition.xml
misc/vm_configs/xmls/config-xmls/nuc6cayh/hybrid.xml
misc/vm_configs/xmls/config-xmls/nuc6cayh/logical_partition.xml
misc/vm_configs/xmls/config-xmls/template/PRE_RT_VM.xml
misc/vm_configs/xmls/config-xmls/tgl-rvp/hybrid.xml
misc/vm_configs/xmls/config-xmls/tgl-rvp/hybrid_rt.xml
misc/vm_configs/xmls/config-xmls/tgl-rvp/logical_partition.xml
misc/vm_configs/xmls/config-xmls/whl-ipc-i5/hybrid_rt.xml
misc/vm_configs/xmls/config-xmls/whl-ipc-i5/logical_partition.xml
misc/vm_configs/xmls/config-xmls/whl-ipc-i7/hybrid_rt.xml

enable TPM2 config on ehl-crb-b board and update TPM2 configs on
legacy boards.

acrn-config: enable TPM2 config on ehl-crb-b board

---

hypervisor/arch/x86/guest/vm.c
hypervisor/dm/io_req.c
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/dm/io_req.h

This reverts commit a67a85c70dc55dfaf39b65b059e09d33e31b72ea.
this revert only for release_2.2 branch to fix WaaG reboot failed，
restore memset in create_vm because sub-module use uninitialized data
in vm structure after reboot

Revert "hv:refine vm & vcpu lock" for release2.2_branch

---

doc/develop.rst
doc/tutorials/using_yp.rst

meta-acrn is a Yocto Project layer repo with recipes for building a
Service and User VM OS using Yocto Project.  While the information there
is sparse, for the experienced YP developer is might be enough.

doc: add pointers to meta-acrn layer repo docs

---

misc/acrn-config/acpi_gen/acpi_const.py
misc/acrn-config/acpi_gen/asl_gen.py
misc/acrn-config/acpi_gen/bin_gen.py
misc/vm_configs/acpi/template/dsdt_tsn_otn1.asl
misc/vm_configs/scenarios/hybrid/ehl-crb-b/VM0/xsdt.asl
misc/vm_configs/scenarios/hybrid/nuc7i7dnb/VM0/xsdt.asl
misc/vm_configs/scenarios/hybrid/whl-ipc-i5/VM0/xsdt.asl
misc/vm_configs/scenarios/hybrid/whl-ipc-i7/VM0/xsdt.asl
misc/vm_configs/scenarios/hybrid_rt/ehl-crb-b/VM0/dsdt.asl
misc/vm_configs/scenarios/hybrid_rt/ehl-crb-b/VM0/xsdt.asl
misc/vm_configs/scenarios/hybrid_rt/whl-ipc-i5/VM0/xsdt.asl
misc/vm_configs/scenarios/hybrid_rt/whl-ipc-i7/VM0/xsdt.asl
misc/vm_configs/scenarios/logical_partition/ehl-crb-b/VM0/xsdt.asl
misc/vm_configs/scenarios/logical_partition/ehl-crb-b/VM1/xsdt.asl
misc/vm_configs/scenarios/logical_partition/nuc7i7dnb/VM0/xsdt.asl
misc/vm_configs/scenarios/logical_partition/nuc7i7dnb/VM1/xsdt.asl
misc/vm_configs/scenarios/logical_partition/whl-ipc-i5/VM0/xsdt.asl
misc/vm_configs/scenarios/logical_partition/whl-ipc-i5/VM1/xsdt.asl
misc/vm_configs/scenarios/logical_partition/whl-ipc-i7/VM0/xsdt.asl
misc/vm_configs/scenarios/logical_partition/whl-ipc-i7/VM1/xsdt.asl

add TSN device OTN1 config into offline ACPI table for TSN device
passthrough to pre-launched RTVM.

acrn-config: add OTN1 device config in offline ACPI table

---

misc/acrn-manager/README.rst

Fix the folder name where the 'acrn-manager' source code is located.
Replace instances of 'UOS' by 'User VM'
Other minor text updates to improve readability

doc: fix source code folder and use 'User VM'

---

hypervisor/arch/x86/guest/vm.c

The commit of da81a0041d72e78a340a183c6531e67e763c4efa
"HV: add e820 ACPI entry for pre-launched VM" introduced a issue that the
base_hpa and remaining_hpa_size are also calculated on the entry of 32bit
PCI hole which from 0x80000000 to 0xffffffff, which is incorrect;

[Release 2.2]HV: correct hpa calculation for pre-launched VM

---

doc/develop.rst
doc/developer-guides/hld/ivshmem-hld.rst
doc/tutorials/enable_ivshmem.rst

Ivshmem hv-land solution emulates the ivshmem device in hypervisor
and the shared memory is reserved in the hypervisor's memory space.
And it can provide inter-vm communication for both pre-launched and
post-launched VMs.
This patch introduces the ivshmem hv-land solution including what
ivshmem hv-land is and how to use it.

doc: add ivhshmem hv-land introduction

---

hypervisor/arch/x86/guest/vm.c

The commit of da81a0041d72e78a340a183c6531e67e763c4efa
"HV: add e820 ACPI entry for pre-launched VM" introduced a issue that the
base_hpa and remaining_hpa_size are also calculated on the entry of 32bit
PCI hole which from 0x80000000 to 0xffffffff, which is incorrect;

HV: correct hpa calculation for pre-launched VM

---

doc/tutorials/using_hybrid_mode_on_nuc.rst
doc/tutorials/using_partition_mode_on_nuc.rst

We use offline ACPI generator tool to create offline ACPI tables for
pre-launched VMs. Update getting start guide for hybrid and logical
partition mode to launch pre-launched VMs with offline ACPI binaries.

doc: update pre-launched VMs launched with offline ACPI

---

misc/acrn-config/board_config/misc_cfg_h.py
misc/acrn-config/launch_config/com.py
misc/acrn-config/library/launch_cfg_lib.py
misc/acrn-config/library/scenario_cfg_lib.py

When generate the launch scripts, the pm_by_vuart setting of pm_notify_channel
in launch setting should be according to the config of SOS vuart1.
Tracked-On: #5154

acrn-config: fix the issue of generating the vuart with incorrect name

---

doc/tutorials/enable_ivshmem.rst

The maximum number of ivshmem shared memory regions cannot exceed 8

doc: Add note about the maximum number of regions for hv-land

---

devicemodel/core/main.c
devicemodel/core/sw_load_common.c
devicemodel/hw/platform/acpi/acpi.c
devicemodel/include/dm.h
devicemodel/include/ptct.h
devicemodel/include/sw_load.h
hypervisor/Makefile
hypervisor/arch/x86/Kconfig
hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/guest/ept.c
hypervisor/arch/x86/mmu.c
hypervisor/arch/x86/ptcm.c
hypervisor/boot/include/acpi.h
hypervisor/include/arch/x86/ptcm.h
hypervisor/include/arch/x86/ptct.h

Added the support of pseudo-SRAM (pSRAM) for RTVM on TGL.
For Yocto RTOS having TCC drivers integrated in, the drivers can make use of pSRAM to greatly improve the performance of RT apps on TGL platforms.

[TGL] Add pseudo-SRAM support for RTVM (phase-1)

---

misc/vm_configs/xmls/board-xmls/tgl-rvp.xml
misc/vm_configs/xmls/config-xmls/tgl-rvp/hybrid_rt.xml

add the TSN device in tgl-rvp board XML and configure it to
passthrough to pre-launched VM for hybrid_rt scenario on tgl-rvp.

acrn-config: add the TSN device passthrough to pre-launched VM on TGL

---

hypervisor/arch/x86/configs/pci_dev.c

It is found that SOS will reset the PCI devices under PCI
bridge 00:1c.0 when 00:1c.0 is exposed to SOS. If a PCI
device under 00:1c.0 is passed through to pre-launched VM,
it will be reset by SOS at startup hence the passthrough
will not work properly. This patch provides a workaround
by hiding PCI bridge 00:1c.0 from SOS in this case.

Hide pci bridge 00:1C.0

---

hypervisor/common/hypercall.c

We remove the UNCACHED bit for pSRAM EPT memmap segment, otherwise access to pSRAM region may bypass pSRAM.

hv: remove UNCACHED for pSRAM EPT memmap segment

---

doc/reference/hardware.rst

Tiger Lake and Elkhart Lake processors added to the document as
supported processors but with no recommended platform.

doc: update HW to include new processors

---

devicemodel/core/vmmapi.c
devicemodel/hw/pci/virtio/virtio.c
devicemodel/hw/pci/virtio/virtio_console.c

Add Null pointer check in init vq ring and add vq ring descriptor
check in case cause Nullpointer exception.
Tracked-On: #5355
Reviewed-by: Wang, Yu1 <yu1.wang@intel.com>

dm: fix fault Injection into VirtIO console backend

---

hypervisor/arch/x86/ptcm.c
hypervisor/include/arch/x86/mmu.h

1. Add null-ptr check for security
2. prevent WBINVD after pSRAM is initialized.

Add null-ptr check and prevent WBINVD after pSRAM is initialized.

---

doc/getting-started/building-from-source.rst

during build, "TARGET_DIR=xxx" works well
Signed-off-by: guoqingxz <guoqingx.q.zhang@intel.com>

doc: update doc for #5157 is closed as fix

---

doc/getting-started/building-from-source.rst
doc/getting-started/rt_industry_ubuntu.rst

From V2.2, we use the iasl tool to compile offline ACPI binary for pre-launched VMs while building ACRN,
so we need to install the iasl tool in the ACRN building environment. This doc is to describe how
to install the iasl tool and specify the version of iasl at the chapter Install build tools and dependencies.
Tracked-On: #5350

doc: add the iasl dependence

---

doc/_templates/breadcrumbs.html
doc/_templates/layout.html
doc/conf.py

As a DX improvement in the documentation, include the release version
(or Latest) in the breadcrumb header on every page.  This can help
readers know which release version documentation they're using.

doc: update breadcrumb to include release version

---

misc/acrn-config/launch_config/com.py
misc/acrn-config/library/launch_cfg_lib.py
misc/vm_configs/xmls/config-xmls/ehl-crb-b/hybrid_rt_launch_1uos_waag.xml
misc/vm_configs/xmls/config-xmls/nuc7i7dnb/hybrid_rt_launch_1uos_waag.xml
misc/vm_configs/xmls/config-xmls/tgl-rvp/hybrid_rt_launch_1uos_waag.xml
misc/vm_configs/xmls/config-xmls/whl-ipc-i5/hybrid_rt_launch_1uos_waag.xml
misc/vm_configs/xmls/config-xmls/whl-ipc-i7/hybrid_rt_launch_1uos_waag.xml

acrn-config: Provide post launch xml for hybrid scenario
There is no default xml for hybrid_rt to to generate the
script of posted launch WaaG.
Tracked-On: #5336

Add default hybrid rt xml

---

devicemodel/core/main.c

Fix typo error "--apicdev_pt HID" to pass through a TPM device. Fix it to
"--acpidev_pt HID"
Tracked-On: #5401

dm: fix typo error to pass through TPM device

---

doc/developer-guides/c_coding_guidelines.rst

- add a rule for "U" suffix
- release the restrictions about function documentation

doc: update coding guidelines

---

misc/acrn-config/board_config/vbar_base_h.py
misc/acrn-config/scenario_config/pci_dev_c.py

Add functionality to get free vbar base for the vmsix devices.
- The devices size is 4k.
- The mmio range for non SOS VM is 2G to 4G
- The mmio range for SOS is depended on the range which is assigned to
PCI bus hostbridge
- The next vbar index is based on last device vbar index vbar_i
Tracked-On: #5422

acrn-config: Get vbar base and index for vmsix supported devices

---

misc/vm_configs/xmls/board-xmls/tgl-rvp.xml
misc/vm_configs/xmls/config-xmls/tgl-rvp/hybrid_rt.xml

update tgl-rvp.xml for TGL boards flashing IFWI with TSN version
to enable embedded tsn device, and passthru the embedded tsn device
for pre-launched RTVM on hybrid-rt scenario of TGL boards.

acrn-config: passthru embeded tsn device for pre-launched RTVM

---

devicemodel/core/pm_vuart.c
misc/life_mngr/life_mngr.c

pm_vuart stops listening and relays the message right away if it encounters EAGAIN during read(). This causes the messages relayed to be fragmented.
Only relay the message when it encounters a null character or a newline character, or when the buffer is full.
Tracked-On: #5429

Correctly handle EAGAIN in pm_vuart when listening

---

hypervisor/dm/vpci/vmsix_on_msi.c

Currently vmsix over msi is not working for pre-launched VM. The reason is the Bar GPA is invalid. acrn-config is enhanced to calcuate/allocate a valid MMIO region for the vmsix Bar. This patch is used to assign the GPA generated by acrn-config to vmsix Bar when vdev init.
This patch also refines the code in init_vmsix_on_msi to use pci_vdev_write_vbar instead of vdev_pt_write_vbar because no mapping/ unmapping needs to be done when vdev init.
Tracked-On: #5316

Vmsix vbar gpa

---

hypervisor/include/arch/x86/guest/ept.h
hypervisor/include/common/ptdev.h

The new (1.8.17) release of doxygen is complaining about errors in the
doxygen comments that were's reported by our current 1.8.13 release.
Let's fix these now. In a separate PR #5412 we'll also update some doxygen
configuration settings that will be obsolete, in preparation for moving
to this newer version.
[External_System_ID]ACRN-6774
Tracked-On: #5385

doc: fix doxygen 1.8.17 issues

---

misc/vm_configs/xmls/board-xmls/cfl-k700-i7.xml
misc/vm_configs/xmls/config-xmls/cfl-k700-i7/hybrid_rt.xml
misc/vm_configs/xmls/config-xmls/cfl-k700-i7/industry.xml

Changes:
1. assign 3 CPUs for WaaG on hybrid_rt scenario;
2. Passthrough NVME@9:0.0 for VM0 on hybrid_rt scenario;
3. Change rootfs from partition2 to partition3;
Tracked-On: #5390
Signed-off-by: Liang Yi <yi.liang@intel.com>

acrn-config: minor change scenario xml for cfl-k700-i7

---

misc/acrn-config/board_config/vbar_base_h.py

Multiple devices could be nested under the same range. Skip remove if
the device is removed already
Tracked-On: #5437
Signed-off-by: Yang,Yu-chu <yu-chu,yang@intel.com>

acrn-config: fix the bug of resolved nested mmio address

---

devicemodel/hw/pci/uart.c
hypervisor/Makefile
hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/guest/vm.c
hypervisor/common/hypercall.c
hypervisor/dm/vpci/ivshmem.c
hypervisor/dm/vpci/vmcs9900.c
hypervisor/dm/vuart.c
hypervisor/include/arch/x86/vm_config.h
hypervisor/include/dm/ivshmem.h
hypervisor/include/dm/vmcs9900.h
hypervisor/include/dm/vuart.h
hypervisor/include/hw/pci.h
misc/hv_prebuild/vm_cfg_checks.c

How to use:
Add pci-vuart in vm_config. Because PCI vUART are also virtual pci devices, their config information are in acrn_vm_pci_dev_config, just like that:
struct acrn_vm_pci_dev_config vm0_pci_devs[] = {
{
.emu_type = PCI_DEV_TYPE_HVEMUL,
.vbdf.bits = {.b = 0x00U, .d = 0x04U, .f = 0x00U},
.vdev_ops = &vmcs9900_ops,
.vbar_base[0] = 0x80001000, /*MMIO bar*/
.vbar_base[1] = 0x80002000, /*MSIX bar*/
.vuart_idx = 2,
.t_vuart.vm_id = 1U,
.t_vuart.vuart_id = 1U,
},
}
If create for post-launched VM, use '-s,<slot>,uart,vuart_idx:<val>' acrn-dm option

PCI vUART Support in HV

---

hypervisor/dm/vpci/vpci.c

cleanup vpci structure when shutdown_vm to avoid use uninitialized data
after reboot.

cleanup vpci structure when shutdown_vm

---

misc/acrn-config/launch_config/com.py

when fix the issue of _PM_SystemS5 with life_mngr fail,
the vuart1(tty) item was devided into two parts, the last
part "/dev/tty*" which need to get will be added to the
end, so it should be handled singly, but it will be added
to other item too, such as vuart1(pty).
Tracked-On:#5366

acrn-config: fix the wrong vuart name in launch script

---

doc/.known-issues/doc/dupdecl.conf
doc/.known-issues/doc/kerneldoc.conf
doc/glossary.rst

Preparing for upgrading to newer versions of doc building tools
including sphing, doxygen, breathe, docutils, etc.  This PR's changes
still work find with the older tool versions, but should eliminate
issues found while moving to newer tool versions (later).

doc: more prep for upgrading doc build tools

---

hypervisor/Makefile
hypervisor/acpi_parser/acpi_ext.c
hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/guest/ept.c
hypervisor/arch/x86/guest/virtual_cr.c
hypervisor/arch/x86/guest/vmexit.c
hypervisor/arch/x86/ioapic.c
hypervisor/arch/x86/mmu.c
hypervisor/arch/x86/page.c
hypervisor/arch/x86/ptcm.c
hypervisor/arch/x86/vtd.c
hypervisor/boot/include/acpi.h
hypervisor/debug/npk_log.c
hypervisor/debug/uart16550.c
hypervisor/dm/vgpio.c
hypervisor/hw/pci.c
hypervisor/include/arch/x86/mmu.h
hypervisor/include/arch/x86/ptcm.h
hypervisor/include/arch/x86/ptct.h

Add pSRAM support in the HV part to initialize pSRAM on all cores. This's the Part 1.
Part 2 will PR later which is used to enable PTCM on pre/post-launched RTVM.
v5:
1. refine global ptcm_command_func
2. remove unnecessary assignment when parse PTCT ACPI Table.
v4:
1. Use bitmap to check whether the pSRAM has initialized on all CPUs.
2. Change NX page table attribute and flush TLB for all the PTCM binary area.
3. Fix a bug SOS could wbinvd the pSRAM when the post-launched RTVM hasn't created.
4. Add Kconfig to configure pSRAM
5. Other minor code/commit refine.
v3:
1. detial comment why we could remove wbinvd when guest change CR0.CD
2. refine init_psram and prase_ptct according Eddie'comments
3. remove #UD inject for INVD vmexit handle
4. add limitation now we only support L3 pSRAM and …

Ptcm: Add pSRAM support Part 1

---

devicemodel/core/main.c
devicemodel/core/sw_load_common.c
devicemodel/hw/platform/acpi/acpi.c
devicemodel/include/dm.h
devicemodel/include/ptct.h
devicemodel/include/sw_load.h
hypervisor/arch/x86/Kconfig
hypervisor/arch/x86/guest/ve820.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/guest/vmexit.c
hypervisor/common/hypercall.c

Add pSRAM support to enable PTCM on pre/post-launched RTVM. This's the Part 2.
v5:
refine ptct e820 add in acrn-dm
other minor refine according to Yu'comments.
v4:
Use bitmap to check whether the pSRAM has initialized on all CPUs.
Change NX page table attribute and flush TLB for all the PTCM binary area.
Fix a bug SOS could wbinvd the pSRAM when the post-launched RTVM hasn't created.
Add Kconfig to configure pSRAM
Other minor code/commit refine.
v3:
detial comment why we could remove wbinvd when guest change CR0.CD
refine init_psram and prase_ptct according Eddie'comments
remove #UD inject for INVD vmexit handle
add limitation now we only support L3 pSRAM and pass through it to one guest
add two TODOs: one for we may use SMP to flush TLB and do pSRAM initialzation on APs,
one for add …

Ptcm: Ptcm: Add pSRAM support Part 2

---

misc/acrn-config/acpi_gen/asl_gen.py
misc/acrn-config/hv_config/board_defconfig.py
misc/acrn-config/hv_config/hv_item.py
misc/acrn-config/library/hv_cfg_lib.py
misc/acrn-config/scenario_config/scenario_cfg_gen.py
misc/vm_configs/xmls/config-xmls/generic/hybrid_rt.xml
misc/vm_configs/xmls/config-xmls/template/HV.xml
misc/vm_configs/xmls/config-xmls/tgl-rvp/hybrid_rt.xml

remove PSRAM_PASSTHROUGH_PRE_RTVM config which is not used in
PSRAM config.
Tracked-On: #5418

acrn-config: remove PSRAM_PASSTHROUGH_PRE_RTVM in PSRAM config

---

doc/conf.py

Some ACRN docs (in particular the HLD) has content nested more than the
4 levels shown in the sidebar navigation.  So when looking at those
documents, it's hard to get to next chapter.  Bring back the
previous/next links to fix this situation.

doc: bring back prev/next buttons

---

misc/acrn-config/board_config/vbar_base_h.py

qemu xml has no devices list. Tool will receive the empty devices list while parsing the "platform" xml. Remove the error of resolved nested mmio address window that the input couldn't be None. Simply return an None list.
Tracked-On:#5454

acrn-config: removed_nested returns None instead return Error

---

devicemodel/core/sw_load_common.c
devicemodel/hw/pci/passthrough.c
devicemodel/include/sw_load.h

Windows graphic driver obtains DSM address from in-BAR mmio register
which has passthroughed. Not like the other platforms obtained from
pci configure space register which has virtualized. So TGL has to
keep identical mapping to avoid trap mmio BAR to do the emulation.
To keep simple, this patch hardcode the TGL DSM region in vE820
table, this will cause memory waste here. In the near future, we
need refine the entire vE820 logic as it is hard to maintained
due to many reserved regions have introduced in recently.
Signed-off-by: Sun Peng <peng.p.sun@intel.com>
Tracked-On: #5461

DM: gvt: Identical mapping for GPU DSM

---

doc/genindex.rst
doc/index.rst

Sphinx generates a full-site index (headings, terms, function names,
etc.) but we haven't been linking to it.  This is a tricky way to get
the site index added to the left nav that appears to work, by creating a
genindex.rst that we can link to in the site toctree so it shows up in
the leftnav, but the generated genindex.html for the dummy genindex.rst
will be overwritten by the sphinx created genindex.html with the
full-site index.

doc: add sphinx-generated index to leftnav

---

doc/conf.py
doc/developer-guides/contribute_guidelines.rst
doc/developer-guides/doc_guidelines.rst
doc/developer-guides/hld/virtio-net.rst
doc/extensions/eager_only.py
doc/extensions/link_roles.py
doc/index.rst
doc/introduction/index.rst
doc/tutorials/setup_openstack_libvirt.rst
misc/acrn-manager/README.rst

Links to files in the GitHub repo's master branch should be to the files
within the branch being generated.  For example, in the v2.1
documentation, links should be to the v2.1 branch contents.  (Previously
links were being made to the master branch in all our archived content.)
This creates a problem when we want to remove an obsolete file in the
master branch but can't because older documentaiton incorrectly depends
on it.
This new extension defines a :acrn_file: and :acrn_raw: role that will
create links to the given file within the current commit branch.

doc: add extension to create files and raw links

---

hypervisor/common/hypercall.c

Hypercall handlers for post-launched VMs automatically grab the vm_lock
in dispatch_sos_hypercall(). Remove the use of vm_lock inside the
handler.
Tracked-On: #5411

hv: remove vm_lock in hcall_destroy_vm()

---

devicemodel/hw/pci/virtio/virtio.c

paddr_guest2host can return NULL, but code paths in virtio
are not checking the return value.
_vq_record() initializes iov_base pointer using paddr_guest2host()
but there is nothing in the flow that checks for NULL.
Chane _vq_record to return -1 in case the address translation
has failed.
Tracked-On: #5452

dm: virtio: check for paddr_guest2host return value

---

misc/acrn-config/scenario_config/pci_dev_c.py

Bug fix:
1. The bdf were inserted in decimal. Fix it with hexadecimal
format.
2. The vuart vbdf will only take the dev which no used bdf has
the same dev. For example: If 00:01.1 is in used but not 00:01.0,
vuart vbdf will skip 00:01.0 and look for 00:02.0, 00:03.0 and so on.
Tracked-On: projectacrn#5482

acrn-config: insert vbdf in hex format and vuart vbdf logic

---

misc/acrn-config/scenario_config/vm_configurations_c.py

The legacy vuart0 of any VMs inserts its base address declaration
anyway without checking whether it's disabled or enabled, and the
com base is hardcoded no matter what is specified in xmls.
Pull the legacy vuart enablement status based on scenario xml.
This reverts commit a8fe9b906afc2d0c4bb10e9193f0eba7a629b32e
Tracked-on: #5470

acrn-config: insert legacy vuart0 base by its enablement status

---

devicemodel/core/main.c
devicemodel/core/sw_load_common.c
devicemodel/core/sw_load_ovmf.c
devicemodel/include/dm.h
devicemodel/include/sw_load.h
doc/user-guides/acrn-dm-parameters.rst

In addition to a single OVMF image (OVMF.fd), split images (OVMF_CODE.fd, OVMF_VARS.fd) can be used to facilitate VM management.
From the OVMF Whitepaper:
> The variable store and the firmware executable are also available in the build output as separate files entitled: "OVMF_VARS.fd" and "OVMF_CODE.fd". This enables central management and updates of the firmware executable, while each virtual machine can retain its own variable store.

Support OVMF split images

---

misc/vm_configs/xmls/config-xmls/tgl-rvp/hybrid_rt.xml

Increase CONFIG_MAX_EMULATED_MMIO_REGIONS to 32, for more pci-vuarts.
Each pci-vuart vdev need 2 mmio BARs, if there are 8 pci-vuarts, they
need emulate 16 mmio regions.
But by default CONFIG_MAX_EMULATED_MMIO_REGIONS=16, that is not enough.
Tracked-On: #5491

TGL: Fix sos can't boot with 6 pci-vuarts

---

hypervisor/dm/vpci/vmcs9900.c

When wrong BAR address is set for pci-vuart, OS may assign a
new BAR address to it. Pci-vuart BAR can't be reprogrammed,
for its fixed value.
Remove the fixed value of pci-vuart.
Tracked-On: #5491

Fix: HV: VM OS failed to assign new address to pci-vuart BARs

---

hypervisor/arch/x86/guest/pm.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/guest/vm_reset.c
hypervisor/include/arch/x86/guest/vm.h

It is possible for more than one vCPUs to trigger shutdown on an RTVM.
We need to avoid entering VM_READY_TO_POWEROFF state again after the
RTVM has been paused or shut down.
Also, make sure an RTVM enters VM_READY_TO_POWEROFF state before it can
be paused.
Tracked-On: #5411

hv: pm: avoid duplicate shutdowns on RTVM

---

hypervisor/arch/x86/guest/vm.c

when HW platform like EHL use mmio type serial, do not need to hide
serial IO port for SOS
Tracked-On: #5498

Fix: do not need to hide IO 0x3f8 for SOS on EHL

---

hypervisor/common/hypercall.c
hypervisor/dm/vpci/ivshmem.c
hypervisor/dm/vpci/vpci.c

- fix bug in 'hcall_destroy_vdev()', the availability of
vpci device shall be checked on 'target_vm".
- refine 'vpci_update_one_vbar()' to avoid potential NULL
pointer access.
- refine destroy_ivshmem_vdev(), umap bars based on actual
enabled bar num of ivshmem devices.
Tracked-On: #5490

hv: bugfix for hv-emulated device de-init

---

hypervisor/arch/x86/configs/pci_dev.c

It is found that SOS will reset the PCI devices under PCI
bridge 00:1c.0 when 00:1c.0 is exposed to SOS. If a PCI
device under 00:1c.0 is passed through to pre-launched VM,
it will be reset by SOS at startup hence the passthrough
will not work properly. This patch provides a workaround
by hiding PCI bridge 00:1c.0 from SOS in this case.
Tracked-On: #5346

hv: pci: Hide PCI bridge 00:1c.0 from SOS

---

hypervisor/common/hypercall.c
hypervisor/dm/vpci/ivshmem.c
hypervisor/dm/vpci/vpci.c

This patch is ported from mainline for 2.3 branch 
- fix bug in 'hcall_destroy_vdev()', the availability of
vpci device shall be checked on 'target_vm".
- refine 'vpci_update_one_vbar()' to avoid potential NULL
pointer access.
Tracked-On: #5508

hv: bugfix for hv-emulated device de-init -v2.3

---

hypervisor/dm/vpci/ivshmem.c

Memory BAR of ivshmem device is 64-bit, 2 BAR registers
are used, counting in one 32-bit MMIO bar and and one
32-bit vMSIX table bar, number of bars "nr_bars" shall
be 4 instead of 3.
Tracked-On: #5490

hv: fix nr_bars for hv-land ivshmem devices

---

devicemodel/core/main.c

Update and light clean-up of the buit-in list of arguments from 'acrn-dm'
* Added options in the top part (list with no explanation)
* A couple of typos fixed
* A couple of options put inside an '#ifdef' statement
Tracked-On: #5445

dm: update acrn-dm built-in list and description of args

---

devicemodel/core/pm_vuart.c
devicemodel/hw/pci/ahci.c
devicemodel/hw/pci/xhci.c

paddr_guest2host may return NULL, this patch checks the return value
to avoid null pointer dereference.
Tracked-On: #5514

DM: Add the return value check in case cause Null pointer exception

---

doc/tutorials/enable_ivshmem.rst

To enable the hv_land ivshmem for post-launched vm, the lanch script
needs to be cofigured accordingly.

doc: update the steps of enable ivshmem

---

doc/.known-issues/doc/dupdecl.conf
doc/conf.py

Breathe and doxygen work best for C++, but we're using C.  This shows up
as API documentaiton having a C++ flavor (modules and classes) instead
of the expected C flavor.  We really need to upgrade the versions of
doxygen and breathe to newer versions, and this configuration tweak
prepares for this.  (It will need CI coordination to update these tools,
but the changes in this PR are compatible with the current older tools.)

doc: fix breathe config for C vs CPP

---

doc/user-guides/acrn-dm-parameters.rst

Correct the GVT-g parameters description in the 'ACRN Device Model parameters'
document. The order was the wrong way around.
Tracked-On: #5528

doc: correct 'gvtg' parameters for acrn-dm

---

doc/tutorials/running_ubun_as_user_vm.rst

Add missing space in the document describing how to use Ubuntu as a User VM OS.

doc: correct typo (missing space)

---

hypervisor/arch/x86/Kconfig

hv: disable AC for split-lock by default.
This patch disables the AC for split-lock check. Only for 2.3.
Tracked-On: #4765

Disable AC for split-lock by default

---

misc/vm_configs/scenarios/hybrid/ehl-crb-b/pci_dev.c
misc/vm_configs/scenarios/hybrid/nuc7i7dnb/pci_dev.c
misc/vm_configs/scenarios/hybrid/whl-ipc-i5/pci_dev.c
misc/vm_configs/scenarios/hybrid/whl-ipc-i7/pci_dev.c
misc/vm_configs/scenarios/hybrid_rt/cfl-k700-i7/pci_dev.c
misc/vm_configs/scenarios/hybrid_rt/ehl-crb-b/pci_dev.c
misc/vm_configs/scenarios/hybrid_rt/whl-ipc-i5/pci_dev.c
misc/vm_configs/scenarios/hybrid_rt/whl-ipc-i7/pci_dev.c
misc/vm_configs/scenarios/industry/cfl-k700-i7/pci_dev.c
misc/vm_configs/scenarios/industry/ehl-crb-b/pci_dev.c
misc/vm_configs/scenarios/industry/nuc7i7dnb/pci_dev.c
misc/vm_configs/scenarios/industry/whl-ipc-i5/pci_dev.c
misc/vm_configs/scenarios/industry/whl-ipc-i7/pci_dev.c

update all default pci_dev.c under misc/vm_configs/scenarios/<scenario>/<platform> for non-xml compilation
Tracked-On: #5425
Signed-off-by: Yang Yu-chu <yu-chu.yang@intel.com>

acrn-config: update default pci_dev.c

---

misc/life_mngr/life_mngr.c

After the SOS socket is closed, read() returns instantly with a return
value of 0. This causes life_mngr to flood the log file with the
following messages:
received msg []
received msg []
received msg []
...
Exit the program directly now if this is detected.
Tracked-On: #5429

misc: life_mngr: prevent log flooding after SOS socket is closed

---

devicemodel/hw/pci/virtio/virtio_console.c

The read should not continue if the virtqueue is not ready.
Tracked-On: #5544

dm: virtio_console: read only when the virtqueue is ready.

---

hypervisor/arch/x86/guest/virtual_cr.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vmexit.c
hypervisor/arch/x86/seed/seed.c

From SDM Vol.2C - XSETBV instruction description,
If CR4.OSXSAVE[bit 18] = 0,
execute "XSETBV" instruction will generate #UD exception.
From SDM Vol.3C 25.1.1,#UD exception has priority over VM exits,
So if vCPU execute "XSETBV" instruction when CR4.OSXSAVE[bit 18] = 0,
VM exits won't happen.
While hv inject #GP if vCPU execute "XSETBV" instruction
when CR4.OSXSAVE[bit 18] = 0.
It's a wrong behavior, this patch will fix the bug.
Tracked-On: #4020

hv: vmexit: refine xsetbv_vmexit_handler API

---

hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/irq.c
hypervisor/arch/x86/rdt.c
hypervisor/common/hypercall.c
hypervisor/debug/dbg_cmd.c
hypervisor/dm/vpci/vsriov.c

While following two styles are both correct, the 2nd one is simpler.
bool is_level_triggered;
1. if (is_level_triggered == true) {...}
2. if (is_level_triggered) {...}
This patch cleans up the style in hypervisor.

hv: coding style clean-up related to Boolean

---

misc/hv_prebuild/vm_cfg_checks.c
misc/tools/acrn-crashlog/acrnprobe/Makefile

The latest gcc 10.x changes the default to '-fno-common'. This causes a couple
of build failures in ACRN. This patch changes the default behaviour to
'-fcommon'.
More details on that change can be found here:
https://gcc.gnu.org/gcc-10/porting_to.html
Tracked-On: #5553
Tracked-On: #5549

misc: adjust compiler options for gcc-10

---

doc/tutorials/acrn_configuration_tool.rst

Acrn introduces pci based vuart. Update the existing vuarts and add the
pci based vuart description
1. rename existing vuarts to legacy_vuart
2. add console and communication vuarts general desciption
- the console vuart is similar to legacy_vuart0 but only contains subtag "base"
- the communication vuart is similar to legacy_vuart1 but only contains subtags
"base", "target_vm_id" and "target_uart_id"

doc: update configuration tool description of vuarts

---

Makefile

Fix the formatting for the cfg.log (build/hypervisor/cfg.log) generation. The
'echo' command uses '-e' but that gets put as-is into the log file. Removing
the '-e' argument fixes it.
Tracked-On: #5561

hv: fix formatting for cfg.log output

---

misc/acrn-config/launch_config/com.py

The "virtio-hyper_dmabuf" is no longer needed for PREEMPT-RT LINUX.
Remove it from launch script.
Tracked-On: #5565

acrn-config: remove hardcoded device in launch script

---

doc/getting-started/rt_industry_ubuntu.rst

Small updates to the Getting Started Guide:
* Add a missing command
* Add a note for the Grub configuration
* Make the 'blkid' hint consistent with the environment
Tracked-On: #5594

doc: small updates to the GSG

---

misc/acrn-config/library/scenario_cfg_lib.py

The function validate if the legacy vuart1 and its target_vm_id are
paired. However, it dynamically modifies the tracking list. It would try
to access an invalid keys which has been removed.
Refine the logic to add a valid paired legacy vuart1 to new list.
Tracked-On: #5592

acrn-config: fix the logic of get_vuart1_vmid

---

doc/conf.py

Automatically update the copyright year on the page footers to be
2018-[current_year] when generating documentation.

doc: automate copyright year footer

---

misc/vm_configs/scenarios/hybrid_rt/ehl-crb-b/misc_cfg.h
misc/vm_configs/xmls/config-xmls/ehl-crb-b/hybrid_rt.xml

some RT related boot arguments are needed for preempt-rt linux.
add them in configure file built in for EHL board.
for EHL, it is booted with SBL, not like GRUB, extra boot arguments
can be added; so better to be built in.
Tracked-On: #5606

misc: add more boot arguments for EHL preempt-rt

---

misc/acrn-config/library/board_cfg_lib.py

add cfl-k700-i7 into tpm supprted boards to enable tpm
passthru to the pre-launched vm.
Tracked-On: #5614

acrn-config: add cfl-k700-i7 into tpm supported boards

---

doc/scripts/requirements.txt

Specify the version of 'sphinx-tabs' to be installed in order
to be able to build the documentation. Without this, the latest
is installed but is incompatible with 'sphinx==1.7.7' as specified
in our doc/scripts/requirements' file.

doc: specify the version of 'sphinx-tabs' to install

---

doc/tutorials/acrn_on_qemu.rst

Fix the 'cp' operation in the instructions explaining
how to build the kernels.

doc: fix 'cp' command in instructions

---

doc/tutorials/acrn-secure-boot-with-grub.rst

Remove 'x' attribute of this file and one more minor fix.

doc: remove exec attribute for 'acrn-secure-boot-with-grub.rst'

---

doc/tutorials/using_windows_as_uos.rst

code-block content wasn't indented in a recent change so wasn't included
in the code-block formatting

doc: fix formatting in windows as UOS doc

---

doc/.known-issues/doc/dupdecl.conf
doc/conf.py

Update known-issues list to eliminate known warnings for duplicate
declaration warnings because of breathe/sphinx upgrades.
Update conf.py to check sphinx version and use appropriate way to
include extra javascript and css files depending on the version.
Both of these changes will allow the old and new doc tools to not show
unanticipated warnings or errors and allow for a smooth upgrade to the
CI system (and contributors local doc builds).

doc: prep for upgrading doc build tools

---

doc/scripts/requirements.txt
doc/tutorials/docbuild.rst

Update the documentation for how to build ACRN documents
(tutorial/docbuild.rst) and the scripts/requirements.txt that lists the
tested configuration of python tools being used.
Previous merged commits have already been made to handle doc builds with
the previous (2.3 documented configuration and the new v2.4
configuration.

doc: upgrade doc-build tools

---

doc/tutorials/docbuild.rst

Fix a typo in the `docbuild.rst` file.

doc: fix typo in docbuild.rst

---

misc/vm_configs/sample_launch_scripts/nuc/launch_vxworks.sh

This patch basically reverts commit 22f24c229b48a98e70572e7e25b1de2077fbd198
since virtio polling mode is still not ready in VxWorks official build.
commit 22f24c229b48a98e70572e7e25b1de2077fbd198
Author: Kaige Fu <kaige.fu@intel.com>
Date:   Thu Jun 13 09:24:07 2019 +0000
DM: Samples: Enable VxWorks as hard-rt VM
This patch adds --lapic_pt option to launch VxWorks as hard-rt VM.
End user could enable VxWorks as hard-rt VM with acrn-config tool, or add
below acrn-dm parameters in launch script:
" --lapic_pt \
--virtio_poll 1000000 \
-U $rtvm_uuid"

DM: samples: Enable VxWorks as normal VM by default

---

devicemodel/hw/pci/virtio/virtio_gpio.c

To avoid flood messages in virtio_irq_evt_notify.
Tracked-On: #5635

dm: virtio-gpio: avoid flood messages in virtio_irq_evt_notify

---

hypervisor/arch/x86/guest/vcpuid.c
hypervisor/arch/x86/guest/virtual_cr.c

Windows64 seems only support processor which has MCE (Machine Check Error)
feature.
Tracked-On: #5638

hv: vcpuid: expose mce feature to guest

---

hypervisor/arch/x86/guest/splitlock.c

When "signal_event" is called, "wait_event" will actually not block.
So it is ok to remove this line.

hv: remove bitmap_clear_lock of split-lock after completing emulation

---

hypervisor/dm/vpci/ivshmem.c
hypervisor/dm/vpci/pci_pt.c
hypervisor/dm/vpci/vdev.c
hypervisor/dm/vpci/vmsix_on_msi.c
hypervisor/include/dm/vpci.h
hypervisor/include/hw/pci.h

The commit 'Fix: HV: VM OS failed to assign new address to pci-vuart
BARs' need more reshuffle.
Tracked-On: #5491
Signed-off-by: Eddie Dong <eddie.dong@intel.com>

Fix: HV: keep reshuffling on VBARs

---

hypervisor/arch/x86/guest/assign.c

Now, we use hash table to maintain intx irq mapping by using
the key generated from sid. So once the entry is added,we can
not update source ide any more. Otherwise, we can't locate the
entry with the key generated from new source ide.
For source id change, remove_remapping/add_remapping is used
instead of update source id directly if entry was added already.
Tracked-On: #5640

hv: ptirq: Shouldn't change sid if intx irq mapping was added

---

misc/acrn-config/board_config/misc_cfg_h.py
misc/acrn-config/board_config/vbar_base_h.py
misc/acrn-config/library/scenario_cfg_lib.py
misc/acrn-config/scenario_config/pci_dev_c.py
misc/acrn-config/scenario_config/scenario_item.py

bdf 00:00.0 is reserved for pci host bridge. Reserve the this bdf
of pre-launced vm even there is neither passtrhough pci devices nor
emulated pci devices.
Refine the logic of get_pt_pci_num. It only counts the passthrough
devices, and does not pre-assume any vhostbridge device exists.
Refine logic of insert pci hostbridge device. Insert a hostbridge if
and only if there is either passthrough pci devices or ivshmem or
both of a pre-launched vm.
Tracked-On: #5609

acrn-config: reserve hostbirdge bdf of pre-launched vm

---

misc/config_tools/board_config/misc_cfg_h.py
misc/config_tools/data/tgl-rvp/tgl-rvp.xml
misc/config_tools/target/acpiparser/__init__.py
misc/config_tools/target/acpiparser/_utils.py
misc/config_tools/target/acpiparser/apic.py
misc/config_tools/target/acpiparser/asf.py
misc/config_tools/target/acpiparser/bitfields.py
misc/config_tools/target/acpiparser/cdata.py
misc/config_tools/target/acpiparser/dmar.py
misc/config_tools/target/acpiparser/facp.py
misc/config_tools/target/acpiparser/rtct.py
misc/config_tools/target/acpiparser/unpack.py
misc/config_tools/target/board_parser.py
misc/config_tools/target/rtct.py

This patch series introduces the ACPI table parsing library from BITS (BIOS Implementation Test Suite) to the config tools, adds the capability of parsing RTCT, and updates the generated configuration files which is a pre-requisite of #5658.

config_tools: parse RTCT and generate SW SRAM base for pre-launched RTVM

---

doc/tutorials/enable_s5.rst

Replace the original Clear Linux (`swupd`) command to add the GCC
compiler for Windows by the equivalent in Ubuntu (i.e. using Ubuntu
package manager 'apt')

doc: use 'apt' to install GCC for Windows

---

hypervisor/scripts/makefile/config.mk

This patch fixes the following issues that break the build system:
1. The tag of the root nodes of board/scenario XML files are still acrn-config,
not config_tools. This patch reverts the XPATH that refers to these nodes.
2. HV_PREDEFINED_BOARD_DIR now also relies on BOARD which may not be
available at the time the variable is defined. As both board and
scenario XML files are placed under the same directory, this patch
refines the path calculation logic to get rid of mixing variables of
the different flavors.
Tracked-On: #5644
Fixes: 97c9b2403036 ("acrn-config: Reorg config tool folder")

Makefile: fix build issues due to reorg of misc/

---

doc/Makefile

There is a comment in the doc/Makefile that is beinhg spit out
when calling 'make clean'. This is harmless but can be confusing
to users so let's make it silent.
Tracked-On: #5669

Makefile: make internal comment in doc Makefile silent

---

misc/config_tools/config_app/configs.py
misc/config_tools/config_app/static/main.js
misc/config_tools/config_app/templates/scenario.html

update config folders used in config app based on config tool folders
reorg; remove "Generate configuration files" button from config app
since the function is deprecated.
Tracked-On: #5644

acrn-config: update config folders used in config app

---

misc/config_tools/acpi_gen/asl_gen.py
misc/config_tools/data/ehl-crb-b/fusa_partition.xml

add fusa_partition scenario with 1 pre-launched Zephyr and 1 pre-launched
RTVM for ehl-crb-b board.
Tracked-On: #5665

acrn-config: add fusa_partition scenario on ehl-crb-b board

---

misc/config_tools/acpi_gen/asl_gen.py
misc/config_tools/acpi_gen/bin_gen.py

acrn-config: Rename acpi generated asl folder name from VMx to ACPI_VMx
Tracked-On: #5644

acrn-config: Rename acpi generated asl folder name from VMx to ACPI_VMx

---

hypervisor/arch/x86/guest/ve820.c
hypervisor/arch/x86/guest/vm.c
hypervisor/include/arch/x86/rtct.h

Currently, we hardcode the GPA base of Software SRAM
to an address that is derived from TGL platform,
as this GPA is identical with HPA for Pre-launch VM,
This hardcoded address may not work on other platforms
if the HPA bases of Software SRAM are different.
Now, Offline tool configures above GPA based on the
detection of Software SRAM on specific platform.
This patch removes the hardcoding GPA of Software SRAM,
and also renames MACRO 'SOFTWARE_SRAM_BASE_GPA' to
'PRE_RTVM_SW_SRAM_BASE_GPA' to avoid confusing, as it
is for Prelaunch VM only.

hv: remove the hardcoding of Software SRAM GPA base

---

doc/developer-guides/hld/hv-dev-passthrough.rst

doc: fix misspelling in hv-dev-passthrough

---

devicemodel/include/acpi.h

Fix compilation issue when using gcc 10.x due to the "__packed"
attribute in acpi.h. Explicitly changing that to __attribute__((packed))
fixes the compilation error.
Tracked-On: #5671

dm: fix compilation issue with gcc10

---

CODEOWNERS

Replace Deb (deb-intel) with Ben (fitchbe)for technical writer/reviewer

doc: update CODEOWNERS for tech docs

---

misc/config_tools/library/common.py
misc/config_tools/scenario_config/scenario_cfg_gen.py
misc/config_tools/schema/types.xsd

Try validate the scenario xml against schema if the config.xsd exsists.
Fix the regular expression pattern of IVSHMEM_REGION string validation.
Tracked-On: #5672

config-tools: validate the scenario against schema

---

hypervisor/arch/x86/guest/ept.c
hypervisor/arch/x86/rtcm.c
hypervisor/common/hypercall.c
hypervisor/include/arch/x86/guest/ept.h

Current implementation, SOS may allocate the memory region belonging to
hypervisor/pre-launched VM to a post-launched VM. Because it only verifies
the start address rather than the entire memory region.
This patch verifies the validity of the entire memory region before
allocating to a post-launched VM so that the specified memory can only
be allocated to a post-launched VM if the entire memory region is mapped
in SOS’s EPT.
Tracked-On: #5555
Reviewed-by: Yonghua Huang  <yonghua.huang@intel.com>

hv: hypercall: prevent sos can touch hv/pre-launched VM resource

---

hypervisor/arch/x86/configs/pci_dev.c
hypervisor/arch/x86/guest/vm.c
hypervisor/dm/vpci/vpci.c
hypervisor/dm/vpci/vsriov.c
hypervisor/hw/pci.c
hypervisor/include/hw/pci.h
misc/hv_prebuild/vm_cfg_checks.c

For pdev owned by HV, or passthrough to pre-launched VM. Deny access
their mmio/pio resource from SOS.

support deny access pdev resource from SOS

---

misc/config_tools/data/ehl-crb-b/hybrid_rt.xml
misc/config_tools/data/ehl-crb-b/industry.xml
misc/config_tools/data/tgl-rvp/industry.xml

add SW SRAM config for hybrid_rt and industry scenarios on tgl-rvp
and ehl-crb-b boards.

config_tools: addSW SRAM config

---

doc/reference/config-options.rst
doc/scripts/configdoc.xsl
doc/tutorials/enable_ivshmem.rst
misc/config_tools/schema/VMtypes.xsd
misc/config_tools/schema/config.xsd
misc/config_tools/schema/types.xsd

Start cleaning up formatting and content layout issues in the
xsd-derived configuration option documentation.  Includes adding
documentation for unnamed embedded simple types within an element (and
updates to the XSLT transformation to display these), cleanup of element
and type documentation, typos and description clarity.

doc: cleanup xsd-derived config doc text

---

devicemodel/core/vmmapi.c

resize vm_config buffer from 16KB to 32KB, as 16KB
is not enough on EHL platform, which will result in
crash when accessing this memory.

dm: resize the vm_config buffer in 'vm_get_config()'

---

devicemodel/hw/pci/xhci.c
devicemodel/hw/platform/usb_pmapper.c

The device descriptor describes general information about a device,
the bcdUSB field contains a BCD version number. The version 3.2 is
represented with value of 0x320H. Add the missed BCD version in the
bcdUSB case statement. And modify the return value of address device
command in case create device failed.
Tracked-On: #5712

DM: xHCI: Fix the USB3.2 device recognition problem.

---

devicemodel/core/vmmapi.c

resize vm_config buffer from 16KB to 32KB, as 16KB
is not enough on EHL platform, which will result in
crash when accessing this memory.

[ACRN-v2.4 branch]dm: resize the vm_config buffer in 'vm_get_config()'

---

misc/config_tools/library/board_cfg_lib.py

add check for is_tpm_passthru by tpm config from scenario
config.
Tracked-On: #5710

config_tools: is_tpm_passthru is checked by scenario config

---

doc/tutorials/running_deb_as_serv_vm.rst

Documentation mentions a specific Debian 10 ISO image version that no
longer exists.  Update to indiate we validated with debian_10.1.0 but
newer versions should also work.
Tracked-On: #5408

doc: update debian ISO image version number

---

doc/tutorials/docbuild.rst

Use title case for title and headings, make heading consistent using
command form

doc: update title and headings for doc build

---

devicemodel/hw/pci/core.c
hypervisor/dm/vpci/ivshmem.c

Ivshmem spec says that BAR0 size should be 256 bytes. Windows ivshmem driver will check BAR0 size, if it is not 256 windows will refuse to load the driver. These two patches fixed this issue with the following
changes:
- In hv the BAR0 size is changed to 256 according to ivshmem spec.
- In dm BAR base addr is aligned to 4K at least to satisfy EPT mapping.

Hv ivshmem barsize

---

hypervisor/boot/guest/vboot_info.c
hypervisor/common/vm_load.c
misc/config_tools/acpi_gen/asl_gen.py
misc/config_tools/data/ehl-crb-b/fusa_partition.xml
misc/config_tools/data/ehl-crb-b/hybrid.xml
misc/config_tools/data/ehl-crb-b/hybrid_rt.xml
misc/config_tools/data/ehl-crb-b/hybrid_rt_fusa.xml
misc/config_tools/data/ehl-crb-b/logical_partition.xml
misc/config_tools/data/ehl-crb-b/sdc.xml

config_tools: update zephyr entry point address on ehl-crb-b to work with zephyr 2.5
config_tools: update condition for bootargs error check only when kernel type is KERNEL_BZIMAGE.
HV: init VM bootargs only for LaaG
Currently the VM bootargs load address is hard-coded at 8KB right before
kernel load address, this should work for Linux kernel only since Linux
kernel is guaranteed to be loadered high than GPA 8K so its load address
would never be overflowed, other OS like Zephyr has no such assumption.
Tracked-on: #5689

update zephyr entry point address on ehl-crb-b

---

devicemodel/hw/pci/core.c
devicemodel/hw/platform/acpi/acpi_pm.c

Per ACPI 6.x chapter 6.1, "A device object must contain either an _HID object
or an _ADR object, but should not contain both."
Remove this object otherwise iasl would complain
"Warning  3073 -   Multiple types ^  (Device object requires either a _HID or _ADR, but not both)"
when launch post-launched VM in devicemodel.
Per ACPI 6.x chapter 19.6.109, the Processor Operator is deprecated.
Replace it with Device Operator, otherwise the iasl would complain
"Warning  3168 -             Legacy Processor() keyword detected. Use Device() keyword instead."
when launch post-launched VM in devicemodel.
Tracked-On: #5719

dm: iasl warning message fix

---

hypervisor/boot/guest/vboot_info.c
hypervisor/common/vm_load.c
misc/config_tools/acpi_gen/asl_gen.py
misc/config_tools/data/ehl-crb-b/fusa_partition.xml
misc/config_tools/data/ehl-crb-b/hybrid.xml
misc/config_tools/data/ehl-crb-b/hybrid_rt.xml
misc/config_tools/data/ehl-crb-b/hybrid_rt_fusa.xml
misc/config_tools/data/ehl-crb-b/logical_partition.xml
misc/config_tools/data/ehl-crb-b/sdc.xml

config_tools: update zephyr entry point address on ehl-crb-b to work with zephyr 2.5
config_tools: update condition for bootargs error check only when kernel type is KERNEL_BZIMAGE.
HV: init VM bootargs only for LaaG
Currently the VM bootargs load address is hard-coded at 8KB right before
kernel load address, this should work for Linux kernel only since Linux
kernel is guaranteed to be loadered high than GPA 8K so its load address
would never be overflowed, other OS like Zephyr has no such assumption.
Tracked-On: #5689

update entry point address for pre-launched zephyr on ehl-crb-b

---

misc/config_tools/config_app/controller.py
misc/config_tools/config_app/views.py
misc/config_tools/library/scenario_cfg_lib.py

app
change generic folder to generic_board folder in config app according
to the reorg data folders and update the method to save xmls.
Tracked-On: #5723

config_tools: change generic folder to generic_board folder in config

---

doc/release_notes/release_notes_0.7.rst
doc/release_notes/release_notes_0.8.rst
doc/release_notes/release_notes_1.0.rst
doc/release_notes/release_notes_1.1.rst
doc/release_notes/release_notes_1.2.rst

Horizontal lines were incorrectly removed during the processing for
using title case on all headings.  Put them back.

doc: fix layout of release notes after title case fix

---

doc/scripts/configdoc.xsl
misc/config_tools/schema/VMtypes.xsd
misc/config_tools/schema/config.xsd
misc/config_tools/schema/types.xsd

Some terms in the config option docs (e.g, Integer, Boolean) are being
flagged by one of our spell checking tools.  Let's make it happy.

doc: fix misspellings in config option doc

---

misc/config_tools/data/ehl-crb-b/fusa_partition.xml

update kern_mod to RT_bzImage in VM1, update memory size of
VM0 to avoid memory conflict.
Tracked-On: #5665

config_tools: fix VM boot issue for fusa_partition scenario

---

misc/config_tools/schema/types.xsd

Loosen the restriction of IVSHMEM_REGION of xsd validation. An ivshmem
region can be shared more than two vms.
Tracked-On: #5672

config-tools: ivshmem support to be shared by multiple vms

---

hypervisor/include/arch/x86/apicreg.h

Fixing an incorrect struct definition for ir_bits in ioapic_rte. Since bits after
the delivery status in the lower 32 bits are not touched by code,
this has never showed up as an issue. And the higher 32 bits in the RTE
are aligned by the compiler.
Tracked-On: #5773

hv: Fix incorrect struct definition for ir_bits

---

hypervisor/arch/x86/guest/vm.c
hypervisor/include/arch/x86/rtct.h
misc/config_tools/board_config/misc_cfg_h.py

1st patch to refine config tool to update some MACROs for PreRTVM software SRAM settings.
2cnd patch to un-map sw sram region that assigned to preRTVM from EPT of Service VM.

Unmap Software SRAM region of PreRTVM from Service VM

---

devicemodel/hw/pci/core.c
devicemodel/hw/platform/acpi/acpi_pm.c

Per ACPI 6.x chapter 6.1, "A device object must contain either an _HID object
or an _ADR object, but should not contain both."
Remove this object otherwise iasl would complain
"Warning  3073 -   Multiple types ^  (Device object requires either a _HID or _ADR, but not both)"
when launch post-launched VM in devicemodel.
Per ACPI 6.x chapter 19.6.109, the Processor Operator is deprecated.
Replace it with Device Operator, otherwise the iasl would complain
"Warning  3168 - Legacy Processor() keyword detected. Use Device() keyword instead."
when launch post-launched VM in devicemodel.
Tracked-On: #5719

[release 2.4]dm: iasl warning fix

---

misc/config_tools/data/apl-mrb/hybrid.xml
misc/config_tools/data/apl-mrb/industry.xml
misc/config_tools/data/apl-mrb/sdc.xml
misc/config_tools/data/apl-up2/hybrid.xml
misc/config_tools/data/apl-up2/industry.xml
misc/config_tools/data/apl-up2/sdc.xml

Remove obsolete kernel (i915) parameters from the Apollo Lake (APL)
board configurations.
Tracked-On: #5236

acrn-config: remove obsolete kernel parameters from APL configurations

---

misc/config_tools/schema/config.xsd

RDT_ENABLED and PSRAM_ENABLED should not by y simultaneously.

config_tools: add sanity check for PSRAM and RDT

---

misc/config_tools/data/ehl-crb-b/industry_launch_1uos_hardrt.xml
misc/config_tools/data/ehl-crb-b/industry_launch_2uos.xml
misc/config_tools/data/ehl-crb-b/industry_launch_6uos.xml
misc/config_tools/data/ehl-crb-b/sdc_launch_1uos_laag.xml
misc/config_tools/data/generic_board/industry_launch_2uos.xml
misc/config_tools/data/nuc6cayh/industry_launch_1uos_hardrt.xml
misc/config_tools/data/nuc6cayh/industry_launch_2uos.xml
misc/config_tools/data/nuc6cayh/industry_launch_6uos.xml
misc/config_tools/data/nuc6cayh/sdc_launch_1uos_laag.xml
misc/config_tools/data/nuc7i7dnb/industry_launch_1uos_hardrt.xml
misc/config_tools/data/nuc7i7dnb/industry_launch_2uos.xml
misc/config_tools/data/nuc7i7dnb/industry_launch_6uos.xml
misc/config_tools/data/nuc7i7dnb/sdc_launch_1uos_laag.xml
misc/config_tools/data/tgl-rvp/industry_launch_2uos.xml
misc/config_tools/data/tgl-rvp/sdc_launch_1uos_laag.xml
misc/config_tools/data/whl-ipc-i5/industry_launch_1uos_hardrt.xml
misc/config_tools/data/whl-ipc-i5/industry_launch_2uos.xml
misc/config_tools/data/whl-ipc-i5/industry_launch_6uos.xml
misc/config_tools/data/whl-ipc-i5/sdc_launch_1uos_laag.xml
misc/config_tools/data/whl-ipc-i7/industry_launch_1uos_hardrt.xml
misc/config_tools/data/whl-ipc-i7/industry_launch_2uos.xml
misc/config_tools/data/whl-ipc-i7/industry_launch_6uos.xml
misc/config_tools/data/whl-ipc-i7/sdc_launch_1uos_laag.xml

Remove the the vuart1(tty) and vuart1(pty) poweroff channel from default
non-windows uos launch script xmls.
Tracked-On: #5736

config-tools: remove "vuart" poweroff channel from default xml

---

hypervisor/Makefile
hypervisor/arch/x86/Kconfig
hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/cpu_caps.c
hypervisor/arch/x86/guest/ept.c
hypervisor/arch/x86/guest/trusty.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/mmu.c
hypervisor/arch/x86/page.c
hypervisor/arch/x86/pagetable.c
hypervisor/common/hypercall.c
hypervisor/dm/vpci/vdev.c
hypervisor/include/arch/x86/guest/ept.h
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/arch/x86/page.h

For FuSa's case, we remove all dynamic memory allocation use in ACRN HV. Instead,
we use static memory allocation or embedded data structure. For pagetable page,
we prefer to use an index (hva for MMU, gpa for EPT) to get a page from a special
page pool. The special page pool should be big enougn for each possible index.
This is not a big problem when we don't support 64 bits MMIO. Without 64 bits MMIO
support, we could control the index not larger than DRAM_SIZE + 4G.
However, if ACRN plan to support 64 bits MMIO in SOS, we could not use the static
memory alocation any more. This is because there's a very huge hole between the
top DRAM address and the bottom 64 bits MMIO address. We could not reserve such
many pages for pagetable mapping as the CPU physical address bits may very large. …

hv: use dynamic page allocation for pagetable mapping

---

devicemodel/core/main.c
devicemodel/core/pm_vuart.c
devicemodel/include/pm_vuart.h
misc/services/life_mngr/life_mngr.c

At most one VM is allowed to use "--pm_notify_channel uart" at a time, since only one socket connection to SOS life_mngr is allowed.
Monitor the listening socket in SOS life_mngr and close any additional connections after a socket connection is established. Identify a closed socket connection to SOS life_mngr as a failure in dm and fail gracefully.
Tracked-On: #5736

Allow only one active SOS life_mngr socket

---

Makefile
devicemodel/Makefile
hypervisor/scripts/makefile/config.mk
misc/Makefile
misc/debug_tools/acrn_crashlog/Makefile
misc/services/acrn_manager/Makefile

Motivated by the review of #5753, the issue #5772 and some offline-reported bugs, this patch series tries aligning the functionality and terminology used in top-level Makefile and component-wise ones. The major changes are as follows.
- Use `y` and `n` as the preferred values of `RELEASE`. The old values `0` and `1` can still be used for backward compatibility. (fixes #5772)
- Allow the top-level Makefile to recognize the `BOARD` and `SCENARIO` settings of a build directory. This allows commands like below to work.
- The top-level Makefile can now invoke the hypervisor configuration-related targets as `hvshowconfig`, `hvdiffconfig` and `hvapplydiffconfig`. The `hv` prefix is added to highlight that they only apply to hypervisor configurations, not configurations to every component.
- …

Expose hypervisor configuration targets to top-level Makefile and fix bugs in diffconfig

---

hypervisor/arch/x86/guest/vmx_io.c
hypervisor/arch/x86/page.c
hypervisor/arch/x86/pagetable.c
hypervisor/include/arch/x86/page.h

v3:
abandon "2. only recover execution right when EPT violation for PSCMCE" in v1
v2:
refine the comments
v1:
1. only treak execution right for large pages
2. only recover execution right when EPT violation for PSCMCE
3. RTVM: build 4KB page mapping in EPT for code pages, use large page mapping for data pages
Tracked-On: #5788

hv: two minor refine for PSCMCE

---

hypervisor/common/hypercall.c

This hypercall handler may result in hypervisor
crash when an invalid 'gpa' is set, e.g. set its
top reserved bits.
This patch adds one more sanity check on input
'gpa' address from service VM to avoid potential
hypervisor crash.
Trackec-On: #5802

[release_v2.4] hv: fix potential crash in write_protect_page()

---

Makefile
devicemodel/Makefile
hypervisor/scripts/makefile/config.mk
misc/Makefile
misc/debug_tools/acrn_crashlog/Makefile
misc/services/acrn_manager/Makefile

This PR applies the same patches in #5791 to the release_2.4 branch. The original descriptions are as follows.
Motivated by the review of #5753, the issue #5772 and some offline-reported bugs, this patch series tries aligning the functionality and terminology used in top-level Makefile and component-wise ones. The major changes are as follows.
- Use `y` and `n` as the preferred values of `RELEASE`. The old values `0` and `1` can still be used for backward compatibility. (fixes #5772)
- Allow the top-level Makefile to recognize the `BOARD` and `SCENARIO` settings of a build directory. This allows commands like below to work.
- The top-level Makefile can now invoke the hypervisor configuration-related targets as `hvshowconfig`, `hvdiffconfig` and `hvapplydiffconfig`. The `hv` prefix is …

[release_v2.4] Expose hypervisor configuration targets to top-level Makefile and fix bugs in diffconfig

---

misc/config_tools/launch_config/com.py

add "--psram" in acrn dm arguments in launch scripts
when PSRAM_ENABLED=y and the VM is post-launched RTVM.

config_tools: add psram config in launch config

---

hypervisor/arch/x86/cpu.c

Before the ACRN HV entered the S3, we would call cache_flush_invalidate_all to
flush all the caches into memory and invalidate the caches on each logical cpu
before we halt the cpu.
This was not a problem before we support pSRAM. Once pSRAM binary code has been
executed on the logical cpu, we could not flush the pSRAM cache into memory then.
Otherwise, the pSRAM cache can't been locked.
This patch removes cache_flush_invalidate_all in cpu_dead since we would not
support to put the ACRN HV into S3. Once we want to support put the ACRN HV into
S3, we would try other ways to flush the data caches in this cpu into memory and
valid whether that way is practical or not.
Tracked-On: #5806

[release_2.4] hv: cpu: remove cache_flush_invalidate_all in cpu_dead

---

devicemodel/hw/pci/xhci.c
devicemodel/hw/platform/usb_pmapper.c

From the Figure 11-10. Downstream Facing Hub Port State Machine the
device connect status should be disabled and the PLS should be polling
for USB2.0, when the device be connected, then the xHCD send the port
reset, for acrn we use libusb_reset_device to emulate the bus reset
action.
Tracked-On: #5795

DM: xHCI: Implement the USB PLS Machine flow spec.

---

doc/user-guides/hv-parameters.rst

Add the 'mmio@' parameter to the document describing all the possible
values for 'uart='. This is the command-line argument passed to the
hypervisor in order to overwrite and/or set the serial port.
Tracked-On: #5820

doc: add missing 'mmio@' description to hypervisor parameters

---

doc/reference/hardware.rst

Fix incorrect information about the presence (or not) of a serial
port on Kaby Lake NUC platforms.
Tracked-On: #5812

doc: fix incorrect info about serial port availability

---

hypervisor/arch/x86/guest/ept.c
hypervisor/arch/x86/guest/trusty.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/mmu.c
hypervisor/arch/x86/page.c
hypervisor/arch/x86/pagetable.c
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/arch/x86/mmu.h
hypervisor/include/arch/x86/page.h
hypervisor/include/arch/x86/pgtable.h

The fields and APIs in old 'struct memory_ops' are used to add/modify/delete
page table (page or entry). So rename 'struct memory_ops' to 'struct pgtable'.
Tracked-On: #5830

hv: pgtable: rename 'struct memory_ops' to 'struct

---

devicemodel/hw/pci/core.c
hypervisor/dm/vpci/ivshmem.c

backport these 2 patches from master to v2.4
----------------------------------------------------------------------------------
Fix the issue that ivshmem windows driver cannot work
Ivshmem spec says that BAR0 size should be 256 bytes. Windows ivshmem driver will check BAR0 size, if it is not 256 windows will refuse to load the driver. These two patches fixed this issue with the following
changes:
- In hv the BAR0 size is changed to 256 according to ivshmem spec.
- In dm BAR base addr is aligned to 4K at least to satisfy EPT mapping.

Release 2.4 ivshmem

---

misc/config_tools/library/board_cfg_lib.py

"is_tpm_passthru" would always return "False" with the existing logic.
1. Replace "get_leaf_tag_map_bool" with "get_leaf_tag_map". Instead returning a dictrionary with boolean diction values, just get the string value.
2. Return "True" if any vm has enabled the passtrhough tpm with option "y".
Tracked-On: #5710

config-tools: fix "is_tpm_passthru" always return "False"

---

misc/config_tools/board_config/vbar_base_h.py
misc/config_tools/data/generic_board/generic_code/hybrid/vbar_base.h
misc/config_tools/data/generic_board/generic_code/hybrid_rt/vbar_base.h
misc/config_tools/data/generic_board/generic_code/industry/vbar_base.h
misc/config_tools/data/generic_board/generic_code/logical_partition/vbar_base.h

"PTDEV_HI_MMIO_START" is removed by the commit
8d9f12f3b737394fbad6247d57155b0455429d15.
Replace "PTDEV_HI_MMIO_START" with "HI_MMIO_START".
Tracked-On: #5693

config-tools: replace "PTDEV_HI_MMIO_START" with "HI_MMIO_START"

---

hypervisor/arch/x86/boot/cpu_primary.S
hypervisor/arch/x86/configs/vacpi.c
hypervisor/arch/x86/guest/vm.c
hypervisor/boot/acpi_base.c
hypervisor/boot/include/acpi.h
hypervisor/boot/include/multiboot.h
hypervisor/boot/include/multiboot_std.h
hypervisor/boot/multiboot/multiboot.c
hypervisor/boot/multiboot/multiboot2.c
hypervisor/boot/multiboot/multiboot_priv.h
hypervisor/common/vm_load.c
hypervisor/include/arch/x86/zeropage.h
hypervisor/include/dm/vacpi.h
hypervisor/include/lib/efi.h

This reverts commit ce9d5e87791cfd135de8cd997274e2e03c75f5a1.
Before readiness of better solution to fix SOS VM e820 and efi memmap mismatch
issue, revert this patch.
Tracked-On: #5626

HV: Revert "HV: remove efi support for SOS"

---

misc/config_tools/data/ehl-crb-b/logical_partition.xml

add passthru devices for logical partition scenario on ehl.
Tracked-On: #5665

config_tools: add passthru devices for logical partition scenario on ehl

---

doc/getting-started/building-from-source.rst
doc/getting-started/roscube/roscube-gsg.rst
doc/getting-started/rt_industry_ubuntu.rst

The ACRN buid system uses 'xmllint' which is provided by the 'libxml2-utils'
package on Ubuntu. This patch adds it to the list of build and development
packages to be installed on the build system to succesfully build ACRN.
Tracked-On: #5861

doc: add 'libxml2-utils' to the list of build dependencies

---

doc/user-guides/hv-parameters.rst
hypervisor/debug/dbg_cmd.c

The 'uart=' parameter for the hypervisor takes multiple forms. One
is to specify the BDF (Bus, Device, Function) value of the serial
port PCI device. The description in the documentation used the
previous format (e.g. '0:18.1') but a 16-bit WORD in HEX needs
to be passed nowadays. E.g.: '0:18.1' is specified by 'uart=0xc1'
Tracked-On: #5820

doc: update BDF information for 'uart=' hypervisor parameter

---

misc/config_tools/schema/types.xsd

A scenario can enable multiple IVSHMEM_REGIONs, loosen the restriction to extend multiple regions support.
Tracked-On: #5863

config-tools: loosen IVSHMEM_REGION restriction in schema

---

hypervisor/dm/vpci/vmsi.c

In VT-d scenario, if MSI interrupt has been enabled,
vCPU writes the content in MSI registers,
and all bits of the content are read-only.
In this case, hypervisor code will call
enable_disable_msi(vdev, false), which will disable MSI.
And there's no chance to call remap_vmsi.
This is wrong behavior, which will result in the disable of MSI.
Tracked-On: #5847
Reviewed-by: Li Fei1 <fei1.li@intel.com>
Signed-off-by: liujunming <junming.liu@intel.com>

hv: vpci: fix msi enable issue under some cases

---

devicemodel/hw/pci/core.c
hypervisor/dm/vpci/ivshmem.c

backport to release 2.3
------------------------------------------------
Ivshmem spec says that BAR0 size should be 256 bytes. Windows ivshmem driver will check BAR0 size, if it is not 256 windows will refuse to load the driver. These two patches fixed this issue with the following
changes:
- In hv the BAR0 size is changed to 256 according to ivshmem spec.
- In dm BAR base addr is aligned to 4K at least to satisfy EPT mapping.

Release 2.3 ivshmem bar

---

misc/services/acrn_manager/acrnctl.c

The creation of the acrn_manager ('acrnctl') configuration folder
is currently done when adding a new VM to the system. This leads to
an error (non-fatal) thrown on the terminal is calling, say 'list'
first without having added a VM yet. This patch moves the creation
of such folder as part of main() thereby ensuring it is created as
soon as the program starts.
Tracked-On: #4898

acrn_manager: create acrnctl configuration folder when starting

---

Makefile

The 'iasl' binary (from the acpica) package can be installed in
different locations depending on the distribution. By default,
we look for it under '/usr/sbin/'. But it is also often found
under '/usr/bin'. This can be overwritten by setting the ASL_COMPILER
flag when compiling ACRN.
This patch goes one step further and automatically determine where
'iasl' is on the development system if the ASL_COMPILER variable
has not been set already.
Tracked-On: #5854

Makefile: automatically determine the location of 'iasl'

---

Makefile

Add the 'hvdefconfig' as a pre-requisite before building the hypervisor.
This solves the problem when using multiple parallel threads (i.e.
"make -j2").
Tracked-On: #5874

Makefile: add pre-requisite before building the hypervisor

---

hypervisor/arch/x86/guest/ept.c
hypervisor/arch/x86/guest/trusty.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/mmu.c
hypervisor/arch/x86/pagetable.c
hypervisor/include/arch/x86/guest/ept.h
hypervisor/include/arch/x86/mmu.h
hypervisor/include/arch/x86/pgtable.h

This patch series reshuffle pagetable module. The goal is to provides the
stable interfaces and data structure for this module. For PageTable, we should
provide interfaces to add/modify/del Page Table Mapping; we also need to provide
interfaces to create the root page table entry and to lookup a page table entry.
The page table date structure:
struct pgtable {
uint64_t flags;
uint64_t default_access_right;
struct page_pool *pool;
bool (*large_page_support)(enum _page_table_level level, uint64_t prot);
uint64_t (*pgentry_present)(uint64_t pte);
void (*tweak_exe_right)(uint64_t *entry);
void (*recover_exe_right)(uint64_t *entry);
};
The page table external interfaces:
----------
| paging |
----------
|
| pgtable_create_root
| pgtable_create_trusty_root
| pgtable_add_map …

Paging/Memory Modularization, Part 1 - PageTable

---

Makefile
misc/Makefile

The Yocto folks are disabling the building of `life_mngr` on the basis it is a component to be run in the User VM. That makes sense to me, if true. Based on that, I have made some modifications to our Makefile to **not** build `life_mngr` by default anymore. I also created a target in the top-level Makefile so it can easily be built on demand from there.
This is sent as a draft PR for now, it should really be sent as a PR after #5810 has been merged... but please take a look at it already today. ;-)

Enhance life mngr makefile

---

hypervisor/Makefile

This patch adds the following dependencies among recipes:
- Building of any C file depends on $(HV_CONFIG_TIMESTAMP) which indicates
the presence of generated configuration files.
- Source files listed in $(VM_CFG_C_SRCS), which are the generated
configuration files, depends on $(HV_CONFIG_TIMESTAMP)
With the dependencies above, the build system can now safely be executed in
parallel, e.g. `make -j4`.
Tracked-On: #5874

Makefile: add missing dependencies for parallel execution of make

---

doc/release_notes/release_notes_2.4.rst
doc/tutorials/acrn_configuration_tool.rst

This patch adds a summary of the significant changes to ACRN configuration and build in v2.4 and gives some instructions on how to upgrade from a previous release.

doc: add summary of config changes and upgrading guides

---

doc/getting-started/building-from-source.rst
doc/getting-started/roscube/roscube-gsg.rst
doc/getting-started/rt_industry_ubuntu.rst

Update the ACPI Component Architecture package (acpica-unix) to
the latest version available as of today: 20210105
Tracked-On: #5553

doc: update acpica-unix version to latest (20210105)

---

misc/config_tools/data/sample_launch_scripts/nuc/launch_hard_rt_vm.sh
misc/config_tools/data/sample_launch_scripts/nuc/launch_uos.sh

Remove the Power Management ('pm') parameters from the sample launch scripts,
and update the comments, At most one VM is allowed to use "--pm_notify_channel uart"
at a time, since only one socket connection to SOS life_mngr is allowed.
Remove it by default and allow user to add on demand
Tracked-On: #5736
Signed-off-by: li shuang <shuangx.li@intel.com>

config-tools: modify sample launch scripts

---

doc/getting-started/roscube/roscube-gsg.rst
doc/release_notes/release_notes_2.4.rst
doc/static/acrn-custom.css

Update draft release notes with more information about documentation.
Remove code-block extra indenting.
Add label to roscube gsg so we can link to it (in the releaes notes).
Fix style for :option: references to make them look more links links.

doc: update v2.4 release notes

---

hypervisor/arch/x86/guest/vcpu.c
hypervisor/include/arch/x86/cpu.h

Both Windows guest and Linux guest use the MSR MSR_IA32_CSTAR, while
Linux uses it rarely. Now vcpu context switch doesn't save/restore it.
Windows detects the change of the MSR and rises a exception.
Do the save/resotre MSR_IA32_CSTAR during context switch.
Tracked-On: #5899

hv: Save/restore MSR_IA32_CSTAR during context switch

---

devicemodel/core/sw_load_common.c
devicemodel/hw/pci/passthrough.c
devicemodel/hw/platform/acpi/acpi.c
devicemodel/hw/platform/acpi/rtct.c
devicemodel/include/pci_core.h
devicemodel/include/pcireg.h
devicemodel/include/sw_load.h

Windows graphic driver obtains DSM address from in-BAR mmio register
which has passthroughed. Not like the other platforms obtained from
pci configure space register which has virtualized. GPU GuC must use
WOPCM in DSM, besides, Windows OS wants to manage DSM also. These two
reason force acrn has to keep identical mapping to avoid trap mmio
BAR to do the emulation.
Tracked-On: #5880
Signed-off-by: Peng Sun <peng.p.sun@intel.com>

DM: gvt: Identical mapping for GPU DSM refine to support EHL/TGL

---

hypervisor/arch/x86/guest/vmsr.c

For platform with HLAT (Hypervisor-managed Linear Address Translation)
capability, the hypervisor shall hide this feature to its guest.
This patch adds MSR_IA32_VMX_PROCBASED_CTLS3 MSR to unsupported MSR
list.
The presence of this MSR is determined by 1-setting of bit 49 of MSR
MSR_IA32_VMX_PROCBASED_CTLS. which is already in unsupported MSR list.
Related documentations:
[1] Intel Architecture Instruction Set Extensions, version Feb 16, 2021,
Ch 6.12
[2] Intel KeyLocker Specification, Sept 2020, Ch 7.2
Tracked-On: #5895 

hv: Hide HLAT to guest

---

doc/tutorials/docbuild.rst

We've validated doc build tool versions, so let's make sure those are
the versions the instructions say to install.  The version of doxygen
you get when you use ``sudo apt install doxygen`` may get a newer
version that may still work so let's tell them that.
Also, we no longer use kconfig files in the document build process, so
remove mentioning that in the build documentation.

doc: update doc build instructions

---

misc/config_tools/data/ehl-crb-b/hybrid_rt_launch_1uos_waag.xml
misc/config_tools/data/ehl-crb-b/industry_launch_1uos_waag.xml
misc/config_tools/data/ehl-crb-b/industry_launch_2uos.xml
misc/config_tools/data/ehl-crb-b/industry_launch_6uos.xml

There is no audio device in the default ehl-crb-b.xml, so remove
passthru audio devices from launch xmls on ehl-crb-b.
Tracked-On: #5925

config_tools: remove audio passthru in launch xmls on ehl-crb-b

---

misc/config_tools/config_app/views.py
misc/config_tools/data/tgl-rvp/industry.xml
misc/config_tools/data/tgl-rvp/industry_launch_6uos.xml

fail to create kata vm type in industry scenario due to
the default vm id value is 1. Meanwhile set the max user
vm to 7 in tgl-rvp industry xml.
Tracked-On: #5932

config-tools: change default industry kata vm id to 7

---

hypervisor/arch/x86/guest/vcpuid.c
hypervisor/arch/x86/trampoline.c

v2:
1. hide new cpuid 0x1f
v1:
1. Use MFENCE to enforce fast string operations was done
2.  Hide CPUID.1b and Use CPUID.0b to emulate CPUID.1f
Tracked-On: #5929

hv: fix some minor bug 

---

hypervisor/arch/x86/e820.c
hypervisor/arch/x86/guest/ve820.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/mmu.c
hypervisor/include/arch/x86/e820.h
hypervisor/include/arch/x86/mmu.h
hypervisor/include/arch/x86/pgtable.h

v2:
1. define a new MACRO PAGE_ATTR_USER
2. use same API to do SOS memory EPT mapping
v1:
For e820 module, we could only provide three APIs:
init_e820 - to initial the e820 table for ACRN hypervisor;
get_e820_entries_count - to get the total number of the e820 entries
get_e820_entry - to get the e802 entiries
to get/set the e820 tables.
However, ACRN doesn't have memory management. There're some usages for
memory allocation. So we add an API e820_alloc_memory to allocate a memory
from e820 table.
Tracked-On: #5830
Acked-by: eddie Dong <eddie.dong@intel.com>

Paging/Memory Modularization - e820 Part

---

doc/conf.py

This patch tweaks the settings in doc/conf.py to allow formatting the
documentation to a PDF file by Sphinx. The changes include:
- Use `xelatex` rather than the default `pdflatex` as the LaTeX engine, as
`pdflatex` is not that good at formatting non-ascii characters out of
the box.
- Use DejaVu fonts (which are available in common Linux distributions) in
the generated PDF.
- Restrict the depths of the table of contents to 3.

doc/conf.py: enable formatting docs in a PDF file

---

hypervisor/arch/x86/cpu_caps.c
hypervisor/arch/x86/guest/ept.c
hypervisor/arch/x86/mmu.c
hypervisor/include/arch/x86/page.h

1. add assumption "platform which PAW over 39 bits must support 1GB large page"
2. use new algo to calculate PPT/EPT_PD_PAGE_NUM
Tracked-On: #5929

hv: pgtable: use new algo to calculate PPT/EPT_PD_PAGE_NUM for platform which PAW over 39 bits

---

doc/Makefile
doc/developer-guides/hld/hv-partitionmode.rst
doc/developer-guides/hld/virtio-blk.rst
doc/tutorials/trustyACRN.rst

Update missing captions on figures to remove remaining broken references
during latexpdf building.  Also, require doing a "make html" before
doing a "make latexpdf" to build all the artifacts needed for running
the latexpdf build.  (We might change that later if needed.)

doc: tweaks for latexpdf build

---

hypervisor/include/lib/util.h

These two MACROs shall be wrapped as a single
value respectively, hence brackets should be used.
Tracked-On: #5951

hv: bugfix in min() and max() MACROs

---

misc/config_tools/hv_config/board_defconfig.py
misc/config_tools/static_allocators/hv_ram.py

add 2 * max (IVSHMEM_SHM_SIZE, 2M) in HV_RAM_SIZE calculation to
avoid ram overflow caused by additional memory usage for shared
memory alignment.
Tracked-On: #5955

config_tools: update IVSHMEM_SHM_SIZE part for HV_RAM_SIZE calculation

---

doc/.known-issues/doc/pdf.conf
doc/Makefile
doc/conf.py
doc/scripts/pullsource.sh
doc/scripts/show-versions.py
doc/tutorials/docbuild.rst

PRs #5945 and #5949 introduced fixes to the doc building process to
support PDF generation of the documentation set.  This PR refines the
doc build process, cleaning up the Makefile, adding display of tool
version information, and updates the doc building documentation to
include additional dependencies needed for building the PDF and
instructions for how to build the PDF.  The latexpdf make target is
provided to just run the latex and PDF producing process that depends on
the HTML artifacts from a make html run.  A new make pdf target is
provided that combines the two steps into one.
A new know-issues pattern file is added that verifies the expected
output from the latexpdf process is returned, as it can't be completely
eliminated without losing potential error messages that need to be …

doc: clean up PDF generation for ACRN docs

---

devicemodel/hw/platform/acpi/acpi.c
devicemodel/hw/platform/acpi/rtct.c

GPA of software SRAM is available only after
build_vrtct() function is called and the return
value of it is valid(Not NULL).
This patch fix bug in create_and_inject_vrtct()
function which violate above pre-condition when
calling get_software_sram_base_gpa().
Tracked-On: #5973

dm: bugfix in create_and_inject_vrtct

---

hypervisor/arch/x86/mmu.c

We should only map [low32_max_ram, 4G) MMIO region as UC attribute,
not map [low32_max_ram, low32_max_ram + 4G) region as UC attribute.
Otherwise, the HV will complain [4G, low32_max_ram + 4G) region has
already mapped.
Tracked-On: #5830

hv: mmu: fix a minor bug

---

devicemodel/hw/platform/acpi/acpi.c
devicemodel/hw/platform/acpi/rtct.c

GPA of software SRAM is available only after
build_vrtct() function is called and the return
value of it is valid(Not NULL).
This patch fix bug in create_and_inject_vrtct()
function which violates above pre-condition when
calling get_software_sram_base_gpa().
Tracked-On: #5973

[release_2.4 hotfix] dm: bugfix in create_and_inject_vrtct

---

doc/user-guides/acrn-dm-parameters.rst

Add a note to the "Device Model Parameters" document to emphasize
the need to use the '--windows' parameter to use Windows-as-a-Guest
(WaaG), else Windows will not recognize the virtual disk it has
been assigned.
Tracked-On: #5962

doc: add note to emphasize the need to use --windows for WaaG

---

doc/getting-started/building-from-source.rst

clang-format is now used as part of the config tools creating c files
based on the XML configuration

doc: add clang-format to setup package list

---

hypervisor/scripts/genconf.sh

Fix a couple of typos in text displayed by a helper script
used when building ACRN. No functional change made to the
script itself.

config-tools: fix a couple of typos in helper script

---

doc/developer-guides/hld/hld-security.rst
doc/developer-guides/hld/hv-hypercall.rst
hypervisor/arch/x86/guest/vmcall.c
hypervisor/common/hypercall.c
hypervisor/common/trusty_hypercall.c
hypervisor/debug/hypercall.c
hypervisor/include/common/hypercall.h
hypervisor/release/hypercall.c

The current permission-checking and dispatching mechanism of hypercalls is
not unified because:
1. Some hypercalls require the exact vCPU initiating the call, while the
others only need to know the VM.
2. Different hypercalls have different permission requirements: the
trusty-related ones are enabled by a guest flag, while the others
require the initiating VM to be the Service OS.
Without a unified logic it could be hard to scale when more kinds of
hypercalls are added later.
The objectives of this patch are as follows.
1. All hypercalls have the same prototype and are dispatched by a unified
logic.
2. Permissions are checked by a unified logic without consulting the
hypercall ID.
To achieve the first objective, this patch modifies the type of the first
parameter of hcall_* functions …

hv: hypercalls: refactor permission-checking and dispatching logic

---

misc/config_tools/data/generic_board/generic_code/hybrid/misc_cfg.h
misc/config_tools/data/generic_board/generic_code/hybrid_rt/misc_cfg.h
misc/config_tools/data/generic_board/generic_code/industry/misc_cfg.h
misc/config_tools/data/generic_board/generic_code/logical_partition/misc_cfg.h
misc/config_tools/xforms/misc_cfg.h.xsl

The macro definition SOS_VM_BOOTARGS in vm_configurations.h calls
macros SOS_ROOTFS, SOS_CONSOLE and SOS_BOOTARGS_DIFF which is defined in
misc_cfg.h and parsed from scenario.xmls.
Add a whitespace in the end of the argument macros to prevent arguments
are concatenated in a single line.
Tracked-On: #5998

config-tools: add white space between arguments

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/guest/ept.c
hypervisor/arch/x86/guest/vmexit.c
hypervisor/arch/x86/ioapic.c
hypervisor/arch/x86/mmu.c
hypervisor/arch/x86/rtcm.c
hypervisor/arch/x86/trampoline.c
hypervisor/arch/x86/vtd.c
hypervisor/debug/dump.c
hypervisor/debug/npk_log.c
hypervisor/debug/uart16550.c
hypervisor/dm/vgpio.c
hypervisor/hw/pci.c
hypervisor/include/arch/x86/asm/cpu.h
hypervisor/include/arch/x86/asm/mmu.h

Wrap common APIs for Cache/TLB Part
For Cache, ACRN provides three APIs:
- flush_invalidate_all_cache
- flush_cacheline
- flush_cache_range
For TLB, ACRN provides two APIs:
- flush_tlb
- flush_tlb_range
This patch also remove ppt_set/clear_(attribute) to set_paging_(attribute)
Tracked-On: #5830

Paging/Memory Modularization - Cache/TLB Part

---

misc/config_tools/schema/types.xsd

The ivshmem region name format is not ristricted to start with "hv".
Loosen the schema validation so that the region name can start with "hv" or "dm".
Tracked-On: #6009

config-tools: fix the regular expression of ivshmem region name

---

hypervisor/arch/x86/rtcm.c
hypervisor/include/arch/x86/asm/rtct.h

For simplification purpose, use 'ssram' instead of
'software sram' for local names inside rtcm module.
Tracked-On: #6015

hv: rename some software SRAM local names

---

devicemodel/core/main.c
devicemodel/hw/platform/acpi/acpi.c
devicemodel/hw/platform/acpi/rtct.c
devicemodel/include/dm.h
devicemodel/include/rtct.h

Remove below legacy SSRAM names:
psram -> ssram
ptct -> rtct
Tracked-On: #6015

dm: clean legacy software SRAM names

---

hypervisor/arch/x86/Kconfig
misc/config_tools/acpi_gen/asl_gen.py
misc/config_tools/board_config/misc_cfg_h.py
misc/config_tools/board_inspector/legacy/rtct.py
misc/config_tools/config_app/templates/scenario.html
misc/config_tools/data/adl-rvp/industry.xml
misc/config_tools/data/ehl-crb-b/hybrid_rt.xml
misc/config_tools/data/ehl-crb-b/industry.xml
misc/config_tools/data/tgl-rvp/hybrid_rt.xml
misc/config_tools/data/tgl-rvp/industry.xml
misc/config_tools/hv_config/board_defconfig.py
misc/config_tools/hv_config/hv_item.py
misc/config_tools/launch_config/com.py
misc/config_tools/library/hv_cfg_lib.py
misc/config_tools/scenario_config/scenario_cfg_gen.py
misc/config_tools/schema/config.xsd
misc/config_tools/schema/types.xsd
misc/config_tools/xforms/config_common.xsl

'psram' and 'PSARM' are legacy names and replaced
with 'ssram' and 'SSRAM' respectively.
Tracked-On: #6012

config-tool: rename PSRARM to SSRAM

---

devicemodel/core/sw_load_common.c
doc/developer-guides/hld/hld-devicemodel.rst
doc/user-guides/acrn-dm-parameters.rst

psram is legacy name of SSRAM, rename it to ssam

doc: clean legacy software SRAM names

---

hypervisor/arch/x86/rtcm.c
hypervisor/include/arch/x86/asm/rtct.h

RTCT has been updated to version 2,
this patch update hypervisor RTCT parseer to support
both version 1 and version 2 of RTCT.
Reviewed-by: Jason CJ Chen <jason.cj.chen@intel.com>

hv: update RTCT parser to support RTCT version 2

---

misc/config_tools/data/apl-mrb/logical_partition.xml
misc/config_tools/data/apl-up2-n3350/logical_partition.xml
misc/config_tools/data/apl-up2/logical_partition.xml
misc/config_tools/data/ehl-crb-b/fusa_partition.xml
misc/config_tools/data/ehl-crb-b/logical_partition.xml
misc/config_tools/data/generic_board/logical_partition.xml
misc/config_tools/data/nuc6cayh/logical_partition.xml
misc/config_tools/data/nuc7i7dnb/logical_partition.xml
misc/config_tools/data/tgl-rvp/industry.xml
misc/config_tools/data/tgl-rvp/logical_partition.xml
misc/config_tools/data/whl-ipc-i5/logical_partition.xml
misc/config_tools/data/whl-ipc-i7/logical_partition.xml

commit 873ed752d ("misc: sanity check VM config for nested virtualization")
requires that the guest_flag tag can't be empty, or it fails to build.
This patch changes all instances of "<guest_flag></guest_flag>"
to "<guest_flag>0</guest_flag>".

config-tools: guest_flag must be assigned with a valid value

---

misc/config_tools/data/ehl-crb-b/ehl-crb-b.xml
misc/config_tools/data/tgl-rvp/tgl-rvp.xml

This patch applies the latest board inspector on ehl-crb-b and tgl-rvp to
generate additional information to the board XMLs.
Tracked-On: #5922

config_tools: update board XMLs of ehl-crb-b and tgl-rvp

---

devicemodel/core/mevent.c
misc/debug_tools/acrn_crashlog/acrnprobe/include/probeutils.h

Unify two functions definitions/declarifications:
Update the parameters from char array to char pointer.
to fix the build issue:
probeutils.c:61:29: error: argument 1 of type 'char *' declared
as a pointer [-Werror=array-parameter=]
Initialize local variable "c" to fix build issue:
core/mevent.c:122:21: error: 'c' may be used uninitialized
[-Werror=maybe-uninitialized]
Tracked-On: #5993

build: fix dm and acrn_crashlog build error with gcc-11

---

devicemodel/Makefile
hypervisor/Makefile
misc/debug_tools/acrn_crashlog/acrnprobe/Makefile
misc/debug_tools/acrn_crashlog/usercrash/Makefile
misc/services/life_mngr/Makefile

This patch series contains some changes for ACRN makefiles and relates to build reproducibility required for generating reliably reproducible packages on a build system like Debian packaging. Furthermore I added a first split up of the windows and linux build of life_mngr:
* Makefile: Make builds reproducible
* Makefile: honor BUILD_VERSION and BUILD_TAG
* Makefile: lifemngr: split linux and windows build
Otherwise there is no impact on the build system.
The patches are already used for quite a while within my ACRN fork for Debian packaging and were affirmed by @NanlinXie and her team.

Makefile improvements

---

hypervisor/boot/guest/vboot_info.c
hypervisor/common/vm_load.c
misc/config_tools/xforms/misc_cfg.h.xsl

1. HV: refine init_vm_bootargs_info():
1) The VM load order type condition is not needed, since the function is called only when create SOS VM or pre-launched VM;
2) Fixed wrong parameter of fill_seed_arg() which introduced by commit 80262f060293d2ba613fa70673ebe794a511ce9c.
3) More comments on why multiboot string could override the pre-configured VM bootargs and why append multiboot cmdline to SOS VM bootargs;
2. HV: remove SOS kernel hugepage related bootargs: 
Hypervisor does not need to care about hugepage settings in SOS kernel, user could enable these settings in the scenario config file or GRUB menu.
3. Config_tools: config hugepage in sos kenrel cmdline:
If there is hugepage support from board xml, config tool will add hugepagesz=1G hugepages=[size] into sos kernel cmdline, the …

Update hugepage config in SOS Bootargs.

---

devicemodel/core/main.c
devicemodel/core/pm_vuart.c
devicemodel/include/pm.h
devicemodel/include/pm_vuart.h

A user can use "--pm_notify_channel uart,allow_trigger_s5" to indicate
the User VM is allowed to trigger system S5.
"--pm_notify_channel uart" means a vuart channel will be created in the
User VM to allow communication with the VM's life_mngr. The Service VM
can then initiate S5 in the guest via its dm's monitor interface. The
additional option, "allow_trigger_s5", will create a socket connection
with the Service VM's life_mngr, allowing this VM to initiate system S5.
v1 -> v2:
- rename pm_notify_channel type to PWR_EVENT_NOTIFY_UART_TRIG_PLAT_S5
Tracked-On: #6034

dm: add allow_trigger_s5 mode to pm_notify_channel uart

---

hypervisor/arch/x86/cpu.c

The accrss right of HV RAM can be changed to PAGE_USER (eg. trusty RAM
of post-launched VM). So before using clflush(or clflushopt) to flush
HV RAM cache, must allow explicit supervisor-mode data accesses to
user-mode pages. Otherwise, it may trigger page fault.

Fix page fault when HV flash its RAM cache

---

devicemodel/bios/changelog_ovmf.txt

- Change 64-bit MMIO BAR window to 256G-512G
The release is the same as 736a03222f5f359aadac9119062ee8255160bad2.
This is just to update the changelog.
Tracked-On: #5913

OVMF release v2.5

---

hypervisor/arch/x86/cpu.c

The accrss right of HV RAM can be changed to PAGE_USER (eg. trusty RAM
of post-launched VM). So before using clflush(or clflushopt) to flush
HV RAM cache, must allow explicit supervisor-mode data accesses to
user-mode pages. Otherwise, it may trigger page fault.

HV: cache: Fix page fault by flushing cache for VM trusty RAM in HV

---

hypervisor/arch/x86/cpu.c

The commit 2ab70f43e5ff682382d2f30fcb0d582a9f4e501d
HV: cache: Fix page fault by flushing cache for VM trusty RAM in HV
It is wrong in using stac()/clac()

HV: Fix mistake use stac() & clac()

---

devicemodel/core/mem.c

Only free rb_entry when we remove this entry from the rb tree, otherwise, a
page fault would trigger when next rb itreation would access the freed rb_entry.
Tracked-On: #6056

dm: rb: only free rb_entry when we remove this entry from the rb tree

---

devicemodel/core/mem.c

Only free rb_entry when we remove this entry from the rb tree, otherwise, a
page fault would trigger when next rb itreation would access the freed rb_entry.
Tracked-On: #6056

release_2.5: dm: rb: only free rb_entry when we remove this entry from the rb tree

---

hypervisor/scripts/genconf.sh
misc/config_tools/static_allocators/bdf.py
misc/config_tools/static_allocators/gpa.py
misc/config_tools/static_allocators/lib/lib.py
misc/config_tools/xforms/board_info.h.xsl
misc/config_tools/xforms/lib.xsl
misc/config_tools/xforms/pci_dev.c.xsl

Generate board_info.h and pci_dev.c based on the new board.xml and integrated to acrn project compilation.
Two static allocators are added: mmio.py and bdf.py. Those allocate free mmio windows and bdf to emulated vuarts, inter-vm shared memory and passthrough devices

config-tools: board_info.h and pci_dev.c xfom using xslt 

---

hypervisor/scripts/genconf.sh
misc/config_tools/static_allocators/bdf.py
misc/config_tools/static_allocators/gpa.py
misc/config_tools/static_allocators/lib/lib.py
misc/config_tools/xforms/board_info.h.xsl
misc/config_tools/xforms/lib.xsl
misc/config_tools/xforms/pci_dev.c.xsl

Generate board_info.h and pci_dev.c based on the new board.xml and integrated to acrn project compilation.
Two static allocators are added: mmio.py and bdf.py. Those allocate free mmio windows and bdf to emulated vuarts, inter-vm shared memory and passthrough devices

config-tools: board_info.h and pci_dev.c xfom using xslt

---

devicemodel/include/pci_core.h

VM 32-bit mmio window is 2G~3.5G
Tracked-On: #6011

release2.5:DM: change 32-bit mmio limit to 3.5G

---

misc/config_tools/data/adl-rvp/industry.xml

commit 873ed75 ("misc: sanity check VM config for nested virtualization")
requires that the guest_flag tag can't be empty, or it will fail to build.
This patch changes adl instances of "<guest_flag></guest_flag>" to
"<guest_flag>0</guest_flag>".
Signed-off-by: Jiang, Yanting <yanting.jiang@intel.com>

config-tools: fix guest_flag issue in config xml for adl

---

misc/config_tools/library/common.py

fix the guest_flag error when saving scenario xml from config
tool UI.
Tracked-On: #6075

config_tools: fix the guest_flag error when saving scenario xml

---

devicemodel/core/vmmapi.c

When a platform reboots or shuts down, the contents of RAM are not immediately
lost but begins to decay. During this period, there is a short timeframe during
which an attacker can turn the platform back on to boot into a program that
dumps the contents of memory (e.g., cold boot attacks). Encryption keys and
other secrets can be easily compromised through this method.
We already erasing the guest memory data when the guest is shut down normally.
However, if the guest is shut down abnormally, the contents of RAM may still
there. This patch mitigate this kind reset attack for a DM launched VM by
erasing the guest memory data by the guest has been created.
Tracked-On: #6061

release_2.5: dm: mitigate reset attack

---

hypervisor/arch/x86/guest/vmcs.c
hypervisor/arch/x86/vmx.c

Remove the direct calls to exec_vmptrld() or exec_vmclear(), and replace
with the wrapper APIs load_va_vmcs() and clear_va_vmcs().

hv: VMPTRLD and VMCLEAR VMCS with the common APIs

---

devicemodel/core/vmmapi.c
devicemodel/hw/platform/acpi/acpi.c
devicemodel/hw/platform/acpi/rtct.c
devicemodel/include/acpi.h
devicemodel/include/public/vhm_ioctl_defs.h
devicemodel/include/types.h
devicemodel/include/vmmapi.h
hypervisor/arch/x86/guest/vcpuid.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/common/hypercall.c
hypervisor/include/public/acrn_hv_defs.h
misc/config_tools/acpi_gen/asl_gen.py

This pull request introduces the support to use physical APIC IDs as vLAPIC IDs for
pre-launched and post-launched VMs, as an attempt to reproduce the host CPU/cache
topology in pre-launched and post-launched VMs.

Use physical APIC IDs as vLAPIC IDs for pre-launched and post-launched VMs

---

devicemodel/include/pci_core.h

VM 32-bit mmio window is 2G~3.5G
Tracked-On: #6011

DM: change 32-bit mmio limit to 3.5G

---

devicemodel/hw/pci/ptm.c
hypervisor/hw/pci.c
hypervisor/include/hw/pci.h

This patch includes 2 parts:
hv: during pci init, hv enables PTM on PTM root capable root port.
dm: add a sanity check whether PTM is enabled before launch guest

Always enable PTM on PTM root capable root port

---

hypervisor/arch/x86/boot/cpu_primary.S
misc/efi-stub/Makefile
misc/efi-stub/MpService.h
misc/efi-stub/boot.c
misc/efi-stub/boot.h
misc/efi-stub/container.c
misc/efi-stub/container.h
misc/efi-stub/efilinux.h
misc/efi-stub/malloc.c
misc/efi-stub/multiboot.h
misc/efi-stub/pe.c
misc/efi-stub/stdlib.h

This PR has 2 commits:
hv: restore the hypervisor 64-bit entry address for efi-stub
efi-stub: add acrn efi application as an alternative bootloader for secure boot
This PR introduces a new ACRN EFI application based on the legacy efi-stub code which provides booting method of HV on UEFI-BIOS without using the GRUB Bootloader. It is supposed to be used for secure booting on certain platform. By means of that users can boot HV, Service VM kernel, pre-launched VM kernel and its ACPI table binary packed in the Slim Bootloader container boot image file format. ACRN EFI application has additional dependencies to compile which are not listed in the existing ACRN GSG doc. Since this is an optional feature but not all users need, it does not get compiled by default to avoid causing any confusion …

Make ACRN HV with hybrid_rt bootable without GRUB on UEFI BIOS

---

hypervisor/arch/x86/guest/vlapic.c

In physical destination mode, the destination processor is specified by its
local APIC ID. When a CPU switch xAPIC Mode to x2APIC Mode or vice versa,
the local APIC ID is not changed. So a vcpu in x2APIC Mode could use physical
Destination Mode to send an IPI to another vcpu in xAPIC Mode by writing ICR.
This patch adds support for a vCPU A could write ICR to send IPI to another
vCPU B which is in different APIC mode.

hv: vlapic: a minor refine about vlapic_x2apic_pt_icr_access

---

devicemodel/hw/pci/ptm.c
hypervisor/hw/pci.c
hypervisor/include/hw/pci.h

This patch has 2 parts:
hv: during pci init, hv enables PTM on root port which is PTM root capable
dm: Add a sanity check whether PTM is enabled

HV always enables PTM on ptm root capable root port

---

devicemodel/hw/pci/ptm.c

Cherry-pick the changes from master to release 2.5 since my last patch
is merged already.
hv is responsible to ensure PTM is always enabled on hw root port if
that root port is PTM root-capable.  If PTM root is not enabled already in physical
root port before guest launch, guest OS can only enable it in root port's virtual
config space and PTM may not function as desired so we would rather not
to allow user to enable PTM on pass-thru device in this case.
Also revisit a few comments to add assumption that acrn only support a
simple PTM hierarch emulation i.e., EP (ptm requestor) is directly connected
to root port (ptm root), or ptm requestor is rcie).
V4:
- Change behavior from V3: When users tries to enable PTM while PTM root is not enabled on
physical root port, allow user to launch VM …

dm: return error if PTM is not enabled on physical root port

---

hypervisor/arch/x86/guest/vlapic.c

In physical destination mode, the destination processor is specified by its
local APIC ID. When a CPU switch xAPIC Mode to x2APIC Mode or vice versa,
the local APIC ID is not changed. So a vcpu in x2APIC Mode could use physical
Destination Mode to send an IPI to another vcpu in xAPIC Mode by writing ICR.
This patch adds support for a vCPU A could write ICR to send IPI to another
vCPU B which is in different APIC mode.

release_2.5: hv: vlapic: a minor refine about vlapic_x2apic_pt_icr_access

---

hypervisor/acpi_parser/acpi_ext.c
hypervisor/arch/x86/rtcm.c
hypervisor/boot/include/acpi.h
hypervisor/include/arch/x86/asm/rtcm.h

Signature of RTCT ACPI table maybe "PTCT"(v1) or "RTCT"(v2).
and the MAGIC number in CRL header is also changed from "PTCM"
to "RTCM".
This patch refine the code to detect RTCT table for both
v1 and v2.

[release_v2.5] hv: update RTCT ACPI table detecting

---

misc/efi-stub/boot.c
misc/efi-stub/boot.h
misc/efi-stub/efilinux.h

This patch sets the MemoryOverwriteRequestControl (MORCtrl for short)
EFI variable before jumping to hypervisor.
Setting variable MemoryOverwriteRequestControlLock (MORCtrlLock for
short) can also be enabled by manually adding -DMORCTRL_LOCK_ENABLED to
CFLAGS.
Setting MORCtrl indicates to the platform firmware that memory be
cleared upon system reset. Setting MORCtrlLock for the first time will
render both MORCtrl and MORCtrlLock to read-only, until next reset.
Tracked-On: #6097 

misc: efi-stub: Set MOR bit before jumping to hypervisor

---

misc/config_tools/acpi_gen/acpi_const.py
misc/config_tools/acpi_gen/asl_gen.py
misc/config_tools/acpi_gen/bin_gen.py

add RTCT table integrated with ACPI binary for pre-launched
VMs.
Tracked-On: #6025

config_tools: add RTCT table support in pre-launched VMs

---

doc/tutorials/acrn_on_qemu.rst

We missed a section during our last update to the QEMU tutorial
that references which version (tag) of ACRN to use.
Tracked-On: #5928

doc: update ACRN version QEMU tutorial

---

misc/config_tools/schema/checks/pre_launched_vm_support.xsd

Update the severity from "warning" to "error" for hybrid cores check.
Tracked-On: #5918

Config_tools: Update Hybrid Cores

---

misc/config_tools/data/sample_launch_scripts/nuc/launch_win.sh
misc/config_tools/launch_config/com.py
misc/config_tools/library/launch_cfg_lib.py

Modify the initial value of PT_SLOT variable and
update the get slot logic that all device call the virtual_dev_slot function to get slot number directly.
Copy the launch_uos_id1.sh to launch_win.sh.
Tracked-On: #6072

Config_tools: Update get slot logic

---

hypervisor/acpi_parser/acpi_ext.c
hypervisor/arch/x86/rtcm.c
hypervisor/boot/include/acpi.h
hypervisor/include/arch/x86/asm/rtcm.h

Signature of RTCT ACPI table maybe "PTCT"(v1) or "RTCT"(v2).
and the MAGIC number in CRL header is also changed from "PTCM"
to "RTCM".
This patch refine the code to detect RTCT table for both
v1 and v2.

[mainline]hv: update RTCT ACPI table detecting

---

devicemodel/hw/pci/virtio/virtio_net.c

Add a check on this place to avoid NULL access issue.
Tracked-On: #6100

dm: NULL check of vq->used in virtio_net_ping_rxq

---

misc/config_tools/data/qemu/qemu.xml

Make up qemu.xml to compromise the static allocators which use the
new xpath based on board inspector.
Tracked-On: #6102

config-tools: update qemu.xml

---

hypervisor/Makefile
hypervisor/arch/x86/guest/nested.c
hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/guest/vept.c
hypervisor/arch/x86/guest/vmexit.c
hypervisor/include/arch/x86/asm/guest/nested.h
hypervisor/include/arch/x86/asm/guest/vept.h

After these patches are merged, it's supposed that it can enable nVMX on SOS without vEPT support.

hv: nested virtualization part 4 - master

---

hypervisor/dm/vpci/vpci.c

Should call vpci_init_vdevs() after mmio window resource has been
initialized
Tracked-On: #6011

release2.5 HV: VPCI: Fix too much of pci_vdev_update_vbar_base log

---

devicemodel/hw/pci/virtio/virtio.c

inputs shall be validated to avoid NULL pointer access.
Tracked-On: #6219

[release_v2.5] dm: validate inputs in vq_endchains

---

devicemodel/hw/mmio/core.c
devicemodel/hw/platform/acpi/acpi.c

The TPM driver will access some mmio registers using absolute address,
That means TPM base GPA must use same HPA value, when passthough it to VM

Release 2.5: DM: TPM: Fix TPM passthrough must use identical mapping

---

devicemodel/hw/pci/virtio/virtio_audio.c
devicemodel/hw/pci/virtio/virtio_block.c
devicemodel/hw/pci/virtio/virtio_console.c
devicemodel/hw/pci/virtio/virtio_coreu.c
devicemodel/hw/pci/virtio/virtio_gpio.c
devicemodel/hw/pci/virtio/virtio_hdcp.c
devicemodel/hw/pci/virtio/virtio_hyper_dmabuf.c
devicemodel/hw/pci/virtio/virtio_i2c.c
devicemodel/hw/pci/virtio/virtio_input.c
devicemodel/hw/pci/virtio/virtio_ipu.c
devicemodel/hw/pci/virtio/virtio_mei.c
devicemodel/hw/pci/virtio/virtio_net.c
devicemodel/hw/pci/virtio/virtio_rnd.c
devicemodel/hw/pci/virtio/virtio_rpmb.c

With virtio polling mode enabled, a timer is running in the virtio
backend service. And the timer will also be triggered if its frondend
driver didn't do the device reset in shutdown. A freed virtio device
will be accessed in the polling timer handler.
Do the virtio reset() callback specifically to clear the polling timer
before the free.
Tracked-On: #6147

dm: Reset virtio device before release

---

doc/.known-issues/doc/dupdecl.conf
doc/conf.py

All releases of ACRN use the same CI docker image for testing the
documentation build. This creates a problem because some features used
in older ACRN releases are deprecated or behave differently with newer
versions of Sphinx and other tools.  Add a check for the Sphinx version
to account for this, and update the .known-issues patterns for duplicate
declarations.

doc: tweak doc config for v2.3 for CI tool mismatch

---

hypervisor/arch/x86/guest/ve820.c
hypervisor/arch/x86/guest/vm.c
hypervisor/include/arch/x86/vm_config.h
misc/acrn-config/scenario_config/scenario_item.py
misc/acrn-config/scenario_config/vm_configurations_c.py
misc/acrn-config/scenario_config/vm_configurations_h.py

This patch is specifically for ANL only, as currently only ANL is using HPA2/HPA3.
Currently acrn supports 2 non-contiguous HPA regions (HPA1 and HPA2), extend
the code to support 3rd non-contiguous HPA region (HPA3) for logical partition scenario
(hybrid scenario is not supported).
To keep things simple, current design has the following assumptions for
ve820 and ept mapping:
HPA2 will always be placed after HPA1
HPA3 will always be placed after HPA2
HPA1/HPA2/HPA3 don’t share a single ve820 entry.
(Create multiple entries if needed but not shared)
Tracked-On: #6145

Add support to assign 3rd non-contiguous HPA regions for logical partition scenario

---

devicemodel/hw/pci/virtio/virtio.c

inputs shall be validated to avoid NULL pointer access.
Tracked-On: #6129

dm: validate inputs in vq_endchains

---

devicemodel/hw/platform/acpi/acpi.c

return with error when read native RTCT done induces
memory leakage pointered by 'buf'.

dm: fix memory leakage risk in create_and_inject_vrtct

---

hypervisor/arch/x86/guest/vm.c
hypervisor/debug/uart16550.c
hypervisor/include/debug/uart16550.h
hypervisor/release/console.c
hypervisor/release/uart16550.c

We need to deny accesses from SOS to the HV owned UART device, otherwise
SOS could have direct access to this physical device and mess up the HV
console.
If ACRN debug UART is configured as PIO based, For example,
CONFIG_SERIAL_PIO_BASE is generated from acrn-config tool, or the UART
config is overwritten by hypervisor parameter "uart=port@<port address>",
it could run into problem if ACRN doesn't emulate this UART PIO port
to SOS. For example:
- none of the ACRN emulated vUART devices has same PIO port with the
port of the debug UART device.
- ACRN emulates PCI vUART for SOS (configure "console_vuart" with
PCI_VUART in the scenario configuration)
This patch fixes the above issue by masking PIO accesses from SOS.
deny_hv_owned_devices() is moved after setup_io_bitmap() where …

hv: deny access to HV owned legacy PIO UART from SOS

---

hypervisor/include/arch/x86/asm/e820.h

e820_alloc_memory() splits one E820 entry into two entries. With vEPT
enabled, e820_alloc_memory() is called one more. On some platforms, the
e820 entries might exceed 32.
Enlarge E820_MAX_ENTRIES to 64. Please note, it must be less than 128
due to constrain of zeropage. Linux kernel defines it as 128.
Tracked-On: #7198

hv: Enlarge E820_MAX_ENTRIES to 64

---

doc/developer-guides/hld/hv-memmgt.rst
hypervisor/arch/x86/guest/ept.c
hypervisor/arch/x86/guest/nested.c
hypervisor/arch/x86/guest/vept.c
hypervisor/include/arch/x86/asm/e820.h
hypervisor/include/arch/x86/asm/guest/ept.h

Rename get_ept_entry() to get_eptp().
vmptrld_vmexit_handler() has a same code snippet with vmclear_vmexit_handler(). Wrap the same code snippet as a static    function clear_vmcs02().

Some minor code refinements

---

misc/config_tools/library/common.py
misc/config_tools/library/scenario_cfg_lib.py

Refine get_pt_intx_table. The method parse the <pt_inx> of scenario and
append the pair of phys_gsi and virt_gsi if there is any.
Refine check_pt_intx. Add a condition that the method returns if the
phys_gsi and virt_gsi are empty dictionary.
Tracked-On: #6178

config-tools: refine get_pt_intx_table and check_pt_intx

---

devicemodel/hw/pci/xhci.c

The trb pointer may be NULL when get the address from user space,
add the pointer check before use the trb.
Tracked-On: #6172
Signed-off-by: Liu Long long.liu@intel.com
Reviewed-by: Shuo A Liu shuo.a.liu@intel.com

DM: xHCI: Add the trb pointer check

---

devicemodel/core/mem.c

return value 'err' of mmio_rb_lookup() being 0 ensures
'entry' is not NULL, hence checking it before 'free(entry)'
is unnecessary.

[release_2.5] dm: remove redundant null check in unregister_mem_init

---

devicemodel/hw/platform/acpi/acpi.c

return with error when read native RTCT done induces
memory leakage pointered by 'buf'.

[release_2.5] DM v2.5 bugfix create and inject vrtct

---

devicemodel/core/mem.c

return value 'err' of mmio_rb_lookup() being 0 ensures
'entry' is not NULL, hence checking it before 'free(entry)'
is unnecessary.

dm: remove redundant null check in unregister_mem_init

---

doc/scripts/configdoc.xsl

Seperate options with simple types with a heading so they don't get
hidden under the previous options that are part of a complex type.

doc: fix config option display

---

doc/developer-guides/hld/hv-timer.rst
hypervisor/include/arch/x86/asm/tsc.h
hypervisor/include/common/ticks.h

Replace rdstc() and get_tsc_khz() with their architectural agnostic
counterparts cpu_ticks() and cpu_tickrate().
Tracked-On: #5920
Signed-off-by: Yi Liang <yi.liang@intel.com>

doc: update timer HLD doc after modularization

---

doc/tutorials/acrn_configuration_tool.rst
misc/config_tools/board_inspector/README

Update the content about getting board xml from native
enviroment in acrn_configuration_tool.rst and README.
Tracked-On: #6134

doc: update the content about generating board xml

---

doc/tutorials/acrn_configuration_tool.rst

Add allow_trigger_s5, enable_ptm, console_vuart and communication_vuart
descriptions.
Tracked-On: #6138

doc: add missing parameters description of launch script xml

---

devicemodel/hw/pci/xhci.c

The trb pointer may be NULL when get the address from user space, add
the pointer check before use the trb.
Tracked-On: #6172

DM: xHCI: Check trb pointer before use it

---

devicemodel/hw/pci/ptm.c
hypervisor/dm/vpci/vroot_port.c
hypervisor/include/arch/x86/asm/vm_config.h
hypervisor/include/hw/pci.h
hypervisor/include/public/acrn_common.h

Root cause:  vrp accidentally changed passthru device's max payload which doesn't match its backend's max payload.  This match causes tx/rv to fail on ethernet card.
Fix: Set vrp's max payload to match hardware value

Fix the bug that pci passthru ethernet failed to get ip address

---

misc/config_tools/library/common.py

Without this, the GUEST_FLAG_NVMX_ENABLED doesn't show up in the
drop-down list of "guest_flags" in the ACRN config GUI.

config_tools: add the missing GUEST_FLAG_NVMX_ENABLED to common.py

---

.clang-format

Remove the AlwaysBreakTemplateDeclarations setting in clang-format file
to fix the issue about "make defconfig".
Tracked-On: #6199

config_tools: update clang-format file

---

devicemodel/hw/pci/virtio/virtio_console.c

Use the teardown API as the unify free console API in virtio console,
in case the console have already been freed by deinit when the teardwon
API is called.

ACRN: DM: Free the console in the unify API

---

doc/reference/hardware.rst
doc/try.rst

Update the ACRN documentation with regards to the supported HW:
* Remove outdated reference to Apollo Lake and Kaby Lake
* Re-order HW platforms in "Supported HW" to be consistent throughout
the document
* Use the '|copy|' and '|trade|' replacements
* Update the recommendation for creating nnon-existant $(BOARD).xml
Tracked-On: #6227

doc: update the "Supported Hardware" document

---

doc/getting-started/getting-started.rst
doc/try.rst

Updates to the Getting Started Guide:
* Update title to simply be "Getting Started Guide"
* Simplify and remove instructions that are redundant
* Add a note explaining the difference between 'nuc11tnbi5' and
'nuc11tnhi5'
Tracked-On: #6225

doc: updates to the Getting Started Guide

---

doc/tutorials/enable_s5.rst

enable_s5.rst has a couple of literalinclude directives referencing
sample scripts that were moved and now go through a symbolic link to the
new folder.  Symbolic links don't work on Windows, so change the
references in enable_s5.rst to not go through the symbolic link.

doc: fix doc reference using symbolic link

---

devicemodel/hw/pci/passthrough.c
devicemodel/include/pcireg.h

Add PCI IDS for ElkhartLake/TigerLake/AlderLake in GPU DSM and OpRegion
passthrough.
Tracked-On: #6270
Signed-off-by: Sun Peng <peng.p.sun@intel.com>

dm: Add PCI IDS for EHL/TGL/ADL in GPU passthrough

---

devicemodel/hw/mmio/core.c
devicemodel/hw/platform/acpi/acpi.c

The TPM driver will access some mmio registers using absolute address,
That means TPM base GPA must use same HPA value, when passthough it to VM

DM: TPM: Fix TPM passthrough must use identical mapping

---

hypervisor/include/lib/list.h

To add brakets for '(char *)(ptr)' in MACRO
container_of(), which may be used recursively.
Tracked-On: #6284

hv: minor coding style fix in list.h

---

hypervisor/include/lib/list.h

To add brakets for '(char *)(ptr)' in MACRO
container_of(), which may be used recursively.
Tracked-On: #6284

[release_2.3.1] hv: minor coding style fix in list.h

---

misc/config_tools/data/adl-rvp/adl-rvp.xml
misc/config_tools/data/cfl-k700-i7/cfl-k700-i7.xml
misc/config_tools/data/ehl-crb-b/ehl-crb-b.xml
misc/config_tools/data/nuc11tnbi5/nuc11tnbi5.xml
misc/config_tools/data/nuc7i7dnb/nuc7i7dnb.xml
misc/config_tools/data/tgl-rvp/tgl-rvp.xml
misc/config_tools/data/whl-ipc-i5/whl-ipc-i5.xml
misc/config_tools/data/whl-ipc-i7/whl-ipc-i7.xml

The PR 6236 has modified the board.xml format for MAX_MSIX_TABLE_NUM fix.
To compromise this PR, updates all the source file board.xmls.
Tracked-On: #6235

config_tools: update board xml files for MAX_MSIX_TABLE_NUM fix

---

hypervisor/arch/x86/guest/vm.c

The vRSDP region of pre-launched VM is located at 0xf2400, it could be
overlapped with the memory space of the raw image so be overriden by
raw image loading. In this case VM would be failed to find ACPI table.
This patch fix this issue by loading raw image first and then building
vRSDP later.
Tracked-On: #6305

[Release 2.5]HV: vm_load: build vrsdp after VM image loaded

---

doc/develop.rst
doc/tutorials/enable_ptm.rst

Restore PTM tutorial removed for the 2.5 release (it's tested as
working now)

doc: add enable PTM tutorial

---

misc/config_tools/board_inspector/cli.py
misc/config_tools/board_inspector/cpuparser/__init__.py
misc/config_tools/board_inspector/cpuparser/cpuids.py
misc/config_tools/board_inspector/extractors/10-processors.py
misc/config_tools/board_inspector/legacy/board_parser.py

While running in a nested environment, such as qemu, parse the board information should be allowed even it is not in a native environment.
Replace the error with warning message and does not exit the program.
Tracked-On: #6208

config-tools: do not exit when the board inspector runs in hypervisor

---

doc/tutorials/nvmx_virtualization.rst

Add notation description for VMCSxx introducted in the nested
virtualization tutorial.

doc: update nested virtualization tutorial notation

---

hypervisor/arch/x86/guest/vmexit.c
hypervisor/debug/console.c
hypervisor/include/debug/console.h
hypervisor/release/console.c

In some scenarios (e.g., nested) where lapic-pt is enabled for a vcpu
running on a pcpu hosting console timer, the hv console will be
inaccessible.
This patch adds the console callback to every VM-exit event so that the
console can still be somewhat functional under such circumstance.
Since this is VM-exit driven, the VM-exit/second can be low in certain
cases (e.g., idle or running stress workload). In extreme cases where
the guest panics/hangs, there will be no VM-exits at all.
In most cases, the shell is laggy but functional (probably enough for
debugging purpose).
Tracked-On: #6312

hv: debug: Add hv console callback to VM-exit event

---

hypervisor/arch/x86/guest/vcpuid.c
hypervisor/arch/x86/guest/vmcs.c
hypervisor/arch/x86/guest/vmsr.c

for core partition VM (like RTVM), PMC is always used for performance
profiling / tuning, so expose PMC capability and pass-through its MSRs
to the VM.
Tracked-On: #6307

hv:  expose PMC to core partition VM

---

misc/config_tools/static_allocators/gpa.py

The log area of TPM is typically placed as part of the ACPI data region in
e820. This patch follows this convention by adjusting how the virtual TPM
log area base address is allocated.

config_tools: adjust the end of TPM log area

---

hypervisor/arch/x86/guest/vm.c

If mmio resource is included in ACPI DATA e820 entry, it is will be
mapped to RAM first. Then pre-launched VM can't map mmio resource GPA
to its MMIO HPA.

Release 2.5：Mmiodev del before add

---

hypervisor/dm/vpci/vpci.c

According to PCIe Spec, for a RW register bits, If the optional feature
that is associated with the bits is not implemented, the bits are permitted
to be hardwired to 0b. However Zephyr would use INTx Line Register as writable
even this PCI device has no INTx, so emulate INTx Line Register as writable.
Tracked-On: #6330

release_2.5: hv: vpci: modify Interrupt Line Register as writable

---

misc/config_tools/config_app/templates/base.html
misc/config_tools/config_app/views.py

config editor creates the default scenario xmls and launch xmls
based on generic configs and set the values to the default ones
from xml schema when users import a new board.
Tracked-On: #6208

config_tools: config editor creates default xmls for a new board

---

hypervisor/quirks/smbios.c

The SMBIOS passthrough is supposed to work under UEFI environment.
Previous patches assumes UEFI environment but it may cause problems on
some platforms. This patch adds checking before probing SMBIOS table to
avoid this problem.
Tracked-On: #6345

hv: SMBIOS: add check before SMBIOS probing

---

hypervisor/debug/uart16550.c

Currently the HV console does not support PCI UART with 64bit BAR, but in the
case that the BAR is in 64bit and the BAR space is below 4GB (i.e. the high
32bit address of the 64bit BAR is zero), HV should be able to support it.
Tracked-On: #6334

[Release 2.5]HV: debug: support 64bit BAR pci uart with 32bit space

---

hypervisor/arch/x86/cpu_caps.c
hypervisor/arch/x86/mmu.c
hypervisor/dm/vpci/vpci.c

1. remove the constraint "MMU and EPT must both support large page or not"
2. modify Interrupt Line Register as writable
Tracked-On: #6330

HV: fix two minor bug

---

hypervisor/boot/guest/vboot_info.c
hypervisor/common/vm_load.c
hypervisor/include/arch/x86/asm/guest/vm.h

This patch set is the first wave to enable prelaunched VM kernel image loading with ELF format. The patch set will refine the vm loader interface that set kernel/ramdisk load address at VM software module loading stage.
Previously the kernel/ramdisk load address is initialized in vboot_info initialization stage, which is meaningless if kernel image has multiple load segments like ELF format.
Tracked-On: #6323

HV: VM loader refinement

---

misc/config_tools/data/ehl-crb-b/ehl-crb-b.xml

The debug uart of mmio@0xfe042000 has been switched to pci uart at 0:19.2,
so change the board file accordingly.
Tracked-On: #6348

config_tools: update ehl-crb-b xml with new uart

---

doc/Makefile

doc: remove obsolete kconfig references in Makefile

---

Makefile
devicemodel/Makefile
hypervisor/Makefile

User could use make targz-pkg command to generate tar package in
build directory,which could help user simplify the process
of installing acrn hypervisor in target board. user need to copy the
tarball package to target board,and extract it to "/" directory.
Tracked-On: #6355
Signed-off-by: liu hang1 <hang1.liu@intel.com>
Reviewed-by: VanCutsem, Geoffroy <geoffroy.vancutsem@intel.com>

Makefile:add targz-pkg entry in Makefile

---

misc/config_tools/board_inspector/acpiparser/aml/context.py
misc/config_tools/board_inspector/acpiparser/aml/interpreter.py
misc/config_tools/board_inspector/acpiparser/aml/parser.py

When applying the board inspector on a wider range of boards, we identified the following issues.
1. The AML interpreter does not support some AML opcodes that are used by the DSDT on other boards, including OnesOp, DefMatch and DefSizeof.
2. The workaround introduced by commit e5ba06cbe80a only evaluates branch predications on integers, while conditions on strings or operation fields are also common.
This PR fixes the above two issues as well as clean up a duplicate method in the implementation of the AML parser.

Various fixes to the board inspector for wider applicability

---

hypervisor/arch/x86/guest/vmcs.c

If HV enable trigger #GP for uc-lock, and is about to emulate guest uc-lock
instructions, should trap guest #GP. Guest uc-lock instrucction trigger #GP,
cause vmexit for #GP, HV handle this vmexit and emulate uc-lock
instruction.
Tracked-On: #6299

hv: uc-lock: Fix do not trap #GP

---

misc/config_tools/board_inspector/acpiparser/aml/builder.py
misc/config_tools/board_inspector/acpiparser/aml/datatypes.py
misc/config_tools/board_inspector/acpiparser/aml/interpreter.py
misc/config_tools/board_inspector/extractors/50-acpi.py

On platforms with multiple host bridges (as is shown in `lspci -t`), the DSDT of the platform typically contains multiple device objects with the `_HID` or `_CID` `PNP0A08`, each of which having its own bus number (as is reported by `_BBN`). Some of these objects can be disabled, i.e. with `_STA` being defined and evaluates to 0.
This patch series enhances the board inspector to extract precise information about multiple-host-bridge platforms. This include:
* Only put the bus numbers of present host bridges in the board XML.
* Support buffer assignments and indexing, which may be used in DSDT to generate `_CRS` (i.e. current resource descriptors) of the host bridges.

Board inspector enhancements to parse DSDT on platforms with multiple host bridges

---

doc/tutorials/cpu_sharing.rst

Remove Kconfig related scheduler configuration in tutorials because the
Kconfig related files have been removed in the other PR 6358.

doc: update Kconfig related doc

---

devicemodel/core/vmmapi.c

When a platform reboots or shuts down, the contents of RAM are not immediately
lost but begins to decay. During this period, there is a short timeframe during
which an attacker can turn the platform back on to boot into a program that
dumps the contents of memory (e.g., cold boot attacks). Encryption keys and
other secrets can be easily compromised through this method.
We already erasing the guest memory data when the guest is shut down normally.
However, if the guest is shut down abnormally, the contents of RAM may still
there. This patch mitigate this kind reset attack for a DM launched VM by
erasing the guest memory data by the guest has been created.
Tracked-On: #6061

dm: mitigate reset attack

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/cpu_caps.c
hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/guest/vmcs.c
hypervisor/arch/x86/guest/vmexit.c
hypervisor/arch/x86/guest/vmsr.c
hypervisor/arch/x86/vtd.c
hypervisor/include/arch/x86/asm/guest/vcpu.h

Before supporting to run ACRN on qemu, ACRN always runs on the hardware platforms.
In order to achieve better performance, there're some constrains about the hardware
platforms, like the hardware platforms must support XSAVE Feature or the VTD mmio read
must be quickly and so on. However, these constrains are not met on most of the virtual
platforms which QEMU emulated. This patch set does two minor refine to support running
ACRN on qemu:
1. Check whether condition is met before check whether time is out after iommu_read32.
This is because iommu_read32 would cause time out on some virtual platform in
spite of the current DMAR status meets the pre_condition.
2. ACRN could run without XSAVE Capability. So remove XSAVE dependence to support
more (hardware or virtual) platforms.
V2:
add …

HV: two minor refine to support running ACRN on qemu

---

misc/config_tools/library/launch_cfg_lib.py

Update lpc slot to origin value 1 from 31 because GOP driver has assumption
to config space layout of the device on 00:1f.0.
Tracked-On: #6340

config_tools: update lpc slot number
