projectacrn/acrn-hypervisor

doc/tutorials/rtvm_performance_tips.rst

Fixed windows line endings, improved tip formatting, additional grammar
and content simplification edits.

doc: edits for rtvm_performance_tips doc

---

hypervisor/arch/x86/irq.c
hypervisor/arch/x86/lapic.c
hypervisor/include/arch/x86/idt.h

1. minor refine about structure idt_64_descriptor
2. minor refine about init_lapic

irq: two minor refine

---

doc/tutorials/building_acrn_in_docker.rst

Use the (new) numbered instruction style in one of our tutorials to
check it out.

doc: update docker build with numbered steps

---

doc/tutorials/acrn_configuration_tool.rst

Doc: Grammatical edits to acrn config tool doc

---

misc/acrn-config/launch_config/launch_item.py
misc/acrn-config/library/launch_cfg_lib.py
misc/acrn-config/library/scenario_cfg_lib.py
misc/acrn-config/scenario_config/scenario_item.py

- refine slot assignment for launch config
- refinement for CPU affinity check
Tracked-On: #4641
Signed-off-by: Wei Liu weix.w.liu@intel.com
Acked-by: Victor Sun victor.sun@intel.com

acrn-config: refine slot assignment for launch config

---

doc/developer-guides/hld/hld-hypervisor.rst
doc/developer-guides/hld/hld-splitlock.rst

Doc: HLD for Split-locked Access Handling

---

doc/developer-guides/hld/hld-splitlock.rst

Add some spelling, grammar, and presentation updates to this new HLD
doc.

doc: update to splitlock hld document

---

doc/tutorials/using_windows_as_uos.rst

doc:update waag gsg after enabling gvt-d and cpu-sharing.

---

doc/tutorials/using_windows_as_uos.rst

Fix consistent spelling of GVT-g and malformed bullet list.

doc: update windows as UOS tutorial

---

doc/getting-started/building-from-source.rst
doc/tutorials/acrn_configuration_tool.rst
doc/tutorials/cpu_sharing.rst
doc/tutorials/vuart_configuration.rst

doc update for hv elements of scenario XML, and build from source, etc.

doc: hv elements update

---

doc/developer-guides/hld/hv-cpu-virt.rst
doc/tutorials/acrn_configuration_tool.rst
doc/tutorials/cpu_sharing.rst

- Changed term from "VCPU affinity" to "CPU affinity"
- changed vcpu_affinity to cpu_affinity_bitmap in vm_config
- fixed some errors

doc: update CPU affinity related descriptions

---

doc/developer-guides/hld/hv-cpu-virt.rst

Update HLD with @zidechen0 material

doc: update HLD for hv_cpu_virt

---

doc/tutorials/agl-vms.rst

doc: fix broken link to touch monitor

---

misc/acrn-config/xmls/board-xmls/tgl-rvp.xml

Update tgl-rvp board information.

acrn-config: update tgl-rvp board information

---

doc/tutorials/using_celadon_as_uos.rst
doc/tutorials/using_zephyr_as_uos.rst

Clarify wording on tutorial notes about needing a serial port connection.

doc: edit notes on serial connection need

---

doc/asa.rst

Update mitigations for security vulnerabilities
for ACRN 1.6.1 release

doc: update security advisory for 1.6.1 release

---

doc/user-guides/kernel-parameters.rst

doc: update hvlog kernel parameter descriptions

---

doc/develop.rst
doc/tutorials/setup_openstack_libvert.rst
doc/tutorials/using_ubuntu_as_sos.rst

Doc: Initial file: Config ACRN using OpenStack & libvert

---

hypervisor/arch/x86/guest/vlapic.c

ACRN syncs PIR to vIRR in the software in cases the Posted
Interrupt notification happens while the pCPU is in root mode.
Sync can be achieved by processor hardware by sending a
posted interrupt notiification vector.
This patch sends a self-IPI, if there are interrupts pending in PIR,
which is serviced by the logical processor at the next
VMEnter
Tracked-On: #4777

hv: Offload syncing PIR to vIRR to processor hardware

---

doc/getting-started/rt_industry.rst

Add instruction to launch multiple post launched VMs.

doc: update industry getting started guide to v1.6.1

---

doc/tutorials/using_windows_as_uos.rst

doc: update GSG for ACRN V1.6.1.

---

doc/getting-started/building-from-source.rst
doc/tutorials/building_acrn_in_docker.rst

Signed-off-by: guoqingxz <guoqingx.q.zhang@intel.com>

doc: update build ACRN doc

---

doc/release_notes/release_notes_1.6.1.rst

Doc: releasenotes_1.6.1

---

doc/conf.py

doc: add 1.6.1 docs version menu choice

---

doc/release_notes/release_notes_1.6.1.rst

doc: edit 1.6.1 release notes

---

doc/release_notes/release_notes_1.6.1.rst

Syntax of acrn-issue role was incorrect in fixed issues section

doc: fix malformed acrn-issue references

---

doc/release_notes/release_notes_1.6.1.rst

doc: fix malformed acrn-issue role in release notes

---

doc/tutorials/waag-secure-boot.rst

Update acrn edk2 source code download path for WaaG
secure boot feature

doc: Update acrn edk2 download path

---

devicemodel/core/main.c
devicemodel/core/monitor.c
devicemodel/core/pm.c
devicemodel/core/vmmapi.c
devicemodel/hw/pci/wdt_i6300esb.c
devicemodel/include/vmm.h
devicemodel/include/vmmapi.h

add logs for vm state transition to help
analyze some problems.
Tracked-On: #4098

acrn-dm: add some logs for vm state transition

---

doc/developer-guides/hld/hv-cpu-virt.rst

Additional editing is forthcoming.

Doc: Grammatical edits to CPU Virtualization doc.

---

hypervisor/debug/shell.c

hv: debug: reboot directly when issue 'reboot' shell cmd

---

doc/tutorials/gpu-passthru.rst
doc/tutorials/using_windows_as_uos.rst

Doc: Grammatical edits to GVT-d docs.

---

hypervisor/arch/x86/Kconfig
hypervisor/arch/x86/vtd.c
hypervisor/include/arch/x86/vtd.h

Some code cleanup in vtd.c
Tracked-On: #4831

hv: vtd: code cleanup

---

devicemodel/core/sw_load_bzimage.c

To remove the limit of 4MB ramdisk size simply adjust layout
dynamically according to ramdisk size rounded up to a 4K boundary.
This enables ramdisk based virtual machines which tend to have
large ramdisk memory requirements (128MB and above).
Tracked-On: #4840

dm: bzimage: dynamically adapt to ramdisk size

---

CODEOWNERS

CODEOWNERS: Update the maintainer of misc folder

---

hypervisor/Makefile

Modify Makefile to add acrn.bin after install

---

doc/developer-guides/hld/hv-cpu-virt.rst
doc/developer-guides/trusty.rst
doc/faq.rst
doc/index.rst
doc/introduction/index.rst
doc/release_notes/release_notes_0.5.rst
doc/tutorials/acrn_configuration_tool.rst
doc/tutorials/run_kata_containers.rst
doc/tutorials/running_deb_as_user_vm.rst
doc/tutorials/running_ubun_as_user_vm.rst
doc/tutorials/using_celadon_as_uos.rst
doc/tutorials/using_windows_as_uos.rst
doc/user-guides/acrn-dm-parameters.rst

There are some subtle syntax errors in some documents that, while they
render OK (most of the time), are being caught by rstcheck (a
restructuredText linter). This PR fixes most of the issues encountered.

doc: rst syntax tweaks

---

doc/tutorials/run_kata_containers.rst

Update tutorial for running Kata containers on Ubuntu
Tracked-On: #4879

doc: update Kata tutorial for Ubuntu Service VM

---

misc/acrn-config/xmls/config-xmls/qemu/sdc.xml

add RDT configurable item for QEMU sdc xml
Tracked-On: #4889

acrn-config: add RDT configurable item for QEMU sdc xml

---

devicemodel/hw/pci/xhci.c

From xHCI spec 4.5.3.2, the only command that software is
allowed to issue for the slot in disabled state is the Enable
Slot Command. Drop other commands in command handle function.
Tracked-On: #4711

DM USB: xHCI: Drop commands if slot is disabled

---

doc/tutorials/run_kata_containers.rst

doc: tweak kata tutorial pre-requisites

---

doc/developer-guides/hld/ivshmem-hld.rst

doc: edit ivshmem hld doc

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/guest/guest_memory.c
hypervisor/arch/x86/guest/instr_emul.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/debug/sbuf.c
hypervisor/include/arch/x86/cpu.h
hypervisor/include/arch/x86/guest/guest_memory.h

dump more info when walk guest page table.
Note:
And this patch is not for fixing it. It's only debug patch. But we were
required to merge it to acrn-2.0 branch.
Tracked-On: #4908

debug: dump more info when walk guest page table.

---

misc/acrn-manager/README.rst

doc: update tools docs to use vm-ubuntu name

---

doc/tutorials/gpu-passthru.rst

doc:Refine GVT-d tutorial

---

doc/getting-started/rt_industry.rst

doc: update links to pre-built images

---

doc/developer-guides/hld/ivshmem-hld.rst

Add the example for two VMs communication

doc: add inter-vm communication example

---

hypervisor/boot/multiboot.c

The acrn_mbi.mi_mmap_va should point to struct multiboot2_mmap_entry when
boot from multiboot2, which is different from struct multiboot_mmap when
boot from multiboot1. So we should handle mmap info separately for multiboot2.
Tracked-On: #4885

HV: correct mmap info for multiboot2

---

hypervisor/arch/x86/configs/apl-mrb/board.c
hypervisor/arch/x86/configs/apl-mrb/misc_cfg.h
hypervisor/arch/x86/configs/apl-up2/board.c
hypervisor/arch/x86/configs/apl-up2/misc_cfg.h
hypervisor/arch/x86/configs/dnv-cb2/board.c
hypervisor/arch/x86/configs/dnv-cb2/misc_cfg.h
hypervisor/arch/x86/configs/generic/board.c
hypervisor/arch/x86/configs/generic/misc_cfg.h
hypervisor/arch/x86/configs/icl-rvp/board.c
hypervisor/arch/x86/configs/nuc6cayh/board.c
hypervisor/arch/x86/configs/nuc6cayh/misc_cfg.h
hypervisor/arch/x86/configs/nuc7i7dnb/board.c
hypervisor/arch/x86/configs/nuc7i7dnb/misc_cfg.h
hypervisor/arch/x86/configs/whl-ipc-i5/board.c
hypervisor/arch/x86/configs/whl-ipc-i5/misc_cfg.h
hypervisor/include/arch/x86/board.h
misc/acrn-config/board_config/board_c.py
misc/acrn-config/board_config/misc_cfg_h.py
misc/acrn-config/library/board_cfg_lib.py

-  hv: config: add msix emulation support
- acrn-config: generate msix emulation information
Tracked-On: #4831

Add msix emulation support

---

misc/acrn-config/launch_config/com.py
misc/acrn-config/library/launch_cfg_lib.py
misc/acrn-config/library/scenario_cfg_lib.py
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/industry.xml

- add support to generate General Linux/Yocto/Ubuntu
- modify whl-ipc-i7 default industry xml
Tracked-On: #4913

acrn-config: Add support generate linux like os scripts

---

misc/acrn-config/launch_config/com.py
misc/acrn-config/library/launch_cfg_lib.py
misc/acrn-config/library/scenario_cfg_lib.py
misc/acrn-config/xmls/config-xmls/apl-mrb/logical_partition.xml
misc/acrn-config/xmls/config-xmls/apl-mrb/sdc_launch_1uos_laag.xml
misc/acrn-config/xmls/config-xmls/apl-up2-n3350/logical_partition.xml
misc/acrn-config/xmls/config-xmls/apl-up2-n3350/sdc_launch_1uos_laag.xml
misc/acrn-config/xmls/config-xmls/apl-up2/logical_partition.xml
misc/acrn-config/xmls/config-xmls/apl-up2/sdc_launch_1uos_laag.xml
misc/acrn-config/xmls/config-xmls/ehl-crb-b/industry_launch_6uos.xml
misc/acrn-config/xmls/config-xmls/ehl-crb-b/logical_partition.xml
misc/acrn-config/xmls/config-xmls/ehl-crb-b/sdc_launch_1uos_laag.xml
misc/acrn-config/xmls/config-xmls/generic/logical_partition.xml
misc/acrn-config/xmls/config-xmls/nuc6cayh/industry_launch_6uos.xml
misc/acrn-config/xmls/config-xmls/nuc6cayh/logical_partition.xml
misc/acrn-config/xmls/config-xmls/nuc6cayh/sdc_launch_1uos_laag.xml
misc/acrn-config/xmls/config-xmls/nuc7i7dnb/industry_launch_6uos.xml
misc/acrn-config/xmls/config-xmls/nuc7i7dnb/logical_partition.xml
misc/acrn-config/xmls/config-xmls/nuc7i7dnb/sdc_launch_1uos_laag.xml
misc/acrn-config/xmls/config-xmls/tgl-rvp/industry_launch_1uos.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/industry_launch_6uos.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/logical_partition.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/sdc_launch_1uos_laag.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/industry.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/industry_launch_6uos.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/logical_partition.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/sdc_launch_1uos_laag.xml

- add support to generate General Linux/Yocto/Ubuntu
- modify whl-ipc-i7 default industry xml
Tracked-On: #4901

acrn-config: add support to generate yocto/generic linux launch script

---

doc/tutorials/acrn_configuration_tool.rst

update acrn_configuration_tool tutorial for RDT and update uos type
for launch configuration tutorial.

doc: update acrn_configuration_tool tutorial for RDT feature

---

doc/getting-started/rt_industry_ubuntu.rst

Update the "Getting Started Guide for ACRN Industry Scenario with Ubuntu Service
VM" document. Specifically:
* Fix some code sequences that were incorrect (wrong file names/paths, etc.)
* Broke down some long lines to improve readibility
* Add some text/notes at places to better explain the process

doc: Update the GSG for the Industrial scenario with Ubuntu

---

doc/tutorials/acrn_configuration_tool.rst

Doc: Edits to the acrn configuration tool

---

doc/introduction/index.rst

Doc: Edits to What is ACRN into doc

---

doc/developer-guides/hld/ivshmem-hld.rst

Doc: Grammatical edits to Shared mem based inter-VM comm doc

---

doc/introduction/index.rst
doc/tutorials/acrn_on_qemu.rst
doc/tutorials/gpu-passthru.rst

Fix misspellings in docs missed during regular reviews

doc: fix misspelling

---

devicemodel/core/hugetlb.c
hypervisor/acpi_parser/dmar_parse.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/hw/pci.c
misc/acrn-config/xmls/board-xmls/ehl-crb-b.xml
misc/acrn-config/xmls/config-xmls/ehl-crb-b/industry.xml

Pull request for release_2.0 branch to run EHL new board

Ehl bringup

---

hypervisor/arch/x86/boot/trampoline.S
hypervisor/arch/x86/cpu_caps.c
hypervisor/arch/x86/page.c
hypervisor/arch/x86/pagetable.c
hypervisor/arch/x86/trampoline.c
hypervisor/include/arch/x86/mmu.h
hypervisor/include/arch/x86/page.h

Pull request for release_2.0 branch to run EHL new board

Ehl bringup: remove 1GB large page support constrain

---

doc/introduction/index.rst

Update the table summarizing all ACRN scenario that are defined. The SDC
also offers the opportunity to run a Kata Containers VM and that was missing
from the description.

doc: update the summary table for all ACRN scenario

---

doc/tutorials/run_kata_containers.rst

Update the "Run Kata Containers on a Service VM" tutorial to use ACRN v2.0. It
also uses Ubuntu 20.04 as the baseline instead of Ubuntu 18.04. The Kata
Containers installation method is different as there are no pre-built binaries
for Ubuntu 20.04 yet, so using the 'kata-deploy' approach instead which is more
generic.
Tracked-On: #4944

doc: Update Kata Containers tutorial to ACRN v2.0

---

doc/tutorials/run_kata_containers.rst

Fixed a few layout issues and added link to mailing list

doc: fix presentation of kata containers tutorial

---

doc/developer-guides/hld/hv-dev-passthrough.rst
doc/release_notes/release_notes_2.0.rst

doc: v2.0 release notes

---

hypervisor/arch/x86/cpu_caps.c
hypervisor/arch/x86/guest/vcpuid.c
hypervisor/arch/x86/guest/vmcs.c
hypervisor/include/arch/x86/msr.h

Remove some unnecessary code
Add check for bit 48 in BASIC VMX INFORMATION MSR.

Tiny fix in hypervisor

---

misc/acrn-config/xmls/config-xmls/apl-mrb/logical_partition.xml
misc/acrn-config/xmls/config-xmls/apl-mrb/sdc_launch_1uos_laag.xml
misc/acrn-config/xmls/config-xmls/apl-up2-n3350/logical_partition.xml
misc/acrn-config/xmls/config-xmls/apl-up2-n3350/sdc_launch_1uos_laag.xml
misc/acrn-config/xmls/config-xmls/apl-up2/logical_partition.xml
misc/acrn-config/xmls/config-xmls/apl-up2/sdc_launch_1uos_laag.xml
misc/acrn-config/xmls/config-xmls/ehl-crb-b/industry_launch_6uos.xml
misc/acrn-config/xmls/config-xmls/ehl-crb-b/logical_partition.xml
misc/acrn-config/xmls/config-xmls/ehl-crb-b/sdc_launch_1uos_laag.xml
misc/acrn-config/xmls/config-xmls/generic/logical_partition.xml
misc/acrn-config/xmls/config-xmls/nuc6cayh/industry_launch_6uos.xml
misc/acrn-config/xmls/config-xmls/nuc6cayh/logical_partition.xml
misc/acrn-config/xmls/config-xmls/nuc6cayh/sdc_launch_1uos_laag.xml
misc/acrn-config/xmls/config-xmls/nuc7i7dnb/industry_launch_6uos.xml
misc/acrn-config/xmls/config-xmls/nuc7i7dnb/logical_partition.xml
misc/acrn-config/xmls/config-xmls/nuc7i7dnb/sdc_launch_1uos_laag.xml
misc/acrn-config/xmls/config-xmls/tgl-rvp/industry_launch_1uos.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/industry_launch_6uos.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/logical_partition.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i5/sdc_launch_1uos_laag.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/industry_launch_6uos.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/logical_partition.xml
misc/acrn-config/xmls/config-xmls/whl-ipc-i7/sdc_launch_1uos_laag.xml

below commit is cherry pick from release_v2.0:
b845de84 acrn-config: modify the linux like uos type to yocto

acrn-config: cherry pick patch from release_v2.0

---

doc/release_notes/release_notes_2.0.rst

Updates from reviewer comments included

doc: update 2.0 release notes

---

doc/tutorials/agl-vms.rst

doc: update broken link to AGL download

---

hypervisor/arch/x86/guest/ept.c

Wrap a function to do guest ept flush. This function doesn't do real EPT flush.
It just make the EPT flush request and do the real flush just before vcpu vmenter.

hv: ept: wrap a function to do guest ept flush

---

doc/develop.rst
doc/release_notes/release_notes_2.0.rst

doc: more release notes 2.0 edits

---

doc/getting-started/rt_industry_ubuntu.rst

doc: update Ubuntu GSG for ACRN V2.0.

---

doc/conf.py

doc: add 2.0 to doc version selector

---

doc/getting-started/rt_industry_ubuntu.rst

doc: update Ubuntu GSG with 2.0 fixes

---

hypervisor/common/hypercall.c

hv: hypercall: restrict the condition to assign/deassign a pci device to a post-launched VM for safety
For the safety of post-launched VMs, pci devices assignments should occur only when VM is being created (at VM_CREATED STATUS), and pci devices de-assignment should occur only when VM is being created shutdown/reset (at VM_CREATED or VM_PAUSED status)
Tracked-on: #4995
Acked-by: Eddie Done <eddie.dong@intel.com>
Reviewed-by: Li Fei <Fei1.Li@intel.com>
Signed-off-by: Wang Qian <qian1.wang@intel.com>

HV: restrict conditions to assign/deassign pcidev

---

hypervisor/arch/x86/ioapic.c
hypervisor/common/ptdev.c
hypervisor/dm/vioapic.c
hypervisor/dm/vpic.c
hypervisor/include/dm/vioapic.h

replace spinlock_obtain with spinlock_irqsave_obtain for vpic and uart

Cleanup spinlock

---

hypervisor/debug/dbg_cmd.c

Currently, we always assign 0x3F8 as port base io address for
emualted COM1 of SOS.
But in some board, it use serial port which has other base io
address for debugging purpose. And this serial port info is also
exposed to SOS by ACPI table.
In this case, SOS could access the debugging serial port because
it could see the port from ACPI table and conflict with ACRN.
To mitigate this issue, we could let emulated COM1 of SOS to use
native debugging serial port base io port and irq info.
Tracked-On: #4998

debug: BOARD_ENABLE: update the debug serial port info of SOS

---

hypervisor/debug/uart16550.c

replace spinlock_obtain/spinlock_release with spinlock_irqsave_obtain
and spinlock_irqrestore_release to avoid dead lock for uart module.
this uart lock may be accessed in ISR context like this path:
dispatch_interrupt->pr_err/pr_xxx or printf
->console_write->uart16550_puts

hv:use spinlock_irqsave_obtain api for uart

---

doc/tutorials/using_windows_as_uos.rst

doc:update WaaG GSG based on Ubuntu.

---

doc/tutorials/using_windows_as_uos.rst

doc: tweak link in waag tutorial

---

misc/acrn-config/library/hypervisor_license
misc/acrn-config/library/scenario_cfg_lib.py
misc/acrn-config/target/board_parser.py

- update the LICENSE year in config tool
- remove unnecessary check for pci.ids
- improvement sanity check for vuart1 target id settings
Tracked-On: #4989

acrn-config: improvement sanity check for vuart1 target id settings

---

misc/acrn-config/board_config/board_c.py
misc/acrn-config/board_config/misc_cfg_h.py
misc/acrn-config/config_app/static/main.js
misc/acrn-config/config_app/templates/scenario.html
misc/acrn-config/config_app/views.py
misc/acrn-config/library/board_cfg_lib.py
misc/acrn-config/library/hv_cfg_lib.py
misc/acrn-config/library/scenario_cfg_lib.py
misc/acrn-config/scenario_config/scenario_cfg_gen.py
misc/acrn-config/xmls/board-xmls/ehl-crb-b.xml
misc/acrn-config/xmls/config-xmls/ehl-crb-b/industry.xml
misc/acrn-config/xmls/config-xmls/generic/hybrid.xml
misc/acrn-config/xmls/config-xmls/generic/industry.xml
misc/acrn-config/xmls/config-xmls/generic/logical_partition.xml
misc/acrn-config/xmls/config-xmls/generic/sdc.xml
misc/acrn-config/xmls/config-xmls/template/HV.xml

- update EHL CRB configs
- add MBA delay support in acrn config app
- refine sanity check for RDT/MBA
Tracked-On: #4943
Reviewed-by: Vijay Dhanraj <vijay.dhanraj@intel.com>

acrn-config: add MBA delay support in acrn config app

---

misc/acrn-config/hv_config/board_defconfig.py
misc/acrn-config/xmls/config-xmls/tgl-rvp/industry.xml

Add more VMs in xml.
Enable vuart0 for VM1.

acrn-config: add more info in TGL industry.xml

---

devicemodel/hw/pci/virtio/virtio_net.c

This patch does the following,
1. Fix an explicit interface name check for tapX preventing
any other interface name like kata_tap to be setup.
2. Add support for macvtap interface.
3. Identify macvtap vs tap interface and
if it is macvtap, identify character device (/dev/tapXX)
to be used.
Tracked-On: #4945

DM: Add macvtap support to virtio-net

---

misc/acrn-config/xmls/board-xmls/ehl-crb-b.xml

add tsn devices and the NVME device in the board xml
Tracked-On: #4831

acrn-config: update board xml for ehl-crb-b

---

doc/develop.rst
misc/packaging/50-acrn.netdev
misc/packaging/50-acrn.network
misc/packaging/50-eth.network
misc/packaging/50-tap0.netdev
misc/packaging/README.rst
misc/packaging/acrn-hypervisor.postinst
misc/packaging/acrn-kernel.postinst
misc/packaging/compile_iasl.py
misc/packaging/deb.json
misc/packaging/install_uSoS.py
misc/packaging/release.json

Tracked-On: #5022
Signed-off-by: zhanqi <sherry.qi.zhang@intel.com>

create acrn hypervisor/kernel deb

---

devicemodel/hw/pci/passthrough.c

Some passthrough devices have no reset mechanisms which cause the device stay
in unknown status during boot/reboot flow. And such unknown status cause
unexpected behaviors in the guest. Except the ordinary reset mechanisms
like FLR, we can utilize enter/exit D3cold as the reset that D3cold will
power gate the entire hardware. But the D3cold is implemented as ACPI
method which has no user interface in the SOS side. But the D3cold is
implemented as ACPI method which has no user interface in the SOS side.
But base on our experience, some devices can utilize D3hot instead of
D3cold. But it is not useful for all PCI devices as the power status
of D3hot is implementation defined.
Provide one new API to program PowerState(D0/D1/D2/D3hot) in PMCSR
register.
Add "d3hot_reset" sub-parameter for …

DM: PT: Add "d3hot_reset" sub-parameter for passthrough device

---

hypervisor/dm/vpci/vhostbridge.c

HV: inject physical PCIEXBAR into vhostbridge to better emulate vhostbridge, and refined init_vhostbridge with dword-alignment
Modified the commit message according to the comments of @dongyaozu

HV: inject physical PCIEXBAR into vhostbridge to better emulate vhostbridge

---

devicemodel/hw/pci/xhci.c

Add Null pointer check in reset and stop endpoint command handle
function to avoid Null pointer exception. Fllow xHCI spec 4.6.8 and
4.6.9, for stop and reset endpoint command, when the slot state is
Disabled the error code should be Slot Not Enabled Error, when the
slot have been enabled by an Enable Slot Command the error code should
be Context State Error.
Tracked-On: #5066

DM: xHCI: Implement reset/stop endpiont error handler

---

doc/developer-guides/hld/hv-rdt.rst
doc/getting-started/building-from-source.rst
doc/tutorials/rdt_configuration.rst

Given the recent changes in the way ACRN configures RDT features,
this patch updates the documentation as well to provide clear
guidelines to the user.
Tracked-On: #5063

doc: update documentation for configuring ACRN RDT features

---

doc/developer-guides/hld/virtio-net.rst

doc: update virtio-net documentation with macvtap support.

---

doc/scripts/filter-known-issues.py
doc/scripts/genrest.py

doc: add copyright/license header to doc scripts

---

misc/vm_configs/scenarios/logical_partition/vm_configurations.c
misc/vm_configs/xmls/config-xmls/apl-mrb/logical_partition.xml
misc/vm_configs/xmls/config-xmls/apl-up2-n3350/logical_partition.xml
misc/vm_configs/xmls/config-xmls/apl-up2/logical_partition.xml
misc/vm_configs/xmls/config-xmls/ehl-crb-b/logical_partition.xml
misc/vm_configs/xmls/config-xmls/generic/logical_partition.xml
misc/vm_configs/xmls/config-xmls/nuc6cayh/logical_partition.xml
misc/vm_configs/xmls/config-xmls/nuc7i7dnb/logical_partition.xml
misc/vm_configs/xmls/config-xmls/tgl-rvp/logical_partition.xml
misc/vm_configs/xmls/config-xmls/whl-ipc-i5/logical_partition.xml
misc/vm_configs/xmls/config-xmls/whl-ipc-i7/logical_partition.xml

- set guest flag value for logical partition
- remove RT guest flag configuration
Tracked-On: #5119

acrn-config/HV: Remove rt guest flag from logical partition xmls

---

doc/tutorials/using_hybrid_mode_on_nuc.rst

Doc: Getting Started Guide Update for hybrid mode

---

hypervisor/common/schedule.c

When wake_thread is called right after sleep_thread on the same vcpu,
but be_blocking is still true, which means the block progress is not
finished, then the thread status would become BLOCKED forever.
To fix the issue, during wake_thread, if be_blocking is true, also go
through the wake flow, the thread is put back to runqueue, and the
status is changed to RUNNABLE
But this is not enough, as when there is only one thread obj in
runqueue, prev would equal to next in scheudle(), so no context switch
happens, the status cannot changed to RUNNABLE. To fix this, also update
the status for case prev == next.
Tracked-On: #5122

[release2_1] [whl] fix stability problem: failed to boot up SOS in cold boot  

---

hypervisor/scripts/makefile/kconfig.mk

The BOARD/SCENARIO envrionment variable should be passed in one shell command;
Tracked-On: #5077

[Release 2.1]Makefile: fix issue on make menuconfig

---

doc/getting-started/building-from-source.rst
doc/tutorials/acrn_configuration_tool.rst

After vm configurations moved to acrn-hypervisor/misc/vm_configs,
some documents need to be updated.

doc: update vm configuration related path

---

doc/tutorials/using_partition_mode_on_nuc.rst

Doc:Update Logical Partition Getting Started Guide

---

doc/tutorials/using_grub.rst

Doc: Update Using GRUB to boot ACRN

---

doc/introduction/index.rst
doc/tutorials/docbuild.rst

doc: fix more references to hypervisor folders

---

doc/release_notes/release_notes_2.1.rst

doc: draft v2.1 release notes

---

doc/tutorials/pre-launched-rt.rst

The Release_2.1 use multiboot2, so update the example

Doc: update user guide for Pre-Launched RT mode

---

doc/developer-guides/hld/hv-console.rst
doc/developer-guides/hld/ivshmem-hld.rst
doc/tutorials/pre-launched-rt.rst
doc/tutorials/using_hybrid_mode_on_nuc.rst
doc/tutorials/using_partition_mode_on_nuc.rst
doc/user-guides/acrn-shell.rst

doc: use kbd consistently and fix misspellings

---

doc/release_notes/release_notes_2.1.rst

Add fixed issues and known issues.

Doc:release_notes_2.1 update

---

doc/getting-started/building-from-source.rst

build with XML file, "TARGET_DIR=xxx" does not work
Signed-off-by: guoqingxz <guoqingx.q.zhang@intel.com>

doc: add known issue:5157 for building-from-source.rst

---

doc/asa.rst

Add notes for fixed security vulnerabilities for v2.1 release.

doc: update security advisory for v2.1 release

---

doc/release_notes/release_notes_2.1.rst

doc: update release notes about LAPIC timer in OVMF

---

doc/user-guides/acrn-dm-parameters.rst

Add guild how to add ACPI device and MMIO device passthrough support through
the cmdline.

doc: update document for "--acpidev_pt" and "--mmiodev_pt" features

---

hypervisor/common/schedule.c

2abbb99f6ac5 ("hv: make thread status more accurate") introduced a
transition stage, marked as var be_blocking, between RUNNING->BLOCKED
of thread status. wake_thread() does not work in this transition stage
because it only checks thread->status.
Need to check thread->be_blocking as well in wake_thread(). When
wake_thread() happens in the transition stage, the previous sleep
operation rolled back.
Tracked-On: #5190
Fixes: 2abbb99f6ac5 ("hv: make thread status more accurate")

hv: Fix thread status mess if wake_thread() happens in transition stage

---

doc/developer-guides/GVT-g-porting.rst
doc/developer-guides/hld/hld-devicemodel.rst
doc/developer-guides/hld/hld-emulated-devices.rst
doc/developer-guides/hld/hv-cpu-virt.rst
doc/developer-guides/hld/hv-ioc-virt.rst
doc/developer-guides/hld/hv-vm-management.rst
doc/developer-guides/trusty.rst
doc/getting-started/building-from-source.rst
doc/try.rst
doc/tutorials/agl-vms.rst
doc/tutorials/building_uos_from_clearlinux.rst
doc/tutorials/debug.rst
doc/tutorials/kbl-nuc-sdc.rst
doc/tutorials/open_vswitch.rst
doc/tutorials/running_deb_as_serv_vm.rst
doc/tutorials/using_grub.rst
doc/tutorials/using_hybrid_mode_on_nuc.rst
doc/tutorials/using_partition_mode_on_nuc.rst
doc/tutorials/using_sbl_on_up2.rst
doc/tutorials/using_ubuntu_as_sos.rst
doc/tutorials/using_vxworks_as_uos.rst
doc/tutorials/using_windows_as_uos.rst
doc/tutorials/using_zephyr_as_uos.rst
doc/tutorials/waag-secure-boot.rst
doc/user-guides/acrn-dm-parameters.rst
doc/user-guides/acrn-shell.rst

doc: spelling and grammar fixes

---

misc/vm_configs/xmls/config-xmls/tgl-rvp/hybrid_rt.xml

Add ./misc/acrn-config/xmls/config-xmls/tgl-rvp/hybrid_rt.xml
Tracked-On: #5185

acrn-config: add hybrid_rt scenario xml config for TGL

---

misc/acrn-config/target/misc.py

Get the max number with integer list to instead string 'number'.
Tracked-On: #5199

acrn-config: get the max number with integer list

---

doc/tutorials/docbuild.rst

doc: update docbuild instructions for 2.2 release

---

doc/faq.rst

Remove obsolete information and Clear Linux/UEFI references.

doc: update FAQ

---

hypervisor/arch/x86/Kconfig

Enhance the help text that accompanies the CONFIG_SCENARIO symbol in Kconfig
Tracked-On: #5203

hv: enhance help text for the scenario option in Kconfig

---

misc/packaging/acrn-hypervisor.postinst
misc/packaging/acrn-kernel.postinst

Tracked-On: #5022
Signed-off-by: zhanqi <sherry.qi.zhang@intel.com>
misc/packaging: remove efi support

misc/packaging: remove efi support

---

hypervisor/common/hv_main.c
hypervisor/common/schedule.c
hypervisor/debug/dbg_cmd.c
hypervisor/debug/shell.c
hypervisor/debug/shell_priv.h
hypervisor/include/arch/x86/guest/vcpu.h
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/arch/x86/per_cpu.h
hypervisor/include/debug/shell.h
hypervisor/include/public/acrn_common.h

to sample vmexit data in HV.
also add a flag to control it.

to sample vmexit data in HV for release_2.0

---

misc/vm_configs/xmls/config-xmls/tgl-rvp/hybrid_rt.xml

add IVSHMEM config in hybrid_rt scenario on tgl-rvp board.

acrn-config: add IVSHMEM config in hybrid_rt of tgl-rvp

---

misc/vm_configs/xmls/config-xmls/ehl-crb-b/hybrid_rt.xml

add hybrid_rt scenario for the ElkhartLake CRB board so that user can
launch Yocto Linux as pre-launched VM.
Tracked-On: #5238
Signed-off-by: "Nishioka, Toshiki" <toshiki.nishioka@intel.com>

acrn-config: add hybrid_rt scenario xml config for ehl-crb-b

---

misc/vm_configs/sample_launch_scripts/nuc/launch_xenomai.sh

There a bug in substring detection, fix it.

script: fix a minor bug in launch_xenomai.sh

---

hypervisor/dm/vpci/vpci.c

Kernel driver and ACPI ASL may access a platform hidden device
thru PIO, e.g., Intel ICH LPC driver. If the access is originated
in SOS or Pre-launched OS, vpci_pio_cfgdata_write/read should support
it.
This commit also reworks vpci_write_cfg/vpci_read_cfg to do the access
check and elimiates the access from post-launched VM (that should be
handled by DM).
Tracked-On: #5257
Signed-off-by: Stanley Chang <stanley.chang@intel.com>
Reviewed-by: Li Fei <fei1.li@intel.com>

hv: support PIO access to platform hidden devices

---

doc/tutorials/launch_uos.sh
misc/acrn-config/launch_config/pt.py
misc/vm_configs/sample_launch_scripts/apl-mrb/launch_uos.sh
misc/vm_configs/sample_launch_scripts/apl-up2/launch_uos.sh

minor_ver should be le 2 when major_ver == 2.
Tracked-On: #5276

acrn-config: fix csme passthrough issue for launch setting

---

hypervisor/debug/uart16550.c

On a PCI type HV uart, the bdf value is in a union together with
mmio_base_vaddr, then the value would be overridden by mmio_base_addr
in uart16550_init(), result in is_pci_dbg_uart() returns a wrong value
and then uart hang.
Tracked-On: #5288

HV: fix uart hang issue caused by bdf overridden

---

misc/vm_configs/xmls/config-xmls/ehl-crb-b/logical_partition.xml
misc/vm_configs/xmls/config-xmls/generic/logical_partition.xml

Delete uuid lines in config xmls
Tracked-On: #4641

acrn-config: remove uuid in config

---

devicemodel/hw/pci/ivshmem.c

Change shared memory name prefix from sos to dm
Change shared memory size unit from byte to megabyte

dm: refine ivshmem usage interface

---

doc/tutorials/using_hybrid_mode_on_nuc.rst
doc/tutorials/using_partition_mode_on_nuc.rst

Bring change made to release_2.2 branch back to the main (master)
branch.

doc: update pre-launched VMs with offline ACPI

---

doc/tutorials/gpu-passthru.rst
doc/tutorials/using_partition_mode_on_nuc.rst

Removed additional references to Clear Linux

doc: continue CL cleanup

---

doc/introduction/index.rst

doc: edit intro grammar

---

hypervisor/dm/vpci/vmsix_on_msi.c

No GPA is specified for the vmsi BAR in the case of vmsi over
msi. This patch hard coded the GPA as 0x80000000 which is the
base addr of 32bit PCI hole in the predefined e820 table of
pre-launched VM.

hv: vmsi: add default BAR GPA for vmsi over msi

---

doc/tutorials/acrn_configuration_tool.rst

Add configration items: IVSHMEM, mmio_resources, pt_intx in
configuration tool documentation

doc:  add IVSHMEM, mmio_resources, pt_intx in configuration tool

---

doc/tutorials/acrn_configuration_tool.rst

Slight wording tweak about the IVSHMEM_REGION description

doc: update IVSHMEM config detail

---

devicemodel/hw/pci/virtio/virtio.c

We can only call these callbacks when they are not NULL.
Tracked-On: #5342

virtio: add virtio callbacks check

---

doc/getting-started/rt_industry_ubuntu.rst
doc/release_notes/release_notes_2.2.rst

Update release notes and fix merge conflict in PR #5365

doc: update rt_industry GSG and v2.2 release notes

---

doc/conf.py

doc: add v2.2 to doc menu choices

---

doc/getting-started/rt_industry_ubuntu.rst

Doc: release_notes_2.2 update

---

doc/release_notes/release_notes_2.2.rst

doc: tweak 2.2 release notes

---

doc/getting-started/rt_industry_ubuntu.rst
doc/release_notes/release_notes_2.2.rst

doc: doc fixes post 2.2 release

---

doc/developer-guides/hld/hv-dev-passthrough.rst
doc/introduction/index.rst
doc/tutorials/acrn_configuration_tool.rst
doc/tutorials/acrn_on_qemu.rst
doc/tutorials/cpu_sharing.rst
doc/tutorials/debug.rst
doc/tutorials/docbuild.rst
doc/tutorials/enable_ivshmem.rst
doc/tutorials/enable_s5.rst
doc/tutorials/gpu-passthru.rst
doc/tutorials/rdt_configuration.rst
doc/tutorials/realtime_performance_tuning.rst
doc/tutorials/rtvm_performance_tips.rst
doc/tutorials/rtvm_workload_design_guideline.rst
doc/tutorials/run_kata_containers.rst
doc/tutorials/running_deb_as_serv_vm.rst
doc/tutorials/running_deb_as_user_vm.rst
doc/tutorials/running_ubun_as_user_vm.rst
doc/tutorials/setup_openstack_libvirt.rst
doc/tutorials/sgx_virtualization.rst
doc/tutorials/sriov_virtualization.rst
doc/tutorials/using_grub.rst
doc/tutorials/using_partition_mode_on_nuc.rst
doc/tutorials/using_vxworks_as_uos.rst
doc/tutorials/using_windows_as_uos.rst
doc/tutorials/using_xenomai_as_uos.rst
doc/tutorials/using_yp.rst
doc/tutorials/using_zephyr_as_uos.rst
doc/tutorials/vuart_configuration.rst
doc/tutorials/waag-secure-boot.rst

doc: spelling and grammar improvements

---

doc/developer-guides/GVT-g-porting.rst
doc/developer-guides/VBSK-analysis.rst
doc/developer-guides/asm_coding_guidelines.rst
doc/developer-guides/c_coding_guidelines.rst
doc/developer-guides/contribute_guidelines.rst
doc/developer-guides/doc_guidelines.rst
doc/developer-guides/graphviz.rst
doc/developer-guides/hld/hld-devicemodel.rst
doc/developer-guides/hld/hld-overview.rst
doc/developer-guides/hld/hld-power-management.rst
doc/developer-guides/hld/hld-security.rst
doc/developer-guides/hld/hld-trace-log.rst
doc/developer-guides/hld/hld-virtio-devices.rst
doc/developer-guides/hld/index.rst
doc/developer-guides/l1tf.rst
doc/developer-guides/modularity.rst
doc/developer-guides/sw_design_guidelines.rst
doc/developer-guides/trusty.rst

doc: more spelling and grammar fixes

---

misc/vm_configs/xmls/config-xmls/ehl-crb-b/logical_partition.xml

main changes:
1. The VM1 is updated to RT Linux;
2. Enable IVSHMEM;
Tracked-On: #4798

acrn-config: update logical_partition for ehl-crb-b

---

doc/acrn.doxyfile

Update some configuration settings that will be obsolete in the new
(1.8.17) doxygen release.

doc: update doxygen configuration

---

misc/vm_configs/xmls/config-xmls/ehl-crb-b/hybrid_rt.xml
misc/vm_configs/xmls/config-xmls/ehl-crb-b/hybrid_rt_fusa.xml
misc/vm_configs/xmls/config-xmls/ehl-crb-b/industry.xml

changes:
1. Change rootfs from partition2 to partition3 for VM0 and SOS VM;
2. Change VM0 mem size to 1GB;
Tracked-On: #5238

acrn-config: minor change hybrid_rt scenario for ehl

---

misc/acrn-config/config_app/static/main.js
misc/acrn-config/config_app/templates/launch.html
misc/acrn-config/config_app/templates/scenario.html
misc/acrn-config/config_app/views.py
misc/acrn-config/launch_config/launch_cfg_gen.py
misc/acrn-config/library/launch_cfg_lib.py
misc/acrn-config/library/scenario_cfg_lib.py
misc/acrn-config/scenario_config/scenario_cfg_gen.py

Add PCI vuart config for scenario setting and launche setting of config
tool UI. The original vuart setting is changed to legacy vuart setting.
Shuang Zheng (3):
acrn-config: add PCI VUART config in scenario config UI
acrn-config: add PCI VUART config in launch config UI
acrn-config: add mutually exclusive logic for legacy vuart and PCI
vuart on config UI

acrn-config: add PCI vuart config in config tool UI

---

hypervisor/arch/x86/configs/pci_dev.c
hypervisor/include/arch/x86/vm_config.h
misc/acrn-config/board_config/misc_cfg_h.py
misc/acrn-config/board_config/vbar_base_h.py
misc/acrn-config/library/common.py
misc/acrn-config/library/scenario_cfg_lib.py
misc/acrn-config/scenario_config/pci_dev_c.py
misc/acrn-config/scenario_config/vm_configurations_c.py
misc/vm_configs/scenarios/hybrid/vm_configurations.c
misc/vm_configs/scenarios/hybrid_rt/vm_configurations.c
misc/vm_configs/scenarios/industry/vm_configurations.c

Config-6523_ivshmem_doorbell
Config-6712_ivshmem_dev_sos
- Enable ivshmeme for SOS VM
- Allocate vbar 1 for pre-launched and SOS VM
Tracked-On: #5426

acrn-config: InverVM communication support

---

doc/tutorials/acrn_configuration_tool.rst
doc/tutorials/docbuild.rst
doc/tutorials/enable_ivshmem.rst
doc/tutorials/rdt_configuration.rst
doc/tutorials/realtime_performance_tuning.rst
doc/tutorials/rtvm_performance_tips.rst
doc/tutorials/running_ubun_as_user_vm.rst
doc/tutorials/setup_openstack_libvirt.rst
doc/tutorials/sgx_virtualization.rst
doc/tutorials/sriov_virtualization.rst

Continuing with additional spelling and grammar fixes missed during
retular reviews.

doc: doc spelling and grammar fixes

---

misc/vm_configs/xmls/config-xmls/tgl-rvp/hybrid_rt.xml

disable psram config
Tracked-On: #5418

acrn-config: disable psram config

---

doc/tutorials/running_deb_as_serv_vm.rst

Update steps from de-privileged boot to direct boot.

Doc: Update Debian as Service Vm

---

doc/getting-started/building-from-source.rst
doc/getting-started/rt_industry_ubuntu.rst
doc/tutorials/using_hybrid_mode_on_nuc.rst
doc/tutorials/using_partition_mode_on_nuc.rst

Feedback suggests we add more top-level navigation to the getting
started guides, so let's include a local TOC as well as using the
"numbered-step" style to top-level steps.

doc: improve GSG navigation

---

devicemodel/hw/platform/usb_pmapper.c

When libusb_control_transfer function return a negative number, because
the function clear_uas_desc's argument is unsigned int this will cause
unsigned integer conversion.
Tracked-On: #5463

ACRN:DM:xHCI Fix the unsigned integer conversion bug

---

doc/developer-guides/hld/ivshmem-hld.rst

With ivshmem doorbell feature enabled, HDL of it shall be updated.

doc: update ivshmem feature HLD

---

hypervisor/arch/x86/guest/vm.c

Always trap for accessing IO port at CONFIG_SERIAL_PIO_BASE(0x3f8).
SOS will trap at IO 0x3f8 access because vuart[0]. When HW platform
has this serial IO port, and HV use it as debug shell, If vuart[0]
is not set, SOS & HV console input/output are mixed up.
So SOS should always trap at CONFIG_SERIAL_PIO_BASE
Tracked-On: #5498

HV: hide CONFIG_SERIAL_PIO_BASE IO port for SOS

---

misc/vm_configs/xmls/config-xmls/cfl-k700-i7/hybrid_rt.xml
misc/vm_configs/xmls/config-xmls/tgl-rvp/hybrid_rt.xml
misc/vm_configs/xmls/config-xmls/whl-ipc-i5/hybrid_rt.xml
misc/vm_configs/xmls/config-xmls/whl-ipc-i7/hybrid_rt.xml

add the right cmd args provided by Ronnie.
Tracked-On: #5501

acrn-config: modify the cmd args in pre-launched rt xml

---

devicemodel/hw/pci/virtio/virtio_mei.c

Prevent memory and information leaks by checking boundaries of
the incoming buffers from the hypervisor.
1. We check that the buffer is sufficent to hold a valid header.
2. We that each hbm message has valid size
vmei_hbm_handler() now returns -EINVAL if the size too small.
3. hdr->length < data_length.
Tracked-On: #5451

dm: mei: vmei_proc_tx check buffer length before accessing the memory

---

devicemodel/hw/pci/virtio/virtio.c

paddr_guest2host can return NULL, but code paths in virtio
are not checking the return value.
_vq_record() initializes iov_base pointer using paddr_guest2host()
but there is nothing in the flow that checks for NULL.
Chane _vq_record to return -1 in case the address translation
has failed.
Tracked-On: #5514

dm: virtio: check for paddr_guest2host return value-v2.3 branch

---

devicemodel/core/pm_vuart.c
devicemodel/hw/pci/ahci.c
devicemodel/hw/pci/xhci.c

Add the NULL pointer check in case there will have security issues.
Tracked-On: #5514

DM: Fix the security issues in the DM.

---

doc/getting-started/rt_industry_ubuntu.rst
doc/tutorials/enable_s5.rst
doc/tutorials/pre-launched-rt.rst
doc/tutorials/running_deb_as_user_vm.rst
doc/tutorials/running_ubun_as_user_vm.rst
doc/tutorials/using_vxworks_as_uos.rst
doc/tutorials/using_zephyr_as_uos.rst
doc/tutorials/vuart_configuration.rst
misc/packaging/README.rst

Some document refer to Clear Linux as Service VM; update them
to Ubuntu Service VM.

Doc: update document to remove CL Service VM dependence

---

misc/acrn-config/board_config/vbar_base_h.py
misc/acrn-config/scenario_config/pci_dev_c.py

1. Discard the method to find unused vbar bases from system ram, find unused mmio windows from 2G to 4G range.
2. Refine the ivshmem devices declaration.
Tracked-On: #5530

acrn-config: refine the ivshmem for pre-launched vm

---

misc/life_mngr/s5_trigger.sh

misc: add the s5_trigger.sh script
Tracked-On: #5411

misc: add the s5_trigger.sh script

---

hypervisor/common/hypercall.c

If we assign the mmio device address and size maliciously, this may crash
the HV, SOS even the UOS. This patch is a hot fix. The formal one needs
the config tool to configure the mmio device which we could pass through
and the HV check the mmio device by it.
Tracked-On: #5555

hv: hypercall: hot fix call assign/deassign mmiodev could crash hv

---

doc/release_notes/release_notes_2.3.rst

doc: add v2.3 release notes draft

---

doc/tutorials/vuart_configuration.rst

update tutorials/vuart_configuration.rst, add pci-vuart guide

Doc: pci-vuart-guide

---

doc/asa.rst

update fixed security issue for 2.3 release.

doc: update 'asa.rst' for 2.3 release

---

doc/tutorials/enable_ivshmem.rst

Add notification (doorbell) usage for ivshmem devices.

doc: update 'enable_ivshmem'

---

doc/.known-issues/doc/dupdecl.conf
doc/asa.rst
doc/nocl.rst
doc/try.rst
doc/tutorials/acrn_configuration_tool.rst
doc/tutorials/running_deb_as_serv_vm.rst

Remove some stray Clear Linux references, document labels, and update
the known issue filter patterns.

doc: doc cleanup for v2.3 release

---

doc/getting-started/building-from-source.rst
doc/getting-started/rt_industry_ubuntu.rst
doc/tutorials/using_partition_mode_on_nuc.rst

Update Getting Started Guide for ACRN Industry Scenario with Ubuntu Service VM

Doc: GSG update for ACRN Industry Scenario with Ubuntu Service VM

---

doc/getting-started/rt_industry_ubuntu.rst
doc/tutorials/setup_openstack_libvirt.rst

update ACRN version, update kernel boot args, and fix the issue in
the steps to set up libvirt.

doc: update the doc to setup openstack with ACRN

---

doc/release_notes/release_notes_2.3.rst

doc: update v2.3 release notes

---

doc/release_notes/release_notes_2.3.rst

Doc: release_notes_2.3 update

---

doc/release_notes/release_notes_2.3.rst

doc: release notes tweaks for v2.3

---

doc/conf.py

doc: update doc version selector for v2.3

---

doc/release_notes/release_notes_2.3.rst

Added a couple of missing documents in the "changed doc" list, and fixed
spelling of passthrough

doc: tweak to 2.3 release notes

---

doc/tutorials/acrn-secure-boot-with-grub.rst

- Format some section title
- Add one more section.

doc: update acrn secureboot enablement

---

doc/getting-started/roscube/roscube-gsg.rst

Small updates to ROScube-I Installation Guide:
* Add newline before `sudo reboot` in User VM section.
* Add `cd ~/acrn/tools/` before downloading script in User VM section.
Signed-off-by: ChenYing Kuo <chenying.kuo@adlinktech.com>

doc: small updates to ROScube-I Installation Guide

---

Makefile

Properly fix formatting for 'cfg.log' file

---

LICENSE

LICENSE file copyright should reflect latest year of contributions
(before this update, it said 2017-2018).
Tracked-On: #5611

doc: update LICENSE copyright years

---

doc/conf.py

doc: tweak to copyright footer

---

doc/tutorials/using_windows_as_uos.rst

Since GVT-g isn't enable for new platform (i.e TGL EHL CFL),
update the doc about using GVT-d GOP to create WaaG image.

Doc: update WaaG image creation with GVT-d GOP

---

doc/tutorials/running_deb_as_user_vm.rst
doc/tutorials/running_ubun_as_user_vm.rst

Pipe info isn't needed for IDV solution; so remove this part in
the document.

Doc: update Debian and Ubuntu as the User VM

---

hypervisor/arch/x86/cpu_caps.c
hypervisor/arch/x86/guest/guest_memory.c
hypervisor/arch/x86/guest/instr_emul.c
hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/guest/virq.c
hypervisor/arch/x86/guest/vmcs.c
hypervisor/include/arch/x86/cpu_caps.h
hypervisor/include/arch/x86/guest/guest_memory.h
hypervisor/include/arch/x86/guest/instr_emul.h
hypervisor/include/arch/x86/guest/vcpu.h
hypervisor/include/arch/x86/irq.h

This patch set adds the emulation for split-lock.
Tracked-On: #5605

Add split-lock emulation

---

hypervisor/arch/x86/guest/assign.c

Now, we use hash table to maintain intx irq mapping by using
the key generated from sid. So once the entry is added,we can
not update source ide any more. Otherwise, we can't locate the
entry with the key generated from new source ide.
For source id change, remove_remapping/add_remapping is used
instead of update source id directly if entry was added already.
Tracked-On: #5640

hv: ptirq: Shouldn't change sid if intx irq mapping was added

---

doc/tutorials/docbuild.rst

New versions of doc build tools are listed, along with tweaks to the
requirements.txt and list of tools installed with apt for building
documentation.

doc: update doc build instructions

---

CODEOWNERS

Update the CODEOWNERS information.

Update the CODEOWNERS information.

---

devicemodel/include/public/vhm_ioctl_defs.h

Refine comment on usage of this structure.

dm: refine comment on 'struct acrn_vm_config'

---

misc/config_tools/config_app/controller.py
misc/config_tools/config_app/requirements
misc/config_tools/config_app/templates/scenario.html
misc/config_tools/config_app/views.py
misc/config_tools/data/generic_board/hybrid.xml
misc/config_tools/data/generic_board/hybrid_rt.xml
misc/config_tools/data/generic_board/industry.xml
misc/config_tools/data/generic_board/logical_partition.xml

render scenario setting UI with xsd schema config, validate scenario setting with xsd validation.
update config app when creating new scenarios according to folder reorg
Tracked-On: #5672
Reviewed-by: Mao, Junjie <junjie.mao@intel.com>

config_tools: scenario setting UI with xsd schema config

---

misc/config_tools/board_config/vbar_base_h.py

Assign extra vbar for vmsix devive for ehl-crb-b only.
Tracked-On: #5693

config-tools: check vmsix enablement for ehl-crb-b

---

misc/config_tools/scenario_config/scenario_cfg_gen.py

add validate_scenario_schema to validate_scenario_setting and update the
excption handling.
Tracked-On: #5672

config-tools: add validate_scenario_schema

---

doc/static/downloads/build_acrn_ovmf.sh
doc/tutorials/gpu-passthru.rst

Add a script to build acrn ovmf with GOP driver. The build is
using a ubuntu 16.04 based docker image.

doc: add script to build acrn ovmf with GOP driver

---

misc/config_tools/schema/types.xsd

doc: test for simple xsd edit

---

misc/config_tools/data/ehl-crb-b/fusa_partition.xml

update fusa_partition scenario following requirements.
Tracked-On: #5665

config_tools: update fusa_partition scenario

---

doc/asa.rst
doc/developer-guides/hld/hld-security.rst
doc/release_notes/release_notes_0.1.rst
doc/release_notes/release_notes_0.2.rst
doc/release_notes/release_notes_0.3.rst
doc/release_notes/release_notes_0.4.rst
doc/release_notes/release_notes_0.5.rst
doc/release_notes/release_notes_0.6.rst
doc/release_notes/release_notes_0.7.rst
doc/release_notes/release_notes_0.8.rst
doc/release_notes/release_notes_1.0.1.rst
doc/release_notes/release_notes_1.0.2.rst
doc/release_notes/release_notes_1.0.rst
doc/release_notes/release_notes_1.1.rst
doc/release_notes/release_notes_1.2.rst
doc/release_notes/release_notes_1.3.rst
doc/release_notes/release_notes_1.4.rst
doc/release_notes/release_notes_1.5.rst
doc/release_notes/release_notes_1.6.1.rst
doc/release_notes/release_notes_1.6.rst
doc/release_notes/release_notes_2.0.rst
doc/release_notes/release_notes_2.1.rst
doc/release_notes/release_notes_2.2.rst
doc/release_notes/release_notes_2.3.rst

After grand update of all titles to use title-case, we found a few that
needed a manual tweak.

doc: update a few mis-handled titles

---

doc/faq.rst

Update our FAQ section by deleting outdated and obsolete information.

doc: update our FAQ section

---

doc/api/GVT-g_api.rst
doc/developer-guides/hld/hld-devicemodel.rst
doc/developer-guides/hld/hld-trace-log.rst
doc/developer-guides/hld/hld-virtio-devices.rst
doc/developer-guides/hld/hv-partitionmode.rst
doc/developer-guides/hld/ivshmem-hld.rst
doc/developer-guides/hld/virtio-blk.rst
doc/developer-guides/hld/virtio-gpio.rst
doc/developer-guides/hld/virtio-i2c.rst
doc/tutorials/acrn-secure-boot-with-grub.rst
doc/tutorials/enable_ivshmem.rst
doc/tutorials/realtime_performance_tuning.rst
doc/tutorials/trustyACRN.rst
doc/tutorials/using_windows_as_uos.rst
doc/tutorials/using_yp.rst
doc/user-guides/acrn-shell.rst
doc/user-guides/kernel-parameters.rst

After grand update of all titles to use title-case, we found some more
that needed a manual tweak.

doc: update another few mis-handled titles

---

hypervisor/arch/x86/guest/vm.c
hypervisor/include/arch/x86/rtct.h
misc/config_tools/board_config/misc_cfg_h.py

Port below PR from mainline to v2.4 release
https://github.com/projectacrn/acrn-hypervisor/pull/5754

[release_v2.4] Unmap Software SRAM region of PreRTVM from Service VM

---

misc/config_tools/data/ehl-crb-b/ehl-crb-b.xml
misc/config_tools/data/ehl-crb-b/fusa_partition.xml

update sbl version of ehl-crb-b.xml.
Tracked-On: #5778

config_tools: update sbl version of ehl-crb-b.xml

---

hypervisor/arch/x86/guest/ept.c

Refine the logic how to skip the pSRAM region when flushing cache.
Tracked-On: #5330

refine ept_flush_leaf_page

---

doc/user-guides/acrn-dm-parameters.rst

Signed-off-by: Benjamin Fitch <benjamin.fitch@intel.com>

doc: reformat acrn-dm-parameters

---

doc/release_notes/release_notes_2.4.rst

doc: start v2.4 release notes draft

---

doc/faq.rst
doc/tutorials/acrn-config-details.txt
hypervisor/Makefile
hypervisor/arch/x86/Kconfig
hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/cpu_caps.c
hypervisor/arch/x86/guest/ept.c
hypervisor/arch/x86/guest/trusty.c
hypervisor/arch/x86/guest/vm.c
hypervisor/arch/x86/guest/vmx_io.c
hypervisor/arch/x86/mmu.c
hypervisor/arch/x86/page.c
hypervisor/arch/x86/pagetable.c
hypervisor/common/hypercall.c
hypervisor/dm/vpci/vdev.c
hypervisor/include/arch/x86/guest/ept.h
hypervisor/include/arch/x86/guest/vm.h
hypervisor/include/arch/x86/page.h
misc/config_tools/board_config/vbar_base_h.py

port high MMIO support from master to release_2.4
Tracked-On: #5788

Release 2.4: port high MMIO support

---

doc/tutorials/acrn_configuration_tool.rst
misc/config_tools/schema/config.xsd

update the path for config editor; update description of vm.name.
Tracked-On: #5644

doc: update path for config editor and desc for some config items

---

hypervisor/arch/x86/cpu_caps.c
hypervisor/arch/x86/guest/vlapic.c

hv: WA: Disable advanced feature of apicv to WA ACRN-6886

---

doc/getting-started/building-from-source.rst
doc/tutorials/using_hybrid_mode_on_nuc.rst
doc/tutorials/using_partition_mode_on_nuc.rst

using_hybrid_mode_on_nuc.rst
using_partition_mode_on_nuc.rst
Signed-off-by: guoqingxz <guoqingx.q.zhang@intel.com>

doc: update doc for hybrid and logical_partition mode:

---

misc/config_tools/data/sample_launch_scripts/nuc/launch_hard_rt_vm.sh
misc/config_tools/data/sample_launch_scripts/nuc/launch_uos.sh

delete pm para in sample launch scripts and update the comments
Tracked-On: #5736
Signed-off-by: li shuang <shuangx.li@intel.com>

config-tools: modify sample launch scripts

---

doc/tutorials/using_windows_as_uos.rst

Part of unsupported parameters for the latest ACRN-DM code are removed.

Doc: Launch Windows as the Guest VM

---

doc/release_notes/release_notes_2.4.rst

doc: additional release notes edits

---

doc/release_notes/release_notes_2.4.rst

Adding fixed issue and known issue information in release note.

Doc: update v2.4 release notes

---

doc/tutorials/using_windows_as_uos.rst

To keep align with script, change Windows10.iso and winvirtio.iso image relative paths to full paths.

Doc: Update Launch Windows as the Guest VM

---

doc/release_notes/release_notes_2.4.rst

Add additional summary material for v2.4 updates.

doc: update release notes

---

doc/conf.py

doc: add 2.4 to doc version menu

---

misc/config_tools/scenario_config/pci_dev_c.py

Refine the logic of finding unused bdf for SOS emulated devices. First,
find the unused bdf based on if the "dev" is unused. Increase the "func"
for the next same type of emulated devices if the last assigned bdf
exists. Otherwise, start over looking for unused bdf based on "dev"
repeatedly.
Tracked-On: #5869

config-tools: find the unused bdf based on first unused "dev"

---

hypervisor/arch/x86/cpu.c

1.  use MFENCE to ensure trampoline code was updated
2. fix an isuue about SMP sync
Tracked-On: #5929

hv: fix some minor bug part2

---

misc/config_tools/data/adl-rvp/adl-rvp.xml
misc/config_tools/data/adl-rvp/industry.xml

Add board xml and industry config xml for ADL-P.
Tracked-On: #5941
Signed-off-by: Jiang, Yanting <yanting.jiang@intel.com>

acrn-config: add adl-rvp xml

---

doc/.known-issues/doc/pdf.conf

Update known-issues pattern for PDF processing to also work with updated
xelatex tools from Ubuntu 20.04

doc: tweak known-issues for PDF processing

---

doc/tutorials/acrn_configuration_tool.rst

Fix incorrect code-block notation and code-block language

doc: fix malformed code block in acrn config docs

---

hypervisor/debug/uart16550.c

This patch fixes the 'uart=bdf@XXX' mechanism for the PCI serial
port devices which bar0 is not MMIO.
Tracked-On: #5968
Signed-off-by: Li Fei <fei1.li@intel.com>

hv: enable uart=bdf@ for PCI serial ports which bar0 is not MMIO

---

doc/tutorials/using_windows_as_uos.rst

doc: fix missing codeblock directive

---

doc/developer-guides/GVT-g-porting.rst
doc/developer-guides/VBSK-analysis.rst
doc/developer-guides/asm_coding_guidelines.rst
doc/developer-guides/c_coding_guidelines.rst
doc/developer-guides/coding_guidelines.rst
doc/developer-guides/contribute_guidelines.rst
doc/developer-guides/doc_guidelines.rst
doc/developer-guides/graphviz.rst
doc/developer-guides/l1tf.rst
doc/developer-guides/modularity.rst
doc/developer-guides/sw_design_guidelines.rst
doc/developer-guides/trusty.rst

Performed copy editing in the topics directly within the "developer-guides" folder. Will edit the "hld" topics in a separate pull request.
Signed-off-by: Benjamin Fitch <benjamin.fitch@intel.com>

doc: copy edits in the developer reference

---

hypervisor/arch/x86/guest/vcpuid.c
hypervisor/arch/x86/guest/vmsr.c
hypervisor/arch/x86/rdt.c
hypervisor/arch/x86/timer.c
hypervisor/debug/profiling.c
hypervisor/debug/shell.c
hypervisor/dm/vpci/vhostbridge.c
misc/config_tools/schema/types.xsd

They not directly related to vCAT, but are all  found during vCAT dev, so merge them first and treated them as part of vCAT.
No functionality changes, all are bug fix or coding style fix reported by checkpatch.pl
Tracked-On: #5917
Acked-by: Eddie Dong eddie.dong@intel.com

Fix bugs/coding style issues found during vCAT development

---

doc/tutorials/using_serial_port.rst

Edited the "Enable Serial Port on NUC" topic.
Signed-off-by: Benjamin Fitch <benjamin.fitch@intel.com>

doc: editing in using_serial_port.rst

---

doc/developer-guides/hld/ahci-hld.rst
doc/developer-guides/hld/atkbdc-virt-hld.rst
doc/developer-guides/hld/hld-APL_GVT-g.rst

Copy editing in several HLD topics. (More to follow in subsequent PRs.)
Signed-off-by: Benjamin Fitch <benjamin.fitch@intel.com>

doc: copy editing in the hld topics

---

doc/tutorials/running_deb_as_serv_vm.rst

doc: fix indenting issues in tutorial

---

misc/config_tools/xforms/vm_configurations.c.xsl

Update the ramdisk config logic.
Tracked-On: #6038

Config_tools: Update ramdisk logic

---

doc/developer-guides/hld/hld-devicemodel.rst
doc/tutorials/enable_s5.rst
doc/user-guides/acrn-dm-parameters.rst

doc: add documentation for allow_trigger_s5 in pm_notify_channel

---

misc/config_tools/data/adl-rvp/adl-rvp.xml
misc/config_tools/data/cfl-k700-i7/cfl-k700-i7.xml
misc/config_tools/data/nuc11tnbi5/nuc11tnbi5.xml
misc/config_tools/data/nuc7i7dnb/nuc7i7dnb.xml
misc/config_tools/data/whl-ipc-i5/whl-ipc-i5.xml
misc/config_tools/data/whl-ipc-i7/whl-ipc-i7.xml

Add nuc11tnbi5.xml;
Update adl-rvp.xml, cfl-k700-i7.xml, ehl-crb-b.xml, nuc7i7dnb.xml, tgl-rvp.xml and whl-ipc-i7.xml.
Tracked-On: #5922

Config_tools: Update board xml

---

misc/config_tools/data/adl-s-crb/adl-s-crb.xml
misc/config_tools/data/adl-s-crb/industry.xml

add adl-s-crb board xml and industry scenario for adl-s-crb.
Tracked-On: #5929

config_tools: add adl-s-crb board and industry scenario

---

devicemodel/hw/pci/virtio/virtio_net.c

Add a check on this place to avoid NULL access issue.
Tracked-On: #6100

dm: NULL check of vq->used

---

misc/config_tools/board_inspector/legacy/parser_lib.py

For illegal characters, replace original characters with escaped characters in board.xml.
Tracked-On: #6113

config_tools: replace illegal character with escaped character

---

hypervisor/Makefile
hypervisor/arch/x86/guest/nested.c
hypervisor/arch/x86/guest/vcpu.c
hypervisor/arch/x86/guest/vept.c
hypervisor/arch/x86/guest/vmexit.c
hypervisor/include/arch/x86/asm/guest/nested.h
hypervisor/include/arch/x86/asm/guest/vept.h

This PR is exactly same with https://github.com/projectacrn/acrn-hypervisor/pull/6118, but targeting to release 2.5

hv: nested virtualization part 4 - release 2.5

---

misc/config_tools/data/tgl-rvp/hybrid.xml
misc/config_tools/data/tgl-rvp/hybrid_rt.xml
misc/config_tools/data/tgl-rvp/industry.xml
misc/config_tools/data/tgl-rvp/logical_partition.xml
misc/config_tools/data/tgl-rvp/sdc.xml

Add CLOS_MASK elements into tgl scenario files as default configuration.
Tracked-On: #6120

Config_tools: Update tgl-rvp scenario xml

---

misc/config_tools/config_app/views.py

This reverts commit 033f458d85d8c6a9c31571ff06301b7df6083c27.

Revert "config_tools: save board xml when loading from config tool UI"

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/guest/nested.c
hypervisor/arch/x86/guest/vept.c
hypervisor/include/arch/x86/asm/guest/vept.h
hypervisor/include/arch/x86/asm/pgtable.h

This patchset includes vEPT support.

vEPT for v2.5

---

hypervisor/arch/x86/cpu.c
hypervisor/arch/x86/guest/nested.c
hypervisor/arch/x86/guest/vept.c
hypervisor/include/arch/x86/asm/guest/vept.h
hypervisor/include/arch/x86/asm/pgtable.h

THis patchset includes vEPT support.

vEPT for mainline

---

hypervisor/arch/x86/guest/vlapic.c

hv: WA ACRN-6886: Interrupt the target CPU and let it do PI with VMENTRY

---

hypervisor/arch/x86/guest/splitlock.c
hypervisor/arch/x86/guest/vm.c
hypervisor/include/arch/x86/asm/guest/vm.h

Only for release 2.5 test purpose.
[External_System_ID] ACRN-6984
[External_System_ID] ACRN-6709

split lock fix

---

doc/developer-guides/doc_guidelines.rst
doc/tutorials/docbuild.rst

Explain how ACRN configuration options are documented and generated
Tracked-On: #5911

doc: update doc guidelines for ACRN config options

---

misc/config_tools/static_allocators/gpa.py

A vmsix supported passthrough device expects the first unused bar region
for vmsix. Pop the first unused_bar_index in gpa.py instead.
Reference code: init_vmsix_on_msi of hypervisor\dm\vpci\vmsix_on_msi.c
Tracked-On: #6192

config-tools: allocate the first unused bar for vmsix

---

hypervisor/boot/guest/vboot_info.c

For ramdisk, need to double check the limit of ramdisk GPA when locate
ramdisk load addr;
For SOS kernel load addr, need not to consider position of hypervisor
start and end address since the range has been set to e820 RESERVED.
Tracked-On: #5879

HV: ramdisk and kernel load addr improve

---

doc/tutorials/enable_ivshmem.rst

Refine the guide to set up ivshmem for both hv-land and dm-land usage.

doc: update ivshmem user guide

---

doc/release_notes/release_notes_2.5.rst

doc: draft for 2.5 release notes contribution

---

doc/tutorials/nvmx_virtualization.rst

Additional clarity and formatting edits to #6198

doc: tweaks to nvmx virtualization doc

---

misc/config_tools/board_inspector/README

1. Update python script name that is executed to generate board xml file
from run.py to cli.py in README file.
2. Update the OS requirement under native Linux in
misc/config_tools/board_inspector/README file.
Tracked-On: #6134

config_tools: modify README file

---

doc/developer-guides/hld/hld-overview.rst

doc: update TCC feature names in hld overview

---

doc/developer-guides/doc_guidelines.rst

doc: clarify doc guidelines

---

doc/reference/hardware.rst

doc: update supported hardware document

---

doc/reference/hardware.rst

Resolve different edits to the supported hardware doc from
PRs #6228 and #6229

doc: resove conflicting edits to supported hardware

---

doc/release_notes/release_notes_2.5.rst

doc: update changed does in release notes

---

doc/conf.py

doc: fix broken links in redirect list

---

doc/asa.rst

update fixed security vulnerabilities for 2.5 release.

doc: update security advisory for 2.5 release

---

doc/release_notes/release_notes_2.5.rst

Fix some minor formatting/layout issues and wording

doc: release notes edits

---

doc/develop.rst
doc/tutorials/acrn-secure-boot-with-efi-stub.rst

Add user guide for ACRN EFI application for Secure Boot.
Tracked-On: #6078

doc: add acrn efi-stub user guide

---

doc/tutorials/acrn-secure-boot-with-efi-stub.rst

doc: edit efi-stub tutorial

---

doc/release_notes/release_notes_2.5.rst

doc: update v2.5 release notes

---

misc/efi-stub/Makefile
misc/efi-stub/boot.c
misc/efi-stub/boot.h
misc/efi-stub/container.c
misc/efi-stub/container.h
misc/efi-stub/efilinux.h
misc/efi-stub/elf32.c
misc/efi-stub/elf32.h
misc/efi-stub/malloc.c
misc/efi-stub/multiboot.c
misc/efi-stub/multiboot.h
misc/efi-stub/pe.c
misc/efi-stub/stdlib.h

Backport EFI stub to mainline.

misc: efi-stub: EFI stub backport

---

doc/reference/hardware.rst

Links to UP2 Shop were incorrect

doc: fix link in hardware doc

---

doc/release_notes/release_notes_2.5.rst

- fix titles for fixed issues list
- edit what's new section to improve readability

release notes edits

---

doc/release_notes/release_notes_2.5.rst

Adding known issue in release note.

Doc: release notes update

---

doc/conf.py

doc: add 2.5 to version menu choice

---

doc/release_notes/release_notes_2.5.rst

doc: update known issues list in v2.5 release notes

---

doc/release_notes/release_notes_2.5.rst

doc: update known issues in 2.5 release notes

---

devicemodel/core/mem.c
devicemodel/hw/pci/virtio/virtio.c
devicemodel/hw/pci/virtio/virtio_audio.c
devicemodel/hw/pci/virtio/virtio_block.c
devicemodel/hw/pci/virtio/virtio_console.c
devicemodel/hw/pci/virtio/virtio_coreu.c
devicemodel/hw/pci/virtio/virtio_gpio.c
devicemodel/hw/pci/virtio/virtio_hdcp.c
devicemodel/hw/pci/virtio/virtio_hyper_dmabuf.c
devicemodel/hw/pci/virtio/virtio_i2c.c
devicemodel/hw/pci/virtio/virtio_input.c
devicemodel/hw/pci/virtio/virtio_ipu.c
devicemodel/hw/pci/virtio/virtio_mei.c
devicemodel/hw/pci/virtio/virtio_net.c
devicemodel/hw/pci/virtio/virtio_rnd.c
devicemodel/hw/pci/virtio/virtio_rpmb.c
devicemodel/hw/pci/xhci.c

this patch set is to mitigate vulnerabilities reported by security fuzzing.

[release_2.0]port security mitigation patches 

---

devicemodel/core/mem.c
devicemodel/hw/pci/virtio/virtio.c
devicemodel/hw/pci/virtio/virtio_audio.c
devicemodel/hw/pci/virtio/virtio_block.c
devicemodel/hw/pci/virtio/virtio_console.c
devicemodel/hw/pci/virtio/virtio_coreu.c
devicemodel/hw/pci/virtio/virtio_hdcp.c
devicemodel/hw/pci/virtio/virtio_hyper_dmabuf.c
devicemodel/hw/pci/virtio/virtio_input.c
devicemodel/hw/pci/virtio/virtio_ipu.c
devicemodel/hw/pci/virtio/virtio_mei.c
devicemodel/hw/pci/virtio/virtio_net.c
devicemodel/hw/pci/virtio/virtio_rnd.c
devicemodel/hw/pci/virtio/virtio_rpmb.c
devicemodel/hw/pci/xhci.c

this patch set is to mitigate vulnerabilities reported by security fuzzing.

[apl_sdc_stable] port security mitigation patches 

---

devicemodel/core/vmmapi.c
devicemodel/hw/pci/virtio/virtio.c
devicemodel/hw/pci/virtio/virtio_console.c

#CVE-2021-23902
#CVE-2021-23904
#CVE-2021-23905

[Release_2.0] DM: port CVEs fix 

---

devicemodel/hw/pci/virtio/virtio.c
devicemodel/hw/pci/virtio/virtio_console.c

#CVE-2021-23902
#CVE-2021-23904
#CVE-2021-23905

[apl_sdc_stable] port CVE Fix

---

README.rst

acrn-security@lists.projectacrn.org shall be used.

doc: Update address to report security vulnerability

---

misc/config_tools/board_inspector/extractors/60-pci.py
misc/config_tools/board_inspector/pcieparser/caps.py
misc/config_tools/xforms/config_common.xsl

Calculates MAX_MSIX_TABLE_NUM based on max(counts of msi, table_size of msi-x)

config-tools: get the proper MAX_MSIX_TABLE_NUM

---

doc/user-guides/acrn-shell.rst

Update keys to return to ACRN shell console

doc: fix acrn shell command

---

hypervisor/debug/uart16550.c

Currently the HV console does not support PCI UART with 64bit BAR, but in the
case that the BAR is in 64bit and the BAR space is below 4GB (i.e. the high
32bit address of the 64bit BAR is zero), HV should be able to support it.
Tracked-On: #6334

HV: debug: support 64bit BAR pci uart with 32bit space

---

doc/release_notes/release_notes_2.5.1.rst

doc: add v2.5.1 release notes

---

misc/config_tools/xforms/config.h.xsl
misc/config_tools/xforms/config.mk.xsl
misc/config_tools/xforms/config_common.xsl
misc/config_tools/xforms/lib.xsl

If the MAX_MSIX_TABLE_NUM is specified in scenario.xml. Return the
largest number from count of MSI, table_size of MSIX or
MAX_MSIX_TABLE_NUM of scenario.xml.
Tracked-On: #6235

config-tools: refine MAX_MSIX_TABLE_NUM

---

misc/config_tools/schema/VMtypes.xsd
misc/config_tools/schema/config.xsd
misc/config_tools/schema/types.xsd

Fix some formatting issues in PR #6378
Tracked-On: #6377

doc: update config data descriptions

---

misc/config_tools/data/cfl-k700-i7/cfl-k700-i7.xml
misc/config_tools/data/ehl-crb-b/ehl-crb-b.xml
misc/config_tools/data/nuc11tnbi5/nuc11tnbi5.xml
misc/config_tools/data/nuc7i7dnb/nuc7i7dnb.xml
misc/config_tools/data/qemu/qemu.xml
misc/config_tools/data/tgl-rvp/tgl-rvp.xml
misc/config_tools/data/whl-ipc-i5/whl-ipc-i5.xml
misc/config_tools/data/whl-ipc-i7/whl-ipc-i7.xml

update the board xml and related scenario xml files because the
PR 6352 update the board inspector code to get more board info.
Tracked-On: #6298

config_tools: update the board xml files

---

hypervisor/arch/x86/guest/ve820.c

Since previous patch to enlarge ACPI NVS/Data region from
960K(reclaim)/64K(NVS) to 960K(reclaim)/1M(NVS), some hard-coded
constants in create_prelaunched_vm_e820 were left unchanged.
This may results in failure to map the ACPI NVS region because the
remaining memory size was wrong.
This patch updates the constants and comments of function
create_prelaunched_vm_e820.
Tracked-On: #6423

release_2.6: hv: ve820: Minor changes to prelaunched VM ve820 mapping

---

misc/config_tools/config_app/views.py

remove some tags check for scenario xml files in generic_board folder when
to import a new type board in UI.

config_tools: remove some tags check for scenario.xml in generic_board folder

---

hypervisor/arch/x86/guest/vcpuid.c
hypervisor/arch/x86/guest/vmcs.c
hypervisor/arch/x86/guest/vmsr.c

This PR is ported from mainline:
https://github.com/projectacrn/acrn-hypervisor/pull/6319

[release_v2.5] expose PMC to partition VM

---

hypervisor/common/event.c
hypervisor/include/common/event.h

Same PR in 2.6 already merged. Backport to master.

hv: Change sched_event structure to resolve data race in event handling

---

doc/getting-started/getting-started.rst

doc: additional DX edits to the new GSG

---

doc/getting-started/getting-started.rst

And, seeing if I can do a pull request.

doc: fix step numbers

---

doc/getting-started/getting-started.rst

Need to "freeze" the acrn-hypervisor for DX reviews since the
release_2.6 branch is still changing with fixes.

doc: update GSG checkout commits

---

hypervisor/arch/x86/guest/vcpu.c

For platforms that do not support XSAVES/XRSTORS instructions, like QEMU,
executing these instructions causes #UD.
This patch adds the check before the execution of XSAVES/XRSTORS instructions.
It also refines the logic inside rstore_xsave_area for the following reason:
If XSAVES/XRSTORS instructions are supported, restore XSAVE area if any of the
following conditions is met:
1. "vcpu->launched" is false (state initialization for guest)
2. "vcpu->arch.xsave_enabled" is true (state restoring for guest)
* Before vCPU is launched, condition 1 is satisfied.
* After vCPU is launched, condition 2 is satisfied because
is_valid_xsave_combination() guarantees that "vcpu->arch.xsave_enabled"
is consistent with pcpu_has_cap(X86_FEATURE_XSAVES).
Therefore, the check against "vcpu->launched" and …

[for v2.6] hv: check the capability of XSAVES/XRSTORS instructions before execution

---

devicemodel/hw/platform/acpi/rtct.c

Native SSRAM entries with only one LAPIC ID of
value 0 in local APIC ID table can't be pass-thru
to guest. Such kind of SSRAM entries are for cache
regions that are global shared and shall be visible
to guests.
This patch refine the building logic of vRTCT to fix
above issue.
Tracked-On: #6510

[release_2.6]DM: fix issue when pass-thru native RTCT SSRAM entries

---

hypervisor/quirks/security_vm_fixup.c

On some UEFI platforms, it is found that SMBIOS major version 3 can be
found under SMBIOS2 GUID, so using major version to distinguish
different version of SMBIOS is not reliable. This patch removes the use
of smbios_info.major_ver, and checks the anchor string instead.
Tracked-On: #6528

release_2.6: hv: minor change to SMBIOS version check

---

hypervisor/quirks/security_vm_fixup.c

Previously it is (falsely) assumed that the major_ver of 32-bit SMBIOS
entry point structure (which is called SMBIOS 2.1 in spec, or SMBIOS2 in code)
will have a value of 2 and major_ver of 64-bit SMBIOS (which is called SMBIOS
3.0 in spec, and SMBIOS3 in code) will have a value of 3. This turned out to be
wrong. This major_ver refers to the implemented doc revision, and 32-bit SMBIOS2
can have its major_ver to be 3 (current most recent implementation).
This patch removes the use of major_ver to distinguish between
SMBIOS2/3, and use a doc-defined anchor string instead.
Tracked-On: #6528

hv: Avoid using SMBIOS major version

---

doc/getting-started/getting-started.rst

Fix some issues found during DX studies of the new GSG that are trivial
changes but are impacting users in the study.

doc: tweak GSG DX issues

---

doc/release_notes/release_notes_2.6.rst

doc: starting draft for v2.6 release notes

---

doc/tutorials/enable_ptm.rst

Fix an error in the documentation where the output from dmesg was
incorrect for the Service VM.

doc: update enable PTM instructions

---

doc/release_notes/release_notes_2.6.rst

doc: add documentation updates to release notes

---

hypervisor/arch/x86/rdt.c
hypervisor/include/arch/x86/asm/rdt.h

Fix some RDT issues found during vCAT testing so use vCAT's git issue # for this PR:
Some cosmetic fixes to rdt.c/rdt.h
Fix bugs in RDT's CDP code
Tracked-On: #5917

hv: some fixes to rdt.c/rdt.h

---

README.rst

TCM (Technical comunity meetings) are monthly not weekly...

doc: update README for TCM meeting change

---

hypervisor/arch/x86/cpu_caps.c

check some essential vmx capablility,
will panic if processor doesn't support it.
Tracked-On: #6584

add vmx capability check

---

devicemodel/hw/pci/passthrough.c
doc/tutorials/gpu-passthru.rst
doc/tutorials/using_windows_as_uos.rst
misc/config_tools/data/sample_launch_scripts/nuc/launch_win.sh
misc/config_tools/launch_config/com.py

remove "gpu" parameter when pass-thru IGD

remove "gpu" parameter when pass-thru IGD

---

misc/config_tools/xforms/lib.xsl
misc/config_tools/xforms/misc_cfg.h.xsl

Return true if the tpm device is present and if the passthrough tpm2 is enabled.
Tracked-On: #6562

config-tools: refine acrn:is-tpm-passthrough-board

---

CODE_OF_CONDUCT.rst

doc: Add CODE_OF_CONDUCT to project repo

---

doc/release_notes/release_notes_2.6.rst

Add new features information provided by engineering.

doc: update release notes with new features

---

doc/tutorials/using_hybrid_mode_on_nuc.rst
doc/tutorials/using_partition_mode_on_nuc.rst

doc: update serial port instructions in scenario GSGs

---

doc/tutorials/using_hybrid_mode_on_nuc.rst
doc/tutorials/using_partition_mode_on_nuc.rst

1. Modified Intel Whiskey Lake to Intel NUC Kit NUC11TNBi5
2. Change the logical partition and mixed test motherboard name
Signed-off-by: Zhong Zhenx.Liu <zhongzhenx.liu@intel.com>

doc: Update logical_partition documentation

---

doc/asa.rst

Update security vulnerability fix in 2.6 release.

doc: update 'asa.rst' for 2.6 release

---

doc/glossary.rst

There are many graphics-related terms in the glossary that are not
referenced in the documentation.  Remove those terms, and clarify new
terms in our updated GSG and introductory docs.

doc: cleanup/update glossary terms

---

doc/getting-started/getting-started.rst

doc: update checkout branch in GSG

---

doc/release_notes/release_notes_2.6.rst

Doc: Add known issue and fixed issue in release note

---

doc/conf.py

doc: add v2.6 to doc menu selector

---

doc/tutorials/enable_s5.rst

Update the "Enable S5 in ACRN" tutorial to:
* Make the language clearer at places
* Consistent use of "Lifecycle Manager" and "life_mngr"
* Change "ACK" to "ACKED"
* Use a ReST reference to point at the architectural diagram
* Update build instructions

doc: Update "Enable S5 in ACRN" tutorial

---

doc/getting-started/getting-started.rst

doc: update GSG with DX recommendations

---

hypervisor/arch/x86/guest/vcpu.c

This patch implements a separate path for L2 VMEntry in run_vcpu(),
which has several benefits:
- keep run_vcpu() clean, to reduce the number of is_vcpu_in_l2_guest()
statements:
- current code has three is_vcpu_in_l2_guest() already.
- supposed to have another 2 statement so that nested VMEntry won't
hit the "Starting vCPU" and "vCPU launched" pr_info() and a few
other statements in the VM launch path.
- save few other things in run_vcpu() that are not needed for nested.

hv: optimize run_vcpu() for nested

---

doc/reference/hardware.rst
doc/tutorials/trustyACRN.rst

doc: fix broken links

---

.gitignore
misc/config_tools/config_app/templates/launch.html
misc/config_tools/config_app/views.py
misc/config_tools/data/generic_board/hybrid_launch_2uos.xml
misc/config_tools/data/generic_board/shared_launch_6uos.xml
misc/config_tools/data/nuc11tnbi5/hybrid_launch_2uos.xml
misc/config_tools/data/nuc11tnbi5/shared_launch_6uos.xml
misc/config_tools/data/whl-ipc-i5/hybrid_rt_launch_1uos_waag.xml
misc/config_tools/data/whl-ipc-i5/sdc_launch_1uos_laag.xml
misc/config_tools/data/whl-ipc-i5/sdc_launch_1uos_zephyr.xml
misc/config_tools/data/whl-ipc-i5/shared_launch_1uos_hardrt.xml
misc/config_tools/data/whl-ipc-i5/shared_launch_1uos_vxworks.xml
misc/config_tools/data/whl-ipc-i5/shared_launch_1uos_waag.xml
misc/config_tools/data/whl-ipc-i5/shared_launch_2uos.xml
misc/config_tools/data/whl-ipc-i5/shared_launch_6uos.xml
misc/config_tools/launch_config/com.py
misc/config_tools/launch_config/launch_cfg_gen.py
misc/config_tools/launch_config/launch_item.py
misc/config_tools/launch_config/pt.py
misc/config_tools/library/common.py
misc/config_tools/library/launch_cfg_lib.py

1. Update launch xml for Sriov/GPU passthrough support
2. Remove gvt_args field.
3. Add passthrough GPU devices support.
4. Add sriov device support.
[External_System_ID] ACRN-5968
Tracked-On: #6290
Signed-off-by: Weiyi Feng weiyix.feng@intel.com

config_tools: Update GPU passthrough support 

---

doc/glossary.rst

doc: clean up UOS/SOS and scenario names in glossary

---

misc/config_tools/config_app/controller.py
misc/config_tools/config_app/static/main.js
misc/config_tools/config_app/templates/launch.html
misc/config_tools/config_app/templates/scenario.html
misc/config_tools/config_app/views.py

since PRs [#6760](https://github.com/projectacrn/acrn-hypervisor/pull/6760) and [#6747](https://github.com/projectacrn/acrn-hypervisor/pull/6747) have renamed uos to user_vm,
we also need to rename it in config UI.
Tracked-On: #6744

config_tools: rename uos to user_vm in config UI

---

doc/developer-guides/hld/index.rst
doc/introduction/index.rst

doc: terminology cleanup in What Is ACRN, HLD intro

---

doc/tutorials/using_partition_mode_on_nuc.rst
misc/config_tools/data/nuc11tnbi5/partitioned.xml

Rename logical_partition to partitioned;
Use acrn hypervisor commit instead of tag v2.6;
Add partitioned.xml ramdisk parameter.
Tracked-On: #6709

doc: Update nuc11 partitioned document and Scenario xml

---

doc/developer-guides/hld/hv-memmgt.rst

fix misspelling in memory management docs
Signed-off-by: Musa Unal umusasadik@gmail.com

doc: fix misspelling in memory management doc

---

doc/tutorials/using_partition_mode_on_nuc.rst

- Replace User OS
- Remove command prompts

doc: terminology cleanup in partitioned GSG

---

devicemodel/README.rst

doc: terminology cleanup in DM readme

---

hypervisor/common/sched_bvt.c

When a new thread is wakeup and added to runqueue, it will get the
smallest avt (svt) from runqueue to initiate its avt. But when all
threads are blocked, and removed from the runqueue, the svt is 0. The
new thread will get avt=0. avt=0 means very high priority, and can run
for a very long time until it catchup with other thread's avt in
runqueue.
To fix it, adjust the new thread's avt when there is another thread in
runqueue.
Tracked-On: #6888

hv: sched: fix bug when reboot vm

---

misc/packaging/acrn-hypervisor.preinst

Signed-off-by: Mete Öztürk <mete@stroma.dev>

Fixed minor wording and typos

---

doc/reference/config-options-launch.rst

doc: terminology cleanup in launch options

---

doc/developer-guides/hld/hostbridge-virt-hld.rst

doc: terminology cleanup in hostbridge hld

---

doc/tutorials/cpu_sharing.rst

Add description for the IORR (IO sensitive Round Robin) scheduler
and the priority based scheduler.

doc: update two scheduling algorithm

---

doc/glossary.rst
doc/introduction/index.rst

doc: remove Android in introductory material

---

doc/conf.py

doc: update Linux Foundation copyright footer

---

doc/tutorials/board_inspector_tool.rst

- Update success message per PR https://github.com/projectacrn/acrn-hypervisor/pull/6672
- Capitalize Board Inspector

doc: minor updates to board inspector

---

misc/config_tools/xforms/vm_configurations.c.xsl

check VM number before filling with dynamic configured VM
[External_System_ID] ACRN-7519
Tracked-On: #6907

config_tools: check VM number before filling with dynamic configured VM

---

doc/tutorials/nvmx_virtualization.rst
doc/tutorials/using_hybrid_mode_on_nuc.rst
doc/tutorials/using_windows_as_user_vm.rst

- Capitalize ACRN Configurator

doc: terminology cleanup in Hybrid GSG, tutorials

---

doc/developer-guides/hld/hld-trace-log.rst

Removed placeholders for images. Will create an issue for tracking.

doc: Remove placeholder text from acrntrace

---

doc/release_notes/release_notes_2.7.rst

This patch updates recommendations to upgrade from a prior ACRN version
for v2.7.

doc: update release notes for v2.7 on configuration upgrades

---

hypervisor/arch/x86/guest/optee.c
hypervisor/arch/x86/guest/vlapic.c
hypervisor/arch/x86/guest/vmcall.c
hypervisor/hw/pci.c
hypervisor/include/arch/x86/asm/guest/optee.h
hypervisor/include/arch/x86/asm/guest/vlapic.h
hypervisor/include/arch/x86/asm/vm_config.h

These patches are third batch of x86_tee patches.

x86_tee patches upstream

---

doc/asa.rst

Update security advisory 2.7 release.

doc: update 'asa.rst' for 2.7 release

---

doc/release_notes/release_notes_2.7.rst

Fix errors in description of changes.
Add mention of SOS -> Service_VM change in config options/values.

doc: update 2.7 release notes

---

doc/reference/hardware.rst

- Remove outdated information.
- Add new HW table.

doc: Supported HW

---

doc/tutorials/acrn_on_qemu.rst

To launch User VM, cpu_affinity parameter is needed for v2.7.

Doc: Launch script update for acrn on qemu

---

doc/release_notes/release_notes_2.7.rst

doc: finalize 2.7 release notes

---

doc/release_notes/release_notes_2.7.rst

Update description of passthrough device usecase additions, and improved
description of Issue #6631 (Kata broken)

doc: clarify 2.7 release notes

---

misc/packaging/acrn-hypervisor.postinst

Debian package adds support for hybrid_rt scenario.
Tracked-On: #6688

deb-pkg: Support hybrid_rt scenario

---

misc/config_tools/launch_config/com.py

add cpu_affinity cmdline at scenario set "SCHED_NOOP"
Tracked-On: #6961

config_tools: add cpu_affinity cmdline at scenario set "SCHED_NOOP"

---

misc/packaging/100_ACRN

Rename acrn-sos to acrn-service-vm
Tracked-On: #6688

deb-pkg: rename acrn-sos to acrn-service-vm

---

misc/config_tools/data/cfl-k700-i7/cfl-k700-i7.xml
misc/config_tools/data/cfl-k700-i7/hybrid.xml
misc/config_tools/data/cfl-k700-i7/hybrid_launch_2user_vm.xml
misc/config_tools/data/cfl-k700-i7/hybrid_rt.xml
misc/config_tools/data/cfl-k700-i7/partitioned.xml
misc/config_tools/data/cfl-k700-i7/shared_launch_6user_vm.xml
misc/config_tools/data/generic_board/generic_board.xml
misc/config_tools/data/nuc11tnbi5/nuc11tnbi5.xml
misc/config_tools/data/whl-ipc-i5/hybrid_rt_launch_1user_vm_waag.xml
misc/config_tools/data/whl-ipc-i5/sdc_launch_1user_vm_laag.xml
misc/config_tools/data/whl-ipc-i5/shared.xml
misc/config_tools/data/whl-ipc-i5/shared_launch_1user_vm_waag.xml
misc/config_tools/data/whl-ipc-i5/whl-ipc-i5.xml

Re-obtain  generic/nuc11/whl/cfl board xmls according to 6987.patch
Modify the corresponding scenario pci
Tracked-On: #6986

config_tool: update generic/nuc11/whl/cfl board xmls

---

doc/tutorials/debug.rst

- Update file path to acrn_trace files

doc: Update debug tools path

---

hypervisor/arch/x86/e820.c

Now the multiboot modules memory have not reserve,it's an issue if
these memory alloc and write before VM start.
Incorrect allocation of multiboot modules memory will cause VM lost
data or start faild.
So we find these modules memory range and reserve these memory from
e820 entry.
All these memory will realloc to VM which own them before the vm start.

hv: alloc multiboot modules memory

---

hypervisor/scripts/makefile/config.mk
misc/config_tools/board_inspector/acpiparser/aml/stream.py
misc/config_tools/board_inspector/extractors/60-pci.py
misc/config_tools/board_inspector/pcieparser/__init__.py

This PR contains 3 bug fixes to the board inspector and HV build system, with each fix separated as an individual patch. Refer to the commit messages for details about the issues and the resolution.

Bug fixes to the board inspector and build system

---

misc/config_tools/launch_config/com.py

1. for the `virtio-net`, add type field to specify tap/macvtap type.
The generated script will look like this. (eg. -s 4,virtio-net,tap=Waag)
2. Change mac_seed as virtio-net subparameter.
(eg. -s 10,virtio-net,tap=YaaG3,mac_seed=XXXXXX)

config_tools: update the usage of virtio-net parameter in launch script

---

doc/getting-started/getting-started.rst
doc/tutorials/acrn_configurator_tool.rst
misc/config_tools/config_app/acrn_configurator.py

Add shebang header to `acrn_configurator.py`, make it executable and update the documentation accrodingly.
Tracked-On: #7057

Shebang configurator

---

hypervisor/arch/x86/mmu.c

Current mmu assum the high memory start from 4G,it's not true for some
platform.
The map logic use "high64_max_ram - 4G" to calculate the high ram size
without any check,it's an issue when the platform have no high memory.
So this patch add high64_min_ram variable to calculate the min address
of high memory and check the high64_min_ram to fix the previou issue.

hv:refine the min address logic of high memory

---

misc/config_tools/data/tgl-vecow-spc-7100-Corei7/hybrid.xml
misc/config_tools/data/tgl-vecow-spc-7100-Corei7/partitioned.xml
misc/config_tools/data/tgl-vecow-spc-7100-Corei7/shared.xml
misc/config_tools/data/tgl-vecow-spc-7100-Corei7/shared_launch_2user_vm.xml
misc/config_tools/data/tgl-vecow-spc-7100-Corei7/tgl-vecow-spc-7100-Corei7.xml

Add tgl-vecow-spc-7100-Corei7 board, scenario and launch xml files.
Tracked-On: #7019

config_tool:  Add tgl-vecow-spc-7100-Corei7 board/scenario/launch xml files

---

devicemodel/hw/platform/tpm/tpm.c

Now the acpidev_pt module only use the hid to check the device,it can't
work well if there are more then one instance.
So this patch add UID to identify same type device to fix these issue.

dm:add UID parameter for acpidev_pt

---

hypervisor/arch/x86/e820.c

Sometimes the memory to be allocated is not at the end of an entry,
that means we have to break one enty into 2 smaller entries, there
are two ways to add the new entry to hv_e820, adds to the end or
insert it.
The initial e820 table is ordered, that's why the e820_alloc_memory
interface asssum all entries was sorted, but add new entry to the
end will break the orde of hv_e820.
So we use insert_e820_entry to replace the add_e820_entry, the new
interfeac will keep the orde and users do not need sort again after
alloc region
Signed-off-by: Chenli Wei<chenli.wei@linux.intel.com>

hv: refine the e820 add new entry logic

---

devicemodel/hw/platform/vssram/vssram.c

By default, pCPU is allowed to request software SRAM buffer
from given region in TCC buffer driver only if this pCPU is
set in the target region's CPU affinity configuration.
This check shall be disabled for software SRAM virtualization
usage in ACRN service VM, because software SRAM buffers are
requested by ACRN DM on behalf of user VM, but ACRN DM and
user VM may run on different CPUs but the target software SRAM
region may be configured only for pCPUs that user VM runs on.
This patch turns off such affinity check in TCC driver when
initializing vSSRAM for user VM.
Tracked-On: #7010

dm: disable TCC strict CPU affinity check

---

doc/tutorials/acrn_on_qemu.rst

Clarify that ``cpu-checker`` is the package that you install to get the
``kvm-ok`` tool used in these instructions.

doc: update cpu-checker instructions in qemu doc

---

doc/tutorials/acrn_on_qemu.rst

- Remove "sdc"
- Replace "sos" with "Service VM"
- Replace "uos" with "User VM"

doc: Update terms in qemu tutorial

---

doc/developer-guides/doc_guidelines.rst
doc/developer-guides/graphviz.rst

- Minor style changes per Acrolinx recommendations

doc: Style cleanup in doc guides

---

devicemodel/core/mevent.c

'mevent_lmutex' is initialized as default type
attempting to recursively lock on this kind of
mutext results in undefined behaviour.
Recursively lock on 'mevent_lmutex' can be detected
in mevent thread when user tries to trigger system
reset from user VM, in this case, user VM reboot hang.
The backtrace for this issue:
#1 in mevent_qlock () at core/mevent.c:93
#2 in mevent_delete_even at core/mevent.c:357
===>Recursively LOCK
#3 in mevent_delete_close at core/mevent.c:387
#4 in acrn_timer_deinit at core/timer.c:106
#5 in virtio_reset_dev at hw/pci/virtio/virtio.c:171
#6 in virtio_console_reset at
hw/pci/virtio/virtio_console.c:196
#7 in virtio_console_destroy at
hw/pci/virtio/virtio_console.c:1015
#8 in virtio_console_teardown_backend at
hw/pci/virtio/virtio_console.c:1042
#9 in …

dm: fix mevent mutex deadlock issue

---

Makefile

The 'dpkg' utility is required in order to build Debian packages. If it is not
installed and available on the build system, the 'make' instructions will fail
with a Python traceback. Fix this by detecting its availability and doing a
graceful exit if not (or simply skip the step).
Tracked-On: #7109

Makefile: detect if 'dpkg' is available

---

doc/tutorials/vuart_configuration.rst

- Update scenario names
Tracked-On: #6701

doc: Update terms in vUART tutorial

---

doc/tutorials/realtime_performance_tuning.rst

remove obsolete content in Document

doc: remove obsolete content in document

---

doc/developer-guides/hld/vuart-virt-hld.rst
doc/developer-guides/trusty.rst
doc/tutorials/setup_openstack_libvirt.rst
misc/debug_tools/acrn_crashlog/usercrash/README.rst

- Minor style changes per Acrolinx recommendations and for consistency

doc: Style cleanup in usercrash, trusty, vuart docs

---

doc/api/devicemodel_api.rst
doc/api/hypercall_api.rst
doc/user-guides/acrn-shell.rst
doc/user-guides/hv-parameters.rst

- Minor style changes per Acrolinx recommendations and for consistency

doc: Style cleanup in guides

---

doc/develop.rst
doc/tutorials/tar_installation.rst

- New document about building tarball files for ACRN installation.
- Steps are from GSG.

doc: Tar file installation

---

doc/developer-guides/hld/hv-timer.rst

- Minor style changes per Acrolinx recommendations and for consistency

doc: Style cleanup in timer hld

---

devicemodel/core/mptbl.c

Previous commit introduced the "use physical APIC IDs as vLAPIC IDs for VMs" change,
but it didn't update the apic_id in mptable. Changed the mptable code to also
set apic_id to physical APIC ID to fix the bug
Tracked-On: #7146

fixed a bug where mptable failed to wake up CPU1# when adding acpi=off into User VM cmdline

---

misc/config_tools/launch_config/launch_cfg_gen.py
misc/config_tools/launch_config/launch_script_template.sh

Fix the issue that doesn't offline CPU in SCHED_NOOP mode.
Tracked-On: #7172

config_tools: fix the issue that doesn't offline CPU in SCHED_NOOP mode

---

devicemodel/hw/pci/ahci.c
devicemodel/hw/pci/virtio/virtio_block.c
devicemodel/hw/pci/virtio/virtio_i2c.c
devicemodel/hw/pci/virtio/virtio_net.c
devicemodel/hw/platform/rpmb/rpmb_sim.c
misc/debug_tools/acrn_crashlog/acrnprobe/probeutils.c

HMAC_*, MD5_* and SHA256_* are deprecated since openssl3.0, replace them with the corresponding equivalents.
Tracked-On: #6743

dm/tools: compatible with openssl3.0

---

misc/config_tools/static_allocators/lib/lib.py

config tool: fixup load_order bug

---

doc/developer-guides/hld/ivshmem-hld.rst

doc: Fix line wrap in ivshmem hld

---

misc/config_tools/static_allocators/guest_flags.py

Fix tee guest flag
Track-On:#6690

config tool: Fix tee guest flag

---

doc/developer-guides/hld/hv-hypercall.rst

Style changes per Acrolinx recommendations and for consistency

doc: Style cleanup in hypercall hld

---

doc/developer-guides/hld/hld-emulated-devices.rst
doc/developer-guides/hld/hostbridge-virt-hld.rst

Style changes per Acrolinx recommendations and for consistency

doc: Style cleanup in host bridge hld

---

doc/getting-started/getting-started.rst

- Add an optional step in GSG to power off User VM.

doc: Add poweroff step to gsg

---

doc/developer-guides/hld/hld-overview.rst

- Clarify that sdc predefined scenario is no longer supported
- Minor cleanup
Tracked-On: #6701

doc: Update sdc reference in overview hld

---

misc/config_tools/schema/VMtypes.xsd
misc/config_tools/schema/config.xsd
misc/config_tools/schema/types.xsd

- Update XSD files to match field names and tooltips in parameter spreadsheet

config_tools: Update Configurator UI XSD

---

hypervisor/acpi_parser/dmar_parse.c

Now ACRN Hypervisor only support one PCI Segment, this patch add this check.
This patch also fix a small bug: it would trigger false error "DRHD with
INCLUDE_PCI_ALL flag is NOT the last one".
Tracked-On: #5907

hv: acpi: refine dmar acpi table parse

---

misc/services/acrn_manager/acrnd.service
misc/services/life_mngr/command_handler.c
misc/services/life_mngr/config.c
misc/services/life_mngr/config.h
misc/services/life_mngr/life_mngr.conf
misc/services/life_mngr/life_mngr_win.c

add a separate config to allow trigger sysreboot
Tracked-On: #7215

misc: life_mngr: add a separate config to allow trigger sysreboot

---

doc/reference/hv-make-options.rst

- Remove mention of tgl-rvp XML because the file was removed from repo
Tracked-On: #6177

doc: Remove tgl-rvp mention

---

misc/config_tools/configurator/yarn.lock

update configurator dependencies to latest version

configurator: update configurator dependencies to latest version

---

misc/config_tools/configurator/package.json
misc/config_tools/configurator/src/assets/schema/scenario.json
misc/config_tools/configurator/src/lib/acrn.jsx
misc/config_tools/configurator/src/pages/Config/CreateNewOrImportAnExistingScenario/CreateNewOrImportAnExistingScenario.jsx
misc/config_tools/scenario_config/jsonschema/converter.py

1. [configurator: fix displayed scenario path](https://github.com/projectacrn/acrn-hypervisor/commit/43843e36610d6cc4f26ef90efd9082cbb0f2a91b) that doubled path splitter.
2. [configurator: fix user can not load scenario's vm data which only have single vm  ](https://github.com/projectacrn/acrn-hypervisor/commit/82a24d439239b9695f621f7fa88879425df454ec).
3. [configurator: fix some schema field does not provide display name](https://github.com/projectacrn/acrn-hypervisor/commit/52e607db688fdc31976f4cbd891d94f5bda04bde)  that's blocked configurator build issue.

configurator: Fix some issue

---

misc/config_tools/schema/config.xsd

Fix it in schema by adding attribute acrn:applicable-vms
Tracked-On:#7262

config tool: service vm parameter display

---

devicemodel/hw/pci/virtio/virtio_gpu.c
devicemodel/hw/vga.c
devicemodel/include/types.h
devicemodel/include/vga.h

Add license information to virtio_gpu.c
Fix some grammar issues.
Tracked-On: #7241

dm: virtio-gpu: update copyright and license

---

misc/config_tools/schema/config.xsd

change acrn:view attribute to ""
Tracked-On: #7261

config tool: hide PTM in schema

---

misc/config_tools/schema/config.xsd

add support for more than one virtio block setting
for specific vm
Tracked-On: #7277

config tool: update virtio block setting

---

doc/developer-guides/hld/hv-cpu-virt.rst
doc/tutorials/cpu_sharing.rst
misc/config_tools/schema/VMtypes.xsd
misc/config_tools/schema/types.xsd

hide SCHED_IORR and KERNEL_RAWIMAGE in schema
and update SCHED_IORR in doc
Tracked-On: #7256

config tool/doc:update SCHED_IORR in schema

---

doc/user-guides/acrn-dm-parameters.rst

Update parameters of virtio-gpu in acrn-dm-parameters.rst
Tracked-On: #7210

doc: virtio-gpu parameters of acrn-dm

---

doc/developer-guides/asm_coding_guidelines.rst
doc/developer-guides/hld/hld-splitlock.rst
doc/developer-guides/hld/hv-rdt.rst
doc/developer-guides/l1tf.rst
doc/tutorials/rdt_configuration.rst
doc/tutorials/rtvm_performance_tips.rst

- Fix broken software.intel.com links that moved to intel.com domain

doc: Fix links

---

doc/developer-guides/doc_guidelines.rst
doc/developer-guides/hld/hld-splitlock.rst
doc/glossary.rst
doc/introduction/index.rst
doc/reference/hv-make-options.rst
doc/tutorials/cpu_sharing.rst
doc/user-guides/acrn-dm-parameters.rst

doc: Capitalize Board Inspector and ACRN Configurator

---

doc/getting-started/getting-started.rst

- Add comment in upgrade command in case users ignore description above command

doc: Add note to GSG about optional upgrade

---

hypervisor/common/ptdev.c

Now interrupt vector in ACRN hypervisor is maintained as global variable, not
per-CPU variable. If there're more PCI devices, the physical interrupt vectors
are not enough most likely.
This patch would not allocate physical interrupt vector for MSI/MSI-X vectors
if interrupt posting could been used to inject the MSI/MSI-X interrupt to
a VM directly.
Tracked-On: #7275

hv: ptdev: address vector scalability problem by interrupt posting

---

hypervisor/arch/x86/guest/vcpuid.c

When CPUID executes with EAX set to 02H, the processor returns information about cache and TLB information.
This information is percpu related, and should be obtained directly from the physical cpu.
BTW, this patch is backported from v2.7 branch.
Tracked-On: #6931

hv: fix cpuid 0x2 mismatch when launch RTVM use atom core

---

misc/config_tools/schema/VMtypes.xsd
misc/config_tools/schema/config.xsd
misc/config_tools/schema/types.xsd

Add documentation for enumerated types and value restrictions so it
shows up in the option documention.  Also add additional acrn:title
annotations.

doc: update schema type documentation

---

misc/config_tools/data/cfl-k700-i7/hybrid_launch_2user_vm.xml
misc/config_tools/data/cfl-k700-i7/hybrid_rt.xml
misc/config_tools/data/cfl-k700-i7/shared_launch_6user_vm.xml
misc/config_tools/data/generic_board/hybrid_launch_2user_vm.xml
misc/config_tools/data/generic_board/hybrid_rt.xml
misc/config_tools/data/generic_board/shared_launch_6user_vm.xml
misc/config_tools/data/nuc11tnbi5/hybrid_launch_2user_vm.xml
misc/config_tools/data/nuc11tnbi5/shared_launch_6user_vm.xml
misc/config_tools/data/qemu/shared.xml
misc/config_tools/data/tgl-vecow-spc-7100-Corei7/hybrid.xml
misc/config_tools/data/tgl-vecow-spc-7100-Corei7/shared_launch_2user_vm.xml
misc/config_tools/data/whl-ipc-i5/hybrid.xml
misc/config_tools/data/whl-ipc-i5/hybrid_rt_launch_1user_vm_waag.xml
misc/config_tools/data/whl-ipc-i5/shared_launch_1user_vm_hardrt.xml
misc/config_tools/data/whl-ipc-i5/shared_launch_1user_vm_vxworks.xml
misc/config_tools/data/whl-ipc-i5/shared_launch_1user_vm_waag.xml
misc/config_tools/data/whl-ipc-i5/shared_launch_2user_vm.xml
misc/config_tools/data/whl-ipc-i5/shared_launch_6user_vm.xml
misc/config_tools/schema/VMtypes.xsd
misc/config_tools/schema/config.xsd

Change parameters attribute to impact UI effect.
Tracked-On: #7335

config tool: Fix parameters in Configurator UI

---

misc/config_tools/data/cfl-k700-i7/hybrid_launch_2user_vm.xml
misc/config_tools/data/cfl-k700-i7/shared_launch_6user_vm.xml
misc/config_tools/data/generic_board/hybrid_launch_2user_vm.xml
misc/config_tools/data/generic_board/shared_launch_6user_vm.xml
misc/config_tools/data/nuc11tnbi5/hybrid_launch_2user_vm.xml
misc/config_tools/data/nuc11tnbi5/shared_launch_6user_vm.xml
misc/config_tools/data/tgl-vecow-spc-7100-Corei7/shared_launch_2user_vm.xml
misc/config_tools/data/whl-ipc-i5/hybrid_rt_launch_1user_vm_waag.xml
misc/config_tools/data/whl-ipc-i5/shared_launch_1user_vm_hardrt.xml
misc/config_tools/data/whl-ipc-i5/shared_launch_1user_vm_vxworks.xml
misc/config_tools/data/whl-ipc-i5/shared_launch_1user_vm_waag.xml
misc/config_tools/data/whl-ipc-i5/shared_launch_2user_vm.xml
misc/config_tools/data/whl-ipc-i5/shared_launch_6user_vm.xml
misc/config_tools/launch_config/launch_cfg_gen.py
misc/config_tools/schema/config.xsd

update vbootloader and vuart0 in schema
Tracked-On: #7294

config tool:update vbootloader xsd file

---

Makefile
hypervisor/scripts/makefile/config.mk
misc/config_tools/data/cfl-k700-i7/hybrid_launch_2user_vm.xml
misc/config_tools/data/cfl-k700-i7/hybrid_rt.xml
misc/config_tools/data/cfl-k700-i7/partitioned.xml
misc/config_tools/data/cfl-k700-i7/shared_launch_6user_vm.xml
misc/config_tools/data/generic_board/hybrid_launch_2user_vm.xml
misc/config_tools/data/generic_board/hybrid_rt.xml
misc/config_tools/data/generic_board/partitioned.xml
misc/config_tools/data/generic_board/shared_launch_6user_vm.xml
misc/config_tools/data/nuc11tnbi5/hybrid_launch_2user_vm.xml
misc/config_tools/data/nuc11tnbi5/partitioned.xml
misc/config_tools/data/nuc11tnbi5/shared_launch_6user_vm.xml
misc/config_tools/data/qemu/shared.xml
misc/config_tools/data/tgl-vecow-spc-7100-Corei7/hybrid.xml
misc/config_tools/data/tgl-vecow-spc-7100-Corei7/partitioned.xml
misc/config_tools/data/tgl-vecow-spc-7100-Corei7/shared_launch_2user_vm.xml
misc/config_tools/data/whl-ipc-i5/hybrid.xml
misc/config_tools/data/whl-ipc-i5/hybrid_rt_launch_1user_vm_waag.xml
misc/config_tools/data/whl-ipc-i5/partitioned.xml
misc/config_tools/data/whl-ipc-i5/shared_launch_1user_vm_hardrt.xml
misc/config_tools/data/whl-ipc-i5/shared_launch_1user_vm_vxworks.xml
misc/config_tools/data/whl-ipc-i5/shared_launch_1user_vm_waag.xml
misc/config_tools/data/whl-ipc-i5/shared_launch_2user_vm.xml
misc/config_tools/data/whl-ipc-i5/shared_launch_6user_vm.xml
misc/config_tools/scenario_config/upgrader.py

Bugfix for acrn build error

---

misc/config_tools/launch_config/launch_script_template.sh

when tap name is number, it will lead to failure of
adding tap dev, fix it.
Tracked-On: #7351

config tool:Fix tap name filter error

---

misc/config_tools/launch_config/launch_cfg_gen.py

add d3hot_reset in launch script when USB xhci is selected
for passthrough device
Tracked-On: #7363

config tool: add d3hot_reset in launch script

---

misc/config_tools/configurator/README.md
misc/config_tools/configurator/index.html
misc/config_tools/configurator/package.json
misc/config_tools/configurator/src-tauri/build.rs
misc/config_tools/configurator/src-tauri/rustfmt.toml
misc/config_tools/configurator/src-tauri/src/configurator.rs
misc/config_tools/configurator/src-tauri/src/main.rs
misc/config_tools/configurator/src/assets/schema/scenario.json
misc/config_tools/configurator/src/components/common/ControlBar.vue
misc/config_tools/configurator/src/lib/acrn.ts
misc/config_tools/configurator/src/main.js
misc/config_tools/configurator/yarn.lock
misc/packaging/gen_acrn_deb.py

1. update configurator document.
2. fix build script doesn't generate allchecks.xsd issue.
3. add open_devtools command, now we can get detail debug info in prod.
4. remove vconsole component, which will cause some strange js runtime issue in Linux.

config_tools: update configurator document and build script

---

doc/getting-started/getting-started.rst

- Add build steps
- Update steps per new UI

doc: Update Configurator steps

---

misc/config_tools/schema/VMtypes.xsd
misc/config_tools/schema/config.xsd

add value restriction for memory size and max pt irq entry
Tracked-On: #7407

config tool:add restriction for some parameters

---

misc/config_tools/launch_config/launch_cfg_gen.py

add vmname in generated launched script by a comment
Tracked-On: #7410

config tool:add vmname in launch script

---

misc/config_tools/configurator/src/pages/Config/Scenario.vue

Add alert when importing an non-exist scenario file
Tracked-On: #7413

config-tools: add alert for non-exist file

---

misc/config_tools/board_inspector/board_inspector.py

1.Temporarily store the log in the form of tempfile,
and the temporary file will be deleted after the summary log information is displayed.
2.Now, the logs will be printed when they generated as well.

config-tools:Board Inspector Behaviors Improvement

---

misc/config_tools/configurator/pyodide/loadBoard.py
misc/config_tools/configurator/src/pages/Config.vue
misc/config_tools/configurator/src/pages/Welcome/NewConfiguration.vue
misc/config_tools/scenario_config/jsonschema/converter.py

This PR fixes 4 bugs as indicated in commit messages.

Configurator bug fixes

---

misc/config_tools/board_inspector/extractors/95-usb.py
misc/config_tools/launch_config/launch_cfg_gen.py
misc/config_tools/schema/VMtypes.xsd
misc/config_tools/schema/config.xsd

Support detecting connected usb devices in board_inspector and list them
in the usb mediator configuration menu.
Tracked-On: #7424

misc: configurator: Config usb mediator devices in dropdown list

---

misc/config_tools/configurator/packages/configurator/src/pages/Config.vue

Step 2 should be available after board is imported/created, and step
3 should follow step 2.
Tracked-On: #7435

misc: configurator: Disable steps until prior step completed

---

hypervisor/arch/x86/guest/vm.c

when SSRAM regions are assigned to service VM
to support virtulization of SSRAM for post-launched
RTVMs, service VM need to access all SSRAM regions
for management, typically, service VM does data
cleanup in SSRAM region when it is reclaimed from
a shutdown RTVM.
This patch update memory type from UC(by default)
to WB.
Tracked-On: #7425

hv: update SSRAM regions EPT memory type to WB

---

misc/config_tools/build.cmd
misc/config_tools/configurator/packages/configurator/package.json
misc/config_tools/configurator/packages/configurator/src/lib/acrn.ts
misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/cpu_affinity.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/uiSchemaGenerate.py
misc/config_tools/configurator/yarn.lock

add custom cpu_affinity component

Configurator: add custom cpu_affinity component

---

misc/config_tools/configurator/packages/configurator/src-tauri/src/configurator.rs
misc/config_tools/configurator/packages/configurator/src-tauri/src/main.rs
misc/config_tools/configurator/packages/configurator/src/lib/acrn.ts
misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/Board.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/Scenario.vue
misc/config_tools/configurator/packages/configurator/src/pages/Welcome/NewConfiguration.vue
misc/config_tools/configurator/packages/configurator/src/pages/Welcome/UseExisting.vue

1. when using existing configuration, UI show the existing information.
2. remove launch script when removing post-launched VM.
3. new working folder created with no existing files.
4. automatically minimized.
Tracked-On: #7450

config-tools: bugfix for file related issue in UI

---

misc/config_tools/board_config/board_c.py
misc/config_tools/schema/config.xsd
misc/config_tools/schema/types.xsd
misc/config_tools/static_allocators/clos.py
misc/config_tools/xforms/vm_configurations.c.xsl

1 Unified CACHE_ID type to Hex Format
2 Rewrite policy merge with RDT Class
3 Modify the logic of generate CPU mask
4 Modify the generate logic of vcat config

Refine for RDT

---

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/VUART.vue

misc: configurator: Add vUART widget

---

misc/config_tools/configurator/packages/configurator/src/pyodide.js
misc/config_tools/scenario_config/jsonschema/converter.py

Copy scenrio.json to build directory, and modify the temporary file
to avoid pollution of hypervisor repo.
Tracked-On: #7459

config-tools: modify scenario.json in build directory

---

misc/config_tools/configurator/packages/configurator/package.json
misc/config_tools/configurator/packages/configurator/src-tauri/Cargo.lock
misc/config_tools/configurator/packages/configurator/src-tauri/Cargo.toml
misc/config_tools/configurator/packages/configurator/src/lib/acrn.ts
misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/cpu_affinity.vue
misc/config_tools/configurator/yarn.lock

fix can't save cpu affinity config issue

config_tools: fix can't save cpu affinity config issue

---

devicemodel/Makefile
devicemodel/hw/pci/virtio/vhost.c
devicemodel/hw/pci/virtio/vhost_vsock.c
devicemodel/hw/pci/virtio/virtio.c
devicemodel/hw/pci/virtio/virtio_net.c
devicemodel/include/vhost.h
devicemodel/include/vhost_vsock.h
devicemodel/include/virtio.h

1.  [ACRN: DM: Expose the vhost kernel ioctrl API]
2.  [ACRN: DM: Implement the vhost vsock]
3.  [ACRN: DM: Fix the virtio negotiated features bug.]

Implement Vsock in ACRN device model

---

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/VUART.vue

The connection label should be consistent with vUART name
Tracked-On: #7455

misc: configurator: Fix minor bug of vUART label error

---

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/Virtio/Console.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/Virtio/Input.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/Virtio/Network.vue
misc/config_tools/configurator/pyodide/loadBoard.py
misc/config_tools/schema/VMtypes.xsd

The patch series adds virtio devices(Input/Network/Console) widget
according to the new design.

config_tools: add virtio devices widget

---

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/IVSHMEM_REGION.vue

Fix configurator build issue introduced by #7483
Tracked-On: #7492

config-tools: fix configurator build issue

---

misc/config_tools/configurator/packages/configurator/src/pages/Config.vue

Added check and error prompt for duplicate names of VM
before save scenario.
Tracked-On: projectacrn#7486

[config_tool] Duplicate VM name

---

misc/config_tools/configurator/packages/configurator/src/pages/Welcome/NewConfiguration.vue

Instead of deleting all files, just remove xml and launch scripts.
Tracked-On: #7495

misc: configurator: remove config files when choosing a working folder

---

misc/config_tools/configurator/packages/configurator/src/pages/Config.vue

After clicking save button, validate settings before writing down
scenario.xml, otherwise broken scenario.xml will be generated.
Tracked-On: #7470

misc: configurator: validate user settings before writing down

---

misc/config_tools/configurator/packages/configurator/src/pages/Config.vue

When clicking the Save button in UI, the log message is incorrect for
pre-launched VM.
Do not show 'launch script' related message when there is only pre-launched
VMs.
Tracked-On: #7524

config-tools: correct the confirm log

---

misc/config_tools/build.cmd
misc/config_tools/configurator/packages/configurator/package.json
misc/config_tools/configurator/packages/configurator/src/main.js
misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/CAT.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/CAT/HexBlockRangeSelector.vue
misc/config_tools/configurator/packages/vue-json-schema-form/vue3/vue3-core/src/components/Widget.js
misc/config_tools/configurator/pyodide/loadBoard.py
misc/config_tools/configurator/yarn.lock
misc/config_tools/schema/config.xsd

Add custom CAT widget for acrn-configurator

config_tools: add custom CAT widget

---

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/CAT.vue

add set default function for cat widget

config_tools: add set default function for cat widget

---

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/IVSHMEM_REGION.vue

Refined region name issue in IVSHMEM_REGION.vue.
Tracked-On: #7553

[config_tool] IVSHMEM changes to Configurator 05.06 build

---

devicemodel/hw/platform/vssram/vssram.c

In ACRN HSM driver, only MMIO type is supported
when doing EPT unmap.
This patch walk around above issue to unmap
SSRAM region before doing EPT mapping.
Tracked-On: #7563

dm: fix SSRAM region unmap failure issue

---

misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
misc/config_tools/schema/checks/cpu_assignment.xsd

The current UI display "report on" message, it's not by design, so this
patch remove these message.

misc: CPU affinity error message cleanup

---

misc/config_tools/configurator/packages/configurator/src/components/common/Footer.vue
misc/config_tools/configurator/packages/configurator/src/lib/acrn.ts
misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/CAT.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/CAT/HexBlockRangeSelector.vue
misc/config_tools/configurator/pyodide/validateScenario.py
misc/config_tools/schema/checks/cpu_assignment.xsd

1. config_tools: add vcat support for configurator
2. config_tools: remove footer version link
3. config_tools: fix service vm cat settings

config_tools: add vcat support for configurator

---

misc/config_tools/configurator/pyodide/loadBoard.py

config_tools: fix load board issue

---

misc/config_tools/static_allocators/clos.py

1 add match interface for RDT policy
2 refine CDP mode

RDT code refine

---

misc/config_tools/configurator/packages/configurator/src/lib/acrn.ts
misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/CAT.vue
misc/config_tools/configurator/pyodide/loadBoard.py

1. config_tools: refine configurator CAT checkbox data binding
2. config_tools: fix data loss issue method 1
3. config_tools: fix cpu_affinity cannot display issue

config_tools: refine configurator CAT checkbox data binding

---

misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/CAT.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/IVSHMEM_REGION.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/VUART.vue

Add tooltips for vUART, IVSHMEM and CAT.
Other tiny fix.
Tracked-On: #7639

config-tools: add tooltips

---

misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/CAT.vue
misc/config_tools/configurator/pyodide/loadBoard.py

1. config_tools: check cat capability info in cat info parser 
2. config_tools: show scenario data error when load scenario
3. config_tools: fix service vm CAT data not complete issue

config_tools: fix service vm CAT data not complete issue

---

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/CAT.vue

filter all pre launched pcpu for service vm's cat data

config_tools: filter all pre launched pcpu for service vm's cat data

---

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/CAT.vue

add notice message for RDT checkbox

config_tools: add notice message for RDT checkbox

---

misc/config_tools/board_inspector/board_inspector.py

Completed the five log level information in help output list.
Tracked-On: #7654

board_inspector:refine board_inspector.py

---

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/CAT.vue
misc/config_tools/schema/VMtypes.xsd

remove default setting and refine statement.
Tracked-On: #7674

config tool: refine cpu_affinity

---

misc/config_tools/board_inspector/board_inspector.py

changed default log level into "warning",
and fixed errors in warning log summary.
Tracked-On: #7653

board_inspector: refine board_inspector.py

---

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/VUART.vue

use v-html to display the HTML.
Tracked-On: #7639

config-tools: tiny fix for tooltip

---

misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/Board.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/CAT.vue

1. config_tools: update CAT data when board updated
1. config_tools: fix delete vm failed issue
1. config_tools: reformat Board.vue
1. config_tools: show confirm message when user deselecting checkbox in cat widget
1. config_tools: fix when CAT checkbox data missing, ui will hang up in hv.advanced issue

Fix ui will hang in hv.advanced when CAT checkbox data is missing

---

misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/Board.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/CAT.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/CAT/HexBlockRangeSelector.vue

1. config_tools: delete the old board file when the new board file is imported successfully.
1. config_tools: disallowed user set CAT CLOS_MASK to 0
1. config_tools: CAT is no longer unchecked when CDP is unchecked
1. config_tools: fix vmNameChange event never called issue

disallowed user set CAT CLOS_MASK to 0

---

misc/config_tools/schema/types.xsd

doc: edit RDT_ENABLED tooltip

---

misc/config_tools/scenario_config/upgrader.py

Now in scenario XML file:
1.The vm memory node info has been transformed into a new form(
e.g. hpa_region, start_hpa, size_hpa, and size).
2.The clos node info will be dropped during the upgrade process,
and users can see the discard waring info.
3.During the upgrade process, the node "RELOC" will be renamed
to "RELOC_ENABLED", the node "MULTIBOOT2" will be renamed to
"MULTIBOOT2_ENABLED".
Tracked-On: #7660

config_tools: refine issues in the upgrader

---

doc/getting-started/overview_dev.rst

- Align with new Configurator design, and use of Configurator instead of editing predefined XMLs

doc: Update Configuration and Development Overview

---

misc/config_tools/static_allocators/clos.py

Merge master RDT refine patch to 3.0:
1 add match interface for RDT policy
2 refine CDP mode

Merge RDT refine patch to 3.0

---

hypervisor/quirks/smbios.c

Reserve SMBIOS table region in ve820 to prevent kernel from using it.
it.
Tracked-On: #7735

[release_2.5] hv: reserve smbios table region in ve820

---

misc/config_tools/configurator/packages/configurator/src/lib/acrn.ts
misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
misc/config_tools/configurator/pyodide/validateScenario.py

This reverts commit 68636087a6435a4f773da6621ddb57c6c9782205.

Revert "config_tools: add SyntacticValidationStage before save scenario"

---

misc/config_tools/schema/VMtypes.xsd

Improve description and title for vUART connection end point VM name

---

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/cpu_affinity.vue

add * in cpu_affinity widget first line of pcpu config

config_tools: add * in cpu_affinity widget first line of pcpu config

---

misc/config_tools/schema/checks/cpu_assignment.xsd

Remove duplicate assertion and improve message text.
Tracked-On: #7745

configurator: Remove duplicate vCPU assignment error message

---

devicemodel/hw/mmio/core.c
devicemodel/hw/pci/virtio/vhost_vsock.c

This PR contains fixes to two coding style issue.

[Release_3.0] Two coding style fixes

---

devicemodel/hw/vdisplay_sdl.c

Fix some typos in output logs.
Tracked-on: #7747

dm: vdisplay: fix comment typos.

---

misc/config_tools/configurator/packages/configurator/src-tauri/src/configurator.rs
misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/cpu_affinity.vue

1. config_tools: filter out non-existing history path
2. config_tools: fix UI cpu_affinity cpu_id validation logic

config_tools: fix UI cpu_affinity cpu_id validation logic 

---

devicemodel/hw/mmio/core.c
devicemodel/hw/pci/virtio/vhost_vsock.c

This PR backports two coding style fixes from release_3.0.

[master branch] Two coding style fixes

---

misc/services/life_mngr/Makefile
misc/services/life_mngr/uart.c

fix two minor bugs
Tracked-On: #7215

Release 3.0

---

doc/tutorials/acrn_configuration_tool.rst
doc/tutorials/upgrading_configuration.rst

- Update to reflect configuration changes for v3.0

doc: Update Intro to ACRN Configuration

---

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/TabBox.vue

add error icon for hypervisor tab

config_tools: add error icon for hypervisor tab

---

misc/config_tools/configurator/packages/configurator/src/pages/Config.vue

hide syntactic error message from configurator ui

config_tools: hide syntactic error message from configurator ui

---

doc/tutorials/board_inspector_tool.rst

- Update prerequisites, commands, command-line options for v3.0 release

doc: Update Board Inspector

---

misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/Scenario/NewScenario.vue
misc/config_tools/configurator/packages/configurator/vite.config.js

1. config_tools: hide severity from error message 
2. config_tools: add document link for create scenario modal
3. config_tools: open scenario document in new window

config_tools: hide severity from error message 

---

misc/config_tools/launch_config/launch_cfg_gen.py
misc/config_tools/static_allocators/gpa.py
misc/config_tools/xforms/lib.xsl
misc/config_tools/xforms/pci_dev.c.xsl
misc/config_tools/xforms/vm_configurations.c.xsl

This patch add PCI config for PCI vUART and remove the PCI vUART config
of hv config which conflict with launched scenario Device ID.

misc: fix PCI vUART issue

---

misc/config_tools/configurator/packages/configurator/src/lib/acrn.ts
misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/CAT.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/CAT/HexBlockRangeSelector.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/cpu_affinity.vue

config_tools: refine cat widget

---

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/Virtio/Console.vue

add default value for virtio console

config_tools: add default value for virtio console

---

misc/config_tools/configurator/packages/configurator/src/assets/css/index.scss

fix configForm character display issue

config_tools: fix configForm character display issue

---

doc/introduction/index.rst

What is ACRN introduction dives from the high level architecture
directly into the device model and device passthrough information.  It
gets pretty deep relatively quickly. Move the Static Configuration Based
on Scenarios section came earlier in the document.

doc: rearrange "What is ACRN" for better presentation

---

doc/tutorials/acrn_configurator_tool.rst

- Update Debian file name
- Fix typos

doc: Update Configurator UI doc

---

doc/getting-started/getting-started.rst

1. add link for ACRN configurator
2. update deb name.
3. update the patch of launch script.
4. update Python package dependencies.

doc: update GSG

---

doc/release_notes/release_notes_3.0.rst

doc: update release notes for v3.0

---

doc/release_notes/release_notes_3.0.rst

doc: more edits for final 3.0 release notes

---

doc/conf.py

doc: add 3.0 release docs to menu choice

---

doc/_templates/layout.html

doc: add 3.0 to /latest header note

---

doc/release_notes/release_notes_3.0.rst

doc: update release notes 3.0 year

---

doc/release_notes/release_notes_3.0.rst

doc: add link to configurator debian package in tag assets

---

debian/control

update debian control file typo issue is a missing ,
Tracked-On:projectacrn#6688

[Release_3.0]update debian control file typo issue is a missing ,

---

misc/config_tools/board_inspector/legacy/board_parser.py

load msr driver if not found cpu number.

config_tools: update loading msr driver logic

---

misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm.vue
misc/config_tools/configurator/packages/configurator/src/pages/Welcome/NewConfiguration.vue

1. fix dirty form data.
2. fix the new working folder cancel button.

config_tools: bugfix for configurator

---

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/Virtio/Input.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/Virtio/Network.vue

Apply pattern checks to network interface name and virtio input id. Report error if regex doesn't match.

config_tools: apply pattern check to virtio devices

---

debian/control
doc/getting-started/getting-started.rst

modify elementpath version ==2.5.0
Tracked-On:projectacrn#6688

[Release_3.0]modify elementpath version ==2.5.0

---

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/Virtio/Console.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/Virtio/Input.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/Virtio/Network.vue

1. left-align the plus icon in the virtio devices so that they match the alignment in the IVSHMEM widget.
2. add tooltips for virtio network, input and console.

config_tools: left-align plus icon and add tooltips for virtio devices

---

devicemodel/hw/pci/virtio/vhost_vsock.c
devicemodel/hw/pci/virtio/virtio_net.c

Porting the missed commit from rlease_3.0 to the master branch.

Porting the missed commit to the master branch

---

misc/config_tools/configurator/packages/configurator/src/lib/acrn.ts

fix CAT data can not be load back issue
Signed-off-by: Weiyi Feng <fwy1998@gmail.com>

config_tools: fix CAT data can not be load back issue

---

misc/config_tools/configurator/packages/configurator/src/pages/Config/Scenario.vue

fix warning message when users attempt to create a new scenario or import an existing scenario, for an existing configuration
Tracked-On: #7898
Signed-off-by: Chuang-Ke chuangx.ke@intel.com
Reviewed-by: Junjie Mao junjie.mao@intel.com

config_tools: show warning message when users attempt to create a new scenario

---

doc/asa.rst

Update security advisory for release_3.0.1

doc: update security advisory for 3.0.1 release

---

doc/release_notes/release_notes_3.0.1.rst

doc: add v3.0.1 release notes

---

misc/config_tools/launch_config/launch_cfg_gen.py

The current launch script allocate bdf for ivshmem by itself and have
not get bdf from scenario.
This patch refine the above logic and generate slot by user settings.

misc: refine slot issue of launch script

---

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/IVSHMEM_REGION.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/VUART.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/Virtio/Console.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/cpu_affinity.vue
misc/config_tools/schema/types.xsd
misc/config_tools/static_allocators/memory_allocator.py

1. apply vBDF pattern check to vUART and ivshmem.
2. add tooltips for CPU affinity and a tiny fix for virtio console device.
3. degrade the log level to debug for hugepage check.

config_tools: bugs fix for configurator

---

devicemodel/Makefile
devicemodel/core/iothread.c
devicemodel/core/main.c
devicemodel/hw/pci/virtio/vhost.c
devicemodel/hw/pci/virtio/virtio.c
devicemodel/hw/pci/virtio/virtio_block.c
devicemodel/include/iothread.h
devicemodel/include/virtio.h

add iothread support for virtio-blk

add support for iothread

---

misc/config_tools/configurator/packages/configurator/src/pages/Config.vue

[config_tool] vUART and IVSHMEM widgets don't generate address
Tracked-On: #7942

vUART and IVSHMEM widgets don't generate address

---

doc/tutorials/rdt_configuration.rst

Add some clarification and updates for 3.1

doc: update rdt config tutorial

---

doc/getting-started/getting-started.rst

While we're waiting for a more complete list of specific package version
requirements, let's fix the xmlschema and elementpath version mismatch
now.

doc: update GSG version for xmlschema

---

doc/user-guides/acrn-shell.rst

ACRN hypervisor shell has been improved to be bash-like shell, so update
its usage

doc: update hypervisor shell usage

---

doc/getting-started/getting-started.rst

Update Getting Started Guide to clarify and improve descriptions of
steps, including adding example commands instead of just describing
them, adding more information about system requirements, making certain
steps explicit, squash the long list of packages to install into fewer
lines, and more.
Move cloning ACRN hypervisor and kernel earlier in the instructions
(anticipating use of a requirements.txt coming from the repo).
[External_System_ID] ACRN-9285

doc: clarify and improve GSG

---

misc/config_tools/schema/config.xsd

Add a reference to the intel.com white paper on MCE avoidance to the
Disable MCE Workaround configuration option
Tracked-On: #7978

doc: add MCE check avoidance explanation

---

misc/sample_application/image_builder/create_image.sh
misc/sample_application/image_builder/setup_hmi_vm.sh
misc/sample_application/image_builder/setup_rt_vm.sh

1. Create a build directory for store images so that the git will not trace the
images.
2. Disable more systemd server in RT-VM in case the error output in
console.
3. Add the make sampleapplication command in the scripts.

ACRN: Scripts: Modify the create images scripts

---

misc/sample_application/image_builder/create_image.sh
misc/sample_application/image_builder/setup_rt_vm.sh

Add the copy RT kernel for the create image scripts.

ACRN:SampleApplication: Copy RT kernel scripts

---

doc/tutorials/rdt_configuration.rst

Improve explanation of the Real-time vCPU option checkbox.
[External_System_ID] ACRN-9307

doc: update rdt doc with real-time vCPU option clarification

---

misc/config_tools/schema/VMtypes.xsd

doc: add tooltip for real-time vCPU option checkbox

---

misc/sample_application/image_builder/create_image.sh

We need set uio when the hmi and rt user VM setup, so creat a rc.local
in the '/etc' and run it after system setup.

misc: add a uio init setting

---

misc/sample_application/image_builder/create_image.sh
misc/sample_application/image_builder/setup_hmi_vm.sh
misc/sample_application/image_builder/setup_rt_vm.sh

1. Delete the generated images if the create scripts failed.
2. Enable root user login on GUI.
3. Enable systemd service in case there are many error logs.

SampleApplication: Update the image create scripts

---

misc/sample_application/image_builder/create_image.sh

1.Add the dhclient for the VM images.
2.Disable the schroot data mapping.

SampleApplication: Add dhclient command

---

doc/getting-started/sample-app.rst

doc: fix typos in sample app guide

---

doc/getting-started/sample-app.rst

1. Add the move iasl binary to the /usr/sbin directory.
2. Modify login RT_VM user to root user.

ACRN: Doc: Modify the SampleApplication document

---

misc/sample_application/uservm/histapp.py

Improve graph labels and align histogram bars on x-axis labels, add a n= value for number of samples counted.
Tracked-On: #8025

Fix sample app histogram display

---

misc/sample_application/uservm/histapp.py

Improve graph labels and align histogram bars on x-axis labels
Add n= value to show it's not a static image.
Tracked-On: #8025

Fix sample app histogram display release_3.1

---

misc/sample_application/uservm/histapp.py

Improve graph labels and align histogram bars on x-axis labels
Add n= value to show it's not a static image.
Tracked-On: #8025

Fix sample app histogram display sample-application

---

misc/config_tools/launch_config/launch_cfg_gen.py

The current code use cpu_id in scenario xml and use apic_id of the pCPU
in the launched script, this confuses the user, especially the same name
"cpu_affinity" is used for these script.
So this patch add some comment to launched script to explain the
relationship between cpu_id and apic_id.

misc: add cpu details to launch script

---

misc/config_tools/configurator/packages/configurator/src/pages/Config/NewBoard.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/Scenario/NewScenario.vue

fix: 1. popup window won't be close when user click background
2.close popup window do cancel function related
Tracked-On: [#7991](https://github.com/projectacrn/acrn-hypervisor/issues/7991)

[Workshop] Configurator create scenario popup window disappear sometimes

---

misc/sample_application/image_builder/create_image.sh
misc/sample_application/image_builder/setup_hmi_vm.sh
misc/sample_application/uservm/histapp.py

1.Use desktop profie to repalce the default profile.
2.Change the flask images path as a absolute path.
3.Add the ssh config function to enable the ssh.
Signed-off-by: Liu Long long.liu@linux.intel.com

SampleApplicaton: Change schroot data mapping to desktop

---

devicemodel/hw/pci/virtio/virtio_i2c.c
devicemodel/include/virtio.h

Update virtio-i2c driver according to virtio spec v1.2

Update virtio-i2c driver according to virtio spec v1.2

---

doc/getting-started/sample-app.rst

doc: fix typo in sample app doc

---

doc/release_notes/release_notes_3.1.rst

doc: draft of 3.1 release notes

---

doc/getting-started/getting-started.rst
doc/tutorials/acrn_configurator_tool.rst
misc/config_tools/configurator/requirements.txt
misc/config_tools/requirements.txt

Modified misc/config_tools/configurator/requirements.txt
and misc/config_tools/requirements.txt. Updated getting-started.rst
and acrn_configurator_tool.rst.
Tracked-On: #7975
Signed-off-by: zihengL1 <ziheng.li@intel.com>

config-tools: modified requirements.txt and update GSG

---

doc/tutorials/acrn_configurator_tool.rst
misc/config_tools/configurator/requirements.txt
misc/config_tools/requirements.txt

Modified misc/config_tools/configurator/requirements.txt
and misc/config_tools/requirements.txt. Updated getting-started.rst
and acrn_configurator_tool.rst.
Tracked-On: #7975
Signed-off-by: zihengL1 <ziheng.li@intel.com>

config-tools: modified requirements.txt and update configurator build doc

---

doc/static/acrn-custom.css

doc: tweak CSS to outdent numbered step icons

---

devicemodel/hw/platform/vssram/vssram.c

In ACRN HSM driver, only MMIO type is supported
when doing EPT unmap.
This patch walk around above issue to unmap
SSRAM region before doing EPT mapping.
Tracked-On: #7563

[release_3.1] dm: fix SSRAM region unmap failure issue

---

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/cpu_affinity.vue
misc/config_tools/configurator/pyodide/loadBoard.py
misc/config_tools/launch_config/launch_script_template.sh
misc/config_tools/scenario_config/jsonschema/converter.py
misc/config_tools/schema/VMtypes.xsd
misc/config_tools/schema/config.xsd

Merge some patchs which already in release_3.1 to master.

config_tools: cpu affinity and UC lock default value

---

doc/release_notes/release_notes_3.1.rst

doc: update 3.1 release notes draft

---

doc/release_notes/release_notes_3.1.rst

doc: v3.1 release notes draft update

---

doc/getting-started/sample-app.rst

Clarify commands that needed to be run on the target and not the dev
system

doc: clarify sample app instructions

---

misc/config_tools/schema/checks/cpu_assignment.xsd
misc/config_tools/schema/checks/vm_memory.xsd

Improve consistency and clarity in CPU and memory size assert messages.

config: update CPU and memory size assert messages

---

misc/config_tools/scenario_config/config_summary.py

Generate config_summary.py script in misc/config-tools/scenario_config
directory. This script can extract important information from scenario
and board xml to summary it into RST format text.
Tracked-On: #8063

config-tools: generate config_summary.rst

---

misc/services/life_mngr/uart.c

Revise try_receive_message_by_uart to read one char from uart one time.
With this implementation each char can be checked. This can be used to
address the following 2 problems:
1) nosie data: it is found that there is noise data in the uart from
guest VM when guest startup.
2) split multiple commands
Tracked-On: #8111

misc: life_mngr: revise try_receive_message_by_uart

---

doc/developer-guides/hld/hld-splitlock.rst
doc/tutorials/rtvm_performance_tips.rst
doc/tutorials/using_grub.rst

doc: Update references to scenario options doc

---

devicemodel/hw/pci/xhci.c

Fix #8114 
Signed-off-by: Marius Rodi <marius.rodi@linutronix.de>

devicemodel: hw: pci: xhci: Remove unnecessary condition 

---

misc/config_tools/scenario_config/upgrader.py

There is some issue when use upgrade to update some old xml version to release_3.1, this patch modify the upgrade script to fix these issue.

misc: refine upgrade script

---

devicemodel/hw/vga.c

To avoid assertions in devicemodel, remove all the assert() in vga.c, use print error message to check errors.
Tracked-On: #8125

dm: vga: remove all the assertion.

---

doc/tutorials/enable_ivshmem.rst
doc/tutorials/vuart_configuration.rst

The issue has been fixed in v3.1.

doc: Remove note about v3.0 Configurator issue

---

hypervisor/arch/x86/tsc.c

HPET is used to calibrate the tsc frequency if system fails to get the accurate frequency from CPUID 0x15. But on some platforms (for example: the emulated ACRN on QEMU) HPET is not started by default, which causes the failure of calibration TSC by HPET.
Tracked-On: #8113

hv: tsc: start HPET counter before calibration

---

doc/tutorials/rdt_configuration.rst

doc: Minor edit to RDT tutorial

---

doc/tutorials/cpu_sharing.rst

doc: Update CPU sharing tutorial

---

doc/getting-started/getting-started.rst
misc/services/acrn_manager/README.rst

submit the some errors about
(1)	Service VM deb ->  *5.10.115*.deb Change to *5.15.44*.deb
(2)	Ubuntu version ->   20.04.4 change to 20.04.5

GSG document revision

---

misc/services/acrn_manager/README.rst

Improve the documentation of "acrnctl and acrnd".

improve the document of acrnd

---

devicemodel/hw/pci/virtio/virtio_block.c

Fix the truncate issue for virtio block parameter.

dm: virtio-blk: fix parameter err

---

misc/config_tools/data/adl-asrock/adl-asrock.xml
misc/config_tools/data/adl-asrock/shared.xml

Add configuration files for ASRock system, with Intel® 12th Gen Core™ CPU (formerly known as Alder Lake) and 32G memory.
Tracked-On: #8163

Add configuration files for ASRock system

---

doc/tutorials/gpu-passthru.rst

Add one more constraint for ASRock platform in GVT-d tutorial

[doc]GVT-d tutorial update based on ASRock platform constraint

---

doc/tutorials/gpu-passthru.rst

doc: Minor editorial update to GVT-d tutorial

---

misc/services/acrn_manager/README.rst

- Update broken link and minor editorial changes
Tracked-On: #8172

doc: Update acrnctrl readme

---

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/CAT/HexBlockRangeSelector.vue

let vCAT chunk no longer  fixed-drag
Tracked-On: #8187

[config_tool] vCAT widget behavior

---

doc/developer-guides/hld/hv-hypercall.rst

doc: Editorial changes to hypercall hld

---

misc/config_tools/configurator/packages/configurator/src/lib/acrn.ts
misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/CAT.vue

use better wording instead the message when CAT not supported
Tracked-On: #8136

[config_tool] Message when CAT not supported

---

doc/getting-started/sample-app.rst

update the ubuntu version info : 20.04.04->20.04.5

doc: Update the version infomation of sample app guide

---

doc/getting-started/sample-app.rst

upgrade the document description about sample application guide.
Ubuntu 20.04.04->Ubuntu 20.04.5

doc: Upgrade the ubunutu version of sample app guide

---

doc/tutorials/enable_s5.rst

- Update the S5 tutorial to align with new template and GSG scenario

doc: Update S5 tutorial

---

doc/conf.py

doc: add 3.1 release docs to menu choice

---

doc/release_notes/release_notes_3.1.rst

doc: Update v3.1 release notes

---

doc/_templates/layout.html

doc: add 3.1 to /latest header note

---

devicemodel/core/main.c
devicemodel/core/vmmapi.c
devicemodel/hw/pci/virtio/virtio.c
devicemodel/include/public/hsm_ioctl_defs.h
devicemodel/include/vmmapi.h

dm: add support for asyncio

---

doc/developer-guides/hld/hv-interrupt.rst

doc: Fix typos in interrupt hld

---

doc/user-guides/acrn-dm-parameters.rst

doc: Editorial changes to DM params doc

---

doc/tutorials/acrn_configurator_tool.rst

doc: Editorial changes to Configurator doc

---

doc/getting-started/sample-app.rst

doc: Editorial changes to sample app guide

---

misc/config_tools/static_allocators/gpa.py

Prevent allocator to allocate PCI bus mmio windows to other devices.
Tracked-On: #8191

config-tools: reserve the secondary PCI bus mmio windows

---

doc/getting-started/getting-started.rst

ubuntu version from 22.04.4 to 22.04.5.
so update the ubuntu kernel version from 5.13.0-30-generic  to 5.15.0-46-generic

revision the GSG document of ubuntu kernel version

---

misc/config_tools/board_inspector/extractors/70-device-classes.py
misc/config_tools/board_inspector/extractors/90-sorting.py
misc/config_tools/board_inspector/extractors/helpers.py

This method gets connected displays and adds them as child nodes to a corresponding graphics card.

config-tools: add topology extract_display

---

doc/getting-started/getting-started.rst

We have real fix in [PR#8222](https://github.com/projectacrn/acrn-hypervisor/pull/8222), thus remove the workround in document.
Tracked-On:8155

doc: Modify the tqdm package problem in the GSG document

---

doc/tutorials/docbuild.rst

Update instructions for newer versions of the PyPI tools and doxygen.

doc: update doc build tutorial

---

misc/config_tools/board_inspector/legacy/misc.py

Little fix of board_inspector.
Tracked-On: #8235

config_tool: bdf of ioport serial port

---

misc/services/life_mngr/life_mngr_win.c

Permit life_mngr in windows to assign the VM name which configure in scenario XML.
Tracked-On: #8051

life_mngr: permit life_mngr in windows to assign VM name

---

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm.vue
misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/Virtio/GPU.vue
misc/config_tools/launch_config/launch_cfg_gen.py
misc/config_tools/scenario_config/upgrader.py
misc/config_tools/schema/VMtypes.xsd
misc/config_tools/schema/checks/virtio_devices.xsd
misc/config_tools/schema/config.xsd

- Support "window" and "full screen" mode
- "Window" mode contains resolution and offsets
- "Full screen" mode contains monitor ID

config-tools: support virtio gpu configuration in UI

---

doc/scripts/configdoc.xsl

Custom attributes in the XML schema, such as `applicable-vms` and `views`, are designed to recursively inherit those of the parent. Thus, the effective attribute of an element should be derived by its lowest ancestor that has that attribute explicitly defined. Looking up only one level would not be sufficient.
This patch updates the `configdoc.xsl` to derive the effective attributes properly so that icons in the generated doc properly reflects what is specified in the schema. Addresses ACRN-7347

doc: fix views and applicable VMs label handling in config option doc

---

doc/getting-started/getting-started.rst
misc/config_tools/requirements.txt

doc: Create a requirements.txt for python package on GSG

---

doc/getting-started/getting-started.rst

doc: update missed changes to Ubuntu 22.04

---

doc/getting-started/sample-app.rst
misc/sample_application/image_builder/create_image.sh
misc/sample_application/image_builder/setup_hmi_vm.sh

changes to 22.04 on sample application guide document, and update the download URL of ubuntu.
Tracked-On: #8269

doc: update changes to 22.04 on sample app guide

---

doc/getting-started/sample-app.rst

doc: Upgrade RT kernel to 5.15 in sample app guide

doc: Upgrade RT kernel to 5.15 in sample app guide

---

misc/config_tools/data/adl-asrock/adl-asrock.xml

This patch update the board.xml for ASRock.

misc: update ASRock board XML

---

misc/config_tools/board_inspector/extractors/95-usb.py

Board inspector may throw an error if a usb device is unplugged or disconnected while extracting usb device information. Print out the debug message and continue parsing.
Tracked-On: #8325
Signed-off-by: yuchuyang <yu-chu.yang@intel.com>

config-tools: board inspector does not exit if a usb device is unplugged

---

hypervisor/debug/uart16550.c

to enable early print output by pci uart, which has mmio address above 4G, add the early pagetable map for the MMIO range.
we make an assumption that only map it with 2MB page, since platform with 39bit memory width have no 1G huge page feature and we cannot get the capacity at runtime, since it is a very early code stage.
v2->v1:
1. add hva2hpa_early
2. add process when *pdpte is not present
Reviewed-by: fei1.li <fei1.li@intel.com>

hv: support for pci uart with high mmio

---

doc/release_notes/release_notes_3.0.2.rst

doc: create 3.0.2 release notes

---

doc/getting-started/getting-started.rst

Signed-off-by: szhen11 <shuang.zheng@intel.com>

doc: update GSG to use debuild to build ACRN packages

---

doc/getting-started/getting-started.rst

doc: update GSG with corrections

---

doc/asa.rst

Update security advisory for v3.0.2 release.

doc: update asa.rst for v3.0.2 release

---

doc/asa.rst

Updating the asa.rst updates for security issues

doc: add asa updates for 3.0.2 release

---

doc/release_notes/release_notes_3.0.2.rst

doc: add 3.0.2 release notes to master branch

---

doc/getting-started/getting-started.rst

1.modify the board inspector name
2.add sudo before reboot (user: acrn)
Signed-off-by: Min Yang <minx.yang@intel.com>

doc: modify getting-started.rst:

---

doc/getting-started/getting-started.rst

doc: update GSG to reflect release 3.2 changes

---

doc/getting-started/sample-app.rst

1. update hypervisor and kernel version to release_3.2
2. modify debian build command
3. remove use of USB stick to copy files from development computer to target (only use scp)
Signed-off-by: Min Yang <minx.yang@intel.com>

doc: update sample-app version &command to match release_3.2

---

CODEOWNERS

update CODEOWNERS in release_3.2

---

CODEOWNERS

Add jianjun to DM maintainer list.
Tracked-On:#5581

update CODEOWNERS for DM maintainer

---

misc/config_tools/scenario_config/config_summary.py

Currently, Configurator load fail because it needs to download RstCloth related packages. This patch defines Doc class to replace RstCloth library to fix this issue.
Tracked-On: #8395

config_tools: replace RstCloth library with class.

---

hypervisor/arch/x86/sgx.c

This patch refactors partition_epc() to make the code easier to understand, also fixes the maybe-uninitialized warning for gcc-13.
Initializing 'vm_config' to get_vm_config(0) is okay here as scenario validator ensures CONFIG_MAX_VM_NUM to be always larger than 0.
Tracked-On: #8413

hv: sgx: refactor partition_epc()

---

devicemodel/hw/pci/passthrough.c
devicemodel/hw/pci/virtio/vhost_vsock.c
devicemodel/hw/pci/virtio/virtio_gpu.c
devicemodel/hw/vdisplay_sdl.c
devicemodel/hw/vga.c

Fixes possible null pointer dereference/uninitialized variable/buffer overflow in code

Fix null pointer dereference/uninitialized variable/buffer overflow in code for release_3.2

---

devicemodel/hw/pci/passthrough.c
devicemodel/hw/pci/virtio/vhost_vsock.c
devicemodel/hw/pci/virtio/virtio_gpu.c
devicemodel/hw/vdisplay_sdl.c
devicemodel/hw/vga.c

Fixes possible null pointer dereference/uninitialized variable/buffer overflow in code

Fix null pointer dereference/uninitialized variable/buffer overflow in code

---

doc/getting-started/getting-started.rst

For the v3.2 release, the new packaged configurator is at https://github.com/projectacrn/acrn-hypervisor/releases/download/v3.2/acrn-configurator-3.2.deb

doc: update path to configurator debian package in GSG

---

doc/getting-started/getting-started.rst

update the selected grub menu entry for booting ACRN and reboot command.

doc: update the selected grub menu entry for booting ACRN and reboot command

---

hypervisor/dm/vpci/ivshmem.c

Please check each patches detailed comments.

hypervisor/ivshmem: Fix some ivshmem  bugs/issues

---

CODEOWNERS

Add junjie to hypervisor approver list

Add junjie to hypervisor approver list

---

hypervisor/arch/x86/vtd.c
hypervisor/include/arch/x86/asm/vtd.h

Fix spelling and typo mistakes.
Tracked-On: #8488

hypervisor: Fix spelling and typo mistakes.

---

devicemodel/hw/pci/xhci.c

Host doorbell array write can be asynchronous, so add an async thread which is used to deal doorbell write.
Tracked-On: #8504

dm: add thread for usb doorbell array write

---

devicemodel/core/monitor.c

devicemodel: Fix spelling and grammar mistakes.

---

hypervisor/arch/x86/irq.c
hypervisor/arch/x86/lapic.c
hypervisor/arch/x86/mmu.c

hypervisor: Fix spelling and grammar mistakes.

---

hypervisor/arch/x86/security.c

Restores canary values of stack protector on all APs
if it was configured, instead of generating a new canary
value.
Tracked-On: #8577

hv: restore stack protector canary if it was configured

---

hypervisor/common/sched_prio.c

hv: sched: Fix scheduler priority issue

---

hypervisor/arch/x86/guest/vm.c

Now multiboot modules memory is already reserved from e820 in function `alloc_mods_memory()` and Service VM will not corrupt pre-launched VM modules.
So remove the code of Service VM delayed loading.
Tracked-On: #8652

hv: remove Service VM delayed loading

---

doc/getting-started/sample-app.rst
doc/release_notes/release_notes_3.3.rst

Add release note of v3.3 including new features, known&fixed issues, new in configurator&inspector, doc updates.
Meanwhile, fix one version error in sample application guide.

doc: add release note of v3.3

---

hypervisor/arch/x86/guest/vm_reset.c

Guest VM, such as Linux, may read RST_CNT register before writing to, in this case, ACRN should not always return dummy value.
Tracked-On: #8688

hv: allow guest with the highest severity to read RST_CNT

---

hypervisor/dm/vpci/vpci_bridge.c

GAI Tooling Notice: These contents may have been developed with support from one or more generative artificial intelligence solutions.
This patch is to add doxygen style comments for some elements in vp-dm_vperipheral vpci_bridge module.

doc: add module design for peripheral vpci_bridge device

---

hypervisor/dm/vuart.c
hypervisor/include/dm/vuart.h

GAI Tooling Notice: These contents may have been developed with support from one or more generative artificial intelligence solutions.
This patch is to add doxygen style comments for some elements in vp-dm_vperipheral vuart module.

doc: add module design for peripheral vuart device

---

hypervisor/arch/x86/guest/vmcall.c

Some hypercalls return -ENODEV which should be set into RAX as return value, e.g. HC_ASSIGN_PCIDEV. So, remove the check in vmcall_vmexit_handler() and change return value to -EACCESS if the hypercall is not sent from Service VM or allowed VM.
Tracked-On: #8598

hv: ENODEV should be able to be set into RAX as hypercall return value

---

hypervisor/arch/x86/guest/guest_memory.c

remove unreachable code branch, merge redundant checking.
Tracked-On: #8708

local_gva2gpa_common: optimize code

---

devicemodel/hw/uart_core.c

When guest console is redirected to stdio, Ctrl-c is also passed to guest. Add escape sequence Ctrl-a x to send SIGINT to exit acrn-dm in such case.
Tracked-On: #8731

dm: uart: add escape sequence Ctrl-a x to exit dm

---

CODEOWNERS

I retired from Intel as of Sep 30, 2024

doc: remove me from CODEOWNERS

---

misc/config_tools/launch_config/launch_cfg_gen.py
misc/config_tools/schema/types.xsd

Add missed ivshmem region ID.
Tracked-On: #8645

config_tools: Add ivshmem region ID to launch script

---

hypervisor/dm/vpci/ivshmem.c

GAI Tooling Notice: These contents may have been developed with support from one or more generative artificial intelligence solutions.
This patch is to add doxygen style comments for some elements in vp-dm_vperipheral ivshmem module.

doc: add module design for peripheral ivshmem device

---

hypervisor/boot/guest/bzimage_loader.c
hypervisor/boot/guest/elf_loader.c

hv: fix stac/clac context in get_initrd_load_addr()
