projectacrn/acrn-hypervisor

Makefile, arch/x86/cpu.c, common/hypercall.c
=> decouple hv sw version and api version

arch/x86/cpu.c
=> Call monitor_cap_detect in bsp_boot_init

arch/x86/mmu.c
the variable 'table_present' is redundant
in function(map_mem_region)
=> Remove unnecessary variable in map_mem

Makefile, arch/x86/cpu.c, common/hypercall.c, include/debug/sbuf.h, include/debug/serial.h, lib/sprintf.c
@dongyaozu @anthonyzxu @JasonChenCJ
=> Cleanup: Don't use HV_DEBUG outside debug dir

arch/x86/ept.c, arch/x86/io.c
=> ioreq: only clear vcpu->req when io request needed

arch/x86/guest/vlapic.c, arch/x86/guest/vmsr.c, arch/x86/intr_lapic.c, arch/x86/timer.c, include/arch/x86/guest/vlapic.h, include/arch/x86/lapic.h
=> prepare for Vlapic timer: cleanup

arch/x86/cpu.c, include/debug/assert.h
=> Remove STATIC_ASSERT Macro and replace with standard  _Static_assert

MAINTAINERS
=> update home page information

debug/shell_internal.c, debug/shell_internal.h, debug/shell_public.c
Add cpuid shell command for QA cpuid test
=> hv: shell: add cpuid command

arch/x86/vmexit.c
Guest OS rdtsc/rdtscp doesn't trap into hypervisor, so remove them.
=> remove deadcode of rdtsc_handler/rdtscp_handler

arch/x86/cpu.c, arch/x86/cpuid.c, arch/x86/mmu.c, arch/x86/vmx.c, common/hv_main.c, include/arch/x86/cpu.h, include/arch/x86/cpufeatures.h, include/arch/x86/hv_arch.h, include/arch/x86/msr.h, include/arch/x86/vmx.h
use cpu_has_cap for cpuid related feature/capability detect
use cpu_has_vmx_ept_cap/cpu_has_vmx_vpid_cap for vmx feature/capability detect
=> cpu cpuid/msr feature/capability detect API refine

arch/x86/interrupt.c
- According to Intel SDM 24.9.2,Vol3, should check the
validity of "VM-exit interruption information" before
extracting the vector of interrupt.
=> refine external interrupt VM exit handler

include/arch/x86/timer.h
=> HV: Fix the missing list_head initializaiton

arch/x86/mmu.c
=> HV: correct the handling of MU_MEM_ATTR_READ MMU flag

README.rst
Simplify the previous README and add more information about project
resources.
Fixes: #144
=> doc: add project README

hypervisor/arch/x86/ept.c
- refine EPT violation vmexit handler
- add check for mmio access that spans devices
=>  HV: refine EPT violation VM-exit handler

hypervisor/arch/x86/mmu.c
Check ept rwx misconfigurations when config memory attribute,
if misconfig it will assert.
=> hv: Check ept rwx misconfigurations

devicemodel/core/inout.c
- i/o access whose handler is not registered should
not be allowed.
=> DM: add spanning devices check for i/o access

hypervisor/Makefile, hypervisor/arch/x86/debug/reboot.c, hypervisor/debug/shell_internal.c, hypervisor/debug/shell_internal.h, hypervisor/debug/shell_public.c, hypervisor/include/arch/x86/reboot.h
To trigger warm reboot for debugging.
=> hv: Add reboot shell command

hypervisor/arch/x86/interrupt.c
Exception type is missing when inject a #GP.
GP should be injected even when guest irq disabled.
=> hv: fix general protection injection

devicemodel/Makefile, devicemodel/core/main.c, devicemodel/hw/pci/gvt.c
Enable graphics virtualization GVT-g
Signed-off-by: Fei Jiang <fei.jiang@intel.com>
=> DM/GVT: implement emulated graphics pci device

hypervisor/arch/x86/guest/instr_emul_wrapper.h, hypervisor/arch/x86/guest/vcpu.c, hypervisor/arch/x86/guest/vlapic.c, hypervisor/arch/x86/vmexit.c, hypervisor/arch/x86/vmx.c, hypervisor/include/arch/x86/guest/guest.h, hypervisor/include/arch/x86/vmx.h
move enum vm_cpu_mode to guest.h
move enum vm_paging_mode to guest.h
replace REAL_MODE with CPU_MODE_REAL
replace PAGE_PROTECTED_MODE with CPU_MODE_64BIT
=> hv: define 4 vcpu modes

Makefile
=> acrn: allow to specify the build output folder

hypervisor/arch/x86/guest/guest.c
h_ptr need update from second page walk
=> guest: quick fix for copy_from/to_vm

hypervisor/arch/x86/guest/vcpu.c, hypervisor/arch/x86/vmexit.c, hypervisor/arch/x86/vmx.c, hypervisor/include/arch/x86/guest/vcpu.h, hypervisor/include/arch/x86/vmx.h
Remove unused API init_cpu.
Control register interface cleanup.
=> Control register handling cleanup

README.rst
Add a mention of the weekly Technical Community meeting to the repo's
README, with links to the meeting information in the wiki.
=> doc: update README technical community meeting

hypervisor/arch/x86/guest/vmcall.c, hypervisor/common/hypercall.c, hypervisor/common/trusty_hypercall.c, hypervisor/include/lib/errno.h
1. hypercall fail would not panic hypervisor.
2. hypervisor don't deal with hypercall fail.
3. hypervisor return the errno to SOS when hypercall failed.
=> ASSERT cleanup for hypercall

devicemodel/hw/platform/ioc.c
This patch implements VM monitor operations including stop/suspend/resume.
For other VM monitor operations(pause/unpause/query), IOC mediator would not
register callbacks for them.
=> IOC mediator: Implement VM monitor operations

devicemodel/hw/pci/passthrough.c
NHLT table is used by some audio driver for topology data, but current
default audio driver doens't depend on it. Disable it by default due
to possible boot failure with different SOS firmware.
=> DM: Disable audio NHLT table by default

devicemodel/hw/platform/rpmb/rpmb_sim.c
=> DM: Fix a potential null-pointer dereference

tools/acrnlog/Makefile
=> Tools:acrnlog: install acrnlog.service

devicemodel/hw/platform/usb_pmapper.c, devicemodel/include/usb_pmapper.h
Additional files updated with an spdx license header
=> license: more spdx license tag updates

devicemodel/samples/apl-mrb/launch_uos.sh
On SBL platform, UOS bsp always starts from realmode, which requires
the support of vSBL.
Boot kernel directly by -U option is no longer supported.
Remove -U option in launch script.
Reviewed-by: Edwin Zhai <edwin.zhai@intel.com>
=> dm: remove -U option in launch script.

devicemodel/hw/pci/passthrough.c
With current implementation:
vm_init_vdevs only handles the negative error code, while passthru_init
returns positive error code when error occurs.
This causes unexpected dm crash since the real error is not being
handled properly.
Change the error code to be negative value in passthru_init because it
is common in Linux kernel to return negative value when error occurs.
v2 -> v3
* add more comments about the reason to convert the return value
v1 -> v2:
* add a wrapper API to convert the error returned from pci_system_init
to the ERROR we defined in DM
* use the defined errno as the return value rather than -1
=> dm: fix the error code issues in passthrough.c

devicemodel/hw/pci/xhci.c, devicemodel/hw/platform/usb_pmapper.c
This patch fix some potential crash issues, like wild pointers access, buffer overflow and etc.
=> DM USB: Fix potential crash issues.

hypervisor/include/common/hypercall.h, hypervisor/include/public/acrn_hv_defs.h
=> doc: fix API documentation misspellings

hypervisor/include/lib/sprintf.h, hypervisor/lib/sprintf.c
unsigned long long--> uint64_t
long long --> int64_t
=> hv:replace unsigned long long with uint64_t

doc/howtos/process/graphviz.rst, doc/howtos/process/images/boot-flow.dot, doc/howtos/process/images/circle-square.dot, doc/howtos/process/images/gaspump.dot, doc/howtos/process/images/node-shape-edges.dot, doc/howtos/process/images/record.dot
Add some practical examples and pointers to additional information about
using graphviz.
=> doc: add some docs about graphviz for drawings

doc/howtos/process/docbuild.rst
=> doc: add graphviz installation instructions

devicemodel/core/main.c
when add/create vcpu failed, before it just exits,
and the resource will not released; now if failed,
let DM release the resource.
=> handle failure when add/create vcpu for a VM in DM

devicemodel/samples/apl-mrb/launch_uos.sh
=> dm: change the android guest selinux policy as permissive

devicemodel/samples/apl-mrb/launch_uos.sh
This reverts commit 4f4e210cd91ca4f3e7869b6cf319192134000371.
=> Revert "dm: change the android guest selinux policy as permissive"

devicemodel/hw/platform/rpmb/rpmb_sim.c
Some APIs of Openssl 1.0 are deprecated in Openssl 1.1+.
Two different API implementations are adaptable to both
Openssl 1.1- and 1.1+.
Fixes: #305
Signed-off-by: Du Min <minx.du@intel.com>
=> DM: Fix build failure with Openssl 1.1+

devicemodel/core/hugetlb.c
check if there are enough free huge pages(1GB & 2MB now) for UOS,
if no, it will try to reserve more pages for UOS.
here are two examples
1. if system has free huge pages: 1 page of 1GB size, 0 page of 2MB.
one UOS need 2GB + 500MB memory, it will try to reserve one more 1GB
page and 250 2MB pages from system. If enough free system memory, it
can succeed.
2. if system has free huge pages: 4 pages of 1GB size, 0 page of 2MB.
one UOS need 2GB + 500MB, 1GB huge pages 4 > 2, it's enough, and 2 pages
left. It will try to reserve 250 2MB pages from system free memory,
if failed, it will try to release 1 of the 2 left 1GB pages. And then
try to reserve 250 2MB pages.
Reviewed-by: Zhao Yakui …
=> improve memory allocation for UOS by hugeTLB mmap

hypervisor/arch/x86/assign.c
Signed-off-by: Li Zhijian <lizhijian@cn.fujitsu.com>
=> HV: remove unused API lookp_entry_by_id()

hypervisor/arch/x86/guest/vpic.c
This patch series change the type of pic pins to be uint8_t and clean up the
uses of integral types, constants and variables by explicitly spelling out
narrowing conversions and unsigned constants related to this type change.
v1 -> v2:
* Rename the number of pins per PIC to NR_VPIC_PINS_PER_CHIP, and the number
of pins of 2 cascading PICs to NR_VPIC_PINS_TOTAL.
* Using "%hhu" instead of "%d" in format string when a pin is expected.
=> HV: vpic: using uint8_t to represent PIC pins

hypervisor/arch/x86/guest/vlapic.c, hypervisor/arch/x86/guest/vlapic_priv.h, hypervisor/arch/x86/lapic.c, hypervisor/include/arch/x86/apicreg.h, hypervisor/include/arch/x86/lapic.h
merge these two structures to lapic_regs
=> hv:merge struct lapic and lapic_regs to lapic_regs

hypervisor/arch/x86/guest/vlapic.c
With current code, the INIT-STARTUP IPI with EXCLUDING_SELF shorthand
cannot be handled.
This patch is to correct hypervisor to emulate IPI with different
delivery_mode & shorthand.
=> HV: bug fix on emulating guest IPI

hypervisor/lib/string.c
- replaced blank spaces with tabs
- deleted some confusing comments
=> HV: coding style cleanup in string.c

hypervisor/lib/string.c
- update 'strtol_deci()' & 'strtoul_hex()'
=> HV: Fix coding style violation of MISRA in string.c

tools/acrntrace/README.rst
-Add acrntrace_format.py usage to README.rst
-Add acrntrace usage to README.rst
-Add acrnanalyze.py to README.rst
=> tools: acrntrace: Updata README.rst

hypervisor/arch/x86/ept.c, hypervisor/arch/x86/vtd.c, hypervisor/boot/dmar_parse.c, hypervisor/bsp/sbl/sbl.c, hypervisor/bsp/uefi/include/bsp/bsp_cfg.h, hypervisor/include/arch/x86/vtd.h
This reverts commit 8d50d40ff8dfed121ab7db86d7c5f5acf840465d.
=> Revert "hv: More changes to enable GPU passthru"

hypervisor/arch/x86/assign.c, hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/ept.c, hypervisor/arch/x86/gdt.c, hypervisor/arch/x86/guest/instr_emul.c, hypervisor/arch/x86/guest/vioapic.c, hypervisor/arch/x86/guest/vlapic.c, hypervisor/arch/x86/guest/vmsr.c, hypervisor/arch/x86/io.c, hypervisor/arch/x86/mmu.c, hypervisor/arch/x86/notify.c, hypervisor/arch/x86/softirq.c, hypervisor/arch/x86/trusty.c, hypervisor/arch/x86/vmexit.c, hypervisor/arch/x86/vmx.c, hypervisor/arch/x86/vtd.c, hypervisor/boot/acpi.c, hypervisor/common/hv_main.c, hypervisor/common/hypercall.c, hypervisor/common/io_request.c, hypervisor/debug/uart16550.c, hypervisor/lib/memory.c, hypervisor/lib/sprintf.c, hypervisor/lib/string.c
Add suffix U to the numeric constant
=> HV:misc:add suffix U to the numeric constant

devicemodel/hw/platform/rpmb/rpmb_sim.c
An immediate reset or power down will cause a loss of write content.
The cause is the data write to disk is at cache within a short
time window before it's synced to storage media.
An explicit fsync() forces to sync the data to storage to prevent
the data loss of such immediate reset.
Signed-off-by: duminx <minx.du@intel.com>
=> DM: Add write sync in fwrite

hypervisor/arch/x86/cpu.c
There are some implicit type conversion in the CPU module,
this voilates MISRA C:2012 required rules.
We walk through each functions of CPU module, update
some variable type and the return value type of
the function, and add 'U/UL' for related const value.
V1-->V2:
Rebase the branch, resolve some conflict.
V2-->V3:
Update commit info for V2.
V3-->V4:
Few updates for fixing error instroduced during
resolving conflict.
=> HV:CPU:Clean up variable type for CPU module

doc/getting-started/apl-nuc.rst
The 'launch_uos.sh' script was updated recently and new lines
added to it. Adjust the 'emphasize-lines' directive accordingly.
=> Documentation: update script higlights in Getting Started Guide

doc/v0.1/release-note.rst
this is the release notes for v0.1,   will add a link to attach change log for people review detail
=> add release notes for v0.1 release

devicemodel/hw/platform/acpi/acpi.c
When XSDT is created by DM, if audio passthru is enabled for
audio device (0:e:0), an entry is added in XSDT that references
the NHLT table. With this fix, NHLT appears in the kernel boot
log for ACPI and entry can be seen in /sys/firmware/acpi/tables/NHLT.
Signed-off-by: Madeeha Javed <madeeha_javed@mentor.com>
=> DM: Fixes issue #592 NHLT is not detected on audio passthru.

hypervisor/arch/x86/guest/instr_emul.c
inst_len with 0 length should be treated as invaild value. This patch move 0 length
check to the begainning of the function and return -EINVAL if inst_len == 0.
=> HV: instr_emul: Return -EINVAL if inst_len equals 0

hypervisor/lib/memory.c
replace blank space indent with tabs
=> HV: code format for memory.c

doc/conf.py, doc/release_notes.rst
Include developer comments, add commit change log
=> doc: update release v0.1 release notes

hypervisor/arch/x86/guest/pm.c, hypervisor/arch/x86/pm.c, hypervisor/include/arch/x86/io.h
The patch fixes integral type related violations on HV pm part.
=> HV: pm: cleanup for misra integral type violations

hypervisor/arch/x86/vmx.c
The patch fixes the issue when SOS can't boot using HV release version.
In current code, the assembly code for "sgdt" & "sidt" is not right.
The operand is output, not input.
Also, current code use "rdmsr" instruction to read MSR_IA32_SYSENTER_CS,
which doesn't sepcify the clobbered registers it uses.
This patch uses API msr_read to read MSR_IA32_SYSENTER_CS.
=> hv: fix bug in some embedded assembly code in vmx

hypervisor/arch/x86/guest/instr_emul.c
There so many ASSERT following the function vie_read_register and vm_get_seg_desc.
It's better to move the ASSERT to those two functions and make the code more
compact.
=> HV: instr_emul: Cleanup ASSERT

hypervisor/arch/x86/io.c, hypervisor/arch/x86/timer.c, hypervisor/arch/x86/virq.c, hypervisor/arch/x86/vmexit.c, hypervisor/common/hv_main.c
to align the data type of parameters
=> HV: coding style cleanup for TRACE_2L & TRACE_4I usage

hypervisor/arch/x86/debug/reboot.c, hypervisor/arch/x86/ept.c, hypervisor/arch/x86/guest/pm.c, hypervisor/arch/x86/guest/vioapic.c, hypervisor/arch/x86/guest/vlapic.c, hypervisor/arch/x86/guest/vmsr.c, hypervisor/arch/x86/guest/vpic.c, hypervisor/arch/x86/ioapic.c, hypervisor/arch/x86/irq.c, hypervisor/arch/x86/notify.c, hypervisor/arch/x86/vmx.c, hypervisor/boot/acpi.c, hypervisor/common/hypercall.c, hypervisor/debug/vuart.c, hypervisor/include/arch/x86/cpu.h, hypervisor/include/arch/x86/irq.h, hypervisor/lib/crypto/hkdf.c, hypervisor/lib/string.c
Includes header file of non-static function, and declare the
in-file use function static.
=> HV: prototyping non-static function

hypervisor/arch/x86/guest/pm.c, hypervisor/arch/x86/guest/ucode.c, hypervisor/arch/x86/guest/vlapic.c, hypervisor/arch/x86/guest/vm.c, hypervisor/arch/x86/guest/vpic.c, hypervisor/arch/x86/irq.c, hypervisor/arch/x86/mmu.c, hypervisor/arch/x86/notify.c, hypervisor/arch/x86/softirq.c, hypervisor/arch/x86/vmexit.c, hypervisor/arch/x86/vmx.c, hypervisor/arch/x86/vtd.c, hypervisor/common/vm_load.c, hypervisor/debug/logmsg.c, hypervisor/debug/serial.c, hypervisor/debug/shell_internal.c, hypervisor/lib/memory.c, hypervisor/lib/sprintf.c, hypervisor/lib/string.c
Fix remaining 11S and 12S violations. These
are after the 7 patches submitted earlier.
=> HV: Fix new MISRAC violations for brackets

hypervisor/bsp/uefi/clearlinux/acrn.conf
update kernel-pk version to align with ACRN v0.1 release
=> update kernel-pk version to align with ACNR v0.1

devicemodel/samples/nuc/launch_uos.sh
update the kernel version to align with ACRN v0.1 and Clear version for UOS
=> update launch_uos.sh to align with ACRN v0.1

doc/api/GVT-g_api.rst, doc/api/index.rst, doc/developer-guides/primer.rst
The document is partly generated from Linux kernel source code via
kernel-doc tool.
ACRN specific stuff are generated from ACRN Hypervisor with a few
introction.
=> [doc] add GVT-g_api.rst

tools/acrn-manager/README.rst
Reviewed-by: Yan Like <like.yan@intel.com>
=> tools: acrnd: update README.rst

hypervisor/arch/x86/guest/instr_emul.c
- explicitly declare the array size of 'size2mask[]'
otherwise, the static checking tool treats the array size to be 4, so
that it complains when accessing index '4' or '8'
- unify the comments style and make sure the line length less than 80
=> hv: instr_emul: fix 'Parameter indexing array too big at call'

hypervisor/arch/x86/trusty.c, hypervisor/arch/x86/trusty2.c, hypervisor/boot/sbl/hob_parse.c, hypervisor/boot/sbl/multiboot.c, hypervisor/include/arch/x86/hob_parse.h, hypervisor/include/arch/x86/trusty.h, hypervisor/include/lib/sprintf.h, hypervisor/lib/div.c, hypervisor/lib/mdelay.c, hypervisor/lib/memory.c, hypervisor/lib/spinlock.c, hypervisor/lib/sprintf.c, hypervisor/lib/string.c
mainly focus on: like U/UL as unsigned suffix;
char and int mix usage; also change some function's params
for data type consistent.
=> HV: handle integral issues as MISRA-C report

devicemodel/hw/pci/xhci.c, devicemodel/hw/platform/usb_mouse.c, devicemodel/hw/platform/usb_pmapper.c, devicemodel/hw/usb_core.c, devicemodel/include/usb_core.h
This patch series enable some important USB features based on USB port
sharing strategy.
1. Multiple interface support;
2. USB 3.0 support;
3. Isochronous transfer.
=> USB virtualization features

hypervisor/arch/x86/mtrr.c
The fixed MTRR MSR numbers are not contiguous, so it's not correct
to justify it by checking if it falls in certain range.
This patch fixes this issue by removing is_fixed_range_mtrr()
and use get_index_of_fixed_mtrr() to loop fixed_mtrr_map[]
and compare individual MSR values.
Also removed the unused function get_subrange_end_of_fixed_mtrr()
=> hv: correct the way to check if a MSR is a fixed MTRR register

hypervisor/debug/console.c, hypervisor/include/debug/console.h
Remove this API console_dump_bytes
=> hv:Remove dead code in console.c

hypervisor/arch/x86/guest/vioapic.c
In vioapic emulating code, the vioapic spinlock is taken twice
in the same context.
=> hv: bug fix on operating spin_lock

hypervisor/debug/shell_internal.c, hypervisor/debug/shell_internal.h, hypervisor/debug/shell_public.c, hypervisor/include/debug/shell.h
Remove shell_construct
Change shell_init to void type
=> hv:Change shell_init to void type

hypervisor/arch/x86/ept.c, hypervisor/arch/x86/guest/guest.c, hypervisor/arch/x86/guest/vmcall.c, hypervisor/arch/x86/mmu.c, hypervisor/arch/x86/pagetable.c, hypervisor/arch/x86/trusty.c, hypervisor/arch/x86/trusty2.c, hypervisor/common/hypercall.c, hypervisor/include/arch/x86/mmu.h, hypervisor/include/arch/x86/pgtable.h, hypervisor/include/common/hypercall.h, hypervisor/include/public/acrn_hv_defs.h
1. Add hcall_change_vm_page_wp_perm to change guest one page write permission.
2. reimplement mmu_add to add page table mapping
=> Revisit HV MMU & EPT

hypervisor/debug/printf.c, hypervisor/include/lib/sprintf.h, hypervisor/lib/sprintf.c, hypervisor/lib/string.c
main focus on integral issues, and change some functions
interface to unify the params data type; also modify to
simplify the code logic.
=> HV: cleanup sprintf&string.c MISRA-C issues

doc/getting-started/apl-nuc.rst, tools/acrn-crashlog/README.rst, tools/acrn-crashlog/acrnprobe/Makefile, tools/acrn-crashlog/acrnprobe/README.rst, tools/acrn-crashlog/acrnprobe/android_events.c, tools/acrn-crashlog/acrnprobe/crash_reclassify.c, tools/acrn-crashlog/acrnprobe/include/load_conf.h, tools/acrn-crashlog/acrnprobe/include/loop.h, tools/acrn-crashlog/acrnprobe/loop.c, tools/acrn-crashlog/acrnprobe/probeutils.c, tools/acrn-crashlog/acrnprobe/property.c, tools/acrn-crashlog/acrnprobe/sender.c, tools/acrn-crashlog/acrnprobe/startupreason.c, tools/acrn-crashlog/common/cmdutils.c, tools/acrn-crashlog/common/include/cmdutils.h, tools/acrn-crashlog/common/include/fsutils.h
Replace debugfs,losetup and fdisk with libraries.
=> Replace debugfs,losetup and fdisk with libraries. 

doc/.known-issues/doc/hypercall.conf
=> doc: tweek known-issues pattern for hypercall API

doc/static/acrn-custom.css
update custom css to make kbd tag more interesting
=> doc: tweak formatting for :kbd: role

doc/user-guides/acrn-shell.rst
Fix an indentation problem during in doc review.
=> doc: fix table in acrn-shell documentation

hypervisor/arch/x86/assign.c, hypervisor/arch/x86/ept.c, hypervisor/arch/x86/guest/guest.c, hypervisor/arch/x86/guest/pm.c, hypervisor/arch/x86/guest/vcpu.c, hypervisor/arch/x86/guest/vlapic.c, hypervisor/arch/x86/guest/vm.c, hypervisor/arch/x86/guest/vmcall.c, hypervisor/arch/x86/guest/vpic.c, hypervisor/arch/x86/mtrr.c, hypervisor/arch/x86/trusty2.c, hypervisor/common/hypercall.c, hypervisor/common/io_request.c, hypervisor/common/vm_load.c, hypervisor/debug/dump.c, hypervisor/debug/shell.c, hypervisor/include/arch/x86/guest/vm.h
Remove structure vm_attr
Wrap two APIs alloc_vm_id and free_vm_id
=> hv:cleanup vmid related code

devicemodel/hw/pci/xhci.c
Refine DM DRD code and modify some logical judgement to avoid
potential NULL pointer issue.
Signed-off-by: Liang Yang <liang3.yang@intel.com>
Reviewed-by: Shuo Liu <shuo.a.liu@intel.com>
=> DM USB: xHCI: Refine drd code to fix a potential NULL pointer issue.

devicemodel/core/main.c
It is necessary to notify the VHM and hypervisor on the completion of a VHM
request even when the UOS is in suspend or system reset mode because the VHM and
hypervisor rely on the notification to reset their own states on the
request.
Currently the VHM request state is checked against REQ_STATE_PROCESSING instead
of REQ_STATE_COMPLETE when handling system reset or suspend/resume, leading to a
completed request unnotified, and causing the HV to complain on an occupied VHM
request when it raises a new one.
This patch fixes this issue by properly notifying completed requests to the VHM
& hypervisor. Some concerns are raised during a discussion on the potential
races which does not hurt for now but may in the future. These considerations
and potential solutions are documented as comments for …
=> DM: notify VHM request complete after pausing the VM

hypervisor/arch/x86/io.c
There is no SOS and device model in strict partition mode. ACRN emulates IO for
virtual devices. Any access to IO not backed by HV should return all FFs on read
and writes should be discarded.
=> hv: Handling IO exits in ACRN for partition mode

devicemodel/hw/block_if.c, devicemodel/hw/pci/virtio/virtio.c, devicemodel/hw/pci/virtio/virtio_audio.c, devicemodel/hw/pci/virtio/virtio_block.c, devicemodel/hw/pci/virtio/virtio_console.c, devicemodel/hw/pci/virtio/virtio_heci.c, devicemodel/hw/pci/virtio/virtio_hyper_dmabuf.c, devicemodel/hw/pci/virtio/virtio_input.c, devicemodel/hw/pci/virtio/virtio_net.c, devicemodel/hw/pci/virtio/virtio_rnd.c, devicemodel/hw/pci/virtio/virtio_rpmb.c, devicemodel/include/block_if.h, devicemodel/include/virtio.h, doc/developer-guides/virtio-hld.rst
dm: storage: support writethru and writeback mode
doc: update virtio-blk usage in HLD
dm: virtio: remove hv_caps from virtio_ops
dm: storage: support cache mode toggling
=> virtio block cache mode support

hypervisor/arch/x86/assign.c, hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/cpuid.c, hypervisor/arch/x86/ept.c, hypervisor/arch/x86/guest/guest.c, hypervisor/arch/x86/guest/instr_emul.c, hypervisor/arch/x86/guest/pm.c, hypervisor/arch/x86/guest/vlapic.c, hypervisor/arch/x86/guest/vmcall.c, hypervisor/arch/x86/guest/vmsr.c, hypervisor/arch/x86/io.c, hypervisor/arch/x86/irq.c, hypervisor/arch/x86/mmu.c, hypervisor/arch/x86/timer.c, hypervisor/arch/x86/vmexit.c, hypervisor/arch/x86/vmx.c, hypervisor/boot/acpi.c, hypervisor/boot/sbl/multiboot.c, hypervisor/common/hypercall.c, hypervisor/common/io_request.c, hypervisor/debug/dump.c, hypervisor/debug/logmsg.c, hypervisor/debug/sbuf.c, hypervisor/debug/shell.c, hypervisor/debug/vuart.c, hypervisor/dm/vioapic.c, hypervisor/dm/vpic.c, hypervisor/lib/memory.c, hypervisor/lib/sprintf.c, hypervisor/lib/string.c
Added brackets to logical conjunctions which have precedence level is less than 13.
=> Logicalconjunctionbracket

hypervisor/arch/x86/cpu.c, hypervisor/include/arch/x86/msr.h
This reverts commit b3690987bd30804ce3c886c85bdc1ba6bf369f22.
=> Revert "[REVERT-ME]: disable turbo mode"

devicemodel/core/monitor.c, tools/acrn-manager/acrn_mngr.h, tools/acrn-manager/acrn_vm_ops.c, tools/acrn-manager/acrnctl.c, tools/acrn-manager/acrnctl.h, tools/acrn-manager/acrnd.c
With these changes, S3 feature works.
1.fixed get_sos_wakeup_reason() in acrnd.c
2.fixed handle_resume() in monitor.c
3.wakeup reason is unsigned int in acrn_mngr.h
4.update resume_vm(char *name) to resume_vm(char *name, unsigned reason)
=> Tools: fixed issues for S3 feature

hypervisor/arch/x86/guest/mptable.c
1)Fix to take into account the size of proc entries in MPtable.
2)Change APIC ids to virtual APIC IDs
=> hv: fix size issue in mptable guest copy - ACRN partition mode

hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/guest/instr_emul.c, hypervisor/arch/x86/guest/vlapic.c, hypervisor/arch/x86/guest/vmsr.c, hypervisor/arch/x86/ioapic.c, hypervisor/arch/x86/notify.c, hypervisor/arch/x86/timer.c, hypervisor/arch/x86/vmx.c, hypervisor/boot/acpi.c, hypervisor/bsp/uefi/uefi.c, hypervisor/debug/shell.c, hypervisor/lib/sprintf.c, hypervisor/lib/string.c
removed some unnecessary variables and functions.
v1-->v2:
Replace div-by-zero with an inline ASM code
=> hv: fixed compiling warning

devicemodel/samples/apl-mrb/launch_uos.sh
Signed-off-by: Yew, Chang Ching <chang.ching.yew@intel.com>
Reviewed-by: Edwin Zhai <edwin.zhai@intel.com>
=> ipu: virtio-ipu4 as default IPU DM

devicemodel/hw/platform/cmos_io.c
=> dm: cmos: fix a logic error for read to clear range

hypervisor/arch/x86/assign.c
Since this interrupt pin is passed through to the guest, we could set
it as we like. There's no need a flag to emulate the masked status.
=> hv: ptdev: simplify ptdev_intx_pin_remap logic

hypervisor/dm/vpci/hostbridge.c, hypervisor/dm/vpci/pci_priv.h, hypervisor/dm/vpci/pci_pt.c, hypervisor/dm/vpci/pci_vdev.c, hypervisor/dm/vpci/vpci.c, hypervisor/include/dm/vpci/vpci.h, hypervisor/partition/vm_description.c
=> VPCI coding style and bugs fixes found in integration testing for partition mode

hypervisor/common/vm_load.c
Tracked-On: #1137
Signed-off-by: Cai Yulong <yulongc@hwtc.com.cn>
=> hv: fixup format of log message in vm_load.c

doc/developer-guides/GVT-G-porting.rst, doc/developer-guides/graphviz.rst, doc/release_notes_0.1.rst, doc/tutorials/using_ubuntu_as_sos.rst
fix misspellings in .rst files missed during regular reviews
=> doc: fix doc misspellings

devicemodel/include/public/vhm_ioctl_defs.h
Tracked-On: #1141
Signed-off-by: Li Zhijian <zhijianli88@163.com>
=> DM: coding style: replace tab with space

hypervisor/debug/shell.c
Pre-allocate 2 pages of static memory for shell log buffer.
=> hv:Replace dynamic allocation with static memory for shell

devicemodel/hw/pci/core.c
if some pci devices behind gvt got failures when initlizing at init_pci(), gvt
instance have no chance to be destroied even acrn-dm exits.
NOTE: this patch can not work standalone, a following patch to kernel
side(643d40961cf: "vhm: init client->kthread_exit true") is requied as well,
otherwise it will stucks during destroying gvt instance.
Tracked-On: #1141
Signed-off-by: Li Zhijian <zhijianli88@163.com>
=> DM: deinit initialized pci device when failed

tools/acrn-manager/acrn_vm_ops.c, tools/acrn-manager/acrnctl.c, tools/acrn-manager/acrnctl.h, tools/acrn-manager/acrnd.c
Reworked the resume/reset flow of UOS, to make them work and be aligned with OSPM design.
=> tools: acrn-manager: rework acrnd resume/reset flow

doc/developer-guides/interrupt-hld.rst
=> Doc: add interrupt storm mitigation explanation.

devicemodel/hw/platform/rtc.c
In the current implementation sigev_notify is configured as
SIGEV_THREAD. When timer expires an async thread is created and
the registered timer callback is called in the context of this
thread. vrtc_update_timer will access the global data vrtc. There
is a race condition that vrtc is freed when deinit and then a timer
expires. In this case vrtc_update_timer will access a freed buffer
which causes problem such as heap corruption and segment fault.
In this patch signal model is used when timer is created. The signal
is masked and a signalfd is used to poll on it with mevent. This avoids
the race condition.
Tracked-On: #1185
=> dm: vrtc: use signalfd to poll signal from timer

doc/release_notes_0.2.rst
Filter v0.2 fixed issues from github closed issue list.
Signed-off-by: Nanlin Xie <nanlin.xie@intel.com>
=> doc: Add fixed issues in v0.2 release note

hypervisor/dm/vioapic.c, hypervisor/dm/vpic.c
remove the following unnecessary spinlock wrappers
#define VIOAPIC_LOCK(vioapic)   spinlock_obtain(&((vioapic)->mtx))
#define VIOAPIC_UNLOCK(vioapic)  spinlock_release(&((vioapic)->mtx))
#define    VPIC_LOCK_INIT(vpic)    spinlock_init(&((vpic)->lock))
#define    VPIC_LOCK(vpic)         spinlock_obtain(&((vpic)->lock))
#define    VPIC_UNLOCK(vpic)       spinlock_release(&((vpic)->lock))
=> hv: vioapic/vpic: clean up spinlock wrappers

doc/release_notes_0.2.rst
Add new feature list and description in v0.2 release note.
=> doc: Add new feature in v0.2 release note

doc/release_notes_0.2.rst
Add known issues and description in v0.2 release note.
=> doc: Add known issues in v0.2 release note.

hypervisor/arch/x86/irq.c
Logically, out-of-range access won't happen at these places. However, it
depends on the behaviour of other codes.
This commit makes changes to explicitly eliminate the possibility in these
functions.
Tracked-On: #1235
=> hv:irq: avoid out-of-range access to irq_alloc_bitmap[]

hypervisor/arch/x86/vtd.c
Current code enables IOMMU from init_iommu_vm0_domain which is called
from vm0/sos boot sequence. For partition mode VMs, this is not called as
VMs are numbered from 1.
This patch adds support to initialize root table pointer for each IOMMU
and enable all IOMMUs from init_iommu. Hence IOMMUs are enabled even
though ACRN does not boot vm0.
This patch was merged in PR #1247 but reverted due to issue #1270.
So this patch includes changes to fix #1270. 
Tracked-On: #1246 #1270
=> hv: init_iommu rework to enable IOMMU for partition mode ACRN

doc/release_notes_0.2.rst
Add change log in v0.2 release note.
=> doc: Add change log in v0.2 release note.

doc/release_notes_0.2.rst
Add instructions for accessing source for the v0.2 tagged
release.
=> doc: add tags and checkout info to release notes

doc/release_notes_0.2.rst
Add new known issue in v0.2 release note.
=> doc: Add new known issue in v0.2 release note.

doc/release_notes_0.2.rst
Remove "DRAFT" indicator, and a few tweaks to repo description and
download instructions noticed in PR #1316
=> doc: release notes update for v0.2 release

doc/tutorials/docbuild.rst
Update the doc build instructions to include how to update the version
navigation selector (bottom of the left nav panel), and make commands
for building and publishing specific tagged releases (e.g., 0.2)
=> doc: update tagged release doc build instructions

devicemodel/hw/pci/virtio/virtio_net.c
Netmap/vale attempts to speed up network communication by bypassing the
TCP/IP network stack, which requires patching the physical NIC driver so
that applications developed based on netmap can interact directly with
the physical NIC driver. It may make sense for some specific scenarios
which requres very high bandwith (10Gb/s or 100Gb/s), we can even put up
with the complexity and compatibility introduced by this techology.
However for ACRN, a virtualization solution for IoT, there is no need to
support this backend. For 1Gb NICs or below, the VBS-U/tap solution
can already achieve near-native bandwidth. To keep simplicity and
improve compatibility, remove the netmap/vale support in dm.
Tracked-On: #1313 …
=> dm: virtio_net: remove netmap/vale backend support

doc/getting-started/apl-nuc.rst
updated Clear Linux version to 25130 as getting started
updated pk kernel version to 4.14.68-99
added one bundle installation
=> update CL version to support v0.2 release

devicemodel/core/main.c, devicemodel/core/vmmapi.c, devicemodel/include/public/acrn_common.h, devicemodel/include/public/vhm_ioctl_defs.h, devicemodel/include/vmmapi.h
1) vhost APIs in DM
2) combine ioreq shared page setup and vm creating. This patch is also needed by vhost series.
Tracked-On: #1329 #1330
=> Vhost APIs in DM

hypervisor/arch/x86/guest/instr_emul.c
1. The wrong operand size is assigned in instruction decode phase
if the operand size is 1 byte.
According to the SDM, the bit 0(w bit) of opcode should be checked
first to detect whether the operand size is 1 byte. Then, check
whether there is prefix to overwrite the default operand size.
The original instruction decode doesn't care about the operand
size. But do opsize fixup during instruction emulation phase.
With ACRN we need operand size packed to ioreq and send to DM
after instruction decode.
2. We should always touch the GPA by following opsize to avoid side
effect (especially when GPA is for a MMIO).
Tracked-On: #1337
=> hv: Fix two minor issues in instruction emulation code

hypervisor/arch/x86/guest/vcpu.c, hypervisor/bsp/uefi/efi/Makefile, hypervisor/bsp/uefi/efi/boot.c, hypervisor/include/arch/x86/guest/gpr.h, hypervisor/include/arch/x86/guest/guest.h, hypervisor/include/arch/x86/guest/vcpu.h, hypervisor/include/arch/x86/guest/vm0_boot.h, hypervisor/include/public/acrn_common.h
Add API set_vcpu_regs to set the vcpu registers.
Tracked-On: #1231
=> Add set vcpu regs

devicemodel/hw/pci/xhci.c
When the physical USB device is disconnected before DM's emulation
is ready, the virtual connection state is not cleared properly. This
will cause the DM refuse to do emulation for future physical connection.
This patch clears those states mentioned above and hence fix the issue.
Tracked-On: #1367
=> DM USB: xHCI: fix enumeration error after rebooting

doc/developer-guides/hld/hld-overview.rst, doc/developer-guides/hld/index.rst
Add another level to the HLD toc, and start conversion of the HLD intro
=> doc: tweak hld intro

hypervisor/arch/x86/guest/vm.c, hypervisor/boot/sbl/multiboot.c, hypervisor/include/arch/x86/guest/vm.h, hypervisor/partition/vm_description.c
This patch fixes compilation issue for PARTITION_MODE.
Tracked-On: #1404
=> hv: Fix for PARTITION_MODE compilation

hypervisor/debug/vuart.c
COM1_IRQ's polarity setting is from ACPI table, as hypervisor do not want
to parse ACPI table here, it just get the configuration from vioapic RTE
setting as a work-around.
TODO:
Here should assert vuart irq according to COM1_IRQ polarity.  The best way
is to get the polarity info from ACIP table. But we just get the info from
vioapic configuration. Based on this, we can still have irq storm during
guest modify the vioapic setting.
As it's only for debug uart, we want to make it as an known issue.
Tracked-On: https://github.com/projectacrn/acrn-hypervisor/issues/1432
=> vuart: assert COM1_IRQ based on its pin's polarity

hypervisor/arch/x86/vmx.c
TR selector initianlization using pre-defined HOST_GDT_RING0_CPU_TSS_SEL
rather than loading from register. Instead calculating real base address
of TSS based on TR selector and gdt, getting it from per cpu data.
Tracked-On: #1394
=> HV: get tss address from per cpu data

devicemodel/hw/block_if.c, devicemodel/hw/pci/virtio/virtio_block.c
1. Remove some dead code from Bhyve
2. Add debugging info
3. Add I/O range checks and reject requests that violate the spec
Tracked-On: #1422
=> dm: clean up virtio-block and block_if

devicemodel/core/main.c
For acrn-dm cmd options, there are some mismatch usage from acrn-dm help
message.
This patch will cleanup them.
Tracked-On: #1469
Reviewed-by: Jason Chen <jason.cj.chen@intel.com>
=> dm: cleanup the cmd options for acrn-dm

hypervisor/dm/vioapic.c
@vioapic_set_pinstate() & vioapic_need_intr(),
add checking input value range for 'pin'.
Tracked-On: #1479
=> hv: fix potential buffer overflow in vioapic.c

devicemodel/Makefile, devicemodel/core/main.c, devicemodel/core/sw_load_bzimage.c, devicemodel/core/sw_load_common.c, devicemodel/core/sw_load_elf.c, devicemodel/hw/platform/debugexit.c, devicemodel/include/dm.h, devicemodel/include/sw_load.h
Add elf loader to DM
Tracked-On: #1465
=> Elf loader push

devicemodel/hw/pci/wdt_i6300esb.c
Per i6300esb spec, when WDT_INT_TYPE(bit 0 and 1 of WDT config register)
are set to 00, IRQ feature should be supported.
The WDT_INT_ACTIVE bit is set when the first stage of the 35-bit
down-counter reaches zero. An interrupt will be generated if WDT_INT_TYPE
is configured to do so (See WDT Configuration Register). This is a sticky
bit and is only cleared by writing a 1.
SMI feature(WDT_INT_TYPE are set to 0x10) is not supported.
Tracked-On: #1498
=> DM: add MSI and INTR support for i6300esb watchdog

hypervisor/arch/x86/guest/ucode.c
Reserve 256KB static memory for microcode
=> hv:Replace dynamic memory with static for microcode

hypervisor/common/hypercall.c
route GSI number#2 to PIC IRQ#0, as by default IRQ for
8254 timer is connected to I/O APIC Pin #2 and PIC Pin #0
Tracked-On #861
=> hv: fix mapping between GSI Num#2 and PIC IRQ #0

devicemodel/hw/pci/xhci.c
Fix potential NULL pointer issue and array out of range issue.
Tracked-On: #1479
Signed-off-by: Liang Yang <liang3.yang@intel.com>
=> Fix potential NULL pointer issue and array out of range issue

devicemodel/hw/pci/virtio/virtio_kernel.c, devicemodel/include/virtio_kernel.h
=> dm: virtio: remove unused vbs_kernel_init

hypervisor/boot/reloc.c
Trampoline code is updated as data when preparing the trampoline
code and doing relocation. In this case, we need to flush cache
to make sure the updated code is in RAM.
Tracked-On: #1604
Reviewed-by: Zide Chen <zide.chen@intel.com>
=> hv: flush cache after update the trampoline code

devicemodel/hw/pci/xhci.c, devicemodel/hw/platform/usb_pmapper.c
Fix several bugs about USB mediator.
Tracked-On: #1566
=> fix some bugs of USB mediator

hypervisor/arch/x86/Kconfig, hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/guest/vlapic.c, hypervisor/arch/x86/guest/vm.c, hypervisor/boot/acpi.c, hypervisor/boot/include/acpi.h, hypervisor/debug/logmsg.c, hypervisor/debug/shell.c, hypervisor/include/arch/x86/cpu.h, hypervisor/include/arch/x86/per_cpu.h
replace dynamic memory with static for pcpu
=> replace dynamic memory with static for pcpu

doc/api/GVT-g_api.rst
* interface name changed
* missing kernel doc comment in kernel source code
Tracked-On: #1511
=> Fix AcrnGT broken API doc due to kernel upgrade

hypervisor/arch/x86/guest/vlapic.c
Guest OS can use vLAPIC in x2APIC mode. Upon vlapic_reset, vLAPIC should
be set to xAPIC mode.
Tracked-on: #1626
=> hv: switch vLAPIC mode vlapic_reset

doc/developer-guides/hld/hld-overview.rst, doc/developer-guides/hld/hld-virtio-devices.rst, doc/developer-guides/hld/hv-cpu-virt.rst, doc/developer-guides/hld/hv-dev-passthrough.rst, doc/developer-guides/hld/hv-interrupt.rst, doc/developer-guides/hld/hv-vt-d.rst, doc/developer-guides/hld/virtio-net.rst
scan and fix misspellings missed during normal review
Tracked-on: #1648
=> doc: fix misspellings in hld docs

hypervisor/debug/profiling.c
Return from the function if the NULL pointer is encountered.
Tracked-On : #1409
Signed-off-by: Manisha Chinthapally <manisha.chinthapally@intel.com>
=> HV: bug fix:possible access to NULL pointer

doc/.known-issues/doc/hypercall.conf, doc/acrn.doxyfile
PR #1678 requires slight tweaking of doxygen/known-issues handling to
successfully generating documentation
Tracked-on: #1595
=> doc: tweak doxygen/known-issues handling

doc/developer-guides/hld/hld-devicemodel.rst
Fix incorrect section heading level.
Tracked-on: #1668
=> doc: fix section heading in device model hld

hypervisor/Makefile, hypervisor/arch/x86/guest/vm.c, hypervisor/arch/x86/guest/vmcall.c, hypervisor/common/hypercall.c, hypervisor/dm/hw/pci.c, hypervisor/dm/vpci/msix.c, hypervisor/dm/vpci/pci_priv.h, hypervisor/dm/vpci/sharing_mode.c, hypervisor/include/arch/x86/guest/vm.h, hypervisor/include/common/hypercall.h, hypervisor/include/dm/vpci.h
=> hv: enable MSI remapping and fix 2 known bugs

tools/acrn-crashlog/acrnprobe/android_events.c, tools/acrn-crashlog/acrnprobe/channels.c, tools/acrn-crashlog/acrnprobe/history.c, tools/acrn-crashlog/acrnprobe/include/load_conf.h, tools/acrn-crashlog/acrnprobe/load_conf.c, tools/acrn-crashlog/acrnprobe/main.c, tools/acrn-crashlog/acrnprobe/probeutils.c, tools/acrn-crashlog/acrnprobe/sender.c, tools/acrn-crashlog/common/fsutils.c, tools/acrn-crashlog/common/include/fsutils.h, tools/acrn-crashlog/usercrash/crash_dump.c, tools/acrn-crashlog/usercrash/protocol.c, tools/acrn-crashlog/usercrash/server.c
Changes include:
1. check the parameter of snprintf
2. remove atoi
3. remove sscanf
4. fix one memleak
=> tools: acrn-crashlog: fix potential issues

doc/developer-guides/contribute_guidelines.rst
All PRs must have a Tracked-on: tag
Tracked-on: #1420
=> doc: update Tracked-on in contribute guide

devicemodel/hw/pci/virtio/virtio_input.c
(EV_MSC, MSC_TIMESTAMP) is added to each frame just before the
SYN event since kernel 4.15. EV_MSC is configured as
INPUT_PASS_TO_ALL. In the use case of virtio-input, there is
a loop as follows:
- A mt frame with (EV_MSC, MSC_TIMESTAMP) is passed to FE.
- FE will call virtinput_status to pass (EV_MSC, MSC_TIMESTAMP)
back to BE.
- BE writes this event to evdev. Because (EV_MSC, MSC_TIMESTAMP)
is configured as INPUT_PASS_TO_ALL, it will be written into
the event buffer of evdev then be read out by BE without
SYN followed.
- Each mt frame will introduce one (EV_MSC, MSC_TIMESTAMP).
Later the frame becomes larger and larger...
This patch fixed above issue by ignoring MSC_TIMESTAMP from guest.
Besides that timestamp is added for every status event from guest
before writing to evdev. …
=> dm: virtio-input: ignore MSC_TIMESTAMP from guest

doc/developer-guides/l1tf.rst
fix indent and Title alignmeng.
Tracked-On: #1672
=> doc: hotfix build issue blocked by l1tf.rst

doc/developer-guides/l1tf.rst
PR #1714 had one error that this PR is fixing.
Tracked-on: #1672
=> doc: fix formatting error in l1tf doc

doc/acrn.doxyfile, doc/developer-guides/hld/hv-cpu-virt.rst, hypervisor/include/arch/x86/guest/vcpu.h, hypervisor/include/public/acrn_common.h
add main vCPU and data structure introduction for HLD; replace the fixed functions & data structure 
descriptions.
=> DOC: add main vCPU and data structure introduction for HLD

doc/developer-guides/hld/hv-memmgt.rst, hypervisor/include/arch/x86/guest/guest.h, hypervisor/include/arch/x86/mmu.h, hypervisor/include/arch/x86/mtrr.h, hypervisor/include/arch/x86/pgtable.h
This patch serials adds API documentation to haeder
file in doxygen style and replace the hard-code API 
docs with doxygen-generated ones.
=> HV:Update APIs doc for HLD

doc/acrn.doxyfile, doc/developer-guides/hld/hv-interrupt.rst, hypervisor/arch/x86/irq.c, hypervisor/include/arch/x86/ioapic.h, hypervisor/include/arch/x86/irq.h, hypervisor/include/arch/x86/lapic.h, hypervisor/include/common/irq.h
=> doc: hv: add comments to irq APIs for documentation

doc/acrn.doxyfile, doc/developer-guides/hld/hv-virt-interrupt.rst, hypervisor/arch/x86/guest/vlapic.c, hypervisor/dm/vioapic.c, hypervisor/dm/vpic.c, hypervisor/include/arch/x86/guest/vioapic.h, hypervisor/include/arch/x86/guest/vlapic.h, hypervisor/include/arch/x86/guest/vpic.h, hypervisor/include/arch/x86/irq.h
Add comments for virtual Interrupt module APIs
=> doc: hv: add comments to vIRQ APIs for documentation

tools/acrn-manager/acrn_mngr.c, tools/acrn-manager/acrn_vm_ops.c, tools/acrn-manager/acrnctl.c, tools/acrn-manager/acrnd.c, tools/acrnlog/acrnlog.c
remove unsafe function sscanf
replace strlen with strnlen
replace atoll with strtoll and replace aoti with strtol
Tracked-On: #1254
=> Tools:   remove usage of banned APIs

hypervisor/dm/vpci/msix.c
MMIO registers might be changed at any time.
The changes might not be catched due to compiler optimization
if there is no 'volatile' keyword.
We have defined MMIO read/write APIs to address the above issue.
'volatile' keyword is being used in these defined MMIO read/write
APIs.
This patch updates the MMIO registers access implementation in
'msix.c' to use these defined MMIO read/write APIs.
v1 -> v2:
* update the algorithm to get the address of high 32-bit of
'pentry->addr'
- previous way:
&(pentry->addr) + 4U
===> &(pentry->addr) + 4 * 64 bits
since 'pentry->addr' is 64 bits
- new way:
(char *)&(pentry->addr) + 4U
===> &(pentry->addr) + 4 * 8 bits
since 'char' is 8 bits
Tracked-On: #1711
Reviewed-by: Jason Chen CJ …
=> hv: use MMIO read/write APIs to access MMIO registers

devicemodel/core/main.c, devicemodel/hw/pci/core.c, devicemodel/hw/pci/virtio/vhost.c, devicemodel/hw/pci/virtio/virtio.c, devicemodel/hw/pci/virtio/virtio_kernel.c, devicemodel/include/dm.h, devicemodel/include/pci_core.h, devicemodel/include/public/vhm_ioctl_defs.h, devicemodel/include/vhost.h, devicemodel/include/virtio.h, devicemodel/include/virtio_kernel.h, doc/acrn.doxyfile, doc/developer-guides/hld/hld-virtio-devices.rst
1) update virtio related functions doc comments
2) also remove one unused APIs. Doc will be removed if we generate by doxygen.
=> update virtio related functions doc comments

doc/developer-guides/hld/hld-vm-management.rst
Transcode, edit, and upload HLD 0.7 section 7 (VM Management)
Tracked-on: #1734
=> doc: update HLD VM Management

hypervisor/partition/vm_description.c
Fix the issue that kernel console doesn't work with partition mode.
Tracked-On: #1756
=> hv: fix partition mode no console issue.

devicemodel/hw/uart_core.c, tools/acrn-manager/acrnd.c, tools/acrn-manager/acrnd.service
with these changes, UOS console can be redirected to system journal
Tracked-On: #1759
=> capture acrnd AaaG booting messages to journald

doc/developer-guides/hld/hld-devicemodel.rst
add the introduction of interrupt storm monitor params in acrn-dm
commond lines.
=> doc: explain intr storm monitor params in acrn-dm

doc/release_notes_0.3.rst
Add v0.3 new feature/fixed issues/known issues/change log into v0.3 release note.
=> doc: Add v0.3 release note

doc/conf.py, doc/release_notes_0.3.rst
Update release notes and version selector for 0.3 release
=> doc: release notes for 0.3

doc/release_notes_0.3.rst
Fix a few spelling and presentation errors.
=> doc: tweaks to 0.3 release notes

hypervisor/arch/x86/guest/instr_emul.c
clean up mmio_read/mmio_write in instr_emul.c
- make these two functions inline
- discard the return value and add the pre condition
- rename these two functions to vie_mmio_read/vie_mmio_write
=> hv: instr_emul: clean up mmio_read/mmio_write

hypervisor/dm/vpci/msix.c
=> hv: fix a few bugs for msix.c

hypervisor/include/arch/x86/msr.h
- fix code style: mix of tab and white spaces, alignments,  etc.
- remove not meaningful comments. Also these comments are below the
source code which makes the code look messy.
- add more MSR register definitions
=> hv: code cleanup: msr.h

devicemodel/hw/pci/virtio/virtio_mei.c, devicemodel/samples/apl-mrb/launch_uos.sh
Should fix UOS reboots and UOS panic stress testing.
Tracked-On: #1846 #1847 #1848 #1849
Signed-off-by: Alexander Usyskin <alexander.usyskin@intel.com>
=> Virtio mei : platform reset fixes 

hypervisor/Makefile, hypervisor/debug/Makefile, hypervisor/release/Makefile
enhance Makefile to compile debug/release into 2 libraries
v1 -> v2:
* auto make all the libraries
=> hv: enhance Makefile to compile debug/release into 2 libraries

hypervisor/common/hypercall.c
to avoid passing guest's memory block into hypervisor internal
process for security.
=> hv:use copy of guest's memory block in 'hcall_set_vm_memory_regions()'

devicemodel/hw/pci/virtio/virtio_mei.c, devicemodel/samples/apl-mrb/launch_uos.sh
Should fix UOS reboots and UOS panic stress testing.
Tracked-On: #1846 #1847 #1848 #1849
Signed-off-by: Alexander Usyskin alexander.usyskin@intel.com
Signed-off-by: Tomas Winkler tomas.winkler@intel.com
=> Vmei fix tomas alpha

hypervisor/debug/logmsg.c, hypervisor/debug/shell.c, hypervisor/debug/shell_priv.h, hypervisor/include/arch/x86/per_cpu.h
=> Remove earlylog

hypervisor/arch/x86/mmu.c
now the size of sanitized_page is 32KB,
revise it to 4KB.
=> hv:Revise sanitized page size

hypervisor/dm/vpci/msix.c
Reduce the count of the "return entries".
Fix the violations which is comply with the cases list below:
1.Function has 2 return entries.
2.The first return entry is used to return the error code of
checking variable whether is valid.
V1->V2:
remove the unrelated code.
Fix the violations in "if else" format.
=> hv: msix: fix "Procedure has more than one exit point"

devicemodel/hw/pci/virtio/virtio_audio.c
[PATCH 1/2] change the vq count and vendor id
Signed-off-by: Zhu Yingjiang <yingjiang.zhu@linux.intel.com>
[PATCH 2/2] use 4 vqs
Signed-off-by: Libin Yang <libin.yang@intel.com>
Tracked-On: #1915
=> Vq count vendor

hypervisor/arch/x86/trusty.c
Since "uint8_t page[CPU_PAGE_SIZE]" wants to ensure the first_page only
took PAGE_SIZE memory space and aligned to PAGE_SIZE. However, it couldn't.
So just make it simpler.
Reviewed-by: Qi, Yadong <yadong.qi@intel.com>
=> hv: trusty: refine struct trusty_mem

hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/guest/guest.c, hypervisor/arch/x86/guest/instr_emul.c, hypervisor/arch/x86/guest/instr_emul.h, hypervisor/arch/x86/guest/pm.c, hypervisor/arch/x86/guest/vlapic.c, hypervisor/arch/x86/notify.c, hypervisor/arch/x86/pm.c, hypervisor/arch/x86/trampoline.c, hypervisor/boot/acpi.c, hypervisor/boot/sbl/multiboot.c, hypervisor/common/hypercall.c, hypervisor/common/softirq.c, hypervisor/common/vm_load.c, hypervisor/lib/memory.c, hypervisor/lib/sprintf.c, hypervisor/lib/string.c
1) remove the theoretic infinite loop
2) refine print_decimal
3) avoid using of mixed mode arithmetic
4) fix type conversion without cast with explicit conversion
=> MISRA C compliance

hypervisor/arch/x86/guest/vlapic.c
String should assigned to const object
=> hv: fix string assigned to non const object

hypervisor/Makefile, hypervisor/arch/x86/vmx.c, hypervisor/dm/vpci/sharing_mode.c, hypervisor/include/arch/x86/host_pm.h, hypervisor/lib/string.c
minor refine about coding style
=> HV: minor refine about coding style

doc/release_notes_0.4.rst
=> doc: Add v0.4 release note

doc/release_notes_0.4.rst
Add known issues found in pre-release test.
=> Add known issues found in pre-release test.

devicemodel/samples/nuc/launch_uos.sh, doc/getting-started/apl-nuc.rst, hypervisor/bsp/uefi/clearlinux/acrn.conf
Doc: Update GSG for v0.4 version and launch and acrn.conf sample script
=> Doc: Update GSG for v0.4 version and launch and acrn.conf sample script

hypervisor/arch/x86/io.c
The bit mask for an out instruction is only applied to hv inout
handlers.
Apply the bit mask to dm inout handlers as well.
Tracked-On: #2075
=> hv: enforce data size on all out exits

hypervisor/arch/x86/guest/vm.c
Fix violation "procedure has more than one exit point"
for this api.
=> hv:refine alloc_vm_id api

hypervisor/common/hypercall.c
=> fix "Procedure has more than one exit point."

hypervisor/arch/x86/guest/ucode.c
- reduce exit points for 'acrn_update_ucode()' function.
Tracked-On: #2095
=> hv: refine coding style for ucode.c

hypervisor/arch/x86/irq.c, hypervisor/arch/x86/lapic.c, hypervisor/include/arch/x86/idt.h
fixed MISRA-C violations in irq.c, lapic.c and idt.h
=> hv: cleanup MISRA-C violations in irq.c, lapic.c and idt.h

hypervisor/common/io_request.c
Clean the io_request.c's violations reported by the misra tools.
V1->V2:
remove violations which checked with NULL.
=> hv:clean io_request.c misra violations

hypervisor/debug/string.c, hypervisor/include/lib/rtl.h, hypervisor/lib/string.c
hv: fix the MISRA-C violations related to string
This patch series fix the MISRA-C violations related to string.
=> hv: fix the MISRA-C violations related to string

hypervisor/arch/x86/pagetable.c, hypervisor/include/arch/x86/e820.h, hypervisor/include/arch/x86/page.h
1) Fix procedure has more than one exit point.
2) Add some brackets to make logical conjunctions more readable.
=> hv: coding style: refine page related

hypervisor/arch/x86/guest/vmsr.c
Fixed three MISRA-C violations:
11S: No brackets to loop body
7C: Procedure has more than one exit point.
8D: DD data flow anomalies found.
initialize read_map and write_map in the declaration statements.
Fixed one bug:
Use "msr <= 0x1FFFU" instead of "msr < 0x1FFFU" because 0x1FFF is a valid MSR
bitmap address.
=> hv: fix enable_msr_interception() function

hypervisor/arch/x86/guest/guest.c, hypervisor/arch/x86/guest/vm.c, hypervisor/include/arch/x86/guest/guest.h
-- fix "more than one exit point" and "goto detected" violations
-- change prepare_vm0_memmap to void type
-- Add free_vm_id when create vm failed
=> hv:fix MISRA-C violations in create_vm

hypervisor/arch/x86/guest/pm.c
1. change multi "return" to one exit.
2. add "U" to unsigned const as postfix.
=> HV: fix pm code for multi-exits & unsigned const

hypervisor/arch/x86/vmexit.c
This patch fixes the MISRA-C violations in arch/x86/vmexit.c
* make the function have only one exit point
=> hv: vmexit: fix MISRA-C violations related to multiple exits

hypervisor/arch/x86/vtd.c, hypervisor/include/arch/x86/vtd.h
This patchset fixes MISRA-C violations in arch/x86/vtd.c
=>  hv:vtd: fix MISRA-C violations

hypervisor/arch/x86/e820.c
fix e820.c violations related misra c.
=> hv: fix e820.c violations

hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/cpu_caps.c, hypervisor/arch/x86/security.c, hypervisor/include/arch/x86/cpu.h
2) Fix procedure has more than one exit point.
=> hv: coding style: refine cpu related function to one exit

doc/tutorials/using_partition_mode_on_up2.rst
Fix the indentation to make a line part of the correct
paragraph (instead of having it erroneously displayed as
part of the previous code-block)
Tracked-On: #2031
=> Documentation: fix formatting in partition mode tutorial

hypervisor/include/public/acrn_common.h
Table contents weren't rendered correctly in
developer-guides/hld/hv-io-emulation.html, so
fix the doxygen comments.
Tracked-on: #1684
=> doc: fix vhm_request doxygen comment

devicemodel/hw/uart_core.c
Discard the input/output data when open tty file. To avoid the
mevent callback is triggered immediately when the fd is added to
epoll.
Also update the uart_drain only read the data from tty file when
fifo has available space.
Tracked-On: #2159
=> dm: flush the input/output during tty open.

hypervisor/arch/x86/virq.c
hv: virq: refine acrn_handle_pending_request() has more than one exit point
The MISRA-C Standards suggests procedures to be single exit.
hv: virq: refine acrn_handle_pending_request() use goto instruction
The MISRA-C Standards suggests not to use 'goto' instruction.
=> hv: virq: refine acrn_handle_pending_request() 

hypervisor/common/hypercall.c
=> hv: hypercall: fix "Procedure has more than one exit point"

devicemodel/core/hugetlb.c, devicemodel/core/main.c, devicemodel/core/smbiostbl.c, devicemodel/core/sw_load_bzimage.c, devicemodel/core/sw_load_common.c, devicemodel/core/sw_load_ovmf.c, devicemodel/core/sw_load_vsbl.c, devicemodel/core/vmmapi.c, devicemodel/hw/pci/core.c, devicemodel/hw/pci/gvt.c, devicemodel/hw/pci/npk.c, devicemodel/hw/pci/virtio/virtio_coreu.c, devicemodel/hw/pci/virtio/virtio_hdcp.c, devicemodel/hw/pci/virtio/virtio_net.c, devicemodel/hw/pci/xhci.c, devicemodel/hw/platform/rpmb/rpmb_backend.c, devicemodel/hw/platform/tpm/tpm.c, devicemodel/hw/platform/tpm/tpm_emulator.c, devicemodel/hw/platform/usb_mouse.c, devicemodel/include/dm.h, devicemodel/lib/dm_string.c
The patch fix some string operations issues and also improve readability
of several snippet.
Tracked-On: #2133
=> Remove banned func calls

devicemodel/core/main.c, devicemodel/core/vmmapi.c, devicemodel/include/public/vhm_ioctl_defs.h, devicemodel/include/vmmapi.h
This is the second part of IO completion polling patchset.
Tracked-On: #1821 
=> Ioreq optimization - 2nd part

devicemodel/core/hugetlb.c, devicemodel/core/main.c, devicemodel/core/smbiostbl.c, devicemodel/core/sw_load_bzimage.c, devicemodel/core/sw_load_common.c, devicemodel/core/sw_load_ovmf.c, devicemodel/core/sw_load_vsbl.c, devicemodel/core/vmmapi.c, devicemodel/hw/pci/core.c, devicemodel/hw/pci/gvt.c, devicemodel/hw/pci/npk.c, devicemodel/hw/pci/virtio/virtio_coreu.c, devicemodel/hw/pci/virtio/virtio_hdcp.c, devicemodel/hw/pci/virtio/virtio_net.c, devicemodel/hw/pci/xhci.c, devicemodel/hw/platform/rpmb/rpmb_backend.c, devicemodel/hw/platform/tpm/tpm.c, devicemodel/hw/platform/tpm/tpm_emulator.c, devicemodel/hw/platform/usb_mouse.c, devicemodel/include/dm.h, devicemodel/lib/dm_string.c
The patch fix some string operations issues and also improve readability
of several snippet.
Tracked-On: #2133
Signed-off-by: Shuo A Liu shuo.a.liu@intel.com
Reviewed-by: Yonghua Huang yonghua.huang@intel.com
=> remove banned APIs

hypervisor/arch/x86/mmu.c
Fix violations that attempt to change parameter
passed by value.
Tracked-On: #2056
=> hv: fix coding style violations in mmu.c

hypervisor/common/hypercall.c
Huihuang Shi (3):
hv: hypercall: fix simple violations of "Procedure has more than one
exit point"
fix it by use "if ... else ..." fmt.
hv: hypercall: fix complicated violations of "Procedure has more than
one exit point"
fix it by use "if ... else ..." fmt or add status.
hv: hypercall: fix "Procedure has more than one exit point"
fix it by split function into two.
V1->V2:
1.merge branches.
2.compact multiple lines into one.
=> hv: hypercall clean "Procedure has more than one exit point"

doc/developer-guides/coding_guidelines.rst, doc/developer-guides/index.rst
This patch introduces an initial draft of ACRN coding guidelines.
We will update this document gradually to support ACRN achieve
MISRA-C compliance.
=> doc: initial draft of ACRN coding guidelines

doc/conf.py
=> doc: update footer copyright year

hypervisor/arch/x86/assign.c
This patch fixes the remaining MISRA-C violations in arch/x86/assign.c
=> hv: assign: fix remaining MISRA-C violations

devicemodel/core/main.c
update acrn-dm comment, remove the series of dot
Tracked-On: #2036
Signed-off-by: Shuang Zheng shuang.zheng@intel.com
=> update acrn-dm comment, remove the series of dot

hypervisor/lib/crypto/crypto_api.c, hypervisor/lib/crypto/mbedtls/hkdf.c, hypervisor/lib/crypto/mbedtls/md.c, hypervisor/lib/crypto/mbedtls/md.h, hypervisor/lib/crypto/mbedtls/md_internal.h, hypervisor/lib/crypto/mbedtls/sha256.c
-remove goto
-remove multiple return
-Modify assignment operator in boolean expression
-Modify/fix code style violations
-fix attempt to change parameters passed by value
-fix value need U suffix
-fix use of mixed arithmetic
-fix assigment in expression
-other fix
Tracked-On: #861 
Signed-off-by: Chen Gang G <gang.g.chen@intel.com>
Reviewed-by: Bing Zhu <bing.zhu@intel.com>
=> fix MISRA C violations and code style

hypervisor/arch/x86/guest/guest.c, hypervisor/arch/x86/guest/vlapic.c
Solve some MISRA violation in two files
4b649cdb (HEAD -> misra, mygit/misra) HV: remove multi-returns in few routine in guest.c
15a7fa78 HV: remove multi returns in vlapic_set_apicbase
4e52b6fb HV: Remove goto in vlapic_read()
5aadb856 HV: remove multiple exits in vlapic_set_intr_ready()
Signed-off-by: Chaohong guo <chaohong.guo@intel.com>
=> Misra for lapic.c and guest.c

hypervisor/boot/acpi.c, hypervisor/boot/reloc.c, hypervisor/boot/sbl/abl_seed_parse.c, hypervisor/boot/sbl/multiboot.c, hypervisor/boot/sbl/sbl_seed_parse.c
To make sure the procedure has only one exit point without any goto expression.
=> HV: code style change for boot part code

hypervisor/dm/vioapic.c, hypervisor/dm/vpci/msix.c
Refine vioapic_indirect_write and vmsix_table_rw to one exit point.
=> hv: coding style: refine functions under dm/ to one exit point

hypervisor/arch/x86/guest/instr_emul.c
V1->V2:
rename is_exception_inject to has_exception.
V2->V3:
remove the else statement and add new if statement to check
has_exception.
Misra C requires not allowed to use goto.
=> fix "goto detected:exception_inject"

doc/tutorials/skl-nuc.rst
Include a line of script that download and untars the patch files
=> doc: update SKL NUC patch download instructions

hypervisor/arch/x86/guest/instr_emul.c
=> hv: inst_emul: clean the "Procedure has more than one exit point"

doc/conf.py
Add option in side-bar menu for 0.5 doc version
=> doc: add menu option for 0.5 docs

doc/developer-guides/coding_guidelines.rst
This patch adds more rules in coding guidelines.
=> doc: add more rules in coding guidelines

doc/release_notes_0.5.rst
Doc: Add release note for v0.5 release.
=> Doc: Add release note for v0.5 release.

hypervisor/lib/crypto/mbedtls/md.c, hypervisor/lib/crypto/mbedtls/md.h, hypervisor/lib/crypto/mbedtls/md_internal.h, hypervisor/lib/crypto/mbedtls/md_wrap.c, hypervisor/lib/crypto/mbedtls/sha256.c, hypervisor/lib/crypto/mbedtls/sha256.h
-Remove upper case
-Modify/fix code style violations
-fix value need U suffix
-Assignment operation in expression
-remove function like macros
v1->v2 fix assignment operation in expression
v2->v3 fix function like macros
Signed-off-by: Chen Gang G <gang.g.chen@intel.com>
=> hv: fix MISRAC violations for crypto lib

hypervisor/boot/acpi.c
1. to avoid data type cast when using 'global_rsdp'
2. other minor fix
=> hv: fix coding style violations in acpi.c

doc/release_notes_0.5.rst
Doc: Add one new known issue into v0.5 release note
=> Doc: Add one new known issue into v0.5 release note

hypervisor/arch/x86/virq.c
The MISRA-C Standards suggests procedures to be single exit
=> hv:fix MISRA-C violation in virq.c

devicemodel/samples/apl-mrb/launch_uos.sh
1. remove the sd card option to reducing the boot time.
Tracked-On: #2331
=> launch_uos.sh remove sd card passthru option

devicemodel/samples/nuc/launch_uos.sh, doc/getting-started/apl-nuc.rst
Doc: Remove CL release number from GSG document
=> Doc: Remove CL release number from GSG document

hypervisor/boot/reloc.c
The patch is to fix MISRA violation in reloc.c by:
- remove multi-returns in relocate();
- remove non useful checking in relocate();
- add suffix U to macro definition
Signed-off-by: Chaohong guo <chaohong.guo@intel.com>
=> HV:  MISRA clean in reloc.c

doc/developer-guides/coding_guidelines.rst
- update and add some rules in coding guidelines
=> doc: update coding guidelines

doc/tutorials/rt_linux.rst
Need to delete '# CONFIG_BLK_DEV_NVME is not set' to enable NVME driver
=> Need to delete '# CONFIG_BLK_DEV_NVME is not set' to enable NVME driver

hypervisor/debug/profiling.c, hypervisor/include/debug/profiling_internal.h
The previous patch was revised base on Eddie Dong's recommendation. The diff needs to ported to the stable branch to make both branches have the same change.
Tracked-On: #2422
=> Porting the patch from master branch

devicemodel/hw/platform/hpet.c
Need to properly remove and free its MMIO entry during deinit.
Tracked-On: #2453
=> dm: vhpet: fix vHPET memory leak on device reset

doc/tutorials/using_sbl_on_up2.rst
add build option on the using_sbl_on_up2.rst which has been modified following dbkinder's comments, replace PR 2483
=> doc:add build option on the using_sbl_on_up2.rst

doc/release_notes_0.6.rst
Initial draft of release notes provided by Nanlin.
=> doc: initial draft of 0.6 release notes

doc/tutorials/create-up2-images.sh
modify create up2 image for changing uos default bootargs
=> doc: modify create up2 image for changing uos default bootargs

doc/tutorials/using_sbl_on_up2.rst
=> doc: fix typo in using_sbl doc

devicemodel/hw/pci/virtio/virtio_console.c
Socket is not currently supported as backend for virtio-console.
Kata containers require socket backend for virtio-console in order to
communicate between the agent running in the VM and the proxy running
in the host. In order to support Kata with ACRN, this feature is required.
v1-->v2:
Prevent new accepts on an already established socket connection. This
removes the need for accepted_fd and accept_evp varibles introduced in
previous patch.
v2-->v3:
Fixed coding style and removed debug prints.
Tracked-On: #2448
=> dm: Add socket backend support for virtio-console

doc/tutorials/create-up2-images.sh, doc/tutorials/using_sbl_on_up2.rst
use weston instead of ias by bundle add x11-server
=> doc: use weston instead of ias by bundle add x11-server

doc/release_notes_0.6.rst
add Fixed issues and known issues in release_notes
=> doc: add Fixed issues and known issues in release_notes_0.6

doc/release_notes_0.6.rst
=> doc: fix formatting issues in v0.6 release notes

doc/tutorials/using_partition_mode_on_up2.rst
Update the using_partition_mode_on_up2.rst to accormodate the latest
configuration method for up2 partition mode.
=> doc: update partition mode config on up2

doc/tutorials/using_partition_mode_on_up2.rst
=> doc: add review comments to up2 doc

doc/conf.py
=> doc: add 0.6 to doc version menu

doc/release_notes_0.6.rst
add features list on release_note_0.6
=> add features list on release_note_0.6

doc/release_notes_0.6.rst
Add one more known issue about #2516
=> Add one more known issue

devicemodel/samples/apl-mrb/launch_uos.sh
add log for uos when to begin
Tracked-On: #2552
=> dm: add specify log for starting uos

devicemodel/hw/pci/xhci.c
To reset USB DRD role is one workaround for adb lost issue with xDCI
passthrough which reproduced in S3 stress test.
This workaround will involve the system global reset if xDCI working in
SuperSpeed mode. This is maybe caused by PMC firmware can't graceful
power gate the xDCI during S3 suspend. The current USB DRD driver will
set STATIC switch bits which will cause ungraceful DRD switch, it may
make the xDCI enter a unknown state, then involved this global reset
issue.
BTW, base on latest code base, the adb lost issue can't reproduce even
remove this workaround.
So remove the old workaround for above reasons.
Tracked-On: #2557
Signed-off-by: Yu Wang <yu1.wang@intel.com>
=> DM USB: xHCI: do not reset DRD role during S3 process

devicemodel/hw/platform/acpi/acpi.c
patch is from Alex Du for IASL tool updated to support
ACPI 6.3 version.
=> DM: modify acpi for IASL to support ACPI6.3

devicemodel/arch/x86/pm.c
Listen to power button state via /dev/input/event0. When the power
button is pressed, then set PWRBTN_STS bit. If PWRBTN_EN is set, the
sci interrupt is triggered.
For suspend or shutdown of UOS by power button, needs UOS to configure
the default behavior of the power button.
Tracked-On: #2560
=> dm: implement power button for power managerment

hypervisor/arch/x86/configs/apl-mrb/pt_dev.c, hypervisor/arch/x86/configs/apl-mrb/ve820.c, hypervisor/arch/x86/configs/dnv-cb2/pt_dev.c, hypervisor/arch/x86/configs/dnv-cb2/ve820.c, hypervisor/arch/x86/configs/partition_config.c, hypervisor/arch/x86/configs/sharing_config.c, hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/cpu_state_tbl.c, hypervisor/arch/x86/e820.c, hypervisor/arch/x86/gdt.c, hypervisor/arch/x86/guest/vm.c, hypervisor/arch/x86/init.c, hypervisor/arch/x86/ioapic.c, hypervisor/arch/x86/irq.c, hypervisor/arch/x86/lapic.c, hypervisor/arch/x86/mmu.c, hypervisor/arch/x86/notify.c, hypervisor/arch/x86/page.c, hypervisor/arch/x86/pagetable.c, hypervisor/arch/x86/static_checks.c, hypervisor/arch/x86/timer.c, hypervisor/arch/x86/trampoline.c, hypervisor/arch/x86/vmx.c, hypervisor/arch/x86/vtd.c, hypervisor/boot/include/acpi.h, hypervisor/include/arch/x86/e820.h, hypervisor/include/arch/x86/guest/vm.h, hypervisor/include/arch/x86/idt.h, hypervisor/include/arch/x86/ioapic.h
cleanup header file for arch folder, only include some necessary header files,
doesn't include hypervisor.h
=> Cleanup header file for arch folder

devicemodel/hw/pci/virtio/virtio_gpio.c
When the backend completes a GPIO request, it returns a valid length
to ensure that response correct.
=> DM: virtio-gpio: return a valid length for GPIO request

hypervisor/boot/sbl/multiboot.c
Purpose of these two patches:
1) fix issues on assigning bootargs_load_addr so it's possible to boot pre-launched VMs at > 4GB address, and safer for SOS.
2) make ramdisk input available for pre-launched VMs.
3) Fix ramdisk_load_addr assignment issue
4) remove duplicated init_vm_boot_info()
=> hv: improve multiboot guest image load addresses assignment

doc/getting-started/apl-nuc.rst
* Remove the older kernel version(pk414)
* Add a one-line command to insert the PARTUUID into the acrn.conf
file (without copying it all manually)
=> Documentation: tweak GSG

doc/developer-guides/GVT-g-kernel-options.rst, doc/release_notes_0.5.rst, doc/tutorials/rt_linux.rst, doc/tutorials/trustyACRN.rst
Fix misspellings missed during regular reviews.
=> doc: fix misspellings

devicemodel/samples/apl-mrb/launch_uos.sh
fix AaaG boot panic issue
Tracked-On: #2652
Signed-off-by: Marcin Pietraszko <marcin.pietraszko@intel.com>
=> fix AaaG boot panic issue

devicemodel/arch/x86/pm.c
Implement power button emulation for acrnctl suspend and stop commands, and check pm1_control SCI_EN bit before trigger SCI.
Yuan Liu (2):
dm: power button emulation by acrnctl command.
dm: check SCI_EN bit of pm1_control before trigger SCI
Tracked-On: #2560
=> power button emulation by acrnctl command

doc/developer-guides/coding_guidelines.rst
This patch adds some rules related to coding style.
=> doc: add some rules related to coding style

hypervisor/arch/x86/guest/vlapic.c
This commit extracts the common logic of vlapic_calc_dest() and vlapic_calc_dest_lapic_pt()
to static inline functions, in order to make vlapic_calc_dest() clean and easy to read.
=> hv: refine vlapic_calc_dest()

doc/developer-guides/coding_guidelines.rst
This patch updates the format in coding style part.
=> doc: update the format in coding style part

doc/developer-guides/coding_guidelines.rst
This patch adds some comments for coding guidelines.
=> doc: add some comments for coding guidelines

devicemodel/hw/pci/passthrough.c
Fix potential memory leakage in some error case handling.
Tracked-On: #2705
=> dm: passthru: fix potential memory leak

devicemodel/hw/pci/xhci.c, devicemodel/samples/apl-mrb/launch_uos.sh
fix SWWDT_UNHANDLED  issue
Tracked-On: #2633
=> dm:usb: fix SWWDT_UNHANDLED 

devicemodel/samples/nuc/launch_zephyr.sh
This patch add one sample script to launch zephyr as guest.
Tracked-On: #2713
=> DM: Add sample script to launch zephyr as guest

devicemodel/hw/pci/xhci.c, devicemodel/hw/platform/usb_pmapper.c
fix possible memory leak for usb.
Tracked-On: #2704
=> dm: usb: fix possible memory leak

hypervisor/arch/x86/vtd.c
Check bus limit when add/remove device in iommu.
Tracked-On: #2743
=> hv: vtd: check bus limit when add/remove device

devicemodel/hw/pci/passthrough.c
Fix potential memory leakage in some error case handling.
Tracked-On: #2704
=> dm: passthru: fix potentail mem leaks

hypervisor/arch/x86/vtd.c
Input parameter "bus" of assign_iommu_device/unassign_iommu_device may be from hypercall.
And the conext tables are static allocated according to CONFIG_IOMMU_BUS_NUM.
Need to check the bus value to avoid access invalid memory address with invalid value.
Tracked-On: #2743
=> hv: vtd: check bus number when assign/unassign device

doc/release_notes_0.7.rst
Review draft of 0.7 release notes
=> doc: add 0.7 release notes

doc/release_notes_0.7.rst
remove apl_sdc_stable branch story
=> doc: remove apl_sdc_stable branch story

devicemodel/hw/uart_core.c
This patch marks thre_int_pending as true when THR is empty.
Tracked-On: #2713
Signed-off-by: Eddie Dong <eddie.dong@intel.com>
=> DM: Mark thre_int_pending as true when THR is empty

doc/developer-guides/coding_guidelines.rst
This patch adds some rules related to naming convention.
=> doc: add some rules related to naming convention

tools/acrn-manager/acrnd.c
The boards without IOC don't need to call get_sos_wakeup_reason function.
The HW IOC can be detected in runtime,via checking "/dev/cbc-early-signals" node.
Tracked-On：https://github.com/projectacrn/acrn-hypervisor/issues/1996
Signed-off-by: liuyonggang <yonggangx.liu@intel.com>
=> Tools: Acrnd fix reporting unnecessary error on NUC and UP2

devicemodel/hw/pci/xhci.c, devicemodel/hw/platform/usb_pmapper.c, devicemodel/include/usb_core.h
This patch set fixes the failure of CTS 'USB Device Test' itme.
Tracked-On: #2800
=> DM USB: xHCI: Fix CTS test failure

devicemodel/core/main.c
Applying realtime scheduler to vcpu0 thread could trigger
stability issue. So revert it here.
Tracked-On: #2717
=> acrn-dm: revert the change which apply realtime schedule to vcpu0

doc/developer-guides/coding_guidelines.rst
This patch adds some rules related to implementation-specific
behaviors.
=> doc: add rules related to implementation-specific behaviors

devicemodel/hw/pci/xhci.c, devicemodel/hw/platform/usb_pmapper.c
This PR fix two stability issues.
Tracked-On: #2823
Tracked-On: #2824
=> Fix two stability issues

hypervisor/boot/sbl/multiboot.c
To merge the multiboot bootargs within sbl_init_vm_boot_info(), buffer
overflow could happen when it doesn't provide correct 'dmax' argument
to strncpy_s().
Also, currently it doesn't check the availability of the dest buffer before
overwriting '\0' with a whitespace, which theoretically the dest string
could end up with no null terminator within it's array boundary.
This patch also creates a separate function to merge the cmdline strings,
because after the above fixes some lines in sbl_init_vm_boot_info()
function could have up to 7 tabs in front of the first character, which
looks messy and sbl_init_vm_boot_info() is getting too complicated.
Tracked-On: #2806
Reviewed-by: Eddie Dong …
=> hv: fix potential buffer overflow in sbl_init_vm_boot_info()

devicemodel/samples/apl-mrb/launch_uos.sh, doc/faq.rst
Add 2 new FAQs
(1) How to change the assigned output for one UOS instead of the default setting?
(2) Why does ACRN need to be know how much RAM the system has?
=> doc: Add 2 new FAQs

doc/tutorials/create-up2-images.sh
Signed-off-by: Lei Lu <leix.lu@intel.com>
=> doc: update UP2 sample directory name in create-up2-image.sh

doc/developer-guides/coding_guidelines.rst
This patch adds some rules related to language extensions.
=> doc: add some rules related to language extensions

doc/developer-guides/GVT-g-kernel-options.rst, doc/developer-guides/index.rst, doc/developer-guides/kernel-parameters.rst
=> doc: add kernel parameters documentation

hypervisor/arch/x86/guest/trusty.c
Refine return value checking in functions.
Tracked-On: #2874
=> hv: trusty: minor change of coding style

hypervisor/arch/x86/cpu_caps.c, hypervisor/arch/x86/guest/instr_emul.c, hypervisor/arch/x86/guest/pm.c, hypervisor/arch/x86/guest/vlapic.c, hypervisor/arch/x86/security.c, hypervisor/debug/dbg_cmd.c, hypervisor/debug/npk_log.c, hypervisor/debug/shell.c, hypervisor/dm/vpci/vmsix.c
All if . . else if constructs shall be
terminated with an else statement.
Acked-by: Eddie Dong <eddie.dong@intel.com
=> hv: fix "Else alternative missing in if."

doc/user-guides/acrn-dm-parameters.rst
This patch update documents for "--rtvm" parameter.
Tracked-On: #2865
=> doc: update documents for "--rtvm" parameter

devicemodel/hw/pci/virtio/virtio_block.c
Add VIRTIO_BLK_F_RO feature bit for virtio-blk.
Tracked-On: #2887
=> dm: storage: add read-only feature for virtio-blk

doc/developer-guides/coding_guidelines.rst
This patch adds some rules related to function documentation.
Tracked-On: #1844
=> doc: add some rules related to function documentation

doc/developer-guides/coding_guidelines.rst
This patch adds rules in coding guidelines.
=> doc: add rules in coding guidelines

doc/release_notes_0.8.rst
=> doc: add v0.8 release note

doc/scripts/publish-index.html
Try to reduce the page flash when redirecting to latest/index.html
=> doc: tweak home page redirect to latest

devicemodel/core/vmmapi.c, doc/user-guides/acrn-shell.rst, hypervisor/arch/x86/configs/vm_config.c, hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/guest/trusty.c, hypervisor/arch/x86/guest/vm.c, hypervisor/common/hypercall.c, hypervisor/debug/profiling.c, hypervisor/debug/shell.c, hypervisor/debug/shell_priv.h, hypervisor/include/arch/x86/guest/vm.h, hypervisor/include/arch/x86/vm_config.h, hypervisor/include/debug/profiling_internal.h, hypervisor/include/public/acrn_common.h, hypervisor/scenarios/logical_partition/vm_configurations.c, hypervisor/scenarios/sdc/vm_configurations.c
- use term of UUID;
- return bool in sanitize_vm_config;
- make vm id statically by uuid;
- show VM UUID in shell
=> HV: series patch to fix vm id by uuid

doc/developer-guides/hld/hv-vt-d.rst, hypervisor/arch/x86/vtd.c, hypervisor/common/hypercall.c, hypervisor/dm/vpci/vpci.c, hypervisor/include/arch/x86/vtd.h
- rename 'assign_iommu_device' to 'assign_pt_device'
- rename 'unassign_iommu_device' to 'unassign_pt_device'
Acked-by: Eddie Dong <eddie.dong@inte.com>
=> hv: rename 'assign_iommu_device' and 'unassign_iommu_device'

tools/acrn-manager/acrnd.c
There is an enhancement requirement about the VM auto-start for debug:
allowing the end user to optionally prevent automatic and immediate launching
of all Guest VM.
This commit adds a parameter to acrnd indicating the delay time before VM
auto-start, within the delay time, user could stop acrnd to prevent the VM
auto-start. The default delay time is 0.
And definition of MACROs and static varialbes are moved to the beginning of
the source file.
Tracked-On: #2947
=> tools: acrn-mngr: add delay to allow user to prevent VM autostart for debug

devicemodel/arch/x86/pm.c, devicemodel/core/mem.c, devicemodel/hw/pci/core.c, devicemodel/hw/pci/virtio/virtio_input.c, devicemodel/hw/platform/acpi/acpi.c, devicemodel/hw/uart_core.c, devicemodel/include/acpi.h, devicemodel/include/block_if.h
This patchset includes the patches used to enable WaaG on ACRN. All the patches in this patchset are for device model. Patches from hypervisor will be sent later separately.
Tracked-On: #2962
=> Waag enabling

hypervisor/scenarios/logical_partition/vm_configurations.c
=> HV: enable lapic passthru for logical partition VM1

hypervisor/common/hypercall.c
The previous will not check the EPT gpa correctly. This patch try to fix this.
=> hv: ept: correct EPT mapping gpa check

hypervisor/common/ptdev.c
Currently ptdev_release_all_entries() calls ptirq_release_entry() to
release ptdev IRQs, which is not sufficient because free_irq() is not
included in ptirq_release_entry().
Furthermore, function ptirq_deactivate_entry() and ptirq_release_entry()
have lots of overlaps which make the differences between them are not
clear.
This patch does:
- Adds ptirq_deactivate_entry() call in ptdev_release_all_entries() if the
irq has not already freed.
- Remove unnecessary code from ptirq_deactivate_entry() to make it do the
exact opposite to function ptirq_activate_entry(), except that
entry->allocated_pirq is not reset, which is not necessary.
- Added the missing del_timer() to ptirq_release_entry() to make it almost
opposite to ptirq_alloc_entry(); Added memset() to clear the whole entry,
which …
=> hv: free ptdev device IRQs when shutting down VM

devicemodel/hw/uart_core.c
When acrn-dm is started by acrnd as a background process, STDIN is
redirected to journal. In this case mevent_add cannot be called on
the fd of STDIN.
Tracked-On: #2998
=> dm: uart: use mevent_add only when it is a tty

hypervisor/arch/x86/guest/instr_emul.c
v1-v2:
1) Detail the comments which instruction will raise issue because of the wrong opsize update.
For the instructions which we support now, only for movsx, movzx.
2) Detail when we need to calculate memory operand.
v1:
For some instructions (like movsx, movzx which we support), there're two operands
and the source operand size is not equal to the dest operand size. In this case,
if we update the memory operand size according to the bit 0(w bit) of opcode,
we will lost the register operand size. This patch tries to fix this by calculating
memory operand size when we want to use it.
1) For some instructions (like movsx, movzx which we support), there're two operands
and the source operand size is not equal to the dest operand size. In this case,
if we update the memory operand size …
=> hv: instr_emul: fix operand size decode

doc/developer-guides/c_coding_guidelines.rst
This patch adds rules in C coding guidelines.
=> doc: add rules in C coding guidelines

doc/faq.rst
Update FAQ about compilation issue workaround on Fedora 29
Signed-off-by: zhangyun <yunxzhang@intel.com>
Tracked-On: #2457
=> doc: How to build ACRN on Fedora 29

devicemodel/hw/uart_core.c
For Linux kernel, the UART driver will disable IER.THRE. But for Windows, it
will keep IER.THRE turn on then cause interrupt storm.
From pc16550d UART spec, INTR PIN description:
"Interrupt. This pin goes high whenever any one of the following interrupt types
has an active high condition and is enabled through the IER Receiver Error Flag;
Received Data Available timeout (FIFO Mode only); Transmitter Holding Register
Empty; and MODEM Status. The INTR signal is reset low upon the appropriate
interrupt service or a Master Reset operation."
And Interrupt Reset Control of Transmitter Holding Register Empty Interrupt
description:
"Reading the IIR Register (if source of interrupt) or Writing into
the Transmitter Holding Register"
The datasheet hasn't describe very clear if the THRE interrupt …
=> dm: uart_core: fix uart dm cause interrupt storm issue

doc/tutorials/rt_linux.patch, doc/tutorials/rt_linux.rst
Signed-off-by: Li, Wilson <wilson.li@intel.com>
=> Updated GSG of using RT Linux as RTVM in accordance with acrn-kernel v4.19.28

hypervisor/arch/x86/Kconfig, hypervisor/scenarios/industry/vm_configurations.c, hypervisor/scenarios/industry/vm_configurations.h
This commmit added one more guest VM to the industry scenario, to
be aligned with the HLD for the industry usage.
Tracked-On: #3039
=> hv: add one more guest VM to the industry scenario

devicemodel/Makefile, devicemodel/core/main.c, devicemodel/core/monitor.c, devicemodel/core/vmmapi.c, devicemodel/hw/pci/core.c, devicemodel/include/log.h, devicemodel/log/kmsg_logger.c, devicemodel/log/log.c, devicemodel/samples/apl-up2/launch_uos.sh, devicemodel/samples/nuc/launch_uos.sh
add log macro/functions for ACRN-DM; add an input parameters to set by user for logger configure in launch script.
TODO: add the logger to save log in hard disk.
Tracked-On: #3012
=> DM: add log system

doc/developer-guides/asm_coding_guidelines.rst, doc/developer-guides/coding_guidelines.rst
This patch creates initial draft of Assembly coding guidelines.
=> doc: initial draft of Assembly coding guidelines

hypervisor/dm/vuart.c
1. Add brackets for if/else sentence.
2. Add suffix 'U' for the unsigned constants.
3. Split vuart_write as its cyclomatic complexity is greater than 20.
=> HV: vuart: cleanup MISRA-C issues 

devicemodel/samples/nuc/launch_vxworks.sh
This patch add one sample script to launch VxWorks as guest.
=> DM: Add one sample script to launch VxWorks as guest

doc/release_notes_1.0.rst, doc/tutorials/using_sbl_on_up2.rst
=> doc: Add v1.0 release note

doc/release_notes_1.0.rst
Fix release intro description, misspellings, remove trailing blanks,
trademark use.
=> doc: Update 1.0 release notes

doc/conf.py
Update the /latest documents with a menu choice for the 1.0 release
docs.
=> doc: add v1.0 doc menu to master

doc/release_notes_1.0.rst
Update the high-level summary.
=> doc: Update intro to 1.0 release notes

doc/release_notes_1.0.rst
Change some of the words from the 1st paragraph.
=> doc: release note v1.0, correct some words.

devicemodel/hw/pci/core.c
AcrnGT traps and intercepts the memory region defined by PCI bar in
service OS kernel driver. No need to register the bar associated region
in dm. By the way, some OS changes BAR start address and there is no
mechanism to reflect the gvt changes back to dm. It causes problem that
other devices may register new region which falls in GVT `old` region,
and leads to hypervisor crash.
v4: Add FIXME tag. It's a short term solution before migrated to OVMF
v3: rewording the comments
v2: removed unnecessary braces and use printf to log (Peter)
Tracked-On: #2976
Signed-off-by: Liu Xinyun <xinyun.liu@intel.com>
=> dm: not register/unregister gvt bar memory

hypervisor/arch/x86/cpu.c
This patch refines 'init_percpu_lapic_id' to move the error
handling to 'init_pcpu_pre'.
=> hv: refine 'init_percpu_lapic_id'

devicemodel/samples/nuc/launch_win.sh
This patch adds one sample script to launch Windows as guest.
Tracked-On: #3099
=> dm: add sample script to launch Windows as guest

devicemodel/core/main.c
This patch tries to fetch max vcpu per vm from HV instead of hardcode in DM.
Tracked-On: #3116
=> DM: Get max vcpu per vm from HV instead of hardcode

devicemodel/Makefile, devicemodel/core/hugetlb.c, devicemodel/core/monitor.c, devicemodel/hw/pci/virtio/virtio_audio.c, devicemodel/hw/pci/virtio/virtio_hyper_dmabuf.c, devicemodel/hw/pci/virtio/virtio_ipu.c, devicemodel/hw/pci/virtio/virtio_rnd.c, hypervisor/arch/x86/guest/instr_emul.c, tools/acrn-crashlog/acrnprobe/main.c, tools/acrn-manager/acrn_mngr.c, tools/acrn-manager/acrn_vm_ops.c, tools/acrn-manager/acrnctl.c, tools/acrn-manager/acrnd.c
Fix build issues with gcc 9.1 version
Tracked-On: #3121
=> build: fix build issue with latest gcc

hypervisor/arch/x86/cpu_caps.c, hypervisor/arch/x86/guest/vcpu.c, hypervisor/arch/x86/security.c, hypervisor/arch/x86/vtd.c, hypervisor/common/schedule.c, hypervisor/include/arch/x86/guest/vcpu.h
check spinlock current usage, if not need, remove it; if needed, add it.
Tracked-On: #3130
=> check spinlock usage and do cleanup

doc/getting-started/apl-nuc.rst, doc/tutorials/agl-vms.rst, doc/tutorials/using_partition_mode_on_up2.rst
bare-metal-install is replaced with bare-metal-install-server due to an recent change by clearlinux.
=> doc: Update clearlinux os installation guide link.

doc/tutorials/using_vxworks_as_uos.rst
This patch adds tutorial about using VxWorks as guest.
=> Doc: Add tutorial about using VxWorks as uos

doc/developer-guides/c_coding_guidelines.rst
This patch updates coding guidelines about naming convention.
=> doc: update function naming convention

devicemodel/samples/nuc/launch_hard_rt_vm.sh
Tracked-On: #3188
Signed-off-by: ZhangYun <yunx.zhang@intel.com>
=> dm: update uos path in launch_hard_rt_vm.sh

doc/tutorials/rt_linux.rst
Signed-off-by: Zhang, Yun <yunx.zhang@intel.com>
=> doc: Update Using PREEMPT_RT-Linux for real-time UOS

doc/developer-guides/c_coding_guidelines.rst
- update prefix format in coding guidelines
=> doc: update prefix format in coding guidelines

doc/tutorials/using_partition_mode_on_nuc.rst
Fix formatting missed during regular review.
=> doc: fix formatting in partition doc

devicemodel/hw/pci/virtio/virtio_console.c
Refine the virtio-console options parse code, so that no need to pass
all the variables as parameters to the backend adding function.
Adding the feature of communication between VMs using virtio-console
based on appointed socket file. Not appointing the socket type will set
the socket type to be server in default.
=>  dm: support VMs communication with virtio-console

doc/tutorials/rt_linux.rst
Signed-off-by: Li, Wilson <wilson.li@intel.com>
=> Added recommended BIOS settings for better real-time performance.

doc/getting-started/building-from-source.rst
Fixes a small typo. See also https://github.com/projectacrn/projectacrn.github.io/pull/18
=> Fix a small typo

doc/getting-started/building-from-source.rst
Rather than have the developer make edits, it was easier to merge
PR #3246 and submit a new PR with improvements.
=> doc: improve clarity of build-from-source intro

devicemodel/samples/nuc/launch_win.sh
Enable audio device by default on WaaG
Tracked-On: #3257
=> dm: enable audio passthrough device.

devicemodel/core/vrpmb.c
Replace assert() with explicit parameter checking and error handling.
=> DM: vrpmb: replace assert() with return false

doc/developer-guides/hld/hv-cpu-virt.rst, doc/developer-guides/hld/hv-memmgt.rst, doc/release_notes_0.2.rst, hypervisor/arch/x86/guest/ept.c, hypervisor/arch/x86/guest/trusty.c, hypervisor/arch/x86/guest/vlapic.c, hypervisor/arch/x86/guest/vm.c, hypervisor/arch/x86/guest/vmtrr.c, hypervisor/common/hypercall.c, hypervisor/dm/io_req.c, hypervisor/dm/vpci/pci_pt.c, hypervisor/include/arch/x86/guest/ept.h
Rename ept_mr_add to ept_add_mr
Rename ept_mr_modify to ept_modify_mr
Rename ept_mr_del to ept_del_mr
=> hv: ept: unify EPT API name to verb-object style

devicemodel/hw/pci/passthrough.c
Remove the use of assert() in passthrough driver.
=> dm: passthru: remove the use of assert()

devicemodel/hw/pci/virtio/virtio_net.c
This patch is to clean up assert from virtio-net.
=> dm: virtio-net: clean up assert

devicemodel/hw/block_if.c, devicemodel/hw/pci/ahci.c, devicemodel/hw/pci/virtio/virtio_block.c
=> Assert clean for block_if virtio-block and ahci

hypervisor/arch/x86/guest/pm.c, hypervisor/arch/x86/guest/vcpu.c, hypervisor/boot/cmdline.c, hypervisor/debug/console.c, hypervisor/dm/vuart.c
MISRA-C standard requires the type of result of expression in if/while pattern shall be boolean.
=> HV: fix expression is not boolean

devicemodel/hw/pci/virtio/virtio_input.c
clean up assert in virtio_input.c
Tracked-On: #3303
=> dm: clean up assert in virtio_input.c

devicemodel/hw/pci/virtio/virtio_audio.c
clean up assert from virtio_audio
Tracked-On: #3301
=> dm: clean up assert in virtio_audio.c

devicemodel/hw/pci/virtio/virtio.c
clean up assert in virtio.c
Tracked-On: #3302
=> dm: clean up assert in virtio.c

doc/user-guides/acrn-shell.rst
This patch updates acrn-shell.rst for new 'version' cmd.
Tracked-On: #3310
=> Doc: Update acrn-shell.rst for new 'version' cmd

tools/acrn-manager/README.rst
Document the acrnd -t, and acrnctl add -C options, noted as missing in
PR #3137
=> doc: update acrnd/acrnctl option docs

devicemodel/hw/pci/virtio/virtio_rpmb.c
clean up assert from virtio rpmb module.
Signed-off-by: dengwei <wei.a.deng@intel.com>
Signed-off-by: yingbinx <yingbinx.zeng@intel.com>
=> DM: virtio_rpmb: clean up assert

devicemodel/hw/pci/virtio/virtio_console.c
Bug fix for parsing options, as the vritio-console support multiple
virtio serial ports, and the parameters is split by ',':
virtio-console,[@]stdio|tty|pty|file:portname[=portpath]\
[,[@]stdio|tty|pty|file:portname[=portpath]]
But the previous patch "refine console options parse code" not
cover this case, can only parse one port config. Fix it in this patch.
Tracked-On: #3337
Acked-by: Wang Yu <yu1.wang@intel.com>
=> DM: virtio-console: bug fix for parsing options

doc/release_notes_1.1.rst
=> doc: Add v1.1 release note

doc/tutorials/acrn-dm_QoS.rst, tools/acrn-manager/README.rst
Modify 'launch_UOS.sh' to 'launch_uos.sh' and provide an example for
the script which is support '-C' option.
=> doc: Update acrn-manager README and QoS introduction

doc/conf.py
Update the /latest/ (master) version of the docs to provide the menu
choice for the v1.1 release.
=> doc: update doc version menu

devicemodel/hw/pci/virtio/virtio_rnd.c
clean up assert in virtio_rnd.c
=> dm: clean up assert in virtio_rnd.c

hypervisor/arch/x86/guest/pm.c, hypervisor/arch/x86/seed/seed_abl.c, hypervisor/arch/x86/vmx.c, hypervisor/boot/cmdline.c, hypervisor/boot/guest/vboot_info.c, hypervisor/common/hypercall.c, hypervisor/common/trusty_hypercall.c, hypervisor/debug/console.c, hypervisor/debug/dbg_cmd.c, hypervisor/debug/dump.c, hypervisor/debug/hypercall.c, hypervisor/debug/npk_log.c, hypervisor/debug/shell.c, hypervisor/debug/trace.c, hypervisor/dm/vuart.c, hypervisor/lib/stack_protector.c, hypervisor/release/console.c
change some APIs to static or include  the header file
=> hv:fix "no prototype for non-static function"

doc/tutorials/using_celadon_as_uos.rst
Add introduction of launching Celadon User OS
=> doc: Add introduction of launching Celadon User OS

doc/tutorials/rtvm_workload_design_guideline.rst
a quick guideline document help RTOS designer/developer to design
his/her RT workload based on RTVM
=> doc: add guideline for RTVM workload design

doc/tutorials/rtvm_workload_design_guideline.rst
=> doc: fix typos in rtvm workload design doc

hypervisor/arch/x86/configs/vmptable.c, hypervisor/arch/x86/guest/trusty.c, hypervisor/arch/x86/guest/vcpuid.c, hypervisor/arch/x86/ioapic.c, hypervisor/arch/x86/seed/seed.c, hypervisor/boot/cmdline.c, hypervisor/boot/guest/vboot_info.c, hypervisor/debug/console.c, hypervisor/debug/profiling.c, hypervisor/debug/shell.c, hypervisor/dm/vrtc.c, hypervisor/include/arch/x86/apicreg.h, hypervisor/include/dm/mptable.h
ACRN Coding guidelines requires type conversion shall be explicity.
=> HV: fix violations touched type conversion

hypervisor/arch/x86/guest/vcpu.c
ACRN coding guidelines banned -- or ++ operations.
V1->V2:
add comments to struct stack_frame
=> HV: fix "use -- or ++ operations"

devicemodel/hw/block_if.c, devicemodel/hw/platform/acpi/acpi.c, devicemodel/log/disk_logger.c, devicemodel/log/kmsg_logger.c, hypervisor/arch/x86/guest/assign.c, hypervisor/arch/x86/lapic.c, hypervisor/arch/x86/notify.c, tools/acrn-crashlog/common/log_sys.c, tools/acrn-crashlog/usercrash/crash_dump.c
These patches fix some issues reported by penetration test.
1, fix some potential array overflow risk
2, remove unsafe apis in dm log
3, fix variable argument list read without ending with va_end
4, fix variable argument list read without ending with va_end
5,  fix some possible memory leak
Tracked-On: #3394 
Tracked-On: #3395 
Tracked-On: #3396 
Tracked-On: #3397 
Acked-by: Gang Chen <gang.c.chen@intel.com>
=> HV: fix some issues reported by penetration test

doc/getting-started/apl-nuc.rst
Signed-off-by: yunzha4x <yunx.zhang@intel.com>
=> doc:Update Getting started guide for Intel NUC

doc/tutorials/using_windows_as_uos.rst
Update WaaG document with Windows (upper case) and step numbering.
=> doc: fix format in WaaG document

doc/tutorials/using_partition_mode_on_nuc.rst
Signed-off-by: yunzha4x <yunx.zhang@intel.com>
=> doc: update using_partition_mode_on_nuc nuc7i7bnh to nuc7i7dnb

devicemodel/hw/pci/virtio/virtio_console.c
Add feature that client uos can still connect to server uos after
rebooting.
Tracked-On: #3459
=> dm: support VMs communication with virtio-console

doc/user-guides/acrn-dm-parameters.rst
Added ovmf NV storage writeback option "w" description and usage example.
=> doc: Add ovmf NV storage writeback option description

devicemodel/hw/pci/xhci.c, devicemodel/hw/platform/usb_pmapper.c
This patch series enable SSD support for USB mediator.
Tracked-On: #3486
=> Fix USB SSD issue for USB mediator

hypervisor/arch/x86/timer.c
In current code, the timer_list for per cpu can be accessed both in
vmexit and softirq handler. There is a case that, the timer_list is
modifying in vmexit, but an interrupt occur, the timer_list is also
modified in softirq handler. So the time_list may in unpredictable
state. In some platforms, the hv console may hang as its timer handler
is not invoked because of the corruption for timer_list.
So, to fix the issue, disable the interrupt before modifying the
timer_list.
Tracked-On: #3512
=> softirq: disable interrupt when modify timer_list

hypervisor/arch/x86/guest/vmcall.c
For non-trusty hypercalls, HV should inject #GP(0) to vCPU if they are
from non-ring0 or inject #UD if they are from ring0 of non-SOS. Also
we should not modify RAX of vCPU for these invalid vmcalls.
Tracked-On: #3497
=> HV: inject exception for invalid vmcall

doc/release_notes/release_notes_1.0.1.rst
=> doc: release notes v1.0.1

doc/release_notes/release_notes_1.0.1.rst
Fix some wording, table formatting, and links to issues and commits from
the original PR #3515
=> doc: update v1.0.1 release notes

doc/develop.rst, doc/tutorials/using_sdc2_mode_on_nuc.rst
Update merged PR #3463 with format and wording improvements.
(Not linked yet into the document navigation)
=> doc: apply edits to SDC2 scenario doc

doc/getting-started/building-from-source.rst, doc/introduction/images/boot-flow-2.dot, doc/introduction/index.rst, doc/try.rst
PR #3516 was submitted during a documentation reorganization and
resulted in merge conflicts with files that no longer exist.  We closed
that PR and opened this one with those changes applied to the right
files.
=> doc: incorporate scenario-based doc update

doc/develop.rst, doc/tutorials/using_sdc2_mode_on_nuc.rst
=> doc: add the SDC2 scenario doc into the navigation

devicemodel/hw/pci/gvt.c
Keep LaaG aperture size consistent with the host bios setting,
if we statically set LaaG aperture 256MB,
it may not have memory space for LaaG aperture.
We get host aperture size from cfg port 0x62.
Tracked-On: #3537
=> dm:gvt:keep LaaG aperture size consistent with the host

doc/introduction/index.rst
- add limitation for UEFI services
=> doc: add limitation for UEFI services

doc/getting-started/apl-nuc.rst
Signed-off-by: yunzha4x <yunx.zhang@intel.com>
=> doc:update Getting started guide for Intel NUC software setup

doc/tutorials/using_hybrid_mode_on_nuc.rst
@lirui34 Under "Hybrid Scenario Startup Checking," please look at steps 2 d. through 2 h. I made edits but I am not sure if I added clarity or if I misunderstood what you mean. Thanks.
=> doc: add hybrid scenario document review edits

doc/release_notes/release_notes_1.2.rst
=> doc: Release Notes v1.2

doc/conf.py
=> doc: add v1.2 to the release navigation picker

hypervisor/arch/x86/guest/virtual_cr.c
Check whether the address area pointed by the guest
cr3 is valid or not before loading pdptrs. Inject #GP(0)
to guest if there are any invalid cases.
Tracked-On: #3572
=> hv: vcr: check guest cr3 before loading pdptrs

devicemodel/arch/x86/pm.c
ACPI supports two ways for power button device, one of them is control
method, and its _HID object is PNP0C0C.
If power button mediator doesn't scan power button from LNXPWRBN node
try to scan PNP0C0C node instead.
v2): Move the functions of openning fixed/control method power button to open_native_power_button
Tracked-On: #3594
=> dm: pm: support control method power button

doc/release_notes/release_notes_1.2.rst
Add three known issues to the v1.2 release notes.
=> doc: Add three known issues to the v1.2 release notes

devicemodel/core/sw_load_bzimage.c
According to $(LINUX_SRC)/Documentation/x86/boot.txt, the header
of bzimage has setup sector number in offset 0x1f1. We don't
need to scan the SETUP_SIG and detect the setup sector number
actually which is not documented in x86 boot protocol.
Tracked-On: #3619
=> dm: bzimage loader: get linux bzimage setup_sects from header

devicemodel/hw/platform/usb_pmapper.c
The patch fixes enumeration related issues introduced by commit 'fc3d19'.
Tracked-On: #3612
=> DM USB: fix enumeration related issues

hypervisor/acpi_parser/acpi_ext.c, hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/guest/vcpu.c, hypervisor/arch/x86/init.c, hypervisor/include/arch/x86/multiboot.h, hypervisor/include/arch/x86/security.h, hypervisor/include/dm/vacpi.h, hypervisor/lib/stack_protector.c
-- remove some unnecessary includes
-- fix a typo
-- remove unnecessary void before launch_vms
=> hv:tiny cleanup

misc/efi-stub/boot.c
Because of this commit:
commit 63e258bd01308d0fb262361145c90d3d0ae10dbf
Author: Tianhua Sun <tianhuax.s.sun@intel.com>
Date:   Wed Jul 17 14:33:47 2019 +0800
efi-stub: update string operation in efi-stub
Remove unsafe API in efi-stub
1, use Strnlen instead of StrLen except the parameter
is a static string.
2, strlen() only work on static strings.
Tracked-On: #3276
In the default case, bootloader_name will be point to a separate ro
section which hold the constant string, free this memory later will
cause undefined behavior (memory corruption, exception and so on).
Tracked-On: #3644
=> efi-stub: fix stack memory free issue

hypervisor/arch/x86/pm.c
We did following to do platform reset:
1. Try ACPI reset first if it's available
2. Then try 0xcf9 reset method
3. if 2 fails, try keyboard reset method
This introduces some timing concern which needs be handled carefully.
We change it by following:
assume the platforms which ACRN could be run on must support either
ACPI reset or 0xcf9 reset. And simplify platform reset operation
a little bit:
If ACPI reset register is generated
try ACPI reset
else
try 0xcf9 reset method
Tracked-On: #3609
=> vm reset: refine platform reset

doc/developer-guides/hld/usb-virt-hld.rst
=> Add supported USB devices for WaaG and LaaG OSs

doc/getting-started/building-from-source.rst
Signed-off-by: yunzha4x <yunx.zhang@intel.com>
=> doc: update Build ACRN from Source

doc/developer-guides/c_coding_guidelines.rst
- update Language Extensions in coding guidelines
=> doc: update Language Extensions in coding guidelines

doc/developer-guides/c_coding_guidelines.rst
=> Add URL to GCC 7.3 Manual, Section 6

doc/develop.rst, doc/tutorials/acrn_configuration_tool.rst
Update material from PR #3559 with review and clarity edits.
=> doc: review edits for config tool doc

devicemodel/Makefile, devicemodel/arch/x86/pm.c, devicemodel/arch/x86/power_button.c, devicemodel/core/main.c, devicemodel/include/acpi.h, devicemodel/include/pm.h, devicemodel/samples/apl-mrb/launch_uos.sh, devicemodel/samples/apl-up2/launch_uos.sh, devicemodel/samples/nuc/launch_uos.sh, doc/user-guides/acrn-dm-parameters.rst
Refine the guest power event notification related code a little bit. To make it easy that add vuart as new channel.
Tracked-on: #3564
Acked-by: Wang Yu <yu1.wang@intel.com>
=> Pm notify channel

CODEOWNERS
Add Nanlin (@NanlinXie) as a reviewer for ACRN documentation.
=> doc: update CODEOWNER for rst

hypervisor/dm/vuart.c
support vuart reliable communication
=> support vuart reliable communication

CODEOWNERS
Modify the maintainer of each sub directory
=> Modify the maintainer of each sub directory

hypervisor/arch/x86/guest/vm.c
When a VM is configured with LAPIC PT mode and its vCPU is in x2APIC
mode, the corresponding pCPU needs to be reset during VM shutdown/reset
as its physical LAPIC was used by its guest
This commit fixes an issue where this reset never happens.
is_lapic_pt_enabled() needs to be called before reset_vcpu() to be able
to correctly reflect a vCPU's APIC mode.
A vCPU with LAPIC PT mode but in xAPIC mode does not require such reset,
since its physical LAPIC was not touched by its guest directly.
Tracked-On: #3708
=> hv: vm: properly reset pCPUs with LAPIC PT enabled during VM shutdown/reset

Makefile, hypervisor/Makefile, hypervisor/arch/x86/cpu.c
- generate config patch in hypervisor/Makefile;
- add acrn-config tag in version.h
=> Makefile: improvement for acrn-config

misc/acrn-config/README, misc/acrn-config/board_config/README, misc/acrn-config/board_config/new_board_kconfig.py, misc/acrn-config/launch_config/README, misc/acrn-config/launch_config/com.py, misc/acrn-config/library/launch_cfg_lib.py, misc/acrn-config/scenario_config/README, misc/acrn-config/xmls/config-xmls/nuc7i7dnb/industry_launch_1uos_hardrt.xml
1.    update README for acrn-config
2.    reserve 2M memory for hv start
3.    fix parameter error in launch script
=> acrn-config: launch config bug fix

doc/tutorials/vuart_configuration.rst
Tweak the "vUART configuration" tutorial to fix a few typos and change some
formatting to improve its readability.
=> doc: tweak vUART tutorial for improved rendering

doc/getting-started/apl-nuc.rst
=> doc: content updates to GSG for the Intel NUC

doc/tutorials/using_celadon_as_uos.rst
=> doc: minor edits to using celadon as user os file

doc/tutorials/using_sbl_on_up2.rst
=> doc: content updates for using SBL on UP2 board file

doc/tutorials/realtime_performance_tuning.rst
=> doc: content updates to RT perf tuning doc

doc/tutorials/realtime_performance_tuning.rst
Editorial tweaks to the "Real-Time (RT) Performance Analysis on ACRN" document,
mostly to improve readibility, no technical content change.
=> doc: editorial tweaks to "Real-Time (RT) Performance Analysis on ACRN"

doc/getting-started/acrn_ootb.rst
=> doc: content updates to Install ACRN out of the box file

devicemodel/core/hugetlb.c
Currently, DM only access /sys/kernel/mm/hugepages/hugepages-2048kB/
entries according to its own huge page requirement. So it could have
following race issue:
DM1                                   DM2
read nr pages
read nr pages
write DM2 nr pages
write DM1 nr pages
Suppose we should write DM1 + DM2 nr page to kernel sysfs interface
to reserve enough huge page (DM1 + DM2). But actually only reserve
huge page requested by DM1.  Which could trigger one VM can't boot.
We can easily hit this issue if we enable multiple UOS auto boot
because more than one VM are started at almost same time.
We add file lock to make sure huge page reserving in DM atomic.
Tracked-On: #3729
Acked-by: Wang Yu <yu1.wang@intel.com>
=> dm: hugetlb: add file lock to make sure huge page reserve atomic

doc/release_notes/release_notes_1.3.rst
=> doc: Release notes v1.3

doc/getting-started/rt_industry.rst
=> Doc: content edits for GSG for ACRN Ind Scenario

doc/conf.py
Update the version menu to include the 1.3 docs (and remove the 0.8)
=> doc: add 1.3 to version menu

doc/getting-started/building-from-source.rst
1. Update build the hypervisor with XML file command.
2. Add "cd hypervisor" before "make defconfig BOARD=nuc6cayh"
=> doc: update build from source

doc/release_notes/release_notes_1.3.rst
=> doc: Add missing link in release notes 1.3

hypervisor/hw/pci.c
We only support Type 0 and Type 1 PCI device. Remove PC-Card type support which
was originally described in the [PC-Card] and is used in previous versions of
the programming model.
=> hv: vpci: remove PC-Card type support

doc/getting-started/rt_industry.rst
=> Corrected number issue in GSG for ACRN Ind Scenario file

misc/acrn-config/config_app/static/main.js
fix the issue: some select boxes disappear unexpectly after edited
Tracked-On: #3809
=> acrn-config: fix the issue some select boxes disappear after edited

hypervisor/arch/x86/guest/vcpu.c, hypervisor/arch/x86/guest/vm.c, hypervisor/arch/x86/guest/vm_reset.c, hypervisor/arch/x86/guest/vmcs.c, hypervisor/arch/x86/init.c, hypervisor/boot/guest/vboot_info.c, hypervisor/common/hv_main.c, hypervisor/common/vm_load.c, hypervisor/dm/vpci/pci_pt.c, hypervisor/dm/vpci/vhostbridge.c, hypervisor/dm/vpci/vmsi.c, hypervisor/dm/vpci/vpci.c, hypervisor/include/arch/x86/vm_config.h, hypervisor/include/common/hypercall.h
--remove unnecessary includes
--remove unnecssary forward-declaration for 'struct vhm_request'
=> hv:remove some unnecessary includes

doc/tutorials/acrn_configuration_tool.rst
=> doc: fix missing words issue in acrn configuration tool doc

misc/tools/acrn-crashlog/usercrash/server.c
This patch is to remove unused info in server.c
Tracked-On: #3787
Acked-by: CHEN Gang <gang.c.chen@intel.com>
=> tools: acrn-crashlog: refine crash complete code

misc/acrn-config/xmls/config-xmls/apl-mrb/hybrid.xml, misc/acrn-config/xmls/config-xmls/apl-up2/hybrid.xml, misc/acrn-config/xmls/config-xmls/generic/hybrid.xml, misc/acrn-config/xmls/config-xmls/nuc6cayh/hybrid.xml, misc/acrn-config/xmls/config-xmls/nuc7i7dnb/hybrid.xml
Wrong NVMe bdf info is modified by mistake; so change it back.
Tracked-On: #3827
Reviewed-by: binbin.wu@intel.com
=> dm: NVME bdf info update on KBLNUC7i7DNH

doc/developer-guides/hld/virtio-console.rst
add new console backend of socket for virtio-console
=> doc: add socket console backend for virtio-console

doc/developer-guides/hld/hld-devicemodel.rst
update code in hld-devicemodel to latest.
=> doc: detail change for hld-devicemodel

doc/developer-guides/hld/virtio-rnd.rst
=> minor content edits to virtio-rnd doc

misc/acrn-config/launch_config/com.py, misc/acrn-config/launch_config/launch_item.py, misc/acrn-config/library/launch_cfg_lib.py, misc/acrn-config/xmls/config-xmls/apl-mrb/sdc_launch_1uos_aaag.xml, misc/acrn-config/xmls/config-xmls/apl-mrb/sdc_launch_1uos_aliaag.xml, misc/acrn-config/xmls/config-xmls/apl-mrb/sdc_launch_1uos_laag.xml, misc/acrn-config/xmls/config-xmls/apl-up2-n3350/sdc_launch_1uos_laag.xml, misc/acrn-config/xmls/config-xmls/apl-up2/sdc_launch_1uos_aaag.xml, misc/acrn-config/xmls/config-xmls/apl-up2/sdc_launch_1uos_laag.xml, misc/acrn-config/xmls/config-xmls/generic/hybrid_launch_1uos.xml, misc/acrn-config/xmls/config-xmls/generic/industry_launch_1uos.xml, misc/acrn-config/xmls/config-xmls/generic/industry_launch_2uos.xml, misc/acrn-config/xmls/config-xmls/generic/industry_launch_3uos.xml, misc/acrn-config/xmls/config-xmls/generic/sdc_launch_1uos.xml, misc/acrn-config/xmls/config-xmls/nuc6cayh/industry_launch_1uos_hardrt.xml, misc/acrn-config/xmls/config-xmls/nuc6cayh/industry_launch_1uos_vxworks.xml, misc/acrn-config/xmls/config-xmls/nuc6cayh/industry_launch_1uos_waag.xml, misc/acrn-config/xmls/config-xmls/nuc6cayh/industry_launch_2uos.xml, misc/acrn-config/xmls/config-xmls/nuc6cayh/industry_launch_3uos.xml, misc/acrn-config/xmls/config-xmls/nuc6cayh/sdc_launch_1uos_laag.xml, misc/acrn-config/xmls/config-xmls/nuc6cayh/sdc_launch_1uos_zephyr.xml, misc/acrn-config/xmls/config-xmls/nuc7i7dnb/industry_launch_1uos_hardrt.xml, misc/acrn-config/xmls/config-xmls/nuc7i7dnb/industry_launch_1uos_vxworks.xml, misc/acrn-config/xmls/config-xmls/nuc7i7dnb/industry_launch_1uos_waag.xml, misc/acrn-config/xmls/config-xmls/nuc7i7dnb/industry_launch_2uos.xml, misc/acrn-config/xmls/config-xmls/nuc7i7dnb/industry_launch_3uos.xml, misc/acrn-config/xmls/config-xmls/nuc7i7dnb/sdc_launch_1uos_laag.xml, misc/acrn-config/xmls/config-xmls/nuc7i7dnb/sdc_launch_1uos_zephyr.xml
1. acrn-config: enable item check for launch config tool
2. acrn-config: remove '-V' option from launch config
3. acrn-config: add 'run_container' back to the launch script
Tracked-On: #3811
=> acrn-config: Enable item check for launch config tool

doc/getting-started/acrn_quick_setup.sh, doc/getting-started/apl-nuc.rst
Align CL version for RT GSG and NUC GSG on 1.3
=> doc: Align CL version for RT GSG and NUC GSG on 1.3

doc/getting-started/acrn_quick_setup.sh, doc/getting-started/apl-nuc.rst
Align CL version for RT GSG and NUC GSG
=> doc: Align CL version for RT GSG and NUC GSG

hypervisor/arch/x86/guest/pm.c, hypervisor/arch/x86/guest/vm.c, hypervisor/include/arch/x86/guest/guest_pm.h
-- change some APIs to static
-- combine two APIs to one(guest_pm_init)
=> hv:Wrap some APIs related with guest pm

misc/acrn-config/launch_config/com.py, misc/acrn-config/launch_config/launch_cfg_gen.py, misc/acrn-config/launch_config/pt.py
1. acrn-config: add 'boot_audio_option' while auido/audio_codec set
2. acrn-config: refine the tools for audio/audio_codec
3. acrn-config: refine parameters for media_pt function
Tracked-On: #3853
=> acrn-config:  refine the launch config tool for audio/audio_codec device

doc/developer-guides/hld/hld-security.rst
update the 'Introduction' section.
=> doc: hld-security introduction update

doc/developer-guides/hld/hld-security.rst
Update some content for hypervisor enhancement section
to keep it consistent with the design.
=> doc: hld-security hypervisor enhancement section update

doc/tutorials/acrn_configuration_tool.rst
add ``vcpu_affinity`` element of scenario xml
=> doc: acrn_configuration_tool add one more scenario element description

doc/tutorials/acrn_configuration_tool.rst
=> Doc: Grammar add for config tool doc

doc/developer-guides/hld/hv-cpu-virt.rst
This PR contains the following updates in HLD:
- CPUID virtualization.
- CR virtualization.
- IO/MMIO virtualization.
- MSR virtualization.
=> doc: update Hv CPU virt HLD

doc/developer-guides/hld/hv-cpu-virt.rst
This patch adds ART virtualization hld.
=> Doc: Add ART virtualization hld

doc/developer-guides/hld/hld-security.rst, doc/developer-guides/hld/hv-hypercall.rst, doc/developer-guides/hld/hv-interrupt.rst, doc/developer-guides/trusty.rst
update hld for hypercall and upcall
=> doc:Update hypercall and upcall

misc/acrn-config/board_config/acpi_platform_h.py, misc/acrn-config/board_config/board_cfg_gen.py, misc/acrn-config/launch_config/com.py, misc/acrn-config/launch_config/launch_cfg_gen.py, misc/acrn-config/library/board_cfg_lib.py, misc/acrn-config/library/common.py, misc/acrn-config/library/launch_cfg_lib.py, misc/acrn-config/library/scenario_cfg_lib.py, misc/acrn-config/scenario_config/scenario_cfg_gen.py, misc/acrn-config/target/acpi.py
1. acrn-config: set default package value for _S3 and _S5
2. acrn-config: skip git environment check when not do git commit
3. acrn-config: refine 'lpc' setting with console type
=> acrn-config: refine the launch config tools and skip git environment check without '--enable_commit'

doc/developer-guides/hld/hld-devicemodel.rst
add entry for passthru realization in device model
=> doc: add entry for passthru realization

doc/getting-started/rt_industry.rst
Need to align the rt gsg updates with 1.3 branch.
=> doc: Align the updates of rt gsg with 1.3

doc/developer-guides/hld/hld-emulated-devices.rst, doc/developer-guides/hld/rtc-virt-hld.rst
add RTC virtualization doc and add entry in hld-emulated-devices
=> doc: add RTC virtualization doc

doc/developer-guides/hld/hld-emulated-devices.rst, doc/developer-guides/hld/hostbridge-virt-hld.rst
add hostbridge emulation doc and entry
=> doc: add hostbridge emulation doc

doc/developer-guides/hld/hld-hypervisor.rst, doc/developer-guides/hld/hv-rdt.rst
The hld of resource director technology, RDT. Should have CAT and
MBA. This is for CAT.
=> doc: add HLD for CAT

misc/acrn-config/launch_config/com.py, misc/acrn-config/launch_config/launch_item.py, misc/acrn-config/launch_config/pt.py, misc/acrn-config/xmls/config-xmls/nuc6cayh/industry_launch_1uos_vxworks.xml, misc/acrn-config/xmls/config-xmls/nuc7i7dnb/industry_launch_1uos_vxworks.xml
- modify the industry scenario config of uos id
- parse rootfs_img and refine virtio-blk
- modify board name to uos name
-  add mem_size for launch vm
-  add the '"' character for launch script
=> acrn-config: hot fix for v1.4

doc/getting-started/rt_industry.rst
some updates in gsg preempt rt setup guide.
=> doc: some updates in gsg preempt rt setup guide.

doc/getting-started/acrn_quick_setup.sh
Also fix efibootmgr not set correct issue.
=> doc: Add industry argument for auto setup script

doc/developer-guides/hld/vuart-virt-hld.rst
Fix "duplicate label" error (name of a figure collided with the name of
a document).  Also fixed very long lines, cleaned up some stray extra
spaces that were breaking up words, and some grammar issues.
=> doc: fix vuart-virt-hld errors

doc/release_notes/release_notes_0.6.rst, doc/release_notes/release_notes_1.0.rst, doc/release_notes/release_notes_1.1.rst
=> Doc: remove broken links in RNs.

devicemodel/core/hugetlb.c
Lock should be held till all the mmap operations are done. This is to
avoid the mmap failure when multiple guests are created concurrently.
For example consider the following case in which vm1 and vm2 are
created by acrnd concurrently:
- vm1 is created with 4G+2M memory.
- 4G+2M memory is reserved in hugetlb now and vm1 continues to
allocate memory for the lowmem without lock held.
- 2G memory is allocated by vm1 for its lowmem, and 2G+2M memory
is available in hugetlb.
- At this time vm2 is created with 1G+2M memory. It finds that enough
memory is reserved (2G+2M), so it does not try to reserve more
memory.
- vm2 allocates some memory for its lowmem/highmem/ovmf.
- vm1 tries to allocate memory for its highmem/ovmf, the allocation
will fail. vm1 creation failed in this case.
Tracked-On: …
=> dm: file lock should be held till all mmap is done

Makefile, misc/efi-stub/Makefile
=> Modify KBL-NUC/SDC for default build on master

Makefile, hypervisor/Makefile
- Makefile: add default defconfig for new board
=> Makefile: add default defconfig for new board

devicemodel/hw/pci/core.c
The acrn vhm driver will convert all PCI configure space access to
PCI_CFG type, so the pci_emul_cfgaddr and pci_emul_cfgdata will nerver
be invoked. Remove these useless functions.
Tracked-On: #3999
=> dm: remove cfc/cf8 pio handler

doc/getting-started/acrn_quick_setup.sh
=> Clean up language in the acrn_quick_setup script.

doc/tutorials/acrn_configuration_tool.rst
Signed-off-by: lkanx <lix.kan@intel.com>
=> doc:update acrn_configuration_tool

doc/develop.rst
=> Added entry for waag-secure-boot tutorial (added in #3883)

doc/developer-guides/hld/hv-memmgt.rst, doc/developer-guides/hld/hv-timer.rst
1. update memory management hld
2. update timer hld
=> Doc: update MMU & Timer HLD

doc/developer-guides/hld/ahci-hld.rst, doc/developer-guides/hld/atkbdc-virt-hld.rst, doc/developer-guides/hld/hld-power-management.rst, doc/developer-guides/hld/hostbridge-virt-hld.rst, doc/developer-guides/hld/hv-interrupt.rst, doc/developer-guides/hld/hv-pm.rst, doc/developer-guides/hld/hv-rdt.rst, doc/developer-guides/hld/hv-startup.rst, doc/developer-guides/hld/hv-timer.rst, doc/developer-guides/hld/hv-virt-interrupt.rst, doc/developer-guides/hld/rtc-virt-hld.rst, doc/developer-guides/hld/system-timer-hld.rst, doc/developer-guides/hld/vuart-virt-hld.rst, doc/tutorials/using_windows_as_uos.rst
=> Doc: Minor grammatical edits on various files.

doc/tutorials/waag-secure-boot.rst
Cleaned up the presentation and formatting problems from the conversion
to ReST, along with English grammar and spelling edits.
=> doc: clean up waag-secure-boot doc

doc/conf.py
=> Doc: update conf.py file to include v1.4

hypervisor/arch/x86/guest/vm.c, hypervisor/dm/vuart.c, hypervisor/include/dm/vuart.h
fifo_reset -> reset_fifo
vuart_fifo_init -> init_fifo
vuart_setup - > setup_vuart
vuart_init -> init_vuart
vuart_deinit -> deinit_vuart
vuart_lock_init -> init_vuart_lock
vuart_lock -> obtain_vuart_lock
vuart_unlock -> release_vuart_lock
vuart_deinit_connect -> vuart_deinit_connection
Tracked-On: #4017
=> hv: rename vuart operations

devicemodel/hw/pci/xhci.c
remove uninitialized variable "dir", then make sure
"xfer->data","xfer->data[i].hcb","xfer->reqs" free correctly.
Tracked-On: #4034
Signed-off-by: Junhao Gao <junhao.gao@intel.com>
=> dm: fix memory free issue for xhci

devicemodel/hw/platform/cmos_io.c
Fix the license of cmos_io.c to BSD-3-Clause
Tracked-On: #4032
=> dm: hw: fix the license of cmos_io.c

misc/acrn-config/board_config/acpi_platform_h.py, misc/acrn-config/board_config/board_c.py, misc/acrn-config/board_config/misc_cfg_h.py, misc/acrn-config/target/dmar.py, misc/acrn-config/xmls/board-xmls/apl-mrb.xml, misc/acrn-config/xmls/board-xmls/apl-up2-n3350.xml, misc/acrn-config/xmls/board-xmls/apl-up2.xml, misc/acrn-config/xmls/board-xmls/nuc6cayh.xml, misc/acrn-config/xmls/board-xmls/nuc7i7dnb.xml
-generate dmar info for board.c
-generate proper msr_index value for CLOS
-update DRHD_INFO section for board xml
-refine DRHD structure initialization
-refinement for parsing DMAR table
-correct value of DRHDx_IGNORE macro
=> acrn-config: refinement for dmar

doc/faq.rst, doc/getting-started/acrn_quick_setup.sh, doc/getting-started/rt_industry.rst
Also fix some quick setup script issues.
=> doc: Stop using kconfig to make a customized efi.

doc/getting-started/building-from-source.rst
=> doc:modfiy ubuntu build on 18.04

doc/tutorials/using_windows_as_uos.rst
Signed-off-by: huyuan3x <yuanx1.hu@intel.com>
=> doc: Update Using Windows as Guest VM on ACRN

doc/getting-started/building-from-source.rst
=> doc: fix error in building_from_source doc

doc/tutorials/enable_laag_secure_boot.rst
=> doc: review edit for enable_laag_secure_boot

doc/developer-guides/hld/hv-memmgt.rst
=> Doc: Final edits to Memory Mangt HLD doc.

doc/developer-guides/hld/hld-overview.rst
=> Doc: Final edits to the HLD Overview doc.

doc/getting-started/rt_industry.rst
=> doc: review edits for rt_industry doc

doc/developer-guides/hld/hv-cpu-virt.rst
=> Doc: Final edits to the CPU Virt doc

doc/developer-guides/hld/hv-hypercall.rst
=> Doc: Final edits to the HV Hypercall doc.

doc/developer-guides/hld/hld-security.rst
=> Doc: Final edits for the HLD-Security doc.

hypervisor/arch/x86/guest/instr_emul.c
In non-64-bit mode, CS segment base address should be considered when
determining the linear address of the vcpu's instruction pointer. Use
vie_calculate_gla() for instruction address translation which also takes
care of 64-bit mode.
Tracked-On: #4064
=> hv: instr_emul: use cs segment when fetching instructions

devicemodel/samples/apl-mrb/launch_uos.sh, devicemodel/samples/apl-up2/launch_uos.sh, devicemodel/samples/nuc/launch_hard_rt_vm.sh, devicemodel/samples/nuc/launch_uos.sh, devicemodel/samples/nuc/launch_vxworks.sh, devicemodel/samples/nuc/launch_win.sh, devicemodel/samples/nuc/launch_zephyr.sh, hypervisor/scripts/genld.sh
Add licenses to the scripts:
```
devicemodel/samples/apl-mrb/launch_uos.sh
devicemodel/samples/apl-up2/launch_uos.sh
devicemodel/samples/nuc/launch_hard_rt_vm.sh
devicemodel/samples/nuc/launch_uos.sh
devicemodel/samples/nuc/launch_vxworks.sh
devicemodel/samples/nuc/launch_win.sh
devicemodel/samples/nuc/launch_zephyr.sh
hypervisor/scripts/genld.sh
```
Tracked-On: #4061
=> dm: Add licenses to the scripts.

doc/tutorials/enable_s5.rst
=> Doc: Grammatical edits to the Enable S5 Guide.

doc/asa.rst, doc/index.rst
=> doc: Add Advisory notes

doc/asa.rst
=> Doc: Grammatical edits to the Advisory doc.

doc/release_notes/release_notes_1.4.rst
=> doc: Release notes v1.4

doc/release_notes/release_notes_1.4.rst
=> Doc: Grammatical edits to the 1.4 Release Notes.

misc/acrn-config/board_config/board_c.py, misc/acrn-config/library/board_cfg_lib.py, misc/acrn-config/target/acpi.py, misc/acrn-config/target/parser_lib.py
- by-pass acpi_idle/acpi_cpufreq for parsing target board
- Cx desc parsing enhancement
- alloc vuart1 irq when pttyS1 not exist only
Tracked-On: #4082
=> acrn-config: enhance for parsing target board and alloc vuart1 irq

CODEOWNERS
=> CODEOWNERS: add acrn-hypervisor Makefile owner

doc/asa.rst
Mitigation for this vulnerability is applied in 1.4 release, update
related notes in adviosry.
Tracked-On: #4101
=> doc: add mitigation description for latest fix in advisory

doc/tutorials/agl-vms.rst
=> Doc: Content edits to the AGL as VMs docs

doc/release_notes/release_notes_1.0.2.rst
=> Release notes for release_1.0.2

doc/release_notes/release_notes_1.0.2.rst
=> Doc: Corrected title formatting in RN 1.0.2 doc.

doc/asa.rst, doc/faq.rst, doc/getting-started/rt_industry.rst, doc/release_notes/release_notes_1.4.rst
=> doc: Update 1.4 versions and some words

doc/tutorials/acrn_ootb.rst
1. Update acrn.efi name in acrn ootb scripts
2. Add licenses to acrn ootb scripts
3. Add format U disk step
4. Add execute permission to ootb script
5. Fix wrong img name
=> doc: update acrn ootb doc

hypervisor/debug/dump.c, hypervisor/debug/shell.c, hypervisor/debug/shell_priv.h, hypervisor/include/arch/x86/guest/vcpu.h
-- remove show_guest_call_trace
-- refine dump host memory
-- add dump guest memory
Tracked-On: #4144
=> Dump guest memory

doc/tutorials/using_ubuntu_as_sos.rst
Signed-off-by: hongliang <hongliangx.ye@intel.com>
=> doc: edit using_ubuntu_as_sos.rst adjust to v1.4

misc/acrn-config/board_config/ve820_c.py
Current ve820 generation script assumes the size of pre-launched
VM memory is less than or equal to 512 MB (Must be the assumption
of logical partition scenario as such).
This patch extends the script to handle pre-launched VM memory
sizes greater than 512 MB.
Tracked-On: #4182
=> acrn-config: Extend ve820 generation script for sizes gt 512 MB

misc/acrn-config/xmls/board-xmls/tgl-rvp.xml, misc/acrn-config/xmls/config-xmls/tgl-rvp/industry.xml, misc/acrn-config/xmls/config-xmls/tgl-rvp/industry_launch_1uos.xml
1. Use acrn-configure tool to generate xml files to support TGL
RVP board. You need make menuconfig as guide in github, and then
comiple as following:
make hypervisor BOARD_FILE=path/xxx.xml SCENARIO_FILE=path/yyy.xml
2. Also uos launch script can be generated by acrn-configure tool with the
uos luanch xml file
Tracked-On: #4181
=> acrn-config: add xml to support TGL RVP board

misc/acrn-config/target/acpi.py
There seems to be a corner case where target xml file
fails to get generated if there was no P-state scaling driver
or C-state idle driver present. This patch addresses it by
handling the file not present exception and setting a warning
as well a "not available" string to successfully generate
target xml file.
Tracked-On: #4199
=> acrn-config: Fix target xml generation issue with no Cx/Px driver

hypervisor/arch/x86/guest/vlapic.c
In APICv advanced mode, an targeted vCPU, running in non-root mode, may get outdated
TMR and EOI exit bitmap if another vCPU sends an interrupt to it if the trigger mode
of this interrupt has changed.
This patch try to kick vCPU off to let it get the latest TMR and EOI exit bitmap when
it enters non-root mode again. Then fill the interrupt to PIR.
Tracked-On: #4200
=> hv: vlapic: kick targeted vCPU off if interrupt trigger mode has changed

misc/tools/acrntrace/Makefile, misc/tools/acrntrace/README.rst, misc/tools/acrntrace/acrntrace.c, misc/tools/acrntrace/scripts/vmexit_analyze.py
=> Acrntrace fix pr

hypervisor/boot/reloc.c
The calculation of the end boundry address is corrected by
adding the size extracted from _DYNAMIC to start address
in type of uint8_t while improving the code by calulating
the end boundry address after scanning, also reducing type
casts accordingly.
Tracked-On: projectacrn#4191
Signed-off-by: Gary <gordon.king@intel.com>
=> acrnboot: correct the calculation of the end boundry of _DYNAMIC region

Makefile
Move the warning message to the end of build process to hint user to check
the validity of $(BOARD)_acpi_info.h, otherwise user might not be aware the
existence of this file and then cause issues.
Another reason is when user uses make menuconfig method to make hypervisor
with XML files, we should give this warning message also.
=> Makefile: highlight board acpi file warning msg

devicemodel/hw/pci/core.c
Now the GVT already tries to reserve the region.
the problem is that the region should be
reflected in PCI BUS0 memlimit32 and updated to DSDT table.
As the GVT PCI bar0/2 is in reserved region
and not updated to memlimit32 in DSDT table,
the problem is triggered.
Tracked-On: projectacrn#4227
=> dm:gvt:update bus0 memlimit32 value

hypervisor/arch/x86/guest/vm_reset.c
The port 0x64 is the status register of i8042 keyboard controller. When
i8042 is defined as ACPI PnP device in BIOS, enforce returning 0xff in
read handler would cause infinite loop when booting SOS VM, so expose
the physical port read in this case;
Tracked-On: #4228
=> HV: expose port 0x64 read for SOS VM

hypervisor/arch/x86/guest/vm.c
=> hv:remove need_cleanup flag in create_vm

hypervisor/arch/x86/idt.S, hypervisor/arch/x86/irq.c, hypervisor/arch/x86/lapic.c, hypervisor/include/arch/x86/irq.h, hypervisor/include/arch/x86/lapic.h
Fisrt 3 preparative patches of "NMI notification for lapic-pt vCPUs" patchset.
=> Nmi notification v4 pr

hypervisor/common/hypercall.c
This patch fixes potential hypervisor crash when
calling hcall_write_protect_page() with a crafted
GPA in 'struct wp_data' instance, e.g. an invalid
GPA that is not in the scope of the target VM's
EPT address space.
This patch is to check the validity for this GPA
before updating the 'write protect' page.
Tracked-On: #4240
=> hv:bugfix in write protect page hypercall

misc/acrn-config/launch_config/com.py, misc/acrn-config/launch_config/launch_item.py, misc/acrn-config/launch_config/pt.py, misc/acrn-config/library/launch_cfg_lib.py, misc/acrn-config/scenario_config/vm_configurations_c.py
- acrn-config: enable log_setting in all vm
- check pass-thruogh device for audio/audio_codec
- correct vuart1 setting in scenario config
- add 'tap_' perfix for virtio-net
Tracked-On: #4249
Signed-off-by: Wei Liu weix.w.liu@intel.com
Acked-by: Victor Sun victor.sun@intel.com
=> acrn-config: Bug fix rel 15

doc/introduction/index.rst
Add a little information (at least pointers) as to how one can change the VM
(Pre-launched, Service or User) boot options.
Tracked-On: #3758
=> doc: add a little info on how to configure the boot options

doc/tutorials/using_windows_as_uos.rst
doc: add windows 10 activation
=> doc: add windows 10 activation

misc/tools/acrntrace/README.rst
=> Doc: Content edits to the acrntrace README file.

doc/introduction/index.rst
=> Doc: Content edits to the introduction/index file.

doc/tutorials/using_windows_as_uos.rst
=> Doc: Content edits to Using WaaG VM on ACRN

misc/acrn-config/launch_config/com.py, misc/acrn-config/launch_config/launch_cfg_gen.py, misc/acrn-config/launch_config/launch_item.py, misc/acrn-config/library/launch_cfg_lib.py
- add 'logger_setting' into launch script
- refine mount device for virtio-blk
Tracked-On: #4248
=> acrn-config: refine mount device for virtio-blk

doc/getting-started/rt_industry.rst, doc/tutorials/acrn_configuration_tool.rst
Signed-off-by: fenglin.hu <fenglin.hu@intel.com>
=> doc: modify Configuration Tools

doc/develop.rst, doc/tutorials/run_kata_containers.rst
=> doc: Add tutorial about how to launch kata vm.

doc/getting-started/rt_industry.rst
=> Doc: Content edit to rt_industry document.

doc/tutorials/cpu_sharing.rst
=> Doc: Content edit to cpu-sharing page

doc/conf.py
=> Doc: Add v1.5 release menu choice.

doc/tutorials/cpu_sharing.rst
=> Doc: More edits to CPU Sharing doc.

doc/tutorials/run_kata_containers.rst
=> Doc: Content edits to Running Kata containers on a Service VM doc

misc/acrn-config/launch_config/com.py, misc/acrn-config/launch_config/launch_cfg_gen.py, misc/acrn-config/launch_config/launch_item.py, misc/acrn-config/launch_config/pt.py, misc/acrn-config/library/launch_cfg_lib.py, misc/acrn-config/scenario_config/vm_configurations_c.py
- add 'logger_setting' into launch script
- refine mount device for virtio-blk
- add 'tap_' perfix for virtio-net
- enable log_setting in all VMs
- check pass-thruogh device for audio/audio_codec
- correct vuart1 setting in scenario config
=> acrn-config: Cherry pick acrn-config patches from release v1.5

doc/tutorials/cpu_sharing.rst
=> DOC: Content edits to CPU Sharing doc

hypervisor/boot/acpi_base.c
Per ACPI 6.2 spec, chapter 5.2.5.2 "Finding the RSDP on UEFI Enabled Systems":
In Unified Extensible Firmware Interface (UEFI) enabled systems, a pointer to
the RSDP structure exists within the EFI System Table. The OS loader is provided
a pointer to the EFI System Table at invocation. The OS loader must retrieve the
pointer to the RSDP structure from the EFI System Table and convey the pointer
to OSPM, using an OS dependent data structure, as part of the hand off of
control from the OS loader to the OS.
So when ACRN boot from direct mode on a UEFI enabled system, hypervisor might
be failed to get rsdp by seaching rsdp in legacy EBDA or 0xe0000~0xfffff region,
but it still have chance to get rsdp by seaching it in e820 ACPI reclaimable
region with some edk2 based BIOS.
The patch will …
=> HV: search rsdp from e820 acpi reclaim region

doc/getting-started/building-from-source.rst
=> doc: remove no support OS parts

doc/reference/hardware.rst
=> Doc: Added Whiskey Lake specs to hardware ref page

doc/tutorials/run_kata_containers.rst
* Add more details about Kata Containers and ACRN in the introduction
* Adjust and correct some of the instructions
=> doc: add more details to the Kata Containers with ACRN tutorial

doc/tutorials/acrn_configuration_tool.rst
=> doc: Update some of the wrong path in acrn configuration tool doc.

doc/tutorials/run_kata_containers.rst
=> Doc: Added missing period in run_kata_containers file.

hypervisor/arch/x86/guest/vm.c
In current code, wait_pcpus_offline() and make_pcpu_offline() are called by
both shutdown_vm() and reset_vm(), but this is not needed when lapic_pt is
not enabled for the vcpus of the VM.
The patch merged offline pcpus part code into a common
offline_lapic_pt_enabled_pcpus() api for shutdown_vm() and reset_vm() use and
called only when lapic_pt is enabled.
Tracked-On: #4325
=> HV: do not offline pcpu when lapic pt disabled

doc/release_notes/release_notes_1.5.rst
=> Doc: releasenotes_1.5

doc/release_notes/release_notes_1.5.rst
=> Doc: Grammatical edits to RN 1.5.

doc/getting-started/rt_industry.rst, doc/tutorials/acrn_ootb.rst, doc/tutorials/using_windows_as_uos.rst
=> Doc: document update base on release_v1.5

doc/tutorials/acrn_ootb.rst
=> Doc: Grammar update to arcn_ootd.rst.

doc/release_notes/release_notes_1.5.rst
adding this information to releasenotes:
Update to use ACRNGT GOP to install Windows
=> Doc: releasenotes_1.5 update

doc/tutorials/using_windows_as_uos.rst
=> doc: change version info

doc/getting-started/rt_industry.rst, doc/tutorials/acrn_ootb.rst
=> doc: update getting start guide about clear version and ootb command

doc/tutorials/acrn_configuration_tool.rst
=> doc: update some xml elements description

doc/tutorials/acrn_configuration_tool.rst
=> Doc: Grammar updates to ACRN Config Tool doc.

doc/getting-started/rt_industry.rst
=> Doc: Style and grammar edits to GSG for ACRN Industry Scenario.

doc/tutorials/acrn_configuration_tool.rst
=> Doc: Fixed spelling error in the acrn_config_tool file.

doc/getting-started/rt_industry.rst
=> Doc: Updated one paragraph in re_industry doc.

devicemodel/hw/pci/core.c, devicemodel/hw/pci/passthrough.c
Now the PCI bar uses the hardcoded prefetch property
for the pass-through device.
This doesn't work when trying to load windows GPU driver
for the pass-through GPU device.
For pass-through devices,
set the bar prefetchable property the same as physical bar.
=> dm:derive the prefetch property of PCI bar for pass-through device

doc/getting-started/rt_industry.rst
=> doc: reset clear linux version and ootb command in getting start guide

doc/getting-started/rt_industry.rst
doc: Modify CL version from 32030 to 31670
=> doc: Modify CL version from 32030 to 31670

doc/getting-started/rt_industry.rst
=> Updated grammer in ACRN industry scenario doc

doc/getting-started/building-from-source.rst
=> Doc: Style updates to Building from Source doc

doc/tutorials/run_kata_containers.rst
Update the Kata and ACRN tutorial based on the latest SW components. Many
previous steps are no longer required and have been removed.
=> doc: update Kata and ACRN tutorial

doc/tutorials/run_kata_containers.rst
=> Grammatical edits to Run Kata Containers doc

misc/acrn-config/board_config/new_board_kconfig.py
=> fix typos in board gen script

doc/tutorials/using_ubuntu_as_sos.rst
=> DOC: Edits to Ubuntu SOS; changed SOS/UOS to Service VM/User VM

doc/tutorials/cpu_sharing.rst
Update VM2 vCPU affinity info to match with the picture of cpu_sharing
=> Doc: VM2 vCPU affinity info update

hypervisor/arch/x86/configs/apl-mrb/board.c, hypervisor/arch/x86/configs/apl-mrb/misc_cfg.h, misc/acrn-config/library/board_cfg_lib.py
- hv: add P2SB device to whitelist for apl-mrb
- acrn-config: add P2SB device to whitelist for apl-mrb
=> acrn-config: add P2SB device to whitelist for apl-mrb

doc/conf.py
Update copyright 2019 to be 2020
=> doc: update copyright year in doc footer

hypervisor/arch/x86/guest/vcpu.c, hypervisor/include/arch/x86/cpu.h
Change xsaves and xrstor to pure assembler
Tracked-On: #4436
=> hv: xsave: change to pure assembler

misc/acrn-config/board_config/board_c.py, misc/acrn-config/board_config/misc_cfg_h.py, misc/acrn-config/board_config/new_board_kconfig.py, misc/acrn-config/library/board_cfg_lib.py, misc/acrn-config/library/common.py, misc/acrn-config/scenario_config/scenario_item.py, misc/acrn-config/scenario_config/vm_configurations_c.py, misc/acrn-config/target/clos.py, misc/acrn-config/xmls/board-xmls/apl-mrb.xml, misc/acrn-config/xmls/board-xmls/apl-up2-n3350.xml, misc/acrn-config/xmls/board-xmls/apl-up2.xml, misc/acrn-config/xmls/board-xmls/nuc6cayh.xml, misc/acrn-config/xmls/board-xmls/nuc7i7dnb.xml, misc/acrn-config/xmls/board-xmls/tgl-rvp.xml, misc/acrn-config/xmls/board-xmls/whl-ipc-i5.xml, misc/acrn-config/xmls/board-xmls/whl-ipc-i7.xml
Update the offline tool to detect support for RDT CAT resources and enumerate its information in the xml file.
=> Rdt cat offline tool

hypervisor/arch/x86/mmu.c
- change variable name from hpa to hva because in this function we are
dealing with hva, not hpa.
- can get the address of ld_text_end by directly referring to this symbol,
because relative addressing yields the correct hva, not the hva before
relocation.
Tracked-On: #4441
=> hv: minor fixes in init_paging()

hypervisor/dm/vpci/vdev.c, hypervisor/dm/vpci/vhostbridge.c, hypervisor/dm/vpci/vmsi.c, hypervisor/dm/vpci/vpci.c, hypervisor/dm/vpci/vpci_bridge.c, hypervisor/dm/vpci/vpci_priv.h
Refine functions name and remove pci_vdev_read_cfg_u8/16/32
=> Refine HV function name

misc/acrn-config/board_config/board_c.py, misc/acrn-config/target/clos.py
This patch adds support for,
1. Storing MBA resource and its max supported clos value
in the target xml file under clos subsection.
2. Generating board.c file with MBA RDT resource.
Tracked-On: #3725
=> acrn-config: Generate target xml and board.c file with MBA RDT resource

hypervisor/arch/x86/ioapic.c, hypervisor/debug/shell.c, hypervisor/include/arch/x86/ioapic.h
rename:
ioapic_get_gsi_irq_addr --> gsi_to_ioapic_base
ioapic_addr -->ioapic_base
=> hv:rename several variables and api for ioapic

devicemodel/core/pm_vuart.c
Currently we have implemented S5 triggered by SOS,
these two patches both support S5 trigger by SOS and RTVM
Tracked-On: #4446
=> support S5 by RTVM

doc/index.rst
Note invites users to view v1.5 branch while
latest build is under construction.
=> Doc: Add note to index.html file

doc/contribute.rst, doc/develop.rst, doc/index.rst, doc/learn.rst, doc/reference/index.rst, doc/try.rst
=> Doc: Re-org documentation to improve user experience; see Nav Bar

doc/develop.rst
=> Doc: Fix tool ref tag on develop.rst page

hypervisor/arch/x86/guest/pm.c, hypervisor/arch/x86/guest/vm.c, hypervisor/arch/x86/guest/vm_reset.c, hypervisor/common/hypercall.c, hypervisor/debug/shell.c, hypervisor/include/arch/x86/guest/vm.h
Rename:
VM_STARTED --> VM_RUNNING
VM_POWERING_OFF --> VM_READY_TO_POWEROFF
Tracked-On: #4320
=> hv:Rename two VM states

doc/develop.rst, doc/index.rst, doc/introduction/index.rst, doc/learn.rst
=> Doc: Update re-org'd ACRN index page and What is ACRN.

doc/tutorials/using_celadon_as_uos.rst
=> doc: Update build celadon instruction link

doc/tutorials/sriov_virtualization.rst
=> doc: Grammatical updates to SR-IOV virt doc

doc/tutorials/using_windows_as_uos.rst
Delete Redhad virtio drive, only keep Oracle as reference.
Delete "inject driver into ISO" part.
In a word, QA just need maintain one latest workable method in GSG for creating WaaG image.
Signed-off-by: ffshen <fangfang.shen@intel.com>
=> doc: update waag GSG according to the latest method

doc/tutorials/using_windows_as_uos.rst
=> Doc: Grammatical edits to using_windows_as_uos.rst

doc/getting-started/rt_industry.rst, doc/tutorials/running_deb_as_serv_vm.rst, doc/tutorials/using_ubuntu_as_sos.rst
=> Doc: Edits to workaround note for EFI command line option string issue.

doc/static/acrn-custom.css
=> Doc: Remove Construction Progress label from site

doc/glossary.rst, doc/index.rst
=> Doc: Add Glossary to Nav Bar and Home Page

doc/asa.rst
Update mitigations for security vulnerabilities
for ACRN v.16 release.
=> doc: update security advisory for v1.6 release

doc/develop.rst, doc/tutorials/using_xenomai_as_uos.rst
=> Doc: add instructions for using Xenomai as UOS

doc/asa.rst
=> Doc Minor edits to Security page

doc/tutorials/using_xenomai_as_uos.rst
=> Doc: Minor edits to Xenomai page

doc/developer-guides/hld/hv-dev-passthrough.rst, doc/developer-guides/hld/split-dm.rst
=> Doc: Grammatical/style edits to split device model page

hypervisor/arch/x86/guest/guest_memory.c, hypervisor/common/hypercall.c, hypervisor/debug/hypercall.c, hypervisor/debug/profiling.c
it reduces LOC by ~80:
-  move error message logging into gpa copy APIs
- code cleanup in hypercall.c
=> hv: some code refinement

doc/developer-guides/hld/hv-vt-d.rst
=> doc: vt-d: update the description of snoop control

doc/developer-guides/hld/hv-vt-d.rst
=> Minor edits to VT-d page.

doc/tutorials/building_acrn_in_docker.rst
One known issue :acrn-issue:`4560` during build ACRN HV.
Please refer to  next section to get Docker Image from Docker Hub.
=> Doc: update building acrn in docker for V1.6

doc/release_notes/release_notes_1.6.rst
=> Doc: releasenotes_1.6

doc/release_notes/release_notes_1.6.rst
=> Doc: Grammatical edits to Release Notes 1.6

doc/release_notes/release_notes_1.6.rst
=> Doc: Release Notes update based on DKinder edits

doc/conf.py
Update doc version choice selector with the 1.6 release
=> doc: add 1.6 to doc version menu

hypervisor/arch/x86/page.c, hypervisor/include/arch/x86/vm_config.h
This patch fixes couple of minor issues with patch 8ffe6fc6
Tracked-On: #4563
=> hv: Fix minor issues with the patch to reserve EPT 4K pages after boot

misc/acrn-config/xmls/board-xmls/tgl-rvp.xml
As we did in commit: 697f3fc09f0e2677fa4aa592c8a44da54a8e6ab8, need
to update IOMEM_INFO for tgl-rvp.
Tracked-On: #4582
=> acrn-config: update IOMEM_INFO of tgl-rvp board

doc/conf.py
=> doc: add google analytics tag

doc/conf.py, doc/static/acrn-custom.js
=> doc: some additional google analytics code

devicemodel/samples/nuc/launch_xenomai.sh
Add a launch script for xenomai RTVM.
Tracked-On: #4514
=> sample: add sample script for launching xenomai RTVM

doc/getting-started/acrn_quick_setup.sh
- Fix swupd mirror issue
- Fix bootloader config file not detect correctly issue (happened on CL: 32750)
=> doc: gsg quick setup script issue fix.

doc/404.rst
=> doc: fix image size on 404 page

doc/404.rst
Fix display of 404 errors on mobile phones.  Also added some additional
wording for reporting errors.  (Last change, I hope :)
=> doc: fix 404 display on mobile devices

hypervisor/Makefile, hypervisor/arch/x86/Kconfig, hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/e820.c, hypervisor/arch/x86/guest/assign.c, hypervisor/arch/x86/guest/vlapic.c, hypervisor/arch/x86/guest/vm.c, hypervisor/arch/x86/ioapic.c, hypervisor/arch/x86/irq.c, hypervisor/arch/x86/page.c, hypervisor/boot/acpi_base.c, hypervisor/boot/guest/direct_boot.c, hypervisor/boot/include/acpi.h, hypervisor/common/hypercall.c, hypervisor/debug/shell.c, hypervisor/dm/vioapic.c, hypervisor/dm/vpci/vdev.c, hypervisor/dm/vpic.c, hypervisor/dm/vuart.c, hypervisor/include/arch/x86/e820.h, hypervisor/include/arch/x86/guest/assign.h, hypervisor/include/arch/x86/guest/vm.h, hypervisor/include/arch/x86/ioapic.h, hypervisor/include/arch/x86/page.h, hypervisor/include/arch/x86/vm_config.h, hypervisor/include/common/ptdev.h, hypervisor/include/dm/vioapic.h, hypervisor/include/dm/vpic.h, hypervisor/include/dm/vuart.h
Backporting patches from master to release_1.6 for v1.6.1
=> Local release 1.6

hypervisor/arch/x86/configs/apl-mrb/misc_cfg.h, hypervisor/arch/x86/configs/apl-up2/misc_cfg.h, hypervisor/arch/x86/configs/dnv-cb2/misc_cfg.h, hypervisor/arch/x86/configs/generic/misc_cfg.h, hypervisor/arch/x86/configs/nuc6cayh/misc_cfg.h, hypervisor/arch/x86/configs/nuc7i7dnb/misc_cfg.h, hypervisor/arch/x86/configs/whl-ipc-i5/misc_cfg.h, hypervisor/arch/x86/mmu.c, hypervisor/arch/x86/page.c, misc/acrn-config/board_config/misc_cfg_h.py, misc/acrn-config/library/common.py
Backporting patches from master to release_1.6
Tracked-On: #4586
=> Hypervisor access to PCI devices with 64-bit MMIO BARs

doc/developer-guides/doc_guidelines.rst, doc/developer-guides/hld/hld-devicemodel.rst, doc/developer-guides/hld/hld-security.rst, doc/developer-guides/hld/hld-virtio-devices.rst, doc/developer-guides/hld/hv-pm.rst, doc/faq.rst, doc/introduction/index.rst, doc/release_notes/release_notes_0.4.rst, doc/release_notes/release_notes_0.5.rst, doc/release_notes/release_notes_0.6.rst, doc/release_notes/release_notes_1.3.rst, doc/release_notes/release_notes_1.4.rst, doc/tutorials/docbuild.rst, doc/tutorials/increase-uos-disk-size.rst, doc/tutorials/kbl-nuc-sdc.rst, doc/tutorials/trustyACRN.rst, doc/tutorials/up2.rst, doc/user-guides/acrn-dm-parameters.rst
Remove trailing spaces on lines to avoid potential issues with git
=> doc: remove trailing spaces

devicemodel/core/pm_vuart.c
1) remove state machine
2) remove retry mechanism
3) pm thread only use to transmit data,not parse detailed message.
v1-->v2:
remove delay in pm_monitor_loop
Tracked-On: #4446
Reviewed-by: Yuhong Tao <yuhong.tao@intel.com>
=> dm:refine pm_vuart code

devicemodel/core/main.c
add vm_pause before vm_destroy
Tracked-On: #4320
=> dm: add vm_pause before vm_destroy

doc/develop.rst, doc/tutorials/rtvm_performance_tips.rst
=> Doc: Initial version of ARCN RTVM Perf Tips

doc/tutorials/using_partition_mode_on_nuc.rst
=> doc: update partition mode tutorial to use whl board.

doc/tutorials/using_partition_mode_on_nuc.rst
=> Doc: Minor grammatical edits to GSG for ACRN logical part mode

doc/developer-guides/doc_guidelines.rst
Include how to use the sphinx-tabs directives.
=> doc: update doc guidelines for sphinx-tabs

hypervisor/arch/x86/vtd.c
Fix the deadloop in hypervisor if timeout of waiting for QI request
completion.
Tracked-On: #4680
=> hv: vtd: fix potential dead loop if qi request timeout
