projectacrn/acrn-hypervisor

misc/config_tools/data/ehl-crb-b/industry_launch_1uos_hardrt.xml, misc/config_tools/data/ehl-crb-b/industry_launch_2uos.xml, misc/config_tools/data/ehl-crb-b/industry_launch_6uos.xml, misc/config_tools/data/generic_board/industry_launch_6uos.xml, misc/config_tools/data/nuc11tnbi5/industry_launch_6uos.xml, misc/config_tools/data/nuc7i7dnb/industry_launch_1uos_hardrt.xml, misc/config_tools/data/nuc7i7dnb/industry_launch_2uos.xml, misc/config_tools/data/nuc7i7dnb/industry_launch_6uos.xml, misc/config_tools/data/tgl-rvp/industry_launch_2uos.xml, misc/config_tools/data/tgl-rvp/industry_launch_6uos.xml, misc/config_tools/data/whl-ipc-i5/industry_launch_1uos_hardrt.xml, misc/config_tools/data/whl-ipc-i5/industry_launch_2uos.xml, misc/config_tools/data/whl-ipc-i5/industry_launch_6uos.xml, misc/config_tools/data/whl-ipc-i7/industry_launch_1uos_hardrt.xml, misc/config_tools/data/whl-ipc-i7/industry_launch_2uos.xml, misc/config_tools/data/whl-ipc-i7/industry_launch_6uos.xml
Update launch xml to use image to launch hard rt vm since
we changed the platforms from two disk to only one NVME disk.
=> config_tools: update launch xml for only one NVME

misc/config_tools/schema/config.xsd, misc/config_tools/schema/types.xsd
This patch refines the configuration data description so that it is
consistent with the current implementation of the configuration tools.
Tracked-On: #6377
=> config_tools: refine the configuration data description

misc/config_tools/static_allocators/intx.py, misc/config_tools/xforms/lib.xsl
There could be multiple ways in the scenario configuration to specify that
no INTx allocation is explicitly allocation to a prelaunched VM:
* Do not have a `pt_intx` node at all.
* Have a `pt_intx` node with no text.
* Have a `pt_intx` node with a text that has nothing but whitespaces,
tabs and newlines.
The current implementation only supports the first way, and will cause
build-time failures when a scenario configuration uses the latter two. The
following changes are introduced by this patch to fix such errors.
* The INTx static allocator queries the text() of `pt_intx` nodes
directly to gracefully handle `pt_intx` nodes with no text.
* The XSLT of pt_intx.c clears all kinds of white spaces from the text of
`pt_intx` nodes before calculating the set of allocated INTx mappings. …
=> config_tools: fix formatting of configured INTx allocation

hypervisor/quirks/smbios.c
The original use of recalc_checksum(eps->int_anchor, ...) may cause
an array bound overflow warning from code scanning tool. This patch
changes it to use offsetof to avoid using int_anchor directly.
Tracked-On: #6380
=> hv: Squash warning of code scanning tool

misc/config_tools/board_inspector/extractors/60-pci.py, misc/config_tools/board_inspector/pcieparser/caps.py, misc/config_tools/data/adl-rvp/adl-rvp.xml, misc/config_tools/data/cfl-k700-i7/cfl-k700-i7.xml, misc/config_tools/data/ehl-crb-b/ehl-crb-b.xml, misc/config_tools/data/nuc11tnbi5/nuc11tnbi5.xml, misc/config_tools/data/nuc7i7dnb/nuc7i7dnb.xml, misc/config_tools/data/tgl-rvp/tgl-rvp.xml, misc/config_tools/data/whl-ipc-i5/whl-ipc-i5.xml, misc/config_tools/data/whl-ipc-i7/whl-ipc-i7.xml, misc/config_tools/xforms/config_common.xsl
Imported the essential patches from master to 2.5 to fix the CONFIG_MAX_MSIX_TABLE_NUM gets wrong number.
=> config-tools: refine the CONFIG_MAX_MSIX_TABLE_NUM of release 2.5

doc/tutorials/using_windows_as_uos.rst, doc/tutorials/waag-secure-boot.rst
acrn-dm --windows parameter is used for specify
the Windows ORACLE virtio device driver,which is
used when enable secure boot in Windows, otherwise
the default REDHAT virtio device driver will be
used which is not certified by Microsoft
Signed-off-by: Liu, Hang1 <hang1.liu@intel.com>
=> doc:add more explanation on parameter --windows

devicemodel/hw/pci/virtio/virtio_console.c
"port->cb" in 'virtio_console_notify_tx()'
function maybe NULL when malicious inputs
are injected from virtio frondend in guest.
Tracked-On: #6388
=> dm: fix potential NULL pointer access in virtio_console.c

misc/config_tools/board_inspector/extractors/50-acpi.py, misc/config_tools/xforms/misc_cfg.h.xsl, misc/config_tools/xforms/vm_configurations.c.xsl
Extract the log area address from TPM2 acpi table and add node
log_area_start_address to board.xml. This emelment is used by host_pa of
mmiodevs.
=> config-tools: add native log area address

hypervisor/dm/vpci/ivshmem.c, hypervisor/include/arch/x86/asm/pgtable.h
ACRN does not support the variable range vMTRR. The default
memory type of vMTRR is UC. With this vMTRR emulation guest VM
such as Linux refuses to map the MMIO address space as WB. In
order to get better performance SHM BAR of ivshmem is mapped
with PAT ignored and memory type of SHM BAR is fixed to WB.
Tracked-On: #6389
=> hv: ivshmem: map SHM BAR with PAT ignored

devicemodel/hw/pci/virtio/virtio_console.c
"port->cb" in 'virtio_console_notify_tx()'
function maybe NULL when malicious inputs
are injected from virtio frondend in guest.
Tracked-On: #6388
=> [release_2.5] dm: fix potential NULL pointer access in virtio_console.c

misc/config_tools/data/ehl-crb-b/hybrid_rt.xml
On some boards it is seen that the log area of the physical TPM2 is
programmed to be 0. If TPM2 is passed through to a pre-launched VM in such
cases, a piece of memory starting from GPA 0 will be unmapped from the
Service VM, leading to Service VM crash due to early BIOS corruption
checks.
This patch temporarily disables TPM2 passthrough on such platforms. A
thorough fix should be proposed later to gracefully handle such cases.
Tracked-On: #6288
=> FIXME: temporarily disable TPM2 passthrough

hypervisor/common/event.c, hypervisor/include/common/event.h
Currently the sched event handling may encounter data race problem, and
as a result some vcpus might be stalled forever.
One example can be wbinvd handling where more than 1 vcpus are doing
wbinvd concurrently. The following is a possible execution of 3 vcpus:
-------
0                            1                           2
req [Note: 0]
req bit0 set [Note: 1]
IPI -> 0
req bit2 set
IPI -> 2
VMExit
req bit2 cleared
wait
vcpu2 descheduled
VMExit
req bit0 cleared
wait
vcpu0 descheduled
signal 0
event0->set=true
wake 0
signal 2
event2->set=true [Note: 3]
wake 2
vcpu2 scheduled
event2->set=false
resume
req
req bit0 set
IPI -> 0
req bit1 set
IPI -> 1
(doesn't matter)
vcpu0 scheduled [Note: 4]
signal 0
event0->set=true
(no wake) [Note: 2]
event0->set=false …
=> release_2.6: hv: Change sched_event structure to resolve data race in event handling

misc/config_tools/config_app/views.py
remove some tags check for scenario xml files in generic_board folder when
importing a new type of board in UI, and minor fix for the warning of config
editor.
=> config_tools: remove some tags check for scenario.xml in generic_board folder

hypervisor/arch/x86/guest/vcpuid.c, hypervisor/include/arch/x86/asm/page.h, misc/config_tools/xforms/board_info.h.xsl
Update platform maximum physical address width to 52 bits and mask off LA57 from cpuid.
Tracked-On: #6357
Signed-off-by: Liang Yi yi.liang@intel.com
=> ICX-d LCC bring-up

misc/config_tools/data/cfl-k700-i7/hybrid_rt.xml, misc/config_tools/data/whl-ipc-i5/hybrid_rt.xml, misc/config_tools/data/whl-ipc-i7/hybrid_rt.xml
Disables TPM2 passthrough on other platforms except TGL
follow the 6410 PR.
Tracked-On: #6288
=> config_tools: disable TPM2 passthrough on other platforms

misc/config_tools/schema/checks/pre_launched_vm_support.xsd, misc/config_tools/static_allocators/gpa.py
The term PSRAM is now obsoleted and should be replaced with SSRAM, as has been
done by commit 9facbb43b3c5 ("config-tool: rename PSRAM to SSRAM"). However,
there are two places in the configuration toolset that still uses PSRAM. This
patch updates these missed occurrences accordingly.
Tracked-On: #6012
=> config_tools: rename two missed PSRAMs to SSRAMs

doc/developer-guides/hld/hld-devicemodel.rst
Default e820 mem map in hld-devicemodel.rst is
mismatched with sw_load_common.c,update the doc
to align with code.
Signed-off-by: Liu, Hang1 <hang1.liu@intel.com>
=> doc: update hld-devicemodel with current e820 mem map

misc/config_tools/launch_config/com.py
Update lpc slot to origin value 1 from 31 in the script too,
because GOP driver has assumption to config space layout of
the device on 00:1f.0.
Tracked-On: #6340
=> config_tools: update lpc slot number in script

hypervisor/arch/x86/guest/ve820.c, hypervisor/dm/vpci/pci_pt.c, hypervisor/dm/vpci/vpci.c, hypervisor/include/common/ptdev.h
When pass-thru GPU to pre-launched Linux guest,
need to pass GPU OpRegion to the guest.
Here's the detailed steps:
1. reserve a memory region in ve820 table for GPU OpRegion
2. build EPT mapping for GPU OpRegion to pass-thru OpRegion to guest
3. emulate the pci config register for OpRegion
For the third step, here's detailed description:
The address of OpRegion locates on PCI config space offset 0xFC,
Normal Linux guest won't write this register,
so we can regard this register as read-only.
When guest reads this register, return the emulated value.
When guest writes this register, ignore the operation.
Tracked-On: #6387
Signed-off-by: Liu,Junming <junming.liu@intel.com>
=> hv:enable GVT-d for pre-launched linux guest in logical partion mode

hypervisor/arch/x86/guest/vm.c, hypervisor/dm/vgpio.c, hypervisor/include/dm/vgpio.h
Rename base_hpa/service_vm_pa to host_hpa in acrn_mmiodev data structure.
Tracked-On: #6366
=> hv: mmiodev: a minor bug fix about refine acrn_mmiodev data structure

devicemodel/include/pci_core.h
The address of OpRegion is not 4KB aligned,
if the OpRegion + extended VBT size is 16KB,
then it will take up to 5 physical pages in host.
So update the OpRegion size to 20KB
to expose the whole OpRegion to guest.
Tracked-On: #6270
Signed-off-by: Liu,Junming <junming.liu@intel.com>
=> dm: update the GPU OpRegion size to 20KB

hypervisor/arch/x86/guest/vcpu.c
If SOS is using kernel 5.4, hypervisor got panic with #GP.
Here is an example on KBL showing how the panic occurs when kernel 5.4 is used:
Notes:
* Physical MSR_IA32_XSS[bit 8] is 1 when physical CPU boots up.
* vcpu_get_guest_msr(vcpu, MSR_IA32_XSS)[bit 8] is initialized to 0.
Following thread switches would happen at run time:
1. idle thread -> vcpu thread
context_switch_in happens and rstore_xsave_area is called.
At this moment, vcpu->arch.xsave_enabled is false as vcpu is not launched yet
and init_vmcs is not called yet (where xsave_enabled is set to true).
Thus, physical MSR_IA32_XSS is not updated with the value of guest MSR_IA32_XSS.
States at this point:
* Physical MSR_IA32_XSS[bit 8] is 1.
* vcpu_get_guest_msr(vcpu, MSR_IA32_XSS)[bit 8] is 0.
2. vcpu thread -> idle thread …
=> [for v2.6] hv: initialize the XSAVE related processor state for guest

misc/config_tools/board_inspector/extractors/50-acpi.py, misc/config_tools/data/tgl-rvp/tgl-rvp.xml
ACPI device drivers use both _HID and _CID to identify devices they
match. This patch copies _CID objects to vACPI devices so that guest
drivers can recognize the passthrough devices properly.
Tracked-On: #6288
=> board_inspector: add _CID to vACPI device objects

misc/config_tools/library/scenario_cfg_lib.py
fix the issue that fail to generate launch script when to disable
CPU sharing.
Tracked-On: #6428
=> config_tools: fix the issue that fail to generate launch script

devicemodel/hw/pci/virtio/virtio_console.c
Function virtio_console_close_all will close all consoles, if the console->nports
value is 1, after the console be destroyed by the mevent teardown function, when
get the nports from the console, there will cause the NULL pointer. Fix the issue.
Tracked-On: #6431
Signed-off-by: Liu Long long.liu@intel.com
Reviewed-by: Jian Jun Chen jian.jun.chen@intel.com
Acked-by: Wang, Yu1 yu1.wang@intel.com
=> ACRN:DM: Fix the Null pointer error

doc/tutorials/acrn_configuration_tool.rst
PR #6418 renames the board inspector tool cli.py to board_inspector.py
and the configuration tool app.py to acrn_configurator.py
Update the documentation to use these new names.  Note that the ROScube
GSG is validated with ACRN v2.1 and instructs the user to checkout that
branch where the tool is still called app.py
=> doc: update configuration tool names

hypervisor/arch/x86/guest/nested.c
check_vmx_permission() is called in vmresume_vmexit_handler() and
vmlaunch_vmexit_handler() already.
=> hv: nested: redundant permission check on nested_vmentry()

hypervisor/arch/x86/guest/nested.c
Currently init_vmx_msrs() emulates same value for the IA32_VMX_xxx_CTLS
and IA32_VMX_TRUE_xxx_CTLS MSRs.
But the value of physical MSRs could be different between the pair,
and we need to adjust the emulated value accordingly.
=> hv: nested: fix bugs in init_vmx_msrs()

hypervisor/arch/x86/guest/vcpu.c
If SOS is using kernel 5.4, hypervisor got panic with #GP.
Here is an example on KBL showing how the panic occurs when kernel 5.4 is used:
Notes:
* Physical MSR_IA32_XSS[bit 8] is 1 when physical CPU boots up.
* vcpu_get_guest_msr(vcpu, MSR_IA32_XSS)[bit 8] is initialized to 0.
Following thread switches would happen at run time:
1. idle thread -> vcpu thread
context_switch_in happens and rstore_xsave_area is called.
At this moment, vcpu->arch.xsave_enabled is false as vcpu is not launched yet
and init_vmcs is not called yet (where xsave_enabled is set to true).
Thus, physical MSR_IA32_XSS is not updated with the value of guest MSR_IA32_XSS.
States at this point:
* Physical MSR_IA32_XSS[bit 8] is 1.
* vcpu_get_guest_msr(vcpu, MSR_IA32_XSS)[bit 8] is 0.
2. vcpu thread -> idle thread …
=> hv: initialize the XSAVE related processor state for guest

misc/config_tools/acpi_gen/bin_gen.py
According to TCG ACPI specification (version 1.2), the current revision of
TPM2 table, which has the optional log area fields, is 4. This patch
updates the revision of vTPM2 accordingly.
Tracked-On: #6288
=> config_tools: update vTPM2 revision to 4

misc/config_tools/config_app/views.py
1. as a workaround, comment the code to check MBA_DELAY tag when
creating a new scenario xml setting because of this tag are retrived
from scenario xml files in generic_board folder where it is removed
now.
2. update the template launch xml file names according the recent
update for launch xml files in generic folder.
=> config_tools: fix UI issue of creating new settings

hypervisor/common/hv_main.c, hypervisor/debug/shell.c, hypervisor/debug/shell_priv.h, hypervisor/include/arch/x86/asm/guest/vcpu.h, hypervisor/include/arch/x86/asm/per_cpu.h, hypervisor/include/debug/profiling.h, hypervisor/include/public/acrn_common.h, hypervisor/release/profiling.c
this feature is used to sample vmexit data per physical CPU
and per virtual CPU of VM, command used in HV console as following:
1. vmexit clear --> to clear current vmexit buffer
2. vmexit -->output current vmexit info
3. vmexit enable | disable, by default enabled.
Tracked-On: #5232
=> hv: dbg: sample vmexit data per-pCPU and per-vCPU

doc/getting-started/getting-started.rst
- mention usefulness of a fast computer for improving build time
- move Ubuntu boot USB drive earlier in the list of prereqs
- move some sentences around for clarity
- improve appearance with some more spacing after images
=> doc: GSG tweaks for DX

misc/config_tools/board_inspector/legacy/board_parser.py
remove the log "<board>.xml has been generated successfully!" in
board_parser.py, because it only mean that the board xml file have
been created sucessfully here, not the all data have been appended
successfully and pretty formatted.
=> config_tools: remove the log of sucessfully generating board XML

hypervisor/arch/x86/configs/vm_config.c, hypervisor/arch/x86/guest/vm.c, hypervisor/include/lib/util.h, hypervisor/include/public/acrn_common.h, hypervisor/quirks/security_vm_fixup.c, hypervisor/quirks/security_vm_fixup.h, hypervisor/quirks/smbios.h, misc/config_tools/data/tgl-rvp/hybrid.xml, misc/config_tools/library/common.py, misc/config_tools/schema/VMtypes.xsd, misc/config_tools/xforms/vm_configurations.h.xsl, misc/hv_prebuild/hv_prebuild.h
This patch passthrough native SMBIOS information to prelaunched VM.
SMBIOS table contains a small entry point structure and a table, of which
the entry point structure will be put in 0xf0000-0xfffff region in guest
address space, and the table will be put in the ACPI_NVS region in guest
address space.
This feature is guarded under config CONFIG_SECURITY_VM_FIXUP, which
by default should be disabled.
**This patch set contains modification to config-tools.**
=> release_2.6: SMBIOS passthrough for pre-launched VM

misc/config_tools/static_allocators/gpa.py
Allocates the log area start address using the same size as native environment.
=> config-tools: refine log area start address allocation

hypervisor/arch/x86/guest/vcpu.c, hypervisor/arch/x86/guest/vmcs.c, hypervisor/arch/x86/guest/vmsr.c, hypervisor/arch/x86/mmu.c, hypervisor/include/arch/x86/asm/guest/vcpu.h, hypervisor/include/arch/x86/asm/guest/vmcs.h
With these 2 patches, the CPUID roundtrip tests on TGL reduces from 
2895 TSC cycles to 2835 cycles.
=> hv: optimize handling of IA32_EFER

doc/getting-started/getting-started.rst
When I follow the GSG, I got a error at the build process.
```
/bin/sh: 1: bc: not found
```
So, I added bc to dependencies.
=> doc: Add bc to build dependencies

hypervisor/common/hypercall.c
GSI of hcall_set_irqline should be checked against target_vm's
total GSI count instead of SOS's total GSI count.
Tracked-On: #6357
=> hv: GSI of hcall_set_irqline should be checked against target_vm

hypervisor/common/hv_main.c, hypervisor/include/arch/x86/asm/guest/vcpu.h
- remove vcpu->arch.nrexits which is useless.
- record full 32 bits of exit_reason to TRACE_2L(). Make the code simpler.
=> hv: minor cleanup of hv_main.c

hypervisor/debug/shell.c
In ACRN RT VM if the lapic is passthrough to the guest, the ipi can't
trigger VM_EXIT and the vNMI is just for notification, it can't handle
the smp_call function. Modify vcpu_dumpreg function prompt user switch
to vLAPIC mode for vCPU register dump.
Tracked-On: #6473
=> ACRN:hv: Fix vcpu_dumpreg command hang issue

misc/config_tools/data/ehl-crb-b/fusa_partition.xml, misc/config_tools/data/ehl-crb-b/hybrid.xml, misc/config_tools/data/generic_board/hybrid.xml, misc/config_tools/data/nuc11tnbi5/hybrid.xml, misc/config_tools/data/nuc7i7dnb/hybrid.xml, misc/config_tools/data/tgl-rvp/hybrid.xml, misc/config_tools/data/whl-ipc-i5/hybrid.xml, misc/config_tools/data/whl-ipc-i7/hybrid.xml, misc/config_tools/schema/VMtypes.xsd, misc/config_tools/schema/types.xsd, misc/config_tools/xforms/vm_configurations.c.xsl
Allow the kern_load_addr and kern_entry_addr take empty string.
Tracked-On: #6461
=> config-tools: Kernel load and entry address accept empty string

devicemodel/hw/pci/xhci.c
The event ring segment table  pointer may be NULL when get the address
from guest, add pointer check before use it.
Tracked-On: #6476
=> ACRN:DM: Add pointer check before use the erst

hypervisor/debug/shell.c, hypervisor/debug/shell_priv.h, hypervisor/include/arch/x86/asm/guest/vcpu.h
inj_guest_exp can be used to inject a virtual exception to a
specified vcpu of a vm. The command format is as follows:
inj_guest_exp <vm id, vcpu id, exception_num>
Tracked-On: #6468
=> hv: debug: add debug command inj_guest_exp

devicemodel/log/disk_logger.c
detection of any error in 'probe_disk_log_file()'
calling 'pr_err()' will cause 'write_to_disk()' function
being called recursively infinitely, as pr_err will
call write_to_disk() and trap to probe_disk_log_file() again,
hence program will crash finally.
This patch fix above issue by using printf instead of pr_err,
as printf outputs to console directly.
Tracked-On: #6518
=> [release_2.6]dm: fix potential program crash issue in disk_logger

devicemodel/log/disk_logger.c
detection of any error in 'probe_disk_log_file()'
calling 'pr_err()' will cause 'write_to_disk()' function
being called recursively infinitely, as pr_err will
call write_to_disk() and trap to probe_disk_log_file() again,
hence program will crash finally.
This patch fix above issue by using printf instead of pr_err,
as printf outputs to console directly.
Tracked-On: #6518
=> dm: fix potential program crash issue in disk_logger

misc/config_tools/data/tgl-rvp/hybrid.xml, misc/config_tools/data/tgl-rvp/hybrid_rt.xml
For SMBIOS and TPM, enable SECURITY_VM_FIXUP and add GUEST_FLAG_SECURITY_VM
flag in TGL hybrid_rt.xml. Then disable SECURITY_VM_FIXUP in TGL hybrid.xml
because it’s previously enabled in hybrid.xml instead of hybrid_rt.xml by
mistake.
=> config_tools: update scenario xml files on tgl-rvp platform

hypervisor/arch/x86/mmu.c
Currently ACRN assumes firmware setup IA32_PAT correctly.  This patch
explicitly initializes host IA32_PAT MSR according to ISDM Table 11-12.
Memory Type Setting of PAT Entries Following a Power-up or Reset.
ACRN creates host page tables based on PAT0 (WB) and PAT3 (UC).
=> hv: initialize host IA32_PAT MSR

misc/config_tools/data/ehl-crb-b/hybrid.xml
for ehl-crb-b platform, update sos rootfs from "dev/sda3"
to "/dev/nvme0n1p3" in hybrid.xml file.
Tracked-On: #6530
=> config_tools: update scenario xml file on ehl-crb-b platform

doc/tutorials/acrn_on_qemu.rst
Qemu HOST-passthrough has hardware dependency CPU feature;
which may block ACRN to boot up on Qemu;So change QEMU HOST-passthrough to CPU Named Model since v2.6.
=> Doc: ACRN on QEMU changed to CPU Named Model

doc/tutorials/using_hybrid_mode_on_nuc.rst
Now ACRN support booting pre-launched Zephyr VM kernel in ELF format
instead of previous raw image format, so update usage in related doc.
=> doc: update usage of zephyr as pre-launched VM kernel

doc/developer-guides/hld/virtio-net.rst
Fix broken links in the Virtio-Net HLD that point at the network
scripts in the source code repository.
Tracked-On: #6542
=> doc: fix broken links to network scripts in HLD

devicemodel/hw/pci/xhci.c, devicemodel/hw/platform/usb_pmapper.c, devicemodel/include/usb_core.h, devicemodel/include/usb_pmapper.h
When destroy the usb device release the resource allocate for transfer
in case cause the memory leak issue. Add the release and cancel
transfer request call back for the emulation device, use the emulation
device call back in xHCI controller emulation.
Tracked-On: #6533
=> ACRN:DM Release resource when destroy the device

misc/config_tools/board_inspector/cli.py
Customized environment variables are not inherited to child processes
created by the subprocess module. As a result the legacy board parser may
not be able to locate the prerequisite utilities if they can be found only
with the customized PATH.
This patch passes the PATH of cli.py to the legacy parser so that both
scripts use the same PATH to search for utilities.
This patch is added in v2 of the series.
Tracked-On: #6287
=> [release 2.5]board_inspector/cli: export PATH to the legacy board parser

misc/config_tools/launch_config/com.py, misc/config_tools/launch_config/pt.py
We will use SRIOV based GPU sharing to replace default GVT-d config
on adl-s-crb platform. So add the logic of passthru gpu VF,
If the string "sriov" is found in launch xml, we will hardcode
different value to gpu VF and set different parameter for WaaG and
LaaG in launch script.
The relevant line in the generated launch script will look like this:
Laag: "-s 2,passthru,0/2/1,gpu  \"
WaaG: "-s 2,passthru,0/2/2,igd-vf  \"
Tracked-On: #6290
=> config_tools: support SRIOV based GPU sharing in launch script

hypervisor/arch/x86/guest/vm.c, hypervisor/dm/vgpio.c, hypervisor/include/dm/vgpio.h
Rename base_hpa to host_pa in acrn_mmiodev data structure.
Tracked-On: #6366
=> release_2.6: hv: mmiodev: a minor bug fix about refine acrn_mmiodev data structure

misc/config_tools/xforms/lib.xsl, misc/config_tools/xforms/misc_cfg.h.xsl
The whitespaces between delimiter saperated elemnts of a list causes
acrn:get-common-clos-max and acrn:find-list-min returns unexpected
numbers.
Translate the whitespaces to nothing and rewrite acrn:find-list-min and
acrn:get-common-clos-max.
Tracked-On: #6515
=> config-tools: refine misc_cfg.h.xsl and lib.xsl

misc/config_tools/config_app/templates/base.html, misc/config_tools/config_app/templates/launch.html, misc/config_tools/config_app/templates/scenario.html
1. For initial UI, rename "ACRN Config" to "ACRN Configurator",
rename "Scenario Setting" to "Scenario Settings", rename "Launch Setting"
to "Launch Settings", and rename "Import Board info" to "Import Board XML";
2. For UI scenario selection, change title "Load Scenario Setting" to
"Load Default Scenario Settings", Change title "Save as" to "Save Scenario XML",
and rename "XML Name" to "Scenario XML Name";
7. For UI launch selection, rename "Load Launch setting" to
"Load Default Launch Settings", change title "Save as" to "Save Launch XML",
change "XML Name" to "Launch XML Name" and Change "Source Path" to "Launch XML Path".
Tracked-On: #6417
=> config_tools: rename UI menu

hypervisor/arch/x86/guest/vmsr.c, hypervisor/arch/x86/rdt.c, misc/config_tools/data/tgl-rvp/industry.xml, misc/config_tools/data/tgl-rvp/tgl-rvp.xml
enable CAT for tgl-rvp on release-v2.5
Configure LLC CAT rt-core: 0xf00, others: 0x0ff
Tracked-On: #6547
=> hv: v2.5: enable CAT for tgl-rvp

misc/debug_tools/acrn_crashlog/acrnprobe/loop.c
In e2fsprogs v1.46.2, s_volume_name is defined with attribute
nonstring. According to gcc doc, nostring defined string may
not contain a terminating NULL. So array safed function should
be used.
We use strncmp instead of strcmp to do comparing here.
Tracked-On: #6494
=> crashlog: fix build issue with e2fsprogs v1.46.2

hypervisor/scripts/makefile/config.mk, misc/config_tools/scenario_config/default_populator.py
While we have default values of configuration entries stated in the schema
of scenario XMLs, today we still require user-given scenario XMLs to
contain literally ALL XML nodes. Missing of a single node will cause schema
validation errors even though we can use its default value defined in the
schema.
This patch allows user-given scenario XMLs to ignore nodes with default
values. It is done by adding the missing nodes, all containing the defined
default values, to the input scenario XML when copying it to the build
directory. This approach imposes no changes to either the schema or
subsequent scripts in the build system.
Tracked-On: #6292
=> config_tools: populate default values in scenario XML

devicemodel/hw/pci/passthrough.c, hypervisor/include/hw/pci.h
'error' might be used uninitialized in cfginitbar. So initialize it to zero
at the beginning.
Tracked-On: #6284
=> release_2.6: dm: pci: minor bug fix about uninitialized local variable

Makefile, hypervisor/Makefile
Add a couple of missing dependencies in the ACRN Makefiles:
1. 'acrn.bin' is required before the hypervisor can be installed
2. The 'acrn_mngr.h' needs to be installed ('tools-install') in
the build folder.
Tracked-On: #6360
=> Makefile: add missing deps in top-level and hypervisor Makefile

devicemodel/hw/pci/passthrough.c
Destory reseverd PIO BAR when deinit passthrough PCI device to free
reserved_bar_regions.
Tracked-On: #6508
=> dm: pci: destory reseverd PIO BAR when deinit passthrough PCI device

doc/developer-guides/hld/hv-ioc-virt.rst
Removed the Porting and Adaptation to Different Platforms section in hv-ioc-virt.rst, because it was blank.
=> doc: Remove empty section marked "TBD"

misc/config_tools/static_allocators/gpa.py
Reserve the log area in [0x7FFB0000, 0x7FFF0000).
=> config-tools: assign a fixed address to log area start address

misc/config_tools/launch_config/pt.py
The execution order of the "modprobe pci_stub" command is erroneous
in the launch script generation logic. The "modprobe pci_stub" command
should be executed before unbinding passthru devices, so we adjust the
command excution order.
Tracked-On: #6565
=> config_tools: adjust the execution order of pci_stub command

hypervisor/include/hw/pci.h
Before checking whether a PCI device is a Multi-Function Device or not, we need
make sure this PCI device is a valid PCI device. For a valid PCI device, the
'Header Layout' field in Header Type Register must be 000 0000b (Type 0 PCI device)
or 000 0001b (Type 1 PCI device).
So for a valid PCI device, the Header Type can't be 0xff.
Tracked-On: #4134
=> hv: pci: fix a minor bug about is_pci_cfg_multifunction

misc/debug_tools/acrn_trace/acrntrace.h
Now ACRN support platform which CPU numbers are large than 10. So the old value
for DEV_PATH_LEN is not enough (18 is not enough for /dev/acrn_trace_xx).
Tracked-On: #6572
=> misc: acrn_trace: enlarge DEV_PATH_LEN

hypervisor/debug/shell.c
Normalize hypervisor help command output format, remove the 10 lines
limit for one screen, fix the misspelled words.
Tracked-On: #5112
Reviewed-by: VanCutsem, Geoffroy <geoffroy.vancutsem@intel.com>
=> ACRN:HV: Normalize hypervisor help output format

hypervisor/arch/x86/guest/assign.c, hypervisor/dm/vioapic.c
Support INTx in local APIC passthrough case.
Assumption:
(a) IOAPIC pins won't be shared between LAPIC PT guest and other guests;
(b) The guest would not trigger this IRQ before it switched to x2 APIC mode.
=> HV: support INTx for lapic-PT

CONTRIBUTING.rst, doc/developer-guides/contribute_guidelines.rst
Summarize the ACRN contributing guidelines (fully documented in a
separate document) and add to the top level of our project repo (as
expected by GitHub and our Technical Steering Committee)
=> doc: Add project CONTRIBUTING repo page

hypervisor/scripts/makefile/config.mk
The current config.mk uses the variable BOARD_FILE as the path to the board
XML when generating an unmodified copy of configuration files for
comparison, which is incorrect. The right variable is HV_BOARD_XML which is
the path to the copy of board XML that is actually used for the build.
This patch corrects the bug above.
In addition, this patch also skips binary files (which are not meant to be
edited manually) when calculating the differences.
Tracked-On: #6592
=> Makefile: fix wrong reference to board XML and skip binary in diffconfig

doc/getting-started/getting-started.rst
1. Because the < > in the document will mislead users to copy and paste directly,
modify the < > to " ".
2. Add sample diagrams for user reference.
3. Because there is a problem with the user adding the GRUB_CMDLINE_LINUX=text
parameter, delete this parameter.
4. The script generation of launch_uos_id3.sh does not match the GitHub and doc,
modify the parameters.
=>     doc: update documentation and grub file

doc/tutorials/acrn_configuration_tool.rst
add virtio input element in the description of elements for
launch XMLs in config doc.
=> doc: add virtio input element in config doc

doc/developer-guides/c_coding_guidelines.rst, doc/developer-guides/contribute_guidelines.rst, doc/developer-guides/doc_guidelines.rst, doc/developer-guides/graphviz.rst, doc/developer-guides/hld/hld-APL_GVT-g.rst, doc/developer-guides/hld/hld-overview.rst, doc/developer-guides/hld/hld-security.rst, doc/developer-guides/hld/hv-cpu-virt.rst, doc/developer-guides/hld/hv-dev-passthrough.rst, doc/developer-guides/hld/hv-interrupt.rst, doc/developer-guides/hld/hv-rdt.rst, doc/developer-guides/hld/hv-startup.rst, doc/developer-guides/hld/hv-vm-management.rst, doc/developer-guides/hld/virtio-console.rst, doc/developer-guides/trusty.rst, doc/getting-started/getting-started.rst, doc/introduction/index.rst, doc/tutorials/enable_ivshmem.rst, doc/tutorials/pre-launched-rt.rst, doc/tutorials/rdt_configuration.rst, doc/tutorials/rtvm_performance_tips.rst, doc/tutorials/sgx_virtualization.rst, doc/tutorials/using_serial_port.rst, doc/tutorials/waag-secure-boot.rst
* General scan for misspellings, "smart quotes", and formatting errors
missed during regular review. Also removed used of "please".
* Fix old XML examples that had desc="..." comments. These comments were
moved to to xsd files instead of being in the XML files themselves.
=> doc: fix mispellings and formatting

doc/developer-guides/VBSK-analysis.rst, doc/developer-guides/hld/hld-APL_GVT-g.rst, doc/developer-guides/hld/virtio-net.rst
Fixed some additional doc references missed in PR #6283
=> doc: finish renaming vmh to hsm

misc/config_tools/scenario_config/default_populator.py
The default value population algorithm introduced by commit
2bfaa34 ("config_tools: populate default values in scenario XML") only
populates default values to the first occurrence of a tag when the tag is
specified to allow multiple occurrences under an xs:all node. This may lead
to incomplete scenario XML as some of the default values are missed.
This patch fixes this issue by checking **all** nodes having the same tag
under a node specified by an xs:all schema.
Fixes: 2bfaa34 ("config_tools: populate default values in scenario XML")
Tracked-On: #6292
=> config_tools: populate default values to all nodes

doc/tutorials/acrn_on_qemu.rst
ACRN will not maintain User VM kernel config any more;
ovmf will be used to launch L2 guest by default.
=> Doc: launch L2 guest with ovmf for ACRN on QEMU

doc/tutorials/using_hybrid_mode_on_nuc.rst, doc/tutorials/using_partition_mode_on_nuc.rst
1. Modify hybrid update ubuntu grub Note: The syntax is easy for users to understand
2. Add to view the serial port number, enter the serial hybrid verification mode
3. Delete the kernel, because the config_uos file has been abandoned for maintenance,
now the Ubuntu native kernel image is used and added to the document
4. Add to view the serial port number, enter the serial port logic_partition verification method
Signed-off-by: Zhongshan.Liu <zhongzhenx.liu@intel.com>
=>     doc: Steps to update hybrid and logic_Partition documents

hypervisor/Makefile, hypervisor/arch/x86/guest/vcpu.c, hypervisor/common/hv_main.c, hypervisor/common/sched_prio.c, hypervisor/common/schedule.c, hypervisor/include/arch/x86/asm/per_cpu.h, hypervisor/include/arch/x86/asm/vm_config.h, hypervisor/include/common/schedule.h, misc/config_tools/library/hv_cfg_lib.py, misc/config_tools/schema/config.xsd, misc/config_tools/schema/types.xsd, misc/config_tools/xforms/vm_configurations.c.xsl
This patch adds a new priority based scheduler to support
vCPU scheduling based on their pre-configured priorities.
A vCPU can be running only if there is no higher priority
vCPU running on the same pCPU.
Tracked-On: #6571
=> hv: add priority based scheduler

hypervisor/arch/x86/guest/vmcs.c
Some processors don't support VMX_PROCBASED_CTLS_TERTIARY bit
and VMX_PROCBASED_CTLS2_UWAIT_PAUSE bit in MSRs
(IA32_VMX_PROCBASED_CTLS & IA32_VMX_PROCBASED_CTLS2),
HV will output error log which will cause confusion,
change the log level from pr_err to pr_info.
Tracked-On: #6397
=> hv:change log level for check_vmx_ctrl

doc/getting-started/getting-started.rst, misc/config_tools/board_inspector/README
Without this ``iomem=relaxed`` kernel parameter, the generated board XML
is essentially the same as having ``--basic`` when executing the board
inspector, i.e. the ACPI namespace will not be parsed. The generated
board XML may still work, but some functionality (e.g. passthru of TPM
and other PCI devices that need INTx) will no longer work due to lack of
hardware information.
Replacing PR #6618
=> doc: add iomem kernel parameter for board inspector

misc/config_tools/acpi_gen/asl_gen.py, misc/config_tools/static_allocators/gpa.py
Pass through the io-ports for the passthrough pci devices of pre-launched VM.
Three parts to support this feature:
1. Identical map the pci devices io-port address for pre-launched VM
2. Set the io-ports address range to DSDT
3. Avoid to allocate the bar index for VMSIX
Tracked-On: #6620
=> config-tools: pci devices' io-ports passthrough

hypervisor/arch/x86/cpu.c, hypervisor/boot/boot.c, hypervisor/boot/multiboot/multiboot2.c
In the commit of 4e1deab3d9fbb7ba80e9c6c4cb8e785df33888b1, we changed the
init sequence that init paging first and then init e820 because we worried
about the efi memory map could be beyond 4GB space on some platform.
After we double checked multiboot2 spec, it is guaranteed that the efi memory
map must be under 4GB space. Consider that the page table will be allocated
in free memory space in future, we have to change the init sequence back that
init e820 first and then init paging.
Tracked-On: #5626
=> HV: init e820 before init paging

misc/config_tools/schema/config.xsd, misc/config_tools/schema/types.xsd
Commit e678dc8 ("doc: pick doc updates for v2.6 release") picked the latest
scenario XML schema from the main branch, which includes both documentation
changes and new configuration entries. These new entries cause build
failures of the release branch because those new entries do not exist in
the scenario XMLs of v2.6 and the default value populator is yet to be
added for v2.7.
This patch removes those new entries to unblock the build.
=> config_tools: schema: revert to old schema

hypervisor/scripts/makefile/config.mk
update board name from nuc7i7dnb to nuc11tnbi5 in makefile because
we have removed the nuc7i7dnb board folder, and also update the
scenario name from industry to shared to fix "make all" build issue.
=> config_tools: update board name in makefile

doc/getting-started/getting-started.rst
As recommended, add a ``-y`` to the ``apt install`` commands so they
don't prompt the user to confirm the installation, seen as unnecessary
in this context.
Also, wrap lines that are longer then 80 chars to improve git reviews
and follow our doc conventions.
=> doc: GSG apt install command DX improvement

hypervisor/arch/x86/guest/nested.c
Change "uint64_t vmcs_hva" to "void *vmcs_hva" in the input argument,
list, so that no type casting is needed when calling them from pointers.
=> hv: nested: refine vmcs12_read/write_field APIs

hypervisor/arch/x86/guest/virq.c
move the bitmap test call out of vcpu_inject_exception(), then we call
the expensive bitmap_test_and_clear_lock() only pending_req_bits is
non-zero and call vcpu_inject_exception() only if needed.
=> hv: call vcpu_inject_exception() only when ACRN_REQUEST_EXCP is set

hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/e820.c, hypervisor/arch/x86/guest/ve820.c, hypervisor/arch/x86/guest/vm.c, hypervisor/arch/x86/mmu.c, hypervisor/bsp/ld/link_ram.ld.in, hypervisor/common/hypercall.c, hypervisor/include/arch/x86/asm/boot/ld_sym.h, hypervisor/include/arch/x86/asm/e820.h, hypervisor/include/arch/x86/asm/mmu.h
It's difficult to configure CONFIG_HV_RAM_SIZE properly at once. This patch
not only remove CONFIG_HV_RAM_SIZE, but also we use ld linker script to
dynamically get the size of HV RAM size.
Tracked-On: #6663
=> hv: remove CONFIG_HV_RAM_SIZE

misc/config_tools/board_inspector/board_inspector.py
add Board Inspector tool success message after users were successful
creating the board configuration file.
Tracked-On: #6670
=> config_tools: add Board Inspector tool success message

hypervisor/include/arch/x86/asm/guest/guest_memory.h, hypervisor/include/public/acrn_common.h, hypervisor/include/public/acrn_hv_defs.h
PR #6283 updated code and docs to the new kernel HSM driver. Fix
some references to VHM missed in the doxygen comments. Also fixed some
misspellings while in these files.
Tracked-On: #6282
=> doc: update uses of VHM in doxygen comments

devicemodel/core/main.c, devicemodel/hw/mmio/core.c, devicemodel/hw/platform/acpi/acpi.c, devicemodel/hw/platform/tpm/tpm.c, devicemodel/include/acpi.h, devicemodel/include/mmio_dev.h, devicemodel/include/tpm.h
This PR enables TPM2 passthrough to post-launched VM with eventlog support.
User starts by providing command line "--acpidev_pt <TPM2_HID>",
of which the <TPM2_HID> will be searched from /proc/iomem for TPM2 buffer
start address and size. Furthermore, If TPM2 eventlog is supported,
TPM2 eventlog information will be retrieved from sysfs TPM2 table and
passed-through as well.
=> dm: TPM passthrough for post-launched VM

misc/config_tools/acpi_gen/bin_gen.py, misc/config_tools/board_inspector/extractors/50-acpi.py
This PR ports the following fixes to the board inspector & config tools on v2.6 release back to mainline:
* c215229 config_tools: update vTPM2 revision to 4
* 855b0ed board_inspector: add _CID to vACPI device objects
The board XML will be updated accordingly in a later PR.
=> Port board inspector fixes on v2.6 release back to mainline

hypervisor/arch/x86/guest/lock_instr_emul.c, hypervisor/arch/x86/guest/virq.c, hypervisor/include/arch/x86/asm/guest/virq.h
In lock instruction emulation, we use vcpu_make_request and
signal_event pairs to shoot down/release other vcpus.
However, vcpu_make_request is async and does not guarantee an execution
of wait_event on target vcpu, and we want wait_event to be consistent
with signal_event.
Consider following scenarios:
1, When target vcpu's state has not yet turned to VCPU_RUNNING,
vcpu_make_request on ACRN_REQUEST_SPLIT_LOCK does not make sense, and will
not result in wait_event.
2, When target vcpu is already requested on ACRN_REQUEST_SPLIT_LOCK (i.e., the
corresponding bit in pending_req is set) but not yet handled,
the vcpu_make_request call does not result in wait_event as 1 bit is not
enough to cache multiple requests.
This patch tries to add checks in vcpu_kick_lock_instr_emulation and …
=> hv: Fix vcpu signaling racing problem in lock instruction emulation

doc/static/acrn-custom.css
Words in the function prototypes looked run together making it hard to
read, so tweak the CSS to add a bit of padding.
=> doc: tweak CSS for Sphinx/Breathe API documents

misc/config_tools/data/cfl-k700-i7/hybrid_rt.xml, misc/config_tools/data/cfl-k700-i7/shared.xml, misc/config_tools/data/generic_board/hybrid.xml, misc/config_tools/data/generic_board/hybrid_rt.xml, misc/config_tools/data/generic_board/shared.xml, misc/config_tools/data/nuc11tnbi5/hybrid.xml, misc/config_tools/data/nuc11tnbi5/shared.xml, misc/config_tools/data/qemu/sdc.xml, misc/config_tools/data/whl-ipc-i5/hybrid.xml, misc/config_tools/data/whl-ipc-i5/hybrid_rt.xml, misc/config_tools/data/whl-ipc-i5/sdc.xml, misc/config_tools/data/whl-ipc-i5/shared.xml
In this patch, add vuart configuration in scenario XML of
each board to support communication between service VM and
user VM since system shutdown feature need to send commands
through this vuart communication channel.
The follow changes are made in this patch:
- Add multi legacy vuart for service VM for communication
- Add one legacy vuart for user VM for communication
- Add 8250.nr_uarts parameter in command line of service OS
=> misc: config_tools: add vuart for communication

misc/config_tools/static_allocators/gpa.py
Get the start and end address based on all pci bus memory resource.
Tracked-On: #6752
=> config-tools: refine MMIO32/64_START and MMIO32/64_END

misc/config_tools/data/cfl-k700-i7/hybrid_rt.xml, misc/config_tools/data/cfl-k700-i7/shared.xml, misc/config_tools/data/qemu/sdc.xml, misc/config_tools/hv_config/hv_item.py, misc/config_tools/library/hv_cfg_lib.py, misc/config_tools/schema/config.xsd
1. remove hvlog parameter in bootargs for all platforms.
2. update HV_RAM_START default address from 2MB to 4MB.
3. add the check that the HV_RAM_START value should be larger
than or equal to 2MB and 2MB aligned.
Tracked-On: #6663
=> config_tools: remove hvlog parameter and update HV_RAM_START default address

misc/config_tools/launch_config/launch_cfg_gen.py, misc/config_tools/library/launch_cfg_lib.py
When we add two or more virtio block devices and rename them for a VM
in launch xml files, then generate launch scripts through the UI.
After ensuring the devices names are different, we repeat these operations
continuously. Finally we will get the duplicate PT_SLOT value 30 for
different virtio block devices in a launch script. This is wrong.
As a workaround, we reassign PT_SLOT variate to reset it after the launch
script is generated every time.
Tracked-On: #6767
=> config_tools: fix the duplicate PT_SLOT value issue

doc/Makefile, doc/index.rst, doc/scripts/fix-git-modified-date.sh, doc/static/acrn-custom.css
The "Last Updated" footer shows the date the page was published, not
when the content was last updated. This has caused readers some
confusion.  Update the footer with the date of the git commit that last
updated the document, and clarify with both the last modified and
published dates in the footer, something like this:
Last modified: Aug 19, 2021. Published: Nov 03, 2021.
=> doc: update last updated information on page footers

misc/config_tools/config_app/templates/launch.html
Since PRs #6760 and #6765 have landed,
we also need to rename "UOS" to "user vm" in UI.
Tracked-On: #6744
=> config_tools: rename UOS to user vm in UI

misc/config_tools/data/cfl-k700-i7/hybrid_rt.xml, misc/config_tools/data/cfl-k700-i7/shared.xml, misc/config_tools/data/generic_board/hybrid.xml, misc/config_tools/data/generic_board/hybrid_rt.xml, misc/config_tools/data/generic_board/shared.xml, misc/config_tools/data/nuc11tnbi5/hybrid.xml, misc/config_tools/data/nuc11tnbi5/shared.xml, misc/config_tools/data/qemu/sdc.xml, misc/config_tools/data/whl-ipc-i5/hybrid.xml, misc/config_tools/data/whl-ipc-i5/hybrid_rt.xml, misc/config_tools/data/whl-ipc-i5/sdc.xml, misc/config_tools/data/whl-ipc-i5/shared.xml
This reverts commit 9e2edd5192d217c8a3eff704d728ae2b9d0085c1.
Because config UI doesn't support multi legacy vuart in current logic,
we need to revert the commit to unblock UI.
=> Revert "misc: config_tools: add vuart for communication"

devicemodel/hw/mmio/core.c
Fix a potential overflow problem in get_more_acpi_dev_info where ch_read
might have a value greater than 32.
Tracked-On: #6769
=> dm: minor fix: fix potential overflow in device model

misc/config_tools/config_app/views.py
When we click the "Import XML" button to import the scenario XML file, then click
the "Export XML" to export the XML files, we will find some errors because
UI doesn't show the default value set in schema.
As a workaround, we call default_populator.py in UI to expand the default value
in the scenario XML file to fix the issue.
Tracked-On: #6292
=> config_tools: fix UI issue don't expand the default value in xml file

misc/debug_tools/acrn_log/README.rst
- Replace SOS with Service VM
- Update file paths to acrnlog directory
=> doc: terminology cleanup in acrnlog readme

devicemodel/hw/platform/acpi/rtct.c
Address of software SRAM configured by TCC tool shall be
page-aligned. This patch fixup these addresses if they're
not page aligned.
Tracked-On: #6778
=> dm: fixup the alignment of software region address

hypervisor/Makefile, misc/config_tools/service_vm_config/README, misc/config_tools/service_vm_config/serial_config.py
Generate serial configuration file for service VM according
to scenario file and vUART ports base address allocated by
config tool.
Currently, some non-standard serial ports are emulated in
hypervisor and will be used to do communication between service
VM and user VM, so need to generate serial configuration file
to configure these serial ports for service VM.
v1-->v2:
Fix some type issues
Refine script code format
=> misc: config_tools: generate serial configuration file

devicemodel/hw/pci/core.c, devicemodel/hw/pci/xhci.c
Fix the Vulnerable coding style in xhci and pci core
Tracked-On: #6769
Signed-off-by: Liu Long <longliu@intel.com>
=> ACRN: DM: Vulnerable coding style in device-model

doc/developer-guides/hld/hv-vt-d.rst
Publisher of this document confirmed that VT-d spec link should be updated, and the existing link will be EOL.
=> doc: Update VT-d spec link

doc/developer-guides/hld/hld-power-management.rst, doc/getting-started/getting-started.rst
It's recommended we always use the .git extension when referring to the
git repo when cloning.  Fix that in the GSG.
Also, fix a misspelling in the hld-power-management doc.
=> doc: fix git clone and misspelling

doc/tutorials/nvmx_virtualization.rst
=> doc: terminology cleanup in nvmx tutorial

doc/user-guides/acrn-dm-parameters.rst
=> doc: terminology cleanup in DM params

.deb.conf
When some communication vuarts are configured in hypervisor
scenario files, serial.conf will be generated and should be
installed in the etc folder of service VM.
In this patch, update deb configuration file to install
serial.conf into etc folder of service VM.
=> deb-pkg: update deb configuration to install serial.conf

misc/config_tools/launch_config/launch_cfg_gen.py
when we add two or more virtio block devices and rename them for a VM
in launch xml files, then generate launch scripts through the UI.
After ensuring the devices names are different, we repeat these operations
continuously. Finally we will get the duplicate PT_SLOT value for
different virtio block devices in a launch script. This is wrong.
After user click the "Generate Launch Script" button to generate the
launch scripts every time, we will reset PT_SLOT variate to fix the issue.
Tracked-On: #6767
=> config_tools: fix the duplicate PT_SLOT value issue in UI

misc/config_tools/launch_config/launch_item.py, misc/config_tools/library/scenario_cfg_lib.py, misc/config_tools/scenario_config/scenario_item.py
1. ensure cpu affinity in launch xml is subset of its scenario settings.
2. cpu_affinity is a must have parameter for acrn_dm, if the user did not provide cpu affinity in launch xml, load it from scenario settings.
Tracked-On: #6724
=> config_tool: add cpu affinity check (release_2.7)

hypervisor/arch/x86/guest/trusty.c, hypervisor/arch/x86/guest/vcpu.c, hypervisor/include/arch/x86/asm/cpu.h, hypervisor/include/arch/x86/asm/guest/vcpu.h
Commit cbf3825 "hv: Pass-through IA32_TSC_AUX MSR to L1 guest"
lets guest own the physical MSR IA32_TSC_AUX and does not handle this MSR
in the hypervisor.
If multiple vCPUs share the same pCPU, when one vCPU reads MSR IA32_TSC_AUX,
it may get the value set by other vCPUs.
To fix this issue, this patch does:
- initialize the MSR content to 0 for the given vCPU, which is consistent with
the value specified in SDM Vol3 "Table 9-1. IA-32 and Intel 64 Processor
States Following Power-up, Reset, or INIT"
- save/restore the MSR content for the given vCPU during context switch
v1 -> v2:
* According to Table 9-1, the content of IA32_TSC_AUX MSR is unchanged
following INIT, v2 updates the initialization logic so that the content for
vCPU is consistent with SDM.
Tracked-On: #6799
Signed-off-by: …
=> [for v2.7] hv: initialize and save/restore IA32_TSC_AUX MSR for guest

misc/services/life_mngr/Makefile, misc/services/life_mngr/command_handler.c, misc/services/life_mngr/uart.h, misc/services/life_mngr/uart_channel.c, misc/services/life_mngr/uart_channel.h
Change macro name:
SCECOND_TO_US --> SECOND_TO_US
Use macro CONF_DIR in Makefile
=> [for v2.7]misc: life_mngr: fix some typo issues

misc/config_tools/xforms/lib.xsl, misc/config_tools/xforms/misc_cfg.h.xsl
Rename function name to get-common-clos-count and refine the calculation. Some platforms have odd clos counts. Using "floor" to get integer numbers for macros.
Tracked-On: #6755
=> config-tools: refine acrn:get-common-clos-max

hypervisor/arch/x86/guest/trusty.c, hypervisor/arch/x86/guest/vcpu.c, hypervisor/include/arch/x86/asm/cpu.h, hypervisor/include/arch/x86/asm/guest/vcpu.h
Commit cbf3825 "hv: Pass-through IA32_TSC_AUX MSR to L1 guest"
lets guest own the physical MSR IA32_TSC_AUX and does not handle this MSR
in the hypervisor.
If multiple vCPUs share the same pCPU, when one vCPU reads MSR IA32_TSC_AUX,
it may get the value set by other vCPUs.
To fix this issue, this patch does:
- initialize the MSR content to 0 for the given vCPU, which is consistent with
the value specified in SDM Vol3 "Table 9-1. IA-32 and Intel 64 Processor
States Following Power-up, Reset, or INIT"
- save/restore the MSR content for the given vCPU during context switch
v1 -> v2:
* According to Table 9-1, the content of IA32_TSC_AUX MSR is unchanged
following INIT, v2 updates the initialization logic so that the content for
vCPU is consistent with SDM.
Tracked-On: #6799
Signed-off-by: …
=> hv: initialize and save/restore IA32_TSC_AUX MSR for guest

misc/config_tools/schema/config.xsd
Set hv features L1D_VMENTRY_ENABLED, MCE_ON_PSC_DISABLED and PTM
default value to 'y' in schema.
Tracked-On: #6793
=> config-tools: enable hv features by default

hypervisor/arch/x86/rtcm.c, hypervisor/include/arch/x86/asm/cpuid.h
ACRN get messy default values for some CAT CBM MSRs,
these unexpected default value will result in TCC
Software SRAM initializes crash.
This patch resets above error default values before calling
CRL(cache reserve library) ABI initializaion function.
Tracked-On: #6780
=> [release_2.7]hv: reset CAT Capacity Bitmask(CBM) MSRs

doc/developer-guides/sw_design_guidelines.rst
=> doc: terminology cleanup in design guidelines

hypervisor/arch/x86/vtd.c, hypervisor/include/arch/x86/asm/vtd.h, hypervisor/include/lib/util.h, misc/hv_prebuild/static_checks.c
The CONFIG_MAX_IR_ENTRIES and CONFIG_MAX_PT_IRQ_ENTRIES are separate
configuration items, and they can be configured through configuration tool
When the number of PT irq entries are more than IR entries, then some
passthrough devices' irqs may failed to be protected by interrupt
remapping or automatically injected by post-interrupt mechanism.
And it waste memory if the CONFIG_MAX_IR_ENTRIES is larger.
This patch replace the CONFIG_MAX_IR_ENTRIES to MAX_IR_ENTRIES and
enforce it align to CONFIG_PT_IRQ_ENTRIES and round up to 2^n as the
IRTA_REG spec.This way can enforce all PT irqs works with IR or PI
mechanism.
Tracked-On: #6745
Reviewed-by: Wang, Yu1 <yu1.wang@intel.com>
=> hv: align the MAX_IR_ENTRIES to MAX_PT_IRQ_ENTRIES

misc/config_tools/launch_config/launch_item.py, misc/config_tools/library/scenario_cfg_lib.py, misc/config_tools/scenario_config/scenario_item.py
config_tool: add cpu affinity check
1. ensure cpu affinity in launch xml is subset of its scenario settings.
2. cpu_affinity is a must have parameter for acrn_dm, if the user did not provide cpu affinity in launch xml, load it from scenario settings.
[External_System_ID] ACRN-7453
Tracked-On: #6724
=> config_tool: update cpu affinity data load and check

hypervisor/common/efi_mmap.c
The HV will be built failed with below compiler message:
common/efi_mmap.c: In function ‘init_efi_mmap_entries’:
common/efi_mmap.c:41:11: error: unused variable ‘efi_memdesc_nr’
[-Werror=unused-variable]
uint32_t efi_memdesc_nr = uefi_info->memmap_size / uefi_info->memdesc_size;
^~~~~~~~~~~~~~
cc1: all warnings being treated as errors
The root cause is ASSERT() api is for DEBUG only so efi_memdesc_nr is not used
in RELEASE code.
The patch fix this issue by removing efi_memdesc_nr declaration;
Tracked-On: #6834
=> HV: fix build issue on RELEASE version

misc/config_tools/xforms/vm_configurations.h.xsl
GUEST_FLAG_SECURITY_VM only for pre-launch vm, should not be
programmed by device model, so we remove it in DM_OWNED_GUEST_FLAG_MASK.
Tracked-On: #6366
=> config_tools: remove GUEST_FLAG_SECURITY_VM in DM_OWNED_GUEST_FLAG_MASK

hypervisor/common/efi_mmap.c
The HV will be built failed with below compiler message:
common/efi_mmap.c: In function ‘init_efi_mmap_entries’:
common/efi_mmap.c:41:11: error: unused variable ‘efi_memdesc_nr’
[-Werror=unused-variable]
uint32_t efi_memdesc_nr = uefi_info->memmap_size / uefi_info->memdesc_size;
^~~~~~~~~~~~~~
cc1: all warnings being treated as errors
The root cause is ASSERT() api is for DEBUG only so efi_memdesc_nr is not used
in RELEASE code.
The patch fix this issue by removing efi_memdesc_nr declaration;
Tracked-On: #6834
=> [release 2.7]HV: fix build issue on RELEASE version

doc/user-guides/kernel-parameters.rst
=> doc: terminology cleanup in kernel params

hypervisor/Makefile, hypervisor/arch/x86/guest/assign.c, hypervisor/arch/x86/guest/optee.c, hypervisor/arch/x86/guest/vm.c, hypervisor/arch/x86/guest/vmcall.c, hypervisor/include/arch/x86/asm/guest/optee.h, hypervisor/include/arch/x86/asm/guest/vm.h, hypervisor/include/arch/x86/asm/vm_config.h, hypervisor/include/common/hypercall.h, hypervisor/include/public/acrn_common.h, hypervisor/include/public/acrn_hv_defs.h, misc/config_tools/library/common.py, misc/config_tools/schema/VMtypes.xsd, misc/config_tools/schema/config.xsd, misc/config_tools/xforms/vm_configurations.c.xsl
This PR contains patches that fixes the v4 of Deng Jie's x86_tee patch series.
One minor change from his original version: 
In hv: tee: Support the concept of companion VM, a default value of 65535 is added as companion_vmid for successful compilation.
=> hv: Add x86 TEE support

devicemodel/core/main.c, devicemodel/core/vmmapi.c, devicemodel/hw/platform/ioc.c, devicemodel/include/dm.h, hypervisor/arch/x86/configs/vm_config.c, hypervisor/arch/x86/guest/vm.c, hypervisor/arch/x86/guest/vmcall.c, hypervisor/common/hypercall.c, hypervisor/include/arch/x86/asm/guest/vm.h, hypervisor/include/arch/x86/asm/vm_config.h, hypervisor/include/public/acrn_common.h, misc/config_tools/xforms/lib.xsl, misc/config_tools/xforms/vm_configurations.c.xsl, misc/services/acrn_manager/acrn_mngr.h, misc/services/acrn_manager/acrn_vm_ops.c, misc/services/acrn_manager/acrnctl.c, misc/services/acrn_manager/acrnctl.h, misc/services/acrn_manager/acrnd.c
port UUID changes from mainline to release_v2.7
HV:
use GUEST_FLAG_STATIC_VM to identify static or dynamic VM
only clear name field for dynamic configured VM
DM:
use MAX_VM_NAME_LEN instead of MAX_VMNAME_LEN
MISC:
use MAX_VM_NAME_LEN instead of MAX_VMNAME_LEN
CONFIG_TOOL:
add GUEST_FLAG_STATIC_VM in guest_flags for all static configured VMs
=> Port UUID changes to release v2.7 branch

devicemodel/hw/platform/acpi/acpi_pm.c, hypervisor/common/hypercall.c
This patch is to eliminate kernel error msgs:
'ACPI Error: AE_NOT_FOUND, Evaluating _PSS'
This is caused by missing of _PSS table in guest ACPI. It would
happen when pstate is not injected to the guest.
Kernel ACPI pstate driver first probes
_PPC(performance capabilites) and _PCT(performance control)
in ACPI. If they exist, then it loads the _PSS(performance state).
If _PPC/_PCT are presented while _PSS is missing, it prints
the error msg.
In acrn-dm, _PPC/_PCT are hard-coded to all vCPUs, while _PSS
are constructed with the pCPUs' pstate data. This is base on
assumption that all VMs can have pstate.
Now the pstate is given to VM only when the VM is not sharing
any CPU(and no RTVM is setup in the scenario).
When the VM doesn't have pstate, the hypercall will return px_cnt=0,
and the _PSS …
=> Fix kernel ACPI error msg while launching rtvm

devicemodel/hw/platform/acpi/acpi_pm.c, hypervisor/common/hypercall.c
This patch is to eliminate kernel error msgs:
'ACPI Error: AE_NOT_FOUND, Evaluating _PSS'
This is caused by missing of _PSS table in guest ACPI. It would
happen when pstate is not injected to the guest.
Kernel ACPI pstate driver first probes
_PPC(performance capabilites) and _PCT(performance control)
in ACPI. If they exist, then it loads the _PSS(performance state).
If _PPC/_PCT are presented while _PSS is missing, it prints
the error msg.
In acrn-dm, _PPC/_PCT are hard-coded to all vCPUs, while _PSS
are constructed with the pCPUs' pstate data. This is base on
assumption that all VMs can have pstate.
Now the pstate is given to VM only when the VM is not sharing
any CPU(and no RTVM is setup in the scenario).
When the VM doesn't have pstate, the hypercall will return px_cnt=0,
and the _PSS …
=> [release_2.7] Fix kernel ACPI error msg while launching rtvm

devicemodel/hw/pci/virtio/virtio_console.c
this patch validates input of virtio_console_control_tx()
function to avoid potential progream crash with malicious
input from guest.
Tracked-On: #6581
=> [release_2.7] dm: validate input of virtio_console_control_tx()

doc/release_notes/release_notes_2.3.rst
Removed the VBS-K Framework Virtualization Overhead Analysis document on
master.
=> doc: fix 2.3 release notes broken link

CODEOWNERS
=> doc: update CODEOWNERS for documentation reviewers

doc/developer-guides/hld/rtc-virt-hld.rst
=> doc: terminology cleanup in RTC virt

hypervisor/arch/x86/boot/cpu_primary.S, hypervisor/arch/x86/mmu.c, hypervisor/bsp/ld/link_ram.ld.in, hypervisor/include/arch/x86/asm/boot/ld_sym.h
In previous commit df7ffab
the CONFIG_HV_RAM_SIZE was removed and the hv_ram_size was calculated in
link script by following formula:
ld_ram_size = _ld_ram_end - _ld_ram_start ;
but _ld_ram_start is a relative address in boot section whereas _ld_ram_end
is a absolute address in global, the mix operation cause hv_ram_size is
incorrect when HV binary is relocated.
The patch fix this issue by getting _ld_ram_start and _ld_ram_end respectively
and calculated at runtime.
Tracked-On: #6885
Signed-off-by: Victor Sun victor.sun@intel.com
Acked-by: Anthony Xu anthony.xu@intel.com
=> [release 2.7]HV: correct hv_ram_size when hv is relocated

misc/services/life_mngr/command_handler.c, misc/services/life_mngr/life_mngr_win.c
1. Refine platform shutdown when User VM fails to shutdown.
2. Add sync delay for WaaG lifecycle manager to avoid unnecessary sync resending.
=> Fix lifecycle manager bug

devicemodel/core/mevent.c
If a file descriptor being monitored by epoll_wait is closed
in another thread, the result is unspecified. So add all mevents
removed in other threads to delete list. And drain the list in
the dispatch mevent thread.
Tracked-On: #6877
=> dm: fix mevent timing issue to master branch

doc/tutorials/sgx_virtualization.rst
=> doc: terminology cleanup in sgx

devicemodel/core/mevent.c
If a file descriptor being monitored by epoll_wait is closed
in another thread, the result is unspecified. So add all mevents
removed in other threads to delete list. And drain the list in
the dispatch mevent thread.
Tracked-On: #6877
=> Dm: fix mevent timing issue to v2.7

devicemodel/hw/platform/acpi/acpi_parser.c
Add check for malloc result to madt pointer.
Tracked-On: #6769
=> dm: minor fix: add check for malloc result

misc/config_tools/launch_config/launch_cfg_gen.py, misc/config_tools/launch_config/launch_item.py, misc/config_tools/library/scenario_cfg_lib.py, misc/config_tools/scenario_config/scenario_item.py
1. load default cpu affinity config from scenario file by vm_name.
Tracked-On: #6724
(cherry picked from commit 0f7d0bb145c2077d65e614fd2f476c05f71103b6)
=> config_tool: load default cpu affinity config by vm_name (release_2.7)

misc/services/life_mngr/command_handler.c, misc/services/life_mngr/life_mngr_win.c
1. Refine platform shutdown when User VM fails to shutdown.
2. Add sync delay for WaaG lifecycle manager to avoid unnecessary sync resending.
=> [v2.7] Fix lifecycle manager bugs

doc/developer-guides/hld/hld-devicemodel.rst, doc/developer-guides/hld/hld-security.rst, doc/tutorials/rdt_configuration.rst, doc/user-guides/acrn-dm-parameters.rst
Since PR #6787 has landed, we need to remove the UUID parameter
"-U" of "acrn-dm" and replace UUID with VM name to identify a VM
in document.
=> doc: replace UUID with vm name to identify a vm

doc/tutorials/enable_ivshmem.rst
- Capitalize ACRN Configurator
=> doc: terminology cleanup in ivshmem

doc/tutorials/acrn_configuration_tool.rst
- Capitalize ACRN Configurator and Board Inspector
=> doc: terminology cleanup in config intro

devicemodel/hw/pci/virtio/virtio_console.c
this patch validates input of virtio_console_control_tx()
function to avoid potential progream crash with malicious
input from guest.
Tracked-On: #6851
=> dm: validate input of virtio_console_control_tx()

hypervisor/arch/x86/boot/cpu_primary.S, hypervisor/arch/x86/mmu.c, hypervisor/bsp/ld/link_ram.ld.in, hypervisor/include/arch/x86/asm/boot/ld_sym.h
In previous commit df7ffab4413034eaa221a104575d8f0bb705ba9f
the CONFIG_HV_RAM_SIZE was removed and the hv_ram_size was calculated in
link script by following formula:
ld_ram_size = _ld_ram_end - _ld_ram_start ;
but _ld_ram_start is a relative address in boot section whereas _ld_ram_end
is a absolute address in global, the mix operation cause hv_ram_size is
incorrect when HV binary is relocated.
The patch fix this issue by getting _ld_ram_start and _ld_ram_end respectively
and calculated at runtime.
Tracked-On: #6885
=> HV: correct hv_ram_size when hv is relocated

misc/config_tools/launch_config/launch_cfg_gen.py, misc/config_tools/launch_config/launch_item.py, misc/config_tools/library/scenario_cfg_lib.py, misc/config_tools/scenario_config/scenario_item.py
1. load default cpu affinity config from scenario file by vm_name.
Tracked-On: #6724
=> config_tool: load default cpu affinity config by vm_name

hypervisor/acpi_parser/dmar_parse.c, hypervisor/dm/vpci/pci_pt.c, hypervisor/dm/vpci/vpci.c, misc/config_tools/board_inspector/legacy/dmar.py, misc/config_tools/hv_config/board_defconfig.py, misc/config_tools/hv_config/hv_item.py, misc/config_tools/static_allocators/bdf.py, misc/config_tools/xforms/config_common.xsl
Get the GPU_SBDF by looking for device from board.xml and extract the
BDF from device address.
Tracked-On: #6855
=> config-tools: get GPU_SBDF automatically

CONTRIBUTING.rst, doc/developer-guides/contribute_guidelines.rst
Per the membership charter, the TSC members are maintained in the
CONTRIBUTING file in the project's GitHub repo.  Update our contributing
documentation to include this file into our technical docs too.
(This is an alternative to PR #6903)
=> doc: Add TSC and membership documentation

hypervisor/arch/x86/guest/vm.c
This patch fixes a minor warning introduced by commit 3c9c41b. No logic
changes.
Tracked-On: #6776
=> hv: Fix minor coding style warnings

hypervisor/arch/x86/guest/vlapic.c
Currently, in RTVM with multi vCPUs, lapic pass through is
configured, each vCPU works in x2apic mode. When one vCPU sends
IPI to all other vCPUs, writes ICR register with the value
0x00000000000c00f8, this ICR writting will trigger VM exit,
the hypervisor passes destination shorthand field 11B (All Excluding
Self) in the virtual ICR value into physical ICR value,
this IPI will be sent to each physical CPU core
in the platform according to 10.6.1 Interrupt Command Register (ICR),
Vol 3, SDM. This will cause one User VM with lapic pass through
configuration can send IPI with any vector (such as NMI or reboot
vector) to other VM, this interference may cause other VM hang.
In this patch, set "Destination Shorthand" field of the
ICR value as 00B (No Shorthand) since the emulation is done …
=> [v2.7]HV: update destination shorthand field in x2apic ICR emulation

misc/config_tools/xforms/vm_configurations.c.xsl
check VM number before filling with dynamic configured VM
Tracked-On: #6907
=> config_tools: check VM number before filling with dynamic configured VM

devicemodel/core/vmmapi.c
there is memory leakage in this function,
where memory pointed by 'cp'.
Tracked-On: #6919
=> [release_2.7] dm: fix memory leakage issue in acrn_parse_cpu_affinity

hypervisor/arch/x86/guest/vm.c, hypervisor/include/arch/x86/asm/guest/vm.h
This patch introduces stateful VM which represents a VM that has its own
internal state such as a file cache, and adds a check before system
shutdown to make sure that stateless VM does not block system shutdown.
Tracked-On: #6571
Signed-off-by: Wang Yu <yu1.wang@intel.com>
=> hv: Add stateful VM check before system shutdown

CODEOWNERS
misc: update CODEOWNERS for debug tools
=> misc: update CODEOWNERS for debug tools

hypervisor/arch/x86/guest/vlapic.c
Currently, in RTVM with multi vCPUs, lapic pass through is
configured, each vCPU works in x2apic mode. When one vCPU sends
IPI to all other vCPUs through writes ICR register with virtual
value 0x00000000000c00f8, this ICR writting will be intercepted,
the hypervisor passes destination shorthand field 11B (All Excluding
Self) in the virtual ICR value into physical ICR value during IPI
emulation, this IPI will be sent to each physical CPU core
in the platform according to 10.6.1 Interrupt Command Register (ICR),
Vol 3, SDM.
One vCPU in User VM with lapic pass through configuration can
send IPI with destination shorthand (10B or 11B) and any vector
(such as NMI or reboot vector) to other vCPUs, this IPI will sent
other VMs in the platform by hypervisor, this interference may
cause other VMs …
=> HV: update destination shorthand during x2apic ICR emulation

hypervisor/arch/x86/guest/vcpuid.c
When CPUID executes with EAX set to 1AH, the processor returns information about hybrid capabilities.
This information is percpu related, and should be obtained directly from the physical cpu.
Tracked-On: #6899
Signed-off-by: Wen <qian.wen@intel.com>
=> hv: fix core type error when launch RTVM use atom core

hypervisor/arch/x86/guest/vlapic.c
Currently, in RTVM with multi vCPUs, lapic pass through is
configured, each vCPU works in x2apic mode. When one vCPU sends
IPI to all other vCPUs through writes ICR register with virtual
value 0x00000000000c00f8, this ICR writting will be intercepted,
the hypervisor passes destination shorthand field 11B (All Excluding
Self) in the virtual ICR value into physical ICR value during IPI
emulation, this IPI will be sent to each physical CPU core
in the platform according to 10.6.1 Interrupt Command Register (ICR),
Vol 3, SDM.
One vCPU in User VM with lapic pass through configuration can
send IPI with destination shorthand (10B or 11B) and any vector
(such as NMI or reboot vector) to other vCPUs, this IPI will sent
other VMs in the platform by hypervisor, this interference may
cause other VMs …
=> [v2.5]HV: update destination shorthand during x2apic ICR emulation

devicemodel/hw/pci/ahci.c, devicemodel/hw/pci/virtio/virtio_block.c, devicemodel/hw/pci/virtio/virtio_i2c.c, devicemodel/hw/pci/virtio/virtio_net.c, devicemodel/hw/platform/rpmb/rpmb_sim.c, misc/debug_tools/acrn_crashlog/acrnprobe/probeutils.c
HMAC_*, MD5_* and SHA256_* are deprecated since openssl3.0, replace them with the corresponding equivalents.
Tracked-On: #6743
=> dm/tools: compatible with openssl3.0

hypervisor/arch/x86/guest/vcpuid.c
When CPUID executes with EAX set to 02H, the processor returns information about cache and TLB information.
This information is percpu related, and should be obtained directly from the physical cpu.
Tracked-On: #6931
=> hv: fix cpuid 0x2 mismatch when launch RTVM use atom core

Makefile
Currently, if board.xml and scenario.xml are specified,
the variable $(BOARD) and $(SCENARIO) are path, but the
parameters passed in to generate debian package should be
board and scenario name. So add a conversion function to
ensure that the function passed to the generated debian
package is board and scenario name.
Tracked-On: #6688
=> deb-pkg: Support specifying board.xml and scenario.xml

devicemodel/core/vmmapi.c
fix memory leakage issue in function 'acrn_parse_cpu_affinity()',
memory pointed by 'cp' is not released before function return.
Tracked-On: #6919
=> dm: fix memory leakage issue in acrn_parse_cpu_affinity

misc/config_tools/schema/VMtypes.xsd
update "bootargs" documentation to keep with release_2.7 branch
in VMtype.xsd.
=> config_tools:doc: sync with release_2.7 for XSD files

doc/release_notes/release_notes_2.7.rst
The acrn-dm ``--cpu_affinity`` parameter is now mandatory.
=> doc: update release notes with cpu_affinity notice

misc/config_tools/data/qemu/shared.xml
rename sdc.xml to shared.xml on qemu platform
=> config_tools: rename sdc.xml to shared.xml on qemu platform

hypervisor/arch/x86/init.c, hypervisor/debug/logmsg.c, hypervisor/include/debug/logmsg.h, hypervisor/release/logmsg.c
The CONFIG_LOG_DESTINATION parameter selects where the logging messages
send to，serial console or memory or npk device MMIO region.
Now we want to remove it and check the loglevel of each channel,close the
output when the loglevel is ZERO.
Tracked-On: #6934
=> hv: remove CONFIG_LOG_DESTINATION

hypervisor/arch/x86/cpu_caps.c, hypervisor/arch/x86/guest/vcpu.c
remove is_valid_xsave_combination api,
assume the hardware or QEMU can guarantee that support
XSAVE on CPU side and XSAVE_XRSTR on VMX side or not.
will add offline-tool in QEMU platform to avoid the user
use wrong XSAVE configurations.
remov check VMX_PROCBASED_CTLS2_XSVE_XRSTR based on the above reason.
for VMX_PROCBASED_CTLS2_PAUSE_LOOP, now it will panic
if run ACRN over QEMU, here remove it from essential check,
and it will print error information when set this bit
if there is no the hardware capability.
v1-v2:
remove is_valid_xsave_combination
Tracked-On: #6584
=> hv:remove 2 bits vmx capability check

doc/tutorials/enable_s5.rst
Currently, Service VM may fail to shut down due to some enabled
VFs. ACRN doesn't disable VFs automatically.
In this patch, add a note for user to disable VFs before Service
VM shuts down.
Tracked-On: #5921
=> doc: add note about SRIOV disable

misc/services/acrn_manager/README.rst, misc/services/acrn_manager/acrn_vm_ops.c, misc/services/acrn_manager/acrnctl.c, misc/services/acrn_manager/acrnctl.h
This patch set is to remove acrnctl suspend and resume command since
these two commands is not used by user any more.
Tracked-On: #5921
=> Remove acrnctl suspend and resume command

misc/hv_prebuild/vm_cfg_checks.c
Currently in sanitize_vm_config, all LAPIC-PT VM are treated as RTVM,
which can be relaxed: LAPIC PT VM does not have to be RTVM.
Change the logic in sanitize_vm_config to support this relaxation.
Tracked-On: #6968
=> hv_prebuild: Support LAPIC-PT only VM

doc/getting-started/getting-started.rst
The commands in the Getting Started Guide for copying files to and from
the USB stick will fail if the USB stick volume name has a space in it.
Fix this by quoting uses of $disk.
=> doc: fix $disk usage in GSG

doc/developer-guides/doc_guidelines.rst, doc/static/acrn-custom.css
Add some color styles we can use (via .. rst-class:: style directive) to
add color to rst tables.  Also introduce a centered class instead of
using the deprecated .. centered:: directive.  Update documentation
guidelines to describe these new styles (background colors).
=> doc: add CSS color styles

doc/getting-started/getting-started.rst, doc/tutorials/using_partition_mode_on_nuc.rst
1. Update launch script and replace the "apt-get" command with "apt" in GSG documentation.
2. Update the tag to v2.7 in partitioned documentation.
=> doc: update GSG and partitioned documentation

devicemodel/hw/pci/xhci.c
Flow Table 6-95 from xHCI spec, Ring Segment Size defines
the number of TRBs supported by the ring segment, valid
values for this field are 16 to 4096.
Tracked-On: #6981
=> ACRN: xHCI: Check the value of Ring Segment Size

devicemodel/hw/pci/passthrough.c
Otherwise it will fail to set the GPU opregion/stolen_memory for guest VM in
course of GPU passthrough and the display can't work.
Tracked-On: #6988
=> ACRN/DM: Add the ADL-P GPU device_id to support GPU passthrough

devicemodel/core/main.c, devicemodel/hw/pci/gvt.c, devicemodel/hw/pci/npk.c, devicemodel/hw/pci/virtio/virtio_coreu.c, devicemodel/hw/pci/virtio/virtio_hdcp.c, devicemodel/include/ioc.h, devicemodel/include/pm_vuart.h, devicemodel/include/sw_load.h
The following parameters have not used by new design:
1.  --vsbl <vsbl_file_path>
2.  --part_info <part_info_name>
3.  -G, --gvtargs <GVT_args>
4.  -s <slot>,pci-gvt
5.  -Y, --mptgen
6.  -s <slot>,virtio-hdcp
7.  -s <slot>,npk
8.  -s <slot>,virtio-coreu
9.  -i, --ioc_node <ioc_mediator_parameters>
10. --pm_by_vuart [pty|tty],<node_path>
11. --pm_notify_channel <channel>
This patch remove these parameters from usage and comment in code to
explain they are all obsoleted now.
Tracked-On: #6690 
=> dm: remove some dynamic parameters from acrn-dm usage

misc/services/acrn_manager/README.rst, misc/services/acrn_manager/acrn_vm_ops.c
User should make sure acrnd service has been started before running acrnctl.
This patch set updates log message and document about this.
Tracked-On: projectacrn#6991
=> Need to start acrnd before running acrnctl

misc/services/acrn_manager/acrnd.service
Currently, if user starts acrnd service, acrnd service will fail to
find the folder "/sys/kernel/gvt" in Service VM, fail to start.
Root cause is GVT-g is not supported in current ACRN, the folder
"/sys/kernel/gvt" will not be created in Service VM.
This patch updates acrnd service to remove this condition check.
v1-->v2:
Weston service is optional for ACRN, acrnd should not depend
on it, so remove weston service dependency in acrnd service.
Tracked-On: #6994
=> Misc: acrnd: fix acrnd start failure

hypervisor/arch/x86/guest/instr_emul.c, hypervisor/arch/x86/guest/ve820.c
remove the dead code since the variable is never used.
Tracked-On: #6776
=> hv: fix clang analyzer deadcode

misc/config_tools/board_inspector/pcieparser/__init__.py
According to PCIe specification (since 2.0), absence of any extended
capabilities is required to be indicated by an extended capability header
with a capability ID of FFFFh and a next capability offset of 000h. Thus,
the board inspector today accesses the first extended capability header at
100h in the configuration space of a PCIe function unconditionally.
However, in practice we have seen real PCI functions which has a PCIe
capability but no extended capability header. This will cause the board
inspector to crash due to invalid configuration space accesses.
To fix that, this patch adds a check to the size of the configuration space
before walking the extended capabilities of a PCIe function.
Tracked-On: #6411
Acked-by: Anthony Xu …
=> board_inspector/pcieparser: check config space size of PCIe devices

doc/tutorials/enable_ivshmem.rst
Remove the TARGET_DIR parameter from the "Enable Inter-VM Communication
Based on Ivshmem" tutorial as this is now an obsolete parameter that
will print out a warning.
=> doc: remove obsolete TARGET_DIR Makefile parameter from tutorial

hypervisor/arch/x86/guest/vcpu.c, hypervisor/arch/x86/guest/vmexit.c, hypervisor/include/arch/x86/asm/cpu.h
The coding guideline rule C-FN-16 requires that 'Mixed-use of
C code and assembly code in a single function shall not be allowed',
this patch wraps inline assembly to CPU_XMM_READ/CPU_XMM_WRITE.
Tracked-On: #6776
=> hv: fix violations of coding guideline C-FN-16

.deb.conf, misc/packaging/gen_acrn_deb.py
When cloning the ACRN source code to a folder, which is not named "acrn-hypervisor",
the debian package created by the "make" call does not contain all needed files.
Because the file ".deb.conf" contains hardcoded folder names which contain the
folder name "acrn-hypervisor".
Tracked-On: #7022
=> [for v2.7]deb-pkg: Delete the folder name of acrn-hypervisor in the configuration file

misc/packaging/acrn-hypervisor.preinst
The check logic of CPU num is wrong and needs to be deleted.
Hyper-threading check should be checked when getting board xml.
Tracked-On: #6688
=> deb-pkg: Delete the Hyper-threading check in preinst

doc/developer-guides/hld/hld-devicemodel.rst, doc/developer-guides/hld/hld-overview.rst, doc/developer-guides/hld/hostbridge-virt-hld.rst, doc/developer-guides/hld/virtio-blk.rst, doc/reference/config-options-launch.rst, doc/tutorials/enable_ivshmem.rst, doc/tutorials/gpu-passthru.rst, doc/tutorials/launch_uos.sh, doc/user-guides/acrn-dm-parameters.rst
The following parameters have not used by new design:
1.  --vsbl <vsbl_file_path>
2.  --part_info <part_info_name>
3.  -G, --gvtargs <GVT_args>
4.  -s <slot>,pci-gvt
5.  -Y, --mptgen
6.  -s <slot>,virtio-hdcp
7.  -s <slot>,npk
8.  -s <slot>,virtio-coreu
9.  -i, --ioc_node <ioc_mediator_parameters>
10. --pm_by_vuart [pty|tty],<node_path>
11. --pm_notify_channel <channel>
This patch remove these parameters from doc.
=> doc: remove some dynamic parameters from acrn-dm usage

misc/config_tools/board_inspector/board_inspector.py, misc/config_tools/board_inspector/extractors/40-acpi-tables.py, misc/config_tools/board_inspector/extractors/50-acpi-namespace.py, misc/config_tools/xforms/config.h.xsl, misc/config_tools/xforms/config.mk.xsl, misc/config_tools/xforms/config_common.xsl
1. Extract common ioapic information such as ioapic id, address, gsi base and gsi num to board.xml
2. Generate MAX_IOAPIC_NUM and MAX_IOAPIC_LINE based on board.xml based on the information from part 1.
=> Config-tools: Generate ioapic number and line maximum automatically

misc/config_tools/static_allocators/lib/__init__.py
If the user installed the lib python package in the host machine,
it will fail to build acrn hypervisor since the same package named lib is
also used in acrn config tool(static_allocators/lib).
So we add the __init__.py file under the static_allocators/lib directory
to fix the error.
Tracked-On: #7001
=> config_tools: add __init__.py under static_allocators/lib directory

misc/config_tools/data/generic_board/hybrid_launch_2user_vm.xml, misc/config_tools/data/generic_board/shared_launch_6user_vm.xml, misc/config_tools/data/nuc11tnbi5/hybrid_launch_2user_vm.xml, misc/config_tools/data/nuc11tnbi5/shared_launch_6user_vm.xml, misc/config_tools/data/whl-ipc-i5/hybrid_rt_launch_1user_vm_waag.xml, misc/config_tools/data/whl-ipc-i5/sdc_launch_1user_vm_laag.xml, misc/config_tools/data/whl-ipc-i5/sdc_launch_1user_vm_zephyr.xml, misc/config_tools/data/whl-ipc-i5/shared_launch_1user_vm_hardrt.xml, misc/config_tools/data/whl-ipc-i5/shared_launch_1user_vm_vxworks.xml, misc/config_tools/data/whl-ipc-i5/shared_launch_1user_vm_waag.xml, misc/config_tools/data/whl-ipc-i5/shared_launch_2user_vm.xml, misc/config_tools/data/whl-ipc-i5/shared_launch_6user_vm.xml, misc/config_tools/launch_config/com.py, misc/config_tools/launch_config/launch_cfg_gen.py, misc/config_tools/launch_config/launch_item.py, misc/config_tools/launch_config/pt.py, misc/config_tools/library/launch_cfg_lib.py
Since PR #7002 has removed some dynamic parameters from acrn-dm usage, this patch also removes the following parameters in launch script generation logic.
1. --vsbl <vsbl_file_path>
2. -s <slot>,npk
3. -i, --ioc_node <ioc_mediator_parameters>
4. -A, --acpi
5. virtio-ipu
6. virtio-audio
7. --pm_notify_channel
8. --pm_by_vuart
=> config_tools: remove some dynamic parameters of acrn-dm

misc/config_tools/data/cfl-k700-i7/hybrid.xml, misc/config_tools/data/cfl-k700-i7/hybrid_rt.xml, misc/config_tools/data/cfl-k700-i7/shared.xml, misc/config_tools/data/generic_board/hybrid.xml, misc/config_tools/data/generic_board/hybrid_rt.xml, misc/config_tools/data/generic_board/shared.xml, misc/config_tools/data/nuc11tnbi5/hybrid.xml, misc/config_tools/data/nuc11tnbi5/shared.xml, misc/config_tools/data/qemu/shared.xml, misc/config_tools/data/whl-ipc-i5/hybrid.xml, misc/config_tools/data/whl-ipc-i5/hybrid_rt.xml, misc/config_tools/data/whl-ipc-i5/sdc.xml, misc/config_tools/data/whl-ipc-i5/shared.xml, misc/config_tools/library/scenario_cfg_lib.py, misc/config_tools/scenario_config/scenario_cfg_gen.py, misc/config_tools/scenario_config/scenario_item.py, misc/config_tools/schema/VMtypes.xsd, misc/config_tools/schema/config.xsd, misc/config_tools/xforms/misc_cfg.h.xsl
1. remove the board_private tag in the schema and all existing scenario XML files,
and remove the related value check about board_private.rootfs and bootargs.
2. merge board_private.rootfs and board_private.bootargs to os_config.bootargs.
and no change to the related contents of the .c/.h files except the order of define SERVICE_VM_ROOTFS.
3. update the schema to make os_config.bootargs configurable for service VM in UI.
=> config_tools: merge board_private.rootfs/bootargs to os_config.bootargs

hypervisor/arch/x86/guest/vmexit.c, hypervisor/debug/shell.c, hypervisor/include/arch/x86/asm/guest/vcpu.h, hypervisor/include/arch/x86/asm/guest/vmexit.h, hypervisor/include/arch/x86/asm/per_cpu.h
change vmexit data array size according to vmexit dispatch_table size.
also add a size check to avoid array overflow.
Tracked-On: #7043
=> hv: improve vmexit array size to avoid overflow

devicemodel/core/main.c
Dynamic parameter '-A' means to generate acpi table in dm.
Few scenario use dm without '-A'. So remove it, and always
generate apci table automatically.
=> dm: remove dynamic param '-A'

devicemodel/hw/pci/virtio/virtio_console.c, devicemodel/hw/pci/virtio/virtio_gpio.c, devicemodel/hw/pci/virtio/virtio_rnd.c, devicemodel/include/virtio.h
The current code would cause infinite calls to vq_getchain()
because that:
- error check of vq_getchain() return value is missing.
- virtqueue misunderstand that there are avaliable descripters
even though the idx of avail ring is invalid.
This patch fixes it by checking validity of the return of
vq_getchain() and jump out of the loop for invalid return value.
This patch alse add validity check in judgment of avaliable
descriptor, and check if the diff between idx of avail ring and
the last idx is greater than size of this queue.
Tracked-On: #7038
Signed-off-by: Wen Qian <qian.wen@intel.com>
Signed-off-by: Li Fei <fei1.li@intel.com>
Acked-by: Wang Yu1 <yu1.wang@intel.com>
=> dm: fix the bug that infinite calls to vq_getchain()

doc/developer-guides/hld/hld-devicemodel.rst, doc/developer-guides/hld/hostbridge-virt-hld.rst, doc/developer-guides/hld/hv-dev-passthrough.rst, doc/getting-started/getting-started.rst, doc/tutorials/acrn_on_qemu.rst, doc/tutorials/enable_ivshmem.rst, doc/tutorials/gpu-passthru.rst, doc/tutorials/launch_uos.sh, doc/tutorials/using_windows_as_user_vm.rst, doc/user-guides/acrn-dm-parameters.rst
Update document to remove 'acrn-dm' dynamic param '-A'.
=> doc: remove dm dynamic param '-A'

devicemodel/core/main.c, doc/developer-guides/hld/hld-devicemodel.rst, doc/user-guides/acrn-dm-parameters.rst
Rename '--virtio_msix' to '--virtio_msi' for this param
means 'force virtio to use singel-vector MSI'.
`-W` is the short version of `--virtio_msi`. But it's
confusing that `-W` and `--virtio_msi` are irrelevant literally.
So remove the short version `W` to prompt user friendliness.
=> dm: Dm rm dynamic param '-W'

hypervisor/scripts/genconf.sh, misc/config_tools/scenario_config/validator.py
Today the XML validation logic is embedded in scenario_cfg_gen.py which is
highly entangled with the Python-internal representation of
configurations. Such representation is used by the current configurator,
but will soon be obsolete when the new configurator is introduced.
In order to avoid unnecessary work on this internal representation when we
refine the schema of scenario XML files, this patch separates the
validation logic into a new script which can either be used from the
command line or imported in other Python-based applications. At build time
this script will be used instead to validate the XML files given by users.
This change makes it easier to refine the current configuration items for
better developer experience.
Migration of existing checks in scenario_cfg_gen.py to XML …
=> config_tools: add a script that focuses on XML validation

doc/developer-guides/hld/hld-devicemodel.rst, doc/reference/config-options-launch.rst, doc/tutorials/cpu_sharing.rst, doc/user-guides/acrn-dm-parameters.rst
1. Cpu affinty was set by pCPU ID which can't be obtained explictly by user. Use lapic ID instead which can be easily read from `/proc/cpuinfo` as `apicid`. (please refer to PR #7040)
2. Since PR #7035 has removed "pm_notify_channel" and "pm_by_vuart" in the launch script generation logic, this patch also removes the related elements("poweroff_channel" and "allow_trigger_s5") in the documentation.
=> doc: update some dynamic parameters from acrn-dm usage 

README.rst, doc/introduction/index.rst
Include the project's GitHub README that contains community support and
resource information into the ACRN Introduction documentation.  Also fix
the ACRN misspelling.
=> doc: add community support and resources to introduction

misc/config_tools/board_inspector/extractors/60-pci.py, misc/config_tools/static_allocators/intx.py
According to ACPI spec, an entry in ACPI PRT (PCI Routing Table) can                                                                                                                                               specify an interrupt line either by an integer or by a pair of a device                                                                                                                                            object and an index. In the later case, the interrupt line is specified by                                                                                                                                         the index'th entry in the current resource list (as reported by the _CRS …
=> Process both forms of ACPI PRT entries

devicemodel/core/main.c, devicemodel/hw/pci/core.c, devicemodel/hw/pci/virtio/virtio_net.c
1. Remove device name requirement for “tap” and "vmnet", change the
parameter format like:
"-s 4,virtio-net,tap/vmnet=dev_name".
2. change mac_seed to virtio-net sub-parameter
As a parameter of acrn-dm,the mac_seed is only used for virtio-net.
So this patch change it to the sub-parameter of virtio-net.
The final format is:
-s 4,virtio-net,tap/vmnet=dev_name,mac_seed=XXXX
Acked-by: Yu1 Wang <yu1.wang@intel.com>
=> dm:change the parameter of virtio-net

misc/config_tools/data/qemu/qemu.xml
qemu build fail with the old board xml.
this should be re-generated by the latest board inspector tool
which include the changes in PR#7067
Tracked-On: #7058
=> config-tools: update qemu board xml

misc/config_tools/static_allocators/gpa.py
Not all pci hostbridge has a device on it. Remove the logic which assumes there is at least one device.
Tracked-On: #7077
=> config-tool: find pci hole based on all pci hostbridge

misc/config_tools/board_inspector/extractors/10-processors.py, misc/config_tools/library/board_cfg_lib.py, misc/config_tools/xforms/board_info.h.xsl, misc/config_tools/xforms/config.h.xsl, misc/config_tools/xforms/config.mk.xsl, misc/config_tools/xforms/config_common.xsl
This PR contains fixes to the following issues:
* The board inspector adds another level of `die` node even though the hardware reports die topology in CPUID.
* Build fails when the board contains any unprogrammed BAR.
* Values of `IOAPIC_MAX_NUM` and `IOAPIC_MAX_LINES` in scenario XML do not override auto-calculated values.
=> Multiple fixes to the board inspector and build system

misc/config_tools/launch_config/com.py
Fix the format of passthrough gpu bdf of post-launched VM.
Tracked-On: #7084
=> config-tool: append passthrough gpu bdf in hexadecimal format

devicemodel/hw/pci/virtio/virtio_net.c
The current mac detection logic only check whether there are parameters
after tap opt. Don't care whether the parameter is MAC or not, then
mac_provided will be set to 1, which will disable the mac_seed setting
when using sub parameters
This patch will check opt and fix the above issue.
=> dm: refine the mac check logic for virtio-net

hypervisor/scripts/makefile/config.mk
Fix typo in hypervisor/scripts/makefile/config.mk file.
Tracked-On: #5647
=> Makefile: fix typo in config.mk

hypervisor/arch/x86/guest/vmcall.c, hypervisor/common/hypercall.c, hypervisor/include/arch/x86/asm/vm_config.h, hypervisor/include/common/hypercall.h, hypervisor/include/public/acrn_hv_defs.h
HC_GET_PLATFORM_INFO hypercall is not supported anymore,
hence to remove related function and data structure definition.
=> hv: remove HC_GET_PLATFORM_INFO hypercall support

misc/config_tools/board_inspector/extractors/10-processors.py
In 10-processors.py, level_types is an unordered dictionary from level type
encodings to human-readable terms, not a list. It is thus illegal to access the
highest level using the `[-1]` notation.
This patch fixes this by calculating the highest level in level_types and use
that level as the index instead.
Fixes: b5b22bf98 ("board_inspector: avoid hard-coded topo level names")
=> config_tools: fix illegal access to the level_types dictionary

doc/conf.py
A shortcut to find the :ref:`labelname` value to link to an HTML page is
to view the source .rst file for that page.  This patch tweaks the
conf.py to do just that.
=> doc: show source file link on html pages

doc/tutorials/acrn_on_qemu.rst
For platforms which have apicv post-interrupt capability;
ACRN would use posted-interrupt to notify another vCPU which in non-root mode;
or sync interrupt for itself when it in root-mode.However,QEMU could not handle this properly.
So, remove the post-interrupt capability in qemu cmdline.
Reviewed-By: Li, Fei <fei1.Li@intel.com>
=> Doc: qemu cmdline update for acrn on qemu

doc/faq.rst, doc/index.rst
Per issue #5265, removing the FAQ from the table of contents until we create more content
=> doc: Remove FAQ from TOC

misc/config_tools/board_inspector/board_inspector.py, misc/config_tools/board_inspector/cpuparser/__init__.py
Bring all the cores up in the beginning of the board_inspector.py
It is expected to run board_inspector in clean and native environment.
To resolve the issue that user may run other jobs which puts cores
offline, bringing up all cores online so tool can run cpuid to extract
all available cores information.
Tracked-On: #7119
=> config-tools: bring all cores online

misc/config_tools/board_inspector/acpiparser/aml/context.py, misc/config_tools/board_inspector/acpiparser/aml/datatypes.py, misc/config_tools/board_inspector/acpiparser/aml/interpreter.py, misc/config_tools/board_inspector/acpiparser/aml/parser.py, misc/config_tools/board_inspector/acpiparser/tpm2.py, misc/config_tools/board_inspector/board_inspector.py, misc/config_tools/board_inspector/cpuparser/platformbase.py, misc/config_tools/board_inspector/extractors/20-cache.py, misc/config_tools/board_inspector/extractors/50-acpi-namespace.py, misc/config_tools/board_inspector/extractors/60-pci.py, misc/config_tools/board_inspector/extractors/helpers.py, misc/config_tools/board_inspector/legacy/acpi.py, misc/config_tools/board_inspector/legacy/board_parser.py, misc/config_tools/board_inspector/legacy/clos.py, misc/config_tools/board_inspector/smbiosparser/smbios.py
category based on different log levels:
1) If the board inspector show CRITICAL error messages, it means that the
board inspector tool exit instantly and generate no file.
2) If the board inspector show ERROR messages, it means that the board
inspector will generate the board XML file successfully, but several conditions
may result in ACRN build or boot failure cannot continue execution due to the error.
3) If the board inspector show WARNING messages, this means that the board inspector
generate the board XML file successfully, but this board XML file is lack of
some feature which could still boot ACRN but loss some features.
4) If the board inspector show INFO messages, this means that board inspector
printed out some normal information.
5) If the board inspector show DEBUG messages, …
=> config_tools: category based on different log levels

devicemodel/core/main.c, misc/config_tools/launch_config/com.py
Enable `lapic_pt` automatically for rtvm for better performance.
Reserve `--lapic_pt` for future use. If VM is not in realtime mode,
`--lapic_pt` will cause a warning.
=> dm: rtvm enable lapic_pt automatically

devicemodel/Makefile, devicemodel/core/cmd_monitor/cmd_monitor.c, devicemodel/core/cmd_monitor/command.c, devicemodel/core/cmd_monitor/command.h, devicemodel/core/cmd_monitor/command_handler.c, devicemodel/core/cmd_monitor/command_handler.h, devicemodel/core/cmd_monitor/socket.c, devicemodel/core/cmd_monitor/socket.h, devicemodel/core/main.c, devicemodel/include/cmd_monitor.h, doc/getting-started/getting-started.rst, misc/packaging/gen_acrn_deb.py
This command monitor in DM is to handle commands from external
systems (such libvirt, kata container) directly.
In current design, external system should send DM through acrnctl,
acrnctl will be replaced by libvirt in ACRN soon.
In this patch set, command monitor is introduced to make external
system can interact with DM directly through unix domain socket;
older command handling in DM is also refined to just keep two
commands (force shutdown, blkrescan), make adding new commands more
easy.
=> Add command monitor in DM

hypervisor/Makefile, paths.make
The 'serial.conf' file need to be put in /etc/, but it is currently being
installed in $(libdir)/acrn/. We therefore ask the user to manually copy that
file over to the /etc/ folder. This patch fixes that by installing
'serial.conf' directly there.
Tracked-On: #7107
=> Makefile: put 'serial.conf' in final location

hypervisor/arch/x86/guest/pm.c, hypervisor/arch/x86/guest/vm.c, hypervisor/arch/x86/vtd.c, hypervisor/boot/multiboot/multiboot.c, hypervisor/common/hypercall.c, hypervisor/dm/vpci/pci_pt.c, hypervisor/dm/vpci/vdev.c, hypervisor/dm/vpci/vmcs9900.c, hypervisor/dm/vpci/vmsix.c, hypervisor/hw/pci.c
The coding guideline rule C-ST-04 requires that
a 'if' statement followed by one or more 'else if'
statement shall be terminated by an 'else' statement
which contains either appropriate action or a comment.
Tracked-On: #6776
=> hv:fix violations of coding guideline C-ST-04

devicemodel/hw/pci/core.c, devicemodel/hw/pci/irq.c
When the virtio-XXX pci devices fall back to legacy PCI intx,
the pci_irq_assert is called to inject the interrupt and then
the pci_irq_deassert is used to mark the completion of PCI interrupt.
Currently the HV vIOAPIC uses the pin_state for the interrupt injection
of legacy PCI intx. In such case it will fail to inject the PCI legacy
intx and the guest system fails to be booted when adding the boot option
of "pci=nomsi".
PCI legacy INTx usually use active low level trigger mode as it is Open-Drain
state and allows multitple interrupt signals to share a single line.
https://wiki.osdev.org/PCI_Local_Bus_Signals
In such case DM needs to set the correct state for the PCI device so that the
HV vIOAPIC can help to inject the PCI legacy intx.
BTW: When the MSI/MSIX is used for PCI device, it …
=> ACRN:DM: Set the desired state to inject PCI legacy intx

doc/developer-guides/hld/hld-devicemodel.rst, doc/developer-guides/hld/mmio-dev-passthrough.rst, doc/user-guides/acrn-dm-parameters.rst
Now the acpidev_pt module only use the hid to check the device,it can't
work well if there are more then one instance.
So this patch add UID to identify same type device to fix these issue.
=> doc:add UID parameter for acpidev_pt

misc/config_tools/data/cfl-k700-i7/hybrid.xml, misc/config_tools/data/cfl-k700-i7/hybrid_rt.xml, misc/config_tools/data/cfl-k700-i7/shared.xml, misc/config_tools/data/generic_board/hybrid.xml, misc/config_tools/data/generic_board/shared.xml, misc/config_tools/data/nuc11tnbi5/hybrid.xml, misc/config_tools/data/nuc11tnbi5/shared.xml, misc/config_tools/data/qemu/shared.xml, misc/config_tools/data/tgl-vecow-spc-7100-Corei7/hybrid.xml, misc/config_tools/data/tgl-vecow-spc-7100-Corei7/shared.xml, misc/config_tools/data/whl-ipc-i5/hybrid.xml, misc/config_tools/data/whl-ipc-i5/hybrid_rt.xml, misc/config_tools/data/whl-ipc-i5/sdc.xml, misc/config_tools/data/whl-ipc-i5/shared.xml, misc/config_tools/xforms/misc_cfg.h.xsl, misc/config_tools/xforms/vm_configurations.h.xsl
Remove the logic to parse SERIAL_CONSOLE and append to bootargs. Specify the console in bootargs directly.
Tracked-On: #7127
=> config-tools: remove SERIAL_CONSOLE extracion for bootargs of SOS

hypervisor/scripts/makefile/config.mk
Remove the fact that a default BOARD and SCENARIO are used in case there was
none provided by the user, nor any available from a previous build. Up until
now, if that was the case, a build was triggered using a default set of BOARD
and SCENARIO values. The 'make' command will now error out asking the user to
specify those parameters.
Tracked-On: #7112
=> Makefile: remove default BOARD and SCENARIO values

misc/config_tools/board_inspector/board_inspector.py
Fix the issue that board inspector exit after showing warning message.
=> config_tools: fix the board inspector exit issue

doc/_templates/layout.html
The master branch is considered unstable and under development. We need
to remind developers of this and refer them to the available stable release
documentation.
=> doc: add header notice on latest documentation from master

doc/release_notes/release_notes_2.5.rst
when an XML option was removed, it will break documentation links to
that option information.  We'll remove the link in the old release notes
to fix this problem.
=> doc: remove build problem in release notes

misc/config_tools/acpi_gen/asl_gen.py
Update the XPATH of apic_id to tolerate the variance of reported
intermediate levels.
Tracked-On: #7159
=> config_tools: fix the issue that fail to get apic_id node

doc/release_notes/release_notes_2.7.rst, doc/tutorials/nvmx_virtualization.rst
PR #7167 removed configuration options that were referenced by
documentation.  Remove those references.
=> doc: fix doc build error for removed options

hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/guest/nested.c, hypervisor/arch/x86/guest/vept.c, hypervisor/include/arch/x86/asm/guest/vept.h
Now the vept module uses a mixture of nept and vept, it's better to
refine it.
So this patch rename nept to vept and simplify the interface of vept
init module.
=> hv: refine the vept module

misc/config_tools/data/cfl-k700-i7/hybrid.xml, misc/config_tools/data/cfl-k700-i7/hybrid_rt.xml, misc/config_tools/data/cfl-k700-i7/partitioned.xml, misc/config_tools/data/cfl-k700-i7/shared.xml, misc/config_tools/data/generic_board/hybrid.xml, misc/config_tools/data/generic_board/hybrid_rt.xml, misc/config_tools/data/generic_board/partitioned.xml, misc/config_tools/data/generic_board/shared.xml, misc/config_tools/data/nuc11tnbi5/hybrid.xml, misc/config_tools/data/nuc11tnbi5/partitioned.xml, misc/config_tools/data/nuc11tnbi5/shared.xml, misc/config_tools/data/qemu/shared.xml, misc/config_tools/data/tgl-vecow-spc-7100-Corei7/hybrid.xml, misc/config_tools/data/tgl-vecow-spc-7100-Corei7/partitioned.xml, misc/config_tools/data/tgl-vecow-spc-7100-Corei7/shared.xml, misc/config_tools/data/whl-ipc-i5/hybrid.xml, misc/config_tools/data/whl-ipc-i5/hybrid_rt.xml, misc/config_tools/data/whl-ipc-i5/partitioned.xml, misc/config_tools/data/whl-ipc-i5/sdc.xml, misc/config_tools/data/whl-ipc-i5/shared.xml, misc/config_tools/schema/VMtypes.xsd, misc/config_tools/schema/config.xsd, misc/config_tools/service_vm_config/serial_config.py, misc/config_tools/static_allocators/bdf.py, misc/config_tools/static_allocators/intx.py, misc/config_tools/xforms/vm_configurations.c.xsl
We have redesign the vuart and the UI for user, so the config tool
should change the schema and xform for the new xml, then change the
static_allocators to alloc irq and io_port for new connection.
This patch add a new vuart connection type and change the xforms and xmls
to adapter the new design.
This patch dependent on the change of one source patch.
=> misc: refine vuart connection

doc/tutorials/setup_openstack_libvirt.rst
Acrn driver in libvirt needs to handle JSON command or
JSON message to interact with command monitor in ACRN DM.
In libvirt, JSON APIs implementation depends on yajl lib.
So yajl should be configured for libvirt.
Tracked-On: #5921
=> doc: configure yajl lib for acrn driver in libvirt

doc/getting-started/getting-started.rst
The v2.7 version does not use the libcjson-dev
=> doc: revert gsg libcjson dependency

doc/tutorials/docbuild.rst
Last year, GitHub announced the deprecation of the unsecured Git
protocol due to security reasons. This change will be made permanent on
March 15, 2022. Update the doc build tutorial to use https: instead of
git: protocol for cloning repos.
And while in here, clarify some of the doc build instructions.
=> doc: update doc-build tutorial to remove git: protocol use

devicemodel/core/vmmapi.c
This reverts commit 811992ee2beb4ba0acf04f72aff675a82d617e3d.
There could be some conflict with current configure tool. will fix it
later.
=> Revert "dm: set PMU_PT flag for CPU core partition VM"

LICENSE
Update the top-level LICENSE file that provides the full text of the BSD-3
Clause license that this project uses. Two updates were made to it:
* Update the year to include 2022
* Removed an extra line: "All rights reserved"
The text matches exactly the reference found here: https://opensource.org/licenses/BSD-3-Clause
=> Update LICENSE information file

misc/config_tools/service_vm_config/serial_config.py
The Service VM needs a 'serial.conf' file to recognize and use
non-standard vUART with the 'setserial' package.
The logic of create serial.conf should update after we move vUART
connection to global and use endpoint to replace the target VM id.
This patch select the new vUART connection and check whether one of the
endpoint is Service VM, if yes, then check the io_port and record it
when the vUART is non-standard.
All these non-standard vUART will be written to the serial.conf.
Reviewed-by: Junjie Mao junjie.mao@intel.com
=> misc: refine the non-stand vUART config

devicemodel/core/main.c
DM dynamic param '-A' has been removed.
For compability, add a warning for `-A` instead of terminate the launch
process.
Tracked-On:#6690
=> dm: add warning for `-A` param

devicemodel/hw/pci/virtio/virtio_net.c, misc/config_tools/launch_config/launch_script_template.sh
Now, the DM assumes the device name entered by user is dependent on
the type.
For example, the device of tap type is named tap_TAAG, this patch
remove the above assumption.
User could set any name, no matter the code of DM or actually created,
it is represented by user input.
Commit 1. DM remove the assume logic of device name.
Commit 2. Config tool also change the generation logic of  launch script .
Commit 3. Fix the issue that got wrong device name after specifying mac address
=> Remove the assume of virtio-net device name

doc/develop.rst, doc/release_notes/release_notes_1.3.rst, doc/release_notes/release_notes_2.0.rst, doc/release_notes/release_notes_2.2.rst, doc/release_notes/release_notes_2.3.rst, doc/release_notes/release_notes_2.5.rst, doc/tutorials/running_deb_as_serv_vm.rst, doc/tutorials/running_deb_as_user_vm.rst, doc/tutorials/running_ubun_as_user_vm.rst, doc/tutorials/using_yp.rst
- Remove Ubuntu and Debian tutorials, as GSG is sufficient
- Remove Yocto tutorial, as it is just a reference to a repo that supports ACRN v2.4
=> doc: Remove outdated tutorials

devicemodel/hw/pci/virtio/virtio_i2c.c
i2c bus counter 'acpi_i2c_adapter_num' shall be updated
when virtio-i2c device is de-initialized, else in user VM
reboot case, this global counter will not be reset and
keep the value last user VM boot, which is not expected
and cause iasl(building ACPI data) program crash finally
because the i2c device name space overflow.
Tracked-On: #7028
=> dm: update virtio-i2c bus counter when device is deinit

misc/config_tools/board_inspector/board_inspector.py, misc/config_tools/board_inspector/extractors/70-device-classes.py, misc/config_tools/board_inspector/extractors/80-lookup.py, misc/config_tools/schema/VMtypes.xsd, misc/config_tools/schema/config.xsd
This patch adds data into board XML that enables the extraction of available PCI devices or serial ports using XPATH which are encoded in the XML schema as well. This helps the next-generation configurator to automatically pick to options from board XMLs.
=> Extract available PCI devices and serials from board XML

devicemodel/core/vmmapi.c, hypervisor/arch/x86/guest/vcat.c, hypervisor/arch/x86/guest/vmsr.c, hypervisor/include/arch/x86/asm/guest/vcpu.h
Revert "Revert "dm: set PMU_PT flag for CPU ...""
This reverts commit 6750d5a2770ad183bf748e718e57934be03a5705.
the bug is root caused and fixed for host/guest MSR store/load,
so recovery the original patch.
Tracked-On: #6966
=> fix a bug about host/guest msr store/load and revert PMU_PT flag in ACRN-DM

misc/config_tools/static_allocators/guest_flags.py
For post-launched RTVM, the acrn-dm can own PMU_PASSTHROUGH flag; for
pre-launched RTVM, need set it in configuration file by default.
Tracked-On: #6966
=> misc: set PMU_PT flag for pre-launched RTVM

hypervisor/arch/x86/mmu.c
Now HI_MMIO_xxx is duplicate with MMIO64_xxx. This patch replace HI_MMIO_xxx
with MMIO64_xxx.
Tracked-On: #6011
=> hv: mmio: replace hi_mmio with mmio64

misc/config_tools/board_inspector/board_inspector.py, misc/config_tools/board_inspector/cpuparser/cpuids.py, misc/config_tools/board_inspector/cpuparser/msr.py, misc/config_tools/board_inspector/cpuparser/platformbase.py, misc/config_tools/board_inspector/extractors/10-processors.py, misc/config_tools/board_inspector/inspectorlib/validator.py, misc/config_tools/board_inspector/schema/boardchecks.xsd, misc/config_tools/board_inspector/schema/checks/platform_capabilities.xsd
1. Add BIOS invalid setting check
I) check if VMX feature is enabled in the BIOS setting. If disabled, the board inspector will show an error message.
II)  check if Hyper-Threading is enabled in the BIOS setting. If enabled, the board inspector will show the warning message.
III) check if VT-d is enabled in the BIOS setting. If disabled, the board inspector will show an error message.
2. Add CPU capability checks.
If a feature is not supported on this processor, the board inspector will show an error message because it would impact ACRN’s ability to function properly.
=> config_tools: add CPU capability and BIOS invalid setting checks

misc/config_tools/launch_config/launch_cfg_gen.py
The device-model land ivshmem regions are not properly generated into the launch
scripts today because:
1. Those regions are provided by "Device Model", not "Device model".
2. VM names are not properly encoded in the XPATH that search for the
ivshmem regions accessible to a VM.
This patch fixes both issues.
Fixes: 0d84ecc4a ("config_tools: merge data in launch XMLs into scenario XMLs")
=> config-tools: fix the generation of DM-land ivshmem regions

hypervisor/scripts/makefile/config.mk, misc/config_tools/board_config/board_cfg_gen.py, misc/config_tools/library/common.py, misc/config_tools/library/launch_cfg_lib.py, misc/config_tools/scenario_config/scenario_cfg_gen.py, misc/config_tools/schema/config.xsd
remove BOARD/SCENARIO attribute dependency for the new configuration.
To do:
will remove all BOARD/SCENARIO attributes in all scenario XML files
and update the upgrader.py after the new configuration works.
Reviewed-by: Junjie Mao <[junjie.mao@intel.com](mailto:junjie.mao@intel.com)>
=> config_tools: remove board and scenario attribute

devicemodel/Makefile, devicemodel/core/hugetlb.c, devicemodel/hw/pci/virtio/virtio_gpu.c, devicemodel/hw/vdisplay_sdl.c, devicemodel/include/vdisplay.h, devicemodel/include/vmmapi.h
Now Virtio-gpu FE is using the below cmds to submit the framebuffer that
needs to be displayed.
VIRTIO_GPU_CMD_TRANSFER_TO_HOST_2D
VIRTIO_GPU_CMD_SET_SCANOUT
VIRTIO_GPU_CMD_FLUSH
This will introduce twice copy. It will affect the CPU usage, memory resource.
In order to optimize the twice copy, this patch set tries to add the support
of zero-copy based on dmabuf-sharing.
The key of zero-copy depends on the DMABuf and eglCreateImageKHR from dmabuf.
In order to create dmabuf based on the GPA addr of virtio-gpu framebuf, the memory
allocation for guest_vm should be based on memfd. This requires that the memory
for guest_vm should be allocated from memfd instead of explicit hugetlb file.
=> Vgpu dmabuf

doc/extensions/last_updated.py
When I added a new document that wasn't checked into GitHub yet, the doc
build failed with an unhanded exception:
Extension error (last_updated):
(exception: time data '' does not match format '%Y-%m-%d')
Problem is the git query looking up the last commit date for a file
returns an empty string for the date if the file exists but it's not in
the git repo (yet). The subsequent call to strptime raises an exception if passed
an empty string.  This patch handles the exception.
=> doc: fix exception error in last_modified processing

doc/Makefile
We use a post-processor to scan the output log from Sphinx to remove
known errors and warnings before deciding if the Sphinx build was
successful.  If an exception happened during the Sphinx build, (see
about the error would appear.  Update the Makefile to not stop on errors
for the Sphinx build. The post-processor will stop the make by returning
an error code if it finds unexpected errors in the log.
=> doc: fix Makefile to report errors if exception raised

doc/extensions/last_updated.py
If a new document is added, the CI system fails because the new document
hasn't been checked into the branch yet so the last_updated.py script
complains with an error.  Change to use the last_published date in this
situation.
Tracked-On: #7249
=> doc: handle last updated footer for new document

doc/extensions/last_updated.py
Update the last_updated extension to correctly handle when new docs are
added and aren't yet commited into git vs. when the list of git folders
isn't correct. Previous PR #7251 incorrectly handled these as the same.
Tracked-On: #7249
=> doc: properly handle last_updated info for new docs

misc/config_tools/board_inspector/board_inspector.py
fix the path issue that fail to read XSD file.
=> config_tools: fix the issue that fail to read XSD file

misc/services/life_mngr/life_mngr_win.c, misc/services/life_mngr/uart.c, misc/services/life_mngr/uart.h
1. enlarge receive Service VM message time to 10s. Now in some extreme
environments, Service VM will takes more than 1s to ACK the User VM's
requirements.
2. fix a bug to calculate string pointer size.
Tracked-On: #7215
=> mise: life_mngr: fix some minor bugs

devicemodel/hw/pci/core.c, devicemodel/include/pcireg.h
Add msi per-vector masking capable and emulate msi mask
pending mechanism in DM.
Tracked-On: #7265
=> ACRN:DM: Add the pci msi per-vector masking capable

misc/config_tools/schema/VMtypes.xsd, misc/config_tools/static_allocators/cpu_affinity.py
default value of minOccurs is "1", which will trigger problem
when user leave pcpu_id blank while preserve cpu_affinity in
service VM.
Tracked-On: #7267
=> config tool: Fix service vm cpu affinity issue

misc/packaging/deb.json
add OVMF_debug.fd in acrn deb
Tracked-On: #7272
=> deb-pkg: add OVMF_debug.fd in acrn deb

misc/config_tools/launch_config/launch_cfg_gen.py
add support for HV land ivshmem prefix in launch script
Tracked-On: #7279
=> config tool: generate HV land ivshmem parameter

misc/config_tools/data/cfl-k700-i7/hybrid_launch_2user_vm.xml, misc/config_tools/data/cfl-k700-i7/shared_launch_6user_vm.xml, misc/config_tools/data/generic_board/hybrid_launch_2user_vm.xml, misc/config_tools/data/generic_board/shared_launch_6user_vm.xml, misc/config_tools/data/nuc11tnbi5/hybrid_launch_2user_vm.xml, misc/config_tools/data/nuc11tnbi5/shared_launch_6user_vm.xml, misc/config_tools/data/tgl-vecow-spc-7100-Corei7/shared_launch_2user_vm.xml, misc/config_tools/data/whl-ipc-i5/hybrid_rt_launch_1user_vm_waag.xml, misc/config_tools/data/whl-ipc-i5/shared_launch_1user_vm_hardrt.xml, misc/config_tools/data/whl-ipc-i5/shared_launch_1user_vm_vxworks.xml, misc/config_tools/data/whl-ipc-i5/shared_launch_1user_vm_waag.xml, misc/config_tools/data/whl-ipc-i5/shared_launch_2user_vm.xml, misc/config_tools/data/whl-ipc-i5/shared_launch_6user_vm.xml, misc/config_tools/launch_config/launch_cfg_gen.py, misc/config_tools/launch_config/launch_script_template.sh, misc/config_tools/scenario_config/upgrader.py, misc/config_tools/schema/VMtypes.xsd, misc/config_tools/schema/config.xsd
We have redesigned Virtio devices (network/input/console) for the user, This patch series include refining the schema,  updating the launch script generation logic, and updating the upgrader python script for the new design.
=> config_tools: refine virtio devices

misc/config_tools/schema/checks/cpu_assignment.xsd
pcpu in pre-launched RTVM cannot share with other VM
Tracked-On: #7287
=> config tool: update cpu affinity check algorithm

devicemodel/core/hugetlb.c, devicemodel/core/vmmapi.c
The guest memory is allocated through hugetlb. Huge page fault is
triggered by writing a byte to the starting address for each huge page.
In hugetlb_fault(), The physical pages are allocated and *clear*.
So no need to erasing the memory again after hugetlb setup. This will
bring about 130ms (changes with platform) latency for each 1G memory.
Notice: this means we depends on kernel to erase the memory in huge page
fault!
Tracked-On: #7298
=> remove repetitive erasing for guest memory

misc/config_tools/board_inspector/extractors/60-pci.py, misc/config_tools/board_inspector/extractors/90-sorting.py, misc/config_tools/board_inspector/pcieparser/__init__.py, misc/config_tools/board_inspector/pcieparser/extcaps.py
This patch series adds logic to fully parse SR-IOV capabilities and                                                                                                                                                                                                                       correctly collect information of VFs when the board inspector collects                                                                                                                                                                                                                    board info. Such info will be stored into the board XML and used at …
=> Board Inspector: Collect all information about SR-IOV devices

misc/packaging/gen_acrn_deb.py
Added the "libsdl2-dev" dependency in file
"misc/packaging/gen_acrn_deb.py"
Tracked-On: projectacrn#7291
Signed-off-by: zihengL1 <ziheng.li@intel.com>
=> packaging: error while loading shared libraries: libSDL2-2.0.so.0

doc/static/acrn-custom.css
The read-the-docs theme uses a reduced font size within tables.  The CSS
used though is overly restrictive and doesn't properly handle tables
containing lists or other constructs where the paragraph tags don't have
the <td> tag within the table as the immediate parent.  Add an
overriding style in our custom CSS to fix this so the font size on lists
within a table are the same as normal paragraphs within a table.
=> doc: fix table CSS font size changing with lists

misc/config_tools/acpi_gen/asl_gen.py
Bugfix:bootargs is optional parameter, which may be not
present in xml as a node, asl_gen.py needs to process
that case.
Tracked-On: #7307
=> config tool:add support for bootargs missing

devicemodel/hw/pci/virtio/virtio_gpu.c, devicemodel/hw/vdisplay_sdl.c, devicemodel/hw/vga.c, devicemodel/include/vga.h
ACRN-DM will display the framebuffer that is submitted from the virtio-gpu
in guest and this is based on 3D driver. But as the 3D driver is not thread-
safe, it will be better that the 3D ops related with virito-gpu needs to
be called in dedicated-thread env. Otherwise it will trigger the sigsegv
in thread_exiting.
This is the patch set that tries to fix the sigsegv issue.
=> Acrn vgpu sigsegv

misc/config_tools/data/generic_board/generic_board.xml, misc/config_tools/data/nuc11tnbi5/nuc11tnbi5.xml, misc/config_tools/data/whl-ipc-i5/hybrid_rt_launch_1user_vm_waag.xml, misc/config_tools/data/whl-ipc-i5/whl-ipc-i5.xml
Because Board Inspector modifies the SR-IOV function,
VF information is correctly captured when Board Inspector
collects Board information. So update the board xmls
Tracked-On: #7031
=> config-tools: update nuc11/whl/generic_board board files

.deb.conf
Bugfix for OVMF_debug.fd
Tracked-On: #8744
=> deb-pkg: add OVMF_debug.fd in .deb.conf

hypervisor/boot/guest/elf_loader.c
This patch is to eliminate a code scan warning.
p_elf_header32 was given a value when it was declared, but later it was
given the same value again. Just remove the later one.
Tracked-On: #7318
=> hv: remove an unnecessary code line

hypervisor/arch/x86/guest/ept.c, hypervisor/arch/x86/mmu.c, hypervisor/arch/x86/pagetable.c, hypervisor/include/arch/x86/asm/pgtable.h
Page table entry present check is page table type
specific and static, e.g. just need to check bit0
of page entry for entries of MMU page table and
bit2~bit0 for EPT page table case. hence no need to
check it by callback function every time.
This patch remove 'pgentry_present' callback field and
add a new bitmask field for this page entry present check.
It can get better performance especially when this
check is executed frequently.
Tracked-On: #7327
=> hv: remove pgentry_present field in struct pgtable

doc/developer-guides/hld/hv-rdt.rst, doc/developer-guides/hld/virtio-blk.rst
1. Fix Incorrect site write in virtio-blk.html range configuration
2. Fix hv-rdt.html CDP_ENABLED parameter configuration error
=> doc: Fix virtio-blk.html/hv-rdt.html statement error

misc/config_tools/board_inspector/extractors/20-cache.py
Unlike other CPU IDs, the cpu_id field under //processors//thread in the
board XML is in decimal as it is assigned by the kernel continuously,
starting from 0. However, the cache info extractor today parses them as
hexadecimal numbers, leading to incomplete cache info when more than 10
processors are present on the board. This patch fixes this issue.
=> board_inspector: parse cpu IDs in decimal rather than hexadecimal

devicemodel/hw/pci/virtio/virtio_gpu.c, devicemodel/hw/vdisplay_sdl.c
The PR tries to fix the below issues in  the virtio-gpu.
a. incorrect access after free. virtio-gpu already frees the
allocated memory in course of reboot cycle. But the pointer is
not cleared to NULL. This will cause the incorrect access after free.
b. the memory_leak after enabling GPU zero-copy for
the virtio-gpu.
=> Fix the memory leak in virtio-gpu

misc/config_tools/launch_config/launch_cfg_gen.py, misc/config_tools/schema/config.xsd
Virtio gpu device UI will be implemented after 3.0.
As a workaround, this patch simply adds the virtio gpu entry in schema
and launch script generation logic.
Tracked-On: #7301
=> config_tools: add virtio gpu

misc/config_tools/data/generic_board/generic_board.xml, misc/config_tools/data/nuc11tnbi5/nuc11tnbi5.xml, misc/config_tools/data/whl-ipc-i5/whl-ipc-i5.xml
The cpu_id is allocated contiguously by the kernel, start at 0.
However, today's cache information extractors parse them as hexadecimal number,
more than 10 will result in incomplete cache information.
The issue now is fixed, so update the board xml.
=> config-tools: update xmls due to cpu_id parser changed

devicemodel/core/main.c
This patch checks the obsoleted parameters and print some warnings
instead of exiting the acrn-dm directly. The following obsoleted
parameters are covered:
-i, --ioc_node
-G, --gvtargs
-Y, --mptgen
--vsbl
--part_info
--pm_by_vuart
--pm_notify_channel
=> dm: optimize the parameter compatibility

misc/config_tools/requirements.txt
This patch adds a requirements.txt file that lists the libraries and their
versions the ACRN configuration toolset needs. The versions of elementpath
and xmlschema are fixed to the latest one supporting Python 3.6 due to the
requirement of the customized overlay.
Such requirements apply to both the board inspector and the XML
manipulation part of the configurator.
=> config_tools: list dependencies on Python libraries in requirements.txt

misc/config_tools/board_config/board_c.py, misc/config_tools/data/cfl-k700-i7/hybrid_launch_2user_vm.xml, misc/config_tools/data/cfl-k700-i7/partitioned.xml, misc/config_tools/data/generic_board/hybrid_launch_2user_vm.xml, misc/config_tools/data/generic_board/hybrid_rt.xml, misc/config_tools/data/generic_board/partitioned.xml, misc/config_tools/data/generic_board/shared_launch_6user_vm.xml, misc/config_tools/data/nuc11tnbi5/hybrid_launch_2user_vm.xml, misc/config_tools/data/nuc11tnbi5/partitioned.xml, misc/config_tools/data/nuc11tnbi5/shared_launch_6user_vm.xml, misc/config_tools/data/tgl-vecow-spc-7100-Corei7/hybrid.xml, misc/config_tools/data/tgl-vecow-spc-7100-Corei7/partitioned.xml, misc/config_tools/data/tgl-vecow-spc-7100-Corei7/shared_launch_2user_vm.xml, misc/config_tools/schema/config.xsd, misc/config_tools/schema/types.xsd, misc/config_tools/static_allocators/clos.py, misc/config_tools/xforms/lib.xsl, misc/config_tools/xforms/misc_cfg.h.xsl, misc/config_tools/xforms/vm_configurations.c.xsl
The current RDT setting requires users to calculate the CLOS mask and
the details, it is not a user-friendly setting.
So we redesigned RDT, users can easily specify the cache of each vcpu
for VMs.
This patch add an RDT region element for schema, calculate and generate
all the mask and rdt parameters by config tool to generates rdt_info
struct for board.c.
=> misc: refine cache config

misc/config_tools/data/cfl-k700-i7/hybrid_launch_2user_vm.xml, misc/config_tools/data/cfl-k700-i7/shared_launch_6user_vm.xml, misc/config_tools/data/generic_board/hybrid_launch_2user_vm.xml, misc/config_tools/data/generic_board/shared_launch_6user_vm.xml, misc/config_tools/data/nuc11tnbi5/hybrid_launch_2user_vm.xml, misc/config_tools/data/nuc11tnbi5/shared_launch_6user_vm.xml, misc/config_tools/data/tgl-vecow-spc-7100-Corei7/shared_launch_2user_vm.xml, misc/config_tools/data/whl-ipc-i5/hybrid_rt_launch_1user_vm_waag.xml, misc/config_tools/data/whl-ipc-i5/shared_launch_1user_vm_hardrt.xml, misc/config_tools/data/whl-ipc-i5/shared_launch_1user_vm_waag.xml, misc/config_tools/data/whl-ipc-i5/shared_launch_2user_vm.xml, misc/config_tools/data/whl-ipc-i5/shared_launch_6user_vm.xml, misc/config_tools/launch_config/launch_cfg_gen.py, misc/config_tools/scenario_config/upgrader.py, misc/config_tools/schema/config.xsd
1. updates virtio console in schema and launch script generation logic to support multiple console sockets.
2. update upgrader.py script for virtio devices.
1) add virtio gpu logic in the upgrader.py script.
2) fix the upgraded virtio elements issue.
3) add the logic to remove the element with an empty value in the XML file to use the default value.
=> config_tools: update virtio console to support multiple console sockets

misc/config_tools/configurator/src/lib/acrn.jsx, misc/config_tools/configurator/src/pages/Config/ConfigureSettingsForScenario/ConfigureSettingsForScenario.jsx
When removing Service VM from UI, the post-launched VMs should also be
removed.
Besides, add a warning window when removing Service VM.
Tracked-On: #7349
Reviewed-by:  Weiyi Feng <weiyix.feng@intel.com>
=> configurator: bugfix for removing Service VM

misc/config_tools/schema/checks/cpu_assignment.xsd
Previously we have checks to make sure pre-launched RTVM does not share
pCPU with others. This patch extends this check to all RTVMs.
Tracked-On: #7361
=> misc: config_tools: Add Check for RTVM pCPU assignment

hypervisor/arch/x86/rdt.c, hypervisor/include/arch/x86/asm/board.h
Since CAT support for hybrid platform is landed, let's remove some old declarations
which are no longer used.
=> hv: remove obsolete declarations related to RDT

hypervisor/dm/vpci/ivshmem.c, hypervisor/dm/vpci/pci_pt.c, hypervisor/dm/vpci/vhostbridge.c, hypervisor/dm/vpci/vmcs9900.c, hypervisor/dm/vpci/vmsix.c, hypervisor/dm/vpci/vpci.c, hypervisor/dm/vpci/vpci_bridge.c, hypervisor/dm/vpci/vpci_priv.h, hypervisor/dm/vpci/vroot_port.c, hypervisor/dm/vpci/vsriov.c, hypervisor/include/dm/vpci.h
1. MSI-X vectors may been changed by system software or driver software on runtime.
So we should pass htrough Message Control Register to guest.
2. Service may use VFs, so ACRN hypervisor should map VF BARs for PF to let PF
could initialize VF by firmware or PF's driver.
Tracked-On: #7275
=> HV: vPCI: fix two monir bugs

misc/config_tools/board_inspector/extractors/10-processors.py
Some cpu reports a brand string with non-viewable characters. While XML
string value can not contain NULL bytes or control characters.
So replace non-viewable characters in brand string with spaces.
Signed-off-by: Qiang Zhang <qiang4.zhang@linux.intel.com>
=> board_inspector: transform non-viewable characters in brand string

misc/packaging/gen_acrn_deb.py
A new target is available to the gen_acrn_deb.py script, namely
'configurator'. The error message in case the user passes an incorrect target
provides the valid option but did not mention this new 'configurator' target.
=> config_tools: add 'configurator' to error message

misc/packaging/gen_acrn_deb.py
Fixed the problem that the "'cp %s %s' % (source, target), cur_dir" command
is still executed when there is no ACPI_VM.bin file after build.
Tracked-On: projectacrn#7366
=> [acrn-configuration tool] make scenario shared file error cp error

devicemodel/hw/pci/virtio/virtio_gpu.c, devicemodel/hw/vdisplay_sdl.c
The virtio_gpu in guest_vm will try to fetch the EDID/Display_info to query
the supported resolution. Now acrn-dm doesn't handle the request of
VIRTIO_GPU_CMD_GET_EDID/VIRTIO_GPU_CMD_GET_DISPLAY_INFO.
This patch set tries to fix the above issue.
=> Acrn vgpu edid

misc/config_tools/static_allocators/clos.py, misc/config_tools/static_allocators/main.py
There was an issue of create hv node by clos module, the direct cause
is the create logic and the indirect cause is these modules of
static_allocators was not sorted before run which cause some platform
have issue and CI could not found.
So this patch fix the create issue and sorted the modules list to make
sure all these platform could work well and get the same allocation.xml
=> misc: fix the issue of create hv node

misc/config_tools/schema/checks/vbdf_assignment.xsd
The latest version of the elementpath library (i.e. 2.5.0) fails to
evaluate an XPATH which feeds a union of node sets to the `distinct-values`
function. An exception will be raised in such case, which eventually causes
the hypervisor build to fail.
This patch removes the usage of `distinct-values` function in the
XPATH. This may cause some additional delays to the evaluation of the
assertion, but at least will not impact the build even the latest versions
of the Python libraries are used.
Tracked-On: #7372
=> config_tools: do not apply distinct-values on a union of node-set

doc/scripts/configdoc.xsl
When an element in the schema does not have an acrn:applicable-vms or
acrn:views (as opposed to having the attribute with an empty value,
acrn:views="") we need to look up the ancestors to see if any of them
have an element with such an attribute defined.  If non of the ancestors
have that attribute defined, then the intrepretation is that the element
can be found for all VMs or for both basic and advanced tabs.
Tweak the xslt processing of the schema data to option config doc to
reflect these semantics.
=> doc: tweak option config doc processing for missing attributes

devicemodel/hw/platform/acpi/acpi_pm.c
For all Definition Blocks in ACPI Namespace, their name are a fixed 32 bits.
This patch refine CPU Definition Blocks name to support more than 10 CPUs
for a guest.
Tracked-On: #7387
=> dm: acpi: refine CPU Definition Blocks name

misc/config_tools/board_inspector/README, misc/config_tools/board_inspector/legacy/acpi.py, misc/packaging/acrn-board-inspector.postinst
This patch is about the bug that VMs can't idle.
ACRN enables VM's C-state by extracting host's C-state table.
The C-state table has two types of interfaces: system-IO and mwait. VMs
just need one of them. ACRN can support both.
Currently we are telling users to use the system-IO type. That is, by
adding 'nomwait intel_idle.max_cstate=0' to host Linux's CMD line when
using board_inspector. (The reaseon we were using system-IO is that
mwait was buggy on Apollo Lake.)
But recent tests show that system-IO is somehow buggy. Linux c-state
driver(no matter intel_cstate or acpi_cstate) fails to enter idle state
with system-IO. This can always be reproduced on native environments.
MPERF counters show CPU cores are not in real idle state as expected.
To enable C-state in VMs, we have to switch to …
=> config-tools: remove 'nomwait' from board_inspector's requirement

misc/config_tools/schema/config.xsd
xs:documentation content has an indented line that causes the reST
formatting of the generated content to be off (leading spaces on lines
are significant to reST formatting).
=> doc: fix malformed virtio gpu device description

devicemodel/core/main.c, devicemodel/hw/pci/core.c
This patch checks the change of "-s" sub parameters, which was
obsoleted or moved and the print some warnings msg or show the new
format.
The following obsoleted parameters are covered:
-s ,pci-gvt
-s ,virtio-hdcp
-s ,npk
-s ,virtio-coreu
--mac_seed
Reviewed-by: VanCutsem Geoffroy <geoffroy.vancutsem@intel.com>
=> dm: optimize the sub parameter of "-s" compatibility

misc/config_tools/schema/checks/cpu_assignment.xsd
cpu_affinity is required field for non-service vm,
add the check in case user misconfig it.
Tracked-On: #7405
=> config tool: add schema check for cpu_affinity

hypervisor/arch/x86/guest/vcpu.c, hypervisor/include/arch/x86/asm/cpu.h
The movdqu instruction moves unaligned double quadword (128 bit)
contained in XMM registers.
This patch uses pointers as input parameters of the function
write_xmm_0_2() to get 128-bit value from 64-bit array for each XMM
register.
Tracked-On: #7380
Signed-off-by: Jiang, Yanting <yanting.jiang@intel.com>
=> Fix: write xmm registers correctly

hypervisor/arch/x86/guest/vm.c
When booting prelaunch RTVM with SSRAM enabled, we need to delete the
SSRAM region that is used by prelaunch RTVM from Service VM EPT mapping.
If it is not used, or it is not fully used, the SSRAM or the rest SSRAM
should be in Service VM map.
But current code has a issue that it always deletes all SSRAM region
from Service VM EPT, even when no SSRAM is enabled for prelaunch RTVM.
This could cause the post RTVM with SSRAM boot failure, as DM checks and
removes SSRAM region from Service VM EPT during post RTVM setup.
Changing get_software_sram_size() to PRE_RTVM_SW_SRAM_MAX_SIZE could
solve the issue, as PRE_RTVM_SW_SRAM_MAX_SIZE is the SSRAM size that
prelaunch RTVM actually uses.
Tracked-On: #7401
=> hv: fix post RTVM booting failure with SSRAM

misc/packaging/acrn-board-inspector.postinst
Currently installing board_inspector deb would overwrite the grub
default kernel CMDLINE GRUB_CMDLINE_LINUX_DEFAULT. This could lose
some useful kernel args configured by user.
This patch is to change the 'overwrite' operation to 'append'.
Simply appending new CMDLINE to GRUB_CMDLINE_LINUX_DEFAULT could
not work. We need to remove duplicated args, and keep the args in
its origin order.
Tracked-On: #7402
=> config-tools: board_inspector deb appends kernel CMDLINE

doc/getting-started/getting-started.rst
The current code need python3.8-venv to build some modules, so we
should add these requirement to "Getting Started Guide".
This patch modify the getting-started.rst to generate new guide.
=> doc: fix the make configurator fails issue

misc/packaging/acrn-hypervisor.postinst
After replacing partitioned ACRN deb with shared deb, the stale
multiboot module for ACPI1.bin was left in ACRN grub entry because it
was taken as kernel image.
Tracked-On: #7400
=> misc: deb: Fix the ServiceVM kernel line in ACRN grub entry

devicemodel/hw/vdisplay_sdl.c
Now the function of edid_generate has some problems in constructing
the detailed_timing_block and standard mode blocks, which causes that
too few modes are parsed from EDID in guest_vm.
This patch set tries to fix the incorrect logic in EDID
detailed_timing_block and standard mode blocks so that the guest_vm
can parse the correct modes from EDID.
=> Acrn edid fix

misc/config_tools/static_allocators/memory_allocator.py, misc/config_tools/xforms/misc_cfg.h.xsl
update the hugepages algorithm as the following steps.
1. calculate the total hugepages of service vm using the formula.
"total memory - the memory consumed by pre-launched VMs - 3G
-1G(memory need by service vm supporting virtio gpu)
-300M*num(number of virtio gpu instance)"
2. calculate hugepage 2M/1G based post-launched vm memory setting.
3. correct the 2M/1G hugepages with the total hugepages in step 1.
"correct_mb, correct_gb= math.modf(total hugepages - the memory
consumed by Post_launched vm)
hugepages_1gb = hugepages_1gb + correct_gb
hugepages_2mb = hugepages_2mb + math.ceil(correct_mb*1024/2)"
Tracked-On: #7301
=> config_tools: update the hugepage algorithm

misc/config_tools/launch_config/launch_cfg_gen.py, misc/config_tools/launch_config/launch_script_template.sh
1. Add logic for virtio_framework in launch script.
If the user select "Kernel based (Virtual Host)" in virtio_framework entry, the "vhost" string will be added to the dm parameter.
2. Update the text format of backend_device_file.
Currently, the “backend_device_file” entry is a text combination of the elements `//device-classes/inputs/input/name` and `//device-classes/inputs/input/phys`. The format <name>:<phys> is shown in UI and the generated launch scripts.
However, we find ":" in some device physical path in adl-s-crb platform, this will result in script can't correctly distinguish <name> and <phys> by a colon. And we are not sure if colon will be found in the name variable in the future.
So this patch updates the text format of backend_device_file to "Device name: xxx, Device …
=> config_tools: bug fix for virtio

misc/packaging/gen_acrn_deb.py
fix can't find deb in build stage issue
=> config_tools: fix can't find deb in build stage issue

misc/config_tools/requirements.txt
After commit f8f1689a8 ("config_tools: do not apply distinct-values on a
union of node-set"), it has been confirmed that the reported build issue no
longer exists when using the latest elementpath (2.5.0) and
xmlschema (1.10.0). So this patch removes the version constraints in
requirements.txt.
Tracked-On: #7372
=> config_tools: drop version constraints on elementpath and xmlschema

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm.vue
The tooltip box's default width is inconsistent with the screen width.
It could run off the configurator window when the tooltip text is long.
Limit it to 50%.
Tracked-On: #7442
=> config-tools: limit the tooltip box max-width

misc/config_tools/configurator/packages/configurator/src/pages/Config.vue, misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm.vue
This patch is to fix the issue that when user edits VM name, the VM_NAME
field in IVSHMEM data doesn't sync.
To fix this, configForm emits a 'vmNameChange' when VM name is edited.
Then old name is replaced with new name. And when deleting VM, the old
name is replaced with null.
Tracked-On: #7445
=> config-tools: ivshmem.vm_name changes with name edit

doc/getting-started/getting-started.rst
commit 78f702e ("Use libdrm library for drm access") adds the dependency on
libdrm library. GSG needs to be updated accordingly. Otherwise, compilation
error occurs like below:
hw/pci/virtio/virtio_gpu.c:21:10: fatal error: libdrm/drm_fourcc.h: No such file or directory
21 | #include <libdrm/drm_fourcc.h>
|          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Tracked-On: #7464
=> doc: update GSG for virtio-gpu dependency libraries

hypervisor/dm/vrtc.c, hypervisor/include/arch/x86/asm/guest/vm.h, hypervisor/include/dm/mc146818rtc.h, hypervisor/include/dm/vrtc.h
Now ACRN would emulate vRTC for non-RT pre-launched VM, RTVM and
Service VM.
For vRTC read, ACRN would only return the the physical RTC register value;
for vRTC write, ACRN would ignore it.
New implement is:
1. Service OS read and write physical RTC.
2. The initial vRTC of each VM will is same with physical RTC, i.e. the RTC of service VM.
3. Guest VM can re-program its RTC (thu NTP etc.), but the update of guest RTC will be 
emulated by Hypervisor through 'offset_rtctime'.
4. Service VM will update physical RTC. So, if the system shuts down, hypervisor can rely 
on #2 for each VM to get right initial RTC (sync with real NTP), without saving the “offset_rtctime”.
5. A calibration of vrtc will trigger by timer every 3 hours to keep
precision.
6. When write the physical RTC, will reset the …
=> Hv vrtc for Prelanuched VM and RTVM

misc/config_tools/launch_config/launch_script_template.sh
The config tool supports auto add d3hot_reset option to
the windows vm script when user configure the usb passthru event,
but it's not handled in the template script or not the pci event
will not unbind successfully while launching the windows guest.
One more fix is for the existing tap network interface check function.
Tracked-On: #7363
=> config tool: fix d3hot_reset unbind tap create issue

hypervisor/lib/crypto/mbedtls/md.c
The comparison "ctx->md_info == NULL" (if ctx is not NULL) will always evaluate
as 'false' for the address of 'hmac_ctx' will never be NULL.
This patch remove this unnecessary check.
Tracked-On: #7453
=> hv: crypto: fix a minor build Werror

misc/services/acrn_manager/acrnctl.c
The comparison ((argv + 1)) will always evaluate as 'true' for the pointer
operand in 'argv + 8' must not be NULL.
Tracked-On: #7453
=> misc: acrnd: fix a minor build Werror

hypervisor/include/arch/x86/asm/vm_config.h, misc/config_tools/service_vm_config/serial_config.py, misc/config_tools/static_allocators/intx.py, misc/config_tools/static_allocators/s5_vuart.py, misc/config_tools/xforms/vm_configurations.h.xsl
"S5" is one of the ACPI sleep states which means the function to shut
down the VMs.
On ACRN, the User VM must be shut down before powering off the Service
VM, so we need a vUART channel to communicate between the Service VM
and User VMs.
After add vUART channel for each User VMs, the predefine number of vUART
is not enough, so move the define of MAX_VUART_NUM_PER_VM to config tool
which could get the right number of vUARTs.
=> Add vUART channel for s5 feature

doc/scripts/configdoc.xsl, misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/IVSHMEM_REGION.vue, misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/VUART.vue, misc/config_tools/scenario_config/jsonschema/converter.py, misc/config_tools/schema/VMtypes.xsd, misc/config_tools/schema/config.xsd, misc/config_tools/schema/types.xsd
The configurator today shows "Please Input" as the placeholder of input
widgets, which is far from informative.
This patch specifies element or type specific placeholders in the XML
schema by reusing the `acrn:widget-options` annotation mechanism. For
manually-designed widgets such as ivshmem or vUART the placeholders are
added in the corresponding vue directly.
=> config_tools: add placeholders in input widgets

doc/reference/config-options.rst, misc/config_tools/schema/VMtypes.xsd, misc/config_tools/schema/config.xsd, misc/config_tools/schema/types.xsd
Edit the schema (.xsd) files to modify the order options are presented.
None of these changes invalidate existing scenario XML files, as they
only reorder elements within the existing parent element, or tweak the
acrn:views, acrn:title, or documentation content.
Move simple type elements before complex type options (under the same
parent element) to avoid the confusion where options look like they're
part of a section based on the title that's added before complex typed
options but not simple typed options.
* add acrn:title to pcpu (pCPU list)
* change documentation for binary option saying "checked" instead of 'y'
* move HYPERV_ENABLED before RDT (simple type before complex type)
* move vuart_connections before FEATURES
* move name before vm_type
* move console_vuart, os_type, vuart0, …
=> schema changes for DX configurator option presentation

misc/config_tools/configurator/README.md, misc/packaging/gen_acrn_deb.py
Artifacts left over from a previous ``make configurator`` build prevented
changes to a schema (.xsd) file from getting incorporated into a
subsequent ``make configurator`` build.
Tracked-on: #7461
=> Fix make configurator not picking up schema changes

misc/config_tools/configurator/packages/configurator/src/pages/Welcome/NewConfiguration.vue
User-input working directory will not work if there's no path split at
the end. This patch checks and adds if no path split at the end of
working directory path.
Tracked-On: #7484
=> misc: configurator: Fix user-input working directory not working

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/IVSHMEM_REGION.vue, misc/config_tools/configurator/packages/vue-json-schema-form/vue3/vue3-core/src/components/Widget.js
IVSHMEM widget have no validation, it doesn't show red line msg for input forms that are marked as 'required'.
This patch adds the empty line validation.
And the vUART widget only do validation when data edit completed. This patch adds 'blur' 'input' 'focus' trigger to get instant result.
Tracked-On: #7481
=> config-tools: add validation to IVSHMEM widget

Makefile, misc/config_tools/configurator/packages/configurator/src/components/common/Footer.vue, misc/config_tools/configurator/packages/configurator/vite.config.js, misc/packaging/gen_acrn_deb.py
Display acrn version string from `git describe --dirty` at UI footer to
help testing. Append the same version to deb package name as well.
Tracked-On: #7488
=> misc: configurator: Use more precise acrn version identifier

misc/config_tools/schema/checks/vuart_config.xsd, misc/config_tools/schema/datachecks.xsd
The current UI have no live-check to check whether a VM connect to
itself.
So we add an assert to the schema and return error when user connect a
VM to itself.
=> misc: add assert for vUART connection

misc/config_tools/configurator/pyodide/loadBoard.py, misc/config_tools/schema/VMtypes.xsd
XPATH 2.0 already supports functions like for-expressions,
so we use XPATH expression instead of the python code to format
virtio input data.
=> config_tools: using XPATH expression to handle input data

misc/packaging/acrn-board-inspector.postinst
Python package is not in debian package, so put its installation
process in the acrn-board-inspector.postinst script
Tracked-On: projectacrn#7498
=> board_inspector.py fails to run on target with clean Ubuntu installation

misc/config_tools/configurator/packages/configurator/src/pages/Config.vue, misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/VUART.vue
1. Add validation to vuart widget, to warn on empty line for required field.
2. Add vm_name check, so that when vm_name is edited in vm tab, the vuart enpoint field changes to the new name.
=> config-tools: add validation and vm_name check for vuart widget

hypervisor/dm/vrtc.c
dm/vrtc.c:565:33: error: 'current' may be used uninitialized in this
function.[-Werror=maybe-uninitialized]
Move the local variable definition into one code block to avoid warning.
Tracked-on: #7511
=> hv: fix build warning with gcc-11.2

hypervisor/arch/x86/vtd.c, hypervisor/include/arch/x86/asm/vtd.h, hypervisor/include/lib/util.h, misc/config_tools/static_allocators/board_capability.py, misc/config_tools/xforms/vm_configurations.h.xsl
There is an issue of calculate 2^n roundup of CONFIG_MAX_PT_IRQ_ENTRIES,
and the code style is very ugly when we use macro to fix it.
So this series move MAX_IR_ENTRIES to offline tool to fix the issue and
clear HV code.
=> Move MAX_IR_ENTRIES  to offline tool

hypervisor/arch/x86/vtd.c
If multiple control fields in GCMD_REG register need to be modified, software
must serialize the modifications through multiple writes to this register.
So one-shot bits (bits 30-29, 27 and 24) in gcmd should not been set.
Otherwise, other control field may be written to GCMD_REG at the same time
with one-shot bit (Clearing one-shot bit has no effect, software sets this field
would set/update this control field used by hardware).
Tracked-On: #7381
=> hv: vtd: reset the one-shot bits for GCMD_REG

misc/config_tools/schema/config.xsd
A previous PR incorectly removed the hypervisor FEATURES options on the
basic tab because all options were advanced.  One wasn't (IVSHMEM).
Tracked-on: #7514
=> config: restore FEATURES on the basic tab

misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
update activeVMID to make the delete vm button disappear
when all VMs are deleted.
Tracked-On: #7516
=> misc: configurator:Fix delete vm button apearance

Makefile, misc/packaging/gen_acrn_deb.py
This patch use 'make clean' to clean up the files left after
a 'make configurator'.
Tracked-On: #7508
=> config_tools: clean up configurator

misc/config_tools/launch_config/launch_cfg_gen.py
Generated launch scripts tracks the options to ACRN device model in an
array `dm_params`. Those scripts use `${dm_params[*]}` to join all
elements in the array and pass the joined string to acrn-dm.
One tricky thing about `${dm_params[*]}` is that it joins the array
elements as one single unquoted string. This means an option as a string
with whitespaces will be split by the shell and passed to acrn-dm as
multiple options. This does not happen to the options generated today, but
prevents users from using, e.g., the -B option to pass the full command
line options for the guest kernel.
Rather than joining all elements as an unquoted string, it is more
preferrable to treat each element in `dm_params` as a quoted string. This
patch does this by:
1. replacing `${dm_params[*]}` with …
=> config_tools: fix option passing to device model in launch scripts

misc/config_tools/schema/checks/cpu_assignment.xsd
CPUs assigned to Pre-launched VM can not be shared. Add a xsd rule to
check it.
Tracked-On: #7526
=> misc: configurator: add check for uniqueness of cpus in Pre-launched VM

misc/config_tools/configurator/packages/configurator/src/lib/acrn.ts, misc/config_tools/configurator/pyodide/loadBoard.py, misc/config_tools/configurator/pyodide/pyodide.py
Use file name as the board xml name instead of using the name in
'board' field in board XML.
e.g.
1. Initial filename is "my_potato.xml"
2. User imports my_potato.xml into the Configurator
3. Resulting file is my_potato.board.xml
Tracked-On: #7521
=> config-tools: change name for board XML

misc/config_tools/launch_config/launch_cfg_gen.py, misc/config_tools/schema/config.xsd
vsock is the new socket address family for host/guest communication.
Configurator option for vsock CID is added in this patch.
Also vsock parameter is generated in script.
Tracked-On: #7535
=> config-tools: add vsock option in configurator

misc/config_tools/configurator/packages/configurator/src/pages/Config.vue, misc/config_tools/configurator/packages/configurator/src/pages/Config/NewBoard.vue
1. Clean all launch scripts before click "Save" button, the new launch
scripts will be created after that.
2. Add a blank line to the warning dialog box.
3, Change dialog box message when click "Use a Different Board" button.
=> config-tools: clean launch scripts before saving

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/Virtio/Console.vue, misc/config_tools/schema/VMtypes.xsd, misc/config_tools/schema/config.xsd
1. Add restriction for Maximum Virtual CLOS configuration that doesn't allow negative numbers in UI.
2. Hide tty and sock in UI.
=> config_tools: bugfix for the configurator

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm.vue
Tooltip width was set to 50%. This could not just cut the line into
2 lines, for the line has to be cut by word. This would leave one
word on a new line, looks weird.
Set to 60% will solve this issue.
Tracked-On: #7541
=> config-tools: change the tooltip width to 60%

misc/config_tools/schema/config.xsd
Current physical memory segmentation UI have an redundant title when
user select the advance mode, so we set the MemoryInfo element title
to NULL to fix this issue.
Tracked-On: #8861
=> misc: fix the physical memory segmentation UI issue

hypervisor/debug/shell.c
In 'get_ptdev_info()', variables 'bdf' and 'vbdf' are
16bits in size but their base addresses are converted
to 32bit pointers when calling 'get_entry_info()'.
This mismatch causes insufficient space when storing
to memory pointer by 'bdf' or 'vbdf' in 'get_entry_info()',
where those pointers are regarded as 32bits width memory.
This patch refines definition of 'get_entry_info()'.
Tracked-On: #7547
=> hv: debug: fix type size mismatch in get_entry_info

misc/config_tools/schema/config.xsd
The current RDT element display for basic and advance mode, it not
necessary, so this patch hide RDT for basic mode.
Signed-off-by: Chenli Wei chenli.wei@intel.com
=> misc: hide RDT for basic mode

misc/config_tools/service_vm_config/serial_config.py, misc/config_tools/static_allocators/s5_vuart.py
The legacy code get all non-stand vUARTs from scenario_etree and generate
the serial.conf, now we need add more non-stand vUARTs which was config
by offline tool and record by allocation_etree.
This patch add allocation_etree to the list, then add all non-stand
vUART to serial.conf which will config by SERVICE VM.
=> misc: modify the non stand s5 vUART generate logic

misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
Show VMname in the warning window when trying to delete a VM from UI.
Tracked-On: #7532
=> config-tools: use VMname instead of VMId

misc/config_tools/data/cfl-k700-i7/hybrid_launch_2user_vm.xml, misc/config_tools/data/cfl-k700-i7/hybrid_rt.xml, misc/config_tools/data/generic_board/hybrid_launch_2user_vm.xml, misc/config_tools/data/generic_board/hybrid_rt.xml, misc/config_tools/data/nuc11tnbi5/hybrid_launch_2user_vm.xml, misc/config_tools/data/tgl-vecow-spc-7100-Corei7/hybrid.xml, misc/config_tools/data/whl-ipc-i5/hybrid.xml, misc/config_tools/data/whl-ipc-i5/hybrid_rt_launch_1user_vm_waag.xml, misc/config_tools/schema/config.xsd
Currently setting cpu_affinity for service vm has no effect. This patch
sets acrn:applicable-vms of cpu_affinity to pre-launched VMs and
post-launched VMs to restrict validation and UI display.
Tracked-On: #7538
=> misc: Add applicable-vms to cpu_affinity

misc/config_tools/static_allocators/bdf.py
Because SR-IOV is enabled to obtain board xml,
the xpath address cannot resolve the @address='0x20000' address.
cause the build to fail. fix build issues
Tracked-On: #7371
=> config-tools: Fix Enable SR-IOV build fail

misc/config_tools/schema/config.xsd, misc/config_tools/schema/types.xsd, misc/config_tools/static_allocators/lib/lib.py
Add an explicit "None" entry in HV console selector if user would like
to disable debug console or there is no serial console available.
Tracked-On: #7546
=> misc: configurator: Add entry "None" to HV console selector

hypervisor/include/common/event.h
This patch changes the type of nqueued in struct sched_event from int8_t
to int32_t.
In commit d575edf79, the 1 bit flag in struct sched_event has been
changed to int8_t counter to resolve race condition. Signal_event
will decrease the counter and wait_event will increase it and loop if
the counter is greater than 0.
In most cases the uses of signal_event and wait_event are consistent,
except VCPU_EVENT_VIRTUAL_INTERRUPT. In our logic, we signal this event
whenever there is an virtual interrupt, but we wait on it only in
hlt_vmexit_handler, and we reset this event before VMEnter.
In most cases this worked fine. However it has been found that in
certain GPU stress testing scenario, the signaling of this event
happened too frequently to the point where this int8_t counter underflowed
(i.e., …
=> [release_3.0 branch] hv: sched_event: Change nqueued from int8_t to int32_t

misc/config_tools/configurator/packages/configurator/src/pages/Config/Board.vue
Only import board with special suffix: .board.xml
Tracked-On: #7571
=> config-tools: fix board import bug

misc/config_tools/data/nuc11tnbi5/shared_launch_6user_vm.xml, misc/config_tools/launch_config/launch_cfg_gen.py
bugfix for the generated launch script without uart parameters
after VUART is configured to "pci"
Tracked-On: #7556
=> config_tools: bugfix for launch script without uart parameters

devicemodel/hw/pci/virtio/vhost_vsock.c, devicemodel/include/vhost_vsock.h
Replace the exclamation mark with period mark in debug info and fix
the Guest CID max value macro.
Tracked-On: #7456
=> ACRN: DM: Fix the vsock error info.

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/IVSHMEM_REGION.vue
The current UI force user input BDF which could automatically fill it
in if it is blank, so it an optional.
This patch change the BDF to an optional.
=> misc: modify IVSHMEM virtual BDF validation check

misc/config_tools/configurator/pyodide/loadBoard.py
Board files with multiple dots in their name may be splitted
incorrectly, and os.path.basename assumes os.name == posix in pyodide
environment. This workaround partially fixes this problem whenever the
the board filename does not contain '\' character.
Tracked-On: #7582
=> [release_3.0] misc: configurator: bugfix: incorrect path split

doc/scripts/configdoc.xsl
The acrn:views processing for showing which tabs an option would display
on wasn't quite right when an element AND a parent both had a views
attribute (specifically when the parent had "basic, advanced" but the
element only had "basic" or "advanced").
=> doc: adjust views processing for schema documentation

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/VUART.vue, misc/config_tools/schema/VMtypes.xsd
The vuart widget was showing enum values in select-form as options.
The correct way is to show enumNames instead of values.
The widget uses b-form which need different data structure for
select-form. So this patch added a transformation.
Also changed the label 'VBDF' to 'Virtual BDF' as an UX improvement.
Tracked-On: #7562
=> config-tools: show enumNames in vuart select-form

misc/config_tools/xforms/misc_cfg.h.xsl, misc/config_tools/xforms/vm_configurations.h.xsl
Add udmabuf.list_limit=8192 to ServiceVM bootargs for virtio gpu. It's
harmless if not used.
Tracked-On: #7581
=> misc: config_tool: Add udmabuf.list_limit=8192 to ServiceVM bootargs

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/Virtio/Console.vue, misc/config_tools/schema/VMtypes.xsd
1. virtio serial port and virtio console are all based on virito serial port. but virtio serial port functionally can not be used as 
console, which may lead to user confusion, so explicitly specify the point by changing the item name as follows:
Virtio console -> virtio serial port (as console)
3. fix the issue that saves all enum values are saved in the scenario XML file if the user doesn't select any value in the configurator.
4. It's unexpected to show the "PCI" option for Console virtual UART type currently, so this patch hides it in the configurator.
=> config_tools: bugs fix for configurator

misc/config_tools/schema/VMtypes.xsd, misc/config_tools/schema/config.xsd
Add additional DX/UI option changes
* Remove description of hypervisor features
* Move vuart connection before debug options
* delete memory options description
* delete hypervisor capacities description
* move cpu affinity before virtual USB HDI
* move memory size right after os type
* add "device assignment" to virtual USB HDI title
* delete usb device assignment description
Also fixed some typos found in descriptions.
=> config: additional DX/UI option layout and descriptions

misc/config_tools/configurator/packages/configurator/src/pages/Config/Board.vue
Delete old .board.xml after reselect a new one so that there will be
only one working .board.xml in working directory
Tracked-On: #7597
=> misc: configurator: Delete old .board.xml after reselect a new one

misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
For Service OS, 'vm_type' should not be modified.
Delete it from 'ServiceVMBasicConfigType' to forbid unexpected error.
Tracked-On: #7528
=> config_tools: hide vm_type for Service VM

misc/config_tools/data/cfl-k700-i7/hybrid_launch_2user_vm.xml, misc/config_tools/data/cfl-k700-i7/hybrid_rt.xml, misc/config_tools/data/cfl-k700-i7/partitioned.xml, misc/config_tools/data/cfl-k700-i7/shared_launch_6user_vm.xml, misc/config_tools/data/generic_board/hybrid_launch_2user_vm.xml, misc/config_tools/data/generic_board/hybrid_rt.xml, misc/config_tools/data/generic_board/partitioned.xml, misc/config_tools/data/generic_board/shared_launch_6user_vm.xml, misc/config_tools/data/nuc11tnbi5/hybrid_launch_2user_vm.xml, misc/config_tools/data/nuc11tnbi5/partitioned.xml, misc/config_tools/data/nuc11tnbi5/shared_launch_6user_vm.xml, misc/config_tools/data/qemu/shared.xml, misc/config_tools/data/tgl-vecow-spc-7100-Corei7/hybrid.xml, misc/config_tools/data/tgl-vecow-spc-7100-Corei7/partitioned.xml, misc/config_tools/data/tgl-vecow-spc-7100-Corei7/shared_launch_2user_vm.xml, misc/config_tools/data/whl-ipc-i5/hybrid.xml, misc/config_tools/data/whl-ipc-i5/hybrid_rt_launch_1user_vm_waag.xml, misc/config_tools/data/whl-ipc-i5/partitioned.xml, misc/config_tools/data/whl-ipc-i5/shared_launch_1user_vm_hardrt.xml, misc/config_tools/data/whl-ipc-i5/shared_launch_1user_vm_vxworks.xml, misc/config_tools/data/whl-ipc-i5/shared_launch_1user_vm_waag.xml, misc/config_tools/data/whl-ipc-i5/shared_launch_2user_vm.xml, misc/config_tools/data/whl-ipc-i5/shared_launch_6user_vm.xml, misc/config_tools/schema/VMtypes.xsd, misc/config_tools/schema/config.xsd, misc/config_tools/xforms/vm_configurations.c.xsl
The current UI "Maximum virtual CLOS" above the "VM Virtual Cache  Allocation Tech", it's not user-friendly, and the clos element was not  used by vCAT feature.
This series move the "virtual_cat_number" element and remove the unused  node from schema, then remove clos node from XMLS to adapter these change.
=> Refine clos and vCAT element

misc/config_tools/scenario_config/upgrader.py, misc/config_tools/schema/types.xsd
The EnablementType is now obsolete and config items having this type have
been updated to use the Boolean type. However, the upgrader is not changed
accordingly and it still converts "y" or "n" of certain config items to
"Enable" or "Disable".
This patch drops the EnablementType in the schema and updates the upgrader
to respect the latest definitions.
=> config_tools: fix move_enablement in the upgrader

misc/config_tools/schema/checks/vuart_config.xsd
The current UI allow user use duplicate vUART io_port for same VM, it's
an issue.
This patch add assert check it.
=> misc: add assert for duplicate vUART io_port

misc/config_tools/data/cfl-k700-i7/hybrid_launch_2user_vm.xml, misc/config_tools/data/cfl-k700-i7/hybrid_rt.xml, misc/config_tools/data/cfl-k700-i7/partitioned.xml, misc/config_tools/data/cfl-k700-i7/shared_launch_6user_vm.xml, misc/config_tools/data/generic_board/hybrid_launch_2user_vm.xml, misc/config_tools/data/generic_board/hybrid_rt.xml, misc/config_tools/data/generic_board/partitioned.xml, misc/config_tools/data/generic_board/shared_launch_6user_vm.xml, misc/config_tools/data/nuc11tnbi5/hybrid_launch_2user_vm.xml, misc/config_tools/data/nuc11tnbi5/partitioned.xml, misc/config_tools/data/nuc11tnbi5/shared_launch_6user_vm.xml, misc/config_tools/data/qemu/shared.xml, misc/config_tools/data/tgl-vecow-spc-7100-Corei7/hybrid.xml, misc/config_tools/data/tgl-vecow-spc-7100-Corei7/partitioned.xml, misc/config_tools/data/tgl-vecow-spc-7100-Corei7/shared_launch_2user_vm.xml, misc/config_tools/data/whl-ipc-i5/hybrid.xml, misc/config_tools/data/whl-ipc-i5/hybrid_rt_launch_1user_vm_waag.xml, misc/config_tools/data/whl-ipc-i5/partitioned.xml, misc/config_tools/data/whl-ipc-i5/shared_launch_1user_vm_hardrt.xml, misc/config_tools/data/whl-ipc-i5/shared_launch_1user_vm_vxworks.xml, misc/config_tools/data/whl-ipc-i5/shared_launch_1user_vm_waag.xml, misc/config_tools/data/whl-ipc-i5/shared_launch_2user_vm.xml, misc/config_tools/data/whl-ipc-i5/shared_launch_6user_vm.xml, misc/config_tools/schema/config.xsd
(adding to release_3.0 branch)
DX/UI recommendation is to move the build type parameter outside of the
debugoptions section. This breaks existing schema files, so also update
scenario XML files in the code tree to match.
Update the xforms xsl script with the same change to the buildtype
option location in schema XML files.
Tracked-on: #5692
=> move buildtype above debugoptions in the scenario schema

devicemodel/hw/platform/hpet.c
'data' maybe used uninitialized in function
hpet_mmio_read() function.
Tracked-On: #7606
=> [release_3.0] dm: fix uninitialized variable issue in hpet_mmio_read

doc/scripts/configdoc.xsl
Fix how the config option doc scripts behave when encountering elements
with blank titles (used to remove extraneous headings in the
configurator UI).
=> doc: properly handle empty and skipped acrn:title elements

misc/config_tools/schema/VMtypes.xsd, misc/config_tools/schema/config.xsd
(Replicating change on master into release_3.0 branch)
DX recommendation is to remove some extraneous titles from the
configurator UI, specifically "Memory", "Hypervisor Features", and "PCI
device assignment"
=> config: remove extraneous headings in UI

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/CAT.vue
Currently the empty cache_regions are saved to scenario file. It is
useless, and unable to pass the load/build validation check, causing
build fail.
This patch add a filter to the empty cache_region entry, so that the
load/build validation check may pass.
Tracked-On: #7609
=> config-tools: remove empty cache_region entry

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/IVSHMEM_REGION.vue, misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/VUART.vue
When user adds a vUART or IVSHMEM region and select VMs in selection
list, deleting the selected VM could break the selection box.
This patch adds a state check against null and undefined value.
Tracked-On: #7624
=> misc: configurator: Fix vUART and IVSHMEM select box missing problem

misc/config_tools/scenario_config/jsonschema/converter.py, misc/config_tools/schema/VMtypes.xsd, misc/config_tools/schema/config.xsd, misc/config_tools/schema/types.xsd
The default error messages provided by the ajv validation library read like
this:
* must have required property MEMORY.STACK_SIZE
* must match pattern "<a regular expression>"
Such messages may look confusing as users are not supposed to understand
the internal naming of the config items or the regular expressions used to
validate strings.
This patch enables the XML schema to include 'acrn:errormsg' annotations
which is a dictionary from error types to customized error messages. This
mechanism is used to show more user-friendly messages upon common errors
such as missing or invalid data in required config item.
=> config_tools: pretty-print JSON schema violations

misc/config_tools/launch_config/launch_cfg_gen.py
"enable_ptm" and "d3hot_reset" failed to pass to acrn-dm because of
shell syntax error (arguments are separated by space, not comma).
Remove "igd-vf" as it's no longer needed.
Tracked-On: #7623
=> misc: config_tool: fix passthrough device options in launch script

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/CAT.vue
Currently the empty cache_regions are saved to scenario file. It is
useless, and unable to pass the load/build validation check, causing
build fail.
This patch add a filter to the empty cache_region entry, so that the
load/build validation check may pass.
Tracked-On: #7609
=> [release_3.0] config-tools: remove empty cache_region entry

devicemodel/hw/pci/virtio/vhost_vsock.c, devicemodel/include/vhost_vsock.h
Vsock guest cid should be u32 type, redefined the cid type and
fix the MAX value of the cid.
Tracked-On: #7456
=> ACRN: DM: Fix the vsock Guest Cid overflow issue

misc/config_tools/schema/VMtypes.xsd, misc/config_tools/schema/checks/virtio_devices.xsd, misc/config_tools/schema/config.xsd, misc/config_tools/schema/datachecks.xsd
1. One VM can have multi vsock. Changed vsock UI to multi line.
2. Add verification that no repeated CID is allowed.
3. Refine the tooltip text.
Tracked-On: #7637
=> config-tools: refine vsock UI

hypervisor/boot/guest/bzimage_loader.c
When CONFIG_MULTIBOOT2 is disabled, 'create_service_vm_efi_mmap_desc' is
unused and build fails because [-Werror=unused-function] is set.
boot/guest/bzimage_loader.c:188:17: error: 'create_service_vm_efi_mmap_desc' defined but not used [-Werror=unused-function]
188 | static uint16_t create_service_vm_efi_mmap_desc(struct acrn_vm *vm, struct efi_memory_desc *efi_mmap_desc)
|                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
Tracked-On: #7634
=> hv: compile out unused function if CONFIG_MULTIBOOT2 is disabled

devicemodel/hw/pci/virtio/vhost_vsock.c
The vsock cid type is u32, redefine the cid type to u32, and use
dm_strtoui API replace dm_strtoi.
Tracked-On: #7456
=> ACRN: DM: Fix the vsock cid overflow issue.

misc/packaging/gen_acrn_deb.py
Update the Debian packaging script to list all the valid options for the first
argument, specifically 'acrn_all', 'board_inspector', 'configurator' and
'clean'.
=> Packaging: update Debian packaging script to reflect all valid targets

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/IVSHMEM_REGION.vue
Fix IVSHMEM size selection options missing bug due to data provider
being deleted by mistake.
Tracked-On: #7650
=> misc: configurator: fix IVSHMEM size missing bug

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/VUART.vue, misc/config_tools/schema/VMtypes.xsd
The labels and titles in vuart widget are hard-coded in the .vue file
rather than exposing the text from XSD file. This patch fixed it.
Tracked-On: #7562
=> [release_3.0] config-tools: refine the vuart widget's text

misc/config_tools/schema/types.xsd
Set VM_NAME' for 'IVSHMEMVM' as required property in schema.
Tracked-On: #7662
Signed-off-by: Zhao <yuanyuan.zhao@intel.com>
=> config_tools: schema of 'VM_NAME' for 'IVSHMEMVM'

misc/config_tools/schema/config.xsd
(Duplicating change on master branch to release_3.0 branch)
The MCE, split lock, and UC lock checkboxes have a unique behavior.
Selecting the checkbox disables the feature. We proposed changing the
behavior, so that the checkbox enables the feature, but the fix is
postponed to v3.1. Change the sense of these option's tooltip and title
to reflect their current behavior (Disabling vs. normal Enabling).
Tracked-On: #7661
=> Change sense of some schema config options

devicemodel/core/main.c, devicemodel/hw/vdisplay_sdl.c, devicemodel/include/vdisplay.h
Virtual display is component which based on native window system.
This feature depended phisical monitor connected and graphic driver in
SOS running correctly. If these dependencies fail, it is a fatal error
for virtual display. We have to terminate the device model to let user
fix runtime environment issue for graphics.
Tracked-On: #7672
=> dm: vdisplay: terminate acrn-dm process when SDL init failed

devicemodel/hw/pci/ahci.c
tfd is one data field of FIS for AHCI, it is unacceptable if it is
random value, could cause AHCI data transport failure.
Acturally there is no chance the switch statement has the value other
than 0~3, since there is only 2 bit to deduce.
Add the initial value for tfd as ATA_S_ERROR, which is checked by
function ahci_write_fis_d2h afterwards, so guest driver could handle it well.
Tracked-On: #7679
=> dm: Fix uninitialized variable in AHCI

misc/config_tools/schema/checks/ivsh_memory.xsd, misc/config_tools/schema/datachecks.xsd
The current code allow the same region name for same VM, it's an issue
This patch add an assert to check the above issue and report it.
=> misc: add assert to check ivsh memory region name

misc/config_tools/schema/checks/cpu_assignment.xsd
CPU sharing among standard Pre-launched VMs and Post-launched VMs are
allowed by design. Revert 4e2abfb4730 ('misc: configurator: add check
for uniqueness of cpus in Pre-launched VM')
Tracked-On: #7688
Signed-off-by: Qiang Zhang <qiang4.zhang@intel.com>
=> misc: config_tool: allow cpu sharing among standard VMs

devicemodel/hw/pci/xhci.c
Flow Table 6-95 from xHCI spec, Ring Segment Size defines
the number of TRBs supported by the ring segment, valid
values for this field are 16 to 4096.
Tracked-On: #6981
=> [release_3.0]ACRN: xHCI: Check the value of Ring Segment Size

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/IVSHMEM_REGION.vue, misc/config_tools/schema/types.xsd
1. Fix the issue that when saving the configuration, the vBDF does not
display automatically in IVSHMEM region.
2. Chagne 'Region name' in IVSHMEM from optional to required.
3. Fix the wrong tooltip content for 'VM name'.
Tracked-On: #7673
=> config-tools: fix vBDF issue for IVSHMEM

misc/config_tools/schema/checks/cpu_assignment.xsd, misc/config_tools/schema/checks/ivsh_memory.xsd, misc/config_tools/schema/checks/passthrough_devices.xsd, misc/config_tools/schema/checks/rdt_support.xsd, misc/config_tools/schema/checks/vbdf_assignment.xsd, misc/config_tools/schema/checks/virtio_devices.xsd, misc/config_tools/schema/checks/vm_types.xsd, misc/config_tools/schema/checks/vuart_config.xsd
Use DX names (acrn:title) instead of element names in messages.
Add missing message in rdt_support.xsd (all asserts need an annotation
with documentation for the error message that will be reported).
Tracked-On: #7685
=> doc: edit schema assert messages for clarity and grammar

misc/config_tools/schema/VMtypes.xsd, misc/config_tools/schema/checks/ivsh_memory.xsd, misc/config_tools/schema/checks/vuart_config.xsd
ivshmem name and vuart connection vm name are required in UI, so
add the check in case user miss setting them.
Tracked-On: #7700
=> config tool:add schema check for UI name validation

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/CAT.vue
CAT is no longer unchecked when VCAT is unchecked
=> config_tools: CAT is no longer unchecked when VCAT is unchecked

devicemodel/hw/pci/core.c
This patch fix the USB msi capability access failed issue and fix the
MSI pending bit clear bugs.
Tracked-On: #7697
=> ACRN:DM: Fix USB msi capability access issue.

misc/packaging/gen_acrn_deb.py
Clear schema files of config tools when 'make clean'.
Tracked-On: #7508
=> config_tools: clear schema files

doc/Makefile, doc/scripts/configdoc.xsl
Add a configuration parameter for the xsltproc processing to decide
whether to include hidden options.
=> doc: parameterize hidden config option doc generation

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/IVSHMEM_REGION.vue
IVSHMEM region name input value may be null after saving the scenario.
Add a null check to avoid marking empty input as correct.
Tracked-On: #7707
=> misc: configurator: fix minor bug of IVSHMEM region name

doc/getting-started/getting-started.rst, misc/config_tools/configurator/README.md, misc/config_tools/configurator/requirements.txt, misc/config_tools/requirements.txt, misc/packaging/gen_acrn_deb.py
For config_tools use python to clear dirty files, add python dependence
while prepare development computer.
Tracked-On: #7508
=> doc: GSG's python dependence

Makefile
Clean the top-level Makefile by removing some old and obsolete targets that
are no longer used and for which we do not even have the required file (such
as $(BOARD).xml.
Tracked-On: #7632
=> Makefile: remove obsolete targets

devicemodel/hw/platform/hpet.c
'data' maybe used uninitialized in function
hpet_mmio_read() function.
Tracked-On: #7606
=> dm: fix uninitialized variable issue in hpet_mmio_read

devicemodel/hw/pci/core.c, devicemodel/include/pci_core.h
The patch fix the Pci Msi capability mask and pending set and clear
bugs.
Tracked-On: #7697
=> ACRN: DM: Fix the MSI mask and pending bit bugs

misc/config_tools/static_allocators/hv_ram.py
The current code use a start address and hv_ram_size to find the start
address of acrn.bin, the start address is 32M which leaving too much
memory and will be load modules by grub, sometimes these modules will
override the HV log region.
This patch set the start address to 4M to avoid the above issue as much
as possible.
This algorithm depend on the board info, so the board XML should be
generate again if user change the SSRAM.
=> misc: modify the HV start address

misc/config_tools/schema/config.xsd
Missed a use of the XML element name instead of the DX-friendly title in
the option description.  (For those paying attention, the default value
shown in the description also uses the XML element name, but we don't
have a convenient way to turn that string into the corresponding
acrn:title value.
=> doc: update VM types description to use DX-friendly title

misc/config_tools/schema/config.xsd
Set 'STANDARD_VM' as default value for 'vm_type'.
Tracked-On: #7726
=> config_tools: add default value to 'vm_type'

misc/config_tools/scenario_config/upgrader.py
When run the upgrader.py to merge scenario XML and launch XML files,
deleted "desc" text in "usb_xhci" node, and changed the "vbootloader"
text from "Enable" to "y", from "Disable" to "n".
Tracked-On: #7660
=> config_tools: refine issues in the upgrader

misc/config_tools/configurator/packages/configurator/src/lib/acrn.ts, misc/config_tools/configurator/packages/configurator/src/pages/Config.vue, misc/config_tools/configurator/pyodide/validateScenario.py, misc/config_tools/configurator/pyodide/validateScenarioStructure.py, misc/config_tools/schema/scenario_structure.xsd
This patch series makes the following changes to the scenario validation in the configurator.
* Validation of scenario XML on load is relaxed to check only the essential structure assumed by the configurator.
* Validation of scenario XML on save is strengthened to check both syntactic and semantic issues.
=> Tweak scenario validation in the configurator

misc/config_tools/library/rdt.py, misc/config_tools/scenario_config/elementpath_overlay.py, misc/config_tools/schema/checks/rdt_support.xsd, misc/config_tools/schema/datachecks.xsd, misc/config_tools/static_allocators/clos.py
The current RDT class and interface was define by the clos.py which is
mix get and merge RDT policy, create clos nodes.
This patch abstract the RDT to interface to common.
=> misc: move the RDT interface to common libary

misc/config_tools/static_allocators/intx.py, misc/config_tools/static_allocators/s5_vuart.py
There were some legacy logic of the current code, the PCI vUART index
in the launch script have not count the vUART of S5 and life_mngr_win
use the COM2 as default vUART.
This patch change the vUART index and irq to adapt above logic and all
of these legacy code will be refine next version.
=> misc: modify the vUART index order and irq

devicemodel/hw/pci/virtio/virtio_net.c, devicemodel/hw/platform/tpm/tpm.c
There was some secure coding style violations of virtio net and tmp,
this patch add some NULL check to fix these violations.
=> misc: fix the secure coding style violations

doc/getting-started/getting-started.rst
"systemd-networkd" is required for acrn-dm to create bridge device.
Document it in GSG before acrn network deb package is ready.
Tracked-On: #7738
Signed-off-by: Qiang Zhang <qiang4.zhang@intel.com>
=> doc: add doc for required systemd services

misc/config_tools/configurator/pyodide/validateScenario.py
fix the typo in validateScenario.py because it leads to
fail to import scenario xml.
=> config_tools: fix the issue that fail to import scenario

devicemodel/hw/pci/virtio/vhost_vsock.c, devicemodel/hw/pci/xhci.c
1. Refine the vhost_vsock_devinit function to return void.
2. Add the endpoint index value check log.
=> Fix vsock and usb memory leak issue

devicemodel/hw/pci/core.c, devicemodel/include/pci_core.h
The patch fix many bugs about the pci msi capabilities.
1. Fix the clear msi mask bit issues.
2. Initialize the offset of pci capabilities this variable will used as
the output of pci_emul_find_capability function.
3. Replace 16-read with 32-read because both mask and pending are 32bit.
4. Add mask and pending element in msicap struct and intialize the struct
value to zero, because we need r/w mask and pending value.
Tracked-On: #7762
=> ACRN: DM: Fix the MSI mask and unmask bugs.

devicemodel/hw/mmio/core.c, devicemodel/hw/platform/tpm/tpm.c, devicemodel/include/mmio_dev.h
There is an secure coding style violations of tmp, this patch add some
NULL check to fix these violations.
=> misc: fix the secure coding style violations of tpm

debian/acrn-board-inspector/acrn-board-inspector
this patch removes VMX and VT-d invalid BIOS setting check in
acrn-board-inspector because the board inspector tool also adds
these checks (please refer to PR #7216) and may it's possible for user
to get the wrong information by these two check in acrn-board-inspector.
so we remove the repeated check in acrn-board-inspector.
=> config_tools: remove VMX and VT-d invalid BIOS check in acrn-board-inspector

misc/config_tools/scenario_config/upgrader.py
Rename "vm_type" from "SOS_VM" to "STANDARD_VM".
=> config_tools: refine vm_type in upgrader

misc/config_tools/configurator/packages/configurator/src/pages/Config.vue, misc/config_tools/scenario_config/jsonschema/converter.py, misc/config_tools/schema/VMtypes.xsd
Currently, if I update Pre-Launched VM type to real-time, select PCPU ID and
enable Real-time vCPU, then we update the name of sevice VM, finally, click the save button.
we will see the type of service vm is updated to RTVM. It is unexpected.
So this patch removes the logic of hiding service VM type, and only allows user
selecting Standard VM type to fix the issue that the service vm type is updated
by UI automatically.
=> config_tools: fix the issue Service VM type is updated by UI automatically

misc/config_tools/schema/checks/rdt_support.xsd
The following issues are witnessed in the RDT assertions in XML schema
rdt_support.xsd:
* Some assertions still check data in vcpu_clos nodes which no longer
exist today because of the refinement of how RDT is configured.
* For those that still hold, acrn:severity and acrn:report-on are not
stated, which prevents the validation activity from reporting failures
against them.
This patch drops the assertions that no longer make sense today and add
ACRN-specific attributes to those that still hold.
=> config_tools: clean up RDT-related assertions

doc/getting-started/getting-started.rst
systemctl won't run as a normal Linux user, requires sudo
Also augment the description information
=> doc: update GSG to use sudo with systemctl command

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/VUART.vue, misc/config_tools/schema/VMtypes.xsd
The current code use the legacy as the default type of communication
vUART, these were only 4 standard vUART ports, others should config by
the /etc/serial.conf, so this patch change the default type to PCI
which could be used without config files.
Signed-off-by: Chenli Wei chenli.wei@linux.intel.com
=> misc: set the communication vUART default type to PCI

misc/config_tools/schema/checks/rdt_support.xsd
The current UI there is an issue which have not sync and save the VMs
to RDT element, these issue will cause the missing of num_pclosids and
the HV can't start.
This patch add assert to check the the missing of CLOS MASK.
The UI issue will be fix by another patch.
=> misc: add assert to check the missing of CLOS MASK

misc/config_tools/schema/checks/cpu_assignment.xsd, misc/config_tools/schema/checks/rdt_support.xsd
This patch fixes the following issues in the existing scenario schema
assertions:
1. The assertion that ensures the existence of pCPU affinity in all
pre- and post-launched VMs does not count the pCPU settings under a
VM properly.
2. The assertion that ensures the presence of CAT settings of a defined
VM is no longer needed as it was originally designed to capture
configurator issues.
=> config-tools: fix assertions against scenario XML

devicemodel/hw/pci/virtio/virtio_net.c
Use the VHOST_NET_F_VIRTIO_NET_HDR in linux system header file,
and set the correct feature bit for Virtio net header.
=> ACRN:DM: Correct vhost_ext_features network bit

devicemodel/hw/pci/virtio/vhost_vsock.c
Free the virtio_vsock struct resource in virtio vsock deinit function
in case memory leak.
Tracked-On: #7759
=> ACRN:DM: Free virtio_vsock struct resource in deinit function

misc/config_tools/configurator/packages/configurator/index.html
Update the text that shows up when loading the ACRN Configurator.
Co-authored-by: David Kinder <david.b.kinder@intel.com>
=> acrn_config: update text when loading the Configurator

misc/config_tools/schema/VMtypes.xsd
With the default population stage today, the `default` and `minOccurs=0`
attributes are typically mutually exclusive:
* A config item with a `default` attribute is guaranteed to exist after
populating default values, making the `minOccurs` attribute meaningless.
* A config item with a `minOccurs=0` attribute allows that item not to be
present even after default values are populated.
This patch removes the `minOccurs=0` attributes from some config items that have
their default values recently added. This allows the default value populator to
fill in those items as expected if a user does not provide them explicitly.
=> config_tools: remove minOccurs from items that have default values

debian/control
Some Debian dependencies are currently missing in the /debian/control file. This change adds these missing dependencies:
Source: acrn-hypervisor
Build-Depends:
python3-requests
python3-tqdm
Package: python3-acrn-board-inspector
Depends:
usbutils
=> Release_3.0:Update Debian control file to add missing dependencies

doc/reference/hardware.rst
Add v3.0 support for TGL Vecow system, starting at the maintenance level
of support.  Transition NUC11TNHi5 from maintenance to community level
support for v3.0.  Maintain all other boards at community level support.
=> doc: update supported hardware doc with TGL Vecow system

misc/config_tools/schema/config.xsd
Following the same logic of commit 59c7077e2 ("config_tools: remove
minOccurs from items that have default values"), this patch marks the
config item os_config, which is a collection of guest OS settings, as
required since subitems of it either have default values or are optional.
=> config_tools: mark os_config item as required in scenario XML

doc/user-guides/acrn-dm-parameters.rst
below parameters are obsolete, reserve the code for potential use
but remove the description in document.
amd_hostbridge
virtio-ipu
virtio-hyper_dmabuf
virtio-audio
=> doc: update some dm parameter

doc/getting-started/getting-started.rst, doc/tutorials/acrn_on_qemu.rst
acrn-kernel tag (for v3.0 hypervisor) should be acrn-v3.0
=> doc: update acrn-kernel repo tag

doc/getting-started/getting-started.rst
You need to be in the acrn-kernel directory in order to ``run make
distclean``
=> doc: fix gsg instructions for building the acrn-kernel

devicemodel/hw/pci/virtio/virtio_console.c
Fix the log format problem in devicemodel when using virtio-console with
'stdio' configuration.
In virtio-console, it will change the STDIO's attributes, and will case
the log message after that not align.
e.g:
for (i=0; i<3; i++)
printf('test\n');
The original output would be like this:
test
test
test
After add 'OPOST' to oflag of STDIO, the output would be like this:
test
test
test
(OPOST - Enable implementation-defined output processing)
Tracked-On: #7860
=> dm: virtio-console: change STDIO BE attribute

misc/config_tools/board_inspector/extractors/95-usb.py
One had escaped from the global cleaning that commit 8b16be918 did.
Tracked-On: #7254
=> Remove "All Rights Reserved" string from license header

doc/getting-started/getting-started.rst
=> doc: elementpath version must be 2.5.0 in the GSG

misc/config_tools/schema/checks/vuart_config.xsd
The current code judges an empty vm_name as a normal vm_name and assert
two endpoints with null name use the same IO port.
There was another which check wether the vm_name of endpoint is null, so
this patch break the assert if get null vm_name.
=> misc: refine the assert of duplicate IO port

misc/config_tools/configurator/packages/vue-json-schema-form/vue3/vue3-core/src/components/Widget.js
Required fields with a checkbox will potentially cause confusion.
So hide the label when display a checkbox.
Tracked-On: #7864
=> config_tools: hide required checkbox's label

misc/config_tools/static_allocators/memory_allocator.py
Fixed a logic error in one line of code in
misc/config_tools/static_allocators/memory_allocator.py.
Tracked-On: #7838
=> config-tools: refine memory allocation for pre-launch vm

hypervisor/arch/x86/guest/lock_instr_emul.c, hypervisor/arch/x86/guest/virq.c, hypervisor/arch/x86/guest/vmexit.c, hypervisor/common/event.c, hypervisor/include/arch/x86/asm/guest/virq.h, hypervisor/include/arch/x86/asm/guest/vm.h, hypervisor/include/common/event.h
Commit d575edf79a9b8dcde16574e28c213be7013470c7 changes the internal
implementation of wait_event and signal_event to use a counter instead
of a boolean value.
The background was:
ACRN utilizes vcpu_make_request and signal_event pair to shoot down
other vcpus and let them wait for signals. vcpu_make_request eventually
leads to target vcpu calling wait_event.
However vcpu_make_request/signal_event pair was not thread-safe,
and concurrent calls of this pair of API could lead to problems.
One such example is the concurrent wbinvd emulation, where vcpus may
concurrently issue vcpu_make_request/signal_event to synchronize wbinvd
emulation.
d575edf commit uses a counter in internal implementation of
wait_event/signal_event to avoid data races.
However by using a counter, the wait/signal pair …
=> hv: Change sched_event back to boolean-based implementation

misc/config_tools/scenario_config/elementpath_overlay.py
This patch adds to the customized function `number-of-clos-id-needed` more
robust checks, which ensures that a given node is a concrete element,
before that function passes the node to `get_policy_list`. This resolves
the incompatibility issue with elementpath 2.5.3 which is reported in v3.0.
Tracked-On: #7867
=> config_tools: resolve incompatibility with elementpath 2.5.3

misc/config_tools/configurator/packages/configurator/src/pages/Config/Board.vue
Placed the "BIOS Revision:" at the top line of BIOS
information, and change the order of the information to have
the board information to the left, and BIOS information to the right.
Tracked-On: #7884
=> config_tool: Move "BIOS Revision" line in Configurator UI

misc/config_tools/board_inspector/board_inspector.py
Use stderror to redirect error message to subprocess.DEVNULL
to hide it when the "update pciids" command is called.
Tracked-On: #7886
=> config-tools: hide the 'update-pciids: download failed' message

hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/tsc.c, hypervisor/boot/acpi_base.c, hypervisor/boot/include/acpi.h, hypervisor/include/arch/x86/asm/tsc.h
On some platforms CPUID.0x15:ECX is zero and CPUID.0x16 can
only return the TSC frequency in MHZ which is not accurate.
For example the TSC frequency obtained by CPUID.0x16 is 2300
MHZ and the TSC frequency calibrated by HPET is 2303.998 MHZ
which is much closer to the actual TSC frequency 2304.000 MHZ.
This patch adds the support of using HPET to calibrate TSC
when HPET is available and CPUID.0x15:ECX is zero.
v3->v4:
- move calc_tsc_by_hpet into hpet_calibrate_tsc
v2->v3:
- remove the NULL check in hpet_init
- remove ""& 0xFFFFFFFFU" in tsc_read_hpet
- add comment for the counter wrap in the low 32 bits in
calc_tsc_by_hpet
- use a dedicated function for hpet_calibrate_tsc
v1->v2:
- change native_calibrate_tsc_cpuid_0x15/0x16 to
native_calculate_tsc_cpuid_0x15/0x16
- move hpet_init to …
=> hv: tsc: calibrate TSC by HPET

debian/control
Tracked-On:https://github.com/projectacrn/acrn-hypervisor/issues/6688
Some Debian dependencies are currently missing in the `/debian/control` file.  This change adds these missing dependencies:
**Source: acrn-hypervisor**
**Build-Depends:**
- python3-requests
- python3-tqdm
**Package: python3-acrn-board-inspector**
**Depends:**
- usbutils
Note: These changes should be part of the ACRN 3.0 release. Should I open a similar PR to the `release_3.0` branch?
=> Update Debian control file to add missing dependencies.

misc/config_tools/board_inspector/extractors/40-acpi-tables.py
Fixed the problem of exception handling of the
incoming type error in reading GSI number method
in 40-acpi-tables.py line 37 when dmesg command
line is too long.
Tracked-On: 7906
=> config-tools: fix board inspector crashed error

hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/cpu_caps.c, hypervisor/arch/x86/security.c, hypervisor/include/arch/x86/asm/cpu_caps.h, hypervisor/include/arch/x86/asm/cpufeatures.h, hypervisor/include/arch/x86/asm/msr.h, hypervisor/include/arch/x86/asm/security.h
For platform that supports RRSBA (Restricted Return Stack Buffer
Alternate), using retpoline may not be sufficient to guard against branch
history injection or intra-mode branch target injection. RRSBA must
be disabled to prevent CPUs from using alternate predictors for RETs.
Quoting Intel CVE-2022-0001/CVE-2022-0002:
Where software is using retpoline as a mitigation for BHI or intra-mode BTI,
and the processor both enumerates RRSBA and enumerates RRSBA_DIS controls,
it should disable this behavior.
...
Software using retpoline as a mitigation for BHI or intra-mode BTI should use
these new indirect predictor controls to disable alternate predictors for RETs.
See: https://www.intel.com/content/www/us/en/developer/articles/technical/ …
=> [release_3.0] hv: cve hotfix: Disable RRSBA on platform using retpoline

misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
add two spacings in alert sentence.
Tracked-On: #7915
Reviewed-by:Junjie Mao <junjie.mao@intel.com>
=> config_tools: add two spaces for error messgae.

hypervisor/arch/x86/guest/vmexit.c, hypervisor/common/hv_main.c, hypervisor/debug/shell.c, hypervisor/debug/shell_priv.h, hypervisor/include/arch/x86/asm/guest/vcpu.h, hypervisor/include/arch/x86/asm/guest/vmexit.h, hypervisor/include/debug/profiling.h, hypervisor/release/profiling.c
this feature is used to sample vmexit data per virtual CPU of VM,
command used in HV console as following:
1. vmexit clear : to clear current vmexit buffer
2. vmexit [vm_id] : output vmexit info per-vCPU of one or all VMs
3. vmexit enable | disable, by default enabled
Tracked-On: #5232
=> [ACRN3.0-branch]hv: shell: add cmd to sample vmexit data per-vCPU

hypervisor/arch/x86/guest/hyperv.c
When LAPIC timer is working in oneshot or periodic mode, OS uses
initial counter register/current counter register to program
a timer. Both initial counter and current counter depend on the
LAPIC frequency. ACRN emulated vLAPIC timer based on the TSC.
vLAPIC freq is the same as TSC freq.
Tracked-On: #7876
=> hv: tlfs: fix the incorrect vLAPIC freq MSR

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/Virtio/Console.vue, misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/cpu_affinity.vue
let minus icons in front of plus icons in those views below: Virtio input device, Virtio network device, Virtio console device, CPU affinity.
Tracked-On: projectacrn#7917 
=> config_tools: order of plus and minus icons is inconsistent

hypervisor/dm/vpci/vpci.c
Validate inputs explicitly instead of using ASSERT, which
works only for debug build.
Tracked-On: #7902
=> hv: validate inputs in vpci_mmio_cfg_access

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/CAT.vue
In the cache widget, there are instructions: "Drag the ends of the boxes to cover the cache chunks you want to allocate to specific VMs. If you have a real-time VM, ensure its cache chunks do not overlap with any other VM's cache chunks."
Tracked-On: #7921
=> config_tool: Instruction missing for L2-only users

devicemodel/hw/mmio/core.c, devicemodel/hw/pci/virtio/virtio_net.c, devicemodel/hw/platform/tpm/tpm.c, devicemodel/include/mmio_dev.h
Merge from release_3.0
There was some secure coding style violations of virtio net and tmp,
this patch add some NULL check to fix these violations.
=> dm: fix the secure coding style violations

misc/config_tools/schema/checks/pci_config.xsd, misc/config_tools/schema/datachecks.xsd
The current ACRN-Configurator allow user add duplicate PCI devices to
passthrough which it is not correct.
This patch add an assert to check the duplicate of PCI devices.
=> misc: add assert to check the duplicate devices

misc/sample_application/Makefile, misc/sample_application/rtvm/Makefile, misc/sample_application/uservm/Makefile
Add the Makefile in the SampleApplication root directory. User
don't need to separate build the userapp and rtapp, just need make
once at the SampleApplication root directory.
Tracked-On #7820
=> SampleApplication: Add Makefile for the entire SampleApplication

hypervisor/common/sched_bvt.c, hypervisor/include/common/schedule.h
BVT schedule rule:
When a new thread is wakeup and added to runqueue, it will get the
smallest avt (svt) from runqueue to initiate its avt. If the svt is
smaller than it's avt, it will keep the original avt. With the svt, it
can prevent a thread from claiming an excessive share of CPU after
sleepting for a long time.
For the reboot issue, when the VM is reboot, it means a new vcpu thread
is wakeup, but at this time, the Service VM's vcpu thread is blocked,
and removed from the runqueue, and the runqueue is empty, so the svt is
0. The new vcpu thread will get avt=0. avt=0 means very high priority,
and can run for a very long time until it catch up with other thread's
avt in runqueue.
At this time, when Service VM's vcpu thread wakeup, it will check the
svt, but the svt is very small, so …
=> hv: sched: fix bug when reboot vm

misc/config_tools/acpi_gen/acpi_const.py, misc/config_tools/acpi_gen/asl_gen.py, misc/config_tools/acpi_gen/bin_gen.py, misc/config_tools/board_inspector/acpiparser/rdt.py, misc/config_tools/board_inspector/acpiparser/rtct.py, misc/config_tools/board_inspector/cpuparser/msr.py, misc/config_tools/board_inspector/cpuparser/platformbase.py, misc/config_tools/board_inspector/extractors/20-cache.py, misc/config_tools/board_inspector/extractors/40-acpi-tables.py, misc/config_tools/board_inspector/legacy/acpi.py, misc/config_tools/board_inspector/schema/checks/platform_capabilities.xsd, misc/config_tools/static_allocators/memory_allocator.py
This PR resolves the following two issues.
First, today ACRN build system reuses the physical RTCT as the vRTCT for a pre-launched RT VM which has access to software SRAM. This results in two issues:
1. Users have to manually copy the physical RTCT to their build machine.
That violates ACRN development framework which defines the board XML
as the only file users need to copy.
2. All information in the physical RTCT will be visible to that
pre-launched RT VM, including L2 software SRAM it does not have access
to, way masks of GT even when graphics is not passed through to it and
the addresses of CRL binary and TCC error log.
To resolve the developer experience and functionality concerns above, this patch series puts information extracted from RTCT to the board XML file and generates a …
=> Generate vRTCT for pre-launched RT VMs and guess presence of L3 CAT in the board inspector

misc/sample_application/uservm/histapp.py
Correct the unit of sample-application result, which should be us(microseconds).
Tracked-On #7820
Signed-off-by: Zhang Wei <wei6.zhang@linux.intel.com>
=> SampleApplication: Change the unit of result

doc/release_notes/release_notes_3.0.1.rst
Clarify description of CVE fix (only impacts ACRN implementation on
Alder Lake platforms), and improve description of the ACRN shell's new
vmexit command.
=> doc: update 3.0.1 release notes

misc/sample_application/image_builder/README.rst, misc/sample_application/image_builder/configRTcores.sh, misc/sample_application/image_builder/create_image.sh, misc/sample_application/image_builder/logger.sh, misc/sample_application/image_builder/setup_hmi_vm.sh, misc/sample_application/image_builder/setup_rt_vm.sh
Creating VM images is always a pain to users, and it is especially the case
for those who want to set up the ACRN sample application which needs two
different VM images, one with graphical desktop and the other optimized for
real-time.
This patch introduces the so-called "image builder" utility which is a set
of scripts that can automate the creation of those VM images. The scripts
will take care of:
- Forking image files based on Ubuntu cloud images and enlarge the root
file system per needs.
- Setting up users and passwords.
- Installing necessary packages to run either the graphical desktop or
real-time applications.
- Specific to the RT VM image, disabling services and tweaking kernel
command line for optimized real-time performance.
- Copying the sample applications into the images …
=> sample_app: Add scripts to create RT and HMI VM images

misc/config_tools/schema/types.xsd
add escape charater to fix vBDF pattern match any character issue
for vUART and ivshmem.
Tracked-On: #7925
=> config_tools: fix vBDF schema pattern issue

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/CAT.vue
v1-->v2:
1. instruction displayed regardless of if L3 or L2 cache were available, now it displayed instructions accordingly no matter how many caches
2. let instructions displayed only once above the topmost CAT configuration table
Tracked-On: #7921
=> [config_tool][patch v2] Cache widget: Instructions missing for L2-only users

doc/getting-started/getting-started.rst
In the "Enable ACRN Secure Boot With EFI-Stub" guide, to build EFI-Stub
smoothly, the installation of "gnu-efi" package is added to GSG.
Tracked-On: #7935
=> doc: fix Build EFI-Stub fail problem

doc/getting-started/getting-started.rst
Remind readers that internet access from a corporate network typically
requires configuring proxy information.
=> doc: add proxy note to GSG

doc/glossary.rst, misc/config_tools/schema/config.xsd
Updated the description of Security VM Features per review comments, and
made the option visible (again) in the configurator as an advanced
hypervisor option.
Created a new glossary entry for "Security VM", referenced by this new
description and tooltip.
Tweak wording of virtio console and input device descriptions.
Tracked-On: #7968
=> doc: update Security VM Features config option

misc/sample_application/image_builder/create_image.sh, misc/sample_application/image_builder/setup_hmi_vm.sh
Add the proxy config file for the HMI VM images, in case install
the packages failed.
=> SampleApplication: Add the proxy setting for HMI

devicemodel/core/iothread.c
dm: bugfix for iothread
As the type of pthread_t is unsigned long, so the init value for it
should not be '-1'. When the tid is '-1', it will continue to call
pthread_kill/pthread_join. This is incorrect.
Tracked-On: #7960
=> dm: bugfix for iothread

misc/config_tools/schema/checks/vbdf_assignment.xsd
The current ACRN-Configurator just check the conflict of user setting.
have not check the conflict with native PCI device's bdf.
This patch add an assert to check the above conflict.
=> misc: add assert to check the vBDF conflict

misc/config_tools/static_allocators/memory_allocator.py
Fixed the problem that acrn can still build normally
when the memory addresses of HV and VM conflict, which
causes the hypervisor to hang.
At the same time, defined a class to process memory to
obtain and check the available memory range.
Memory range obtain and check related functions are
defined as class methods.
Tracked-On: #7913
=> config-tools: solve hv and vm memory address conflict

doc/getting-started/getting-started.rst
The new acrn-kernel for v3.1 expects gelf.h that's installed with the libelf-dev
package that's not listed as a dependency in the GSG.  Without this
package, building acrn-kernel fails.
=> doc: add libelf-dev dependency to GSG

doc/getting-started/getting-started.rst
Edits preparing for using a requirements.txt introduced an error in the
step order (using a directory before it was created).
=> doc: fix order of steps in GSG setup

devicemodel/hw/vdisplay_sdl.c
ACRN uses the DMABuf to render the framebuffer submitted from guest vm.
But the DMABuf doesn't work when guest_vm is booted with multi-display.
This patch set tries to fix the display issues when multi-display is used.
This issue is related with the  limitation in libSDL. One small texture(32x32) is added to WA the issue and
helps to assure that the libSDL can configure its internal state correctly.
=> Acrn waag multi

doc/getting-started/getting-started.rst, doc/tutorials/acrn_configurator_tool.rst, misc/config_tools/requirements.txt
Moved requirements.txt form misc/config_tools/configurator
directory to misc/config_tools directory and modified
relevant python package installing steps in GSG.
Tracked-On: #7975
=> config-tools: modified requirements.txt and update GSG

misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
the focus  change to that new VM on the Basic tab when the new VM  added
Tracked-On: #7914
=> Focus change to new VM when added

misc/config_tools/schema/config.xsd
The configurator can't process :term: glossary references, so remove it.
=> doc: remove use of :term: role in tooltip

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/cpu_affinity.vue
add tooltip to explain "Real-time vCPU"
use the one generated from the XSD files to generate tooltip infomation.
Tracked-On: #8000
=> [config_tool] Real time vCPU checkbox is confusing to users

doc/getting-started/getting-started.rst
GSG was recently updated to use a requirements.txt for python
dependencies, but that file doesn't exist in the repo at the v3.0 tag
the instructions say to use.  Revert to not use a requirements.txt until
we get this figured out.
=> doc: revert to not using requirements.txt in the GSG

doc/getting-started/sample-app.rst
After review with engineering, we added material for showing what a
successful hmi_vm.img build ending looks like (and a hint of what to do
if it looks like the build failed.  Also added using a dhclient commmand
to the instructions in case the HMI_VM didn't get an IP address.
=> doc: update sample app user guide

doc/getting-started/getting-started.rst
The Getting Started Guide specifies that we need to install the Python packages lxml, xmlschema, and defusedxml.
However, a make clean involves the execution of the Python script manager.py. This script imports the package requests.py, which might not be installed if the developer follows the Getting Started Guide.
Add requests follow this command in GSG.
sudo pip3 install "elementpath==2.5.0" lxml "xmlschema==1.9.2" defusedxml tqdm requests
[External_System_ID] ACRN-9144
Tracked-On: #8029
Signed-off-by: Zhang Wei <wei6.zhang@intel.com>
=> doc: Add a python package in GSG

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/VUART.vue
when the VM of a vUART endpoint changes the configurator can clear its corresponding I/O port or BDF settings automatically
Tracked-On: #8033
=> [config_tool] vUART widget address for pre-launched VM doesn't update

misc/config_tools/schema/checks/cpu_assignment.xsd
The current ACRN Configurator have no warning when the user set CPU zero
to RTVM.
This patch add an assert to check the above.
=> misc: add assert to check the RTVM CPU affinity

misc/config_tools/schema/config.xsd
The current ACRN Configurator show the XML name instead of DX-friendly
name when user delete the default value of some numeric field.
This patch add some "acrn:errormsg" which will show the DX-friendly name
to fix the above issue.
=> misc: refine the ACRN Configurator error message

doc/getting-started/getting-started.rst
Make the GSG more consistent with the sample app doc and show how to use
scp to transfer files between the dev and target machines.
Also add a mention of the sample app guide at the end of the GSG.
=> doc: update GSG to include scp instructions

doc/getting-started/sample-app.rst
Previously the sample apps needed to be run as root, but with a recent
update they could be run as a normal (acrn) user.  Update the sample app
to use sudo for running these sample app components in case the user
doesn't login as root.  Also, split running the background app and the
foreground app into two commands to eliminate some confusion.
=> doc: update sample app doc to use sudo

doc/getting-started/getting-started.rst, doc/getting-started/sample-app.rst
* Fix missing /build folder in copy command in GSG
* Mention USB stick needs formatting for large files when used for the
sample app (but we'll put that into GSG too).
=> doc: update GSG and sample app guide

misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
1.add condition to recalculate maxVMID from saved VM name, so that vm name could be update correctly
if there is VM names "service VM" "real-time VM" "VM11", the new VM will be named "VM12"
2. support calculate VM name when changing any VM name.
if there is VM names "service VM" "real-time VM" , the new VM will be named "VM2",count from 0.
Tracked-On: #8046 
Signed-off-by: Chuang-Ke [chuangx.ke@intel.com](mailto:chuangx.ke@intel.com)
Reviewed-by: Junjie Mao [junjie.mao@intel.com](mailto:junjie.mao@intel.com)
=> [config_tool] Configurator creates duplicate VM name

misc/services/life_mngr/life_mngr_win.c
Permit life_mngr in windows to assign the VM name which configure
in scenario XML.
Tracked-On: #8051
=> life_mngr: permit life_mngr in windows to assign VM name

misc/config_tools/schema/checks/vm_memory.xsd, misc/config_tools/schema/datachecks.xsd
The current code does not detect the memory applied by all VMs, if it
exceeds the native memory, there will be an allocate failed and these
VMs can't run.
Reviewed-by: Junjie Mao junjie.mao@intel.com
=> misc: add assert to check the total memory size of User VMs

misc/config_tools/scenario_config/upgrader.py
The current generic data moving policy in the upgrader do not work well
with complex nodes having multiple-occurred descendants. That causes the
lost of cache allocation policies in scenario XMLs when upgrading a v3.0
scenario XML to the coming v3.1.
This patch adds another generic-purpose mover that simply copies a whole
subtree unchanged.
Most nodes of this kind are handled by special movers as their formats
changed dramatically in v3.0, which is why that issue is not identified
earlier.
=> config_tools/upgrader: keep cache allocation policies properly

misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
fix CAT widget data doesn't refresh after import another scenario
the focus will go to "Basic Parameters" tab after import a scenario everytime. so that data could be refresh.
Tracked-On: #8068
=> [config_tool] Imported scenarios not populating CAT widget

doc/getting-started/getting-started.rst
missing a trailing backslash on a command continuation
=> doc: fix typo in GSG

misc/config_tools/schema/config.xsd
Disable UC lock detection(UC_LOCK_DETECTION_ENABLED) by default.
Tracked-On: #8018
=> config_tools: UC_LOCK_DETECTION_ENABLED default value

misc/config_tools/configurator/packages/configurator/src/pyodide.js, misc/config_tools/configurator/packages/configurator/thirdLib/library.json
The current elementpath of ACRN Configurator use 2.4.0 which can's
support some new python interface, this patch update it to 2.5.0 to
fix the above issue.
=> misc: update elementpath to 2.5.0

misc/config_tools/launch_config/launch_script_template.sh
Change ">>/dev/stderr" to ">&2"
Although it seems that the two have the same effects, the way they work is different.
The ">/dev/stderr" does an open(), it goes to the filesystem look for that file, opens and write to it. The second way, ">&2",just uses file descriptor 2.
The acrnd deamon outputs the stdin and stderr messages to journal through socket. And the socket cannot be manipulated with open methods.So acrnd cannot open the "/dev/stderr" which has redirected to a socket.
For successfully excuting the create_tap function in acrnd deamon, We change ">> /dev/stderr" to ">&2".
For the remain ">> /dev/stderr", they all follow the echo command and will not harm the launchscript functionality.
Tracked-On: #8066
Signed-off-by: Zhang Wei wei6.zhang@intel.com
Signed-off-by: Zhang Wei …
=> config_tool: modify the launchscript template

misc/config_tools/library/rdt.py, misc/config_tools/static_allocators/clos.py, misc/config_tools/static_allocators/cpu_affinity.py
The current code sort cpu list by string order, this is an issue when
we want to assign more then 10 vCPUs for some VM.
So this patch rewrite the sort of these list, now the cpu list order
by int type.
=> misc: refine the vCPU sort for cpu_affinity and CAT

misc/config_tools/configurator/packages/configurator/src/lib/acrn.ts
Before, the logic automatically sets RDT as y if CDP is y. when the user imports a scenario, the CDP is y and RDT is y, the view will set CDP as y and RDT as y.
After fixing, the logic won't set RDT as y if CDP is y, which means the RDT won't be changed no matter if CDP is y or n(only when import scenario) .
Tracked-On: #8087
=> config_tools: enable RDT and CDP after launch scenario

doc/scripts/changed-docs.awk, doc/scripts/changed-docs.sh
changed-docs.sh (and the accompanying awk script) shows docs changed
between a previous release branch and the current master branch, in a format that
can be used for the releae notes (a list of :ref: items).
=> doc: add a doc helper script

misc/config_tools/board_config/board_c.py, misc/config_tools/schema/VMtypes.xsd, misc/config_tools/schema/checks/vbdf_assignment.xsd, misc/config_tools/schema/config.xsd, misc/config_tools/xforms/lib.xsl
Currently we have to use additional patch to change config tool python
code to enable P2SB hidden device.
This patch have add an element, user could config the P2SB device in
the scenario XML.
=> misc: add config for P2SB

misc/config_tools/schema/VMtypes.xsd, misc/config_tools/schema/config.xsd, misc/config_tools/schema/types.xsd
The configurator build requires the released documentation to be
published before it normally would so it can resolve :ref: links in
tooltips. Move these :ref: links into a second xs:documentation tag so
the reference will appear in the option documentation but not in the
tooltip (and break this premature dependency in the configurator build).
Tracked-On: #8098
=> doc: remove use of :ref: in tooltips

misc/config_tools/board_inspector/extractors/20-cache.py
Commit 2a8b80d0c ("config_tools: board_inspector: guess L3 CAT parameters
if not reported via CPUID") refactors the implementation of `--add-llc-cat`
option of the board inspector but does not update the referenced XML nodes
properly. This patch fixes a using-undefined-variable issue introduced by
that commit.
Tracked-On: #7948
=> config_tools: fix a typo in cache info extractor

misc/config_tools/scenario_config/jsonschema/converter.py
With multiple xs:documentation nodes under the same xs:annotation, xs2js
will convert the XML into a dict where the key `xs:documentation` maps to a
list rather than a string. This patch enhances the converter.py to handle
such case properly.
Tracked-On: #8098
=> config_tools: handle multiple xs:documentation properly

misc/config_tools/schema/checks/rdt_support.xsd
The current code have not check whether all cache region has "Code and
Data Prioritization", it's an issue for some platform which have only
L2 or L3 "Code and Data Prioritization" capability.
This patch add assertion to check whether all L2, L3 cache could be set
CDP_ENABLE.
=> misc: add assertion to check the CDP Enable

misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
improve the translateError function by adding a condition: if there are errors describing the same error and same paths, remove the repeat one.
Tracked-On: #8117
=> [config_tool] Duplicate error for vUART connection

misc/config_tools/static_allocators/memory_allocator.py
Now, if you use a memory address below 4G, there will be a warning, but the build process of the hypervisor will not be interrupted.
=> config-tools: Fix error reporting for memory addresses below 4G

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/VUART.vue
the configurator can clear its corresponding I/O port or BDF settings automatically when the VM of a vUART endpoint changes 
v1-->v2: support the result working on multiple VUART Connections
Tracked-On: #8033
=> [config_tool]  v2 UART widget address for pre-launched VM doesn't update

doc/user-guides/kernel-parameters.rst
to avoid misleading for users, delete the description about hypervisor relocation disabling, since it is not officially supported by ACRN configurator now.
Tracked-On: #8133
=> [doc]remove some decription about hvlog

misc/config_tools/configurator/README.md, misc/config_tools/configurator/packages/configurator/src/pages/Config/Scenario/NewScenario.vue
1. In the title "Create a new Scenario", capitalize the "N" in "new".
2. Fix the file path to the installer.
Tracked-On: #8137
=> config-tools: fix typos of UI and README

misc/config_tools/schema/checks/vbdf_assignment.xsd
The BDF of user setting should skip the slot '00', '01', '02', '1f', all these slots should select one of the 03~1e.
This patch add an assertion to check the above policy.
=> misc: add assertion to check the BDF value

doc/tutorials/vuart_configuration.rst
The ACRN Configurator release 3.1 following the release 3.0 logic, so the COM2 still used for S5.
This patch modify the "The release v3.0 ACRN Configurator assigns… …" to "The release v3.0+ ACRN Configurator assigns… …" and refine a typo issue.
=> doc: update vUART tutorials

misc/config_tools/configurator/packages/configurator/src/pages/Config.vue, misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm.vue
Reset the real_time_vcpu to 'n' if the VM is not a real-time VM.
Tracked-On: #8145
=> config-tools: diable real_time_vcpu for non real-time VM

devicemodel/hw/pci/core.c, devicemodel/hw/pci/passthrough.c, devicemodel/include/passthru.h, devicemodel/include/pci_core.h, hypervisor/dm/vpci/vpci.c, hypervisor/include/hw/pci.h
PCI ROM is the firmware specific to PCI device and it is provided by
the device vendor. The PCI rom resides in 0x30 offset of PCI config space.
This can be used to check whether the PCI rom exists. And when it exists,
it can load the firmware from the addr that is obtained from ROM bar addr.
This patch set tries to add the support of PCI rom bar so that the rom file
can be loaded for the passthrough device. Based on the PCI rom, it is convenient
to add the GPU GOP for OVMF firmward instead of integrating the GPU Gop into
the OVMF.
The PCI rom bar is handled in DM. The minor change is in HV so that
it can forward the access of ROM_bar reg to DM. Now this is handled only
when the ACRN_PTDEV_QUIRK_ASSIGN is specified for the passthru device.
It is noted that the rom_file has no dependency on …
=> Add the support of PCI rom for passthru GPU device

hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/guest/vcpu.c, hypervisor/arch/x86/guest/virq.c, hypervisor/arch/x86/guest/vm.c, hypervisor/arch/x86/guest/vmcs.c, hypervisor/arch/x86/lapic.c, hypervisor/arch/x86/notify.c, hypervisor/common/sched_bvt.c, hypervisor/common/sched_iorr.c, hypervisor/common/schedule.c, hypervisor/debug/console.c, hypervisor/debug/shell.c, hypervisor/include/arch/x86/asm/guest/vcpu.h, hypervisor/include/arch/x86/asm/lapic.h, hypervisor/include/arch/x86/asm/notify.h, hypervisor/include/arch/x86/asm/per_cpu.h, hypervisor/include/common/schedule.h, hypervisor/include/debug/console.h, hypervisor/release/console.c
hv: use kick-mode in per-cpu to control kick pCPU
hv: add param to control INIT used to kick pCPU
hv: improve smp call to support debugging RTVM
Tracked-On: #8207
=> improve kick-pcpu with INIT/IPI and SMP call 

misc/config_tools/schema/types.xsd
Some member of CACHE_REGION have no documentation element, this cause some issue when we generate documentation for user.
This patch add some documentation to fix the above issue.
=> misc: add documentation element for CACHE_REGION

misc/packaging/gen_acrn_deb.py
Added python3-tqdm depend in gen_acrn_deb.py
Tracked-On: #8155
=> config-tools: Missing tqdm python package in board_inspector.deb

misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
The cpu_affinity is null when creating a new scenario. Do not update the pcpu properties if the cpu_affinity is null.
Tracked-On: #8145
=> config-tools: check if the cpu_affinity is null

debian/grub/25_linux_acrn, hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/pm.c, hypervisor/include/arch/x86/asm/board.h, hypervisor/include/arch/x86/asm/host_pm.h, hypervisor/include/public/acrn_common.h, misc/config_tools/board_config/board_c.py, misc/config_tools/board_inspector/cpuparser/cpuids.py, misc/config_tools/board_inspector/cpuparser/msr.py, misc/config_tools/board_inspector/extractors/10-processors.py, misc/config_tools/library/board_cfg_lib.py, misc/config_tools/schema/config.xsd, misc/config_tools/schema/types.xsd, misc/config_tools/static_allocators/cpu_freq.py, misc/packaging/acrn-hypervisor.postinst, misc/packaging/gen_acrn_deb.py
1. Background:
Customers of the industry segment are asking for more computation power
in WaaG. Currently there are two ways to manage CPU frequency when
running ACRN:
- Pass through HWP/p-state to guest. This doesn't work for Windows
because Windows running in a VM relies on Hyper-V to manage the
frequency. So it does not load frequency driver.
- Or rely on service VM's Linux HWP driver, which can set the
frequency policy to hardware autonomous selection. But it does not
work either because when a CPU is set to offline, that driver
sets HWP autonomous frequency selection range to minimal. Also we
don't want the RTVM's frequency been changed by autonomous selection.
So we have to let ACRN manage CPU frequency.
2. The design:
The design of ACRN CPU performance management is to let hardware …
=> add ACRN CPU performance management

misc/config_tools/board_config/board_c.py
This patch remove a invalid variable from hidden_pdev_list to fix an build issue.
=> misc: modify hidden_pdev_list to fix build issue

misc/config_tools/configurator/packages/configurator/src/lib/acrn.ts, misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/CAT.vue, misc/config_tools/scenario_config/elementpath_overlay.py, misc/config_tools/schema/checks/rdt_support.xsd, misc/config_tools/xforms/config_common.xsl
Today users are able to tweak whether the hypervisor includes support to software SRAM (SSRAM). This, however, gives rise to potential functional incorrectness when the hypervisor is not built with such support but a service VM attempts to assign SSRAM to a post-launched VM (which is possible as the service VM can still see the SSRAM-related ACPI tables). In such cases the SSRAM assigned to a post-launched VM is not properly initialized and thus not locked in cache.
As makes little sense for a user to configure the SSRAM support in the hypervisor in a different way as the presence of SSRAM on hardware, this patch removes the "SSRAM support" option from the configurator. The config tools will now automatically enable the SSRAM support if the hardware supports the feature and disable that …
=> config_tools: determine SSRAM_ENABLED automatically

misc/config_tools/board_inspector/extractors/10-processors.py, misc/config_tools/board_inspector/extractors/60-pci.py, misc/config_tools/board_inspector/pcieparser/__init__.py, misc/config_tools/board_inspector/pcieparser/header.py
This PR fixes the following crashes of the board inspector when:
* There is a PCIe function with a header type other than 0 or 1.
* The hardware does not support HWP.
=> Fixes to crashes of the board inspector

doc/.known-issues/doc/pdf.conf, doc/Makefile, doc/acrn.doxyfile, doc/custom-doxygen/mainpage.md
These changes are compatible with both the Ubuntu 20.04 and 22.04 documentation build processes.
=> doc: prep for Ubuntu 22.04

doc/.known-issues/doc/sphinx.conf, doc/conf.py, doc/scripts/requirements.txt
Update known-issues processing and tweak conf.py and requirements.txt (for PyPI package versions) to handle a broader version of doc-generation tools (sphinx, breathe, docutils, etc.).  This should let us move to Ubuntu 22.04 while maintaining doc-build compatibility with older tool versions available with Ubuntu 20.04 (doxygen in particular).
=> doc: update doc build tools for Ubuntu 22.04 and Sphinx

doc/developer-guides/hld/hld-security.rst, doc/developer-guides/hld/hld-trace-log.rst, doc/developer-guides/hld/hv-cpu-virt.rst, doc/release_notes/release_notes_3.0.rst, doc/tutorials/docbuild.rst
In markdown a single backtick around a term says to format it as fixed-width text, e.g., `fixed-width text`.  The rst language uses double back-ticks, e.g., ``fixed-width text``.
Fix misuses of single backtick in our documentation.
=> doc: fix incorrect single back-tick usage

debian/rules
The debian build rule of calculating method for post launch vm ids when generating launch scripts should not be reading //vm/@id in scenario xmls directly but reading //vm/@id in scenario xml and then plus vm id for service vm.
Since the objective here is to generate the launch scripts for all VMs, change the debian rule to invoking the launch_cfg_gen.py script without parameter user_vmid when there are post launch vms to achieve the objective.
Tracked-On: #8245
Signed-off-by: szhen11 <shuang.zheng@intel.com>
=> config_tools: fix the issue for debuild on tgl-rvp with hybrid scenario

debian/rules
This patch series fixes issues with configuration file detection when using ACRN_BOARDLIST, ACRN_SCENARIOLIST and CONFIGDIRS other than the default settings in debian/rules, e.g. using
`debuild -eACRN_BOARDLIST= -eACRN_SCENARIOLIST= -eCONFIGDIRS=<custom config path> -- binary`
to build all custom board/scenario configurations from  <custom config path>.
Remember: `-eACRN_BOARDLIST=` means detecting all available boards, whereas not setting `ACRN_BOARDLIST` means using the debian/rules default settings. The same applies to `ACRN_SCENARIOLIST`.
=> Issue8246 debianization improvement

hypervisor/dm/vpci/vmsix.c, hypervisor/hw/pci.c, hypervisor/include/arch/x86/asm/io.h
Now ACRN would traps MSI-X Table Structure access and does MSI-X interrupt
remapping for pass-thru PCIe devices. ACRN does this trap by unmmapping the
address ranges where the MSI-X Table Structure locates in granularity of 4K
pages. So there may have other registers (non-MSI-X structures) in these
trapped pages
However, the guest may access these registers (non-MSI-X structures) in these
trapped pages, which needs to be forwarded to the physical device. This patch
forwards the access to real hardware for pass-thru PCIe devices.
Tracked-On: #8255
=> vpci: fix pass-thru pcie device may access MSI-X BAR

Makefile, hypervisor/Makefile, hypervisor/scripts/genconf.sh, hypervisor/scripts/makefile/config.mk, misc/hv_prebuild/Makefile
Dependencies among targets in Makefiles today have the following issues:
1. Phony targets are used for intermediate files. That causes unnecessary
rebuilds of almost all sources even no source file is changed. As an
example, invoke `make hypervisor-install` after `make hypervisor` will
rebuild the hypervisor before the installation steps are carried out.
2. Dependencies on validated XMLs are not stated explicitly. That causes
random error messages (mostly Python stack traces) to be shown when
invalid board or scenario XML is given in addition to the validation
errors, which confuses users.
3. Copied XMLs do not explicitly depend on user-given ones (when user
specifies them) though they actually are. That prevents users from
updating the board and/or scenario XMLs for an existing build …
=> Makefile: sort out dependencies among targets

doc/developer-guides/hld/hld-devicemodel.rst, doc/developer-guides/hld/hv-dev-passthrough.rst, doc/developer-guides/hld/hv-io-emulation.rst, doc/user-guides/acrn-dm-parameters.rst
fixing some grammar issues in documentation
=> doc: grammar fixes

hypervisor/dm/vpci/vdev.c, hypervisor/include/dm/vpci.h
The current code would write 'BAR address & size_maks' into PCIe virtual BAR before updating the virtual BAR's base address when guest writing a PCIe device's BAR. If the size of a PCIe device's BAR is larger than 4G, the low 32 bits size_mask for this 64 bits BAR is zero. When ACRN updating the virtual BAR's base address, the low 32 bits sizing information would be lost.
This patch saves whether a BAR writing is sizing or not before updating the virtual BAR's base address.
Tracked-On: #8267
=> hv: vPCI: fix large bar base update

doc/scripts/configdoc.xsl
The schema of scenario XMLs uses both named and anonymous complex types, but the configdoc.xsl today only works for named complex types. That causes improper rendering of config items related to virtio devices (whose schema uses anonymous types) as well as wrong applicable VM icons which states that virtio devices apply to not only post-launched VMs but also pre-launched and service VM, which does not make sense.
This patch improves configdoc.xsl by adding support of anonymous complex types so that they are walked through in the same way as named ones.
=> doc: handle anonymous complex types in XML schema

misc/config_tools/configurator/pyodide/populateDefaultValues.py
Clean up vm_name of vuart and/or VM_NAME of IVSHMEM which is not defined in //vm/name while loading scenario XML.
Rviewed-by: Junjie Mao <junjie.mao@intel.com>
Tracked-On: #8270
=> config-tools: clean up the vm names which do not exist

debian/debian_build.sh, debian/rules
$ debian/debian_build.sh -h
Usage: debian/debian_build.sh [--board_list ACRN_BOARDLIST] [--scenario_list ACRN_SCENARIOLIST] [--config_path CONFIGDIRS] [--release n|y] [acrn | board_inspector | clean] Optional arguments:
-h, --help           show this help message and exit
-b, --board_list     list the boards to build, seperated by blank; build all scanned boards in the config path if specified as ""; build the default boards in debian rules if not specified
-s, --scenario_list  list the scenarios to build, seperated by blank; build all scanned scenarios in the config path if specified as ""; build the default scenarios in debian rules if not specified
-c, --config_path    specify the config path for the board and scenario configuration files, default use misc/config_tools/data if not …
=> debian: create script to build acrn with debuild

debian/acrn-hypervisor.install, debian/rules
To be able to to conditionally add a launch script directory for acrn-hypervisor package, the debian/acrn-hypervisor.install file must be created dynamically. If there are only configurations (e.g. partitioned scenarios) that do not need any launch scripts, we have to omit the launch script directory entry in debian/acrn-hypervisor.install.
Tracked-On: #8263
=> debian/rules: Dynamically generate acrn-hypervisor.install

devicemodel/hw/pci/virtio/virtio_gpu.c, devicemodel/hw/vga.c
To avoid assertions in devicemodel, remove all the assert() in vga.c, use print error message to check errors.
Tracked-On: #8125
=> dm: vga: remove all the assertion.

doc/scripts/requirements.txt
Verified that the newly released RTD theme is OK to use with the doc build process, so update the requirements.txt with that and tweak the acceptable docutils versions.
=> doc: update doc build requirements

misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
Switch tag in order to trigger the component re-rendering after importing different board XML.
Tracked-On: #8288
=> config-tools: re-rendering the data after importing different board XML

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/cpu_affinity.vue, misc/config_tools/launch_config/launch_cfg_gen.py, misc/config_tools/launch_config/launch_script_template.sh, misc/config_tools/schema/checks/cpu_assignment.xsd, misc/config_tools/schema/config.xsd
Add "exclusively owns physical CPUs" checkbox to pre-launched VMs
and post-launched VMs. RTVM will not display this checkbox.
If this checkbox is set, the VM will use all the pCPUs assigned to
it alone.
Launch script offline SOS vcpu when launch own pCPU VM.
=> config_tools: add own_pcpu widget

hypervisor/arch/x86/guest/vcpuid.c, hypervisor/arch/x86/guest/vm.c, hypervisor/arch/x86/guest/vmcs.c, hypervisor/arch/x86/guest/vmexit.c, hypervisor/arch/x86/guest/vmsr.c, hypervisor/include/arch/x86/asm/cpuid.h, hypervisor/include/arch/x86/asm/guest/vm.h
When CPU support MONITOR/MWAIT, OS prefer to use it enter deeper C-state.
Now ACRN pass through MONITOR/MWAIT to guest.
For vCPUs (ie vCPU A and vCPU B) share a pCPU, if vCPU A uses MWait to enter C state, vCPU B could run only after the time slice of vCPU A is expired. This time slice of vCPU A is gone to waste.
For Local APIC pass-through (used for RTVM), the guest pay more attention to timeliness than power saving.
So this patch hides MONITOR/MWAIT by:
1. Clear vCPUID.05H, vCPUID.01H:ECX.[bit 3] and
MSR_IA32_MISC_ENABLE_MONITOR_ENA to tell the guest VM's vCPU
does not support MONITOR/MAIT.
2. Enable MSR_IA32_MISC_ENABLE_MONITOR_ENA bit for
MSR_IA32_MISC_ENABLE inject 'GP'.
3. Trap instruction 'MONITOR' and 'MWAIT' and inject 'UD'.
4. Clear vCPUID.07H:ECX.[bit 5] to hide …
=> hv: hide mwait from guest.

misc/config_tools/static_allocators/bdf.py
According to section 6.1.1, ACPI Spec 6.4, _ADR of a device object under PCI/PCIe bus can use a special function number 0xFFFF to refer to all functions of a certain device. Such objects will have their own nodes in the board XML, and that causes build-time issues when a static allocator attempts to get all BDFs occupied under the root bus because 0xFFFF is not a valid function number (which ranges from 0 to 7).
This patch skips ACPI devices with such addresses when listing existing BDFs.
Tracked-On: #8293
=> static_allocator: skip ACPI objects referring all functions of a PCI device

misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm.vue, misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm/CustomWidget/Virtio/GPU.vue, misc/config_tools/launch_config/launch_cfg_gen.py, misc/config_tools/schema/checks/virtio_devices.xsd, misc/config_tools/schema/config.xsd
Fix the following issues:
1. <gpu> and <displays> elements are added to scenario XML when they are not configured.
2. Virtio GPU components disappears after switching to another tab and switching back to previous tab.
3. Wrong error message of vertical offset checking.
Improve the error check in virtio_devices.xsd:
1. Every window virtual display need to configure window resolution, horizontal offset and vertical offset.
2. Any display's elements need to be configured. The existing code only check the first window resolution, horizontal offset, vertical offset and monitor id.
v1->v2
1. make gpu an array with maxOccurs="1".
Signed-off-by: yuchuyang <yu-chu.yang@intel.com>
Tracked-On: #8292
=> config-tools: fix virio GPU rendering issue

misc/config_tools/launch_config/launch_cfg_gen.py
generate one line of parameter in launch scipt for multiple xchi configs in scenario.xml.
=> config tool: combine multiple xhci to one line

misc/config_tools/board_inspector/board_inspector.py
1. Generate success message when there is no critical error.
2. Generate note when there is error(s).
Tracked-On: #8297
Signed-off-by: yuchuyang <yu-chu.yang@intel.com>
=> config-tools: refine print out message after running board inspector

debian/rules
When building debian packages using one or more work folders generated by the configurator, the build system will use the name of the work folder as the scenario name because the configurator always names a scenario XML as 'scenario.xml'. Scenario names are important here because:
1. they are used to name the installed hypervisor binaries and map files, and the postinst scripts will use those names to fetch the right binary to put under /boot.
2. when multiple work folders defining different scenarios on the same board is given, use the basename of the scenario XMLs leads to a name conflict.
Not following the same scenario name derivation rule in debian/rule will prevent a proper hypervisor binary to be put under /boot and lead to boot-time failure. The potential scenario name collisions …
=> debian/rules: adapt to configurator-generated work folders

CODEOWNERS
misc: Update CODEOWNER for doc reviewer changed.
=> misc: Update CODEOWNER for doc reviewer changed.

debian/debian_build.sh
update the debian/debian_build.sh script to let the gbp dch to get the email address for debian/changlog from one of the 3 ways with priority from high to low: using environment variable 'EMAIL' or 'DEBEMAIL' if existed(this is actually gbp dch required), user.email in git config if existed(set user.email to environment variable 'EMAIL' or 'DEBEMAIL' for gbp dch), or using a dummy address "projectacrn@gmail.com".
Tracked-On: #8262
Signed-off-by: szhen11 <shuang.zheng@intel.com>
=> config_tools: add the dummy address to let anonymous trial of ACRN

misc/config_tools/static_allocators/hv_ram.py
The legacy logic use double IVSHMEM_SIZE to calculate the HV RAM, it can't match the current code.
This patch use the IVSHMEM_SIZE size only.
=> misc: refine the calculate logic of hv_ram_size

misc/config_tools/scenario_config/config_summary.py
Current code use a invalid parameter to print the vCPU number, this patch use the length of vCPU list to fix the above issue.
=> misc: fix the vCPU number issue of document

misc/config_tools/static_allocators/gpa.py
When one single device being connected after multiple-levels of PCI-to-PCI bridges, all those bridges may have the same MMIO window. That causes the current static allocator not to consider that window being occupied because of how it detects nested MMIO regions.
Remove duplicates in the list of secondary bus MMIO windows to fix that issue.
Tracked-On: #8312
=> static_allocator/gpa: deduplicate secondary PCI window list

misc/config_tools/board_inspector/board_inspector.py, misc/config_tools/board_inspector/cpuparser/platformbase.py, misc/config_tools/board_inspector/extractors/10-processors.py, misc/config_tools/board_inspector/inspectorlib/external_tools.py, misc/config_tools/board_inspector/legacy/acpi.py, misc/config_tools/board_inspector/legacy/board_parser.py, misc/config_tools/board_inspector/legacy/clos.py, misc/config_tools/board_inspector/legacy/dmar.py, misc/config_tools/board_inspector/legacy/misc.py, misc/config_tools/board_inspector/legacy/parser_lib.py
Using partial executable paths in the board inspector may cause unintended results when another executable has the same name and is also detectable in the search paths.
Introduce a wrapper module (`external_tools`) which locates executables only under system paths such as /usr/bin and /usr/sbin and converts partial executable paths to absolute ones before executing them via the subprocess module. All invocations to `subprocess.run` or `subprocess.Popen` throughout the board inspector are replaced with `external_tools.run`, with the only exception being the invocation to the legacy board parser which already uses an absolute path to the current Python interpreter.
Tracked-On: #8315
=> board_inspector: use executables found under system paths

misc/config_tools/board_inspector/board_inspector.py, misc/config_tools/board_inspector/cpuparser/platformbase.py, misc/config_tools/board_inspector/inspectorlib/external_tools.py, misc/config_tools/board_inspector/legacy/acpi.py, misc/config_tools/board_inspector/legacy/board_parser.py, misc/config_tools/board_inspector/legacy/clos.py, misc/config_tools/board_inspector/legacy/dmar.py, misc/config_tools/board_inspector/legacy/misc.py, misc/config_tools/board_inspector/legacy/parser_lib.py
Using partial executable paths in the board inspector may cause unintended results when another executable has the same name and is also detectable in the search paths.
Introduce a wrapper module (`external_tools`) which locates executables only under system paths such as /usr/bin and /usr/sbin and converts partial executable paths to absolute ones before executing them via the subprocess module. All invocations to `subprocess.run` or `subprocess.Popen` throughout the board inspector are replaced with `external_tools.run`, with the only exception being the invocation to the legacy board parser which already uses an absolute path to the current Python interpreter.
Tracked-On: #8315
=> board_inspector: use executables found under system paths (for v3.0.x)

.gitignore
ignore debuild intermediate files in .gitignore to avoid these files pollute acrn-hypervisor repo when using debuild to build acrn.
Tracked-On: #8262
Signed-off-by: szhen11 <shuang.zheng@intel.com>
=> ignore debuild intermediate files

Makefile, hypervisor/Makefile, hypervisor/arch/x86/cpu.c, hypervisor/debug/shell.c
The version info is mainly used to tell the user when and where the binary is compiled and built, this will change the hv version format.
The hv follows the format:
HV: major.minor-stable/unstable-remote_branch-acrn-commit_date-commit_id-dirty DBG/REL(tag-current_commit_id) scenario@board build by author date. 
The '(tag-current_commit_id)' is optional, it exits only when there are tags for current commit.
e.g.
with tag:
ACRN:\>version
HV: 3.1-stable-release_3.1-2022-09-27-11:15:42-7fad37e02-dirty DBG(tag: v3.1) scenario3.1@my_desk_3.1 build by zhangwei 2022-11-16 07:02:37 without tag:
ACRN:\>version
HV: 3.2-unstable-master-2022-11-16-14:34:49-11f53d849-dirty DBG scenario3.1@my_desk_3.1 build by zhangwei 2022-11-16 06:49:44
Tracked-On #8303
Signed-off-by: Zhangwei6 <wei6.zhang@intel.com> …
=> hv: change the version format

devicemodel/hw/pci/virtio/vhost.c, devicemodel/hw/pci/virtio/virtio.c, devicemodel/include/virtio.h
Add the new parameter for register ioevent function, let the vhost vq and viothread vq can share the register ioevent common API.
Tracked-On: #8323
Reviewed-by: Conghui <conghui.chen@intel.com>
=> ACRN:DM: Fix the vhost register kick fd issue.

devicemodel/Makefile, devicemodel/core/main.c
The version info is mainly used to tell the user when and where the binary is compiled and built, this will change the dm version format. The dm follows the format:
major.minor-stable/unstable-remote_branch-acrn-commit_date-commit_id-dirty (tag-current_commit_id) build by author date.
Compare to the hv version, which is:
major.minor-stable/unstable-remote_branch-acrn-commit_date-commit_id-dirty DBG/REL(tag-current_commit_id) scenario@board build by author date. 
The dm doesn't contain DBG/REL because it's given in configurator-tool only for hv. also not contain scenario and board info. e.g.
with tag:
$acrn-dm -v
DM: 3.1-stable-release_3.1-2022-09-27-11:15:42-7fad37e02-dirty(tag: v3.1) build by zhangwei@2022-11-16 07:02:35
without tag:
$acrn-dm -v
DM: …
=> dm: change the version format

debian/grub-acrn.README.Debian, debian/grub/25_linux_acrn, debian/grub/acrn.cfg
These patches provide the following fixes and changes:
- Simplify the GRUB configuration helper script: We now only generate a top-level GRUB menu entry. I removed the unnecessary entries under 'Advanced ...' submenu.
- Fix the Service VM command line parameter merge when generating GRUB menu:  The optional parameters either generated by the helper script or set via `GRUB_CMDLINE_LINUX` and `GRUB_CMDLINE_LINUX_DEFAULT` (in /etc/default/grub) are now appended to the ACRN command line, which leads to the desired merging of configuration provided parameters and GRUB provided parameters.
- First basic GRUB configuration support via extended GRUB variables for pre-launched VMs. This includes specifying the location of a VM's kernel image using `GRUB_ACRN_KERNEL_VMx`. Here is the description …
=> Issue8274 wrong kernel cmdline added in grub menu when install acrn hypervisor

misc/config_tools/board_inspector/legacy/acpi.py
Commit 0cbcdbd7c ("board_inspector: use executables found under system paths") unintendedly changes how acpi.py invokes `rdmsr` and that impacts the type of the execution results and causes incompatible method calls when the results are parsed.
Convert the invocation back to shell-style.
Fixes: 0cbcdbd7c ("board_inspector: use executables found under system paths")
Tracked-On: #8315
=> board_inspector: fix the invocation to rdmsr

misc/config_tools/schema/checks/vm_memory.xsd
The division operator in XPATH is `div`, not `/`. Fix it in an error message of the assertions.
=> config_tools/schema: fix division operator in error messages

devicemodel/core/main.c, devicemodel/core/vmmapi.c, devicemodel/include/public/hsm_ioctl_defs.h, devicemodel/include/vmmapi.h
Remove the common interface for sbuf setup, as it is not accept by kernel side. Instead, use dedicate setup function for asyncio to init its sbuf.
Tracked-On: #8209
=> asyncio: refine the setup ioctl

debian/rules
The variables BOARDLIST and SCENARIOLIST serve as filters of XMLs that are found under the user-given directories, and there is no need to assume any filter if a user does not specify that explicitly.
Update the default filters to none so that all found XMLs will be used if a user does not state otherwise.
Tracked-On: #8246
=> debian/rules: change default BOARDLIST and SCENARIOLIST to empty

debian/rules
When searching for scenario XMLs that are saved under the same directory as a board XML, debian/rules uses the wildcard `*` which includes other non-XML files. That causes some non-XML files to be considered as scenario XMLs as well and will cause build-time errors when the build system attempts to parse them as XMLs.
Change the wildcard expression to `*.xml` to restrict the found files to be XML.
Tracked-On: #8344
=> debian/rules: search for XML files only

doc/getting-started/getting-started.rst
* install all Debian packages from /tmp (not ~/acrn-work)
* remove use of USB stick to copy files between dev and target (use scp)
* fix kernel version numbers (5.15.44 to 5.15.77)
* update parameters for debian_build.sh
* remove display of GRUB menu (ACRN now takes over target and automatically boots into hypervisor then Service VM
=> doc: update GSG with v3.2 changes

misc/sample_application/image_builder/create_image.sh, misc/sample_application/image_builder/setup_rt_vm.sh
The switch to Ubuntu 22.04 for ACRN v3.2 requires a few changes to the sample application scripts:
- user _apt cannot access debian packages in user directories, so copy them to /tmp to install
- HMI-VM image size needs to be bigger (running out of space during image update)
Tracked-On: #8352
=> Update sample app scripts for Ubuntu 22.04

doc/getting-started/getting-started.rst
Add "Linux" before kernel version, and "ACRN" before acrn version.
Signed-off-by: Min Yang <minx.yang@intel.com>
=> doc: add "Linux" and "ACRN" to grub display in GSG

debian/grub/20_acrn-board-inspector, debian/grub/25_linux_acrn
1. add kernel version to menuentry "Ubuntu-ACRN Board Inspector"
2. add kernel version and acrn version to menuentry "Ubuntu with ACRN hypervisor"
Signed-off-by: Min Yang <minx.yang@intel.com>
=> debian: add kernel version to GRUB menuentry

doc/static/acrn-custom.css
Sphinx version 5 generates &lt;section&gt; instead of &lt;div&gt; for section headings.  This throws off the custom CSS style for numbered steps so the number icon wasn't showing up.  Tweak the custom CSS to look for both &lt;section&gt; and &lt;div&gt; with class=numbered-step to handle Sphinx 4 and 5-generated content.
=> doc: fix missing numbered-step icon

hypervisor/arch/x86/guest/assign.c, hypervisor/common/hypercall.c, hypervisor/common/ptdev.c, hypervisor/include/arch/x86/asm/guest/assign.h
This series fixes hypervisor side PCIe INTx passthru issue occurred
when passthru USB xDCI, SMbus controllers and IPU to Post-launched VM.
The first patch fixes the hash table implementation used to look up
ptirq_remapping_info from physical interrupt or virtual interrupt
in a VM.
The second patch fixes wrong IOAPIC and RTE states when assigning an
INTx interrupt to Post-launched VM.
=> Ptirq fix for PCIe INTx passthru

misc/config_tools/scenario_config/elementpath_overlay.py
Starting from elementpath 4.0.0, the XPath2Parser class no longer has a SYMBOLS member and completeness checking based on that are removed as well. This patch updates the elementpath_overlay in the config tools to fix the compilation issue when using recent elementpath versions.
Tracked-On: #8368
=> config_tools: adapt to elementpath >= 4.0.0

misc/config_tools/scenario_config/config_summary.py
The new board xml have add a "module" node under the "processors/die" which has cause an issue when we run the summary, this patch  use "//" to select all "cpu_id" under the "processors".
=> misc: fix the summary issue after update board xml

misc/config_tools/board_inspector/legacy/misc.py
If we use 5.15 kernel on rpl-p platform, some iomem info dumped with non-ascii characters, then tool will raise a decode error.
So this patch filters non-ascii characters to handle this error.
Tracked-On: #8388
=> config_tools: filter non-ascii characters in iomem infomation

misc/config_tools/board_inspector/extractors/10-processors.py
If no TURBO_RATIO_LIMIT and TURBO_ACTIVATION_RATIO MSRs info on target, board inspector will crash because of the IOError exception.
This patch captures the IOError exception to handle this error.
Tracked-On: #8380
=> config_tools: capture the IOError exception

debian/debian_build.sh
This patch adds -v or --verbose option to build script to enable verbose output by setting DH_VERBOSE environment variable. This is useful when debugging build issues.
Tracked-On: #8399
=> debian: add verbose option in build script

misc/config_tools/configurator/packages/configurator/src/pyodide.js, misc/config_tools/configurator/packages/configurator/thirdLib/library.json
9c2d0f8858f8 ("config_tools: replace RstCloth library with class.") removes all usage of rstcloth in code, but the rstcloth package is not removed from acrn-configurator and it will still download dependencies for rstcloth. This patch simply removes it.
Tracked-On: #8395
=> config_tools: remove rstcloth package

devicemodel/hw/pci/gvt.c
gvt_init_config() may perform out-of-range read on host_config, add bound check before accessing it.
Tracked-On: #8382
=> dm: gvt: add bound check in gvt_init_config()

misc/services/life_mngr/Makefile
Linker option "-z,relro" will be automatically added to LDFLAGS when building debian packages. Since x86_64-w64-mingw32-ld does not support "-z" option, it causes failure in building the life_mngr windows exe. This patch fixes it by skipping the windows build of life_mngr if LDFLAGS contains any "-z" option.
Tracked-On: #8399
=> misc: life_mngr: skip windows build if LDFLAGS contains -z option

misc/config_tools/board_inspector/legacy/board_parser.py
`modprobe msr` will be invoked if no /dev/cpu/#/msr is found. If the "msr" module is built-in that check will pass and no `modprobe msr` should be invoked.
fixes: aeab5a2 ("config_tools: update loading msr driver logic")
Tracked-On: #8410
=> config_tools: will load msr driver if no /dev/cpu/#/msr is found

misc/config_tools/launch_config/launch_cfg_gen.py, misc/config_tools/schema/config.xsd
add customized parameters in the launch script generation logic. If user specify customized parameters in configurator, we will append them to the dm parameters for launching VMs.
Tracked-On: #8408
=> config_tools: add customized parameters in launch script generation logic

misc/config_tools/scenario_config/config_summary.py
currently, configurator will fail to generate config_summary.rst file if user enable the "Cache Allocation Technology" because note function in rstcloth is replaced by self.doc.note.
So this patch updates function and usage to fix this issue.
fixs: 9c2d0f8 ("config_tools: replace RstCloth library with class.")
Tracked-On: #8422
=> config_tools: fix the issue that fail to generate config_summary.rst if enable CAT

devicemodel/hw/pci/gvt.c, hypervisor/arch/x86/sgx.c, misc/services/life_mngr/list.h, misc/services/life_mngr/socket.c, misc/services/life_mngr/uart_channel.c
Backport following commits to release 3.2 to solve build issues with gcc 12/13
c9e5fd146 misc: fix the summary issue after update board xml
632097778 dm: gvt: add bound check in gvt_init_config()
e4e25f076 hv: sgx: refactor partition_epc()
=> Backport compiler fix for release 3.2

hypervisor/arch/x86/guest/vlapic.c, hypervisor/arch/x86/guest/vm.c, hypervisor/arch/x86/guest/vmsr.c, hypervisor/include/arch/x86/asm/guest/vm.h, hypervisor/include/public/acrn_common.h
Background:
Currently CPU frequency control is hidden to guests, and controlled by
hypervisor. While it is sufficient in most cases, some guest OS may
still need CPU performance info to make multi-core scheduling decisions.
This is seen on Linux kernel, which uses HWP highest performance level
as CPU core's priority in multi-core scheduling (CONFIG_SCHED_MC_PRIO).
Enabling this kernel feature could improve performance as single thread
workloads are scheduled on the highest performance cores. This is
significantly useful for guests with hybrid cores.
Design:
The concept is to create a virtual HWP(VHWP) interface for guests, so
that guest can have some CPU performance managing and prioritized MC
scheduling abilities.
For guests owning its pCPUs, we can just allow vCPU read …
=> enable VHWP for guests who owns pCPUs(part 2)

hypervisor/arch/x86/guest/vmsr.c
Guests may read MSR_PLATFORM_INFO to get nominal TSC frequency, though it should be replaced by reading CPUID leaf 0x16 on newer processors. This patch emulates MSR_PLATFORM_INFO with 0 for non-service vm instead of injecting #GP to avoid guest crash.
Tracked-On: #8406
=> hv: allow non-service vm to read MSR_PLATFORM_INFO (CEh)

devicemodel/hw/pci/passthrough.c
The Data of Stolen Memory (DSM) region on Alder Lake-N and Raptor Lake platform is indicated by the BDSM register (0xC0 and 0xC4 in PCI config space), which is the same as Gen 11 (Tiger Lake) iGPU. This patch adds ADL-N and RPL iGPU device id to passthrough the DSM region properly when using GVT-d.
The PCI device ids are taken from i915 kernel driver.
Tracked-On: #8432
=> dm: passthrough DSM region for ADL-N and RPL

hypervisor/dm/vpci/pci_pt.c, hypervisor/include/arch/x86/asm/io.h
On x86 platform, the upper 16 bit of I/O BAR should be initialized to
zero by BIOS. Howerever, some buggy BIOS still programs the upper 16
bits to non-zero, which causes error in check_pt_dev_pio_bars(). Since
I/O BAR reprogramming by VM is currently unsupported, this patch
ignores such I/O BARs when creating vpci devices to make VM boot.
Tracked-On: #8373
=> hv: vpci: ignore PCI I/O BAR with non-zero upper 16 bits

hypervisor/arch/x86/guest/assign.c, hypervisor/include/arch/x86/asm/apicreg.h
According to SDM Vol3 11.12.10, in x2APIC mode, Logical Destination has two parts:
- Cluster ID (LDR[31:16])
- Logical ID (LDR[15:0]) Cluster ID is a numerical address, while Logical ID is a 16bit mask. We can only use Logical ID to address multi destinations within a Cluster.
So we can't just 'or' all the Logical Destination in LDR registers to get one mask for all target pCPUs. This would get a wrong destination mask if the target Destinations are from different Clusters.
For example in ADL/RPL x2APIC LDRs for core 2-5 are 0x10001 0x10100 0x20001 0x20100. If we 'or' them together, we would get a Logical Destination of 0x30101, which points to core 6 and another core. If core 6 is running a RTVM, then the irq is unable to get to core 2-5, causing the guest on core 2-5 driver fail.
There …
=> hv: bugfix: fix the ptdev irq destination issue

misc/sample_application/image_builder/create_image.sh, misc/sample_application/image_builder/setup_hmi_vm.sh
In chroot environment, the running kernel is the host kernel, so uname command cannot get the kernel verison in image. Since hmi-vm uses GVT-d, and kernel 5.15 does not support newer iGPUs in 13th Gen processors, this patch installs the linux-generic-hwe kernel (5.19) instead of linux-modules-extra package.
In Ubuntu 22.04, package needrestart is installed by default to interactively prompt user there is a pending kernel upgrade or serivces need to be restarted in apt. This patch removes it.
Also, this patch expands hmi-vm image by 2GB to hold the new kernel and runs 'apt autoremove' after everything is installed.
=> misc: sample_application: fix setup_hmi_vm.sh for Ubuntu 22.04

misc/config_tools/scenario_config/config_summary.py
An error will be raised if no cache level 3 information in board xml file. this patch skips getting cache level 3 information when no l3 cache info in config_summary.py.
Tracked-On: #8438
=> config_tools: tiny fix for config_summary.py

hypervisor/arch/x86/guest/assign.c
ffs64() returns INVALID_BIT_INDEX (0xffffU) when it tries to deal with zero input value. This may happen In calculate_logical_dest_mask() when the guest tries to write some illegal destination IDs to MSI config registers of a pt-device. The ffs64() return value is used as per_cpu array index, and it would cause a page fault.
This patch adds protection to the per_cpu array, making this function return zero on illegal value. As in logical destination's definition, a zero logical designation would point to no CPU.
Fixes: 1334349f8
Tracked-On: #8454
=> hv: bugfix: skip invalid ffs64 return value

devicemodel/hw/pci/virtio/virtio_gpu.c
In virtio_gpu_cmd_create_blob() and virtio_gpu_cmd_resource_attach_ backing(), entries may be accessed before initialization. Fix it by using calloc() to allocate it instead of malloc().
Tracked-On: #8439
=> dm: virtio-gpu: fix uninitialized memory access

misc/config_tools/configurator/packages/configurator/src-tauri/Cargo.lock, misc/config_tools/configurator/packages/configurator/src-tauri/Cargo.toml
update tauri version to 1.4.1 fix security vulnerability for configurator dependent library.
Tracked-On: #8445
=> configurator: update tauri version

hypervisor/include/arch/x86/asm/guest/nested.h
arch/x86/guest/nested.c, where nested_vmexit_handler() is defined, is only compiled when CONFIG_NVMX_ENABLED is enabled. Define a dummy function in include/arch/x86/asm/guest/nested.h to fix the undefined reference linker error.
Tracked-On: #8465
=> hv: fix undefined reference to nested_vmexit_handler() in vmexit.c

doc/getting-started/getting-started.rst, doc/getting-started/sample-app.rst
Launch script attaches guest network to bridge acrn-br0 by default, while this bridge is not automatically created during installation. This patch updates the documentation to guide users with the sample bridge configuration in Getting Started Guide and Sample Application Guide.
Tracked-On: #8448
=> doc: update network configuration section

doc/getting-started/sample-app.rst
The create_image.sh script uses qemu-img to create image files. Users only need to install qemu-image in qemu-utils instead of the whole qemu package.
Tracked-On: #8448
=> doc: replace qemu-kvm with qemu-utils in sample application guide

doc/_templates/layout.html
Update the header banner on the latest documentation to references 3.2 and 3.0 stable release documentation (instead of 3.1)
=> doc: update header banner for stable documentation link

doc/index.rst, doc/projects/index.rst, doc/projects/multi-arch-support.rst
Add initial documentation organization (and draft content) for a project adding multi-architecture and RISC-V support for ACRN.
=> doc: draft organization for multi-arch support

hypervisor/arch/x86/guest/vm.c
On some platforms, the last e820 entry may not be of type E820_TYPE_RAM, such as E820_TYPE_ACPI_NVS which may also be used by Service VM. So we need take all e820 entry types into account when finding the upper bound of Service VM EPT mapping.
Tracked-On: #8495
=> hv: fix Service VM EPT mapping upper bound

hypervisor/Makefile, hypervisor/arch/x86/configs/pci_dev.c, hypervisor/dm/vpci/vpci_mf_dev.c, hypervisor/include/arch/x86/asm/vm_config.h, hypervisor/include/dm/vpci.h, misc/config_tools/xforms/vm_configurations.c.xsl
When function 0 in a multi-function PCI device is passthru to Pre-launched VM
or owned by the hypervisor, a dummy function 0 should be emulated for Service
VM if the other functions are left to Service VM.
We met this case on a platform whose LPSS device contains a PCI serial port at
function 0 together with several I2C functions.
The first patch improves the PCI device config initialization logic as
discussed in [1].
The second patch add the dummy multi-function device support.
[1] https://lists.projectacrn.org/g/acrn-dev/message/37656
=> hv mutli-function device passthru fixes

hypervisor/arch/x86/guest/ept.c, hypervisor/arch/x86/guest/vept.c, hypervisor/dm/vpci/ivshmem.c, hypervisor/include/arch/x86/asm/e820.h
ACRN boot fails when size of ivshmem device is configured to 512MB,
this patch series is to allocate this memory from E820 table instead of
reserving in hypervisor.
=> hv: allocate ivshmem shared memory from E820

hypervisor/common/sched_bvt.c
When bvt scheduler picks up a thread to run, it sets up a counter ‘run_countdown’ to determine how many ticks it should remain running. Then the timer will decrease run_countdown by 1 on every 1000Hz tick interrupt, until it reaches 0. The tick interrupt consumes a lot of power during idle (if we are using HLT in idle thread).
This patch is to switch the 1000 HZ timer to a dynamic one, which only interrupt on run_countdown expires.
Tracked-On: #8507
=> hv: switch to dynamic timer in bvt scheduler

hypervisor/arch/x86/cpu.c, hypervisor/arch/x86/guest/vcpu.c, hypervisor/arch/x86/guest/vlapic.c, hypervisor/common/event.c, hypervisor/common/hv_main.c, hypervisor/common/schedule.c, hypervisor/include/arch/x86/asm/cpu.h, hypervisor/include/arch/x86/asm/per_cpu.h, hypervisor/include/common/schedule.h
When all vCPU threads on one pCPU are put to sleep (e.g., when all
guests execute HLT), hv would schedule to idle thread. Currently the
idle thread executes PAUSE which does not enter any c-state and consumes
a lot of power. This patch is to support HLT in the idle thread.
=> support halt in hv idle

hypervisor/arch/x86/guest/vcpu.c, hypervisor/common/hv_main.c, hypervisor/common/sched_bvt.c, hypervisor/common/sched_iorr.c, hypervisor/common/sched_prio.c, hypervisor/common/schedule.c, hypervisor/include/arch/x86/asm/vm_config.h, hypervisor/include/common/schedule.h, hypervisor/include/lib/util.h, misc/config_tools/data/generic_board/generic_code/hybrid/vm_configurations.c, misc/config_tools/data/generic_board/generic_code/partitioned/vm_configurations.c, misc/config_tools/data/generic_board/generic_code/shared/vm_configurations.c, misc/config_tools/schema/config.xsd, misc/config_tools/xforms/vm_configurations.c.xsl
This series refines BVT scheduler parameters and add weight support for
threads to allow more flexiable cpu resource allocation among VCPU threads
from different VMs.
As of now, BVT parameters can only be statically set in config tool. We can
allow dynamic parameters tuning via hypercalls in the future.
=> refine BVT scheduler

devicemodel/hw/pci/xhci.c, devicemodel/include/usb_core.h
Currently only devices on usb bus 0~4, port 0~19 can be passthrough to the emulated XHCI controller. Remove this unnecessary limit.
Some unused definitions are also removed.
Tracked-On: #8506
=> dm: xhci: remove bus/port limit

misc/config_tools/board_inspector/legacy/acpi.py
Some motherboards exposes MCFG1/MCFG2 instead of one ACPI MCFG table, thus no /sys/firmware/acpi/tables/MCFG exists but MCFG1 and MCFG2.
Read MCFG1 if MCFG doesn't exist.
The same issue report/fix is at https://github.com/intel/pcm/issues/74.
=> Support ACPI MCFG multi tables boards for board_inspector

misc/config_tools/acpi_gen/bin_gen.py
When enable TPM2 tag in acrn scenario file, can't pass compile: File "../hypervisor/../misc/config_tools/acpi_gen/bin_gen.py", line 128, in tpm2_acpi_gen
ctype_data.start_method_specific_parameters[i] = int(start_method_parameters[i], 16)
ValueError: invalid literal for int() with base 16: '\n        '
Fix this issue in tpm2_acpi_gen.
Tracked-On: #8516
=> config_tools: Fix TPM2 parameter issue

misc/config_tools/acpi_gen/asl_gen.py
Currently, for pre-launched VM, ACPI table is generated only when "reboot=acpi" is added to cmdline in the scenario file. This patch remove this check support that ACPI table must be generated automatedly for the Pre-launched VM.
Tracked-On: #8546
=> config_tools: ACPI table needs to be generated automatedly for Pre-launched VM

devicemodel/hw/pci/lpc.c, devicemodel/hw/uart_core.c
This patchset enhances current lpc uart emulation feature including supporting emulating COM3 and 4, this is used for improving debugging experience on post-launched vm without hv console.
=> dm: lpc uart emulation enhancements

misc/config_tools/acpi_gen/asl_gen.py
Current acpi table adopts the DWordAddressSpace to present 
the PCI hole above 4G. It is not correct, because DWordAddressSpace 
is used to present the mem space below 4G.
Follow the ACPI spec, modify to QWordAddressSpace here.
Refer: 19.6.22. CreateQWordField (Create 64-Bit Buffer Field)
Tracked-On: #8552
Signed-off-by: Zhangwei6 <wei6.zhang@intel.com>
=> config_tools: fix pre_launch VM ACPI table

hypervisor/common/sbuf.c, hypervisor/common/vm_event.c, hypervisor/debug/logmsg.c, hypervisor/debug/profiling.c, hypervisor/debug/trace.c, hypervisor/dm/io_req.c, hypervisor/include/common/sbuf.h
sbuf_put copies sbuf->ele_size of data, and puts into ring. Currently this function assumes that data size from caller is no less than sbuf->ele_size.
But as sbuf->ele_size is usually setup by some sources outside of the HV (e.g., the service VM), it is not meant to be trusted. So caller should provide the max length of the data for safety reason. sbuf_put() will return UINT32_MAX if max_len of data is less than element size.
Additionally, a helper function sbuf_put_many() is added for putting multiple entries.
Tracked-On: #8547
=> hv: add max_len for sbuf_put param

hypervisor/debug/console.c
For uart console, some control keys are defined as byte sequences, such as:
* up arrow - 0x1b/0x5b/0x41
* F8 - 0x1b/0x5b/0x31/0x39/0x7e
Currently hv console only read one char per poll.
When guest vuart console is active, those byte sequences may not be sent to guest vuart in good timing due to the poll interval. Thus control keys such as up/down can not be used in shell or vim.
The solution is to read all input chars in one poll, so that control keys can be received by guest OS properly.
Tracked-On: #8564
=> hv: console reads all input chars in one poll

hypervisor/debug/console.c, misc/config_tools/schema/config.xsd, misc/config_tools/xforms/config_common.xsl
Add a new option CONSOLE_VM in scenario to set the default vm to be outputted in hv console, when it is not set, acrn console will be used (current behavior). This is intended for debugging vm boot issues.
Tracked-On: #8518
=> hv: configure hv console default output in scenario file

hypervisor/arch/x86/mmu.c
ppt_page_pool.bitmap should be zero-initialized. Also fixes the wrong indention in allocate_ppt_pages().
Tracked-On: #8559
=> hv: mmu: intiialize ppt_page_pool.bitmap in allocate_ppt_pages()

hypervisor/dm/vpci/ivshmem.c
secure coding fix.
Tracked-On: #8566
=> hv: fix potential NULL pointer dereferrence in ivshmem.c

hypervisor/common/hypercall.c
In hcall_vm_intr_monitor(), the default case for intr_hdr->cmd is a wrong case. So, it should return error code back. But it returns success code 0 in current codes.
Tracked-On: #8580
=> hv: return error code for default case in hcall_vm_intr_monitor

devicemodel/hw/pci/lpc.c
The meaning of lpc_uart_vdev::enabled was changed from runtime enablement status of UARTs to user configuration in commit 852f10cc3. So it's incorrect to clear it in lpc_deinit() which will cause UARTs disabled after reboot.
Tracked-On: #8537
Fixes: 852f10cc3 ("dm: lpc: only emulate COM ports specified in command line")
=> dm: fix LPC UART no output issue after reboot

hypervisor/debug/console.c, hypervisor/dm/vuart.c, hypervisor/include/dm/vuart.h
The first patch adds an key escaping sequence to ensure that users can input
any key to guest serial via vm console. This makes it possible to debug
Service VM kernel with kgdb/kdb and sysrq. The key sequence to switch from
guest console to HV console has changed to "<break> + e". In minicom, it will
be a sequence of "<ctrl-a> + f + e".
The second patch fixes the interrupt ID in IIR for normal data receiving.
Although the old RX Timeout value worked but RX Ready is more reasonable.
=> Hv break char for kdb upstream

misc/config_tools/library/board_cfg_lib.py, misc/config_tools/static_allocators/gpa.py, misc/packaging/gen_acrn_deb.py
Python 3.12 adds escape sequence check in strings, if it is invalid, a SyntaxWarning will be given. Fix it by using raw string notation in regular expressions, and changing comments in unused string literal to normal comments.
Tracked-On: #8588
=> misc: fix invalid escape sequence in python 3.12

debian/grub/20_acrn-board-inspector, debian/grub/25_linux_acrn
`version_find_latest` is removed in grub 2.12, replace it with `sort -V -r` for maximum compatibility.
Tracked-On: #8576
=> debian: fix broken grub config with grub 2.12

misc/config_tools/schema/config.xsd, misc/config_tools/static_allocators/guest_flags.py
In hv, we implement the feature of thermal virtualization, We want to use this GUEST_FLAG_VTM flag to enable and disable this feature. So we mark this flag in config tools.
porting from the inner source repo. 
Tracked-On: #8595
Signed-off-by: Zhangwei6 <wei6.zhang@intel.com>
=> config_tools: support the GUEST_FLAG_VTM flag

misc/config_tools/configurator/packages/configurator/src-tauri/Cargo.lock, misc/config_tools/configurator/packages/configurator/src/pages/Config.vue, misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm.vue, misc/config_tools/configurator/packages/configurator/src/pages/Config/NewBoard.vue, misc/config_tools/configurator/packages/configurator/src/pages/Config/Scenario/NewScenario.vue, misc/config_tools/configurator/packages/configurator/src/pages/Config/Scenario/OverwriteMessage.vue, misc/config_tools/configurator/packages/configurator/src/pages/Config/Scenario/SaveScenario.vue
I make this change during recent building configurator but got a failure. The change is to fix the problem caused by vue3's strictly syntax chacking. It is reported for newly releases only and before v3.2.25 it is a warning. I follow the error message and suggestion to change the code. Error message said "v-model cannot be used on a prop, because local prop bindings are not writable".
Suggestion said "Use v-bind binding combined with v-on listener to emit update" I ran the build & install procedure to verify the problem was solved.
Tracked-on: #8596
=> misc: fix v-model used on props for vue3 make strictly checking

misc/config_tools/configurator/packages/configurator/src-tauri/Cargo.lock, misc/config_tools/configurator/packages/configurator/src-tauri/Cargo.toml, misc/config_tools/configurator/yarn.lock
The vulnerability was scanned by Trivy on May 28,2024. Vulnerability ID is GHSA-xphf-cx8h-7q9g and severity is medium, with title iFrames Bypass Origin Checks for Tauri API Access Control. I fixed the crash and checked by build-install-launch procedure, I confirm it was solved.
Tracked-On: #8613
=> misc: fix tauri's vulnerability

hypervisor/dm/vpci/ivshmem.c, hypervisor/dm/vpci/vdev.c, hypervisor/dm/vpci/vmcs9900.c, hypervisor/dm/vpci/vpci.c, hypervisor/dm/vpci/vroot_port.c, hypervisor/include/dm/vpci.h
In devicemodel, a passthrough device is deassigned and then assigned to guest on guest reboot. Each time hypervisor allocates a new pci_vdev structure to keep its info. As it was stored in a statically-allocated array, it will eventually use up all slots, resulting both resource leak and out-of-bounds access.
Fix it by clearing the corresponding vdev structure on device deassign, thus a bitmap is introduced to track the usage, replacing the existing array count.
Tracked-On: #8590
=> hv: vpci: clear vdev structure on device deassign

misc/config_tools/board_inspector/pcieparser/extcaps.py
PCIe extended capability with ID 0x1F is Precise Time Measurement. So fix typo "TPM" which may confuse users.
Tracked-On: #5915
=> board_inspector: fix typo in PCIe PTM Capability name

misc/config_tools/configurator/packages/configurator/src/pages/Config.vue
This patch will add checking cpu affinity while user click to add new vm. When I was following client's findings up I found that if I click to add a new post-launched vm for step 3.Configure settings for scenario and launch scripts, it failed to show error messages. The current version will check cpu affinity and serial port for post-launched and hv when creating a new vm, it wont verify when adding new post-launched & pre-launched vms, it will fail to save scenario configuration file without any explanation. I've rebuilt and run configurator, confirmed the checking procedure works.
Tracked-On: #8601
Reviewed-by: Junjie Mao junjie.mao@intel.com
=> misc: add checking while append new vm

misc/config_tools/configurator/packages/configurator/package.json, misc/config_tools/configurator/packages/configurator/src/pages/Config.vue, misc/config_tools/configurator/packages/configurator/src/pages/Config/ConfigForm.vue, misc/config_tools/configurator/packages/configurator/src/pages/Config/NewBoard.vue, misc/config_tools/configurator/packages/configurator/src/pages/Config/Scenario/NewScenario.vue, misc/config_tools/configurator/packages/configurator/src/pages/Config/Scenario/OverwriteMessage.vue, misc/config_tools/configurator/packages/configurator/src/pages/Config/Scenario/SaveScenario.vue, misc/config_tools/configurator/yarn.lock
Although my former patch can pass through build procedure but when I launch configurator and try to load board.xml, the loading procedure wont finish. So we cannot step forward anymore.
I cannot find a solution right now, so I have to fix the version to v3.2.33 for several weeks.
This patch is applied to fix vulnerability scanned by Trivy also. Vulnerability ID is CVE-2024-4068 & fixed version of dependency is 3.0.3. I added one configuration item named override for package.json.
I tested and confirmed the fix is ok.
Tracked-On: #8626
=> misc: fix Vue3 version & update braces's version

hypervisor/arch/x86/guest/vmexit.c
In HV, cpuid uses the lower 32 bits of rax\rbx\rcx\rdx registers to pass parameters, But the software does not clear the upper 32-bit registers,  if the guest uses 64-bit variables to pass parameters to cpuid，guest will use rax\rbx\rcx\rdx, not eax\ebx\ecx\edx, the previous value of the high 32 registers will affect the guest.
Tracked-On:8605
=> hv: fix using cpuid does not clear the upper 32-bit registers.

devicemodel/core/main.c
iothreads are created by emulated block devices like virtio. These devices are resetted on vm reset, but these iothreads are not freed, causing a resource leak. Fix it by deinit all iothreads on vm reset.
Tracked-On: #8612
=> dm: deinit iothreads on vm reset

hypervisor/arch/x86/guest/vcpuid.c
Some cpuids will return invalid values on hybrid platform because of the error in the pointer arithmetic. Add `(void *)` before `cpu_cpuids.leaves`.
Leaf 0x14 is used to report Intel Processor Trace Enumeration and varies between P-cores and E-cores on hybrid platform. So add it to `hybrid_leaves`.
Tracked-On: #8608
Fixes: 59a8cc4c2 ("hv: cpuid: make leaf 0x4 per-cpu in hybrid architecture")
=> hv: cpuid: fix hybrid related cpuid error

doc/developer-guides/hld/ivshmem-hld.rst
- In 'MMIO Registers Definition', the names of interrupt status/mask registers are wrong
Tracked-On: #8568
=> doc: Correct the registers names in ivshmem hld

misc/packaging/acrn-hypervisor.postinst, misc/packaging/acrn-kernel.postinst
If the root partition is bind mounted with / and another, the current postinst script (using command lsblk) will fail to find the partition: $type will be "/" only and cause the following command may find the wrong partition.
And current command forces the root partition to be ext4.
This patch fixes the two issues.
Two setups with bind mounted root partition;
Ubuntu 22.04 desktop, bind mount firefox snap:
```
> lsblk
nvme0n1      259:19   0 931.5G  0 disk
├─nvme0n1p1  259:20   0   243M  0 part /boot/efi
├─nvme0n1p2  259:21   0 927.5G  0 part /var/snap/firefox/common/host-hunspell
│                                      /
```
Windows WSL2, bind mount WSLg:
```
> lsblk
sdc    8:32   0     1T  0 disk /mnt/wslg/distro
/
```
Tracked-On: #8532
=> Fix Debian packaging postinst partition finding

misc/config_tools/static_allocators/hv_ram.py
As ivshmem has switched from static allocation to E820 allocation, the hv_ram_size no longer needs to include ivshmem size.
Tracked-on: #8522
=> config_tools: remove ivshmem size from hv_ram_size

hypervisor/common/schedule.c, hypervisor/debug/trace.c, hypervisor/include/debug/trace.h, misc/debug_tools/acrn_trace/scripts/acrnalyze.py, misc/debug_tools/acrn_trace/scripts/cpuusage_analyze.py, misc/debug_tools/acrn_trace/scripts/formats
To maximize the cpu utilization, core 0 is usually shared by service vm and guest vm. But there are no statistics to show the cpu occupation of each vm.
This patch is to provide cpu usage statistic for users. To calculate it, a new trace event is added and marked in scheduling context switch, accompanying with a new python script to analyze the data from acrntrace output.
Tracked-On: #8621
Reviewed-by: Haiwei Li <haiwei.li@intel.com>
=> hv: trace: show cpu usage of vms in pcpu sharing case

hypervisor/boot/guest/elf_loader.c, hypervisor/boot/guest/vboot_info.c, hypervisor/boot/include/elf.h, hypervisor/boot/include/multiboot_std.h
Current ACRN can not support multiboot protocol for VM images.
With the in-depth development, customers need more ways to load different types of VMs. For example the OPTEE and android kernelflinger binary requirements. This series is a preliminary multiboot boot protocol enablement for cmdline and memory map, and TODO full multiboot support in the future.
=> Enable ACRN ELF loader support

devicemodel/hw/pci/lpc.c, devicemodel/hw/uart_core.c, devicemodel/include/uart_core.h, misc/config_tools/static_allocators/intx.py, misc/config_tools/static_allocators/s5_vuart.py
This patch is to change the vUART resource occupied by S5 function between Service VM and guest VM to avoid the standard UART port conflict when legacy UART passthrough to guest VM.
Tracked-On: #8622
=> vUART: change S5 vUART resource

doc/develop.rst, doc/tutorials/user_vm_guide.rst, doc/tutorials/using_celadon_as_user_vm.rst
This patch adds tutorials about using Celadon as user vm. This tutorials contains: Build Celadon from source code with refined configs and kernel; Launch Celadon vm with passthrough gpu and passthrough disk.
Tracked-On: #8254
=> doc: add celadon as user vm guide

doc/tutorials/acrn_configurator_tool.rst
1.We updated libwebkit2gtk-4.0-dev install method for Canonical had removed that package already, but Tauri need it, so we advice the user to download the dependencies through Ubuntu22.04's repo or adopt our links directly.
2.remove unnecessary package: libappindicator3-dev, we found it is possible to build acrn without that dependency, so we remove it now.
Tracked-On: #8659
=> doc: update libwebkit2gtk install method & remove unnecessary package

misc/config_tools/configurator/packages/configurator/src/lib/acrn.ts, misc/config_tools/configurator/packages/configurator/src/pages/Config.vue, misc/config_tools/configurator/packages/configurator/src/pages/Config/Scenario/NewScenario.vue, misc/config_tools/configurator/pyodide/updateSchema.py
This patch is to support Main VM, i.e., the Main VM scenario is similar to paritioned scenario, which select one VM as Main VM and owns the physical resources.
I extracted all pcis from the board, substracted them with dispatched ones and then make an assignment to replace the old enums.
This is implemented through two methods called updateSchema which is to update schema on the current VM and updateLoadSchema which is to maintain pcis, i.e. removed the pcis listed on the pre-launched VM, while loading scenario.xml.
I tested locally and confirmed the functionalties above are implemented.
Tracked-On: #8657
=> misc: Configurator Main VM Support

misc/config_tools/configurator/packages/configurator/src-tauri/Cargo.lock, misc/config_tools/configurator/packages/configurator/src-tauri/Cargo.toml
Trivy scaned one vulnerability three days ago and we fixed it now.
The title for vulnerability is openssl's `MemBio:get_buf` has undefined behavior with empty buffers.
I tested through building configurator, launching it and generating scenario.xml & launch scripts. I confirmed the result is correct.
Tracked-On: #8668
=> misc: fix openssl's vulnerability for tauri

hypervisor/arch/x86/guest/vm.c, hypervisor/include/public/acrn_common.h, misc/config_tools/schema/config.xsd, misc/config_tools/static_allocators/guest_flags.py
GUEST_FLAG_STATELESS indicates guest is running a stateless operating system and need to be shutdown forcefully without data loss. This flag is only appalicable to pre-launched VM. For TEE_VM, this flag will be set implicitly.
Tracked-On: #8671
=> hv: add GUEST_FLAG_STATELESS flag

devicemodel/Makefile, devicemodel/hw/platform/gpio.c, devicemodel/hw/platform/uart.c
Add GPIO and UART to ACPI device list to support UART pass through as ACPI device
by --acpidev_pt parameter.
Here is an example of pass through GPIO with --acpidev_pt argument:
--acpidev_pt INTC1055,uid=0,type=irq,irq=14,polarity=3,trigger_mode=3
--acpidev_pt INTC1055,uid=0,type=memory,min=0xfd6e0000,len=0x10000
--acpidev_pt INTC1055,uid=0,type=memory,min=0xfd6d0000,len=0x10000
--acpidev_pt INTC1055,uid=0,type=memory,min=0xfd6a0000,len=0x10000
--acpidev_pt INTC1055,uid=0,type=memory,min=0xfd690000,len=0x10000
Here is an example of pass through UART with --acpidev_pt argument:
--acpidev_pt PNP0501,uid=19,type=irq,irq=5
--acpidev_pt PNP0501,uid=19,type=io_port,min=0x2e8,len=8
This PR depends on:
=> [release_3.3] Add GPIO and UART to ACPI passthrough device list

debian/acrn-hypervisor.postinst.in, debian/acrn-hypervisor.postrm.in, debian/acrn-hypervisor.prerm.in, debian/grub/25_linux_acrn
Calling debconf in grub script may fail when installing with dpkg as
debconf database might be occupied by dpkg, causing update-grub fail
with message below
```
debconf: DbDriver "config": /var/cache/debconf/config.dat is locked by another process: Resource temporarily unavailable
```
This patchset fixes issue above by creating a symlink to scenario file
at fixed path /usr/share/acrn/scenario.xml and let grub-acrn script
read scenario here so that debconf is no longer called.
=> [release_3.3] Remove debconf call in grub script

doc/acrn.doxyfile
`consistency` is used to describe the consistency rule and `alignment` is used to describe the align info.
These two are used to enhance the documentation inside a struct comment block.
=> doc: add custom commands in acrn.doxyfile

hypervisor/arch/x86/mmu.c, hypervisor/arch/x86/page.c, hypervisor/arch/x86/pagetable.c, hypervisor/include/arch/x86/asm/page.h, hypervisor/include/arch/x86/asm/pgtable.h
ACRN hypervisor is decomposed into a series of components and modules. The module design in hypervisor is to add inline doxygen style comments above functions, macros, structures, etc.
This patch is to add comments for some elements in hwmgmt_page module.
=> doc: add module design for some defines in hwmgmt_page

devicemodel/hw/platform/acpi/acpi.c, devicemodel/hw/platform/acpi/acpi_pm.c, devicemodel/include/acpi.h
After upgrading to guest kernel 6.1.80, it checks the CPPC V2 capability in _OSC of DSDT. To support it for ACRN guest, add CPPC V2 capability in _OSC of DSDT. Currently we only support CPPC V2 capability in _OSC of DSDT.
Tracked-On: #8691
=> dm: acpi: support CPPC V2 capability in _OSC of DSDT for ACRN guest.

hypervisor/common/hypercall.c
After rebooting guest, CPPC initialization failed because _CST and _CPC missed in DSDT table. When writing _CST and _CPC in DSDT table, it gets cx_cnt or px_cnt as condition. Getting cx_cnt or px_cnt triggers the hypercall hcall_get_cpu_pm_state. The hypercall hcall_get_cpu_pm_state uses VM_CREATED as VM state's condition. While, after rebooting guest, the VM state is VM_PAUSED when writing _CST and _CPC in DSDT table. Therefore, changing VM state's condition from VM_CREATED to VM_CREATED or VM_PAUSED for hcall_get_cpu_pm_state can solve the CPPC initialization failed issue after rebooting guest.
Tracked-On: #8695
=> hv: hypercall: change condition for hcall_get_cpu_pm_state

hypervisor/arch/x86/vtd.c
This patch fixes the following testability issues identified by the dynamic module test.
Global variables defined in function scope cannot be referenced outside the function, making it impossible to check the return value of these functions.
=> hv: fix testability issues that impact module test

hypervisor/dm/vrtc.c, hypervisor/include/dm/vrtc.h
GAI Tooling Notice: These contents may have been developed with support from one or more generative artificial intelligence solutions.
This patch is to add doxygen style comments for some elements in vp-dm_vperipheral vrtc module.
=> doc: add module design for peripheral vrtc device

doc/release_notes/release_notes_3.3.rst
Delete the redundant field "Celadon" in "Enabling Celadon as User VM"
=> doc: modify v3.3 release notes

hypervisor/arch/x86/guest/vm_reset.c, hypervisor/arch/x86/pm.c, hypervisor/debug/shell.c, hypervisor/include/arch/x86/asm/host_pm.h
Service VM may write 0x6 to port 0xcf9 to trigger a warm reset, but current hypervisor always performs a cold reset by writing 0xE to CF9. Hypervisor should reboot the system in the same mode as Service VM specified. Specific OS features (like linux pstore) requires warm reset to keep data across reboot.
The behavior of hv console's reboot command (cold reset) remains unchanged.
Tracked-On: #8539
=> hv: handle reboot from Service VM properly

misc/config_tools/schema/config.xsd, misc/config_tools/xforms/config_common.xsl
For Service VM, the I/O APIC number and RTE number are from platform. Otherwise, hypervisor emulates one I/O APIC and 48 RTEs. But 'MAX_IOAPIC_NUM' is always 1 and 'MAX_IOAPIC_LINES' is always 120 for now.
This patch is introduced to fix these issues.
Tracked-On: #8725
Suggested-by: Junjie Mao <junjie.mao@intel.com>
=> misc: fix two IOAPIC related configs

hypervisor/arch/x86/guest/vm_reset.c, hypervisor/include/arch/x86/asm/guest/vm.h
hv: vm_reset: simulate RESET_CONTROL(0xCF9) register
Add reset_control in acrn_vm. Use this reset_control to simulate
RESET_CONTROL(0xCF9) register in hypervisor.
Tracked-On: #8724
=> hv: vm_reset: simulate RESET_CONTROL(0xCF9) register

CONTRIBUTING.rst
Change TSC Chair from Junjie to Yu due to job change.
Tracked-On: #8746
Signed-off-by: Yuhuanx Huang <yuhuanx.huang@intel.com>
=> doc: Change TSC Chair from Junjie to Yu due to job change.

devicemodel/core/hugetlb.c
During init of hugetlb we check and create /run/hugepage/acrn folder. Concurrent acrn-dm instances might race between the time of check and create.
This commit ignore EEXIST error when creating directory.
Tracked-On: #125284
=> dm: Fix concurrent acrn-dm hugetlb init race

hypervisor/arch/x86/guest/hyperv.c, hypervisor/arch/x86/guest/vm.c, hypervisor/include/arch/x86/asm/guest/hyperv.h
In current code process, hyperv data in struct vm_arch is never cleared during VM shutdown and is retained to next VM launch. As the enabled bit of hypercall_page msr is not clear, hypercall page might cause fatal error such as Windows VM BSOD during VM restart and memory remapping. Hyperv page destory function can ensure hyperv page is destory during each VM shutdown so hyperv related config such as hypercall page is established correctly during each VM launch.
Tracked-On: #8755
=> hv: hyperv: Add hyperv page destory function

misc/config_tools/configurator/packages/configurator/src-tauri/Cargo.lock, misc/config_tools/configurator/packages/configurator/src-tauri/Cargo.toml
upgrade openssl to 0.10.72
upgrade tokio to 1.43.1
Tracked-On: ACRN-12537
=> misc: upgrade two dependencies for acrn-configurator

misc/config_tools/acpi_gen/asl_gen.py, misc/config_tools/acpi_gen/bin_gen.py, misc/config_tools/board_config/board_c.py, misc/config_tools/board_inspector/board_inspector.py, misc/config_tools/board_inspector/inspectorlib/mmio.py, misc/config_tools/board_inspector/inspectorlib/validator.py, misc/config_tools/configurator/pyodide/loadBoard.py, misc/config_tools/configurator/pyodide/populateDefaultValues.py, misc/config_tools/configurator/pyodide/updateSchema.py, misc/config_tools/launch_config/launch_cfg_gen.py, misc/config_tools/library/launch_cfg_lib.py, misc/config_tools/scenario_config/config_summary.py, misc/config_tools/scenario_config/lxml_loader.py, misc/config_tools/scenario_config/scenario_cfg_gen.py, misc/config_tools/service_vm_config/serial_config.py, misc/config_tools/static_allocators/main.py
This patch is to fix Bandit scan issue b313-b320 which is vulnerable to XML attacks when parsing untrusted XML data.
I replace lxml.etree with the equivalent defusedxml package.
I confirm it works after making a Bandit scan, building the configurator and compiling the acrn.
Tracked-On: ACRN-10179
=> misc: Bandit scan issue for lxml

debian/acrn-hypervisor.postinst.in, debian/acrn-hypervisor.postrm.in, debian/acrn-hypervisor.prerm.in, debian/grub/25_linux_acrn
Calling debconf in grub script may fail when installing with dpkg as
debconf database might be occupied by dpkg, causing update-grub fail
with message below
```
debconf: DbDriver "config": /var/cache/debconf/config.dat is locked by another process: Resource temporarily unavailable
```
This patchset fixes issue above by creating a symlink to scenario file
at fixed path /usr/share/acrn/scenario.xml and let grub-acrn script
read scenario here so that debconf is no longer called.
=> Remove debconf call in grub script
